### ISSUE TITLE
Jenkins error rate is too high

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1005]
It looks to me like we're simulating reads with a 5% substitution rate:
https://github.com/vgteam/vg/blob/master/jenkins/vgci.py#L453

That's way too high for short reads--it's getting into nanopore territory. I think that's going to skew our results a lot.

**Comment by glennhickey** [comment]
Good point!  I would have thought those numbers were taken from
scripts/map-sim, but that has -e 0.01 -i 0.002.
