### ISSUE TITLE
vg map pacbio ccs reads - fails

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1078]
Hi,
I'm trying to map pacBio ccs reads to a graph using vg map and afterwards convert the mappings using vg surject.
`vg map -x $XG -g $GCSA -f $READ1 -K -j -t 32 -M 3 -w 128 -W 32 $GRAPH > $GAM`
When I use a single read everything works fine, but when I switch to the full fastq file the mapping works and I can get mapping stats using vg stats, but the conversion from gam to bam fails, as it claims, that SEQ and QUAL fields are of different length.

> [E::sam_parse1] SEQ and QUAL are of different length
> [W::sam_read1] Parse error at line 38

In my input fastq file the seq und the phred quality have the same length. I tried it with phred-64 and phred-33, both don't work for the complete fastq file. I don't know what is going wrong.

Thanks,
Chris

**Comment by edawson** [comment]
Hey @ChriKub ,

Why did you close the issue? Did you solve the problem?

**Comment by ChriKub** [comment]
I created another issue that explains the problem better.
