### ISSUE TITLE
vg map doesn't produce mapping quality scores

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#108]
There's a "mapping_quality" field in the Alignment message, but vg does not seem to use it.  This would be useful to have for variant calling.

**Comment by ekg** [comment]
I've applied neural networks applied to this in the past. They seem to work fine, although to generalize them properly they need to be trained on very general test data or retrained for each specific combination of genome and sequencing technology.

We could instead use something like the conditional probability of the kmers in the read ~ `P(kmers | reference)`. Thoughts?

**Comment by ekg** [comment]
The `P(kmers | reference)` makes sense, but requires keeping track of the number of kmers of a given length in the db. I guess this could be extrapolated for GCSA from the length of its BWT.

**Comment by edawson** [comment]
Duplicate[here]( https://github.com/vgteam/vg/issues/26)
