### ISSUE TITLE
XG indexing replaces lower-case sequence with 'N's

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#1119]
It appears that the XG index is taking lower-case letters in a fasta file sequence (which represents apparent repeat sequence) and replacing them with wildcard N characters. I'm not sure if this is intended behavior.

**Comment by jeizenga** [comment]
Yeah, that's not great. Is the pipeline FASTA -> VG -> XG, or is there a direct FASTA -> XG conversion I'm not aware of?

**Comment by cmarkello** [comment]
@jeizenga It's FASTA -> VG -> XG

**Comment by glennhickey** [comment]
vg construct gives (gave?) a warning for softmasked sequence.  but agreed
it'd be more intuitive to just convert to upper case rather than preserve
un-indexable symbols by default.

**Comment by adamnovak** [comment]
I think we should convert to upper-case and give a warning in vg construct. I will implement this this week.

**Comment by cgroza** [comment]
Hi, there is an issue related to this. If a VCF file contains variant calls with lower case REF sequences, vg construct will complain. Here is an example:
```
warning:[vg::Constructor] Lowercase characters found in chr1; coercing to uppercase.
error:[vg::Constructor] Variant/reference sequence mismatch: t vs pos: 40180775: T; do your VCF and FASTA coordinates match?
Variant: chr1	40180775	.	t	tGTTT	0	PASS	MTD=bwa_freebayes
zero ind: 40180774 1-indexed: 40180775
```
