### ISSUE TITLE
Debug Erik's mapper PR's vg call test

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1121]

**Comment by glennhickey** [comment]
It's worse than I thought at first glance.  Goes from 19 to 9 false
positives, which seems like a big jump.

Old

Threshold  True-pos-baseline  True-pos-call * False-pos*  False-neg
Precision  Sensitivity  F-measure
----------------------------------------------------------------------------------------------------
  164.000                154            153         * 9*          7
0.9444       0.9565     0.9504
     None                156            155         13          5
0.9226       0.9689     0.9452

New

Threshold  True-pos-baseline  True-pos-call  *False-pos * False-neg
Precision  Sensitivity  F-measure
----------------------------------------------------------------------------------------------------
  130.000                156            155        * 19*          5
0.8908       0.9689     0.9282
     None                156            155         20          5
0.8857       0.9689     0.9255
