### ISSUE TITLE
extract_connecting_graph step 2 mixes parts of different positions

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1130]
https://github.com/vgteam/vg/blob/6b0f4767392727cd0ac6cb315654cbd9b3f8d17b/src/algorithms/extract_connecting_graph.cpp#L263

This line mixes the ID of pos_2 and the orientation of pos_1 and that makes me super uncomfortable.

Changing it to be `id(pos_2), !is_rev(pos_2)` does not fail the unit tests, which also makes me uncomfortable.

@jeizenga Can you explain why it should be the way it is? Or should it be changed?

**Comment by jeizenga** [comment]
That very much looks like a copy-paste bug to me, and I think you've identified the right way to correct it. Strange that it wouldn't be caught in the unit tests though. It must be that all of the tests that follow this code path have both positions on the same strand.

**Comment by adamnovak** [comment]
I think this is fixed now.
