### ISSUE TITLE
Make the Cactus test on Jenkins good

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1147]

**Comment by adamnovak** [comment]
We could maybe do a simulation from ref and one of the alts on MHC, so that the Cactus graph will actually be useful.

**Comment by adamnovak** [comment]
Evaluating correctness when mapping to the primary reference is tricky.

**Comment by adamnovak** [comment]
We can use the Cactus alignment to define the correct part of the primary reference to map to for reads from an alt. If there's no aligned bases, we don't expect it to be possible to map that read correctly. We can mark it wrong, or we could remove it from the denominator.

**Comment by adamnovak** [comment]
@ekg How are you planning to evaluate correctness for reads that don't actually have a true mapping location in the reference you're mapping to?

**Comment by adamnovak** [comment]
Maybe we should be using alt-aware BWA as the control here. Which will probably win if we're just simulating from an alt.

**Comment by adamnovak** [comment]
@benedictpaten thinks we should target MHC and yeast here.

**Comment by adamnovak** [comment]
OK, here is my plan for how to get a better Cactus-based test:

- [ ] Modify vg sim to take a path name in the xg and simulate from it.
- [ ] Modify vgci.py to use the simulate-from-path functionality.
    - [ ] Alternately, extract individual names paths from the base graph as xg indexes and plug into the existing logic that lets us simulate from haplotypes represented as separate XGs.
    - [ ] Make sure simulated reads are annotated on all paths they touch.
- [X] Toil-vg should already annotate reads with positions on all the paths they touch in the main xg file used for alignment.
- [ ] Make mapeval handle multiple annotations cleverly: always take the reference path one, and ignore all the others. Right now it only takes the 0th annotation. Things with no reference path annotation can be treated as unmapped/censored for now.
- [ ] Create a Jenkins test that simulates reads from a couple of the alts, maps them to the graphs (including Cactus), and evaluates, of the reads that can be annotated with true reference positions, which are mapped correctly.
- [ ] Add alt-aware BWA-mem as a control. This will potentially be difficult because I haven't seen much documentation on setting up your own custom alt graph, and we would need to do one restricted to just MHC.
    - [ ] Make sure to surject/subset the alt alignments onto the ref path for comparison.
    - [ ] Alternately, add functionality to mapeval to compare positions on multiple paths and use that.

**Comment by glennhickey** [comment]
Looks reasonable to me.  Would be great to simulate from a sample and haplotype (something like vg find -q) directly in addition to paths, but not a priority as we already have a pipeline for this.  

I think we definitely want to follow up by using alt paths for comparison.  These can come from cactus or maybe from the VCF alts (via construct -a).  Then we can simulate a bunch of reads from known large insertions that have no reasonable reference positions (these exist even in the 1kg vcfs we're currently using), and see how well vg places them back on the graph.  This would put the focus on vg's strength when compared to linear methods, rather than ignoring it like we do now.

**Comment by adamnovak** [comment]
I'm going to kick this over to @glennhickey; he thinks this might look bad because `vg annotate` isn't working right on multiple paths.
