### ISSUE TITLE
vg map cheats on simulation tests

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#1182]
I've always assumed that vg map -G input.gam would completely realign the reads from the input alignments.  For one thing, our simulation experiments, where we pass in the simulated truth gam this way, don't make sense otherwise.  This doesn't seem to be the case though:

https://github.com/vgteam/vg/blob/master/src/subcommand/map_main.cpp#L983-L988

as it looks like the mapper is just passing through the input alignment if it can't find an alignment of its own.  

Is there a rationale for this behaviour?  At the very least, we need an option to disable it during simulation tests.

**Comment by jeizenga** [comment]
It was probably written to handle Alignments created from FASTQ/HTS records, which don't have the path filled in. We should throw in an Alignment::clear_path() at the outset to be safe.

**Comment by ekg** [comment]
Oh no! This is absolutely incorrect.
