### ISSUE TITLE
vg pileup fails

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1200]
Hi,
I created ccs read mappings against a vg graph and want to build a pileup from them in order to call SNPs. I mapped using `vg map -x graph.xg -g graph.gcsa -D -K -t 8 -M 8 -w 2048 -W 64 -f ccs_reads.fastq.gz graph.vg > ccs_reads.gam  2> ccs_reads.gout. The mapping works reasonably well:

> Total alignments: 35340
> Total primary: 9746
> Total secondary: 25594
> Total aligned: 5753
> Insertions: 4853233 bp in 48472 read events
> Deletions: 4741 bp in 2056 read events
> Substitutions: 345748 bp in 312070 read events
> Softclips: 5716524 bp in 19126 read events
> Unvisited nodes: 10649708/10920775 (262987740 bp)
> Single-visited nodes: 163722/10920775 (4159988 bp)
> Significantly biased heterozygous sites: 0/0

When I want to pileup the reads  using `vg pileup -t 8 -p -v graph.vg ccs_reads.gam > ccs_reads.vgpu 2> ccs_reads.vgpout ` I sadly get a error message for which I'm unable to find a setting that would fix it in the mapping.

> Reading input graph
> Computing pileups
> vg: src/pileup.cpp:183: void vg::Pileups::compute_from_alignment(vg::Alignment&): Assertion `node_offset >= 0' failed.

I am sadly unable to provide you with the graph I used as it is way too large, but you can find the GAM file [here](https://owncloud.tuebingen.mpg.de/index.php/s/VrstZWHxfNJLPmm) if it is of any help.

Until know I was able to produce one alignment from a different set, that I could pile up. Probably because the mapping did not create a weird node offset.

Is there anything I can do to fix this problem?
Thanks

**Comment by glennhickey** [comment]
Judging by the assert, it looks like it is hitting a (reversed) mapping
position in ccs_reads.gam whose offset is greater than or equal to the
node's length in the graph.vg.

The simplest cause would be an inconsistency between graph.vg and graph.xg
in your command lines (perhaps the .vg was changed after making the xg?)

To check this, you can stick an "if (node_offset < 0) {cerr <<
pb2json(mapping) << endl;}" right above the assert in question to print the
problematic mapping.  You can then use vg view to find the node_id in your
graph.vg to check it's length.

**Comment by ChriKub** [comment]
We updated to cbbdd7b6a734a1848e4466a0959bc7abc64d89c2 which fixed the problem.
