### ISSUE TITLE
Consult with Jouni about replacing our gPBWT implementation with GBWT

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1205]
How is construction going to work?

How do we have to feed in the threads?

When are we going to plug it in? Is that already done?

Can we port over everything we have that uses threads easily?

**Comment by adamnovak** [comment]
We also have to pull in Yohei's gPBWT-using read scoring code.

**Comment by jltsiren** [comment]
I have a VG fork at https://github.com/jltsiren/gbwt, where you can build GBWT with `vg index -x xg_file -v vcf_file -G gbwt_file`. Thread names are stored in the XG index, while the threads are in the GBWT index. By default, the construction scans the VCF file once for every 200 samples, but you can change the batch size with `-b`. I'm not sure whether 200 is the best time/space trade-off, but that made it possible to build the chr22 index on my 8 GB laptop.

[GBWT wiki](https://github.com/jltsiren/gbwt/wiki) has some API documentation, but I'm not sure if it's completely up-to-date. I'm planning to revise it before the next GBWT release. In particular:

* [Data Model](https://github.com/jltsiren/gbwt/wiki/Data-Model) has some general discussion about the assumptions.
* [File Formats](https://github.com/jltsiren/gbwt/wiki/File-Formats) contains more technical information. I'm probably going to move some of it elsewhere, as it may be necessary for understanding the other pages.
* [Identifiers](https://github.com/jltsiren/gbwt/wiki/Identifiers) describes simple mappings between integers and (id, orientation) pairs. The construction in VG uses `Node` mapping. If you get a path identifier with a `locate()` query, you have to use `Path` mapping to get the thread identifier used in XG.
* [Query Interface](https://github.com/jltsiren/gbwt/wiki/Query-Interface) documents the queries that I have implemented so far.

**Comment by glennhickey** [comment]
Thanks, Jouni!
(just seeing this now after my previous message in other thread)

**Comment by adamnovak** [comment]
Glenn says we are currently ~weeks away from being ready to merge in the GBWT.
