### ISSUE TITLE
Current install directions do not work on macOS High Sierra

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1209]
Apparently gcc 4.9 is incompatible with High Sierra, and that's what we have MacPorts installing.

**Comment by edawson** [comment]
Which version is installed by MacPorts on High Sierra?

Folks on institutional laptops may still be stuck on Sierra (source: I am still stuck on Sierra). GCC 5.4 or 6.2 would be kind of in parity with what most clusters have available.

Aside: I kinda miss Linux version fragmentation after dealing with OS X.

**Comment by jeizenga** [comment]
I have gcc7 installed now, but I'm not sure which one is default.

**Comment by glennhickey** [comment]
If it works on 7, maybe we can just change the README but add a note to
change 7 to 4.9 for versions older than Sierra.  I think it only comes up
in a couple commands...
