### ISSUE TITLE
Microsoft broke our tests

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1243]
The URL where the tidyverse Docker image wants to install `ggrepl` from (or the package index where it used to get ggrepl) no longer exists.

```
E           Installing package into '/usr/local/lib/R/site-library'
E           (as 'lib' is unspecified)
E           Warning: unable to access index for repository
https://mran.microsoft.com/snapshot/2017-09-28/src/contrib:
E             Line starting '<!doctype html><html ...' is malformed!
E           Warning message:
E           package 'ggrepel' is not available (for R version 3.4.1)
```

I think Microsoft moved `mran.microsoft.com` to `cran.microsoft.com`, and redirected some things, but not others.

This might be solved by updating the Tidyverse Docker image that toil-vg uses. @cmarkello?

**Comment by glennhickey** [comment]
It seems to be working okay now on a local test so maybe just a hiccup.
That said, there is now a newer image out (3.4.2) than what toil-vg
defaults to (3.4.1) (though they were both updated a few weeks ago)..

https://hub.docker.com/r/rocker/tidyverse/tags/

I'll bump up toil-vg to 3.4.2 anyway.

**Comment by adamnovak** [comment]
Microsoft has fixed their redirects, it seems, so now tests are passing on Jenkins again.
