### ISSUE TITLE
clang now supports openmp

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#1246]
https://clang-omp.github.io/

We might consider fully supporting our build using it.

**Comment by jltsiren** [comment]
From my point of view, the main issue with Clang is multithreaded sorting. GCSA2 construction gets much slower without it. GCC has multithreaded quicksort in the libstdc++ parallel mode, while there is nothing comparable in the Clang standard library.

C++17 execution policies would be the standard alternative to the parallel mode, but nobody really supports them at the moment. Meanwhile, if we are willing to require C++14, we could use https://github.com/SaschaWitt/ips4o instead.

**Comment by jltsiren** [comment]
I'm only using it explicitly in a few places, such as https://github.com/jltsiren/gcsa2/blob/master/include/gcsa/utils.h#L273 Defining `_GLIBCXX_PARALLEL` is generally a bad idea. Many STL algorithms are parallelized automatically, and the threshold for parallelization is quite low. If you have tens of CPU threads, the parallelization overhead can make things several times slower, if you call STL functions with small or medium inputs.
