### ISSUE TITLE
make cannot work

### ISSUE THREAD

**Issue by yangxiaofeill** [vgteam/vg#1296]
```
if [ ! -d bin ]; then mkdir -p bin; fi
if [ ! -d lib ]; then mkdir -p lib; fi
if [ ! -d obj ]; then mkdir -p obj; fi
if [ ! -d obj/algorithms ]; then mkdir -p obj/algorithms; fi
if [ ! -d obj/unittest ]; then mkdir -p obj/unittest; fi
if [ ! -d obj/subcommand ]; then mkdir -p obj/subcommand; fi
if [ ! -d include ]; then mkdir -p include; fi
if [ ! -d cpp ]; then mkdir -p cpp; fi
make: *** No rule to make target `deps/protobuf/src/google/protobuf/*.cc', needed by `.rebuild-protobuf'.  Stop.
```

when I run "make" command, it print message like above. How to solve this problem?

**Comment by subwaystation** [comment]
I have the same problem, but for `libgwbt`.

```
. ./source_me.sh && make static
if [ ! -d bin ]; then mkdir -p bin; fi
if [ ! -d lib ]; then mkdir -p lib; fi
if [ ! -d obj ]; then mkdir -p obj; fi
if [ ! -d obj/algorithms ]; then mkdir -p obj/algorithms; fi
if [ ! -d obj/unittest ]; then mkdir -p obj/unittest; fi
if [ ! -d obj/subcommand ]; then mkdir -p obj/subcommand; fi
if [ ! -d include ]; then mkdir -p include; fi
if [ ! -d cpp ]; then mkdir -p cpp; fi
. ./source_me.sh && cd deps/gbwt && make libgbwt.a && mv libgbwt.a /home/heumos/git/vg/lib && cp -r include/gbwt /home/heumos/git/vg/include/
make[1]: Entering directory '/home/heumos/git/vg/deps/gbwt'
make[1]: *** No rule to make target 'libgbwt.a'.  Stop.
make[1]: Leaving directory '/home/heumos/git/vg/deps/gbwt'
make: *** [Makefile:210: lib/libgbwt.a] Error 2
```

**Comment by glennhickey** [comment]
Have you (both) tried running git submodule update --init --recursive?
Looks like you may not have all the submodules downloaded.

**Comment by subwaystation** [comment]
I tried it right now. It works until:

```
[ 60%] Linking C static library libraptor2.a
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[ 63%] Built target raptor2
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
Scanning dependencies of target raptor_sort_r_test
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
[ 64%] Building C object src/CMakeFiles/raptor_sort_r_test.dir/sort_r.c.o
[ 64%] Linking C executable raptor_sort_r_test
libraptor2.a(turtle_lexer.c.o): In function `turtle_lexer_lex_destroy':
turtle_lexer.c:(.text+0x37c7): undefined reference to `yycleanup'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/raptor_sort_r_test.dir/build.make:97: src/raptor_sort_r_test] Error 1
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make[2]: *** [CMakeFiles/Makefile2:128: src/CMakeFiles/raptor_sort_r_test.dir/all] Error 2
make[2]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make: *** [Makefile:256: lib/libraptor2.a] Error 2
```
So `git pull` is not enough everytime. Which single command would make sure, that `vg` and all its submodules are updated? Thanks!

**Comment by subwaystation** [comment]
I got gcc 7.2. Just FYI.

**Comment by ekg** [comment]
@subwaystation did you manage to build from a fresh `git clone --recursive`?

I ran into this a few days ago and followed the same approach as @glennhickey's. This solved it for me.

**Comment by subwaystation** [comment]
@ekg starting with a fresh clone as you suggested, the problem with building raptor still persists....

**Comment by yangxiaofeill** [comment]
@glennhickey I tried use --recursive to download the full files, and it can make. However, when I run "./source_me.sh && make" command, there are error message like this: 
`libtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -I. -I./src -I./src -pthread -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -DNO_FRAME_POINTER -g -O2 -MT src/base/libtcmalloc_la-linuxthreads.lo -MD -MP -MF src/base/.deps/libtcmalloc_la-linuxthreads.Tpo -c src/base/linuxthreads.cc  -fPIC -DPIC -o src/base/.libs/libtcmalloc_la-linuxthreads.o
src/base/linuxthreads.cc:254:3: error: 'sem_t' does not name a type
   sem_t       *lock;
   ^
src/base/linuxthreads.cc: In function 'void ListerThread(ListerParams*)':
src/base/linuxthreads.cc:272:22: error: 'struct ListerParams' has no member named 'lock'
   if (sem_wait(args->lock) < 0) {
                      ^
src/base/linuxthreads.cc:272:26: error: 'sem_wait' was not declared in this scope
   if (sem_wait(args->lock) < 0) {
                          ^
src/base/linuxthreads.cc: In function 'int TCMalloc_ListAllProcessThreads(void*, ListAllProcessThreadsCallBack, ...)':
src/base/linuxthreads.cc:558:3: error: 'sem_t' was not declared in this scope
   sem_t                  lock;
   ^
src/base/linuxthreads.cc:558:26: error: expected ';' before 'lock'
   sem_t                  lock;
                          ^
src/base/linuxthreads.cc:588:8: error: 'struct ListerParams' has no member named 'lock'
   args.lock         = &lock;
        ^
src/base/linuxthreads.cc:588:24: error: 'lock' was not declared in this scope
   args.lock         = &lock;
                        ^
src/base/linuxthreads.cc:625:29: error: 'sem_init' was not declared in this scope
     if (sem_init(&lock, 0, 0) == 0) {
                             ^
src/base/linuxthreads.cc:643:23: error: 'sem_post' was not declared in this scope
         sem_post(&lock);
                       ^
src/base/linuxthreads.cc:669:26: error: 'sem_destroy' was not declared in this scope
         sem_destroy(&lock);
                          ^
make[1]: *** [src/base/libtcmalloc_la-linuxthreads.lo] Error 1
make[1]: Leaving directory `/opt/software/vg/deps/gperftools'
make: *** [lib/libtcmalloc_minimal.a] Error 2`

I don't why this errors.

**Comment by subwaystation** [comment]
@ekg even after switching to `gcc4.9` as described in https://gist.github.com/slizzered/a9dc4e13cb1c7fffec53, the same error still pops up:

```
-- Build files have been written to: /home/heumos/git/vg/deps/raptor/build
make[1]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[2]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[  1%] Built target turtle_tables_tgt
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[  3%] Built target turtle_parser_tgt
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[  4%] Built target turtle_flex_tgt
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[  4%] Built target turtle_lexer_tgt
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[  4%] Built target parsedate_tables_tgt
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[  6%] Built target parsedate_tgt
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
[ 63%] Built target raptor2
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make[3]: Entering directory '/home/heumos/git/vg/deps/raptor/build'
[ 63%] Linking C executable raptor_sort_r_test
libraptor2.a(turtle_lexer.c.o): In function `turtle_lexer_lex_destroy':
turtle_lexer.c:(.text+0x37c7): undefined reference to `yycleanup'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/raptor_sort_r_test.dir/build.make:97: src/raptor_sort_r_test] Error 1
make[3]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make[2]: *** [CMakeFiles/Makefile2:128: src/CMakeFiles/raptor_sort_r_test.dir/all] Error 2
make[2]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/heumos/git/vg/deps/raptor/build'
make: *** [Makefile:256: lib/libraptor2.a] Error 2
```

Do you have any suggestions? Thanks!

**Comment by adamnovak** [comment]
@yangxiaofeill: You appear to be missing the type `sem_t` from `<semaphore.h>`. Can you compile and run a test program like this?

```
#include <semaphore.h>

int main(int argc, char** argv) {
    sem_t test;
    return 0;
}
```

Or can you make the example program from http://man7.org/linux/man-pages/man3/sem_wait.3.html work?

What compiler version are you using?

@subwaystation: it looks like you are having trouble building the lexer that Flex generated, for parsing Turtle files, as part of the Raptor build. Flex (and Bison) are part of the dependencies that vg doesn't ship. Did you install them in a particularly interesting way? What versions are you using? I have Flex 2.5.39 and that works for me.

I think `yycleanup` is actually supposed to be defined by the generated C code that Flex makes. If it existed it would be in `deps/raptor/build/src/turtle_lexer.c`. Does that file define or call `yycleanup`? My copy doesn't have it or try to call it, but some Flex parsers like https://github.com/leafo/goattracker2/blob/master/src/asm/lexyy.c seem to want it.

**Comment by subwaystation** [comment]
@adamnovak 
Let us continue this discussion in #1235.
