### ISSUE TITLE
Add trained vs. Erik simulator comparison to compare-graphs.sh

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1311]
We want to compare the speed of mapping reads from each simulator.

**Comment by glennhickey** [comment]
I think we can quickly get at this from consecutive runs, as both types of simulated reads are on S3.  What we're missing is some real reads.  Maybe compare-graphs.sh isn't the right place to get the times (in absence of anythign to compare to), but we can put something together to do mapping only either as an option or another script.
