### ISSUE TITLE
xg indexing is crazy expensive for tiny subgraphs

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#1322]
If you have a big graph then make a subgraph for it, you end up with a node space from `[1-max_id(graph)]` that's mostly empty. This causes problems for xg. Here is an example graph. It needs several G of RAM to build, but it's only got 14 nodes and is 444bp long.

```
{"node": [{"id": 306128489, "sequence": "CTGAATGTTTGTCTGTCACAAAGGATTCCAGA"}, {"id": 306128490, "sequence": "GCACTGCTGCTATGGTCTACATGTATGTCCTT"}, {"id": 306128491, "sequence": "CACATAGGATTCCAGAACACTGCTGCTGGGTT"}, {"id": 306128492, "sequence": "CTGAGTGTTTCTCCCTCACATAGAATTC"}, {"id": 306128488, "sequence": "CACACAGGATTCCAGAACACTGCTGCTGGGGT"}, {"id": 306128487, "sequence": "ACACTGCAGCTGGGGTCTGAATGTTTGTCCCT"}, {"id": 306128486, "sequence": "CTTTATGACTGTCCATCACATAGGATACCAGA"}, {"id": 306128485, "sequence": "CACAAAGAATTCCAGAACACTGCTACGAGGGT"}, {"id": 306128484, "sequence": "TCACTGCTATGAATGTCTGAATGTTTGTCCCT"}, {"id": 306128483, "sequence": "CTGAATGTTTGTCACTCACATGGGATTCCACA"}, {"id": 306128482, "sequence": "CACAGGGGATTCCAGAACACTTCTGCTGTGGT"}, {"id": 306128481, "sequence": "ACACTACTACGAGAGTCTGAATGTTTGTTCCT"}, {"id": 306128480, "sequence": "CTAAATGTTTGTCCTTCAAATAGGATTCCAGA"}, {"id": 306128479, "sequence": "CACATAGGATTCAAGGACCCTGCTGCTGGGGC"}], "edge": [{"from": 306128489, "to": 306128490}, {"from": 306128490, "to": 306128491}, {"from": 306128491, "to": 306128492}, {"from": 306128488, "to": 306128489}, {"from": 306128487, "to": 306128488}, {"from": 306128486, "to": 306128487}, {"from": 306128485, "to": 306128486}, {"from": 306128484, "to": 306128485}, {"from": 306128483, "to": 306128484}, {"from": 306128482, "to": 306128483}, {"from": 306128481, "to": 306128482}, {"from": 306128480, "to": 306128481}, {"from": 306128479, "to": 306128480}], "path": [{"name": "GL000205.1", "mapping": [{"position": {"node_id": 306128479}, "rank": 5443}, {"position": {"node_id": 306128480}, "rank": 5444}, {"position": {"node_id": 306128481}, "rank": 5445}, {"position": {"node_id": 306128482}, "rank": 5446}, {"position": {"node_id": 306128483}, "rank": 5447}, {"position": {"node_id": 306128484}, "rank": 5448}, {"position": {"node_id": 306128485}, "rank": 5449}, {"position": {"node_id": 306128486}, "rank": 5450}, {"position": {"node_id": 306128487}, "rank": 5451}, {"position": {"node_id": 306128488}, "rank": 5452}, {"position": {"node_id": 306128489}, "rank": 5453}, {"position": {"node_id": 306128490}, "rank": 5454}, {"position": {"node_id": 306128491}, "rank": 5455}, {"position": {"node_id": 306128492}, "rank": 5456}]}]}
```

**Comment by adamnovak** [comment]
Didn't we used to have an offset that we used when converting node IDs to ranks? Did we change all that when we moved to the g vector?

**Comment by ekg** [comment]
I guess that's what's going on? I haven't looked into this recently. Perhaps we need an initial offset to handle this.

**Comment by JervenBolleman** [comment]
Might also be interesting to see if [CRoaring](https://github.com/RoaringBitmap/CRoaring) bitmap/bitsets might help these kind of bad sparse bitsets.

**Comment by ekg** [comment]
(I'm working on the mappering branch, xg version 8.)

This is the xg index memory breakdown of a typical graph, the 1000G test included in the repo:

![z xg memorysun](https://user-images.githubusercontent.com/145425/36842946-46ee60be-1d45-11e8-9571-d092fd42fdf9.png)

This is the same breakdown for graph I posted here:

![big xg memorysun](https://user-images.githubusercontent.com/145425/36842895-19985c28-1d45-11e8-846c-d9246e9131df.png)

So there is a bv that's getting allocated in the path which is `O(max_node_id)`.

**Comment by ekg** [comment]
The node ids in the wavelet tree are being stored in `sdsl::wt_gmr`. I'll test other types to see if it improves things.

**Comment by ekg** [comment]
I changed the wavelet tree to `wt_int`. This looks more like I'd expect.

![big xg memorysun wt_int](https://user-images.githubusercontent.com/145425/36846131-55283b58-1d51-11e8-916f-96def64d91f6.png)

The index of the attached graph is no longer 90M (!!!!) but 9.1K. Now to check that this doesn't break anything.

**Comment by ekg** [comment]
Changing things to `wt_int` does resolve the construction cost problem for small graphs. However, it comes at a huge cost in terms of access performance, and this slows down `vg map` by a factor of 2x!

I found that I am able to resolve the problem by generating a local id space for each path where we number the ids internally from 1 and can translate between the external and internal id spaces by remembering the minimum id for each path.

The result is roughly the same in terms of space allocation:

![big xg memorysun wt_gmr id_trans](https://user-images.githubusercontent.com/145425/36861833-0016ed7c-1d7d-11e8-8fdf-a7f282c049e7.png)

I'm fixing this up now and working through the tests.
