### ISSUE TITLE
Connect haplotype information to mapping

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1331]
When available, it should impact a read's alignment score.

**Comment by ekg** [comment]
The simplest version of this is to just need to add a penalty for non-concordance with known haplotypes, the recombination penalty. If we can't look up the path of the read, then we apply the penalty.

**Comment by adamnovak** [comment]
I can make that happen in the multipath mapper on the final single-path alignments, but because it's a *multipath* mapper I think we need to do something more complex if we want it to actually matter for alignment selection.

@jeizenga Do you have any ideas as to how you would want the haplotype information to factor into the multipath mapping process?

While we think about that I can go ahead and implement this in the single-path mapper.
