### ISSUE TITLE
Make a command that converts a .xg into a .vg

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1337]
Maybe make it live in `vg xg`?

**Comment by ekg** [comment]
I am also interested in this. It should be noted that you can work around this using the `-r` node range flag and the context expansion option `-c`. You just need to specify a range that's bigger than that of the graph.

```shell
vg construct -r 1mb1kgp/z.fa -m 32 -p >z.vg
vg index -x z.xg z.vg

vg find -c 1 -x z.xg -r 1:10000000 | vg stats -lz -
#nodes   31250
#edges   31249
#length  1000000
<z.vg vg stats -lz -
#nodes   31250
#edges   31249
#length  1000000
```

Hacks. :fork_and_knife:
