### ISSUE TITLE
Let me see the stderr output from the vg command in the Jenkins tests

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1338]
This would make my life way easier. Using the RealTimeLogger in Toil requires a lot of extra steps to even find where I need to add debug statements, and even then gives me less access to the fine grain operations in vg.

**Comment by glennhickey** [comment]
I think this needs to be done in toil-vg.  The ContainerRunner class could be modified to always collect stderr (maybe as an option) and send that out using the RealtimeLogger.
