### ISSUE TITLE
kmer generation is horribly slow

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#1345]
The kmer generation algorithm is nightmarishly slow. There seem to be many reasons. I'm going to rewrite it now that we know how it will be used.

**Comment by jeizenga** [comment]
Is this the one that's living the VG object right now? If you're already ripping it up, I've been thinking for a while that it should live somewhere else. The VG object seems to have a lot of bloat in general. What would be really cool would be to do it with the HandleGraph interface.

**Comment by ekg** [comment]
Yeah, I definitely think we should do it with the handlegraph interface. That way we just need to get to an XG index and we can do the kmer generation. This would also limit the maximum memory requirements of all the pipelines (provided we can be a little more clever about our XG construction).

**Comment by adamnovak** [comment]
I think we have a student (Emily Kobayashi) who wants to work on basically this project.

**Comment by ekg** [comment]
I've fixed this. It's pushed to the pangenome branch, but I suspect will fail tests at present. Before merging I'm going to get rid of all the other old kmer generation stuff. It's also not yet set as the default method in the external interfaces, which I did for testing but is easy to fix now.

It's much faster (20X) than the old code:

```
erik@tappy [06:49:00 PM] [~/vg/test] [pangenome *]
-> % time vg kmers -z -B -g -k 16 z.vg >/dev/null
vg kmers -z -B -g -k 16 z.vg > /dev/null  4.76s user 0.06s system 311% cpu 1.549 total
erik@tappy [06:50:15 PM] [~/vg/test] [pangenome *]
-> % time vg kmers -B -g -k 16 z.vg >/dev/null
vg kmers -B -g -k 16 z.vg > /dev/null  118.08s user 0.20s system 385% cpu 30.670 total
```
