### ISSUE TITLE
tutorial problem: 

### ISSUE THREAD

**Issue by colindaven** [vgteam/vg#1351]
Hi,

I am having problems running the last part of the human genome variation tutorial https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph. 
Specifically, the section "Indexing with xg and GCSA2" is not completing and I cannot create a gcsa index.

Has this been tested recently with the modern codebase - versions below.

Thanks
Colin

vg version 

```
vg
vg: variation graph tool, version v1.6.0-89-g5538a36

usage: vg <command> [options]

main mapping and calling pipeline:
  -- construct     graph construction
  -- index         index graphs or alignments for random access or mapping
  -- map           MEM-based read alignment
  -- call          call variants on an augmented graph
  -- augment       augment a graph from an alignment
  -- help          show all subcommands

For more commands, type `vg help`.
```

This is the stack trace I am getting.
```
Manual stack trace:
Stack trace from backtrace() for signal 6:
[0x87061a]
=================
[0x870971]
=================
[0xc52cd0]
=================
[0xc52c99]
=================
[0x107cf3a]
=================
[0xfb03ad]
=================
[0xfa5b76]
=================
[0xfa5bc1]
=================
[0xfaf549]
=================
[0xf64a90]
=================
[0x112f402]
=================
[0xc8d1ff]
=================
[0xcb36db]
=================
[0xcb6b97]
=================
[0xcb8d22]
=================
[0xc7faeb]
=================
[0x76af37]
=================
[0x7b8a28]
=================
[0x404cba]
=================
[0x106c626]
=================
[0x106c81a]
=================
[0x4b8a89]
=================
```

**Comment by adamnovak** [comment]
I don't think that that has been tested recently, but it also should not result in a segfault even if the command line options have changed.

Were you running the `vg index -x wg.xg $(for i in $(seq 22; echo X; echo Y); do echo $i.vg; done)` command? Is that backtrace the entire output, or is there an assertion failure message?

That backtrace looks extremely sparse; are you using a static or debug-stripped binary? Can you try updating to the current master and doing a `make clean-vg` before rebuilding? Since about Friday I just pushed up code that should improve the backtraces, by changing the way the binary is linked.

**Comment by colindaven** [comment]
Thanks for the reply. Yes, I was running the `vg index -x wg.xg $(for i in $(seq 22; echo X; echo Y); do echo $i.vg; done` packaged in a shell script.

I did not compile myself, this is the bioconda version which I guess is a binary. I will compile the latest version myself and report back.

**Comment by ekg** [comment]
Did your recompilation fix the problem? I'm impressed that vg is in bioconda. Does anyone know who the maintainer is?

**Comment by colindaven** [comment]
My mistake. vg does not yet seem to be in bioconda although has been discussed here:

https://github.com/bioconda/bioconda-recipes/pull/5086

My pull and compilation was quite recent (dec 21) but I will recompile and have another crack at it

**Comment by colindaven** [comment]
I recompiled on a new 512GB Ubuntu 16.04 server which I just access to. The older server had a _very_ old GCC etc which probably led to the issues, but it was the only server at that point I could use with 256GB+ RAM. 

Happily, the entire tutorial runs through just fine now.

Thanks for the help.
