### ISSUE TITLE
Merge GBWT-mpmap into master

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1354]

**Comment by ekg** [comment]
Is there a function in GBWT that allows checking the frequency of a given haplotype? If so then there is a five line chunk of code that we can add to the mapper to provide haplotype panel awareness to its scores.

**Comment by adamnovak** [comment]
I've been working on that for the normal mapper, actually. It's turned out
to be a little more than 5 lines, because I want to adjust the scores of
all the mapping locations of the read, and because some mapping locations
can't be correctly scored yet. But it's in there right now if you provide a
GBWT file that was generated along with your xg.
