### ISSUE TITLE
Support traversals that are longer than the read length in vg genotype

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#1357]
This is necessary to, say, call large inserts.  Will need, at the very least, :
* Better traversal finder.  Ideally, a generalized version of ReadRestrictedTraversal finder that can handle overlapping reads when deciding if a traversal is supported
* Modifying the affinity getting functions to be aware that a given read only maps to part of a traversal

**Comment by ekg** [comment]
:+1:

**Comment by ekg** [comment]
How's this going? I think @edawson will be interested.

**Comment by glennhickey** [comment]
I just merged a patch that lets genotype try to call longer sites with its
existing logic.  Still a work in progress,  but would be very interested in
how it does on @edawson's data in its current form.

**Comment by edawson** [comment]
Awesome! I'll rebuild and give it a go.
