### ISSUE TITLE
Check per-sample read generation logic

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1360]
We synthesize reads from the gPBWT for the tests, but I think we're only using the first fragment of each haplotype. We should make sure/assert that there are no other fragments of those haplotypes in the index, to avoid simulating reads from just the very start of the graph all the time.

**Comment by glennhickey** [comment]
I haven't had a chance to look closer yet, but I've noticed that the
chrom21 calling results on the simulated reads are pretty lousy across the
board (including bwa/freebayes).  Could this be related?

**Comment by adamnovak** [comment]
It could be. We would expect a whole bunch of false negatives (or maybe
hets seen as homozygous) all near each other if this were the cause.
