### ISSUE TITLE
`vg view` into JSON format from *.vg 

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1366]
Apologies if this is in the documentation:

I would like to convert my `example.vg` graph into `*.json` format. The example commands in the README for this is:

    # json version of binary alignments
    vg view -a x.gam >x.json

So, it looks like one needs to convert a `*.vg` file into `*.gam` format. 

How does one do this?

**Comment by ekg** [comment]
You need to use `vg view -j example.vg >example.json`.

**Comment by evanbiederstedt** [comment]
Thanks!

**Comment by evanbiederstedt** [comment]
Is it possible to make the above more clear in the README?
