### ISSUE TITLE
data: URLs passed to HTSlib need to be URL encoded and aren't

### ISSUE THREAD

**Issue by srmcgee** [vgteam/vg#1388]
Hello, 

I am running vg surject on a *.gam file with the following command:

vg surject -x my.xg -b my.gam > my.aln.bam

and I am getting the following error:
```
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 4
[vg::alignment] Failure to parse SAM record
data:,@HD	VN:1.5	SO:unknown
@SQ	SN:4	LN:191154276
@PG	ID:0	PN:vg
C6F0DANXX:4:1103:20530:30100	69	*	199080457	0	*	=	199080457	0	ATCGGGCCGGTAGCAGGGGTTAGGGCAGGCGTCTCTGTAGGGAGACACCCGCCCGCTATGGCTGGGCGGGTGCCCTCAGGTCCCTCGCCTCGGGCAGCGG	87%32.+6(-657@<:?@C.6,/78+-77:65?A?>################################################################

Got signal 11Got signal 11
Manual stack trace: ...
```

Though the SEQ and QUAL strings appear to be the same length. And when I look in the fastq files at this read location, I don't see anything unusual:
```
-bash-4.1$ grep -A 4 "C6F0DANXX\:4\:1103\:20530\:30100" bams/109108_1.fastq
@C6F0DANXX:4:1103:20530:30100
ATCGGGCCGGTAGCAGGGGTTAGGGCAGGCGTCTCTGTAGGGAGACACCCGCCCGCTATGGCTGGGCGGGTGCCCTCAGGTCCCTCGCCTCGGGCAGCGG
+
87%32.+6(-657@<:?@C.6,/78+-77:65?A?>################################################################
@C6F0DANXX:4:2202:12845:93381
```
(the gam file is generated with the command "vg map -f read1.fastq -f read2.fastq -x my.xg -g my.gcsa -k 22 > my.gam") 

The same error also happens when I attempt to map and surject directly from a BAM file (with vg map -b my.bam ... > my.aln.bam)

The graph (*.vg) I'm mapping to is based on all of chr4 but built with a VCF from just two gene regions.

Please let me know if you need more information.

Any assistance in this is greatly appreciated. Thank you. 
Sean

**Comment by wheaton5** [comment]
I am having the same issue.

[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 4
[vg::alignment] Failure to parse SAM record
data:,@HD       VN:1.5  SO:unknown
@SQ     SN:3L   LN:1000001
@PG     ID:0    PN:vg
HS20_08149:5:1101:3153:19363#49 133     *       19064729        0       *       =       19064729        0       GATCGCGGACGAGGAGAACAGAAAAAGGGGCCGGGTCCCTTTATTTTTGGTCGCCGTGGGCACGACCCGCCCACAAGCCCGCCATCCCCCCCCCCAATCG    8BAD=@;-A)(D..(.%'&'B'(('(('+-'&'''%7+'56%$%'+('''''''$+''%',+%%66D,+'9'',6%'+**''!'+@*+($?3*4+5(&+&

**Comment by ekg** [comment]
Something appears to be wrong with the quality string, and it's triggering this check in htslib: https://github.com/samtools/htslib/blob/develop/sam.c#L1283-L1285

@wheaton5 @srmcgee do either of you have the original read from the fastq handy for these failures? Something is not right with how vg is handling the qualities.

**Comment by wheaton5** [comment]
@HS20_08149:5:1101:3153:19363#49
GCCGTTCTTCTATCGCGATCCGAACGAAGACATCCAGAGCCCGTACGTGTGCAAACCGTGCGACTGTGATCCACGTGGCTCGCTGGACGATGGCATCTGC
+
B@DFEEFFFDFFFGFGFGHCIFGHDGGHFGCGGGKGGGGFGHFEGHGHEGHFGGHFFFCEGGFGFG<CGCFF-HFDDCGBDAF,FA7CF29;;B.6:7G3
@HS20_08149:5:1101:3153:19363#49
GATCGCGGACGAGGAGAACAGAAAAAGGGGCCGGGTCCCTTTATTTTTGGTCGCCGTGGGCACGACCCGCCCACAAGCCCGCCATCCCCCCCCCCAATCG
+
8BAD=@;-A)(D..(.%'&'B'(('(('+-'&'''%7+'56%$%'+('''''''$+''%',+%%66D,+'9'',6%'+**''!'+@*+($?3*4+5(&+&
@HS20_08149:5:1101:3153:85309#49

**Comment by wheaton5** [comment]
But the * character (ASCII 42) should be an accepted quality score, right? Anything from ASCII 33 to 93 (tho above 73 shouldn't occur from a raw read as phred 40 is max qual for illumina) should be legit?

**Comment by ChriKub** [comment]
Hi,
I have the same problem. I uploaded the data to reconstruct this error [here](https://owncloud.tuebingen.mpg.de/index.php/s/D9ZHUdw5BI4FQ1C). I have my PacBio ccs reads stored in a bam file.

`vg construct -r Sequence.fasta > graph.vg`
`vg index -x graph.xg -g graph.gcsa -k 16 graph.vg`
`vg map -x graph.xg -g graph.gcsa -b reads.bam > test.gam`
`vg surject -x graph.xg -s test.gam > test.bam`

```
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 4
[vg::alignment] Failure to parse SAM record
data:,@HD       VN:1.5  SO:unknown
@SQ     SN:TAIR10_Chr4  LN:7227
@PG     ID:0    PN:vg
*       0       TAIR10_Chr4     4440    60      9S275M1I39M3I59M1I14M1I6M1I6M1I30M3I16M1I37M3I10M1I9M1I23M1I29M2I19M2I7M1I53M1I19M1I13M1I67M1I34M1I60M1I64M1I145M1I214M2I160M1I13M1I85M1I21M2I32M2I14M2I10M1I15M1I17M1I6M1I11M1I45M3I35M1I14M3I26M1I41M1I52M1I31M3I54M1I11M2I12M8I20M2I26M3I24M3I18M1I33M1I99M2I38M1I2M1I6M2I2M1I85M1I24M1I32M1I20M1I27M1I164M2I12M1I83M1I34M1I21M166S      =       4440    0       ATACCACTCTGCACCTTGCCGTCATGAACTGGGACTTTTACTCCATTACTTGTCTTGCTAGCCGTAACTGCGAGATACTGAACTTACGAAACAAAAGCGGCTTAAGAGCTAGGGATATTGCCGAGTCAGAGGTGAAACCCACTACATCTTTCATGAGGTATTTCTGATTCCGTTTCATACAACACATTTGATCCCTCATAAATGATTTATAGTTGGACCTCCATATTTTTGGAATTACAGAGGTGGACACTGGCGCTCTTATTATACGCTATTCACTCAAGTGGTTTTCGAATCTGTTAAGTCATTAACAATACTGTCAGAGCCACTACTAGACCCTAATAATAACAGACATTACGTCAACGCTCTTCTCGTGGTAGCGGCTCTTGTTAGCCACAGTGACGATTTGCTGGCAGGCTTTTACATACCATGTGGTTCTATCAGCAGAGTGCCAACACAACAAACTTGAGGCAGGGCAACTTTGGACACTAACCCAACTCTCTTCAGATTTATCCTGCTATTTTGACTCTTTGGCAATGCAAAGTTCTGTTGCTAACAATATGTACTCTATTTGGGCGCAGTTGGGGGTGATCCAGCACTCATCAGCACAAATACCTTACATGTGGCCTTGCCCTTACTACTTTTTCATTACTATGCATGCACCTGGCCATTCCTTTTTGGCGTGATCCACTGCAATTGCCACATGTGACATGGCTTTTAGTCACCATTAGCATTATATCTGGTGGATTCTTCCTTTGCACAATCTTTAGTCCTTGGCCCTCACGTCATGCTACAGCGGTCATAGCCTTCCGCCAGTGCTGGTATATATCTCAGGACTTTGATGCTGACTATAGACATATCTGTGTTTTTTTGTGCGTTTGATCAAAGCTTGTTTTGGTTGTGTGGCGTGTGAATAAATCATCAAAAGTTGTATAGTTCAAAGGATATGTTTCTTCTCTTTTTTTTTCTTTCAAAAAGCTACGAGATATGCTGGTCTCTCTCAGAAGCGGCATCTTGATCATAGAATTCATTCGAAGTCCTATCAGAATTATCTGTAGTTGTAATAAAGCGTGAAAGAGTATATCATTCGAAGAAAGTTCCTCTAAAATAATGGAGTGATATTTATTATTCGGTTTAGTGGATACCAGTTACTTATCTCTCGAATTTATGAACCAATTCCAAGGAGATGAGTTTACAAAAAAAAGGTAAATTGTTTTTTATTCTCGTCGTGCGTTCCACATGAGTCGTTTCCAAGAGCAATATAGACGATACTTCACAAGAATTATTATTTTGTTGGTGGGATATAAAAATTTGAAGATACGTTTGGCAACGACAATACGACGTTAGATTGTTCCAAGAGGTGCAAAACTTAGGGACCCTCTTTATTCGTTCACTGTAACCATCGACCACAACATGACTAGGTAGACTCTTCTTTTGGTCAATGTGATGTTTATTACGATTTTGATGAAGACTGGCTCTATCAAGATATGAATCTCTGATCATATCTCCACTAATCTTCATCTGTTATTCCCTCATTTACTTTGATTTCCTTCATCGCTCTCTCTTTTTATGTATTATCAAATTTTTCTTTATTTCGCTTCACTAAACCCACCCCCATGTAATTGCTCGTGAGTTTTGGGCAGAGTGGCGCAACCACCGTAGAGCACACCACACCTAACCCCAATCCATTATTATGACCGTAATTTGTGGTTGATTAGTGTATTTTTTCTTGTTAGATTGTATTCTGAGAAGTAAATTTGTTTTTTACAATTAGTTTTTTAAACATAGTACCAATAGAATTTTATGACAGATTATAATCATTATTTTAAAAATCAATAATATCTAACAAATTAATAAACACAATCACAAATTACTATATTTTAAATAAATATTGATAATTTTAATTATATTATGTTGGTTTATTGGTTAACTCGCAGGATATGCGAGTAGTTAATTCATTTGAGATGGTAATCCTCCATATACTAACGCGATCACCCTGACTCTTTTAGACATCCTTAATAGTATAACAGCTATAACCTATAAAAATAGATTATGTTCCAAACTCGCGGATTCTAAACCTGAATTGATGACATGGCGGAACCATTCATAAACCTACCACAATTCTTGCGTTTGGGGAAAGTTGGTTTCCTTTTCATTTCTTTGAATGTTGATCCTAGATTGTGTAGTTCTCAAGCTCATGCTCTTGCTCGTCAAATACGTATCAACGATTTGCTTTTCCTTAGACGTTCTTGCATCGGATTGGTTTTAACTCAACTCCACTCGATGAAAAATGTACTATCTTAAAACAGAAACAAAGCTGCCAACTTCAATAAATTCCCAATATCTACGCATGAAAATATGATTCTGTCTTTTTTTGTTGTCTATCTTTCAATACTTTAAAAAGTGATATTTATAGAGGCGATTTGTCCTTGGCCCGATAGGAATTTGAGTAAAAAACACTCTGATTGTATATTTCCACGAATATCCAAATCGGCGAATATGGTTCCCACCATGTCTTAGCTCCTTGTCGTCACTCGGAATTTTTTAAATAATAGGATCGCTTTAATAATATAATCTCTATAATTTATAGTTCCTTTTCAATATTGGCGTCTCCGTTGAAGCTTTCCACAAATCTCAAATTTGTTGCGAGACTCTCAAATGTATCTCTCTCGACGATGATATTACGTCTCTGAATTGGGTTTGCTTCGATCAAAGGGTCGTCCTTCGCACTCTTCTCTGCCTTCACCTCCTCTGTTTTCTCTATCTCTTCGATTCAGGTTGTTTATCGAATTTGATCCCTTTTTCAATTGCAAAAATCATATCTTAATGTTCACATTCGAGTTCTGTGAAAAGTGTTGTTGGTTTTTCGCATTGCAGGGGAAAGGGTTGGTCTTTGATGACTACTTTGACGAACCCTAATGTATCAGAGTGTCTAAATGAATAGGAAGACAGAAAGTAGCTTATGGATGTTGTTGGTTATAAGTTACTCCTATATGATG    8D1*<--13=,85?T+VI>XBOPH<M@]N;+UA6:+EH4,J=BN<2K0%2A@IH4+BE@,85G=M5X@FNQNKKJ>=7EN4U2*JGPL1G/2&2HK),8YI;W?]KIILI@;M33IGBWC:$5@DON=DJ,VBA$IC3>&(0<9;4E86>?EHAL6<5E8//A8G=?+A6MK2JGNHNJL.aI?>1'OD7KF/@C>B&F3L+<L9,XJBMF).5&3*5:@BS@<:,JKZN4U?\C[KG)JB7AH*?KOKL4;X=JN75$0F8@1=HO@EMI9RBD@MK1SA<2K2EBPO85DBE53(@8J5I:D3H>W==L=>-B6JF9KB=6572LB@;DGC4=D83YM4HA-B@<EA1=8LJO23L%XB9I4-9PG=4@.-K9;(CAU&.A;RM$<;&*4;C@>C9EPM&9BN<NI&BRG%5G+[I957%5HA;9F%>2<?K@2<MK<GJ'6'/2I?J0M--'2.&$75:'G3+(Z<0(<=N3B-%6-/V$&(60%-1GH&3716/,.1:(-@7KM+;BJ86=)*($7C75<+06P<)5)/@58=/UXJ8<'3E3=BA(8DG6J<9>@27GL7$G77<,3/&CG54.*$5*9NEHK3>V;E(BE?OHJD+LL9$1[ZM3/Q/IC+4CKL1HDU>G27JMAJ:<JI1%FGHL46*-EGIHB9&A<J:(51$,H$8?5C.2/NXL>2E353(?,1;544(M0B5\J0T&68@J2:*%156LO0\TRG16<.%@HFZHK@D7E77C&:J@O>)CA/WM6B;K/KEA=&'#2FO*WJG$A3L.23K<DEPAIBAOH-LMN<;OE3P1B5:HLG);P7O4<:$>C=:7?6?LC+C42242GCG@]KN)E?$;6)7:?7.0F%HJKPFN9MOB&32&8*9?0&%>,L<8MB91LP8X1GK5;;1DEA012)55,*.:968<?;<RN,``PPJOP4^VEF@V()<9E05*$/UH4U4H;?40LO?C[NM4&LOGFH@=EF6LIO'>NI>@9KGQMJJD2FICM8*LKG?IG?M:738K-C'R<DNKAZN9L69?.@-.>GN=C@<C/VJPBLNH=PD9>B.?HH%1*=HC2I5EAQ4,D?/K170+BJ2A(F7L2KQDC.4K;<L%=N/'C/YMOL%Y?MO3CM?J3%KN@B0%RU7>I79L@@[/G@D9H.@H=DBO66)IBQCW?07:HAH6>49OCF88?Q1?0$<P>K9[:UA:;5%I5,FF,8%JSMQZ\N8YN-QPDNC&N8;>7<9ODKKGQMHH6PG-T'P<.5646;75+(EE4;8?GF7?.:91A0K:K*2NDECWB3;5F4=X3T>>GF%HJK5$8&:&&GD%'5((9,5>*LNM0=LH>>PG/Y4,N;?PK&KP?RMJQNKPM@VJCI/NB-M1G<]MG8UMNO%]QMC:MF'P<<6>EL&/?-46;K3@WH/JLBO<QCE34%-:8K4H5<GEK8J,8:-GE80INMN7I9)ILA$;KN3K<&47B;J,KB6'72/HH+*14J/-''9E1-H7?>KNKJNO7PI4)@G;2JJM+LKI=O@&K7I5=9TC@I4CJB&J;DN8%98>:DB0WE8LG-;6@I*+JK8))96</IM;@6&+G2HB()+(-CPC7&<;7CI7'.LC.R\\XD+?8?%>;?NO@\OFK8,I;&;J&+E1=9@2,%8-&18%-1-3;,1,:::'D;73+$**-A*(%6K'==(A=,BB8B8@7>04$$&(:@37&9?3*+%<MB-K--I:;A3.K0C%?%+0$$+3'NBD<MB.%/,3%GD;60>.128@4'1*J,<?+==ADE87E/<*:C%::%$8:;313D<G*?@C%1>CG,*,.3:-*7')(32F:+,(:%>LFC<&27ADD--=A,*+/?&6C(NPI(=A=..15@3:EACCDA)%@):@-H(%($+&&-)%+<*>@48>&L98A9/3&-;4+DC@-;AA77@38<4<-A545M(9B%1;DC3+-0$20>3D9J*L8?-L:?135064(8%%=33C>-4B,6:9&KE@':A0B.A%(?B52:9N37=153&>7C+@3%62=+:87ON?1E9,('F?0+?)'%%&6&2.@#&.6??)/61$(239*6)53*1%'6<555.C2F)).,8<O'NCC0EC@0B91>BB1PH;OA:5+..))%$(63,7/::M,.-I39O39;&EM:FA;-C22,E.?>-D8;=#F8#/20(D<<38.7'8;8&&KL>)%,:?A4POF;F+(*JFD4;=@'03/&'&%5B/30=3&7PB/1>:BFDCD36>DCFED.%%24/2.5@5)3IE:5$-64C/)9B:@21AC(B?8='4$>;@CF.MB+3''*58?,ED,D4<BB/D>BB/BDBF$811//:92&((@/9L%C8.))&+&78(C5.+8%$))F%23&,6?.0=<N(II3D4BCB@0+D;5BE(;;777(<)1-346<B)AMONC81)42,65=AB14@D::+CC0I:'KPP<6>5,79,**%3A@A7@4CB2@B35,,&&$-(9=E3@B)G(7(<=;6-,%HE7+6C5=:?<&.(7.-&+(+?<2B9A.2A/9'$*0@JDF9AFE4B381%-,Q6MMB<OC1/;@6F=-7B1<'+..A>9C>>D;86;E&=;::2/<93*8<+4D=#DEC+>16BA(;A;3*69C268A3%I)?<<)/1'5:>&:(%)+B@.9;-,*))48;M50-$*J/93:@.E6@.55870@4PH0@;0(B,,;-/<6C@3?1QNB9;1;+',,8B;1C@3BA:;&$#-&$31-AC':%)(7%6++NA5C;HFFD?C16++/)$DA8+M&B:?:&59F.6A?B0&01*<:A.L%+36;6;+?>?E2D@.2--?)9<314?4A'20$1&),ACE;;O+9&$BC6B>%51'0E<B0033&LJJCD<64BC.%N5<=2*7&.%$)693B)(=D7CCE1GMC1*35?*$;*3%/()11BDA*2+8@'JNK5NK)F/&2,%)2)<71C/0D;B8.(C8C>3A9;*KK@<N?C3,+.((+%+)6$?,=%&'9FC=)1'4A<.$-+1ECG<<9&21'*2<*,&?4+8).%C26+;&1B3.6).$0-&$&-2-

```

**Comment by adamnovak** [comment]
When you post literal text you want to put it between "```" and "```" so it gets a nice gray box and isn't parsed as Markdown. I've edited some of the comments to fix them up.

@wheaton5 It's checking for just a literal "*" string, because it's allowed to have just "*" for the qualities even if the sequence is more than one base. If there isn't just a "*", strcmp returns a nonzero value, and then the length check is performed.

I think the problem here is URL encoding. @srmcgee's quality string contains `%32`, @wheaton5's has a `%66`, and @ChriKub's has a `%2A`. We're blindly pasting the raw quality string into a `data:` URL, but we aren't properly URL-encoding it. HTSlib URL-decodes it, substituting `%` and any two hex digits with the corresponding character, but it's liberal in what it accepts and doesn't complain about the numerous uses of unencoded reserved characters (like `%` by itself) in the quality strings. It only gets upset if it successfully makes a substitution and then finds out that the quality string is now 2 characters shorter than it should be. So we only encounter this error when `%` and two valid hex digits happen to appear together in real input data (and apparently this never happens in the data we test vg with).

We need to add a URL encoding step when we generate the `data:` URLs we feed to HTSlib.

**Comment by ekg** [comment]
I've instrumented the code in sam.c, and it looks like it's got the wrong sequence length for the qual string internally. However, what we're feeding in in alignment.cpp is correct. I'm perplexed and wondering if it will be faster to break with htslib and use https://github.com/walaj/SeqLib than try to figure out what's going on here. The interface to write SAM/BAM/CRAM for htslib is not very user-friendly. At least at the time that I wrote the vg integration for it I had to jump through some very strange hoops.

**Comment by ekg** [comment]
@adamnovak this sounds pretty... difficult. Maybe it's time to look at using SeqLib. I believe the only changes will need to be in alignment.cpp. On the other hand, maybe we can work around this.

**Comment by adamnovak** [comment]
I think, given how permissive the parser is, all we really need to do to
avoid this problem is replace `%` with `%25` in the strings we pass in. We
still won't really be making technically valid URLs, but we won't be making
anything that HTSlib will have a plausible wrong parsing for either.

**Comment by ekg** [comment]
This should be fixed. Please speak up if you run into a similar issue. I still want to swap out htslib for SeqLib, but that can wait.

**Comment by srmcgee** [comment]
Thank you very much. I'll give it a spin.
