### ISSUE TITLE
Factor longer functions in main.cpp into library functions for easier reuse

### ISSUE THREAD

**Issue by ryan-williams** [vgteam/vg#14]

**Comment by edawson** [comment]
I've started doing this for the [`sift`](https://github.com/edawson/vg/blob/master/src/sift_main.cpp) and [`homogenize`](https://github.com/edawson/vg/blob/master/src/homogenize_main.cpp) commands. We should revisit it for the other commands as well.

**Comment by adamnovak** [comment]
I think we really want to change things over to subcommands now, so I'm going to close this.
