### ISSUE TITLE
`vg index`: specify number of threads

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1402]
I'm running the following command from the README to generate an index for `x.vg`:

    vg index -s -k 11 -d x.vg.index x.vg

On my server, this will use as many cores as possible. How can I limit 'vg index' to only use N number of threads?

**Comment by glennhickey** [comment]
-t N

**Comment by evanbiederstedt** [comment]
Thank you for the help. Issue closed. 

BTW, could I get this in the README/wiki? Of course, I may have missed
