### ISSUE TITLE
Error on Build with Centos 7

### ISSUE THREAD

**Issue by saiz06** [vgteam/vg#1406]
I build with the following command on Centos 7:

. ./source_me.sh && make static

And I keep getting the following error:

cram/cram_io.c:57:19: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
                   ^
compilation terminated.
make[1]: *** [cram/cram_io.o] Error 1
make[1]: Leaving directory `/root/test/vg/deps/htslib'
make: *** [lib/libhts.a] Error 2

I installed zlib-devel but it did not solve the problem. Would you know the possible cause?

Thanks

**Comment by JervenBolleman** [comment]
@saiz06 did you follow the example at [wiki](https://github.com/vgteam/vg/wiki/Building-VG-on-Cent-OS-6.6-or-7--and-using-it)

**Comment by adamnovak** [comment]
I don't think `zlib-devel` is the right package for that header. Try asking `yum`:

```
sudo yum whatprovides */bzlib.h
```

I think you might actually want `bzip2-devel`.

**Comment by JervenBolleman** [comment]
@adamnovak we got a bit further on the gitter channel and will update the wiki afterwards.

**Comment by saiz06** [comment]
Got it running, thanks. I'm going to update the wiki.
