### ISSUE TITLE
clarification: mapping with RocksDB?

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1408]
From the README, users create an index form the graph `x.vg`

```
# store the graph in the xg/gcsa index pair
vg index -x x.xg -g x.gcsa -k 11 x.vg

# alternatively, store in a rocksdb backed index (recommended for surjection to BAM later)
vg index -s -k 11 -d x.vg.index x.vg
```

Now, we can map a read:

```
# align a read to the indexed version of the graph
# note that the graph file is not opened, but x.vg.index is assumed
vg map -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -x x.xg -g x.gcsa -k 22 >read.gam
```

It looks like the first command which creates a `*gcsa` file must be run for this to work. If so, could this be made more clear in the README? "Alternatively" would give me the impressive that either command would suffice. 

If the previous sentences are wrong, could users get a equivalent command for `vg map` (which works via RocksDB/x.vg.index)?

**Comment by ekg** [comment]
Mapping with the rocksdb index is no longer possible. This is a bug in the README that I've fixed via a dirty push to master.

**Comment by evanbiederstedt** [comment]
Thanks, appreciated
