### ISSUE TITLE
small softclips result from surjection

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#1409]
Working with some simulated data, we're finding that we are often missing the exact alignment (in BAM) by 1-4bp. The reason seems to be the way that surjection is picking up less reference to run the global alignment against than needed. Maybe a fix is to extend a little bit on both ends. This could be risky as we can start to introduce weird microdeletions at the beginning and end of the alignment that are allowable under the global alignment score heuristics.

**Comment by ekg** [comment]
Practically, it's probably OK to allow SNPs at the start and end of the read rather than turn them into soft clips. Longer stuff seems to be less frequent.

**Comment by ekg** [comment]
We can use the score setting to determine the length of a soft clip that we expect. It should be that the score for the set of mismatches is less than that if we opened a gap of the length of a soft clip. The short soft clips coming through surjection are resulting from aligning the read against a smaller reference subsequence than we should.

**Comment by jeizenga** [comment]
With the new algorithm I expect we'll be finding artifacts that are, if nothing else, different than these. I'm going to close this for now.
