### ISSUE TITLE
vg view GAM to json: Format error

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1411]
Hi,
I converted GAm files to json using:
`vg view -a mapping.gam -j > mapping.json`
When I try to view them either using the python3 json package, or json_pp I get an error message:
> garbage after JSON object, at character offset 14147 (before ""mapping_quality": 6...") at /usr/bin/json_pp line 44.

> garbage after JSON object, at character offset 6650 (before ""score": 2614, "sequ...") at /usr/bin/json_pp line 44.

It seems as if additional " characters end up in the file.

Cheers,
Chris

**Comment by glennhickey** [comment]
I think those APIs are expecting a single JSON document.  What vg view -a
gives you is a list of JSON records.   You can parse them line by line
though:

gam_records = []
for line in json_file:
    gam_records.append(json.loads(line))

**Comment by ChriKub** [comment]
@glennhickey yes, it does. Thanks
