### ISSUE TITLE
Malformed BAMs from VG Surject

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#1424]
@ekg @adamnovak @glennhickey 
So I've been attempting to use `vg surject` to produce BAM files on a set of samples for the purposes of doing joint genotype calling on a cohort and have found that it produces malformed BAM files.

When running a sample BAM file through Picard tools' `ValidateSamFile` it produces the following errors:
(out of a total of ~1182156685 records)
```
Error Type      Count
ERROR:INVALID_ALIGNMENT_START   781
ERROR:INVALID_MAPPING_QUALITY   365824
ERROR:INVALID_MATE_REF_INDEX    1182155904
ERROR:MISSING_READ_GROUP        1
WARNING:MISSING_TAG_NM  1181765146
WARNING:RECORD_MISSING_READ_GROUP       1182156685
```

The BAM file is produced by merging chromosomal BAM files that were each the product of vg surject on their respective chromosomal GAM file.

Descriptions for the various errors output from `ValidateSamFile` can be found here: https://gatkforums.broadinstitute.org/gatk/discussion/7571/errors-in-sam-bam-files-can-be-diagnosed-with-validatesamfile

Of note, the `ERROR:INVALID_MATE_REF_INDEX` errors seem to indicate unpaired reads. It looks like this was noticed in a previous issue? https://github.com/vgteam/vg/issues/369
What's the status on that issue?

**Comment by adamnovak** [comment]
For the read group, it appears that GAM can hold read groups, and the `--read-group` option to `vg map` ought to make them get set in the emitted mappings.

As for the other issues, I shall investigate.

**Comment by adamnovak** [comment]
I just closed #369 because in general paired reads come through paired and that read was for the initial implementation. If some particular reads are coming unpaired, that's a new bug.

**Comment by cmarkello** [comment]
@adamnovak @glennhickey  BAMs are much improved, I'm no longer getting `ERROR:INVALID_MATE_REF_INDEX`, `ERROR:MATE_NOT_FOUND`, and a majority of `ERROR:INVALID_MAPPING_QUALITY`. However, I'm still getting some residual invalid mapping qualities on the surjected BAMs.

samtools `ValidateSamFile` still returns a number of `ERROR:INVALID_MAPPING_QUALITY` type errors on these BAMs.

They're formatted like the following:
`$QNAME   4   *   0   60  151M    *   0   0 $SEQ $QUAL`

`$QNAME   4       *       0       60      123M28S *       0       0     $SEQ $QUAL`

`$QNAME   4       *       0       60      17M6D134M       *       0       0     $SEQ $QUAL`

I can't seem to get you a small sample of these malformed alignment records since it seems that `vg view` can't convert JSON to GAM format.

**Comment by adamnovak** [comment]
OK, I just made a pull request which ought to help here; surject should
stop putting CIGARs and nonzero MAPQs on anything with the unmapped flag
set, and will explode if they don't exist for reads with the flag unset.

Can you test it? And did you figure out how to go back from JSON to GAM (vg
view -JGa)?

On Tue, Feb 20, 2018 at 12:49 PM, Charles Markello <notifications@github.com

**Comment by cmarkello** [comment]
@adamnovak I now have the GAM file containing some of the bad reads from the malformed surjected BAM file.

They can be found on kolossus in `/cluster/home/charles/hiveHome/UDP_debug_data/bad_surjected_bam_reads/MAPQ_record.UDP10961_22.gam`.
They were formed using the vg version found in the container `quay.io/vgteam/vg:v1.6.0-442-gd3a69a42-t134-run`.

The 1kg_GRCh37-based graph reference used can be found in `/cluster/home/charles/hiveHome/UDP_debug_data/graph_1kg_ref_index_vg_v1.6.0_187`

I believe the command that can be run to reproduce the bad BAMs is the following (although you'd need to double check on the compiled vg script version):
```
WORK_DIR="/cluster/home/charles/hiveHome/UDP_debug_data"
${WORK_DIR}/bin/vg surject -x ${WORK_DIR}/graph_1kg_ref_index_vg_v1.6.0_187/1kg_ref_hs37d5.xg -t 32 -b -p 22 ${WORK_DIR}/bad_surjected_bam_reads/MAPQ_record.UDP10961_22.gam > ${WORK_DIR}/test_22.bam
```

**Comment by adamnovak** [comment]
OK, I think I figured this out. We were feeding the unsurjected read
forward when surjection failed, which is not what we want for SAM output.

I've made it successfully work on that file on Kolossus, and the required
changes are in my PR.

**Comment by cmarkello** [comment]
Awesome! I'll be sure to test out the pull request as soon as the unit
tests finish.

Thanks again!
-Charlie
