### ISSUE TITLE
MAPQ score for the primary alignment of the input query using VG ALIGN 

### ISSUE THREAD

**Issue by ksnv** [vgteam/vg#1425]
Hi, 

I am trying to get the mapping quality score (MAPQ score) for the primary alignment (best alignnment) of the input query using VG ALIGN.

I tried to using debug flag provided for vg align to check for the details. I doubt it provides only the alignment scores but not any information on MAPQ scores. 

What could be the right way to get MAPQ score using only the primary alignment score of the input query (not considering secondary or any other sub-optimal alignments using VG's MAPQ computation) 

Thank you.

**Comment by ksnv** [comment]
Thanks Jordan ! How VG assigns mapq score ? Can you throw some light on VG's computation of mapping quality function ?

**Comment by jeizenga** [comment]
The idea is similar to the approach originally described in the supplement of the MAQ paper as "type-3 mapping errors":
http://genome.cshlp.org/content/18/11/1851
In our case, the likelihood model comes from interpreting alignment scores as the log-likelihood of a pair-HMM, as in Durbin, Ch. 4.

**Comment by ksnv** [comment]
Thanks Jordan ! 
VG handled the implementation of MAQ score right ? 
Which block of code helps to print each of the following values that contribute to Q(A/X) score 
1) S(A^/X) value
2) max S(A/X) value

**Comment by jeizenga** [comment]
As far as I know there's no code that will just print out mapping qualities. They get added to the GAM files in the mapping process. If you wanted to hack the code a bit, I'd take a look in the gssw_aligner.cpp file. That's where the mapping quality computation code is.

**Comment by ksnv** [comment]
Thanks Jordan for immediate response. Actually I want to inspect the values of best alignment based S(A^/X) score (not the straightforward alignment score, but the quality adjusted score which was used in the formula for Q(A/X) in your work.) Similarly, want to inspect the second best quality adjust score (referred as  max(S(A/X)) in your work). 

I tried to trace the implementation for inspecting those values. But I found it hard for me to cope up with the naming conventions of the variables used.
![screenshot from 2018-02-15 10-13-44](https://user-images.githubusercontent.com/36166942/36244459-3b67d620-124c-11e8-9651-3e215053b998.png)
Here I am attaching the formula found from your previous posts for understanding MAQ in vg. 

 It would be of great help if you can help in identifying the same !

**Comment by jeizenga** [comment]
Ah, I see. It's possible to use base quality adjusted scores without producing a mapping quality, and also to produce a mapping quality without using base quality adjusted scores. They're kind of separate things, although I do think the base quality adjustments are a natural way to incorporate base qualities into the mapping quality computation. The base quality adjusted alignment scores can be toggled with the `-A` flag in `vg map` and `vg mpmap`. If you do that, the adjusted scores will be both a) used in the MAPQ calculation, and b) the score reported in the GAM.

**Comment by ksnv** [comment]
Jordan , are you saying that -A will print only the primary quality adjusted alignment score (S(A^/X) from the above formula ) by keeping second parameter ( max(S(A/X) ) zero then (as -K is not default flag)???? 

Is the score in the gam file alignment score or mapping quality score ???

I suspect -A value is complete alignment adjusted score but what I wanted is the S(A^/X) which is only match mismatch based quality adjusted score directly used in the above formula.  

Thanks !

**Comment by jeizenga** [comment]
I'm not quite sure I understand what you mean by "print out". The alignment scores and the mapping qualities are both fields in the GAM records. The alignment score is called "score" and the mapping quality field is called "mapping_quality". There's no native functionality that will show you only one or the other. 

If you select quality adjusted alignment, that's the quality adjusted score is the one that will be added to the GAM record. It's also the score used to compute the MAPQ. 

As for the maximum scoring alternate alignment, the fact that you only have `-K` set to report one alignment does not mean that other alignments weren't computed. In fact, we often need to compute many alignments in order to determine which is the optimal alignment. The other alignments that we don't select will be used to compute the mapping quality.

**Comment by ekg** [comment]
To be clear you can see this in the output of you out it in JSON. Then you
can pick out the mapping quality using `jq .mapping_quality` on the
JSON-GAM stream.
