### ISSUE TITLE
Add readgroups and sample name to vg mpmap options

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#1428]
@jeizenga @adamnovak 
In order for HaplotypeCaller to accept `vg surject`'ed BAM files, they first need readgroup information. So having those as part of `vg mpmap` would be helpful. You can follow the options listed in `vg map`:
```
    -N, --sample NAME       for --reads input, add this sample
    -R, --read-group NAME   for --reads input, add this read group
```

**Comment by jeizenga** [comment]
Added in https://github.com/vgteam/vg/pull/1430

**Comment by jeizenga** [comment]
Closed via https://github.com/vgteam/vg/pull/1430
