### ISSUE TITLE
Confused by missing GCSA2 index during `vg index`; error upon `vg map`

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1437]
After constructing a graph, I am following the README to execute `vg index` and then `vg map`. 

The command I'm running after constructing the graph `x.vg` is:

```
vg index -x x.xg -g x.gcsa -k 16 x.vg
```

This command executes without any errors; however, there is no `x.gcsa` to be found. 

This appears to be a problem upon mapping, as 

```
vg map -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -x x.xg -g x.gcsa >read.gam
```

will consequently throw the following error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Need XG, GCSA, and LCP to create a Mapper
Got signal 6
Manual stack trace:
Stack trace from backtrace() for signal 6:
[0x92bb5a]
=================
[0x92beb5]
=================
[0xc667b0]
=================
[0xc6677e]
=================
[0x107ba2a]
=================
[0x103ca4d]
=================
[0xfb4076]
=================
[0xfb40c1]
=================
[0xfb4009]
=================
[0x76f635]
=================
[0x7d1d28]
=================
[0x40532d]
=================
[0x10733a3]
=================
[0x107362e]
=================
[0x4c0ffa]
=================

````

The relevant code is here: https://github.com/vgteam/vg/blob/80aba8632b24e8c43bf34b3f0f37fe2516f54cf0/src/subcommand/map_main.cpp#L847-L855

It's basically missing a required argument. 

So, is there an extra step necessary to generate the index for mapping? Is this a bug? Troubleshooting recommendations?

**Comment by jltsiren** [comment]
This sounds strange. Try adding `-p` to the `vg index` command, as the progress information may contain some clues.

**Comment by evanbiederstedt** [comment]
@jltsiren Thanks for the response. I'll run this and output you when complete.

**Comment by adamnovak** [comment]
Yes, that index command really should produce an x.gcsa file; there's something wrong with it.

**Comment by evanbiederstedt** [comment]
@jltsiren @adamnovak So, the output file using `-p` is pretty huge.

e.g. I tried >24 hours ago restarting this command and on a ~0.8 GB *vg. The output text file is already +7GB. 

I do not see an output *.gcsa being written. 

(1) Would you like to download the *vg?

(2) Similarly, I think you'll have to download the output file with the `-p` flag as well.

**Comment by edawson** [comment]
This sounds like an old commit maybe? Maybe try a:

````
      git pull  
      git submodule update --init --recursive
````

I thought @adamnovak had fixed the long progress bar issue.

**Comment by adamnovak** [comment]
I thought I had fixed it too. I remember testing it.

**Comment by evanbiederstedt** [comment]
+1 Thanks for the help everyone!
