### ISSUE TITLE
vg view -d error post vg find, still produces dot file but seems wrong

### ISSUE THREAD

**Issue by wheaton5** [vgteam/vg#1438]
https://drive.google.com/open?id=1Ix6YM63MLzLWonbwGcGjgosuxlIuHC08

xg and command to produce error available on my google drive at that link.

error is
graph invalid: edge index=0 (1925->1926) cannot find node (from) 1925
[vg view] warning: graph is invalid!

this does not occur if you do vg view -d reference.vg (file also provided)

The dot provided by the command that errors does have indels but does not have snps which should be present and seem to be present in the vg view -d reference.vg dot file via inspection of the text (I cannot produce a picture of the resulting large graph).

What I am mostly interested in is inspecting some regions that are fully diverged and seeing if the vg augment (or vg mod) commands I have tried have added some fermi contigs that span these regions. I tried it on one such region but it looked linear + indels.

**Comment by glennhickey** [comment]
You can get around this by using the -c option to expand out the graph a
bit from your path.  so

`vg find -p 3L:520209-521000 -x xg.xg -c 10 | vg view -d - > notsure.dot`

will give you a valid dot.

**Comment by wheaton5** [comment]
yes, erik just let me know. Thanks
