### ISSUE TITLE
vg msga failure

### ISSUE THREAD

**Issue by wheaton5** [vgteam/vg#1448]
fails on vg + unitig assembly fasta with error
error: failed to include path

https://drive.google.com/open?id=1jtMG9kWA9FYKxGJU_GhiKdMaAP9whkV1
contains the files and command

**Comment by ekg** [comment]
This happened to me today because the path I was trying to add had a
duplicated name in the input set. Are the unitigs all named differently?

**Comment by wheaton5** [comment]
They are named 1,2,3,4,5.... etc.

**Comment by ekg** [comment]
The fasta file includes spaces in the headers:

```
> 1
```

I'd expect:

```
>1
```

This is confusing our fasta reader (fastahack). If this is standard then I should fix fastahack. The quick fix is to use sed on the file to remove the spaces.
