### ISSUE TITLE
Why does the wiki recommend vg index with -k 11? 

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1454]
My understanding is that the -k option sets the starting kmer size for the index, with 16 as the max (and I think) recommended value. Is there a recommended reason for trying 11 instead? 

https://github.com/vgteam/vg/wiki/Basic-Operations

Can you provide details regarding the different values for the `-k` arg for 'vg index'? 

    vg index -x graph.xg -g graph.gcsa -k 11 graph.vg          # Index

https://github.com/vgteam/vg/blob/master/README.md

    # store the graph in the xg/gcsa index pair
    vg index -x x.xg -g x.gcsa -k 16 x.vg

**Comment by jltsiren** [comment]
The `-k 11` is a leftover from years ago, when we had different assumptions and different algorithms.

By default, `vg index` builds a 8k-mer index, but it can also be used to build a 2k-mer index, a 4k-mer index, or a 16k-mer index. The 16k-mer index is probably going to be the default soon, once I have sorted out some issues in index construction.

The order of the index is an upper bound for MEM length in read mapping, so it should be sufficiently large. On the other hand, a 16k-mer index with `-k 10` can already produce a single MEM for exactly mapping 150 bp reads, so larger values are probably not necessary.

Theoretically, the most efficient choice of `-k` is near the base-4 logarithm of genome length (e.g. `-k 16` for a human genome, or `-k 10` or `-k 11` for a 1-megabase genome). This results in the best time/space trade-off for index construction:

* `vg index` first enumerates all k-base paths in the graph and then joins them into longer paths when needed.
* Enumerating paths of length k is faster than enumerating paths of length k/2 and joining them into paths of length k.
* If a path of length k/2 is already unique, we don't need its length-k extensions, so we can save time and space by not enumerating the extensions.
* Hence  we should choose k near the phase transition, where most k-mers still occur in the graph, but a significant fraction of them occurs only once.

Finally, `-k 16` is the largest supported value of k.

**Comment by evanbiederstedt** [comment]
@jltsiren Excellent! This is such a comprehensive answer. Could we get this on the wiki? 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
@jltsiren 

Thanks for working on the wiki and clearing things up a bit, I appreciate the work!

 https://github.com/vgteam/vg/pull/1512
https://github.com/vgteam/vg/wiki/Index-Construction

In the current wiki version, users are shown how to make a simple graph via

    vg index -x graph.xg -g graph.gcsa graph.vg

Users may run into this error: 

    error:[vg index] kmer size for GCSA2 index must be >0

if they're using an older vg version (I think my installation was from last month). I haven't taken the time to install the latest master branch; if a default `-k` is used for the above command to work, is it a 8k-mer index or 16k-mer index?

Apologies if this is clear somewhere. Keep up the good work, everyone! Much appreciated

**Comment by jltsiren** [comment]
I added a mention on the wiki page that the instructions assume VG from March 8 or later. The three PRs I made added sensible default values, simplified some workflows, and added some new functionality. For example, GBWT construction used to create per-chromosome XG indexes, and there was no way to transfer the thread databases from them to a whole-genome XG index.

The default GCSA2 index is now a 256-mer index (`-k 16 -X 4`). The use cases where it's reasonable to build a lower-order index should be quite rare.

**Comment by evanbiederstedt** [comment]
@jltsiren 

I'll try this again with the -Z flag, as mentioned in this thread https://github.com/vgteam/vg/issues/1458

Otherwise, in the face of this error `PathGraphBuilder::write(): Size limit exceeded, construction aborted`, is the recommendation for users to keep trying at consecutively smaller kmer values? `-k 15` then `-k 14`, etc.?

**Comment by evanbiederstedt** [comment]
@jltsiren 

This command does indeed work

`nice vg index -Z 1700 -b /path/ -t 20 -k 16 -g graph.gcsa graph.pruned.vg`

I'm not sure why there was an error previously. That solves issue (2). I will open up an Issue for (1)
