### ISSUE TITLE
Loading VG graphs is sometimes very slow

### ISSUE THREAD

**Issue by jltsiren** [vgteam/vg#1457]
It takes a lot of time to load VG graphs from disk. Loading a single human chromosome takes several minutes, meaning that the reading speed is 1 MB/s or less. Recently I have encountered even worse graphs that take tens of minutes to load. This annoyed me enough that I started investigating.

Loading a VG graph essentially consists of three kinds of steps (assuming that there are no paths):

1. Read the next `Graph` chunk from disk.
2. Add the nodes and the edges from the chunk to the `Graph` object in the VG graph.
3. Insert the loaded nodes and edges into various hash maps.

The first two steps are fast enough, so the issue is with the hash maps. By loading a problematic graph with various hash maps disabled, I narrowed the problem down to the following three hash maps:

```
hash_map<id_t, Node*> node_by_id;
hash_map<id_t, vector<pair<id_t, bool>>> edges_on_start;
hash_map<id_t, vector<pair<id_t, bool>>> edges_on_end;
```

All three have an integer key. In the GCC implementation, the `std::hash` of an integer is the integer itself. If the node identifiers form a contiguous range, they will occupy a contiguous range of buckets in the hash table as well.

The problematic graphs all come from haplotype-aware pruning. Their node identifiers form two contiguous ranges: one for the original nodes and another for duplicates. Sometimes these ranges overlap modulo bucket count. If the overlap is bad enough, searching the hash table will take about sqrt(n) probes for many keys.

We need a better hash function for integer keys to solve this problem.

**Comment by ekg** [comment]
Thank you @jltsiren this is fascinating. I had wrongly assumed that much of the slowness is coming from the decompression.

@jeizenga and I have been wanting to replace this in-memory structure with something better. In theory it should be possible to do without touching much code, but actually many things in vg are referring to `Node*`s. It would be ideal to rebase around the handle graph concept (handle.hpp).

**Comment by ekg** [comment]
Please make a PR with Thomas Wang's hash function, if it's possible. That would seem like an obvious fix. There are other places besides loading where this problem might be evident--- such as when manipulating small subgraphs where we have consecutive node id ranges.
