### ISSUE TITLE
`vg index` GCSA: problem: how to re-direct huge files written to `/tmp`? 

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1460]
This is just using the standard `vg index` command:

    vg index -p -t 10 -x myfile.xg -g myfile.gcsa -k 16 myfile.vg

The problem is that there are several huge  (~150 GB) files written to `/tmp` that cause server problems on my end, of the format:

    /tmp/gcsa_*

I'm unsure whether this is the problem as the algorithm runs and completes, or whether there are temporary files which remain after I prematurely stop the above command. 

Question: How can I redirect where these files are saved?

**Comment by jltsiren** [comment]
Failed indexing runs can leave temporary files behind, while successful runs will remove them. You can delete the files safely after `vg index` has finished. The naming pattern is `gcsa_hostname_pid_counter`.

You can redirect the temporary files to another directory by setting the `TMPDIR` environment variable. Unfortunately this does not affect the input kmer files `.vg-kmers-tmp-*`, which are written to the working directory.

See my answer to #1458 for further discussion on the temporary files.

**Comment by evanbiederstedt** [comment]
@jltsiren Thanks for the help, this clears things up.
