### ISSUE TITLE
xg indexes get way too big

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#1468]
I am skeptical of the succinctness of xg indexes made from augmented graphs.  For instance, when I augment my chromsome 21 graph with about 50 148bp reads (vg mod -i), the xg index size increase from `509M` to `12G`, all for a `50M` graph.

```
21.vg : 52M
vg index 21.vg -x 21.xg -> 21.xg : 509M
vg mod 21.vg -i 52_reads.gam -> 21_aug.vg : 52M
vg index 21_aug.vg -x 21_aug.xg -> 21_aug.xg : 12G
```

This seems to have arisen in the past few months (since I last ran my call debugger script).  I'll debug by trying to draw one of those sdsl space charts as soon as I get a chance.

**Comment by glennhickey** [comment]
Just saw #1322 which is still open.  So this must be due to the node range not starting at 1.  I'll leave this issue up as, in addition to the node range mentioned before, it seems that small paths are particularly problematic.

**Comment by ekg** [comment]
There is a really simple fix for this. The path descriptions need an initial offset in the sequence space. If they are small then this will make their representation small.
