### ISSUE TITLE
Mapping qualities of the alignments in BAM file

### ISSUE THREAD

**Issue by shilpagarg** [vgteam/vg#147]
Hi, 

Is it possible to output mapping quality of the alignments as well? 

Thanks.

**Comment by ekg** [comment]
We need a technique to estimate them. This is non-trivial to do correctly, but there are a number of ways we could estimate it.

Multi-mapping provides a way to do this, as does kmer counting.

Reads with many possible mappings (as assessed by actually mapping them) should have lower mapping quality.

Things that are likely to have alternative mappings would have many more kmer hits than those that don't.

Other than these, if you could suggest a heuristic technique from another aligner, I'll see if I can add it.

**Comment by adamnovak** [comment]
We now have mapping qualities in our GAM files (though I don't know if they get copied over to BAMs by surject).
