### ISSUE TITLE
Possible route forward with surject

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1470]
@ekg @adamnovak 
I ran into a lot of the same problems that I think we're running into with the surject algorithm when I was working out how to construct MultipathAlignments. I think the code I wrote could probably be repurposed to make a pretty good surjection algorithm.

The MultipathAlignment workflow is kind of like this:
1. Extract a subgraph around some MEMs (https://github.com/vgteam/vg/blob/master/src/multipath_mapper.cpp#L1929)
2. Walk out MEMs into Paths (https://github.com/vgteam/vg/blob/master/src/multipath_mapper.cpp#L3641)
3. Compute the connectivity between the Paths (https://github.com/vgteam/vg/blob/master/src/multipath_mapper.cpp#L3666)
4. Do alignments between Paths that could be connected into longer alignments (https://github.com/vgteam/vg/blob/master/src/multipath_mapper.cpp#L2276)

I can imagine a similar workflow for surjection:
1. Extract the reference path graph around an Alignment
2. Get the sub-Paths from the Alignment that are on the reference path
3. Compute the connectivity between the sub-Paths
4. Do alignments between the sub-Paths

It would take a little refactoring, but the algorithms are all already there and I'm quite confident in them.

**Comment by ekg** [comment]
This would be ideal. It would provide maximum control over the surjection
with minimum realignment cost.

I haven't done so but perhaps now that I'm rewriting surject again I should
refactor it into an object where these different approaches can live.

I'll be in touch about the performance of the "heavy full length bonus" way
of handling surjection. Thus far it looks like it is working very well but
this doesn't mean there won't be low frequency problems with it.

**Comment by ekg** [comment]
Here's a test harness we can use:

```
vg construct -r 1mb1kgp/z.fa -v 1mb1kgp/z.vcf.gz -m 32 -p >z.vg
vg index -g z.gcsa -k 16 -p z.vg
vg sim -x z.xg -l 100 -n 1000 -e 0.01 -i 0.005 -a >z.sim
i=8; time vg map -d z -G z.sim --surject-to bam | pv >z.sim.$i.bam && sambamba sort z.sim.$i.bam && freebayes -f 1mb1kgp/z.fa -l@ 1mb1kgp/z.vcf.gz -m 0 -q -1 z.sim.$i.sorted.bam | pv -l | vcfbiallelic | vcfkeepinfo - TYPE AO RO DP | vcf2tsv | gzip >z.sim.$i.sorted.bam.tsv.gz
```

Now, in R:

```R
require(tidyverse)
summarize(read.delim("z.sim.8.sorted.bam.tsv.gz"), count=n(), alt=sum(AO), ref=sum(RO), bias=mean(sum(AO)/sum(RO+AO)))
```

This outputs a bias estimate:

```
  count    alt    ref      bias
1 28732 214830 217498 0.4969144
```

We want `0.5`.

**Comment by ekg** [comment]
I re-did the experiment using the quality scores given by the chipseq dataset to simulate the reads:

```
vg sim -n 200000 -f ENCFF000ATK.first100k.fastq.gz -s 8291 -x z.xg -a | pv >z.51bp.ENCFF000ATK.sim
i=10; time vg map -d z -G z.51bp.ENCFF000ATK.sim --surject-to bam | pv >z.51bp.ENCFF000ATK.sim.$i.bam && sambamba sort z.51bp.ENCFF000ATK.sim.$i.bam && freebayes -f 1mb1kgp/z.fa -l@ 1mb1kgp/z.vcf.gz -m 0 -q -1 z.51bp.ENCFF000ATK.sim.$i.sorted.bam | pv -l | vcfbiallelic | vcfkeepinfo - TYPE AO RO DP | vcf2tsv | gzip >z.51bp.ENCFF000ATK.sim.$i.sorted.bam.tsv.gz
```

```R
summarize(read.delim("z.51bp.ENCFF000ATK.sim.10.sorted.bam.tsv.gz"), count=n(), alt=sum(AO), ref=sum(RO), bias=mean(sum(AO)/sum(RO+AO)))
```

The results get better, I assume because the qual-based error model is better than the one I was manually specifying:

```
  count    alt    ref      bias
1 28732 287770 290973 0.4972328
```

**Comment by jeizenga** [comment]
Just got results from the first test harness you suggested, which are comparable but actually a little worse. I'm going to run larger samples with both to see if it's statistical noise. On the plus side, the path-anchored surject algorithm seems to be 5-6x faster.

```
  count    alt    ref      bias
1 28732 142812 145141 0.4959559
```

**Comment by jeizenga** [comment]
Update:
Path-anchored algorithm on 200,000 149-bp reads with a trained error distribution
```
  count    alt    ref      bias
1 28732 424096 427259 0.4981424
```

Classic algorithm on 200,000 149-bp reads with a trained error distribution
```
  count    alt    ref      bias
1 28732 423893 428413 0.4973484
```

**Comment by jeizenga** [comment]
And a larger data set (750,000) with the same training data:
Path anchored
``` 
count     alt     ref      bias
1 28732 1592651 1601984 0.4985393
```
Classic
``` 
count     alt     ref      bias
1 28732 1591804 1606273 0.4977379
```

**Comment by jeizenga** [comment]
In sum, I'm taking this evidence to say that the path-anchored algorithm is comparable, maybe marginally better on some data, including data that has more realistic errors. It's also much faster. That's enough evidence for me to go ahead and do the switch and make it the default option. PR to follow soon.

**Comment by jeizenga** [comment]
@ekg I'm getting some failing tests b/c my current code is preserving the full length bonuses. Is there any reason we were stripping them before?

**Comment by ekg** [comment]
@jeizenga I guess there wasn't really any reason. It's encouraging that the path anchored algorithm is looking slightly better! It's about where I was when I used the global alignment algorithm rather than the local alignment with a big full length bonus. I'll check out your PR.
