### ISSUE TITLE
VG deconstruct (vg2vcf)

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#150]
Opening this just to make a place for dialogue. I'm debating various ways to implement VG to VCF conversion (which we'll call deconstruction), especially given that we don't preserve reference metadata from input. I'm guessing we'll need the reference as an input to deconstruct:
`vg deconstruct -r ref.fa <graph>`

I'll be actively working on this from here on out and am happy to leverage the hivemind for suggestions.

**Comment by ekg** [comment]
You can get the original reference as a path in the graph. In this case you might just need to tell vg which references to deconstruct out.

**Comment by glennhickey** [comment]
Yeah, the vg surject interface (-p) could be a good example to use as a
starting point..

**Comment by ekg** [comment]
@glennhickey this requires exactly the same functionality as surject. We were talking about working on the underlying function and then adapting it to the two different applications.

So the API I was thinking of is:

```c++
// this could be in VG, XG, etc.
Path relative_mapping(const Path& p1, const Path& p2);
Path relative_mapping(const Path& p1, const string& p2_name);
```

The output mapping describes the mapping of p1 onto p2, which we could represent either as an "anonymous" path or as a named path in the variation graph. The same interface should work on VG, XG, and the vg::Index.

A basic algorithm is to do a BFS from each end to find the nearest "upstream" and "downstream" locations where we find some component in the second path. If we can find them within some number of bases then we align the sequence of p1 on the other side of the bubble onto p2 and emit the resulting path.

If we can only find either end the mapping should look like it soft clips (insertion at start or end). This should fall out of alignment.

**Comment by edawson** [comment]
Update: A first pass at this is now implemented and in the master branch. It currently operates on the graph itself (rather than the index) and can call SNPs and indels. In theory, it should be able to call any known variation in the graph, though the output for complex events may not be identical to the input for various reasons. Underneath it's just a basic bubble caller but @ekg and I are thinking of trying other methods as well.

**Comment by adamnovak** [comment]
Since vg deconstruct is implemented, I'm going to close this issue.
