### ISSUE TITLE
vg surject fails when working on graphs with multiple overlapping reference sequences

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#1501]
`vg surject` gets confused and does horrible things (crashing) when given alignments that overlap many different reference sequences. It must be told which reference sequence(s) to surject into and also these must be separated. There has to be a better way.

**Comment by jeizenga** [comment]
I believe this should be resolved with the new surject algorithm. It might be worth checking if you have a reproducing example ready, but I'm going to close this for now.
