### ISSUE TITLE
Add a runtime check early in vg execution to bail with an informative message if SSE4.2 is not available

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#153]
Was talking with @pd3 about problems running vg on different hosts at the Sanger.

@lh3 did you get the same error when trying the binary release?

sse4 support should be detected, and if not an error printed saying something to the effect of "sse4 is required'. Ideally we'd switch back to a different alignment implementation.

[9:28:30 AM] petr_danecek: Hi Erik,
[9:29:09 AM] petr_danecek: looked briefly at vg and have some failing tests: "Illegal instruction" from vg construct -r small/x.fa -v small/x.vcf.gz | vg align -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -j -
[9:31:00 AM] petr_danecek: probably something with my installation? maybe my paths contain include unsupported versions of some external dependencies or something like that.
[9:32:51 AM] petr_danecek: might be good to have some configure script to take care of this

.....
confusion
.....

[9:45:39 AM] Erik Garrison: cat you get me your CPUflags?
[9:45:46 AM] petr_danecek: vg align -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -j rmme.x
[9:45:55 AM] Erik Garrison: eg10@vr-4-1-16:~/graphs/vg/test$ vg.pd3 construct -r small/x.fa -v small/x.vcf.gz | vg align -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -j -  
{"sequence": "CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG", "path": {"mapping": [{"position": {"node_id": 72}, "edit": [{"from_length": 14, "to_length": 14}], "rank": 1}, {"position": {"node_id": 74}, "edit": [{"from_length": 1, "to_length": 1}], "rank": 2}, {"position": {"node_id": 75}, "edit": [{"from_length": 1, "to_length": 1}], "rank": 3}, {"position": {"node_id": 77}, "edit": [{"from_length": 32, "to_length": 32}], "rank": 4}]}, "score": 96}
[9:46:13 AM] Erik Garrison: so it's coming out fine on vr-4-1-16
[9:46:39 AM] Erik Garrison: try this:
[9:46:41 AM] Erik Garrison: cat /proc/cpuinfo | grep flags
[9:46:54 AM] Erik Garrison: the illegal instruction on alignment could be related
[9:47:01 AM] Erik Garrison: if your processor doesn't have the right flags
[9:47:12 AM] Erik Garrison: rather, support the right instructions
[9:47:20 AM] Erik Garrison: then some of the stuff in gssw might fail
[9:47:48 AM] petr_danecek: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid amd_dcm pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr npt lbrv svm_lock nrip_save pausefilter
[9:48:03 AM] petr_danecek: you are right, when logged on  vr-4-1-16 then it works
[9:48:36 AM] petr_danecek: fragile :-|
[9:49:24 AM] Erik Garrison: eg10@vr-4-1-16:~/graphs/vg/test$ ( echo fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid amd_dcm pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr npt lbrv svm_lock nrip_save pausefilter; cat /proc/cpuinfo | grep flags | head -1) | tr ' ' '\n' | sort | uniq -c  | sort -n | grep -v '2 '
      1 3dnow
      1 3dnowext
      1 aes
      1 aperfmperf
      1 arat
      1 avx
      1 bmi1
      1 cpb
      1 decodeassists
      1 f16c
      1 flags           :
      1 flushbyasid
      1 fma
      1 fma4
      1 lwp
      1 pclmulqdq
      1 perfctr_core
      1 pfthreshold
      1 sse4_1
      1 sse4_2
      1 ssse3
      1 tbm
      1 tce
      1 topoext
      1 tsc_scale
      1 vmcb_clean
      1 xop
      1 xsave
[9:49:51 AM] Erik Garrison: these are the relevant ones:       1 sse4_1
      1 sse4_2
      1 ssse3
[9:50:04 AM] Erik Garrison: the complier you're using will compile for them
[9:50:12 AM] Erik Garrison: but you don't have the instruction set on your system
[9:50:19 AM] Erik Garrison: this might be made worse by the static compile
[9:50:29 AM] Erik Garrison: we could try turning that off....
[9:50:56 AM] Erik Garrison: on the other hand there are very few systems now that don't have sse3 and 4*
[9:50:57 AM] petr_danecek: -msse4.1 ?
[9:51:04 AM] Erik Garrison: yeah you can remove that for instance
[9:51:10 AM] Erik Garrison: this is fragile though
[9:51:14 AM] Erik Garrison: back to the configure script
[9:51:32 AM] Erik Garrison: it could be gssw
[9:53:05 AM] Erik Garrison: yeah
[9:53:12 AM] Erik Garrison: there is no way around it except to somehow build against an older library
[9:53:16 AM] Erik Garrison: https://github.com/ekg/gssw/commit/f1e41c7f343f4d3bebe71332a4665d0a12fe6aed
[9:53:30 AM] Erik Garrison: so i suggest testing on vr-4-1-16
[9:53:47 AM] Erik Garrison: at least for the moment
[9:53:48 AM] Erik Garrison: for dev work
[9:53:58 AM] petr_danecek: is it possible to detect this so that the program exists with a meaningful message?
[9:54:12 AM] Erik Garrison: that's a good idea
[9:54:22 AM] Erik Garrison: there must be a compiler intrinsic for that
[9:54:53 AM] Erik Garrison: http://stackoverflow.com/questions/2403660/determine-processor-support-for-sse2

**Comment by ekg** [comment]
Relevant: https://github.com/Mysticial/FeatureDetector

**Comment by jltsiren** [comment]
SDSL uses avx if compiled on a system that supports it. That's why I submit all of my jobs at Sanger with `-R avx`.

**Comment by iqbal-lab** [comment]
What is avx?

**Comment by mcshane** [comment]
https://en.wikipedia.org/wiki/Advanced_Vector_Extensions

We run all GATK HaplotypeCaller jobs with the `-R avx` bsub option too.

**Comment by pd3** [comment]
This checks whether sse3/sse4.1/sse4.2/avx is supported. I don't know what parts of `vg` rely on which version, so don't where to add it:

````
void check_cpu_features(void)
{
    unsigned int index = 1; // eax=1:feature bits
    unsigned int regs[4];

    __asm__ __volatile__(
#if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64)
            "pushq %%rbx     \n\t" /* save %rbx */
#else
            "pushl %%ebx     \n\t" /* save %ebx */
#endif
            "cpuid            \n\t"
            "movl %%ebx ,%[ebx]  \n\t" /* write the result into output var */

#if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64)
            "popq %%rbx \n\t"
#else
            "popl %%ebx \n\t"
#endif
            : "=a"(regs[0]), [ebx] "=r"(regs[1]), "=c"(regs[2]), "=d"(regs[3])
            : "a"(index));

    printf("sse:    %d\n", (regs[3]&(1<<25))?1:0);  // edx
    printf("sse2:   %d\n", (regs[3]&(1<<26))?1:0);
    printf("sse3:   %d\n", (regs[2]&(1<<0 ))?1:0);  // ecx
    printf("sse4.1: %d\n", (regs[2]&(1<<19))?1:0);
    printf("sse4.2: %d\n", (regs[2]&(1<<20))?1:0);
    printf("avx:    %d\n", (regs[2]&(1<<28))?1:0);
}
````

**Comment by ekg** [comment]
You could add it to gssw itself. Or, we could do the check prior to
alignment.

**Comment by pd3** [comment]
Which version is required, 4.1 or 4.2? @jltsiren says that SDSL requires avx, which is also not supported by the vr-2-2-02 machine. 
So maybe the check should be placed in vg to inform about both?

**Comment by ekg** [comment]
That makes sense to me.

**Comment by jltsiren** [comment]
Well, it looks like SDSL only uses SSE 4.2 after all, but `-R avx` still solves the problem at Sanger.

AMD introduced the support for SSE 4.2 quite late. Some of the older nodes (at least the ones using Opteron 6174 CPUs) do not support it, even though `lshosts` claims that they do. Requiring AVX finds the nodes that also support SSE 4.2.

SDSL apparently assumes that `sse4a` is equivalent to `sse4_2`, which causes the problem. When compiled on an Opteron 6174, SDSL sets the command line option `-msse4_2` and generates code that doesn't run on an Opteron 6174.

**Comment by edawson** [comment]
I think it should be flagged at compile time whether the hardware supports
all VG functions. If someone got all the way to alignment and then found
out their machine wouldn't do it I bet they'd be frustrated.

On Wednesday, November 11, 2015, Erik Garrison <notifications@github.com>
wrote:

> You could add it to gssw itself. Or, we could do the check prior to
> alignment.
>
> On Wed, Nov 11, 2015 at 11:40 AM, pd3 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > This checks whether sse3/sse4.1/sse4.2/avx is supported. I don't know
> what
> > parts of vg rely on which version, so don't where to add it:
> >
> > void check_cpu_features(void)
> > {
> > unsigned int index = 1; // eax=1:feature bits
> > unsigned int regs[4];
> >
> > __asm__ __volatile__(
> > #if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64)
> > "pushq %%rbx \n\t" /* save %rbx */
> > #else
> > "pushl %%ebx \n\t" /* save %ebx */
> > #endif
> > "cpuid \n\t"
> > "movl %%ebx ,%[ebx] \n\t" /* write the result into output var */
> >
> > #if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64)
> > "popq %%rbx \n\t"
> > #else
> > "popl %%ebx \n\t"
> > #endif
> > : "=a"(regs[0]), [ebx] "=r"(regs[1]), "=c"(regs[2]), "=d"(regs[3])
> > : "a"(index));
> >
> > printf("sse: %d\n", (regs[3]&(1<<25))?1:0); // edx
> > printf("sse2: %d\n", (regs[3]&(1<<26))?1:0);
> > printf("sse3: %d\n", (regs[2]&(1<<0 ))?1:0); // ecx
> > printf("sse4.1: %d\n", (regs[2]&(1<<19))?1:0);
> > printf("sse4.2: %d\n", (regs[2]&(1<<20))?1:0);
> > printf("avx: %d\n", (regs[2]&(1<<28))?1:0);
> > }
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ekg/vg/issues/153#issuecomment-155746757>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekg/vg/issues/153#issuecomment-155748780>.
>


-- 
Sent from my iPhone

**Comment by ekg** [comment]
So as long as they're compiling on a machine with /proc/cpuflags, we can
check by grepping for the flag names prior to build.

This might be the sanest thing to do, but also if people are working from
precompiled binaries we'll need to register the error dynamically.

**Comment by edawson** [comment]
True. I still think we should warn them as early as possible about any
incompatibilities. Maybe distribute a brief test script with the binary?

On Wednesday, November 11, 2015, Erik Garrison <notifications@github.com>
wrote:

> So as long as they're compiling on a machine with /proc/cpuflags, we can
> check by grepping for the flag names prior to build.
>
> This might be the sanest thing to do, but also if people are working from
> precompiled binaries we'll need to register the error dynamically.
>
> On Wed, Nov 11, 2015 at 11:51 AM, Eric T. Dawson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I think it should be flagged at compile time whether the hardware
> supports
> > all VG functions. If someone got all the way to alignment and then found
> > out their machine wouldn't do it I bet they'd be frustrated.
> >
> > On Wednesday, November 11, 2015, Erik Garrison <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > You could add it to gssw itself. Or, we could do the check prior to
> > > alignment.
> > >
> > > On Wed, Nov 11, 2015 at 11:40 AM, pd3 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > > > This checks whether sse3/sse4.1/sse4.2/avx is supported. I don't know
> > > what
> > > > parts of vg rely on which version, so don't where to add it:
> > > >
> > > > void check_cpu_features(void)
> > > > {
> > > > unsigned int index = 1; // eax=1:feature bits
> > > > unsigned int regs[4];
> > > >
> > > > __asm__ __volatile__(
> > > > #if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64)
> > > > "pushq %%rbx \n\t" /* save %rbx */
> > > > #else
> > > > "pushl %%ebx \n\t" /* save %ebx */
> > > > #endif
> > > > "cpuid \n\t"
> > > > "movl %%ebx ,%[ebx] \n\t" /* write the result into output var */
> > > >
> > > > #if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64)
> > > > "popq %%rbx \n\t"
> > > > #else
> > > > "popl %%ebx \n\t"
> > > > #endif
> > > > : "=a"(regs[0]), [ebx] "=r"(regs[1]), "=c"(regs[2]), "=d"(regs[3])
> > > > : "a"(index));
> > > >
> > > > printf("sse: %d\n", (regs[3]&(1<<25))?1:0); // edx
> > > > printf("sse2: %d\n", (regs[3]&(1<<26))?1:0);
> > > > printf("sse3: %d\n", (regs[2]&(1<<0 ))?1:0); // ecx
> > > > printf("sse4.1: %d\n", (regs[2]&(1<<19))?1:0);
> > > > printf("sse4.2: %d\n", (regs[2]&(1<<20))?1:0);
> > > > printf("avx: %d\n", (regs[2]&(1<<28))?1:0);
> > > > }
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ekg/vg/issues/153#issuecomment-155746757>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ekg/vg/issues/153#issuecomment-155748780>.
> > >
> >
> >
> > --
> > Sent from my iPhone
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ekg/vg/issues/153#issuecomment-155751314>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekg/vg/issues/153#issuecomment-155752202>.
>


-- 
Sent from my iPhone

**Comment by pd3** [comment]
An error at compile time would be good. However, it may as well be that the program is compiled on a machine which supports SSE4 and run on machine which does not. A dynamic check is more useful.

**Comment by jrandall** [comment]
I don't think the scope of this issue goes far enough - sure, it would be nice to have a meaningful error message explaining why the code doesn't work, but I don't accept the premise that the code needs to be written to target a specific CPU capability. Although it would be a pain to have to write different versions of your code for each CPU, you can use a helper library that will do that for you (such as sseplus: http://sseplus.sourceforge.net/). 

It looks like there are only one or two functions in gssw that actually use SSE 4.1 and these are both provided in sseplus. Using sseplus means that the function you call (in this case `_mm_max_epu16`) will use the SSE 4.1 instructions if available, otherwise fallback to SSE 2, or even work with a reference implementation on a CPU without any SIMD extensions. This should not be a hard change to make - just a change in header and adding sseplus to the build process. 

I also think adding a warning at compile and/or runtime would make sense when SSE support is not available or is a lower version that desired, but in that case it should be something more like "SSE 4.1 support not available, expect longer runtimes" rather than telling the user they are entirely out of luck.

**Comment by jrandall** [comment]
It looks like SDSL already has fallback code when SSE 4.2 is not available, but it is implemented as an `#ifdef` rather than a runtime check. If SDSL moves to runtime feature testing, that could fix that part of the issue?

I notice that in addition to the cross-cpu implementations of many of the sse functions, sseplus also has utility functions for sse feature testing. Might be good to use that: http://sseplus.sourceforge.net/group___c_p_u_i_d.html#g4f364a8a66e1682a5db1cf4a50c2ac95
