### ISSUE TITLE
NAN scores from Sublinear Li and Stephens

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1534]
`linear_haplo_structure::score` will sometimes claim to have successfully scored a haplotype, but also return a NAN score.

https://github.com/vgteam/vg/blob/d434bd337690b23df7c28b284cfee73ce1df59fe/src/haplotypes.cpp#L789-L801

This may indicate a problem with https://github.com/yoheirosen/sublinear-Li-Stephens because `observed->is_valid()` on the input haplotype is true, but the score from `observed_state.calculate_probability(observed)` still comes out as NAN.

My current plan to work around this is to just say that scoring failed if a NAN is encountered, but @yoheirosen might want to look at this and see if there is a real underlying problem.

**Comment by yoheirosen** [comment]
Looking into this. Something is off. Re-running some old experiments and
I'm getting -NAN where I didn't in the past
