### ISSUE TITLE
trouble contructing GSCA2 index with `vg index`

### ISSUE THREAD

**Issue by indraniel** [vgteam/vg#1548]
I been encountering some memory issues when constructing a GCSA2 index running `vg index`.  I've been trying to follow the ["Working with a whole genome variation graph"][0] recipe, but using Build 38, and the 1000 Genomes site VCFs mentioned here:

    ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/

I've been able to successfully run `vg construct`, perform Node ID coordination, build an xg index, and prune the relevant `vg` graphs for GCSA2 indexing using the following docker image: [`quay.io/vgteam/vg:v1.6.0-655-g8a272d34-t144-run`][1].   But, for the GSCA2 indexing step I get the following error after 17 hours of running:

    terminate called after throwing an instance of 'std::bad_alloc'

Show below is the full stack trace:

```
...
GCSA::GCSA(): Step 3 (path length 64 -> 128)
PathGraph::prune(): 11964592065 -> 11112739870 paths (9978740293 ranges)
PathGraph::prune(): 9745150320 unique, 64580345 redundant, 1146469235 unsorted, 156539970 nondeterministic paths
PathGraph::prune(): 390.1 GB in 24 file(s)
...
PathGraph::read(): File 23: Read 114800509 order-64 paths
PathGraph::extend(): File 23: Created 114834552 order-128 paths
PathGraph::read(): File 23: Read 114834552 order-128 paths
PathGraphBuilder::sort(): File 23: Sorted 114834552 paths
PathGraph::extend(): 11112739870 -> 12890262237 paths (57025430465 ranks)
PathGraph::extend(): 500.6 GB in 24 file(s)
GCSA::GCSA(): Step 4 (path length 128 -> 256)
PathGraph::prune(): 12890262237 -> 11812690872 paths (10903470837 ranges)
PathGraph::prune(): 10721002430 unique, 64580345 redundant, 810501681 unsorted, 216606416 nondeterministic paths
PathGraph::prune(): 442.1 GB in 24 file(s)
PathGraph::read(): File 0: Read 943121582 order-128 paths
PathGraph::extend(): File 0: Created 1029045131 order-256 paths
PathGraph::read(): File 0: Read 1029045131 order-256 paths
PathGraphBuilder::sort(): File 0: Sorted 1029045131 paths
PathGraph::read(): File 1: Read 1055710859 order-128 paths
PathGraph::extend(): File 1: Created 29887176473 order-256 paths
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Stack trace (most recent call last):
#18   Object "/vg/bin/vg", at 0x4ba868, in _start
#17   Object "/vg/bin/vg", at 0x119f9f9, in __libc_start_main
#16   Object "/vg/bin/vg", at 0x119f805, in generic_start_main
#15   Source "src/main.cpp", line 61, in main [0x405326]
#14 | Source "src/subcommand/subcommand.cpp", line 72, in operator()
      Source "/usr/include/c++/5/functional", line 2267, in operator() [0x7f43c7]
#13   Source "src/subcommand/index_main.cpp", line 1120, in main_index [0x792ab8]
#12   Source "/vg/deps/gcsa2/gcsa.cpp", line 493, in GCSA [0xd58477]
#11   Source "/vg/deps/gcsa2/path_graph.cpp", line 950, in extend [0xd931d1]
#10   Source "/vg/deps/gcsa2/path_graph.cpp", line 379, in sort [0xd90ff6]
#9  | Source "/vg/deps/gcsa2/path_graph.cpp", line 969, in resize
      Source "/usr/include/c++/5/bits/stl_vector.h", line 676, in read [0xd8d5da]
#8  | Source "/usr/include/c++/5/bits/vector.tcc", line 557, in _M_allocate
    | Source "/usr/include/c++/5/bits/stl_vector.h", line 170, in allocate
    | Source "/usr/include/c++/5/bits/alloc_traits.h", line 491, in allocate
      Source "/usr/include/c++/5/ext/new_allocator.h", line 104, in _M_default_append [0xd65c8a]
#7  | Source "src/tcmalloc.cc", line 1679, in cpp_alloc
      Source "src/tcmalloc.cc", line 1548, in tc_new [0x1263dcc]
#6    Source "src/tcmalloc.cc", line 1063, in handle_oom [0x1085d0d]
#5    Object "/vg/bin/vg", at 0x10c7f18, in __cxa_throw
#4    Object "/vg/bin/vg", at 0x10d1de0, in std::terminate()
#3    Object "/vg/bin/vg", at 0x10d1d95, in __cxxabiv1::__terminate(void (*)())
#2    Object "/vg/bin/vg", at 0x115f68c, in __gnu_cxx::__verbose_terminate_handler()
#1    Object "/vg/bin/vg", at 0x11b01b9, in abort
#0    Source "../sysdeps/unix/sysv/linux/pt-raise.c", line 35, in raise [0xd29bd9]
Aborted (Signal sent by tkill() 11 10019)
/gscmnt/gc2802/halllab/vg-test/build-gcsa2-index.sh: line 26:    11 Aborted                 (core dumped) ${VG} index -p -Z ${MAXMEM} -t ${THREADS} -b ${TMPDIR} -g ${OUTPUT_DIR}/wg.gcsa $(for i in $(seq 22; echo X; echo Y); do echo ${INPUT_DIR}/chr${i}.pruned.vg; done)
```

My exact `vg index` command line is this:

```bash
# via docker image: quay.io/vgteam/vg:v1.6.0-655-g8a272d34-t144-run
VG=/vg/bin/vg
MAXMEM=4096 # in gb (4 TB)
THREADS=32

WORKSPACE=/gscmnt/gc2802/halllab/vg-test
INPUT_DIR=${WORKSPACE}/pruned-graphs
OUTPUT_DIR=${WORKSPACE}/build-gcsa2-index
export TMPDIR=${WORKSPACE}/tmp

${VG} index -p -Z ${MAXMEM} -t ${THREADS} -b ${TMPDIR} -g ${OUTPUT_DIR}/wg.gcsa $(for i in $(seq 22; echo X; echo Y); do echo ${INPUT_DIR}/chr${i}.pruned.vg; done)
```

I'm running the above command on a machine with 54 hyperthreaded cores (I've allocated 32 cores/threads here), 4 TB of disk space, and 400 GB of RAM.  This seems more than the peak memory (100 GB RAM) and disk (1.5 TB) GCSA2 construction mentioned on the [wiki page][0].

Am I doing something amiss?  Otherwise, are there any suggestions on how to best diagnose and resolve my issue?  Is this a better question to ask in [jltsiren/gcsa2][2]?

Thanks in advance!

[0]: https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph
[1]: https://quay.io/repository/vgteam/vg?tab=tags
[2]: https://github.com/jltsiren/gcsa2

**Comment by jltsiren** [comment]
The number of paths in file 1 (chr2) in the fourth doubling step suggests that you have encountered the issue I fixed yesterday in #1542. There was a similar issue with build 37 and 1000 bp node size limit, but it was not present with node size limit 32 bp, as in the wiki example.

Basically, we add new head and tail nodes to the graph before building GCSA. Due to something we forgot over the years, these nodes were assigned ids immediately after the first graph file. In most cases, the head and tail replaced the first two nodes in the second graph file. If the second file is too fragmented, with many heads and tails, there will be a ridiculous number of 256 bp paths starting from the head node in that graph.

I believe this has been fixed, if you update to the latest master.

**Comment by indraniel** [comment]
I have another question.  Based on this recent fix, does this mean that I should restart the ["Working with a whole genome variation graph"][0] recipe from the beginning again (run `vg construct`, perform Node ID coordination, build an xg index, and prune the relevant vg graphs for GCSA2 indexing), or could I simply restart from the GCSA2 indexing step again using the graph files I've already generated?

[0]: https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph

**Comment by jltsiren** [comment]
You can continue with the existing graph files. The fix only changed kmer generation for GCSA construction.

**Comment by indraniel** [comment]
Looks like there was a new docker image of `vg` release on quay, [v1.6.0-810-g74916b4f-t147-run](https://quay.io/repository/vgteam/vg?tab=tags), a few hours ago.  I'll try using that for the GCSA index construction.

**Comment by indraniel** [comment]
I was able to successfully build the GCSA2 index with the latest docker image on [quay.io](https://quay.io/repository/vgteam/vg?tab=tags).  Thanks again for the help and insights!
