### ISSUE TITLE
`vg prune -r` error: `[vg prune]: mode --restore-paths requires --xg-name`

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1558]
Hi there

Following https://github.com/vgteam/vg/wiki/Index-Construction, "Complex graph, Without a reference or haplotypes" and  "Complex graph, With a reference but without haplotypes"

I tried building a complex graph with the reference, 

`vg prune -r graph.vg > graph.pruned.vg`

I get an error: 

`[vg prune]: mode --restore-paths requires --xg-name`

Without the reference, 

`vg prune -r graph.vg > graph.pruned.vg`

it appears to work. Why is this?

**Comment by jltsiren** [comment]
You are using an old version of VG with the reference. I removed the `--xg-name` requirement before writing up the documentation.

**Comment by evanbiederstedt** [comment]
@jltsiren I see, thanks. 

I'll try the latest version.

**Comment by evanbiederstedt** [comment]
@jltsiren This is correct. The above error is due to an older version of vg, circa Feb. 2018

Thanks for the help
