### ISSUE TITLE
The proposal for `vg inject` command

### ISSUE THREAD

**Issue by 6br** [vgteam/vg#1561]
I would like to add `vg inject` subcommand to convert bam file with CIGARs to gam file  since it should be useful to lift over alignments from `linear` genome to the variation graph.

Currently, `vg view -b -G` supports the conversion from bam to gam, and read sequence and quality can be converted. But it discards CIGARs. So, to convert from bam with CIGARs to gam, @ekg and I came to the agreement to add a new subcommand in RDF summit 3(#1544).

I think `vg inject` commands can be described as below. I will start to implement with a simple set of args to clarify the concept of `vg inject`.

```
usage: vg inject [options] >output.gam

options:
    -x, --xg-name FILE      use the graph in this xg index
    -b, --bam-name FILE     input BAM file
    -s, --sam-name FILE     input SAM file
    -c, --cram-name FILE     input CRAM file
    -t, --threads N         number of threads to use
    -p, --from-path NAME    inject from this path (many allowed, default: all in bam)
    -F, --from-paths FILE   inject from nonoverlapping path names listed in FILE (one per line)
```

If you have any suggestions or ideas, comments are welcome.

**Comment by ekg** [comment]
:+1:

**Comment by 6br** [comment]
#1564 has been merged. Now we can use `vg inject` to lift over alignments.
