### ISSUE TITLE
Index Translation

### ISSUE THREAD

**Issue by MohammedJanahi** [vgteam/vg#1569]
1. What you were trying to do
              Go back and forth between a sequence position and a node ID. 
         
2. What you wanted to happen
              I would like a way translate from node ID to position in the sequence and back.
              Something like: 
                           vg translate x.vg --position X
                           and that would return the node id or id(s) where position X in the sequence would be. 
                           (meaning the X'th position of the sequence used to build this vg is in/around node id Y)
                           and 
                           vg translate x.vg --node_id X
                           and this would give me the positions (start and end) of the sequence located in 
                           node with ID X

3. What actually happened
             I don't know if such a feature exists...

**Comment by adamnovak** [comment]
You need to have indexed your graph into an xg file, but `vg find` can do this.

Running `vg find -x graph.xg -n 123 -P chr21` will find the starting offset of the first instance of node 123 in path "chr21". It outputs a table of node ID and position, and you can use multiple -n options to look up multiple nodes.

To go the other way, you can use `vg find -x graph.xg -p chr21:9999 >part.vg` to extract, into part.vg, the subgraph consisting of the node at offset 9999 in path "chr21". You can also use a range like `chr21:100-200`. Then you have to look at the graph to find out what node or nodes you got; `vg view -j part.vg | jq '.node[].id'` will do that.

This is a bit complicated, especially going from a linear position to a node ID. We could definitely present an easier-to-use interface, maybe as part of the `vg surject` command (which maps alignments from a graph to a linear coordinate space) and the upcoming `vg inject` which does the opposite. We also probably want to better account for the case where a node appears multiple times in the same path, and we want to report node orientation.

I don't think we can support the concept of "the X'th position of the sequence used to build this vg" though; you're probably always going to need to specify a name for the linear path you want to work with. We need this to distinguish between multiple chromosomes stored in the same graph file, and between multiple named paths (like chr6 and the MHC alt loci) that might be in the same connected component.
