### ISSUE TITLE
Snarl cutting can make reads worse on primary

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1583]
Here is a read, in its mapeval-accepted correct alignment:

```
{"sequence": "CCAGAACCACACTGTCTTGGTGAGCGTAGCCTTGTAGTAAGTTTTGCCGCACTGTCTTGGTTGGCGTAGCCTTCGTAGTAAGTTTTGATCGCGCTGTCTTGGTTGGCGTAGCCTTGTAGTAAGTTTTGATCGCGCTGTCTTGGTTGGC", "identity": 0.95945945945945943, "path": {"mapping": [{"position": {"node_id": 1432167, "offset": 22}, "edit": [{"to_length": 10, "from_length": 10}], "rank": 1}, {"position": {"node_id": 1432168}, "edit": [{"to_length": 15, "from_length": 15}, {"to_length": 1, "from_length": 1, "sequence": "G"}, {"to_length": 16, "from_length": 16}], "rank": 2}, {"position": {"node_id": 1432169}, "edit": [{"to_length": 4, "from_length": 4}, {"from_length": 1}, {"to_length": 27, "from_length": 27}], "rank": 3}, {"position": {"node_id": 1432170}, "edit": [{"to_length": 1, "sequence": "C"}, {"to_length": 17, "from_length": 17}, {"to_length": 1, "from_length": 1, "sequence": "C"}, {"to_length": 14, "from_length": 14}], "rank": 4}, {"position": {"node_id": 1432171}, "edit": [{"to_length": 1, "from_length": 1}, {"to_length": 1, "from_length": 1, "sequence": "G"}, {"to_length": 21, "from_length": 21}, {"to_length": 1, "from_length": 1, "sequence": "T"}, {"to_length": 3, "from_length": 3}, {"to_length": 1, "from_length": 1, "sequence": "G"}, {"to_length": 4, "from_length": 4}], "rank": 5}, {"position": {"node_id": 1432172}, "edit": [{"to_length": 10, "from_length": 10}], "rank": 6}]}, "mapping_quality": 14, "name": "seed_102_fragment_93758_2", "quality": "HyEhJSMjIyMjHiUeHhskIyAnKSkpKSkpKScmIyMmJCcmIiQnJCcmJygpKSkpKSkpKSgoKBccISImJyYmKCYnJygpKSknJScnJicnHyUlJSUlJCMkJCMjIyQeISEjIyMjIyMjIyMjIyIjIyMjIyMbHh4jIyMjIyMjIiAiHSIiIyMjIyIiIiIiHxceISMjIyIhISMjIw==", "score": 120}
```

Save that as read.gam.

You can replicate it on Kolossus; it aligns starting at node 1432167:

```
vg mpmap -x /cluster/home/anovak/build/vg/gbwt-experiment/21/gbwt-graphs-v4/primary.xg -g /cluster/home/anovak/build/vg/gbwt-experiment/21/gbwt-graphs-v4/primary.gcsa -G read.gam -S > correct.gam
```

But if you turn on snarl cutting, you get a different, wrong alignment starting at node 1432187, with a score 10 points lower:

```
vg mpmap -x /cluster/home/anovak/build/vg/gbwt-experiment/21/gbwt-graphs-v4/primary.xg -g /cluster/home/anovak/build/vg/gbwt-experiment/21/gbwt-graphs-v4/primary.gcsa --snarls  /cluster/home/anovak/build/vg/gbwt-experiment/21/gbwt-graphs-v4/primary.snarls  -G read.gam -S > wrong.gam
```

Poking around in the debug logs, it looks like snarl cutting is preventing a multipath alignment that looks like this from being broken up into multiple components:

![image](https://user-images.githubusercontent.com/5062495/38112005-79898e4c-3355-11e8-910f-b1bdb75735f9.png)

Because after snarl cutting it looks like this:

![image](https://user-images.githubusercontent.com/5062495/38112024-8939da90-3355-11e8-90d8-1b22b002b8b6.png)

This is the graph that *should* produce the correct alignment, which doesn't get found.

**Comment by jeizenga** [comment]
I have a PR that fixes the problem on this particular read, which was something that I would call a bug. I don't think this constitutes a demonstration that I've fixed all problems with the performance degradation from snarl-cutting. @adamnovak can you rerun those analyses with the new code and see how it looks?

**Comment by adamnovak** [comment]
I think the right thing to do is pull the new code into my new evaluation
pipeline and run the comparison with that. If it's in vg master, I guess I
can trigger a Docker build and plug it in.

-Adam
