### ISSUE TITLE
'make test' fails on some systems on master, possibly because of different md5sum versions

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1600]
My undergrad @emikoifish was trying to get vg set up on her Macbook but kept having the integration tests fail. We dug into it, and the failures were also occurring on vgteam/vg/master. Moreover, the output on her machine of the vg commands was, as far as I can tell, identical to the results I was getting on my own machine. However, the hash digest that the integration tests were producing was different. I wonder if it might be some difference in the md5sum versions. 

(One of) the specific command from the integration tests that produced a different result was
```
vg view -Jv msgas/inv-mess.json | vg mod -u - | md5sum 
```

**Comment by adamnovak** [comment]
md5sum should always produce the same hash for the same input; otherwise it's not md5sum.

But I to recall the GNU md5sum and the BSD md5sum producing differently-formatted outputs; I think one emits a bare hash and the other will emit the filename and the hash even when hashing standard input (with a placeholder filename).

**Comment by jltsiren** [comment]
Is this in tests 19 and 21 of `14_vg_mod.t`? They have been failing for months on my Mac, even though the Travis Mac tests are successful. I guess this might be a locale issue or something related to OS or compiler versions.

This is fundamentally a protobuf issue, as it does not impose a specific storage order. The graph files generated by

```
vg view -Jv msgas/inv-mess.json | vg mod -u -
```

are bitwise different on my Mac and a Linux server, but they still encode the same graph.

**Comment by jeizenga** [comment]
For the time being I've just told her to ignore the failures, but I'll add this to my long-running gripe with the way the integration tests are designed.

**Comment by adamnovak** [comment]
If it's a Protobuf bitwise file difference, I think the approach we usually
take to standardizing the bitwise representation of the graph is to `vg
view` to GFA and sort that text.
