### ISSUE TITLE
mac OSX installation failed with no such instruction: `vzeroupper'

### ISSUE THREAD

**Issue by mscampbell** [vgteam/vg#162]
I saw your talk at CSHL and thought that vg might be useful for one of my projects. I thought I'd get it running on my laptop so I could explore it a little. I followed the installation instructions for mac OSX including installing the dependencies with macports, and selected the gcc compiler

sudo port install gcc49 libtool jansson jq cmake pkgconfig autoconf automake libtool
sudo port select gcc mp-gcc49

I symlinked glibtoolize to libtoolize as mentioned in a previous issue and ran

git clone --recursive https://github.com/ekg/vg.git
cd vg
./source_me.sh && make static

I get the following error

. ./source_me.sh && cd deps/rocksdb && /Applications/Xcode.app/Contents/Developer/usr/bin/make static_lib && mv librocksdb.a /Users/mcampbel/vg/lib && cp -r include/\* /Users/mcampbel/vg/include/
  GEN      util/build_version.cc
  GEN      util/build_version.cc
  CC       db/builder.o
/var/folders/qg/r0ndzbq53tddzxypnnw3zmzw0000gn/T//ccdVL3fy.s:1582:no such instruction: `vzeroupper'
/var/folders/qg/r0ndzbq53tddzxypnnw3zmzw0000gn/T//ccdVL3fy.s:1665:no such instruction:`vzeroupper'
/var/folders/qg/r0ndzbq53tddzxypnnw3zmzw0000gn/T//ccdVL3fy.s:1760:no such instruction: `vzeroupper'
**(more lines like those above)**
make[1]: **\* [db/builder.o] Error 1
make: **\* [lib/librocksdb.a] Error 2

I googled around and didn't find much. Am I missing something simple?

**Comment by ekg** [comment]
I'm not sure as I don't use OSX. Perhaps someone who does have a Mac laptop
could help out?

Some people have been using vg in virtual machines on macs.

**Comment by edawson** [comment]
Howdy @mscampbell - I believe this is an error that shows up when building on Yosemite, and I haven't figured out a way around it yet. It doesn't seem there's good support for AVX instructions in Yosemite and this chokes the RocksDB build. Changing the compiler flags doesn't seem to resolve it, much to my chagrin. The most recent OSX release (El Cap) makes things a bit better but it's still not an easy build. I believe @adamnovak has built on El Cap successfully.

 I've been building and running vg in a virtual machine and on docker, both with Ubuntu 14.04. It's easy to build and run, and the static binary works fine on docker (especially if you use an Ubuntu:latest image).

Sorry for the build troubles - it's certainly not something you missed. It's had me stumped for a week or two now and I haven't taken the time to investigate further. I'm hoping to iron out some of the kinks in the next month once I've made progress on some other things.

**Comment by glennhickey** [comment]
Hi all,

I've been using vg on a Macbook Air for some time.  I have El Capitan now,
but I think it was working on Yosemite too.  The instructions in the README
are exactly the recipe I've used to do this, and I have made the odd pull
request here and there to keep things running on Mac.

Unfortunately, I've fallen a bit behind the latest master branch, which has
seen a number of pretty drastic improvements to the build organization over
the past weeks.  Chances are, I (or some other Mac user) will have to go in
and hack the Makefile again to bring Mac compatibility back.  I don't think
I ever got a static build to work on my Mac though, so building a
non-static version (if that's still possible) would definitely be something
to try right away.

At Sant Cruz, we're frozen on this older version for the next month or so
as we use vg to make some results for a paper.  It works fine on my Mac.
If you're just looking to try it out, it may be suitable for your needs:

https://github.com/adamnovak/vg/releases/tag/graph-bakeoff-0.2

cheers
-Glenn

**Comment by adamnovak** [comment]
I think you can just crib the options from this bit of the old Makefile and put them in your Makefile:

https://github.com/ekg/vg/blob/master/Makefile.old#L24-L28

```
	CXXFLAGS:=$(CXXFLAGS) -msse2 #needed to link against gssw
	LDFLAGS:=$(LDFLAGS) -L/opt//local/lib/ # needed for macports jansson
	STATICFLAGS= # -static doesn't work on OSX unless libgcc compiled as static. 
	ROCKSDB_PORTABLE=PORTABLE=1 # needed to build rocksdb without weird assembler options
```

If someone could PR that bit of `Makefile.old` into the new `Makefile`, that would also be great.

Also, don't try and build static on OS X, as apparently we haven't gotten it to work yet.

You could also try adding a '-Wa,-q' (no spaces) as recommended [here](http://stackoverflow.com/a/19342603) to try the clang assembler with the gcc compiler.

@glennhickey Is there a good reason the clang compiler won't work?

**Comment by adamnovak** [comment]
On a related note, [Travis supports OS X builds](http://docs.travis-ci.com/user/osx-ci-environment/), so if we do actually intend to advertise support for OS X, we should really have CI testing it.

**Comment by mscampbell** [comment]
Thanks for the insights. I am indeed using Yosimite. I tried dropping in the Makefile options from @adamnovak, and I get the same errors. I've been meaning to look into Docker anyway, I'll probably try that next. At the end of the day it will end up on a unix server, so it's not a deal breaker if I can get it to build on OSX.

**Comment by glennhickey** [comment]
@adamnovak unless apple's changed something very recently, you can't use
clang from xcode because it doesn't support omp.

**Comment by adamnovak** [comment]
We haven't had the mysterious vzeroupper issue show up in a long time. Maybe it's gone?

I'm going to close this and if someone reports it again we can use that issue.
