### ISSUE TITLE
Included path semantics: should we prevent partial mappings?

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#163]
When we include a path in the graph, we may end up with it starting within a node. This can make certain analyses difficult, and my sense is that we should "encourage" included paths to start and end at node boundaries.

I can add a function to be called in normalization to break up the nodes and do the right things to the paths.

Thoughts?

**Comment by glennhickey** [comment]
Sounds like a great idea to me.

**Comment by adamnovak** [comment]
I'm going to assume this has been handled. Certainly a lot of the code assumes that non-Alignment paths use their entire nodes.
