### ISSUE TITLE
How to merge graphs from whole genome variation graph

### ISSUE THREAD

**Issue by kevyin** [vgteam/vg#1640]
Hi 

This guide https://github.com/vgteam/vg/wiki/working-with-a-whole-genome-variation-graph
generates a group of vg graphs per chromosome

I've generated gams by aligning reads to the split indexes and now want a merged graph to use for vg stats 
`vg stats <graph.vg> -a aln.gam > aln.gam.stats`

vg concat looks like it may modify nodeids which may be detrimental?

Does this work?
`vg view -V 1.pruned.vg 2.pruned.vg ...etc -v > merged.vg`

Thanks

**Comment by ekg** [comment]
If the graphs have _non overlapping ID space_ then you actually just need to concatenate them together:

`cat 1.vg 2.vg 3.vg >all.vg`

If they have overlapping ID space, then you need to determine if you should make a joint ID space for all of them, which would be the case for separate chromosomes, or if you want to just overlay them, which is the case when you have subsets of a larger graph. If you want to join the ID space you do:

```
vg ids -j 1.vg 2.vg 3.vg
cat 1.vg 2.vg 3.vg >all.vg
```

If you want to overlay you can use vg view to clean up duplicates:

```
cat 1.vg 2.vg 3.vg | vg view -Vv - >all.vg
```

**Comment by kevyin** [comment]
Thanks! In this case the ids should be _non overlapping_ since `vg ids` was already run on them.

The overlay command is sure to be handy 

Cheers
