### ISSUE TITLE
clarification request: vg construct without an input VCF

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1650]
Hi

Could you clarify what the following command does:

    $ vg construct -r hg38.fa > output.vg

Given that I'm only using the flag `-r`, whereby

    -r, --reference FILE  input FASTA reference (may repeat)

I would think that this would be the same command as an empty VCF, which should produce a simple, non-branching graph, e.g. 

   ... -A-C-G-T-A-C-G-T- ...

Is this understanding correct?

**Comment by evanbiederstedt** [comment]
Hi @ekg 

Thanks for the response. 

> Note that the node size is limited to 1000 due to requirements of some
algorithms in vg (gcsa2 indexing and the alignment model).

I'm trying to better understand how this would effect my use case above. Let's say I were to use the entire FASTA `hg38.fa` for 

`$ vg construct -r hg38.fa > output.vg`

Here, the node size limit of 1000 wouldn't apply, as our input `hg38.fa` is a typical human reference?

**Comment by adamnovak** [comment]
The node isze is limited by breaking nodes that would be oversized into multiple parts. So you would not get 25 nodes, but about (total genome length / 1000) nodes.

1000 is not a maximum number of nodes (that is effectively unlimited, up to about 2^64). It is a limit on the maximum length of any particular node, in bases.

**Comment by evanbiederstedt** [comment]
@ekg @adamnovak Thank you, I think I understand now what it meant by `node size`, which is different from `maximum number of nodes`.
