### ISSUE TITLE
make with `-j` requires many repetitions to fully build vg

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#166]
As described in the title, parallel builds seem to never work (even with low parallelism). So I think there is something very borked with the dependencies in the Makefile.

Is there a nice tool somewhere for debugging Makefiles?

**Comment by edawson** [comment]
This PR should remedy this, for the moment: https://github.com/ekg/vg/pull/186

As to debugging Makefiles, I haven't found anything. I think a simple Perl/Python script that made sure every local include in a header file was matched to a corresponding dependency in that file's Make rule would go aways towards accomplishing this. It also seems that Make does not pass signals to sub-Makes - if a single Make process dies, its siblings don't fail out immediately. There are probably some Make options that would help us out, but when I debugged the PR I manually reviewed the output or pushed the logs out to a file and grepped for "error." There should exist a better way.
