### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by saiz06** [vgteam/vg#1673]
In what scenario would  xg and GCSA2 based index be recommended? I want to generate a VG graph and then push it to SPARK for further processing of the graph.

**Comment by jeizenga** [comment]
The basic breakdown is this:

- VG graphs are mutable and manipulable, but memory intensive.
- XG is a more memory efficient but static graph implementation.
- GCSA2 is substring search index for a graph. 

In general, we tend to use VG objects when we're constructing or modifying the graph, and then we switch to using a XG once we're finished and we just want to compute against the graph. If you're going to do read mapping with `vg`, then you also need a GCSA2 index. 

Without knowing what you want to do in your SPARK pipeline I can't be completely sure which data structures would be most appropriate, but I hope this helps you figure it out!

**Comment by saiz06** [comment]
Thanks. Is GCSA2 indexing supported by SPARK?
