### ISSUE TITLE
vg find -G error (xg::XG::node_sequence(int64_t) const: Assertion `rank != 0')

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#1676]
1. What you were trying to do:

I mapped CCS long reads to variation graph consisting of several hundred smaller subgraphs (e.g. 99.1.vg) in a merged id space. I tried to accumulate the graph touched by the alignments in the GAM not using the full variation graph but the subgraph and the GAM as input. 

2. What you wanted to happen

Goal was to further subset the subgraph based on alignments to the nodes.

3. What actually happened:

```
vg: src/xg.cpp:1333: std::__cxx11::string xg::XG::node_sequence(int64_t) const: Assertion `rank != 0' failed.`
```

4. What data and command line to use to make the problem recur, if applicable

```
vg find -G 9944.ccs.gam -x 99.1.xg > 99.1.sub.vg
```

5. Stack trace:

```
Stack trace (most recent call last):
#11   Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x4bffd8, in _start
#10   Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x13f55e9, in __libc_start_main
#9    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x13f53f5, in generic_start_main
#8    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x4069d6, in main
      Source "src/main.cpp", line 61, in main [0x4069d6]
#7    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x80b3c7, in vg::subcommand::Subcommand::operator()(int, char**) const
    | Source "src/subcommand/subcommand.cpp", line 72, in operator()
      Source "/usr/include/c++/5/functional", line 2267, in operator() [0x80b3c7]
       2264:     {
       2265:       if (_M_empty())
       2266:    __throw_bad_function_call();
      >2267:       return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
       2268:     }
       2269:
       2270: #if __cpp_rtti
#6    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x79ef88, in main_find(int, char**)
      Source "src/subcommand/find_main.cpp", line 683, in main_find [0x79ef88]
#5    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0xad0f57, in xg::XG::node(long) const
      Source "src/xg.cpp", line 1327, in node [0xad0f57]
#4    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0xaabdcb, in xg::XG::node_sequence[abi:cxx11](long) const
      Source "src/xg.cpp", line 1333, in node_sequence [0xaabdcb]
#3    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x13f8f6d, in __assert_fail
#2    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x13f8f0a, in __assert_fail_base
#1    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0x1405d09, in abort
#0    Object "/ebio/abt6_projects9/1001_genomes_calls/data/nlrome/vg/bin/vg", at 0xd879c9, in raise
      Source "../sysdeps/unix/sysv/linux/pt-raise.c", line 35, in raise [0xd879c9]
```

6. Stats are here (vg stats -a 9944.ccs.gam 99.1.vg):

Total alignments: 20205
Total primary: 20205
Total secondary: 0
Total aligned: 18512
Insertions: 995631 bp in 110348 read events
Deletions: 14019 bp in 5952 read events
Substitutions: 1530287 bp in 371757 read events
Softclips: 10726373 bp in 37420 read events
Unvisited nodes: 103/482 (153 bp)
Single-visited nodes: 3/482 (4 bp)
Significantly biased heterozygous sites: 0/0

7. Data is here:

https://drive.google.com/open?id=12ZwIPSxu2QJNPhIIGHYSoR4Rp2c6wggS

**Comment by adamnovak** [comment]
I don't think this is going to work quite the way you are trying to do it. Using `vg find` to pull out the subgraph touched by a GAM requires the xg index of the full graph, not a subgraph. It needs to be able to look up all the nodes that were touched by each alignment, and it is crashing because it is looking for a node that is touched but isn't in the subgraph you are giving it.

If you did the mapping with vg, you must have generated a whole-graph xg index to pass to `vg map`, right? You should be able to pass that to `vg find` instead of the index of each subgraph's index.

**Comment by fbemm** [comment]
Forgot to add that. Did it right after testing with the subgraphs and the error is exactly the same.

**Comment by adamnovak** [comment]
OK, I've dug into this, and it looks like the mapper here is producing alignments that have just one mapping that is an insert of the whole read, with the position unset (which defaults to node 0, which isn't in the graph).

What version of vg are you using? @ekg says he has dissuaded the mapper from doing that recently.

I'm going to patch `vg find` to pass over this sort of thing without error.

**Comment by fbemm** [comment]
I used version v1.7.0-24-g469ba20.
