### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by abeconnelly** [vgteam/vg#168]
When compiling, I get the following errors:

```bash
g++ -O3 -std=c++11 -fopenmp -g -L./ -L/usr/local/lib/ -lprotobuf -lz -pthread -o bin/example cpp/example.pb.o obj/main.o -I./ -Isrc -Iobj -Icpp -L./ -L/usr/local/lib/ -lprotobuf -lz && cp src/*.h* include/
Makefile:36: recipe for target 'bin/example' failed
[libprotobuf WARNING google/protobuf/compiler/parser.cc:492] No syntax specified for the proto file. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
cpp/example.pb.o: In function `GetEmptyStringAlreadyInited':
/scratch/bio-tool/vg/include/google/protobuf/generated_message_util.h:84: undefined reference to `google::protobuf::internal::empty_string_'
cpp/example.pb.o: In function `google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(char const*, int, google::protobuf::internal::WireFormat::Operation, char const*)':
/scratch/bio-tool/vg/include/google/protobuf/wire_format.h:328: undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
cpp/example.pb.o: In function `GetEmptyStringAlreadyInited':
...
```

There are many more errors and I've only shown the first few lines.

I tracked it down to the `deps/xg/stream` directory where I found the following line in the `Makefile` there:

```bash
...
LD_LIB_FLAGS=-L./ -L/usr/local/lib/ -lprotobuf -lz
...
```

I believe this is a discrepancy between my system installed `protoc` and the one included with `vg`:

```bash
$ which protoc ; protoc --version
/usr/local/bin/protoc
libprotoc 2.5.0
$ $VG_DIR/bin/protoc --version
libprotoc 3.0.0
```

Changing `$VG_DIR/deps/xg/stream/Makefile` to include protocol buffer library as included with `vg` allows me to compile without issue.  The changes are:

```diff
$ git diff Makefile
diff --git a/Makefile b/Makefile
index f017530..bf869ac 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ OBJ_DIR:=obj
 PROTO_PATH:=
 
 INCLUDES=-I./ -Isrc -Iobj -Icpp
-LD_LIB_FLAGS=-L./ -L/usr/local/lib/ -lprotobuf -lz
+LD_LIB_FLAGS=-L./ -L/scratch/bio-tool/vg/deps/protobuf/src -lprotobuf -lz
 
 
 all: $(BIN_DIR)/example
```

Where `/scratch/bio-tool/vg` is the place I've cloned the `vg` repo into (that is, the `$VG_DIR` directory above).

My apologies for not issuing a pull request but if I understand this right, `xg` is actually another git repo and I don't know how (or if) you want to co-ordinate passing in the location of the local protocol buffer libraries.

**Comment by ekg** [comment]
What command did you use to build? `. ./source_me.sh && make` ?

**Comment by abeconnelly** [comment]
Yes, sorry, I should have said.  I got a compilation error when running `. ./source_me.sh && make` (I was following the directions from the README) though the above output from me going into the `deps/xg/stream` directory and running `make` myself.

`protoc` and the corresponding libraries look to be compiled and 'installed' locally correctly but you can see that the `Makefile` in `deps/xg/stream` is using the system wide protocol buffers libraries.

**Comment by edawson** [comment]
This looks like a remnant of something I did a while back during testing. We should just remove the ```-/usr/local/lib``` and that should do it. Seems that's taking precedence over the path fiddling we do with source_me.

**Comment by ekg** [comment]
Thanks for checking up on this. Do you have a patch handy?

**Comment by edawson** [comment]
Here's a patch - I had to rename the extension to txt for Github to let me upload it. It builds and tests out on my machine, but just let me know if it doesn't work for y'all.

[fix_makefile.txt](https://github.com/ekg/vg/files/49559/fix_makefile.txt)

**Comment by ekg** [comment]
This lazy guy is looking for a PR too :)

**Comment by adamnovak** [comment]
Looks like we now only add `/usr/local/lib` to the libraries path on Mac, when hunting about for Macports-based dependencies.

I'm going to mark this as closed, and if it's breaking for other people we can have a new issue.
