### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#1690]
vg is moving to a regular release schedule, but first we need to debate and decide a few items:

1. How long should backwards compatibility be maintained or guaranteed? 

2. Are we going to go with full semantic versioning, even if releases are on set time intervals?

3. Do we push all releases to Docker / package managers, or only major ones?

**Comment by adamnovak** [comment]
What we have been doing is releasing 1.X.0 with a grab bag of compatible and incompatible CLI, internal API, and format changes, and not really following semantic versioning at all. I don't think we can adopt semantic versioning without figuring out exactly what the API surface is (e.g. does a removed CLI flag necessitate a major version bump? What about a new Protobuf field with semantics that impinge on the interpretation of old fields? What about a new version of xg that can't be read by older builds? What about an internal refactoring away of methods?).

I definitely don't want to get sucked in to maintaining a bunch of 1.x, 2.x, 3.x etc. release branches and trying to backport patches.

We definitely want to be pushing our releases to the main vgteam/vg Quay.io, and keeping our development Dockers out of there.

**Comment by adamnovak** [comment]
I've made an issue for a 1.8.0 release: https://github.com/vgteam/vg/issues/1691

**Comment by edawson** [comment]
I'm going to make a wiki page on releases describing the process and linking to the docker repo. Closing this.
