### ISSUE TITLE
Release vg 1.8.0

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1691]
1. [x] Create a new **v1.8.0** release [on Github](https://github.com/vgteam/vg/releases/new)  
2. [x] Tag a commit with the desired **v1.8.0** release version on Github
3. [x] Build and upload a static Linux binary for the release  (Mac OS X can't build static binaries.)
    ```
    cd vg
    git fetch --tags git fetch --tags https://github.com/vgteam/vg.git
    LATEST_TAG="$(git describe --tags `git rev-list --tags --max-count=1`)"
    git checkout "${LATEST_TAG}"
    make static
    ```
4. [x] In the new release describe:
    1. Any breaking changes (e.g. a change in vg.proto)
    2. Any updated or new submodules
    3. Any new dependencies.
    It may help to consult the log of commits since the last release.
5. [x] Kick off a build of the Docker image. If you already have a clone of https://github.com/vgteam/vg_docker you can do:
    ```
    cd vg_docker
    git checkout master
    git pull origin
    git submodule sync
    cd vg
    git fetch --tags origin
    LATEST_TAG="$(git describe --tags `git rev-list --tags --max-count=1`)"
    git checkout "${LATEST_TAG}"
    cd ..
    git add vg
    git commit -m "Release vg ${LATEST_TAG}"
    git push origin
    ```
6. [x] Create a milestone for the next release [here](https://github.com/vgteam/vg/milestones/new), named **v1.9.0**, due in 6 weeks.
7. [x] Create an issue **Release vg v1.9.0** for the next release [on the Gihub issues page](https://github.com/vgteam/vg/issues) and assign it to the milestone.
8. [x] Close the previous release milestone [here](https://github.com/vgteam/vg/milestones), and the corresponding release issue.
9. [x] Update [this wiki page](https://github.com/vgteam/vg/wiki/Releases) with the next release version, date, issue, and milestone.

**Comment by ekg** [comment]
For the static binary, you may want to use `strip` to make it small enough to reasonably download (e.g. 10 mb rather than 300).

**Comment by adamnovak** [comment]
We should have building a Docker image on the list.

I'm worried that `strip` will pull out all the debugging symbols that make
the stack trace code useful. We should have a look through the strip
options and see if there is a way to make the binary smaller while still
having useful crash dumps.
