### ISSUE TITLE
vg sim silently accepts strings as seeds but doesn't produce consistent output

### ISSUE THREAD

**Issue by twrightsman** [vgteam/vg#1704]
> Please describe:
>
> 1. What you were trying to do

Simulate the same read set using a specific string as a seed: "test_alignment".

> 2. What you wanted to happen

On multiple calls of `vg sim` using the same string as a random seed, output the exact same read set.

> 3. What actually happened

`vg sim` produced different read sets on subsequent calls with the same seed.
**Using an integer seed causes the expected behavior.**

> 4. What data and command line to use to make the problem recur, if applicable

```
$ vg sim -a -x test_alignments.xg -s "test_alignment" -P Path1 -l 10 -n 10 -e 0.01 -i 0.01 > test_alignments.Path1.iter1.gam
$ vg sim -a -x test_alignments.xg -s "test_alignment" -P Path1 -l 10 -n 10 -e 0.01 -i 0.01 > test_alignments.Path1.iter2.gam
$ vg sim -a -x test_alignments.xg -s "test_alignment" -P Path1 -l 10 -n 10 -e 0.01 -i 0.01 > test_alignments.Path1.iter3.gam
```

I'm not sure if the PRNG that `vg sim` is using supports string seeds (the [documentation](http://www.cplusplus.com/reference/random/mersenne_twister_engine/seed/) suggests it does) but could `vg sim` at least emit a warning or an error if the seed is invalid?

**Comment by glennhickey** [comment]
Yeah, invalid seeds get ignored.  atoi() converts them to 0, which vg sim
treats as "no seed," and then comes up with a random seed using the clock.

In fact, invalid strings for pretty much any parameter value in vg will
silently be treated as 0, as they tend to go through atoi or atof or
stringstream.  We could save a lot of confusion by switching to something
that aborts with a meaningful error (stoi/stof wrapped up to give more
informative exceptions would do the trick).



On Tue, May 29, 2018 at 4:49 AM, Travis Wrightsman <notifications@github.com
