### ISSUE TITLE
Mac and raptor still can't play nicely

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#1705]
1. What you were trying to do
Build on Mac OS / Travis.

2. What you wanted to happen
A clean recursive clone / push to a PR builds a working vg executable.

3. What actually happened
I get the dreaded "yycleanup not found" error (#1658 and elsewhere). What have we done / can we do to prevent this? I end up patching the raptor install with Adam's lexer.zip fix every time I do a fresh clone.

4. What data and command line to use to make the problem recur, if applicable
Both of these fail on Mac OS. They work on Linux now.
`git clone --recursive https://github.com/vgteam/vg && cd vg && make -j 4`
`git clone --recursive https://github.com/vgteam/vg && cd vg && git checkout safe-svs && git submodule update --init --recursive && make -j 4`

This is the last block to the `safe-svs` pull request. It passes all the tests on Linux and Jenkins.

**Comment by adamnovak** [comment]
We have a fix for this in the makefile in master:

https://github.com/vgteam/vg/blob/3787f6bf624f8f598680ccaf406ea162fbf4e4bb/Makefile#L334

It should delete all the yycleanup lines from the lexer when vg builds raptor.

Is your PR up to date with that fix?

**Comment by edawson** [comment]
Awesome, I'll close this. It's definitely in the PR Makefile now.

**Comment by edawson** [comment]
It's not that line, which is definitely in the Makefile. It seems the make step right after that is failing:

```
[ 37%] Building C object src/CMakeFiles/raptor2.dir/turtle_parser.c.o

turtle_parser.c: In function 'yysyntax_error':

turtle_parser.c:1092:7: error: multiple default labels in one switch

       default: yyformat = YY_("syntax error");

       ^~~~~~~

turtle_parser.c:1085:5: error: this is the first default label

     default: /* Avoid compiler warnings. */

     ^~~~~~~

make[3]: *** [src/CMakeFiles/raptor2.dir/turtle_parser.c.o] Error 1

make[2]: *** [src/CMakeFiles/raptor2.dir/all] Error 2

make[1]: *** [all] Error 2

make: *** [lib/libraptor2.a] Error 2
```

I can't replicate this locally. It kind of seems like the second default statement gets pushed in during compilation, as it's not in the source code from what I can see.

**Comment by adamnovak** [comment]
I'm seeing this double-default broblem in all the mac tests now. How long have people been merging over failed mac tests???

I think Bison started adding a default label to case statements that it didn't add before. Raptor's script to "fix" Bison's output also does that:

https://github.com/vgteam/raptor/blob/2b56e14d04e511565febeea87754af7ca80e3829/scripts/fix-bison.pl#L48

Travis is now getting Bison 3.0.5. Bison 3.0.5 was released about 5 days ago: https://lists.gnu.org/archive/html/info-gnu/2018-05/msg00013.html

We should be able to replicate the problem locally with Bison 3.0.5.
