### ISSUE TITLE
Merging GBWTs produces GBWT files that can't be used for haplotype-aware mapping

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1711]
In `vg gbwt` we have code to merge GBWT indexes. But the code that uses GBWT indexes for haplotype-aware mapping reads the haplotype count from the *xg*, which it assumes was generated alongside the gbwt in a single `vg index` run. If you do something like toil-vg is doing now for multiple chromosomes,  where you build an XG of the whole graph and separately build and merge chromosome GBWT indexes (and discard the chromosome XG files) you end up with an XG file that thinks there should be no haplotype information, and a GBWT file of haplotype information that vg will refuse to use. The result is errors like this:

```
=========> Failed job 'run_chunk_alignment' 046c944e-f924-4eb6-ad92-d3f0b66f220d 
INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.16.0a1.dev2290-c6d3a2a1677ba3928ad5a9ebb6d862b02dd97998.
INFO:toil-rt:Starting alignment on aligned-snp1kg-gbwt-pe chunk 0
INFO:toil-rt:Running VG for aligned-snp1kg-gbwt-pe against /var/lib/toil/toil-8863cb77-213b-431f-84f1-1fd2ffaf6a99-6835e381-a4a4-413a-b
INFO:toil-rt:Docker Run: vg map -f reads_chunk_0_0.fq.gz -t 32 -i -x graph.vg.xg -g graph.vg.gcsa --gbwt-name graph.vg.gbwt
ERROR:toil-rt:Docker container for command vg map -f reads_chunk_0_0.fq.gz -t 32 -i -x graph.vg.xg -g graph.vg.gcsa --gbwt-name graph.v
ERROR:toil-rt:Dumping stderr...
ERROR:toil-rt:terminate called recursively
ERROR:toil-rt:terminate called after throwing an instance of 'std::runtime_error'
ERROR:toil-rt:  what():  Cannot score any haplotypes with a 0 haplotype count; does the XG contain the path database?Stack trace (most 
ERROR:toil-rt:
```

We need to come up with an alternative to storing the global "haplotype count" of how many haplotypes are in the population in the xg. It has to be stored in the GBWT somehow, I think. To make things really correct we need to be able to support different values in different places (we will have more haplotypes on chrX or the autosomes than on chrY).

**Comment by jltsiren** [comment]
The `-F` option of `vg index` can be used to pass information from GBWT construction to XG construction. It outputs a thread database with haplotype count and thread names from GBWT construction. XG construction can read multiple databases. The current behavior is to store the maximum of the individual haplotype counts and all thread names in the XG index.

Examples: [GBWT construction](https://github.com/vgteam/vg/wiki/Index-Construction#with-haplotypes-4), [XG construction](https://github.com/vgteam/vg/wiki/Index-Construction#with-haplotypes-5).

**Comment by jltsiren** [comment]
If we have a reference + VCF graph, we could have haplotype counts on a per node basis. We determine the number of haplotypes at each variant site and store the number in each node associated with the site. For reference nodes between variant sites, we take the maximum of the adjacent sites.

There are two problems with this approach:
* The approach does not generalize to other types of graphs.
* There can be more paths than haplotypes. If there is no phasing information at a site, we start a new path, and the adjacent reference nodes are included in both paths.

**Comment by adamnovak** [comment]
I believe we fixed this by shipping the appropriate files around in toil-vg.
