### ISSUE TITLE
mpmap doesn't pair up paired reads at the ends of its files

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1719]
When you run mpmap in paired single-path mode, some of the reads at the ends of the GAM files don't have `fragment_next`/`fragment_prev` set. This causes problems with vg surject, such as https://github.com/vgteam/toil-vg/issues/553

**Comment by jeizenga** [comment]
Odd. Is this a toil-vg issue or a vg issue? The code that adds these fields seems pretty straightforward to me:

https://github.com/vgteam/vg/blob/master/src/subcommand/mpmap_main.cpp#L1001
https://github.com/vgteam/vg/blob/master/src/subcommand/mpmap_main.cpp#L1030

**Comment by adamnovak** [comment]
It looks like this happens when the fragment length estimation fails, because there aren't enough reads in the chunk being aligned. The ambiguous pair buffer is aligned single-ended, and the information about the resulting alignments being part of a read pair is lost.

**Comment by jeizenga** [comment]
Yeah, that's bad behavior. Also, what scenario are we running into this with? If we are chunking up the reads so finely that the fragment length distributions aren't being properly estimated we're going to have other problems too.

**Comment by adamnovak** [comment]
I'm running into this in my tiny test run, where I do a very small number of reads just to make sure that the whole pipeline works end to end.
