### ISSUE TITLE
integers are strings in vg view json output for gam files

### ISSUE THREAD

**Issue by wolfib** [vgteam/vg#1723]
Sometime between vg version v1.5.0-1999-g3f8fb66 and vg version v1.7.0-103-gf87f178 the json output of `vg view` has changed. The integer values for certain keys (node_id, offset, rank) used to be returned without quotation marks, whereas now they are surrounded by quotation marks.

This is a minor change, but it tripped up tubemaps which started interpreting the values as strings. Once I knew what was going on, it was an easy change on my end, but I still think vg should switch back to the old behaviour for consistency reasons.

Here is an example:
```
vg view -j -a chunk_0_17_0_603.gam
```
new output:
```
{
  "sequence":"AATCTAGCAAATATATCTCAGACTTTTAGAAATCTCTTCTAGTTTCATTTTCCTTTTTTTTTTTTTTTTTTTTTGCCACATTCTCCCTTTCCCCCCGGGCG",
  "path":{
    "mapping":[
      {
        "position":{
          "node_id":"40",
          "offset":"6"
        },
        "edit":[
          {
            "from_length":31,
            "to_length":31
          }
        ],
        "rank":"1"
      },
      ...
```
old output:
```
{
  "sequence":"AATCTAGCAAATATATCTCAGACTTTTAGAAATCTCTTCTAGTTTCATTTTCCTTTTTTTTTTTTTTTTTTTTTGCCACATTCTCCCTTTCCCCCCGGGCG",
  "path":{
    "mapping":[
      {
        "position":{
          "offset":6,
          "node_id":40
        },
        "rank":1,
        "edit":[
          {
            "from_length":31,
            "to_length":31
          }
        ]
      },
      ...
```

**Comment by JervenBolleman** [comment]
This was done for #1616 and  as side effect allows #1556.

**Comment by wolfib** [comment]
Thanks!

So the json-conversion is now done by protobuf, which maps int64 to string. The reason for that is that some JSON-parsers don't support int64 precision.

I'm therefore closing the issue.
