### ISSUE TITLE
Alignment sensitive to read length. 

### ISSUE THREAD

**Issue by ghost** [vgteam/vg#173]
I used some 76nt ChIP-seq reads and tried to map them to a whole genome vg with variation included (call it VG) and a whole genome graph without variation (no -v parameter in construct, call it LG). As the last 10 nt in the reads didn't have a great quality I trimmed them. Compared mapping results of these two with bowtie.

| VG | LG | Bowtie | Total reads | read length |
| --- | --- | --- | --- | --- |
| 8592653(64.83%) | 8962878(67.63%) | 8527121(64.34%) | 13253257 | 76 |
| 8076328(60.94%) | 8482629(64%) | 8594341 (64.85%) | 13253257 | 66 |

**And the alignment with the VG is performing worse than the LG**

**Comment by ekg** [comment]
This looks like a problem! They should at least be the same. So somehow the
process is working differently when the variation is added.

To figure out what is happening, would you please post the precise commands
that you used to create, index, and map to the graphs? Without this there
is a risk that we cannot produce the same failure mode.

Also, which version of vg did you use?

Thank you for reporting this. I will let you know what I find ASAP!

I used some 76nt ChIP-seq reads and tried to map them to a whole genome vg
with variation included (call it VG) and a whole genome graph without
variation (no -v parameter in construct, call it LG). As the last 10 nt in
the reads didn't have a great quality I trimmed them. Compared mapping
results of these two with bowtie.
VG LG Bowtie Total reads read length 8592653(64.83%) 8962878(67.63%)
8527121(64.34%) 13253257 76 8076328(60.94%) 8482629(64%) 8594341 (64.85%)
13253257 66

*And the alignment with the VG is performing worse than the LG*

—
Reply to this email directly or view it on GitHub
<https://github.com/ekg/vg/issues/173>.

**Comment by malvarez94** [comment]
To construct the LG (vg with no variation) I used the same parameters as in the tutorial "working with a whole genome vg", used de xg/GSCA2 index. And the parameters would be:

To construct the LG (vg with no variation, no -v parameter in construct) I used the same parameters as in the tutorial "working with a whole genome vg", used de xg/GSCA2 index. And those parameters would be:

*vg construct: -m50

*For GSCA index: 
    vg mod -pl 16 -t 16 -e 3 $chr.vg \
        | vg mod -S -l 100 - >$chr.k16e3l100.vg
    vg kmers -gB -k 16 -F -H 1000000000 -T 1000000001 -t 16 \
        $chr.k16e3l100.vg > $chr.k16e3l100.graph

*vg map: -k16 -GFX 1.5 -T 50 -l 12

And the VG (vg with -v parameter) used was the one you provided me a time ago. I'm creating my own VG with the exact same parameters as the LG in case you didn't use the same. I'll let you know how it goes. 
 

version used:1.3.0

**Comment by ekg** [comment]
@malvarez94 Just bumping this issue. I plan to look into this in the coming few days. I apologize that I haven't had time over the holidays. Hope all is well.

**Comment by adamnovak** [comment]
The aligner has been dramatically improved since this issue was opened. I'm going to assume this has been resolved.
