### ISSUE TITLE
Obtaining MHC variant graph using 1000 Genomes VCF file 

### ISSUE THREAD

**Issue by cjain7** [vgteam/vg#1749]
Hi vg-team,

I would like to build a MHC variant graph from GRCh38 reference and 1KG VCF files. I am trying to see how to use VG for this purpose.

Here is what I have:
- background of vg commands like `construct`
- GRCh38.p12 chromosome 6 fasta file 
- 1000 Genomes Phase 3 VCF files for chromosome 6 in GRCh38 
- [Genomic coordinates for MHC region](https://www.ncbi.nlm.nih.gov/grc/human/regions/MHC)

Can the `-R/--region` parameter be directly leveraged to get the MHC graph or do you suggest some pre-processing?

Thanks!

**Comment by glennhickey** [comment]
-R will work.  vg construct -r chrom6.fa -v chrom6.vcf.gz -R 6:start-end >
mhc.vg

**Comment by cjain7** [comment]
Thanks, this worked well. One minor caveat to execute above command was to rename the fasta sequence identifier to '6'.
