### ISSUE TITLE
README mapping and calling examples don't work together when attempted in order

### ISSUE THREAD

**Issue by zafarsustbd** [vgteam/vg#1751]
Please describe:

1. What you were trying to do
From vg homepage, I am just following the steps to construct a graph and call for a vcf.
2. What you wanted to happen
Just following the instruction to build a small graph and do variant calling.
3. What actually happened
It's crashing on both `call` and `genotype` command.
4. What data and command line to use to make the problem recur, if applicable
I installed vg today and the exact sequence of command to reproduce the issue is:
```
../../bin/vg construct -r ../small/x.fa -v ../small/x.vcf.gz >x.vg
../../bin/vg index -x x.xg -g x.gcsa -k 16 x.vg
../../bin/vg map -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -x x.xg -g x.gcsa >read.gam
../../bin/vg filter read.gam -r 0.90 -fu -s 2 -o 0 -D 999 -x x.xg > filtered.gam
../../bin/vg augment x.vg filtered.gam -q 10 -S aug_graph.support -Z aug_graph.trans -A aug_alignment.gam > aug_graph.vg
../../bin/vg call aug_graph.vg -b x.vg -s aug_graph.support -z aug_graph.trans -r SEQ > calls.vcf

vg: src/path_index.cpp:254: vg::PathIndex::PathIndex(vg::VG&, const string&, bool): Assertion `vg.paths.has_path(path_name)' failed.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_TDuI0F/stacktrace.txt

```

Stacktrace:
[stacktrace.txt](https://github.com/vgteam/vg/files/2123963/stacktrace.txt)

Environment details:

Ubuntu version: Ubuntu 16.04.3 LTS
GCC version: 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by adamnovak** [comment]
The underlying problem here is that "SEQ" in the last line isn't supposed to be a literal; it needs to be replaced with the name of the reference path you are calling against. In this case (starting from test/small/x.fa), the path name ought to be "x":

```
./../bin/vg call aug_graph.vg -b x.vg -s aug_graph.support -z aug_graph.trans -r x > calls.vcf
```

Keep in mind that you have only aligned a single read here, so it is likely that you won't get any variants out. If you want to see the variants from the initial VCF, I think you have to simulate and align a few X coverage of reads.

We probably should change the README so that the mapping and calling examples work together, and people can run them end to end like you are trying to do. We also probably should improve the error message for when a user specifies a nonexistent path name, so it doesn't look so much like an internal error.

**Comment by zafarsustbd** [comment]
Thank you very much! But shouldn't it be whole path and name of the file (i.e: `../small/x.fa`):

```
./../bin/vg call aug_graph.vg -b x.vg -s aug_graph.support -z aug_graph.trans -r ../small/x.fa > calls.vcf
```
instead of just `x`? I have another question, where can I find the documentation of all these input parameters (`-d`, `-r`, `-b` etc) for vg?

**Comment by adamnovak** [comment]
It's not "path" in the sense of a file path; it's "path" in the sense of a
sequence of nodes in the graph.

To do variant calling into a VCF, you have to articulate your variants as
VCF records, which are about the potential replacement of part of a
reference sequence with an alternate piece of sequence. So vg needs to know
how the reference sequence you want it to call against is embedded in the
graph. In this case, you want to point it at the path named "x", which was
derived from the `>x` record in the FASTA, and tell it to do variant
calling using that path's sequence as the reference sequence.

The command line options are right now unfortunately only documented in the
vg program's internal help. If you want the available options for `vg
call`, you run `vg call --help` and it will print them all out along with
some descriptions. If you want a list of all the vg commands, you can do
`vg help`. But we haven't yet written a man page or anything that would
describe the options in more detail.

**Comment by zafarsustbd** [comment]
Thank you very much!
