### ISSUE TITLE
Question about genotyping

### ISSUE THREAD

**Issue by apregier** [vgteam/vg#1753]
I have spent quite a bit of time reading documentation and code, and just trying things out, but perhaps you can answer my question without much work.
I am trying to make a graph with SVs, then align reads to it, then genotype the SVs (i.e. get read depth for ref/alt alleles for each SV that I input).  I can make it through the first two parts (construct with a `-a` option to save variants as paths, then index and map).  But, I am stuck on the last bit.  I have tried the chunked_call script, and can get a VCF, but the variants have ids that seem to be related to graph coordinates rather than the original ids.  Also, I don't seem to be finding the variants I expect (although I'm not completely convinced that I am building the graph correctly, so that could be part of the problem).
I guess the question is - is this currently possible?  If not, is it almost possible, and if so, which subcommand (call, genotype, srpe, something else?) is currently closest?  I am able to do some hacking/development to get this to work, but it would help to have a little guidance to get started.

**Comment by adamnovak** [comment]
It's not currently possible for the output VCFs from vg to be expressed in terms of the original variant IDs. The variants are used in the construction of the graph, but the idea of an individual variant is mostly thrown away in favor of our "snarl" concept, which supports nesting, and then the projection back to VCF at the end doesn't try to match up against "known" variants.

You also may not be getting your structural variants into the graph at all if you are not passing the `-S` option to vg construct. The SV ingest code is new and we don't quite trust it yet, so it's behind a flag at the moment.

It probably would be possible to replace the VG-generated variant IDs with rsIDs from the original VCF. It would involve either taking a template VCF of known, named variants at calling time, or else somehow associating the known variant IDs with the "alt paths" in the graph, which are currently just used for importing phased haplotypes. There would also be some nontrivial questions to answer about how to deal with cases where the input variants overlapped, or where novel material overlaps one of the original input variants, or other similar things that would break the VCF variant abstraction.

I'm not sure if call or genotype would be the best place to put such a feature. It might be easier in call, but I think most of our new work is going on in genotype.

On the other hand, there might already be existing software that can recognize known variants in a VCF and assign their IDs to them. And even if not, doing the problem in that space might be simpler.

**Comment by apregier** [comment]
Thanks, this is helpful.  I don't know that it is totally necessary to have the original IDs, but it is helpful to know that they are not expected to be there.  I agree if it is not possible to save them upfront it is better to match them up later with separate software.

**Comment by apregier** [comment]
Ooh, I just found the variant_recall functionality in genotype, looks promising if a bit dusty...

**Comment by adamnovak** [comment]
Hm. I think I forgot that that existed. It might do what you want.
