### ISSUE TITLE
vg graph traversal and path annotation

### ISSUE THREAD

**Issue by zafarsustbd** [vgteam/vg#1759]
I am trying to do some statistical analysis on nodes/edges of variation graph. What could be the best way to traverse the graph in order to do that? Should I first use `vg view -dn` to convert it to dot file for traversing the graph or there are some other ways to traverse it?

Another question, how to label/annotate/find the paths which was mapped from `.fastq` paired-end reads to the vg graph?

**Comment by ekg** [comment]
You can export the graph to GFAv1 using `vg view graph.vg >graph.gfa`. That's a reasonable place to do your analysis. The dot output is not suitable for downstream use, as much of it is related to formatting for visualization and not graph structure.

The paths from the mapping are recorded in an alignment file, a .gam, which is like a BAM file.

**Comment by zafarsustbd** [comment]
Thank you very much for your response! What about if I augment a graph using `.gam` file and initial constructed `.vg` file so that I can use that new augmented graph as reference for future mapping? In that case, will that augmented graph retain the path information of those aligned `fastq` reads?

**Comment by ekg** [comment]
@zafarsustbd in this case you'll keep all the path information from the aligned fastq. However, the path storage (for positional paths that are used for mapping clustering) is expensive in the .xg index and so you may want to consider encoding the gam using gbwt. You can do this by building the gbwt index with `vg index` and providing the `--store-gam` parameter to specify the alignment set. Then the .gam paths can be used by the mapper to generate haplotype concordance scores for new alignments.

```
# in vg/test
# generate a test graph and test data
vg construct -r tiny/tiny.fa -v tiny/tiny.vcf.gz >t.vg                                                                            
vg index -x t.xg -g t.gcsa t.vg
vg sim -l 30 -n 100 -x t.xg -a >t.sim.gam
vg map -G t.sim.gam -x t.xg -g t.gcsa >t.sim.aln.gam
# augment including alignment paths, sort the graph and compact its ids
vg mod -i t.sim.aln.gam t.vg | vg mod -z - | vg mod -c - >t.aug.vg
# index and visualize the augmented graph
vg index -x t.aug.xg t.aug.vg
vg viz -x t.aug.xg -o t.aug.svg
```

![screenshot from 2018-06-26 13-34-24](https://user-images.githubusercontent.com/145425/41911850-b9dc4fee-7945-11e8-8859-689e2e9ba62c.png)

The problem with this approach is how big the .xg index gets when including the positional paths:

```
 4.0K t.vg
  12K t.xg
 4.0K t.gcsa.lcp
 4.0K t.gcsa
  16K t.sim.gam
 4.0K t.sim.aln.gam
 8.0K t.aug.vg
 116K t.aug.xg
 544K t.aug.svg
```

Note that t.aug.xg, which now includes 101 positional paths, is 116K, while the input graph was only 12K.

To store more haplotypes in less space, we can use the GBWT. There is a somewhat non-obvious way to do this at present, which I'll describe here in hopes it gets us thinking about how to make this simpler:

```
# extract the alignments as a GAM in the coordinate space of the augmented graph
vg paths -X -v t.aug.vg >t.sim.aln.emded.gam
# keep only the reference path in the file we'll feed to .xg indexing
vg mod -r x t.aug.vg >t.aug.ref_path_only.vg
# build an index, but using only the positional path in t.aug.ref_path_only.vg for .xg
# and use the alignments in the embedded GAM to build the .gbwt index
vg index -x t.aug.ref_path_only.xg -G t.aug.ref_path_only.gbwt -M t.sim.aln.emded.gam t.aug.ref_path_only.vg
```

Now the space usage is much more modest, only 24K vs. 116K.

```
 4.0K t.aug.ref_path_only.gbwt
  20K t.aug.ref_path_only.xg
```

I suggest trying out a few of these things on a small graph to get a sense of the tradeoffs. You can look in the tests directory [`test/t`](https://github.com/vgteam/vg/tree/master/test/t) for examples to further guide your exploration.

**Comment by zafarsustbd** [comment]
Wow! Thank you very much for your great explanation!
