### ISSUE TITLE
vg augment crash

### ISSUE THREAD

**Issue by zafarsustbd** [vgteam/vg#1766]
I have a reference genome sequence from chr6 (`~ 30mbp`), one `.vcf.gz` file consisting around ~300 variation entries and `.fastq` pair-end reads. I constructed the graph using `ref` and `.vcf.gz` file:
```
vg construct -p -r ref.fa -v vcf_files/ref.vcf.gz > graph.vg
vg index -p -x graph.xg -g graph.gcsa -k 16 graph.vg  
vg map -x graph.xg -g graph.gcsa -f fastq_files/R1.fastq -f fastq_files/R2.fastq > graph.aln.gam
vg filter graph.aln.gam -r 0.90 -fu -s 2 -o 0 -D 999 -x graph.xg > filtered.gam
vg augment graph.vg filtered.gam -q 10 -S aug_graph.support -Z aug_graph.trans -A aug_alignment.gam > aug_graph.vg 
``` 
Augment call crashes with the following backtrace:
```
vg: src/pileup_augmenter.cpp:384: void vg::PileupAugmenter::verify_path(const vg::Path&, const std::__cxx11::list<vg::mapping_t>&): Assertion `in_string == call_string' failed.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_Ud9gTC/stacktrace.txt
```
Full stacktrace:

[stacktrace.txt](https://github.com/vgteam/vg/files/2142922/stacktrace.txt)

Attached the whole trace for analysis. Though I can generate augmented graph by `mod` command (given below) but vg call/genotype requires `.support`, `.trans`, `aug_alignment.gam` files.
```
vg mod -i graph.aln.gam graph.vg | vg mod -z - | vg mod -c - > graph.aug.vg 
```

How to advance in this situation? 
FYI: my vg version is `v1.8.0` (git commit `3cb239e`)

**Comment by ekg** [comment]
Mod will produce the .trans file but not the support. Adding that would be
a workaround. It would be better to fix augment itself.

**Comment by adamnovak** [comment]
It looks like according to https://github.com/vgteam/vg/issues/1772#issuecomment-401446588 the workaround is to add `-a direct` to the `vg augment` call. This may be more or less the same problem as that issue.
