### ISSUE TITLE
vg map and augment based on sample

### ISSUE THREAD

**Issue by zafarsustbd** [vgteam/vg#1771]
Hi,

I am mapping multiple samples (each `paired end .fastq` file contains reads from an individual human) in the graph. Is there any way to get the paths or annotations based on samples (file name or description of that sample)? If I just do normal mapping of `.fastq` files, I am getting path names for each read in the `.fastq` file. 

Another question related to the same topic, now that I know each sample (`paired end .fastq` file) came from an individual person, how to augment the graph so that **vg** can discard ambiguous mappings for that particular sample?

**Comment by ekg** [comment]
You can filter on mapping_quality to get rid of reads that are likely to
come from many places. Augmenting the graph with all the reads will be
expensive unless it is done in chunks. It sounds like you are trying to
implement genotyping or variant calling.

**Comment by zafarsustbd** [comment]
Actually I have data from multiple samples (humans) and I want to do some statistical analysis to find the variations among different people. Do you think it's possible to somehow mark or annotate the alignments based on individual person rather than each read?

**Comment by ekg** [comment]
You can use vg pack to convert alignments into a coverage vector over the
graph. It's then possible to do this for multiple samples, thus
constructing a matrix of coverage by sample. In theory it's then possible
to do different popgen analyses on this matrix (like PCA) but thus far no
one has tried.
