### ISSUE TITLE
vg augment crashes on exmaples

### ISSUE THREAD

**Issue by zafarsustbd** [vgteam/vg#1772]
I am just running experiments on examples (`small` folder in `test`) provided with vg. It crashes on augment command:

```
vg construct -p -r ../small/x.fa -v ../small/x.vcf.gz > x.vg
vg index -p -x x.xg -g x.gcsa -k 11 x.vg
vg map -x x.xg -g x.gcsa -f ../small/x.fa_1.fastq -f ../small/x.fa_2.fastq > x.aln.gam
vg filter x.aln.gam -r 0.90 -fu -s 2 -o 0 -D 999 -x x.xg > x.aln.filtered.gam 
vg augment x.vg x.aln.filtered.gam -q 10 -S aug_graph.support -Z aug_graph.trans -A aug_alignment.gam > aug_graph.vg

vg: src/path.cpp:16: vg::mapping_t::mapping_t(const vg::Mapping&): 
Assertion `length == mapping_to_length(m)' failed.
```
Later I found that crash happens with `-A` flag. If I don't put `-A`, then it doesn't crash.
```
vg augment x.vg x.aln.filtered.gam -A aug_alignment.gam > aug_graph.vg
```
Full stacktrace:

[stacktrace_small.txt](https://github.com/vgteam/vg/files/2149899/stacktrace_small.txt)

**Comment by ekg** [comment]
Some of these graphs do not confirm to the current file format. The paths
do not have the lengths of the nodes they cross embedded. Maybe we should
revisit this.

**Comment by zafarsustbd** [comment]
Can you please point me if there is any input specification for the current file format? Thanks!

**Comment by glennhickey** [comment]
@zafarsustbd  I will push a cleanup to the README examples and interface soon.  But the `-A` flag is not supported in `vg augment` except with `-a direct`.  So if you want to:
* make an augmented graph: use `vg augment -a direct -A`
* run vg genotype: just pass in your graph and gam (`-G`) and let it augment for you.
* run vg call: don't use `-A` with `vg augment`.
