### ISSUE TITLE
GBWT ignoring deletions

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#1784]
This came up while working with the hgsvc structural dataset, where haplotype threads never crossed deletion edges.   Here's a quick way to reproduce an example.

```
wget http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr21.fa.gz
gzip -d chr21.fa.gz
wget https://glennhickey.s3.amazonaws.com/temp/single_deletion_HG005733.vcf.gz
tabix -f -p vcf single_deletion_HG005733.vcf.gz
vg construct -r chr21.fa -v single_deletion_HG005733.vcf.gz -m 32 -a -R chr21:32477603-32477803 > single.vg
vg index single.vg -x single.xg -G single.gbwt -v single_deletion_HG005733.vcf.gz
vg paths -T -x single.xg -g single.gbwt -V > single_threads.vg
cat single.vg >> single_threads.vg
vg view single_threads.vg
```
gives two reference threads 
```
P	_thread_HG005733_chr21_0_0	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
P	_thread_HG005733_chr21_1_0	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
```
flipping the deletion to an insertion (in the vcf and rebuilding everything) works
```
P	_thread_HG005733_chr21_0_0	1+,2+,3+,4+,5+,6+,7+,8+,9+,10+,11+ 32M,32M,32M,5M,32M,32M,17M,32M,32M,32M,4M	
P	_thread_HG005733_chr21_1_0	1+,2+,3+,4+,8+,9+,10+,11+	32M,32M,32M,5M,32M,32M,32M,4M	
```
@jltsiren any idea why this is happening?

**Comment by glennhickey** [comment]
Looks like this problem arose in #1744.

**Comment by jltsiren** [comment]
In this particular case, `vg index` processes the variant, but it cannot find a path for the alternate allele (path name `_alt_ec73503d81c13dd2cca7e820961ceb26a59426f1_1`). Because the alt path does not exist, the construction uses the reference path instead.

**Comment by ekg** [comment]
This could be related to my flat alts twiddling. We have to make sure that
the variant is still included. Presumably it needs to cross the deletion
and have one base on either side?

**Comment by glennhickey** [comment]
For what it's worth, the alt paths haven't changed.  Here they are in master where deletion is lost:
```
P	_alt_ec73503d81c13dd2cca7e820961ceb26a59426f1_0	5+,6+,7+	32M,32M,17M	
P	_alt_ec73503d81c13dd2cca7e820961ceb26a59426f1_1			
P	_thread_HG005733_chr21_0_0	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
P	_thread_HG005733_chr21_1_0	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
P	chr21	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
```

And here they are in aadb2e697756dc5a7b90411ed0a40c3cbdf10223 (last commit before #1744 merged in) where deletion is kept:
```
P	_alt_ec73503d81c13dd2cca7e820961ceb26a59426f1_0	5+,6+,7+	32M,32M,17M	
P	_alt_ec73503d81c13dd2cca7e820961ceb26a59426f1_1			
P	_thread_HG005733_chr21_0_0	1+,2+,3+,4+,8+	32M,32M,32M,5M,19M	
P	_thread_HG005733_chr21_1_0	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
P	chr21	1+,2+,3+,4+,5+,6+,7+,8+	32M,32M,32M,5M,32M,32M,17M,19M	
```

**Comment by jltsiren** [comment]
The issue may be in `VGset::to_xg()`. When alt paths are removed from the graph, empty paths are never added to `mappings`, and hence they are never returned to the caller.

**Comment by jltsiren** [comment]
These seem to be two separate issues:

* `VGset::to_xg()` has never returned empty paths.
* The old haplotype generation code interpreted missing paths as deletions, while the current code interprets them as reference alleles.
