### ISSUE TITLE
Zero-based or one-based coordinates for graph

### ISSUE THREAD

**Issue by apregier** [vgteam/vg#1793]
I am having a heck of a time with 0- and 1-based coordinates going in and out of VCF.  Here is what I am doing:
1. building a graph from a fasta+vcf
2. aligning reads
3. using the variant recall functionality to get genotype at that variant - this is based on the alt paths stored in the graph.
With just a couple modifications I got this to work.  The problem is that the variant it spits out is off by one (the position in the output vcf is one less than the position in the original vcf).  The variant recall code subtracts one from the input variant (see https://github.com/vgteam/vg/blob/master/src/variant_recall.cpp#L185), and if I remove that line, the position is correct on the output variant.  However, when the variant_id is calculated (see https://github.com/vgteam/vg/blob/master/src/utility.cpp#L252) it no longer matches up with the name of alt path stored on the graph (since apparently the alt path must also be named with position - 1, although I haven't been able to track that down exactly), so the genotype isn't calculated correctly.
At this point I am just not sure what the right thing to do is.  I saw that there is a zeroBasedCoordinate in the vcflib Variant object - maybe there should be more extensive use made of that field rather than decrementing the position?

**Comment by adamnovak** [comment]
It looks like `variant_recall.cpp` has been fixed in master to not subtract 1 out anymore. In general I think we stopped modifying variant positions to 0-based when passing them around internally. I assume whoever did that made sure the variant IDs are consistent.

I'm going to close this; please re-open it if that hasn't actually solved the problem.
