### ISSUE TITLE
Linking to dependencies

### ISSUE THREAD

**Issue by lexnederbragt** [vgteam/vg#180]
I'm running into compilation issues, which HPC- IT staff tells me is because "a lot of external dependencies are installed in in `lib/`, but these libraries are not used during linking. In particular, this is one of the linking lines:

````
g++ -O3 -std=c++11 -fopenmp -g -o bin/example cpp/example.pb.o 
obj/main.o -I./ -Isrc -Iobj -Icpp -L./ -L/usr/local/lib/ -lprotobuf -lz 
&& cp src/*.h* include/
```

The external protobuf library compiled in `$(TOPGIT)/lib` is not used, and 
instead the one installed in `/usr/local/lib` is."

I hope this text makes sense, and I hope there is a possible fix?

**Comment by ekg** [comment]
Are you using e.g. `. ./source_me.sh && make -j 8 static`?

**Comment by lexnederbragt** [comment]
Yes.

**Comment by ekg** [comment]
It looks straightforward enough to fix by adding the lib and include
directory locations into the build. I thought this was done by source_me,
but it seems not to be working?

**Comment by edawson** [comment]
I thought I had fixed this. Removing the -L/usr/local/lib should fix
things. The -L flags override the source_me stuff if I understand it
correctly.

On Monday, January 4, 2016, Erik Garrison <notifications@github.com> wrote:

> It looks straightforward enough to fix by adding the lib and include
> directory locations into the build. I thought this was done by source_me,
> but it seems not to be working?
> On Jan 4, 2016 9:17 AM, "Lex Nederbragt" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Yes.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ekg/vg/issues/180#issuecomment-168688557>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekg/vg/issues/180#issuecomment-168689203>.
>


-- 
Sent from my iPhone

**Comment by angainor** [comment]
Thanks for your replies. I have tried to remove all -L flags from deps/xg/stream, but it did not help. I have to manually include a correct -Lpath flag to make things compile. 

Moreover, I seem to have trouble linking with static: cannot find -lpthread. I have removed the -static option from deps/xg/Makefile and the top level Makefile (leaving only "-static-libstdc++ -static-libgcc"). Is -static really needed?

**Comment by ekg** [comment]
Static is needed if you do not set up your environment to point to the lib
directory in the vg repo. You will want to write a wrapper script like
source_me.sh to run the dynamically linked vg. I find this awkward and tend
to run the statically linked binary.

**Comment by angainor** [comment]
OK, so I could in principle do without the make static and use simple make? As long as I set the LD variables correctly (this is what we do in our environment when using module load ...). The problem with that is that deps/xg/Makefile has its own version of STATICFLAGS, which I have to change manually. Would it be possible for you to reuse it from the top-level Makefile?

Regarding the linking problem. source_me.sh sets the LIBRARY_PATH correctly, but I have a protobuf library installed in a default system location (/usr/lib64). GCC uses it before LIBRARY_PATH is searched. I think you need a different method to explicitly tell the linker to use your custom compiled libraries - AFAIK that must be with the -L flag.

**Comment by angainor** [comment]
I have made a temporary compilation fix that works for us, attached a simple patch here. I use the -Wl,-rpath linker option (added to source_me.sh), so you avoid having to use a wrapper script for running dynamic binaries - they use your local compiled libraries.

Cheers,

Marcin

[vg.txt](https://github.com/ekg/vg/files/79777/vg.txt)
