### ISSUE TITLE
Variant calling for multiple sample

### ISSUE THREAD

**Issue by zafarsustbd** [vgteam/vg#1802]
Hi I am augmenting vg graph for multiple sample. In each step, I index the graph, map my sample (paired-end fastq files), filter it and then finally augment this mapping with the graph (from previous iteration). For augmenting, I am using the following command:

`vg mod -i graph.aln.gam graph.vg | vg mod -z - | vg mod -c - > graph.aug.vg`

Now that I have a graph which contains all the variants for incorporated samples, I want to get all these variants with respect to the original reference genome. I tried following command:
`vg genotype graph.aug.vg -r chr >> calls.vcf`

But I get the following error:
`[vg genotype] Index argument must be specified when not using -G `

The reason I don't want to provide the `gam` file because it will have information of last mapped sample only. I want to get all the variants that was incorporated in the graph, not just for the last one. Is there any way I can do this in VG?

**Comment by glennhickey** [comment]
vg genotype assumes a single diploid sample when it's making calls.  If you
still want to pool samples and see what comes out, the simplest way is
probably just catting all the gams together and running with -G.

**Comment by adamnovak** [comment]
If you want everything in the graph expressed as VCF, you might be able to get @edawson's `vg deconstruct` to do that for you. But that will find a lot of sequencing errors in addition to actual variants, since we throw more or less everything into the augmented graph and rely on the calling step to pull out the actual variants with sufficient read support.

**Comment by zafarsustbd** [comment]
Thank you very much! I actually wrote a module to get all the variants from graph (for al the samples) with respect to a certain path. It's working fine, at this point I can close the issue :)
