### ISSUE TITLE
Incorrect Snarls lead to segfault in Genotyper, which causes Travis to periodically hang on the integration tests

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#1856]
We've been experiencing periodic hangs from Travis in the genotyper integration tests. I tracked the segfault down to the [RepresentativeTraversalFinder::find_traversals](https://github.com/vgteam/vg/blob/master/src/traversal_finder.cpp#L903) algorithm, but the issue appears to be that it's working with incorrect Snarls. This in turn breaks some expectations in the SnarlManager::shallow_contents algorithm.

The Genotyper uses [CactusSnarlFinder::find_snarls](https://github.com/vgteam/vg/blob/master/src/snarls.cpp#L30) to find these snarls, which as far as I can tell is just every edge on the reference path:
```
{"type":"ULTRABUBBLE","start":{"node_id":"1"},"end":{"node_id":"3"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"3"},"end":{"node_id":"5"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"5"},"end":{"node_id":"6"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"6"},"end":{"node_id":"8"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"8"},"end":{"node_id":"9"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"9"},"end":{"node_id":"11"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"11"},"end":{"node_id":"12"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"12"},"end":{"node_id":"14"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
{"type":"ULTRABUBBLE","start":{"node_id":"14"},"end":{"node_id":"15"},"start_end_reachable":true,"directed_acyclic_net_graph":true}
```

In this graph (tiny.vg):
<img width="1173" alt="screen shot 2018-09-04 at 1 17 02 pm" src="https://user-images.githubusercontent.com/7377501/45055587-18cb2a80-b045-11e8-97d1-b5d2922dda2b.png">

These are clearly wrong. I think I may have diagnosed the problem, but I want some eyes on it that are more familiar with this part of the code base. @adamnovak @glennhickey 

I think the issue is that the snarls are identified in the subset graph here:
https://github.com/vgteam/vg/blob/master/src/genotyper.cpp#L92
But then the contents algorithm is run using the full graph here:
https://github.com/vgteam/vg/blob/master/src/genotyper.cpp#L165
which feeds into here
https://github.com/vgteam/vg/blob/master/src/genotyper.cpp#L429

Sometimes snarls in the pruned subset graph are not snarls in the full graph, which leads to the broken assumptions. If I'm right, I don't really know what the best solution would be.

**Comment by adamnovak** [comment]
Yeah that doesn't look like it is going to work, making the snarls on the subset and then later using the full graph. And if we're working with different sets of simulated reads every time, that would explain why sometimes it hangs and sometimes it doesn't.

The right thing to do might be to use the subset graph everywhere if we are going to use it anywhere. We just set one reference to the graph to use (either the subset graph or the full graph) and then access the graph through that reference everywhere we need it.
