### ISSUE TITLE
Snarl loading is slow

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1862]
The snarls file at s3://cgl-pipeline-inputs/vg_cgl/pop-map/alignments/wg38/v5/sim/graph.vg.snarls takes about 20 minutes to load into a SnarlManager, despite being only about 300 MB.

Jordan thinks the problem is that we are wasting all our time maintaining multiple hash tables on the defining boundary nodes of the snarl. I think he's right; I tried swapping out the hash table implementation for the wang_hash based Google hash table we have, as well as for just a tree-based `std::map`, and didn't notice dramatic improvements. The `std::hash` we have for pairs isn't great, but it doesn't look to be producing oodles of collisions either.

I am going to rearchitect the SnarlManager to get rid of the whole key form concept, and all the parallel hash tables. This might mean keeping things in a bunch of vectors by snarl number, or in a big vector of fully-populated snarl-describing structs that also hold children, etc.

While I'm at it maybe I can do #1797.

**Comment by jeizenga** [comment]
If you're looking to test your solution to https://github.com/vgteam/vg/issues/1797, you could have a look at my `snarl-by-handles` branch in the `jeizenga` fork. It has tests that I believe are failing because of it.

**Comment by adamnovak** [comment]
The solution I have come up with right now is to have a `SnarlRecord` that holds the snarl and also the parent/children/chain info, and set it up so you can cast between `SnarlRecord*` and `Snarl*` (by using inheritance, but composition with the Snarl at the first field would also work I think). Then I can have all the `Snarl*` pointers to the SnarlManager's managed snarls really point to `SnarlRecord`s, and I can get the children and so on by casting the pointers back to their real types instead of looking up stuff in a giant map.

Right now I'm trying to run an experiment to see if this is actually any faster, or faster enough. I didn't get anywhere with the callgrind profiling; the original code didn't even manage to finish deserializing the snarls in a couple hours under the profiler.
