### ISSUE TITLE
Construct behavior is not consistent across operating systems

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#1868]
Please describe:

1. What you were trying to do
Construct identical graphs on Mac and Linux, using the same VCFs and references.

2. What you wanted to happen
Construct a graph from test/sv/x.fa and test/sv/x.inv.vcf, which includes an inversion.
```
 ./bin/vg construct -S -r test/sv/x.fa -v test/sv/x.inv.vcf > x.vg 
```

The graph should look like 
[o.pdf](https://github.com/vgteam/vg/files/2374401/o.pdf)

3. What actually happened
On Mac OS, this seems to work (both locally and on Travis), and the graph produced is the expected one.

On Linux, the graph that gets made looks so:
[o.pdf](https://github.com/vgteam/vg/files/2374411/o.pdf)

Which is the graph I would expect if the VCF had the ref/alt fields replaced with sequence and then the two sequences got aligned together.

It doesn't make sense to me why we would get different behavior with the same compiler on different operating systems unless we've done it intentionally somewhere.

4. What data and command line to use to make the problem recur, if applicable
x.fa and x.inv.vcf are available in the test/sv/ directory.

**Comment by edawson** [comment]
@apregier the current SV work lives in the de_sv_ify branch for the moment. If you could try to replicate it that would be great. If you want to collab on a todo list for SVs I'd be happy to divide the effort - maybe we make a new wiki page with a roadmap for SV development?

**Comment by ekg** [comment]
@edawson and I discussed what might be causing this, and he's checking if the builds are somehow out of sync. Based on this report, it would appear that the option parsing is working differently on the two systems. This could be possible, but it's good to check carefully all the prerequisites for the test before we dig deeper to figure out what's going on.

**Comment by apregier** [comment]
Yeah, seems likely to be a build issue.  Re: collaborating, a wiki sounds great.  I'm also happy to hop on Skype and talk about specifically what we are trying to accomplish and see what tasks will overlap.

**Comment by apregier** [comment]
FWIW, I got the expected inversion graph when I ran the above command on that branch.

**Comment by edawson** [comment]
This is now fixed and merged into master. I think it came down to some default value initializations, but it is really hard to tell.
