### ISSUE TITLE
graph produced with cactus (MSA) + hal2vg is very slow

### ISSUE THREAD

**Issue by eldariont** [vgteam/vg#1878]
Hi,

I created a multiple sequence alignment of 12 yeast assemblies with cactus and converted the resulting _yeast.hal_ to _yeast.vg_ with hal2vg.

Then I wanted to look at the paths embedded in _yeast.vg_ with `vg paths -v yeast.vg -L`. This takes a long time (> 10 minutes before I stopped the command). The same slow processing can also be observed when executing `vg view` or `vg validate` on _yeast.vg_. I would like to know whether this is a consequence of specific layout characteristics that cactus graphs converted to vg graphs might have or whether there is another reason behind this.

_yeast.vg_ can be downloaded here: https://www.dropbox.com/s/c6klq15qcly887j/cactusoutput1.vg?dl=0

Cheers
David

**Comment by jltsiren** [comment]
The file is probably damaged:
```
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
```

On my Mac, I was able to build an XG index of the graph in ~10 minutes. The `vg paths` ran for 30-40 minutes before failing silently. On a Linux server, the `vg paths` command ran in ~10 minutes using 35 GB of memory and reported almost 3000 paths. I was also able to run `vg validate` and `vg stats` there, while the attempt to build a GBWT index of the paths failed.

**Comment by ekg** [comment]
I get the same error. Has hal2vg been updated to work with the current version of vg?

**Comment by eldariont** [comment]
Thank you, Jouni and Erik, for looking into this.

I could replicate everything you reported but don't know how the file was damaged. Both `cactus` and `hal2vg` finished (seemingly) successfully and didn't report any errors. The _yeast.hal_ seems to be fine because `halValidate yeast.hal` returns "File valid".

I reran `hal2vg` but got the exact same file as before. From what I can see from the github page, `hal2vg` was not updated for a few months. But why should it produce a truncated file?

Apart from the absent EOF marker: Is it common for `vg paths` to take 10min and use 35gig of memory on a graph of this size?

**Comment by eldariont** [comment]
I could confirm that _yeast.vg_ is not damaged or truncated. `hal2vg` just does not add the EOF marker to its output stream. When I added a call to `stream::finish(*_outputstream);` at the end of `hal2vg`, the resulting vg file did not produce the error anymore:

```
> vg stats -z yeast_new.vg
nodes   5957293
edges   8326474
```

Which leads to the question why processing by vg is so slow and memory-intensive on the file. Is there something special about it?

**Comment by jltsiren** [comment]
VG paths are quite heavy objects. With almost 3000 of them, your yeast graph is more than twice as large as a human chr1 graph with only a reference path.

You could store the paths as threads (lightweight paths) in a GBWT index. First build the GBWT:
```
vg index -T -G yeast.gbwt -F thread_names yeast_new.vg
```
Then create a VG graph without the paths and build an XG index that will also store thread names:
```
vg mod -D yeast_new.vg > yeast_no_paths.vg
vg index -x yeast.xg -F thread_names yeast_no_paths.vg
```

**Comment by eldariont** [comment]
Thanks a lot. That did the trick. 👍 

I now have a valid 50MB vg graph without the paths and two index files on it. As you said, commands are much quicker on this lighter graph. Will close this issue.
