### ISSUE TITLE
vg construct produces incorrect alt paths for relatively simple variants

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1889]
If you download these files:

```
aws s3 cp s3://vg-data/pop-map/alignments/wg38/v7/sim/graph.vg.xg .
aws s3 cp s3://vg-data/pop-map/alignments/wg38/v7/sim/graph.vg.gcsa .
aws s3 cp s3://vg-data/pop-map/alignments/wg38/v7/sim/graph.vg.gcsa.lcp .
```

And you use this one-read FASTQ:
[test.fq.gz](https://github.com/vgteam/vg/files/2413187/test.fq.gz)

And you build vg 224da982 (or current master 49ae9199) and run it with:

```
vg mpmap --single-path-mode -f test.fq -t 1 -x graph.vg.xg -g graph.vg.gcsa >/dev/null
```

Then you will get this assertion failure:

```
vg: src/multipath_mapper.cpp:3177: void vg::MultipathMapper::sort_and_compute_mapping_quality(std::vector<vg::MultipathAlignment>&, vg::MappingQualityMethod, std::vector<long unsigned int>*) const: Assertion `!alignments.empty()' failed.
```

This is caused by the (unpaired) `sort_and_compute_mapping_quality` getting 0 alignments out of `optimal_alignments`, even though it asked for 1. 

I think that this is a different problem than #1846, and is probably somewhere in the `optimal_alignments` code that it looks like I was the last person to touch.

**Comment by adamnovak** [comment]
We're getting 0 alignments out because the input MultipathAlignment has no subpaths. This is because the MultipathAlignmentGraph made for it is empty, because the only input MEM goes off the end of the cluster graph being used to create the MultipathAlignmentGraph.

The problem might really be in the clustering/cluster graph extraction, if we're never supposed to have the only MEM fall off the end and be discounted.

**Comment by jeizenga** [comment]
The graph extraction is supposed to guarantee that all of the seed MEMs are included in the graph. It can happen that a MEM goes off the end, because the cluster graphs "scoop up" any additional MEMs that happen to be located in the graph that they extract. But there should be at least one MEM that is fully contained in the graph.

**Comment by adamnovak** [comment]
The real problem seems to be that the xg has the graph actually ending in the middle of this MEM:

![image](https://user-images.githubusercontent.com/5062495/46045620-0b004680-c0d3-11e8-86d3-4f0cba2829af.png)

There is no node 30781014, and we pick up with node 30781015, which looks to have more MEM sequence, but nothing in the xg connects them. The paths (which are derived from threads, since this is the no-primary-reference sample graph we are trying to map to) just jump over this gap.

![image](https://user-images.githubusercontent.com/5062495/46045717-4f8be200-c0d3-11e8-82ad-5516d9f12675.png)

**Comment by adamnovak** [comment]
This is really a GBWT problem.

The GBWT has threads in it that both skip over the nodes that link these two parts of the graph together. When we subset to just the part-of-the-sample-haplotypes parts of the graph, we drop those nodes and end up with a disconnected graph.

The GCSA index is following the GBWT threads here, instead of the actual graph (I think), which is how it manages to produce hits for MEMs that run off the end of the graph. Even in the base graph with the missing nodes in it, there's no match to the MEM we're supposed to have found here. But if you follow the GBWT's haplotype paths, you can find a match.

![image](https://user-images.githubusercontent.com/5062495/46114586-1ffad980-c1a8-11e8-86dd-ebfdbd7d65cf.png)

![image](https://user-images.githubusercontent.com/5062495/46114612-39038a80-c1a8-11e8-93a5-310a165b853a.png)

The GBWT construction is apparently unable to deal correctly with these VCF records (probably just the first one):

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA12878
5	10540709	.	AAA	AAG,A	50	PASS	SOURCE=GIAB;AC=1,1;AN=2	GT	2|1
5	10540714	.	A	G	50	PASS	SOURCE=GIAB;AC=1;AN=2	GT	1|0
5	10540727	.	G	A	0	PASS	SOURCE=PG;AC=2;AN=2	GT	1|1    
```

You should be able to reproduce the problem with this small test data:

[gbwt-broke.tar.gz](https://github.com/vgteam/vg/files/2421882/gbwt-broke.tar.gz)

And these commands:

```
vg construct -r test.fa -v test.vcf.gz -a > test.vg
vg index -x test.xg -G test.gbwt -v test.vcf.gz test.vg
vg mod -D test.vg > test.extracted.vg                           
vg paths --gbwt test.gbwt --extract-vg -x test.xg -q _thread_NA12878_5_0 >> test.extracted.vg
vg paths --gbwt test.gbwt --extract-vg -x test.xg -q _thread_NA12878_5_1 >> test.extracted.vg
vg validate test.extracted.vg
```

The graph will fail validation, due to a path skipping nodes.

**Comment by adamnovak** [comment]
The GBWT problem is itself *really* caused by an alt path generation problem. The alt paths for that first variant skip nodes, and the original `test.vg` graph will fail validation:

![image](https://user-images.githubusercontent.com/5062495/46114854-571dba80-c1a9-11e8-8db1-c9b2b6776798.png)
