### ISSUE TITLE
Mapping examples do not work.

### ISSUE THREAD

**Issue by subwaystation** [vgteam/vg#1892]
Please describe:

1. What you were trying to do
I tried to use **vg** in order to work through the small Mapping examples given by your docs on the first page.
2. What you wanted to happen
**vg** should have run through without any error.
3. What actually happened
```
[heumos@wave test]$ vg index -x x.xg -g x.gcsa -k 16 x.vg
[heumos@wave test]$ vg map -s CTACTGACAGCAGAAGTTTGCTGTGAAGATTAAATTAGGTGATGCTTG -x x.xg -g x.gcsa >read.gam
[heumos@wave test]$ vg map -r <(vg sim -n 1000 -l 150 -x x.xg ) -x x.xg -g x.gcsa >aln.gam
error: could not parse d from argument "/dev/fd/63"
[heumos@wave test]$ vg surject -x x.xg -b aln.gam >aln.bam
[heumos@wave test]$ vg map -r <(vg sim -n 1000 -l 150 -x x.xg ) -x x.xg -g x.gcsa --surject-to bam >aln.bam
error: could not parse d from argument "/dev/fd/63"
```
Could this be an ArchLinux specific error? Like described in [here?](https://unix.stackexchange.com/questions/279545/failed-to-open-config-file-dev-fd-63-error-no-such-file-or-directory-for-wp)
Thanks!

**Comment by ekg** [comment]
Does it work when you write `vg sim -n 1000 -l 150 -x x.xg` to a file and pass that to `-r`?

**Comment by subwaystation** [comment]
Then the following happens:
```
[heumos@wave test]$ vg sim -n 1000 -l 150 -x x.xg > x.sim.vg
[heumos@wave test]$ vg map -r x.sim.vg -x x.xg -g x.gcsa >aln.gam
error: could not parse d from argument "x.sim.vg"
```

**Comment by adamnovak** [comment]
The `-r` option takes a float:

```
-r, --reseed-x FLOAT          look for internal seeds inside a seed longer than FLOAT*--min-seed [1.5]
```

Maybe it changed meaning since the tutorial was written?

Do you want `-T` instead?

```
-T, --reads FILE              take reads (one per line) from FILE, write alignments to stdout
```

**Comment by subwaystation** [comment]
@adamnovak Thanks!
I feel like a really dump user now xD

So it seems to be a local problem, why the examples do not run through on my machine.

**Comment by adamnovak** [comment]
No, you're not wrong; the docs are wrong. The README definitely says:

```
vg map -r <(vg sim -n 1000 -l 150 -x x.xg ) -x x.xg -g x.gcsa >aln.gam
```

That's not going to work; we need to change the README.

**Comment by ekg** [comment]
Thank you for fixing the docs. Apologies, I made the docs and the change of
variable name without updating it! Sorry for the bad advice!

**Comment by subwaystation** [comment]
No problem. Glad I could help out.
I was not aware, that `vg sim` only outputs the sequences line by line, so I put the wrong endings into the README.
