### ISSUE TITLE
bluntify GFA overlap graphs graphs

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#190]
Most producers of GFA record overlap information in the link (`L`) fields using a cigar string. However, vg does not know how to handle these overlap graphs directly, and so they must be normalized for us to read them in and use them as a basis for resequencing.

Taking the [example from the GFA-spec](https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md#example):

``` text
H   VN:Z:1.0
S   11  ACCTT
S   12  TCAAGG
S   13  CTTGATT
L   11  +   12  -   4M
L   12  -   13  +   5M
L   11  +   13  +   3M
P   14  11+,12-,13+ 4M,5M
```

There is a path:

``` text
11 ACCTT
12  CCTTGA
13   CTTGATT
14 ACCTTGATT
```

The bluntification algorithm wants to remove the duplicated region of each sequence, yielding a graph in which all edges have cigar `0M`.

How does it work?

**Comment by ekg** [comment]
A really rough sketch of the graph in question.

![photo_2016-02-02_16-40-18](https://cloud.githubusercontent.com/assets/145425/12756714/d839c672-c9cc-11e5-9597-906c4ec97b4d.jpg)

**Comment by adamnovak** [comment]
I implemented better bluntification logic a while ago, and we had some bluntification for a long time before that, so this can be closed.
