### ISSUE TITLE
Vg Command Error

### ISSUE THREAD

**Issue by JackCurragh** [vgteam/vg#1908]
When I try to use the command Vg I get an error saying that vg requires a numerical argument. I am trying to construct the graph from the test directory to understand how it works. The error also appears when I try ```vg help```

1. What you were trying to do: Follow the graph construction example
2. What you wanted to happen: Construct the test graph
3. What actually happened: 
 ```Error: Non-numerical argument.```
4. What data and command line to use to make the problem recur, if applicable
```~/vg$ vg help```

**Comment by ekg** [comment]
What was the command that you gave to vg construct?

**Comment by JackCurragh** [comment]
It was straight from the readme file 
```vg construct -r small/x.fa -v small/x.vcf.gz >x.vg```

**Comment by ekg** [comment]
What happens when you run `make test`?

**Comment by JackCurragh** [comment]
The test ran but failed this is the summary report:
```Test Summary Report
-------------------
t/02_vg_construct.t (Wstat: 0 Tests: 23 Failed: 1)
  Failed test:  17
Files=42, Tests=454, 330 wallclock secs ( 0.36 usr  0.06 sys + 364.15 cusr 31.34 csys = 395.91 CPU)
Result: FAIL
Makefile:11: recipe for target 'test' failed
make: *** [test] Error 1

```

**Comment by ekg** [comment]
Most of the tests depend on construct working, so it is very strange that
only this one construct test is failing. That would suggest something wrong
with the inputs. Verify that they have not changed with `git status`.

**Comment by JackCurragh** [comment]
```HEAD detached at v1.10.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   ../deps/boost-subset (untracked content)
	modified:   ../deps/fermi-lite (untracked content)
	modified:   ../deps/gperftools (modified content, untracked content)
	modified:   ../deps/raptor (untracked content)
	modified:   ../deps/snappy (untracked content)
	modified:   ../deps/sparsehash (modified content, untracked content)
	modified:   ../deps/ssw (untracked content)
	modified:   ../deps/structures (untracked content)
	modified:   ../deps/sublinear-Li-Stephens (untracked content)
	modified:   ../deps/vcflib (untracked content)
	modified:   ../deps/vowpal_wabbit (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../distanceIndex
	distanceIndex
	i.bam
	j.vg
	j.xg
	small/x
	small/x.vcf
	small/x.vcf (1).gz
	small/x.vg
	small/xy (1).vcf
	small/xy (1).vcf.gz
	small/xy.vcf
	small/xy2 (1).vcf
	small/xy2 (1).vcf.gz
	small/xy2.vcf
	t.svg
	testGraph
	x.gcsa
	x_gam.xg
	../testGraph

no changes added to commit (use "git add" and/or "git commit -a")

```
This came back.

**Comment by JackCurragh** [comment]
Apologies for not getting back to you sooner and thanks for the help. Yes I only see the error non-numerical argument message. Since installing have never seen the help text. 

```~/vg$ vg help```
```Error: Non-numerical argument. ```
Above are the two lines including command and resulting error.

**Comment by JackCurragh** [comment]
I am running this in bash. 
I checked with ```echo $0```

**Comment by adamnovak** [comment]
Are you sure that `vg` is invoking our `vg`? Can you do a `which vg` to check? There's a `cgvg` Debian/Ubuntu package that also provides a `vg` command, which appears to expect a single numerical argument. See: https://github.com/jreybert/cgvg/blob/master/vg.in

**Comment by adamnovak** [comment]
And specifically see this line where that script produces exactly the error message you are getting:

https://github.com/jreybert/cgvg/blob/15baf452cc09d0e79d70a719e0da8e6d93209d2a/vg.in#L54

**Comment by JackCurragh** [comment]
I am pretty sure it is your vg. 
```/usr/bin/vg``` came back. 
vg is one of only 4 softwares I have installed since I started using this pc.

**Comment by adamnovak** [comment]
It seems unlikely that `/usr/bin/vg` is actually our vg; we don't have a `make install` or any way for the vg binary we build to make it into `/usr/bin`. You would have had to have copied it there manually from the `bin` directory in your copy of the vg repo, or from your downloaded binary.

If you do a `ls -lah $(which vg)` you should be able to see the size. Our vg is going to be at least 25 MB, possibly ~300 MB if you have a version with all the debug info still in it. The other `vg` is going to be substantially smaller.

The real vg binary is going to be in `./bin/vg` from the root of your vg repository.

**Comment by JackCurragh** [comment]
Okay yes you were dead right. Is there a way that I remove this other vg?

**Comment by adamnovak** [comment]
If you're on Debian or Ubuntu it would be `sudo apt remove cgvg`. On other distros the command and package name might be different.

If you just want to override it you can add a line to your `~/.bashrc` file like this:

```
export PATH=/path/to/repo/for/vg/bin:$PATH
```

Then when you open a new shell, `vg` should refer to our vg, since it will be in an earlier directory in your PATH.

**Comment by JackCurragh** [comment]
I am on Ubunru so I removed cgvg using ```sudo apt remove cgvg```.
Now however in the vg directory vg help results in the following 
```
~/vg$ vg help

Command 'vg' not found, but can be installed with:

sudo apt install cgvg

```
This has only come about since I rebooted earlier this morning. Before that command vg resulted in:
``` 
bash: /usr/bin/vg: No such file or directory
```
``` which vg``` now results in nothing 
and ``` ls -lah $(which vg) ``` results in 
```
ls -lah $(which vg)
total 140K
drwxr-xr-x 23 jackt jackt 4.0K Oct  9 08:22 .
drwxr-xr-x  4 root  root  4.0K Sep 15 14:09 ..
-rw-------  1 jackt jackt 4.7K Oct  9 08:49 .bash_history
-rw-r--r--  1 jackt jackt  220 May 16 22:24 .bash_logout
-rw-r--r--  1 jackt jackt 3.7K May 16 22:24 .bashrc
drwx------ 36 jackt jackt 4.0K Oct  8 19:45 .cache
drwx------ 19 jackt jackt 4.0K Sep 15 15:34 .config
drwx------  3 root  root  4.0K Jun 19 18:15 .dbus
drwxr-xr-x  2 jackt jackt 4.0K Jun 25 18:13 Desktop
drwxr-xr-x  3 jackt jackt 4.0K Jul  6 10:06 Documents
drwxr-xr-x  9 jackt jackt 4.0K Oct  8 19:24 Downloads
-rw-r--r--  1 jackt jackt 8.8K May 16 22:24 examples.desktop
drwx------  3 jackt jackt 4.0K Jun  5 20:19 .gnome
drwx------  3 jackt jackt 4.0K Jun 24 15:46 .gnupg
drwxr-xr-x  2 jackt jackt 4.0K Sep 25 15:16 .gphoto
-rw-------  1 jackt jackt  12K Oct  9 08:22 .ICEauthority
drwx------  5 jackt jackt 4.0K Jun 24 16:25 .local
drwx------  5 jackt jackt 4.0K May 16 22:37 .mozilla
drwxr-xr-x  2 jackt jackt 4.0K May 16 22:37 Music
drwxr-xr-x  2 jackt jackt 4.0K Oct  2 09:56 Pictures
drwx------  3 jackt jackt 4.0K Jun  5 20:19 .pki
-rw-r--r--  1 jackt jackt  807 May 16 22:24 .profile
drwxr-xr-x  2 jackt jackt 4.0K May 16 22:37 Public
drwxr-xr-x  3 jackt jackt 4.0K Aug 17 22:08 R
drwxr-xr-x  3 jackt jackt 4.0K Sep 22 16:27 snap
drwx------  2 jackt jackt 4.0K Jun 24 15:46 .ssh
-rw-r--r--  1 jackt jackt    0 Jun 16 10:07 .sudo_as_admin_successful
drwxr-xr-x  2 jackt jackt 4.0K May 16 22:37 Templates
drwxr-xr-x 17 jackt jackt 4.0K Oct  2 10:23 vg
drwxr-xr-x  2 jackt jackt 4.0K May 16 22:37 Videos
-rw-r--r--  1 root  root   170 Jun 19 18:17 .wget-hsts

```

**Comment by ekg** [comment]
You will need to install `vg` into your path. If you run `echo $PATH` in your shell you will see a list of directories in which your shell searches for executable files matching the command line you give. I would suggest putting `vg` into `/usr/local/bin`. Just copy it in with `sudo cp bin/vg /usr/local/bin`. Then you should be able to run it from any working directory.
