### ISSUE TITLE
Banded alignment doesn't produce qualities, sequence names or alignment scores

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#191]
When aligning long reads (~8kb) I found that the output wasn't producing qual scores or sequence names.  
`vg map -B 200 -k 8 -f t.fq -g hpv.gcsa -x hpv.xg -J`

Erik figured out that it's because these are not grabbed from the input alignments during banded mapping. Mapping with a band size greater than read length yields quals:
`vg map -B 20000 -k 8 -f t.fq -g hpv.gcsa -x hpv.xg`  

I've since modified the mapper code to steal the qualities and sequence name from the input and tack it on the output (in the banded mapping function of mapper.hpp). I'll put the modified code in a new pull request soon.

However, there's still not a good concept of score for banded alignments. Erik suggested we score based on the path and the parameters used for the dynamic programming bit.

**Comment by adamnovak** [comment]
Banded alignment has been redone; I'm going to assume it fixed this issue.
