### ISSUE TITLE
vcflib SVLEN and END semantics displease me

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#1926]
I'm not sure about this whole block:

https://github.com/vgteam/vcflib/blob/98f3096f559644c2bdd296bd915256bd2e8be3a8/src/Variant.cpp#L301-L341

SVLEN is supposed to hold the length *change* caused by the alt allele of the variant, according to the vcflib spec. If we have it, we populate `info_len` with the absolute value of the field.  But then we turn around and, if SVLEN isn't set, we populate `info_len` based on the difference between POS and END, which will produce a value with completely different semantics. Then at the end we compare `info_end` and the position plus `info_len`, and bail on canonicalization if they don't match.

It looks like for an insertion we would expect END not to be the same as POS but to be POS plus the length of the inserted sequence, which would be a really weird and I think incorrect way to write the variant. That's actually what our unit test VCFs are doing, as in https://github.com/vgteam/vg/blob/a5dee39f6d3c28c05e5a3bf5bc0af1fc864e69b5/src/unittest/constructor.cpp#L1452, but I am pretty sure it is wrong. But it's something we guarantee:

https://github.com/vgteam/vcflib/blob/98f3096f559644c2bdd296bd915256bd2e8be3a8/src/Variant.h#L241

I also think I have a problem with this guarantee from canonicalization:

https://github.com/vgteam/vcflib/blob/98f3096f559644c2bdd296bd915256bd2e8be3a8/src/Variant.h#L245

SVLEN is defined as a length change by the spec, so it should be negative for deletions, positive for insertions, and zero for inversions. Right now we're using it to try and pass inversion length as well:

https://github.com/vgteam/vg/blob/a5dee39f6d3c28c05e5a3bf5bc0af1fc864e69b5/src/constructor.cpp#L741

See also: https://github.com/vgteam/vg/issues/1922

**Comment by eldariont** [comment]
I agree on all your points. The VCF specification defines SVLEN as the "Difference in length between REF and ALT alleles". This would mean:

For deletions, SVLEN<0 and the region between POS and END is deleted ==> POS - END = SVLEN
For insertions, SVLEN>0 and POS == END.
For inversions, SVLEN=0 and the region between POS and END is inverted.

**Comment by edawson** [comment]
> For insertions, SVLEN>0 and POS == END
> For deletions, SVLEN<0 and the region between POS and END is deleted ==> POS - END = SVLEN

I agree with these, and all the callers I've seen implement this. SVLEN should be negative for DELs - I thought this got fixed later in canonicalization.


> For inversions, SVLEN=0 and the region between POS and END is inverted.

None of the callers I've seen implement this as such, but I see now that is indeed how the spec states it. No example is provided for inversions in the spec. I'm not sure what to do about the disagreement.

Lumpy reports an SVLEN > 0 for inversions:
> 1       16840374        71      N       <INV>   .       .       SVTYPE=INV;STRANDS=++:2,--:4;SVLEN=382449;END=17222823;CIPOS=-217,117;CIEND=-10,0;CIPOS95=-1 ...

Manta reports an SVLEN > 0 as well:
> 1       47908159        MantaINV:4784:1:2:0:0:0 G       <INV>   .       MinSomaticScore END=216684962;SVTYPE=INV;SVLEN=168776803;IMPRECISE;CIPOS=-169,170;CIEND=-316,317;INV5;SOMATIC;SOMATICSCORE=16   PR

Delly does not report SVLEN:
> 20      9652429 INV00014010     G       <INV>   .       PASS    PRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.7.7;CHR2=20;END=9728491;PE=9;MAPQ=22;CT=5to5;CIPOS= ... 

SvABA reports SPAN (rather than SVLEN), but it is always non-zero.

> we populate info_len based on the difference between POS and END

Yep, I got this wrong. I'd still like to verify that they agree (e.g. in the case someone passes SVLENs on hg19 and ENDs on hg38, which we've seen).

**Comment by adamnovak** [comment]
We have fixed this issue by revising how vg and vcflib handle symbolic SVs.
