### ISSUE TITLE
Mysterious warning when constructing/indexing insertions

### ISSUE THREAD

**Issue by jmonlong** [vgteam/vg#1958]
I noticed a (rare) warning that appeared when simulating thousands of insertions. The small example below reproduces the warning. I'm not sure it's important but it might be hiding something.

`warning: [vg index] Alt and ref paths for a8a80fb7fa0081783e9904226d5456c8da185f52 at x:31000 missing/empty! Was the variant skipped during construction?`

In *var.vcf*:

```
##fileformat=VCFv4.1
##INFO=<ID=AC,Number=A,Type=Integer,Description="Alternate allele count">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=x>
##SAMPLE=<ID=s>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  s
x       30000   ins1    G       GAGCAACCGCCTCCAGCAGTCAATCAAATGATTCGGAGCGTGTTTCGGCCTAAGTGTTAGTACACAGGCGGCGATCGTAGAGCCAAGATGGGCCGTGTGCCTCTAGATAGCGACCGTCAACGCTCTGTTTCCCGCCTTTGTCTAGCTTTTAAACGCCCCCTG      99      .       AC=1    GT      1|0
x       31000   ins2    C       CGTATAGTCCCGGACCAAGGTCATCTAAGGTGACAATATGCAGGGCTGCCATATACCTCGAGTACACTCACCCGATTAAAAACCCGTCGGCTTGGTCAGTGCGCATGGGCCTGTTTAATTGCTGAGGAAACATTCGCTTTCTAAAGAGCTGGGCCACACTCTGCGGGGTTCCGTAATAGCGGCTACTTCCGGTTAACCGTATGCGGACCATCAGCCGAACCCAAAAGTCGACGTGCCGCAATCCTCGACAGTAGGCCCTACGTTTATATCATTTGTAGCCGGGCCCCGTTTTGTCCATGAGTCTGGTCTGGACATTGGTGCAGAAACGCACATTCAATGACTTGAAAGATTTATTAACGTGTATTGGTTGCAGGTGTTTGTACCTCCAGTATCCACGAATGTCCGTGAAGACAAATTACCGTTTAAGGTCAGTGTACGCGAACAGTTGCTATGATCATACGGGGGAGGTAACAATGCGCCAGCGTTATTCAATCGTCTATAGCAACACGGCTGGTGTGATGCGAGGTCTAACTTTGAGCCTGATTTTCCATATAACAATGGGAGTTAGGCTCGGGCTATTAAGTTATGACCCTGACAGACTTGATCGCGGAGAAACCAGCTGTTGTCACATAAGGAACAGAAGCCCATACCAAGAAGTAAACGAGGCGTAATGTCGTTGCACGGCACCTGTCTATTTTATAGTTGCTGAAGTTAGGTGGTACGACGGTGCAGTTTGTATAATAACTTGCAGGCGAACGGCCCGACAACATATGGCTCCT     99      .       AC=1   GT       0|1
```

The [ref.fa.gz](https://github.com/vgteam/vg/files/2512929/ref.fa.gz).

And the commands:

```
bgip var.vcf
tabix var.vcf.gz
vg construct -r ref.fa -v var.vcf.gz -a -f -m 32 > x.vg
vg index -x x.xg -v var.vcf.gz x.vg
```

What I noticed when trying to reproduce the warning:

- both insertions needs to be there.
- the inserted sequence is not important
- the size of both inserted sequences is important: no warning if shorter
- the distance between insertions is important: e.g. no warning if 100s bp further
- the amount of sequence before, here 30kbp, seems important

At some point I noticed inconsistencies between the node ids in the vg and xg (shifted by 1). But after building the latest vg, I can't see that anymore (but the warning is still there). Both the vg and xg look fine and contains the insertion which is why I'm not sure how important that is.

**Comment by adamnovak** [comment]
I'm not able to reproduce the issue with the files and commands you provided. I am using vg v1.11.0-126-gfd328f5c.

This is what I get when I dump the paths in the vg I build. Is this what you get also?

```
vg paths --list -v x.vg
_alt_d9a250df1d95b4ee9435213dbe984afdba18b7eb_0
_alt_d9a250df1d95b4ee9435213dbe984afdba18b7eb_1
_alt_e5871288906aff45c5b14154e03910d89e0db9cf_0
_alt_e5871288906aff45c5b14154e03910d89e0db9cf_1
x
```
I have paths for both variants, although neither has hash a8a80fb7fa0081783e9904226d5456c8da185f52.

Here's the graph I get. Can you post your graph if it is different?

[x.vg.gz](https://github.com/vgteam/vg/files/2515954/x.vg.gz)

Could you also maybe post your vcf file as a file? It could be in fixing up the spaces to tabs when copy-pasting from Github I missed an important detail that is causing the variant to get the wrong hash somehow in index vs. in construct.

**Comment by jmonlong** [comment]
I'm using the vg v1.11.0-110-g1a02460a

This is what I get:

```
vg paths --list -v x.vg
_alt_a8a80fb7fa0081783e9904226d5456c8da185f52_0
_alt_a8a80fb7fa0081783e9904226d5456c8da185f52_1
_alt_bf7238687c0e3dc0a08b5db05371a9bc9423338c_0
_alt_bf7238687c0e3dc0a08b5db05371a9bc9423338c_1
x
```

My graph is different. Here it is 
[x.vg.gz](https://github.com/vgteam/vg/files/2516378/x.vg.gz). 
And the vcf 
[var.vcf.gz](https://github.com/vgteam/vg/files/2516380/var.vcf.gz).

I'll try to reproduce with the latest vg.

**Comment by jmonlong** [comment]
I get the warning and the same hash with vg v1.11.0-126-gfd328f5c but you're right the var.vcf was a bit different, sorry about that I must have mixed up with one that don't get the warning. The var.vcf.gz from the previous message is correct.
