### ISSUE TITLE
visualize a graph and alignments with 1bp nodes

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#196]
For visualization, we should be able to use `vg mod -X` and friends to also chop up alignments so that they are described in terms of single bases. This will make rendering MSAs and assemblies more regular and hopefully easier in some cases.

**Comment by adamnovak** [comment]
I'm not sure this is really practical for visualization, and @wolfib is working on a visualizer that can draw reads within nodes.

I'm going to close this; please re-open it if you think we still should do this.
