### ISSUE TITLE
trying to construct variation graph

### ISSUE THREAD

**Issue by ziaursani** [vgteam/vg#2003]
I am trying to construct variation graph with the following command

For i in $(cat filename1.txt);
do ./vg construct -C -R $i -r filename2.fasta -v filename3.vcf.gz –m 32 > $i.vg; done

I am getting following error

Assertion: 'reference_for.count (fasta_name)' failed.
Error Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash/dGSY2m/stacktrace.txt

**Comment by glennhickey** [comment]
It looks like you have a sequence name in filename1.txt that is not present
in filename2.fasta.

The error message here should be more verbose, though.
