### ISSUE TITLE
High memory use for GCSA indexing of reference-only graph

### ISSUE THREAD

**Issue by gmagoon** [vgteam/vg#2007]
Hi vg devs,
I've been working with a vg build from a recent master branch head, 1c59f2e.

I've been trying to create indices for a reference-only graph for hs37d5.fa (no variants, with no VCF specified at construct step). I've encountered some issues with high memory use on the GCSA indexing step. Based on the [wiki](https://github.com/vgteam/vg/wiki/Working-with-a-whole-genome-variation-graph), I was expecting the memory use to top out around 100 GB, at most, but in my attempts it has been trying to use more than the 256 GB RAM on the system I was using. Now granted, I am using a single .vg file in contrast to the per-contig vg file approach described in the wiki. But I would have expected that to impact the memory use on the construct step rather than indexing steps. Also, note that I didn't do the prune step as there is no variation in the graph.
The command I'm using is pretty simple (no special options / flags): `./vg index -g hs37d5.gcsa hs37d5.vg`

The .xg indexing step for the same (reference-only) graph maxed out at just over 5.1 GB. The wiki seemed to suggest that was the more memory-intensive indexing step (at least for the graph considering 1000G variation).

Any feedback on this would be much appreciated, particularly with regard to whether this is expected behavior or not.

Thanks very much in advance,
Greg

**Comment by jltsiren** [comment]
The memory usage of GCSA construction is usually proportional to the size of the largest `.vg` file. This is a space optimization. We assume that a path cannot cross from one graph file into another, so we only need to load path fragments from one graph file into memory when extending path length. A reference-only GCSA index could be built with a simpler and more space-efficient algorithm, but we have not implemented it.

**Comment by gmagoon** [comment]
ah, so it is my use of a single .vg file that is the source of the issue....thanks very much @jltsiren
