### ISSUE TITLE
vg sim -F produces invalid GAM

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2027]
I caught `vg sim -F`making a mapping that falls off the end of a node. 

The node is 25bp long: `S	41332064	TGGCATGATTGTATATTTAGAAAAC`

The simulated GAM is going 14 bases past offset 18 (32)

{"sequence":"TT
TGGTCACAGAGAAGTTAAATGTCTTAACGAAGTGATCTCTGTCATTTTTTGCTTTTTTCTAGAAGTTTCTGCCTTGCTCACATGTTTTTCCAAGTCTCCC
TTAGGTGATTGGTGTATCTGTTTG","path":{"mapping":[{"position":{"**node_id":"41332064","offset":"18","is_rev
erse":true},"edit":[{"from_length":14,"to_length":14}],**"rank":"1"},{"position":{"node_id":"41332063"
,"is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"2"},{"position":{"node_id":"4
1332062","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"3"},{"position":{"nod
e_id":"41332061","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"4"},{"positio
n":{"node_id":"41332060","is_reverse":true},"edit":[{"from_length":9,"to_length":9},{"from_length":1
,"to_length":1,"sequence":"C"},{"from_length":6,"to_length":6}],"rank":"5"}]},"name":"seed_1774_frag
ment_87300_2","quality":"ICEgISEmJiYmJiYlJiYmJiUmJiYmJiYfJR8iISQmJiYhIxAQEBAlJB8lIiYQGSEkJSYmJiYmJRAkJiQmJiYmJiYmJiYmJiYmJiYkJiImIiYmJiYmIR8lJiYmJiYmJiYmDxoOIiEdJSYmJiYmJiYfISUPDw8XFw8PDw8lJiYP","score":131}

This is coming off a whole genome run through toil-vg that runs commands like

`vg sim -x index.xg -n 128000 -p 570 -v 165 -i 0.002 -I -s 2 -F error_template.fastq -a | tee sim_0_1_unannotated.gam | vg annotate -p -x index.xg -a - | tee sim_0_1.gam | vg  view -aj -`

Did notice the warning `INFO:toil-rt:(stderr) warning:[NGSSimulator] Recommended that insert length mean (570) > 5 * insert length standard deviation (165)`

**Comment by jeizenga** [comment]
For the record, that warning from the simulator is just because the distribution gets truncated by the first read in the pair. You won't notice it if the mean is far from 0 (in std dev units), but if it's too close to 0 the statistical properties of the insert length distribution might get a little funky. I probably should make it a little less stringent. 2.5 standard deviations is probably plenty.
