### ISSUE TITLE
RepresentativeTraversalFinder crashes on cactus graph with failed assertion

### ISSUE THREAD

**Issue by eldariont** [vgteam/vg#2041]
Hi,

I was running `toil-vg call` on one of my cactus graph and it crashed:
```
RuntimeError: Docker container for command vg call chunk_S288C.chrXVI_0_aug.vg -t 4 -S SRR4074257.recall.cactus.twoout -z chunk_S288C.chrXVI_0.trans -s chunk_S288C.chrXVI_0.support -b chunk_S288C.chrXVI_0.vg -u -n 0 -r S288C.chrXVI -c S288C.chrXVI -l 954457 -o 0 failed with code 134
```

I can reproduce the error with the following files and commands on vg v1.12.1-83-g9a00b102 "Parolise":
`vg call chunk_S288C.chrI_0_aug.vg -t 4 -S SRR4074257.recall.cactus.twoout -z chunk_S288C.chrI_0.trans -s chunk_S288C.chrI_0.support -b chunk_S288C.chrI_0.vg -u -n 0 -r S288C.chrI -c S288C.chrI -l 219929 -o 0`

Files: https://www.dropbox.com/s/gfpdtmymjfjz90z/Archive.zip?dl=0

Result:
```
...
S288C.chrI	23744	5516691_5514212_5552938_5553675_5540725-5516691_5553675_5540725	A	AGG	4473	PASS	DP=301;SVLEN=2;XSEE=9892,9893,9894,4887785;XREF	GT:DP:XDP:AD:XADL:SB:XAAD	1/0:301:140,237:120,181:-8.250185:60,60,95,86:181
S288C.chrI	23741	5578978_5558693_5533720_5516691-5578978_5558693_4887786_5516691	TTT	GCG,GCA	3402.67	lowxadl	DP=271;SVLEN=0,0;XSEE=9890,9891,9892,3945529,3945530,4887786;XREF	GT:DP:XDP:AD:XADL:SB:XAAD	1/2:271:140,237:0,181,90:-17.880078:0,0,79,102,39,51:271
S288C.chrI	23735	5539370_5561058_5565421	A	G	6762.33	PASS	DP=182;SVLEN=0;XSEE=9886,9887,9888,4777338;XREF	GT:DP:XDP:AD:XADL:SB:XAAD	1/1:182:140,237:1,181:.:0,1,78,103:181
S288C.chrI	23732	5518064_5506440_5549947_5539370	AG	TT	6963.8	PASS	DP=186;SVLEN=0;XSEE=9883,9884,9885,9886,3945528,5277386;XREF	GT:DP:XDP:AD:XADL:SB:XAAD1/1:186:140,237:0,186:.:0,0,69,117:186
S288C.chrI	23728	5560953_5550838_5518064	A	T	7219	PASS	DP=192;SVLEN=0;XSEE=9881,9882,9883,3945527;XREF	GT:DP:XDP:AD:XADL:SB:XAAD	1/1:192:140,237:0,192:.:0,0,83,109:192
S288C.chrI	23722	5582180_5573761_5533682_5506174_5503309_5529903_5560953-5582180_5556196_5533682_9879_9880_5560953	TCGAG	TCAGC,CCGAG	2879.8	lowxadl	DP=238;SVLEN=0,0;XSEE=9876,9877,9878,9879,9880,9881,3311828,3945524,3945525,3945526,4887788,5089103;XREF	GT:DP:XDP:AD:XADL:SB:XAAD	1/2:238:140,237:19,141,78:-11.298452:6,13,64,77,32,46:219
vg: src/traversal_finder.cpp:1146: vg::RepresentativeTraversalFinder::find_traversals(const vg::Snarl&)::<lambda(std::vector<vg::Visit>)>: Assertion `contents.first.count(augmented.graph.get_node(visit.node_id()))' failed.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_zg8mUz/stacktrace.txt
```

**Comment by adamnovak** [comment]
OK, I've managed to replicate this. It looks like the traversal finder is trying to find a traversal that includes something that isn't actually in the snarl that it is trying to find a traversal of, which it detects is nonsensical.

To actually find and fix the problem, I'm going to have to break out just the subgraph of the offending snarl, make a little unit test out of it, and then fix it to pass. Not too hard, but I don't think I'm going to be able to get to it until January, unfortunately.

**Comment by eldariont** [comment]
Thank you, Adam, for looking into this!
From my side, there is no hurry because I can just use vg version 1.11 in the meantime which does not have this issue. Merry Christmas! 🎅

**Comment by glennhickey** [comment]
I'm seeing something pretty similar on a graph containing inversions made with `vg construct`.  

@adamnovak, do you mind taking a look? Everything to reproduce is on courtyard (see README) here: `/public/home/hickey/dev/hgsvc/call-crash`

```
error[RepresentativeTraversalFinder::find_traversals]: Node 134063640 not in snarl {"start":{"node_id":"134154177"},"end":{"node_id":"134146655"},"start_self_reachable":true,"end_self_reachable":true,"start_end_reachable":true,"directed_acyclic_net_graph":true} contents:
	134086936
	134100073
	134117067
	134145997
	134146655
	134080600
	134118852
	134154177
	134127311
	134078629
	134124661
	134132419
vg: src/traversal_finder.cpp:1176: vg::RepresentativeTraversalFinder::find_traversals(const vg::Snarl&)::<lambda(std::vector<vg::Visit>)>: Assertion `false' failed.
```

![inversion](https://user-images.githubusercontent.com/901102/51620460-6c5ce880-1f00-11e9-803b-9b3eb4b77a72.png)

**Comment by adamnovak** [comment]
I'll have a look at this.

**Comment by glennhickey** [comment]
Thanks!  From the error message it seems like it's finding its way inside a
child snarl then getting mad because the node's not in the shallow
contents.
