### ISSUE TITLE
Unable to GCSA index graph with hs38d1 decoys

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2044]
I can successfully GCSA index the 24 chromosomes from HG38 with gbwt-backed pruning using toil-vg.  When I add in chrM, chrEBV, and the 2500 hs38d1 decoy sequences, I get `PathGraphBuilder::write(): Size limit exceeded, construction aborted`.  I've used the same code to index hs37d5 (where the decoy sequences are all concatenated together) without issue.  I'm presently trying to figure out if toil-vg's doing something wrong here but @jtsiren does it make any sense to you that passing thousands of small (linear) scaffolds as separate graphs to gcsa indexing would cause the above error?

To prune the 24 chroms, I'm using
```
vg prune --append-mapping mapping --unfold-paths --gbwt-name graph.gbwt
```
To prune the remaing 2500 '.vg', (they have no variation so this presumably does nothing)
```
vg prune --restore-paths
```
Then I pass my 2500+ files to vg index (on an i3.8xlarge node)
```
vg index --gcsa-name out.gcsa --threads 16 --temp-dir ./index-temp --mapping mapping chr1.vg chr2.vg ... chrM.vg decoy1.vg decoy2.vg ... decoy2500.vg
```

**Comment by glennhickey** [comment]
I left an important part out of the original issue:  I'm also mixing in SVs from 3 HGSVC samples into the 1kg VCF.  Given that @adamnovak has successfully indexed the decoy sequences before, it's probably the SVs at issue here.  Both the SVs and HG38 1kg vcf run through fine alone, but combining them seems to lead to problems.  One idea after discussing with @adamnovak, is that perhaps the SVs are increasing the complex region sizes during pruning, leading the pruner to fill in paths from many more haplotypes than usual (from 1kg) for these regions.  I'll get some tests going that should confirm this soon..

**Comment by adamnovak** [comment]
I think we really want @jltsiren.

**Comment by jltsiren** [comment]
The progress information from the `-p` option of `vg index` should give a better idea what went wrong.

Also, is your `ulimit -n` high enough? With 2500+ input files, GCSA construction will open 10000+ temporary files at the same time.

**Comment by glennhickey** [comment]
See #2059
