### ISSUE TITLE
which pipeline should I use to generate starting vcf file to feed vg pipeline?

### ISSUE THREAD

**Issue by MehmetGoktay** [vgteam/vg#2058]
Hi,

I wonder if there is a good pipeline to generate starting vcf file to feed vg pipeline?

Best,
Mehmet

**Comment by MehmetGoktay** [comment]
Hi,

I wonder if there is a good pipeline to generate starting vcf file to feed vg pipeline?

Best,
Mehmet

**Comment by MehmetGoktay** [comment]
Thank you very much for your detailed answer.

**Comment by adamnovak** [comment]
Thanks!

I'm going to go ahead and close this issue. Please feel free to re-open it if you have more questions on the subject.
