### ISSUE TITLE
Unable to GCSA index SV-SNP graph after prune -u

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2059]
When I GCSA index a graph made from a merged VCF of 3 phased SV genomes and the 1000 Genomes GRCH38 calls, I get `PathGraphBuilder::write(): Size limit exceeded, construction aborted`.  
The following works:
* same pipeline on either input graph (1kg or SV) individually
* same pipeline but doing restore-paths instead of unfold-paths on the pruning step
* same pipeline run just on chromosome 1 (I didn't check all chromosomes in this way)

The following didn't help:
* making the gbwt with forced phasing
* thresholding rare (AF<1%) variants before cosntruction

Everything to reproduce is on courtyard in `/public/home/hickey/dev/hgsvc/pruning/HGSVC-1KG-jan5`
See `COMMAND` for the command line, `toil-vg.error` for the stack trace, `whole_run.stderr` for the output of running `vg index` with `-p`.  

Simply not pruning with unfold-paths is a workaround, but I think this shows there may be an issue with the unfolder on complex regions in the presence of large deletions.  

(This has nothing to do with decoys as previous suggested at the top of #2044)

**Comment by jltsiren** [comment]
The construction failed in the third `extend()` step in chr11. Here is one example of a region, where the paths have too many extensions:

![loop](https://user-images.githubusercontent.com/11444026/51275934-2ea01300-1988-11e9-8d7a-fca1e9b6d8cf.png)

There is a cycle that consists of nodes 196896290 and 196896292. All nodes in this region have their original ids. Pruning didn't remove enough edges to disconnect the nodes from the rest of the graph, so unfolding simply restored all edges used in the haplotypes.

I'm not sure if this is a bug in `find_edges_to_prune()` or if the situation can be solved with more aggressive pruning.

**Comment by ekg** [comment]
Is the problem that a cycle has been introduced somehow in the graph construction? You could also greedily prune cycles out of the graph in preparation for indexing.

**Comment by glennhickey** [comment]
The original graph doesn't seem to have the cycle, so as far as I can tell it's getting added by the pruning:
![orig](https://user-images.githubusercontent.com/901102/51335681-afc2dd00-1a50-11e9-84ae-923c3264e348.png)

**Comment by jltsiren** [comment]
I guess there are (at least) two possible insertions between reference nodes 196896289 and 196896293 and a haplotype that contains both of them. Because an insertion corresponds to an empty reference range (the alt path contains only the insertion and no reference nodes), the haplotype generation logic in GBWT does not detect the overlap. Because there is a haplotype using an edge from 196896292 to 196896290, unfolding adds the edge to the graph.
