### ISSUE TITLE
inversions are off by one with vg construct -S

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2072]
This is actually illustrated in the tests where this inversion at (1-based) x:9

`x 9 sv1 C <INV>`  (https://github.com/vgteam/vg/blob/master/test/sv/x.inv.vcf#L10)

is getting made at (1-based) x:10  

![inv](https://user-images.githubusercontent.com/901102/51693732-84e70480-1fcd-11e9-8f29-73bd80d5cd02.png)

**Comment by glennhickey** [comment]
This seems to be by design:
https://github.com/vgteam/vg/blob/master/src/constructor.cpp#L821-L825
```
// "If any of the ALT alleles is a symbolic
// allele (an angle-bracketed ID String “<ID>”)
// then the padding base is required and POS
// denotes the coordinate of the base preceding
// the polymorphism.
```
But the inversion example in that same spec seems to contradict this;
![screenshot from 2019-01-24 14-33-56](https://user-images.githubusercontent.com/901102/51703736-20d03a80-1fe5-11e9-9c7c-101921a0a4a7.png)

**Comment by edawson** [comment]
I placed that bit of text from the spec:

> If any of the ALT alleles is a symbolic allele (an angle-bracketed ID String “<ID>”) then the padding base is required and POS denotes the coordinate of the base preceding the polymorphism.

I twiddled with this forever. My opinion is that the spec contradicts itself, or at the least is *very* confusing.

**Comment by glennhickey** [comment]
Yeah, seems like a contradiction.  Hoping to hear back from https://github.com/samtools/hts-specs/issues/375

**Comment by edawson** [comment]
We also posted about this here, with little apparent hope of resolution: https://github.com/samtools/hts-specs/issues/173

**Comment by glennhickey** [comment]
Aha, no sense complaining about it here, then!   I was originally triggered when comparing my multibase-snp inversions (from vg call) to the symbolic allele inversions (fed into vg construct) and noticing the off-by-one.  But that's just the spec.
