### ISSUE TITLE
vg find -p can produce "invalid" graphs

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#208]
It gets edges off nodes in the path but not the nodes on the other ends.

If dangling edges make a graph "invalid", we shouldn't output them under such normal circumstances.

**Comment by adamnovak** [comment]
I'm going to close this, pending a larger discussion of graph validity.

**Comment by jeizenga** [comment]
FWIW, I don't think we should ever produce a graph like that if for no other reason than it will probably break a lot of code elsewhere if we try to pipe the graph into another command.
