### ISSUE TITLE
`vg stats -a` looks like it is spending all its time fighting over per-statistic locks

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#2092]
The code for `vg stats`'s processing of reads tracks a bunch of counters, and for each read it locks and increments the appropriate counters in turn, in parallel over the reads.

I'm pretty sure that this is spectacularly inefficient, especially with lots of threads. Instead, each thread should compute its own stats, and then the stats should be aggregated and reported at the end. We should be able to get away with not doing any locking at all. We should copy the way that `vg filter` collects counts for filtered reads due to each kind of filter, and then aggregates at the end.

Someone should 1) profile `vg stats` to see if I'm right about this and 2) refactor it to use per-thread stat computation with final aggregation.

**Comment by glennhickey** [comment]
Yeah, judging from experience with vg filter, you ought to be able to get
near linear speedup out of for_each_parallel() when doing even very simple
GAM stats (at least for a handful of cores).

This isn't an issue for stats, but doing tests of vg filter really showed
me what a bottleneck *writing* the GAM is.  It would take a bit of
profiling to be sure, but I would expect that a parallel GAM writer could
be used to speed up anything writing GAMs.   The idea would be the same:
compress them into some thread-specific buffers, then write them out
sequentially.  I've rarely seen a 32-core mapping job use much more that
2300% CPU, and I wonder how much time is lost blocking on protobuf
compression.
