### ISSUE TITLE
Picard SortSam fails on VG Surjected BAMs

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#2093]
@ekg @jeizenga 
When attempting to sort a VG surjected BAM by queryname using picard's `SortSam` function, I get the following validation errors for numerous reads:

>Ignoring SAM validation error: ERROR: Record 493973, Read name {READ_NAME} , Mapped mate should have mate reference name

The version of VG I've used for mapping and surjecting this BAM file is within the docker container `quay.io/vgteam/vg:v1.11.0-215-ge5edc43e-t246-run`

When running picards `ValidateSamFile` on that same BAM file I get the following stats:
```
## HISTOGRAM    java.lang.String
Error Type      Count
ERROR:INVALID_CIGAR     8351
ERROR:INVALID_FLAG_MATE_UNMAPPED        3185895
ERROR:MISMATCH_FLAG_MATE_NEG_STRAND     540797418
ERROR:MISMATCH_FLAG_MATE_UNMAPPED       3185895
ERROR:MISSING_READ_GROUP        1
WARNING:ADJACENT_INDEL_IN_CIGAR 49
WARNING:RECORD_MISSING_READ_GROUP       1084761484
```
It looks like out of the total number of reads, about 0.3% of them have a mate that's unmapped. Should I simply ignore these records?

Is this a problem with vg surject? Has this been resolved in a newer version of VG? Or could there be something wrong with mpmap?

**Comment by jeizenga** [comment]
Hmm. In mpmap it is possible to have discordantly mapped reads if it can't find a concordant pair of mappings. In that case, it is also possible that one read would be unmapped. However, I wouldn't expect it at that rate. 

I don't know how surject generates those SAM flags from the GAM. Any insight there @ekg?

I'm also a bit unsettled by this "invalid CIGAR" warning. Do you have any idea what those reads look like?

**Comment by ekg** [comment]
As far as I know you need to apply Picard reordersam to fix the ordering of
the files so they match the reference chromosome order. This may be
unrelated.

**Comment by ekg** [comment]
Ok I see. We can add this to the unmapped mates.

**Comment by cmarkello** [comment]
I've already run reorderedsam on these BAMs so I don't believe that's
related to the problem here.

**Comment by cmarkello** [comment]
After counting samtool flag stats on a chromosome 21 subset of my surjected BAM I get the following

**Comment by cmarkello** [comment]
@glennhickey @jeizenga 
This definitely seems like a problem with VG Surject. It looks like Surject is failing to relabel properly paired reads when their mate is missing after the surjection process. 

When I filter the surjected BAM file to chromosome 21 and for reads that are properly paired I get the following SAM flag statistics from `samtools flagstat`:

> 13646706 + 0 in total (QC-passed reads + QC-failed reads)
> 0 + 0 secondary
> 0 + 0 supplementary
> 5098 + 0 duplicates
> 13646706 + 0 mapped (100.00% : N/A)
> 13646706 + 0 paired in sequencing
> 6840751 + 0 read1
> 6805955 + 0 read2
> 13646706 + 0 properly paired (100.00% : N/A)
> 13646706 + 0 with itself and mate mapped
> 0 + 0 singletons (0.00% : N/A)
> 212112 + 0 with mate mapped to a different chr
> 123600 + 0 with mate mapped to a different chr (mapQ>=5)

When sorting the BAM file by readname and looking at the 1st few reads I get records where their mate read record is missing. Sorting by readname via `samtools sort -n` should put read pairs next to eachother and since I've filtered for properly paired reads, every read record should have it's pair next to it, but that's not showing up on the surjected BAM file.

```
HISEQ1:22:H9UJNADXX:1:1101:1156:94225   83      21      14414911        13      148M    *       0       0       GGCGAAAACAGGACAACTCTGATGAAGGTAAATGGTAGCCAGTTCTTTCAGCAGGAGATGGATTTGGTTTAAATACATAGAATAAAAATGAATTTATCTCATTGAAATATAACTAGTTTGTGAAACCTGTGGAATATTTATTTATATT      <BBCACDCCDDDDDDCDDDDEEDDDDDEEDDDDDDCDDDDDDDCCECEDEEFFFFFHHHHHIJJJJJJJJIGIHGJIIEJJJJJJJJJJJJJJJJJJJJJJJJIIJJIIJIIJJGJJJJIJJJHFJIJJJJJJJJGHHHHFFFFFCCC      NM:i:0  MD:Z:148        PG:Z:MarkDuplicates
HISEQ1:22:H9UJNADXX:1:1101:1158:66266   83      21      37652868        60      148M    *       0       0       TAGTGGAGAAATACTGCCGAAAGCATCCAGCTTCACATCTTGACATTTGTGCTGAAAGTAATAAGTTTCTATAATTTACTAGGAGGACTTTTCTACACCTCAGATCCCTTCTCATGCACTATCATTAAGTATCATTAAAGAAATAAGT      CDDDDDEEDEECADDDBDDDEDDDDDDDDDDEEDDDDDDEEDDDDDDDEEEEEEFFFFFFFGHHHHJGGIJJJJJIHHJJJJJIHFBIJJJIJHHFBJJJJJJJJIJJJJJJJJIGHFIJJJJJJJJJJJJIIJJHHHHHFFFFFCCC      NM:i:0  MD:Z:148        PG:Z:MarkDuplicates
HISEQ1:22:H9UJNADXX:1:1101:1159:55163   67      21      36266562        60      148M    *       0       0       CATGTCTGAGTCTAAGAAATTGGAGTAGGAGAGCAAGAAAACACAAGTTCATCTACACACCTAATAGTTCAGCAATTCTGAGGAAAATGCCAGGATTTTTTAAACCCAAAAACAAGGGCAAAAATGAGTGGATTTTGAAAACTGTGAT      =@@DBDD?FFACFGBHEHBEIIIFB3ACFEH<@?<CFGGII>G?FGIGGGGIDIIHGFIIIIIIIBA=DGHD>ECCHHHBDBEEACC>>@CCC?=CCCCCB?ACC??@BBB8>BB<@?B?<BC8?>4>+4<CC@@CCBACCCCC::@@      NM:i:0  MD:Z:148        PG:Z:MarkDuplicates
HISEQ1:22:H9UJNADXX:1:1101:1159:78074   67      21      29720994        60      148M    *       0       0       AATAAATAAAAACTTTTTAACATGGGAATGCCACAATTTTGTGGCAGCTGGGGACAAATGTTTCTAGTGTTTTTTGTGGCAGGGAAATGCAATCAGTTCATATGGAAGATGAATTTAGTTTTTGGATGTTCCTCCTTGTAATTAATAA      CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJHIIJJJJJJJJJIJJJJIJCHIIJJJDEAHHHFDCBCDDDDDD8<A:3:4@:::4+::::(+4@4:38::>>:AC:>:@DDD05(((4>3>:>C9>(4:>:B:A4:@      NM:i:0  MD:Z:148        PG:Z:MarkDuplicates
HISEQ1:22:H9UJNADXX:1:1101:1162:91161   67      21      22471662        60      113M1D35M       *       0       0       CACGCTGCTATAAAGAACTGCCTGAGACTAGGGAATTTATAAGGAAGAGAGGTTTAATTGGCTCACAGTTCTGCATGACTGGGGAGACCTCAGGAAAAATACAATCATGATGGAAGGCCCCTCTTCACAGGGCAGCAAGAGAGAGAAG      @@@DDDDDHAFFHGHJEIHHHIGIJJIJJ<EF)?FHIJ@DI@D?DHFCHGCG9CDGGFHJGDFGEGD=@@=EEHGCHDDFFBCBCD??BDDDCDCDDCD1>:CCCC@CD>CCCDD?@ABBDDBCC>>CD@B7<B>??CC?8<@B@BC?      NM:i:2  MD:Z:32T80^A35  PG:Z:MarkDuplicates
```
