### ISSUE TITLE
Y; do your VCF and FASTA coordinates match?

### ISSUE THREAD

**Issue by MehmetGoktay** [vgteam/vg#2094]
Hi,

I keep getting this awkward error when I try to run vg construct on the merged vcf file which was called by Freebayes. 

Could anyone kindly let me know how to solve this problem.

This is my script : vg construct -t 50 -r Reference.fa -v merged.vcf.gz> graph.vg

This is the error : 

error:[vg::Constructor] Variant/reference sequence mismatch: N vs pos: 12192624: Y; do your VCF and FASTA coordinates match?
Variant: 1	12192624	.	N	C	51.1739	.	AB=0;ABP=0;AC=4;AF=1;AN=4;AO=3;CIGAR=1X;DP=7;DPB=4;DPRA=0;EPP=3.73412;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=56.3333;MQMR=0;NS=1;NUMALT=1;ODDS=10.1503;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=44;QR=0;RO=0;RPL=1;RPP=3.73412;RPPR=0;RPR=2;RUN=1;SAF=0;SAP=9.52472;SAR=3;SRF=0;SRP=0;SRR=0;TYPE=snp
zero ind: 12192623 1-indexed: 12192624

**Comment by ekg** [comment]
It looks like freebayes is quashing the "Y" into "N". Could you convert all non-ATGC characters in the reference to N?

Sorry that vg and freebayes are being a little heavy-handed here.

**Comment by glennhickey** [comment]
I've run into this before too.  It even comes up in different versions of
the reference.  For instance,
ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
contains Y's (and other funny IUPAC characters) whereas
http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz has only
Ns at these positions.  Mixing and matching can anger vg.

You can fix up a reference with something like this

`awk 'BEGIN{FS=" "}{if(!/>/){ gsub(/[YRWSKMDVHBXyrwskmdvhbx]/,"N"); print
}else{print $1}}' ref.fa`

**Comment by MehmetGoktay** [comment]
It worked. 

Thanx.
