### ISSUE TITLE
Sharing HandleGraph and Algorithms code with dsgvg

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#2104]
As was discussed at the vgteam call today, we want to share some code between vg and @ekg's https://github.com/vgteam/dsgvg. Specifically, we want to share the `handle.hpp` handle graph interface, and some algorithms from `algorithms`.

Whatever we do, we're going to have to factor out the shared code into its own folder(s) and have it build its own library that does not depend on the greater `libvg`. Maybe it will be `libhandlegraph`? It might be worth it to make the base handle graph interface separate from the algorithms, which would in turn depend on it.

We're also going to have to work out how to actually share the code in the Git repos. We could:

- Just copy-paste files around manually, and track two copies of the code. Simple to start, but potentially terrible if we want to try and merge/synchronize changes.
- Make a new repo for this shared code, and pull into both dependent projects as a Git submodule. We understand how to work with submodules, but this makes PRing changes that touch this shared code very hard, as you have to get your PR against the shared repo merged before any PRs in the dependent repos can even start being tested. This was a huge pain with `xg` and drove the integration of `xg` into the main vg repo.
- Make a repo for the shared code, and pull it in to both projects using [Git subtrees](https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree). This is kind of a git-assisted copy paste. Everything actually exists and can be modified and PR'd as normal in both dependent repos, but Git has some machinery to rewrite changes into/out of commits that just talk about the subtree's code, and by doing that and having a Github repo for just the subtree, we could keep the two dependent repos' copies in sync. The downside is everyone who wants to sync things up has to learn the Git wizardry required to make that happen.
- Try using [git-subrepo](https://github.com/ingydotnet/git-subrepo#description). This is supposed to be "better" than either subtrees or submodules according to its author, but it's an aftermarket add-on to Git that people would have to install to sync up the subrepos.

**Comment by jeizenga** [comment]
I think my vote is for submodule, tbh. I don't think `handle.hpp` is as unstable as the `xg` code was. Although, the same might not be true of `algorithms`...

**Comment by jeizenga** [comment]
I'm considering this resolved now that we have `libhandlegraph`
