### ISSUE TITLE
MAF Import

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#2119]
Please describe:

1. What you were trying to do

Construct a graph from a MAF file.

2. What you wanted to happen

Integrate the paths/sequences that the MAF was constructed from into the graph

3. What actually happened

```
error:[vg construct] cannot construct from a reference/VCF and an MSA simultaneously
```

4. What data and command line to use to make the problem recur, if applicable

```
vg construct -r pg.fasta  -M pg.maf -F maf > pg.vg
```

I guess this approach was never intended. MAFs should be converted to a GFA file anyway. Just wanted to check if there is a way to do it, and I don't see it.

**Comment by jeizenga** [comment]
Yes, the FASTA constructor and the MSA constructors are quite distinct. Unfortunately, last I checked the MAF constructor is broken--it doesn't fully support the generality of the MAF format, where the same base in one of the input sequences can appear in multiple aligned blocks. Fixing it has been on my to-do list for quite a while, I'm afraid.

As a short-term workaround, I might suggest the conversion MAF -> HAL -> VG, which you should be able to accomplish with `maf2hal` from:
https://github.com/ComparativeGenomicsToolkit/hal
And `hal2vg` from:
https://github.com/ComparativeGenomicsToolkit/hal2vg
