### ISSUE TITLE
Surject producing BAM with invalid flags

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#2123]
@ekg @jeizenga @glennhickey 
Running VG Surject using the version of VG contained in docker container `quay.io/vgteam/vg:v1.14.0`
produces some alignments of reads where the paired read has malformed SAM flags.

The following are example read pairs that Picards `ValidateSamFile` found containing `INVALID_FLAG_MATE_UNMAPPED` errors. For example, according to [this site](https://www.samformat.info/sam-format-flag) which interprets proper SAM flag values for read pairs, a read with sam flag 81 should be paired with a mate containing sam flag 161. But in the Surjected BAM a read with flag 81 is paired with a read with flag 133. All 3 examples have flags saying that their mate should be mapped, but the mates flag says that it is unmapped. 

```
HISEQ1:22:H9UJNADXX:1:1112:1098:65889   81      21      9411959 59      148M    *       0       0       TCATGCTTGCTGATTTGTCTGTTTGTTGAGAGGAGAATGTTCAGAATTTTATATCTTCAACATCTTTTTCTTCATTAATAAGATACTGAGATTTTATAACTCTTGTCATTTTGGTCCCTTATATTTTCATATGGAAATATCGTATAAT   @>A8<99AA>BA:<?<<?38288@?AAA:BAA;;BBBBBAA;DBAA5AA@5A>A;;@:A>?DB?FE>AFIIIIIIIGIF@FEFCFBGFEFF?CFFBFGGGB?<FFEBGEEBFGEC<+?HHCHCEBC:<IEIFIFIFFFFFDDDDD@@@
HISEQ1:22:H9UJNADXX:1:1112:1098:65889   133     *       0       0       *       21      9411959 0       NNNNNNNNNNNNNNNNNNANNNTNNTNCTNNNNNNNNNNGGNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNNANNNNNNNNNNNNNNTNANNNNNNNNNNNNNNNNNT   ##################3###2##1#1:##########00#.#################################+###########################+#######+##############+#+#################(
```
```
HISEQ1:22:H9UJNADXX:1:1206:1227:79798   65      21      9412118 21      148M    *       0       0       AATATATTTGTGTAAAATTAAGAAAATTATCTTATCTAATAACTTGATCAATATCTGTGATTATATTTTCATTGCCTTCCAATTTTAATATTTGTTCTCTATTCCTTCTTAATCTGGATTGAAGTTCTGATTAATTATTTTAATGTTG   @@@DADDDHFDDFG?G@H9FIHG>AFFH?BHDHDAHGGE@FHI@DBGIIBGCGHDHGDGEGGIGAFEHIGIIIICIIIGDHIIIIIIGHECEHHCHEDDEE?B@CCCCCCC@CCC>:>>C?C>CCCCCC@ACC>CDDDDDCDCCC>A:
HISEQ1:22:H9UJNADXX:1:1206:1227:79798   133     *       0       0       *       21      9412118 0       NGGNAANNNNNNNNNNNNNGNNNNNNANNNNNNNCANGNNNNNNANNNNNNNNNNNNNNNNGNNNNNNNNNNNNTTNANNNNNNNNNNNNGTNNNNANNANNTNNNNNNANNNNANANNNNNNANNNATTNNNNNNNNNNNNNNNTNT   #0(#--#############-######1#######00#0######-################,############,+#+############(+####+##(##+######(####+#(######+###++2###############(#+
```
```
HISEQ1:23:H9UD5ADXX:2:2207:1096:57593   65      21      9415036 7       148M    *       0       0       CCCCCTTAAAAATAATTTTTAATGTACTAGATTTATAAATAGAACAACAAGATTTCTAATTTAAACTCAAAAATTTGTTAAATTGGTTAACAATTTAACATAATATGCTGCACATTAATTCAGAATATGAAATCTTATATGTAGTCCT   <@@DDDDDFFFF?GEA<<I4FFDAFEFEFHCDFGEE@?CEDCG@DDEDBF??D?FE*?DF8?9=.88=BFF>F@@E)=7?>??==:7?BBBCAB3AAD@BBAB>A@35@::>@>BA>>@5:>:>BB>4:@DB::A:@BB@3+:>:@@@
HISEQ1:23:H9UD5ADXX:2:2207:1096:57593   133     *       0       0       *       21      9415036 0       NNNNNNNNNNANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN   ##########2#########################################################################################################################################
```

**Comment by glennhickey** [comment]
#2127 should fix this by adding the mate unmapped and mate reversed flags.  
`samtools fixmate`, if you're not already using, may be a more expedient way to fix your surject output while you wait for vg to get all the flags right.

**Comment by cmarkello** [comment]
@glennhickey @ekg @jeizenga 
After attempting to fix the problems with `samtools fixmate`, it looks like the SAM flags of the mates have been fixed. Now I'm running into `INVALID_INDEXING_BIN` errors.

```
## HISTOGRAM    java.lang.String
Error Type      Count
ERROR:INVALID_INDEXING_BIN      606
ERROR:MISSING_READ_GROUP        1
WARNING:MISSING_TAG_NM  10486980
WARNING:RECORD_MISSING_READ_GROUP       10487586
```

The error is defined as "Indexing bin set on SAMRecord does not agree with computed value" and I'm not exactly sure what that means. Is it an issue with the BAM indexer? What is an indexing bin? And what is computed value? I used `samtools index -b` for that (and have also tried `samtools index -c` to build a .csi index).

When I attempt to add read groups via `picard AddOrReplaceReadGroups` in order to satisfy the requirement of GATK's HaplotypeCaller the same error comes up for the first specific read 
```
SAM validation error: ERROR: Record 918, Read name D00360:95:H2YWMBCXX:1:1103:1070:69140, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned.
```
The specific SAM record for that read ID is the following pair:
```
D00360:95:H2YWMBCXX:1:1103:1070:69140   165     1       143373476       0       *       =       143373476       0       ACAGCAAGATATNTCAAGGTCACTANCATAGCACATGTGTANNNNNNNNNNNNNNNNNNNCATNNNNCNNANNNNCNNNNAN        DADDDIIIHIII#<DGHHIIIIIII#<<EGHCHIHIIIIII###################<<<####<##<####<####<#      MQ:i:0
D00360:95:H2YWMBCXX:1:1103:1070:69140   89      1       143373476       0       250M    =       143373476       0       ATTATGTGTCAAAGTAGACTAGTCCTGCTATCTAAACAATGGTTCGGAGAATGNTCTCATAATATTTGTTCATTAATCAACCTAAGTCTCACTCTCAGTCTTCCAAGTGGCATATGAGCTGGGAAACTAATTCAGTCATATACCATGTGACCTTCTGAACCAGATCAACATAAAGAAATTGCTAAAGAAATAAGCTTTAGATTCTAGATTCTTTTTACTATAGTCATTTAGAGATGAATTACATTTATTT  -D@CGEEFFD:..HIHCHEEGHHHHEGIHHHHG</HHFHHDHHCIIHHFGD<<#CHC?EIHHEIIHHEHGIHGF1@1HCFCF1HEF1HGHGCHHHEHIIIIHEHHH?EIIHEIHGIIIHHCFIIGIIHIIIIIIIHGIIIIIHHGHHGCHHHIGHIIIIHHIIIHIIIHGIIHIIHIIHHIHIIIIGHIIHIIHIHIIIIIIIIIIIIIIIIIHGIHHGIIIIHGHIHHHEHGIIHIHHIIHIIHDDDDD
```

**Comment by cmarkello** [comment]
After looking at that record in the BAM file prior to `fixmate` it looks like the following:
```
D00360:95:H2YWMBCXX:1:1103:1070:69140   83      1       143373476       0       250M    *       0       0       ATTATGTGTCAAAGTAGACTAGTCCTGCTATCTAAACAATGGTTCGGAGAATGNTCTCATAATATTTGTTCATTAATCAACCTAAGTCTCACTCTCAGTCTTCCAAGTGGCATATGAGCTGGGAAACTAATTCAGTCATATACCATGTGACCTTCTGAACCAGATCAACATAAAGAAATTGCTAAAGAAATAAGCTTTAGATTCTAGATTCTTTTTACTATAGTCATTTAGAGATGAATTACATTTATTT  -D@CGEEFFD:..HIHCHEEGHHHHEGIHHHHG</HHFHHDHHCIIHHFGD<<#CHC?EIHHEIIHHEHGIHGF1@1HCFCF1HEF1HGHGCHHHEHIIIIHEHHH?EIIHEIHGIIIHHCFIIGIIHIIIIIIIHGIIIIIHHGHHGCHHHIGHIIIIHHIIIHIIIHGIIHIIHIIHHIHIIIIGHIIHIIHIHIIIIIIIIIIIIIIIIIHGIHHGIIIIHGHIHHHEHGIIHIHHIIHIIHDDDDD
D00360:95:H2YWMBCXX:1:1103:1070:69140   133     *       0       0       *       1       143373476       0       ACAGCAAGATATNTCAAGGTCACTANCATAGCACATGTGTANNNNNNNNNNNNNNNNNNNCATNNNNCNNANNNNCNNNNAN        DADDDIIIHIII#<DGHHIIIIIII#<<EGHCHIHIIIIII###################<<<####<##<####<####<#
```
It seems that `samtools fixmate` is correcting the unmapped mate read as unmapped, but it's giving it a mapped position which shouldn't exist since it's unmapped. I think it's tripping the SAM Validator in that it's expecting the unmapped mate to not have a mapped coordinate.

**Comment by glennhickey** [comment]
From section 2.4.1 of the [samtools spec](https://samtools.github.io/hts-specs/SAMv1.pdf),  

> For a unmapped paired-end or mate-pair read whose mate is mapped, the unmapped read should have RNAME and POS identical to its mate.

If there's something in surject that's breaking picard, I'd be surprised that fixmate enforcing this convention is it.

**Comment by cmarkello** [comment]
For now it seems that using `samtools addreplacerg` instead of picards `AddOrReplaceReadGroups` ignores the `INVALID_INDEXING_BIN` error and produces a BAM that appears to work with GATKs HaplotypeCaller. I'm only getting an empty VCF from that, but I'm attempting to run a larger BAM to see if HaplotypeCaller was running into an error that it was ignoring.

**Comment by adamnovak** [comment]
BAM assigns each read to a "bin" in the index based on the reference interval it covers. In section 4.2 of the SAM/BAM spec at https://samtools.github.io/hts-specs/SAMv1.pdf you can see that BAM reads are supposed to have a "bin" field in them, set to the correct bin for the read given its alignment. If someone changed the read's alignment without recomputing the bin, or if vg didn't compute the correct bin for the read's alignment at the start, then that bin field will be wring and validators may complain. In particular, unmapped reads with POS 0 will get a different bin than unmapped reads with POS set to their mate's POS.

Round-tripping through SAM should fix the bins, as SAM doesn't have a bin field, just the alignment.

**Comment by cmarkello** [comment]
What's "Round-tripping". You mean convert the BAM to SAM and then convert that SAM back to BAM before indexing the BAM?

**Comment by adamnovak** [comment]
Yeah, that's what I mean.

**Comment by glennhickey** [comment]
Seems pretty harsh of Picard to enforce that if there's (presumably) no .bai present.  I'd expect indexing the fixmate output to also fix the bins.

**Comment by adamnovak** [comment]
I don't think indexing the BAM is supposed to modify the BAM. But I
don't know why you don't just leave computing the bin to the indexer.
Maybe it makes the indexer faster to not do that.

**Comment by glennhickey** [comment]
Sheesh, you're right.  `fixmate` shouldn't output BAM, I guess.  What's the point of it changing the position if you can't query it after?

**Comment by cmarkello** [comment]
Ok so the good news is that fix appears to work with HaplotypeCaller.

For note, my inefficient workaround for processing BAM files sourced from `VG Surject` using the VG container `quay.io/vgteam/vg:v1.11.0-215-ge5edc43e-t246-run` to become compatible with GATK is the following:

VG Surjected BAM input titled "HG002_merged.sorted.bam" in this example
##### Sort by readname for `samtools fixmate` compatibility
```
samtools sort \
  -n -O BAM \
  HG002_merged.sorted.bam \
  -o HG002_merged.namesorted.bam
```
##### Fix bad mate pair flags
```
samtools fixmate \
  HG002_merged.namesorted.bam \
  -O BAM \
  HG002_merged.namesorted.fixmate.bam
```
##### Sort fixed reads by position for `samtools addreplacerg` compatibility
```
samtools sort \
  HG002_merged.namesorted.fixmate.bam \
  -O BAM \
  -o HG002_merged.fixmate.positionsorted.bam
```
##### Add readgroup tags to reads for GATK compatibility
```
samtools addreplacerg \
  -r ID:1 -r LB:lib1 -r SM:HG002 -r PL:illumina -r PU:unit1 \
  -O BAM \
  -o HG002_merged.fixmate.positionsorted.rg.bam \
  HG002_merged.fixmate.positionsorted.bam
```
##### Convert BAM to SAM and back to BAM to fill in indexing bin information for fixed mate read position changes
```
samtools view \
  -h -O SAM \
  HG002_merged.fixmate.positionsorted.rg.bam \
  -o HG002_merged.fixmate.positionsorted.rg.sam
samtools view \
  -O BAM \
  HG002_merged.fixmate.positionsorted.rg.sam \
  -o HG002_merged.fixmate.positionsorted.rg.round_tripped.bam
samtools index \
  -b HG002_merged.fixmate.positionsorted.rg.round_tripped.bam
```

**Comment by glennhickey** [comment]
With the fixes currently in master, going through SAM after `fixmate` should no longer be necessary.  So by my count, that leaves the following changes needed in vg surject to avoid `fixmate` and `addreplacerg` entirely:

- [ ] Output TLEN column (distance between reads) 
- [ ] Use bwa's definition of the PROPER PAIR flag
- [ ] CLI option in surject to set the read group information

**Comment by ekg** [comment]
The BAMs headers produced by vg surject / vg map --surject-to are not ordered the same as the FASTA the reference is generated from. Has this been resolved recently? If not, we may need to annotate paths with ranks / ids in addition to names.

**Comment by glennhickey** [comment]
@ekg Don't think fasta ordering (#2069) has come up with @cmarkello's GATK work yet, nor has hit been resolved.  Out of curiosity, which tools is it affecting?

**Comment by adamnovak** [comment]
I'm going to make an attempt at the RG tagging now, if nobody is doing that already.
