### ISSUE TITLE
Issue with vg construct, lowercase

### ISSUE THREAD

**Issue by cademirch** [vgteam/vg#2130]
Hello, 
I am trying to construct a graph using Drosophila data, however I am running into an issue using vg construct. The error message:
```
warning:[vg::Constructor] Lowercase characters found in NW_007931121.1; coercing to uppercase.
```
Is written many times to my .err file. However it appears that vg finishes. But, the few test graphs I have made seem to be far too small considering the size of my input VCF. 

Thanks.

**Comment by ekg** [comment]
You mean that the size of the reference plus alternate alleles in the VCF
is smaller than the sequences in the final graph?

**Comment by cademirch** [comment]
The opposite actually. If I remember correctly the VCF was 200-300Gb while the graph was ~400Mb. Is the .vg file compressed? Also, any advice on the lowercase warning? Or is that normal? 

Thanks.

**Comment by ekg** [comment]
The vg file is compressed and the VCF contains much more than just
alternate sequences. Please check that the sun of lengths of the alternate
alleles plus the reference length equals the sum of sequence lengths in the
final graph.

**Comment by glennhickey** [comment]
The lowercase warning is indeed normal.  The vg indexes don't distinguish between lower and upper case bases to save space, so the constructor will just convert everything in your fasta file to uppercase. 

You can use `vg stats -l` to check the amount of sequence in the graph as @ekg suggested.  You can also use `vg paths -L -v` to see the different fasta sequences present in your graph, as well as their lengths.

**Comment by cademirch** [comment]
Okay great. Thanks for the help!
