### ISSUE TITLE
Read mapping / BAM output not accounting for overlapping nodes?

### ISSUE THREAD

**Issue by alancleary** [vgteam/vg#2145]
I've used my own pipeline to construct a vg file representing a k=100 compressed de Bruijn graph (nodes of length >= 100 and all neighbors overlap by 99) for a highly conserved ~600kb region in three accessions. I then used vg to chop the nodes to length 32 and map ~9 million paired-end reads from a fourth accession with ~95% sequence identity. Finally, I filtered the output GAM using the example parameters in the vg repo's readme and output the alignments as a BAM file relative to a single path.

What I expected was for several thousand reads to be mapped well to the graph and for the length of the sequence of the path designated as the reference when generating the BAM to be as long we know it to be, ~650kb. What we experienced instead is only ~300 mapped reads made it through the filter and the output BAM thinks the reference path's sequence is ~1.6Mb. The ~300 mapped reads are not limited to the real ~650kb extent, but rather distributed across the faux ~1.6Mb region. Furthermore, the reads that made it through the filter tend to have gaps in their alignments and aren't aligned well at all to the reference as described by the BAM (example below).

![screen shot 2019-02-28 at 10 42 51 am](https://user-images.githubusercontent.com/836063/53753870-95fa1f80-3e6f-11e9-951f-7a0d7f85cd19.png)

I wrote a program that outputs two version of the sequence of a path in a vg graph: one that accounts for overlapping nodes and one that does not. When I ran it on the path designated as the reference for the BAM I found that the sequence that accounts for overlaps was exactly the same as the input sequence, whereas the sequence that does not account for overlaps was ~1.6Mb. So I suspect that the vg BAM output is not accounting for overlapping nodes. Also, based on the alignment above, I suspect the map operator is not accounting for overlaps either. Is this the case or have I missed a crucial vg parameter?

**Comment by ekg** [comment]
The only algorithm in VG that handles node overlaps is the "pinchgraph"
reduction of them into a blunt ended graph. This happens on import from
GFA. VG is not designed to work with these.

If you have a problem scaling this reduction then it might make sense to
teach seqwish to run this reduction. It also produces base precise graphs.

**Comment by alancleary** [comment]
Thanks for the response, @ekg. That's not the answer I was hoping for but it certainly helps. I was unaware of seqwish. Will definitely check it out!
