### ISSUE TITLE
Can anyone please explain what is a meaning of Node with the dot in the variation graph? Please see node 48 in the file (attached)

### ISSUE THREAD

**Issue by ziaursani** [vgteam/vg#2148]
Please describe:

1. What you were trying to do
2. What you wanted to happen
3. What actually happened
4. What data and command line to use to make the problem recur, if applicable

```
Format code blocks or terminal copy-pastes like this, between triple backticks.
```

**Comment by ziaursani** [comment]
Node with the dot in the variation graph

**Comment by ziaursani** [comment]
![node_with_the_dot](https://user-images.githubusercontent.com/37387689/53973206-3d898300-40f8-11e9-9081-32ece91e03af.png)

**Comment by ekg** [comment]
How did you build this? It's an empty node. Consider it a deletion. I think
there is a function accessible from VG mod that removes nodes like this and
links their inbound and outbound neighbors together.

**Comment by ziaursani** [comment]
This dot is in vcf file in ALT field at base positions 4305 and 6522. I have attached the vcf file. Can you please explain what it means?
[NCYC78_97_430_672_1406_1415_2517_2855_3493_3630_umt.zip]. (https://github.com/vgteam/vg/files/2942871/NCYC78_97_430_672_1406_1415_2517_2855_3493_3630_umt.zip)

**Comment by ekg** [comment]
Oh! sorry, it's not an empty node. vg is taking the string directly from the VCF file. I can only assume that the generated graph would be correct if these nodes were removed and their inbound and outbound connections were linked.

I can't reproduce this without your reference file `S288c_rDNA_cracker_fixed.fasta`

**Comment by ekg** [comment]
... but I'll make a test case with another VCF file that we already have.

**Comment by ekg** [comment]
```
# our inputs
-> % cat tiny.fa
>x
CAAATAAGGCTTGGAAATTTTCTGGAGTTCTATTATATTCCAACTCTCTG
-> % cat y.vcf
##fileformat=VCFv4.1
##fileDate=20141110
##source=mutatrix population genome simulator
##seed=1415643582
##reference=x.fa
##phasing=true
##commandline=mutatrix --dry-run -s 0.05 -i 0.01 -p 2 x.fa
##INFO=<ID=AC,Number=A,Type=Integer,Description="Alternate allele count">
##INFO=<ID=TYPE,Number=A,Type=String,Description="Type of each allele (snp, ins, del, mnp, complex)">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples at the site">
##INFO=<ID=NA,Number=1,Type=Integer,Description="Number of alternate alleles">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="Length of each alternate allele">
##INFO=<ID=MICROSAT,Number=0,Type=Flag,Description="Generated at a sequence repeat loci">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1
x       9       .       G       A       99      .       AC=1;LEN=1;NA=1;NS=1;TYPE=snp   GT      1|0
x       10      .       C       T       99      .       AC=2;LEN=1;NA=1;NS=1;TYPE=snp   GT      1|1
x       14      .       G       .       99      .       AC=1;LEN=1;NA=1;NS=1;TYPE=snp   GT      1|0
x       34      .       T       A       99      .       AC=2;LEN=1;NA=1;NS=1;TYPE=snp   GT      1|1
x       39      .       T       A       99      .       AC=1;LEN=1;NA=1;NS=1;TYPE=snp   GT      1|0
# build and view the graph
-> % vg construct -r tiny.fa -v y.vcf| vg view -dp - | dot -Tpng -o y.png
```

![y](https://user-images.githubusercontent.com/145425/54020261-42484880-4185-11e9-9897-71c5caad3d55.png)

This is the same test, but with the correct reference base at the same position:

![tiny](https://user-images.githubusercontent.com/145425/54020293-50966480-4185-11e9-99f9-2d891efabfe7.png)

It looks to me that this isn't really doing what's intended, *if* the "." is meant to represent a deletion.

I think it's best to fix your VCF file so that it always includes sequence in both the reference and alternate records. Then the VCF related functionality in vg will work as expected, and the graphs will have the right structure.

**Comment by ziaursani** [comment]
The vcf file I have created through vgs as follows
vg construct -r S288c_rDNA_cracker_fixed.fasta > S288c_rDNA_cracker_fixed.vg
vg index -x S288c_rDNA_cracker_fixed.xg -g S288c_rDNA_cracker_fixed.gcsa S288c_rDNA_cracker_fixed.vg
vg map -f NCYC78_forward_paired.fastq -f NCYC78_reverse_paired.fastq -g S288c_rDNA_cracker_fixed.gcsa -x S288c_rDNA_cracker_fixed.xg > NCYC78_paired.gam
vg augment -a pileup -Z samp.trans -S samp.support S288c_rDNA_cracker_fixed.vg NCYC78_paired.gam > NCYC78_paired.vg
vg call -z samp.trans -s samp.support NCYC78_paired.vg > NCYC78_paired.vcf

I have attached fasta file and vcf file. I cannot attach read files NCYC78_forward_paired.fastq and NCYC78_reverse_paired.fastq because they are too big. You can see in the attached vcf file the ALT values in the bases 9527 and 9528 are just a dot.  What I am doing wrong? and how can I fix this?

[svg.zip](https://github.com/vgteam/vg/files/2945930/svg.zip)

**Comment by ekg** [comment]
You need to use a variant caller that doesn't produced "." in the ALT field.

**Comment by adamnovak** [comment]
We might want to consider throwing an error during construction. We can't handle "." alts, so we shouldn't just pass them through when they appear.

**Comment by ekg** [comment]
That's right. We are being pretty strict about DNA elsewhere. We might as
well be clear that this is a problem.

Non-DNA graphs are interesting, but add complexity to handle as well.

**Comment by jodicks** [comment]
Thanks Erik and Adam for working through this issue with Zia. You may remember you've previously helped Prithika with her work on constructing variation graphs for whole yeast genomes, which has been really helpful. In Zia's project we're looking specifically at repetitive genomic regions, so quite small graphs, which we can look at in detail. Ideally, we'd like to use a "pure" vg pipeline where we iteratively call variants against a vg (initially a flat vg) and then fold them in. While the "." variants in the ALT fields are more common in these repetitive regions, we would expect to see them in all of our whole genome datasets (not just yeast, but all eukaryotes and possibly prokaryotes too). So calling an error on such an eventuality would occur for most datasets where variants called within vg were then folded back into it. For the time being, we're considering "fixing" the vg-called vcf files but it would be preferable that the "." alleles weren't called at all. I think they aren't in bwa, for example. But using bwa to construct our vcfs wouldn't bring benefits such as alleviating reference allele bias, so we don't want to do that. Zia is currently writing a short document on the issues he has seen in his project so far, which I think could be helpful going forward.

**Comment by adamnovak** [comment]
Hold on, is *vg* generating VCFs with a `.` for an `ALT`? I don't think that should be happening. If so, we should fix that in the vg caller.

**Comment by ziaursani** [comment]
You can read my earlier comment. I have listed vg commands through which I have produced vcf. I have also attached the VCF file there.

**Comment by jodicks** [comment]
Yes, that's exactly it. A fix would be gratefully received. The most frequent cause of this - not exclusively though I think - is homopolymeric tracts (i.e. runs of the same base). We often see these in our repetitive regions within yeast genomes, and there can be different numbers of the base in different repeat copies (e.g. 12 T's at locus 1, 13 T's at locus 2, 9 Ts at locus 3). There's an example of such a repeat beginning on line 49 of Zia's vcf file, spilling across the next few lines.

**Comment by glennhickey** [comment]
We indeed should fix vg call to not output these variants.  In the meantime, you can filter them out of your VCF.  They are non-calls and should be ignored.

```
bcftools view NCYC78_paired.vcf -e 'ALT="." || GT="0" || GT="0/0"'
```

**Comment by adamnovak** [comment]
OK, it looks like we call "." as an alt in conjunction with "0" as a genotype. This is at least sensible, but we shouldn't do this *unless* the user asks for trivial calls to be reported, right? Or do we want to consider this a non-trivial call because it is asserting haploid-ness on part of the reference (which is maybe nested inside a bigger variant).

If we want to count this as trivial we need to touch [here](https://github.com/vgteam/vg/blob/a72723d381b1241a5e2b56ef777de2cdc2fa947f/src/support_caller.cpp#L2039-L2040). We also want to skip these alts at the construct step.
