### ISSUE TITLE
Broken hgvm link in documentation

### ISSUE THREAD

**Issue by pesho-ivanov** [vgteam/vg#2150]
The [documentation](https://github.com/vgteam/vg/wiki/Long-read-assemblies-using-vg-msga) seems to refer to a [broken link](http://hgwdev.sdsc.edu/~anovak/hgvm/) (by @adamnovak). My guess is that it should be changed to a [new link](http://public.gi.ucsc.edu/~anovak/hgvm/).

**Comment by adamnovak** [comment]
Good catch; we moved all our servers around and didn't fix the documentation. It should be a working link now.
