### ISSUE TITLE
More details on refpos field and mapping parameters

### ISSUE THREAD

**Issue by kevsilva** [vgteam/vg#2167]
Hello,

As mentioned in a previous issue, I created a graph from E. coli O104 and IAI39 and mapped reads generated from O104 without errors. However while I was trying to get back the paths where reads mapped on my own, I realized it was inconsistent with the info given by refpos.

Here is an example for a certain read:
`{"sequence":"GTGTTGTTACTCGTAAGTTTCGCAGCTTATTAACAGCCAATCAGAGGGGGGAGAAATCCTCCCTCACCCTTGTTCCTTTACTTTAGGTTGAAAAAAAATCAGCGTCAAGAAGGTTTCATTAACACATATCCCTGGCCCAAAAAGCCGGGGATTTTTTATATCTGCGTTCCGCTAAAAGGTGCAAATGCTCAGGACGTTGC","path":{"mapping":[{"position":{"node_id":"348232","offset":"2","is_reverse":true},"edit":[{"from_length":11,"to_length":11}],"rank":"1"},{"position":{"node_id":"348230","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"2"},{"position":{"node_id":"348229","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"3"},{"position":{"node_id":"324634","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"4"},{"position":{"node_id":"324632","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"5"},{"position":{"node_id":"324631","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"6"},{"position":{"node_id":"324629","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"7"},{"position":{"node_id":"324628","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"8"},{"position":{"node_id":"324626","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"9"},{"position":{"node_id":"324625","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"10"},{"position":{"node_id":"324623","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"11"},{"position":{"node_id":"324622","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"12"},{"position":{"node_id":"324620","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"13"},{"position":{"node_id":"324619","is_reverse":true},"edit":[{"from_length":15,"to_length":15}],"rank":"14"},{"position":{"node_id":"324618","is_reverse":true},"edit":[{"from_length":10,"to_length":10}],"rank":"15"},{"position":{"node_id":"324616","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"16"},{"position":{"node_id":"324615","is_reverse":true},"edit":[{"from_length":21,"to_length":21}],"rank":"17"},{"position":{"node_id":"324614","is_reverse":true},"edit":[{"from_length":3,"to_length":3}],"rank":"18"},{"position":{"node_id":"324613","is_reverse":true},"edit":[{"from_length":29,"to_length":29}],"rank":"19"},{"position":{"node_id":"324612","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"20"},{"position":{"node_id":"324611","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"21"},{"position":{"node_id":"324610","is_reverse":true},"edit":[{"from_length":18,"to_length":18}],"rank":"22"}]},"mapping_quality":60,"score":210,"identity":1,"refpos":[{"offset":"297721","name":"genomes/ecoli_IAI39_UTI_contig3"},{"offset":"759152","is_reverse":true,"name":"genomes/ecoli_O104_HUS_contig1"}],"time_used":3675}
`
According to this json output, this read can be found in O104 and IAI39 (which is indeed the case). There are two issues with this result: I can't understand how this information is retrieved, at first I thought it was by looking at the nodes, if the nodes were a sub-list of the nodes composing a path, but for example the node "324632" is never crossed by the path O104, see the attached file for a visualization of the graph. [aln1.zip](https://github.com/vgteam/vg/files/2971787/aln1.zip) So then I thought that maybe it was just by looking at the position of the read in the raw sequence of each path, hence the offset given. Indeed this read is at the position 297721 on IAI39, but it is at the position 759457 in O104 and not 759152.
So this is the first part of my issue, could you explain a little more this output?

The second part of my issue is that, considering those results, I should then be expecting at least 2 perfect alignments (in fact I think I am a little bit in the same situation as my previous issue with duplicate regions on the graph but I leave this for the other post): one for IAI39 (which should be exactly as the output above) and one for O104.
Initially my code was:
`vg map -D -s 'GTGTTGTTACTCGTAAGTTTCGCAGCTTATTAACAGCCAATCAGAGGGGGGAGAAATCCTCCCTCACCCTTGTTCCTTTACTTTAGGTTGAAAAAAAATCAGCGTCAAGAAGGTTTCATTAACACATATCCCTGGCCCAAAAAGCCGGGGATTTTTTATATCTGCGTTCCGCTAAAAGGTGCAAATGCTCAGGACGTTGC' -x mygraph.xg -g mygraph.gcsa -M 100 -j > test.json`
I finally found the two alignments I was expecting by playing with the `-w` parameter:
`vg map -D -s 'GTGTTGTTACTCGTAAGTTTCGCAGCTTATTAACAGCCAATCAGAGGGGGGAGAAATCCTCCCTCACCCTTGTTCCTTTACTTTAGGTTGAAAAAAAATCAGCGTCAAGAAGGTTTCATTAACACATATCCCTGGCCCAAAAAGCCGGGGATTTTTTATATCTGCGTTCCGCTAAAAGGTGCAAATGCTCAGGACGTTGC' -x O104contigs_IAI39contigs_a.xg -g O104contigs_IAI39contigs_a.gcsa -M 100 -j -w 100 > test.json`
And the output:
```
{"sequence":"GTGTTGTTACTCGTAAGTTTCGCAGCTTATTAACAGCCAATCAGAGGGGGGAGAAATCCTCCCTCACCCTTGTTCCTTTACTTTAGGTTGAAAAAAAATCAGCGTCAAGAAGGTTTCATTAACACATATCCCTGGCCCAAAAAGCCGGGGATTTTTTATATCTGCGTTCCGCTAAAAGGTGCAAATGCTCAGGACGTTGC","path":{"mapping":[{"position":{"node_id":"348232","offset":"2","is_reverse":true},"edit":[{"from_length":11,"to_length":11}],"rank":"1"},{"position":{"node_id":"348230","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"2"},{"position":{"node_id":"348229","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"3"},{"position":{"node_id":"324634","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"4"},{"position":{"node_id":"324632","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"5"},{"position":{"node_id":"324631","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"6"},{"position":{"node_id":"324629","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"7"},{"position":{"node_id":"324628","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"8"},{"position":{"node_id":"324626","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"9"},{"position":{"node_id":"324625","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"10"},{"position":{"node_id":"324623","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"11"},{"position":{"node_id":"324622","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"12"},{"position":{"node_id":"324620","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"13"},{"position":{"node_id":"324619","is_reverse":true},"edit":[{"from_length":15,"to_length":15}],"rank":"14"},{"position":{"node_id":"324618","is_reverse":true},"edit":[{"from_length":10,"to_length":10}],"rank":"15"},{"position":{"node_id":"324616","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"16"},{"position":{"node_id":"324615","is_reverse":true},"edit":[{"from_length":21,"to_length":21}],"rank":"17"},{"position":{"node_id":"324614","is_reverse":true},"edit":[{"from_length":3,"to_length":3}],"rank":"18"},{"position":{"node_id":"324613","is_reverse":true},"edit":[{"from_length":29,"to_length":29}],"rank":"19"},{"position":{"node_id":"324612","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"20"},{"position":{"node_id":"324611","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"21"},{"position":{"node_id":"324610","is_reverse":true},"edit":[{"from_length":18,"to_length":18}],"rank":"22"}]},"mapping_quality":60,"score":210,"identity":1,"secondary_score":[-349169],"time_used":15115}
{"sequence":"GTGTTGTTACTCGTAAGTTTCGCAGCTTATTAACAGCCAATCAGAGGGGGGAGAAATCCTCCCTCACCCTTGTTCCTTTACTTTAGGTTGAAAAAAAATCAGCGTCAAGAAGGTTTCATTAACACATATCCCTGGCCCAAAAAGCCGGGGATTTTTTATATCTGCGTTCCGCTAAAAGGTGCAAATGCTCAGGACGTTGC","path":{"mapping":[{"position":{"node_id":"348232","offset":"2","is_reverse":true},"edit":[{"from_length":11,"to_length":11}],"rank":"1"},{"position":{"node_id":"348230","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"2"},{"position":{"node_id":"348229","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"3"},{"position":{"node_id":"324634","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"4"},{"position":{"node_id":"324632","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"5"},{"position":{"node_id":"324631","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"6"},{"position":{"node_id":"324629","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"7"},{"position":{"node_id":"324628","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"8"},{"position":{"node_id":"324626","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"9"},{"position":{"node_id":"324625","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"10"},{"position":{"node_id":"324623","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"11"},{"position":{"node_id":"324622","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"12"},{"position":{"node_id":"324620","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"13"},{"position":{"node_id":"324619","is_reverse":true},"edit":[{"from_length":15,"to_length":15}],"rank":"14"},{"position":{"node_id":"324618","is_reverse":true},"edit":[{"from_length":10,"to_length":10}],"rank":"15"},{"position":{"node_id":"324616","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"16"},{"position":{"node_id":"324615","is_reverse":true},"edit":[{"from_length":21,"to_length":21}],"rank":"17"},{"position":{"node_id":"324614","is_reverse":true},"edit":[{"from_length":3,"to_length":3}],"rank":"18"},{"position":{"node_id":"324613","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"19"},{"position":{"node_id":"348651","offset":"20","is_reverse":true},"edit":[{"from_length":7,"to_length":7}],"rank":"20"},{"position":{"node_id":"348650","is_reverse":true},"edit":[{"from_length":27,"to_length":27}],"rank":"21"},{"position":{"node_id":"348302","is_reverse":true},"edit":[{"from_length":8,"to_length":8}],"rank":"22"},{"position":{"node_id":"348301","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"23"},{"position":{"node_id":"348299","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"24"},{"position":{"node_id":"348298","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"25"},{"position":{"node_id":"348297","is_reverse":true},"edit":[{"from_length":3,"to_length":3}],"rank":"26"},{"position":{"node_id":"348294","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"27"},{"position":{"node_id":"348293","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"28"},{"position":{"node_id":"348292","is_reverse":true},"edit":[{"from_length":8,"to_length":8}],"rank":"29"},{"position":{"node_id":"348291","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"30"},{"position":{"node_id":"348289","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"31"},{"position":{"node_id":"348286","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"32"},{"position":{"node_id":"348284","is_reverse":true},"edit":[{"from_length":5,"to_length":5}],"rank":"33"}]},"score":-349169,"is_secondary":true,"identity":1}
```
This time the issue is that I do not have refpos field and also I can't understand this huge negative score for the second alignment while the nodes and position are right, this is a perfect matching, it should then be 210. Even the identity score is correctly 1.
Again further explanations about refpos and also -w (it is supposed to be a parameter for long read alignment, so why playing with it gives me the expected output whereas I use 200bp reads) would be appreciated.

Thank you.

**Comment by adamnovak** [comment]
The `refpos` field annotates the alignment with, for each path that the alignment is touching, the position along that path at which the alignment occurs. It doesn't mean that the read aligns perfectly to the path, or that *all* the nodes that the alignment visits occur on the path (just some of them).

In the case of the read you posted, it looks like it aligns to some part of the graph where path `genomes/ecoli_IAI39_UTI_contig3` runs through it in one orientation, and `genomes/ecoli_O104_HUS_contig1` runs through it in the other orientation. In this graph region, some of the nodes are shared between those paths, and some of the nodes are part of one path but not the other (i.e. there are SNP or other differences between the two reference sequences). The read takes some path through this graph region, including taking some specific versions of the variable regions (in the case of node 324632, it takes the version of that C/G mismatch that agrees with IAI39 and not with O104). The read might clearly be much more in agreement with one of those paths than the other, or it might be more or less evenly split in how many matches/mismatches it has against each, but it is still going to be assigned `refpos` annotations on both paths, giving the effective path coordinate of the part of the *graph* that the read is aligned to. Also, since, looking at the graph, it looks like these paths visit this graph region multiple times, you're going to get the coordinate of each path's *first* visit to the region; it doesn't look to see which visit of the path to the region agrees most closely with the read sequence or anything. That should account for the perfect match on O104 at 759457; there should be a similar sequence at 759152, which is represented by the same region of the graph with some different settings for the variable regions, and which has a lower path coordinate and so was used in the refpos annotation.

`vg map` shouldn't be expected to give you two alignments here; this is all one alignment to the graph, which has two (or more) possible path coordinates depending on which path you are measuring along and which occurrence of the region on the path you choose. I think that by bringing the band width way down with `-w`, you managed to get the long read alignment code to kick in on this short read. I think the algorithm is that if the read is much longer than `-w`, it chops it up into `-w` sized chunks, aligns each chunk, and then tries to stitch the results together into something coherent.

Your primary and secondary mappings that you get out with `-w 100` *don't* represent mappings to different paths; they're two alternative ways of mapping the read to this one region of the graph. The giant negative score on the secondary alignment might be a bug in the long read alignment code, or it might be that that secondary mapping is actually properly scored and just very bad. It looks to assert a jump directly from node 324613 reverse to node 348651 reverse; it might be that the shortest path between those nodes requires taking a gap that scores about -349169 points. Note that identity for the alignment is only calculated based on matches and mismatches; it ignores indels altogether.

The long read alignment code doesn't set refpos automatically; you can pipe the GAM output (from `vg map` without `-j`) through `vg annotate -p -x O104contigs_IAI39contigs_a.xg -` and then `vg view -aj -`, to annotate the alignments with `refpos` values and then convert them to JSON for viewing. If you do that, each alignment is still going to get a `refpos` on each path, since both paths go through this part of the graph.

Does all that help at all?

**Comment by kevsilva** [comment]
Thank you so much, this is really clear and helpful. Just some more clarifications:

For `refpos`, do you know the number behind "just some of them"? Does `refpos` annotate the alignment if at least **one** node of the read touches a path, for example?

Thanks to your explanation I understand how `-w` works and why I have this secondary alignment with those offset and score. And additionally, I realised it was not the second alignment I was in fact expecting. Because I still expect at least two alignments or some kind of other result: if I go back with my first result (without playing with `-w`) and look for perfect matching between nodes from the alignment and nodes from the path, I will find that this read comes from IAI39 only. However I simulated reads from O104, so I should only find reads from O104 only, or from O104 **and** IAI39 but never IAI39 only.
The alignment I am expecting exists in the graph and is visible in the image from my first post (without listing every node, it goes from node 348284 to 348302, 348650 to 348654, and finally 248229, 348230, 348232). Is there a parameter from `vg map` I should change to get this alignment or having only one alignment is some kind of related to the fact that the nodes 248229, 348230 and 348232 exist in the two expected alignments and for some reason then only one alignment is displayed?

**Comment by adamnovak** [comment]
I think that having a single node on the path is sufficient to get a refpos annotation for it. @ekg would probably know for sure.

As for getting the wrong alignment, if both potential alignments spell out the same sequence, and they are sufficiently close together in the graph (you said they share nodes, right?), the whole graph region will be pulled out as one clustering hit, and then it is only allowed to give rise to one final alignment in that region. I guess the "wrong" one is arbitrarily winning the tie. Right now our secondary alignments have to come from different parts of the graph; they can't overlap the primary alignment, and they can't even be too close in graph space.

If you want to consider multiple different alignments to the same part of the graph, our multipath mapper (vg mpmap) can potentially do that. It outputs "multipath" alignments, that are essentially graphs of pieces of alignment between a read and the graph reference; you can traverse those graphs and get a whole selection of optimal and suboptimal alignments of a read to a graph region.

**Comment by kevsilva** [comment]
Again thank you for this very helpful answer.

Now I wanted to try vg mpmap but I get an error:
`ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.`

As input, I tried fasta (even though it does not seem to be a valid input according to the help), fastq and gam, with or without -S, with more or less -t.

**Comment by jeizenga** [comment]
Could you copy the exact command you used when you got that signal 11 error?

**Comment by adamnovak** [comment]
It might also be helpful to have the stack trace file; there should be a path to a file in the error message, probably under `tmp`, which includes information on exactly what vg was trying to do when it crashed.

**Comment by kevsilva** [comment]
Here it is:
`vg mpmap -x O104contigs_IAI39contigs_a.xg -g O104contigs_IAI39contigs_a.gcsa -f weird_read_2.fq -t 8 > aln.gamp`

```
Stack trace (most recent call last) in thread 33205:
#9    Object "", at 0xffffffffffffffff, in 
#8    Object "path_to_vg", at 0x198489e, in __clone
#7    Object "path_to_vg", at 0x101afea, in start_thread
#6    Object "path_to_vg", at 0x18d4255, in gomp_thread_start
#5    Object "path_to_vg", at 0xa0c336, in vg::MultipathMapper::calibrate_mismapping_detection(unsigned long, unsigned long) [clone ._omp_fn.0]
#4    Object "path_to_vg", at 0xa0be76, in vg::MultipathMapper::multipath_map_internal(vg::Alignment const&, vg::MappingQualityMethod, std::vector<vg::MultipathAlignment, std::allocator<vg::MultipathAlignment> >&, unsigned long)
#3    Object "path_to_vg", at 0xa0bbd9, in vg::MultipathMapper::align_to_cluster_graphs(vg::Alignment const&, vg::MappingQualityMethod, std::vector<std::tuple<vg::HashGraph*, std::vector<std::pair<vg::MaximalExactMatch const*, std::tuple<long, bool, unsigned long> >, std::allocator<std::pair<vg::MaximalExactMatch const*, std::tuple<long, bool, unsigned long> > > >, unsigned long>, std::allocator<std::tuple<vg::HashGraph*, std::vector<std::pair<vg::MaximalExactMatch const*, std::tuple<long, bool, unsigned long> >, std::allocator<std::pair<vg::MaximalExactMatch const*, std::tuple<long, bool, unsigned long> > > >, unsigned long> > >&, std::vector<vg::MultipathAlignment, std::allocator<vg::MultipathAlignment> >&, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >*)
#2    Object "path_to_vg", at 0xa0758b, in vg::MultipathMapper::multipath_align(vg::Alignment const&, vg::HashGraph const*, std::vector<std::pair<vg::MaximalExactMatch const*, std::tuple<long, bool, unsigned long> >, std::allocator<std::pair<vg::MaximalExactMatch const*, std::tuple<long, bool, unsigned long> > > >&, vg::MultipathAlignment&) const
#1    Object "path_to_vg", at 0xdb447a, in vg::algorithms::dagify(vg::HandleGraph const*, vg::MutableHandleGraph*, unsigned long)
#0    Object "path_to_vg", at 0xdb2abf, in vg::algorithms::eades_algorithm(vg::HandleGraph const*)
```

**Comment by jeizenga** [comment]
This could definitely be a bug in the code. Is this data shareable? I'll open a separate issue for this, but it will be hard for me to debug without a reproducing example.

**Comment by kevsilva** [comment]
This is from genomes from the NCBI so nothing confidential: https://github.com/kevsilva/test

Thanks!

**Comment by jeizenga** [comment]
I've opened a separate issue for the seg-fault, which should be resolved soon. I'll limit my comments here to the question of using using `vg mpmap` for this problem. 

First, I will warn you that `mpmap` is optimized for relatively simple graphs and may not perform well on graphs with complex topologies. In particular, its seed clustering is relatively fragile, and its accuracy tends to drop noticeably on graphs with a lot of cycles.

Second, `mpmap` will always attempt to produce multipath alignments with meaningful topologies, but that's a hard thing to do without some additional information about the graph. In particular, it tends to do a much better job if it knows the "snarl decomposition", which is essentially the structure of bubbles in the graph. To do that, you compute the snarls with another command and then pass them along to `mpmap`:

```
vg snarls graph.vg > graph.snarls
vg mpmap -x graph.xg -g graph.gcsa -s graph.snarls -f reads.fq > reads.mapped.gamp
```

If you'd like more information on snarls, I'd refer you to our paper:
https://link.springer.com/chapter/10.1007/978-3-319-56970-3_11
Or the preprint without a paywall:
https://www.biorxiv.org/content/10.1101/101493v1

Hope that helps!

**Comment by kevsilva** [comment]
Great, everything works fine and I got exactly what I was expecting (at least for this read).

Thank you!
