### ISSUE TITLE
Generalization to assembly graphs

### ISSUE THREAD

**Issue by ryan-williams** [vgteam/vg#22]
(although directional, nothing is intrinsically DAG-based except alignment)

**Comment by ekg** [comment]
This is an important point. We can fix this very easily with a number of
minor changes to the alignment algorithm in gssw. Basically, alignment
needs to "unroll" loops in the graph until they are at most a read length
long. This can be avoided if we detect the score decreases as the loop
progresses.

The other changes relate to enforcing a partial order over the node ids.
After construction a graph sort and a node id compaction function require
that the graph is acyclic. This isn't necessary in a global sense, and it
should be straightforward to avoid it. Circular genomes can be supported
natively with just this adjustment.

**Comment by adamnovak** [comment]
We now support cyclic graphs just fine, the only problem being variant calling when your reference path visits the same region twice.
