### ISSUE TITLE
VG RDF import turtle

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/vg#220]
There is a request for having an RDF import. The idea is that mini-paths such as Ensembl genes can be build outside of VG but included into it easily.

**Comment by ekg** [comment]
I concur. It is also an important test of the completeness of the semantic model to be able to convert losslessly between the two formats.

**Comment by JervenBolleman** [comment]
Major issue is that parsing all the RDF formats is a bit hairy, yet I don't want to add a dependancy. 
I might just parse n-triples which is the simplest to do.
