### ISSUE TITLE
Signal 11 - vg view - SibeliaZ GFA

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#2214]
Please describe:

1. What you were trying to do

I tried to convert a SibeliaZ-derived GFA of 11 ~50Mb large genomes to vg.

2. What you wanted to happen

I wanted a GFA file with 1027599 segments, 1895120 edges 4150 paths being converted to a vg file.

3. What actually happened

```
ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Crash report for vg v1.15.0 "Tufo"
Crash report for vg v1.15.0 "Tufo"
Stack trace (most recent call last):
#8    Object "vg", at 0x4d5679, in _start
#7    Object "vg", at 0x19881d8, in __libc_start_main
#6    Object "vg", at 0x4092b5, in main
#5    Object "vg", at 0x9a17a7, in vg::subcommand::Subcommand::operator()(int, char**) const
#4    Object "vg", at 0x9b168c, in main_view(int, char**)
#3    Object "vg", at 0xade46c, in vg::get_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)>)
#2    Object "vg", at 0x9ae502, in std::_Function_handler<void (std::istream&), main_view(int, char**)::{lambda(std::istream&)#7}>::_M_invoke(std::_Any_data const&, std::istream&)
#1    Object "vg", at 0xdd513e, in vg::gfa_to_graph(std::istream&, vg::VG*, bool)
#0    Object "vg", at 0x1232ec0, in stPinchThread_getFirst
```

4. What data and command line to use to make the problem recur, if applicable

```
vg view -F -v pangenome.gfa > pangenome.vg
```

Is there a upper limit for how many paths vg can handle? Segments and Edges standalone are importing as well as a smaller number of paths <100.

Cheers,
Felix

**Comment by edawson** [comment]
> 4150 paths
> Is there a upper limit for how many paths vg can handle?

Not a known one, but you might have hit it. Does your graph build if you try the same GFA without paths (e.g.   
```
grep -v "^P" pangenome.gfa > pangenome_nopaths.gfa
vg view -F -v pangenome_nopaths.gfa > pangenome_nopaths.vg
```
)?

Paths are definitely the hardest GFA entity to work with. 4500 is A LOT, especially if they're full-genome.

**Comment by edawson** [comment]
Oops - I see you already tried this.

Is there perhaps a single path that chokes it? I've seen that before as well. Is one cyclic or just way bigger than the rest?

**Comment by fbemm** [comment]
GFA without paths works. The limit seems to be around 100-200 depending on complexity. I can reduce the number to around 15 chromosome-like sequence and leave the rest out. F

On 15 Apr 2019, "Eric T. Dawson" <notifications@github.com> wrote:
>> 4150 paths
>> Is there a upper limit for how many paths vg can handle?
>
>Not a known one, but you might have hit it. Does your graph build if
>you try the same GFA without paths (e.g.   
>```
>grep -v "^P" pangenome.gfa > pangenome_nopaths.gfa
>vg view -F -v pangenome_nopaths.gfa > pangenome_nopaths.vg
>```
>)?
>
>Paths are definitely the hardest GFA entity to work with. 4500 is A
>LOT, especially if they're full-genome.

--
Felix Bemm
Sindelfinger Str. 47
72070 Tübingen
Tel. +49 173 6655117

**Comment by fbemm** [comment]
They can be between 1kb and 5Mb. That should also be reflected in the node count. Looking at MAF files in general is sort of imposing that cycles can happen. I can try again with a MAF that is deduplicated. F

On 15 Apr 2019, "Eric T. Dawson" <notifications@github.com> wrote:
>Oops - I see you already tried this.
>
>Is there perhaps a single path that chokes it? I've seen that before as
>well. Is one cyclic or just way bigger than the rest?

--
Felix Bemm
Sindelfinger Str. 47
72070 Tübingen
Tel. +49 173 6655117

**Comment by ekg** [comment]
There isn't an upper limit to anything in vg that you are likely to be able
to run into. The only exception is the 1024bp node limit for GCSA2
indexing. There should be no limit to the number of paths you can include
in terms of the code or API. At most you're running into a memory limit on
your system. The in-memory representation currently used in vg is very
inefficient though, so you'll run into this more quickly than you should.

You may be able to read this GFA into odgi for examination by the tools
there. Currently there isn't much though, just statistics and
visualization: https://github.com/vgteam/odgi. If that doesn't work then
it's also interesting, because it suggests a problem with the GFA or with
odgi.

As a final note, we should be able to build the xg index (a static index of
the graph) directly from the GFA by memory mapping the file and walking
over it. That's something I'd like to work on, but I'm occupied with more
mundane tasks at the moment.

**Comment by fbemm** [comment]
Reading the GFA without paths into odgi works, with paths it fails with:

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
Aborted (core dumped)

Looks like it fails with the first path already. I am going to debug what is wrong with the paths now.
```

**Comment by fbemm** [comment]
The issues don't look complementary. I attached a small example. It imports into vg but not in odgi. 

This works in vg:

```
vg view -F -v test_1.gfa > test_1.vg
vg mod -X 256 test_1.vg > test_1.mod.vg
vg index -x test_1.mod.xg -g test_1.mod.gcsa test_1.mod.vg
```

But with the same GFA odgi still gives:

```
node 0
edge 0
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
Aborted (core dumped)
```

[test_1.zip](https://github.com/vgteam/vg/files/3083425/test_1.zip)

Guess this should go to the odgi repo.

**Comment by fbemm** [comment]
I attached a GFA with 200 paths. Would be great if somewhere can confirm what I am experiencing. 

[test_2.gfa.zip](https://github.com/vgteam/vg/files/3083606/test_2.gfa.zip)

**Comment by fbemm** [comment]
The issue with the 200 path GFA seems to be related to the last 100 paths. The upper 100 (26Mb total sequence w/ 247,666 nodes) import/convert fine in vg. The lower 100 (12Mb total sequence w/ 142,482 nodes) won't.

**Comment by fbemm** [comment]
Think I found it. Seems as vg is failing with paths that have a single node.

`P       CTG780   699838+`

**Comment by ekg** [comment]
Was this resolved?
