### ISSUE TITLE
GAM to BAM

### ISSUE THREAD

**Issue by ziaursani** [vgteam/vg#2216]
I want to get BAM format from a GAM file. I am using following command.
vg surject -x NCYC430_paired.xg -b NCYC430_paired.gam > NCYC430_paired.bam

I am getting following error 
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
 what():  Tried to get paths of nonexistent node 2
terminate called recursively
Segmentation fault

I have attached xg file. I cannot attach GAM file it is quite big. Please help.

Zia

[NCYC430_paired.zip](https://github.com/vgteam/vg/files/3085733/NCYC430_paired.zip)

**Comment by ekg** [comment]
It would seem that you have a mismatch between the graph you aligned
against and the one you're using for surjection.

Note that you can also directly output BAM from vg map with `--surject-to
bam`.

**Comment by ziaursani** [comment]
Yes you are right my xg file was wrong. I have now created BAM file NCYC430_paired.bam. But now I want to create its index file with

samtools index NCYC430_paired.bam

When I apply above command I get following error

[E::hts_idx_push] NO_COOR reads not in a single block at the end 0 -1
samtools index: failed to create index for "NCYC430_paired.bam": No such file or directory

Please help.

Zia

**Comment by ekg** [comment]
You may need to sort the file to get the indexing to work. Did you already
do that?

**Comment by ziaursani** [comment]
thanks job done
