### ISSUE TITLE
Vg creating partially connected nodes for insertions

### ISSUE THREAD

**Issue by cgroza** [vgteam/vg#2264]
Please describe:

1. What you were trying to do
Hi,
I am trying to add some large insertions to the hg38 human reference.
I created a VCF and FASTA file pair, and passed them to vg construct using `vg construct` with the  `-vcf` and `-I` options.

2. What you wanted to happen
Normally, I expect the nodes correspoding to the insertion to be connected on the left and right side. However this only happens for only some of the insertions.

3. What actually happened
For some insertions, they are only connected on the left or right side, which makes them dangle from the reference path.

4. What data and command line to use to make the problem recur, if applicable
This is the commant that I used to create the genome:
```
set -x
mkdir graphs
ref=/project/6007512/C3G/projects/hg38_svs/Homo.sapiens.hg38.fa

for C in $(seq 1 22; echo X; echo Y)
do
vg construct -S -I NA12878_sv_subseqs.fa -v NA12878_svs_fixed.vcf.gz  -C -R chr$C -r $ref -t 1 -m 32 > graphs/chr$C.vg
done
#NOTE: remember to run this part
vg ids -j $(for i in $(seq 1 22; echo X; echo Y); do echo graphs/chr$i.vg; done)
```
Data and an example from my graph is available at:
https://github.com/cgroza/vg_vcf_fasta
The example in the repo is at position:
```
chr9	137322694	137322695
```
Example: https://github.com/cgroza/vg_vcf_fasta/blob/master/sv.svg

Thank you in advance for any help.

**Comment by glennhickey** [comment]
It looks okay to me.  Perhaps you are not setting enough context expansion steps when visualizing to properly see the entire insertion?
```
vg construct -r hg38.fa -v NA12878_svs_fixed.vcf.gz -S -I NA12878_sv_subseqs.fa -R chr9 -C > svs_chr9.vg
vg stats -HT svs_chr9.vg
# heads	1 
# tails	4325635
# Shows 1 head and 1 tail in graph, so no dangling nodes apart from 2 telomeres
vg index svs_chr9.vg -x svs_chr9.xg
vg find -x svs_chr9.xg -p chr9:137322694-137322695 -c 20  | vg view -pd - -S | dot -Tpng > out.png
```
![out](https://user-images.githubusercontent.com/901102/57654484-45efb580-75a2-11e9-8d01-df19b0912620.png)

**Comment by cgroza** [comment]
Yes that did it. Thank you!
