### ISSUE TITLE
extract exact sequences from the graph

### ISSUE THREAD

**Issue by ManuelTgn** [vgteam/vg#2281]
Hi everyone,

I'm new using this tool and I'd like to extract a precise "substring" from the .xg file (for example the string that is contained between positions i and j); now what I can obtain is the subgraph between i and j, but it's not what I'm looking for, so, is there a command line or a commands pipeline to extract such a substring, taking into account also all the possible alternative paths between the two queried positions?    
Thank you.

**Comment by ekg** [comment]
You would need to extract a subgraph, and then enumerate the kmers inside
of it. Try this:

vg construct -r 1mb1kgp/z.fa -v 1mb1kgp/z.vcf.gz -m 32 -p >z.vg
vg index -x z.xg z.vg
vg find -x z.xg -n 49202 -c 10 | vg kmers -k 11 -

A substring of a graph isn't well defined, but kmer enumeration is.

**Comment by lucapinello** [comment]
Hi Erik!

Hope you are well.

I have a similar question.

Given a region coordinate in a reference genome i.e. 

chr1:102334-103334

What is the simplest way to extract the subgraph corresponding to this range?

In the manual I saw:

find: use an index to find nodes, edges, kmers, or **positions**

Is the position here the position in the genome?

Thanks!

**Comment by ekg** [comment]
Hi Luca!

This should be pretty easy to do with this parameter to `vg find`:

    -p, --path TARGET      find the node(s) in the specified path range(s) TARGET=path[:pos1[-pos2]]

It's a little tricky. We need to "expand the context" of the graph by a few steps using the `-c` parameter in order to be sure to get all the neighboring small variants. Otherwise, we'll just get the subgraph corresponding to this path and edges connected to it.

To explain visually:

```
cd ~vg/test
# build the graph
vg construct -r tiny/tiny.fa -v tiny/tiny.vcf.gz >t.vg
# visualize it
vg view -dp t.vg | dot -Tpng -o t.vg.png
```
![t vg](https://user-images.githubusercontent.com/145425/58633095-c4a95a00-82e7-11e9-95b1-e77bd1759097.png)
```
# index the graph
vg index -x t.xg t.vg
# pick up a subgraph without context expansion
vg find -p x:30-35 -x t.xg | vg view -dp - | dot -Tpng -o t.vg.x:30-35.png
```
![t vg x:30-35](https://user-images.githubusercontent.com/145425/58633141-e1de2880-82e7-11e9-81b0-ae5a6e48017d.png)
```
# pick up a subgraph with context expansion
vg find -p x:30-35 -c 1 -x t.xg | vg view -dp - | dot -Tpng -o t.vg.x:30-35c1.png
```
![t vg x:30-35c1](https://user-images.githubusercontent.com/145425/58633223-27025a80-82e8-11e9-9923-87de746a0285.png)

And by working through this I may have uncovered an old bug. I would expect to see one less step in node space than we're getting here. Hmm.

Anyway, hopefully this explains how to do this for what you're interested in.

**Comment by lucapinello** [comment]
Hi Erik,

Thank you so much for the real-time response :)

This is super helpful!

Considering that the string (30:35) is between nodes: 9 and 12, is there a way to expand only adding the node 10 i.e. getting this:

![image](https://user-images.githubusercontent.com/1081322/58634089-66b14e00-82b8-11e9-9e04-0459dbc1c1a0.png)

**Comment by ekg** [comment]
I started writing a response but it took longer than editing the code to fix up some of the weird things we ran into here and support this application.

The totally generic way to do this would require us making a snarl/bubble decomposition of the graph and using that to find places where there are variants in bubbles that your path range overlapped. I'm leaving that for another day.

If your graph is a DAG, say built from small variants and a reference, and its ids are assigned according to the partial order, then we can just run the path range query and add nodes in the id range between the start and end node in the path target.

I also started to make a complicated command line to demonstrate this, but realized it didn't work and it was easier to just implement in `vg find`. I've pushed the changes to a PR #2288.

```
    -E, --path-dag TARGET  like -p, but gets any node in the partial order from pos1 to pos2, assumes id sorted DAG
```

```
vg find -x t.xg -E x:30-35 | vg view -dp - | dot -Tpng -o t.vg.x:30-35.path-dag.png
```

![t vg x:30-35 path-dag](https://user-images.githubusercontent.com/145425/58637329-93825700-82f2-11e9-9030-a4380b06f402.png)

You can pull from that branch or wait for it to land in master, which probably will be later today or tomorrow as we need to let the CI tests complete.

**Comment by ManuelTgn** [comment]
Hi Erik,

is it also possible to keep track of the path range inside the obtained nodes?
More precisely, since our path is in range 30:35, is it possible to have pointers inside nodes that point to the starting and ending nucleotide, in order to have the precise queried path range?

Thank you again

![Inked58637329-93825700-82f2-11e9-9030-a4380b06f402_LI](https://user-images.githubusercontent.com/51021763/58649109-8de53b00-830b-11e9-9e6c-a25797cadced.jpg)

**Comment by ekg** [comment]
We could emit an alignment representing the subpath. Or cut the nodes at
the right point.

All these functions suggest we should make a new command.

I was thinking vg subgraph.

**Comment by na76** [comment]
Would it be possible to limit the enumerated kmers described by ekg to those including the non-reference sequence when a variant is present? We are working with graphs constructed using only one variant and would like to retrieve the sequences of those variants at specific reference genome coordinates. In the example above, if we take nodes 10 and 11 to represent a SNP, with 10 being the non-reference base, we would like querying x:30-35 retrieve the substring "CTATAA".

Additionally, is it possible to convert a node ID to the linear genome coordinate at which it starts? For example, querying node ID 9 would correspond to x:15. We could use this to select the correct kmer by finding the difference between the start of the desired interval (x:30) and the start of the node (x:15).

**Comment by ManuelTgn** [comment]
Hi guys,

 

Thank you so much for the function to extract subgraphs from the vg genome graph. We have been having a lot of fun building a tool bases on this!
 

We would like to know if it is possible to speed up the extraction process. We are currently using this command:

 

vg find -x genome_graph -E index:start_position-end_position

 

This with 5000 regions on a regular PC it takes about 7-8 hrs.
 
Also we were wondering if we it may make sense to provide to the command a list of regions instead of executing it one region at the time. Since this can help to speedup the execution if some parts are in common.

 
Last minor thing, can you please return two pointers that point to the starting and ending position of the region inside the first and last node returned; I was thinking something like 
starting_node_id:position - ending_node_id:position
 


Thank you so much guys!

@ekg @lucapinello

**Comment by ekg** [comment]
Great to hear this is working out for you! The performance is
understandable though. Virtually all your runtime is loading the xg index
and this would run orders of magnitude faster if that load cost could be
paid once.

A quick solution would be to provide a file with a list of targets and
write out each target as a separate file. That's a very quick patch to vg
find, so I might be able to do it to help you out.

This week at the BioHackathon in Japan I will be making a server based on
xg that exposes the handle graph API. The idea there would be to wrap that
API in a python library or similar. You might then be able to use this for
your queries.

**Comment by lucapinello** [comment]
Hi Erik,

Yeah this makes sense. We can provide a minimal BED file with three columns with all the regions like this:

chr1   1231231   1231931 
chr2  2231231   2231931 
.
.
.

For the output sounds great maybe:

1) one file per region as you have suggested.
2) A separate file with for each region the start and end indexes on the first and last node of the extracted subgraph? (or alternatively, this can be put on top of each file in 1) ).

Also really excited about the Python API! Happy to try it as soon as you have an initial version.

Thanks a ton!

**Comment by ManuelTgn** [comment]
Hi @ekg ,

I was wondering if you had time to implement the new function we had discussed with Luca. We are looking forward to test it!

I am attaching a sample BED file from ENCODE. Essentially we need just the first 3 columns so feel free to ignore the rest.

I am printing here the top 10 lines:

`chr11	7536097	7536521	.	1000	.	63.61172	-1	4.63505	212
chr6	75230591	75230715	.	1000	.	63.61909	-1	4.63505	109
chr10	110311467	110311600	.	1000	.	63.62055	-1	4.63505	57
chr9	126302100	126302247	.	1000	.	63.62961	-1	4.63505	58
chr2	31729819	31729973	.	1000	.	63.63058	-1	4.63505	54
chr17	19646020	19646186	.	1000	.	63.63468	-1	4.63505	84
chr3	152835213	152835637	.	1000	.	63.63566	-1	4.63505	212
chr15	62125744	62126168	.	1000	.	63.63572	-1	4.63505	212
chr5	149951262	149951410	.	1000	.	63.6387	-1	4.63505	77
chr5	172646879	172647303	.	1000	.	63.64538	-1	4.63505	212`

Thanks a lot again!

**Comment by lucapinello** [comment]
Hi @ekg I was wondering if you can take a look at this when you have time.

Thanks a lot for the help!

Luca

**Comment by ekg** [comment]
Yes, sorry that I missed this. Adding this should be simple. I guess you
don't write c++? ;)

I've put a reminder in my calendar for tomorrow. Sorry for the wait.

**Comment by ekg** [comment]
@jeizenga and I were talking about making a python wrapper for a very
simple variation graph API. I guess I'd have your votes for that? Do you
think it would be useful? (Not saying that I would do this instead of the
bed region extracting, but for later.)

**Comment by lucapinello** [comment]
Hey @ekg thanks! Yeah my C++ is pretty rusty :)

Also a Python API would be amazing and very helpful for the community.

**Comment by ekg** [comment]
@lucapinello I've got an update in this PR that resolves your request: https://github.com/vgteam/vg/pull/2488#issue-322170398

Please build from that branch and test. It may be that we run into some problems with other tests due to the slight change in semantics of vg find, but I can probably clear these up quickly if they occur, and this should land in master soon.

Hope this helps!

**Comment by lucapinello** [comment]
Terrific! We will test this and we will let you know soon. Thank you so much Erik!
