### ISSUE TITLE
use vg find to grab all bubbles in a path range of a partially ordered graph

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#2287]
Hi Erik,

Thank you so much for the real-time response :)

This is super helpful!

Considering that the string (30:35) is between nodes: 9 and 12, is there a way to expand only adding the node 10 i.e. getting this:

![image](https://user-images.githubusercontent.com/1081322/58634089-66b14e00-82b8-11e9-9e04-0459dbc1c1a0.png)

_Originally posted by @lucapinello in https://github.com/vgteam/vg/issues/2281#issuecomment-497318789_

**Comment by glennhickey** [comment]
This is good functionality to have.  I think @jeizenga has something a little more general [here](https://github.com/vgteam/vg/blob/master/src/algorithms/extract_connecting_graph.hpp), which I've been meaning to try out in chunk (#2144)

**Comment by ekg** [comment]
This is a slightly different way of extracting the connecting graph. It's more general in that it should work on any kind of graph, but it has a distance parameter that might require tuning in some cases. We should also expose it in `vg find`, or maybe another utility specific to this task? `vg subgraph`?

**Comment by lucapinello** [comment]
Thank you so much @ekg and @glennhickey !

@ekg we will try your commit, thanks for the quick solution.

I want to provide some context here. We are trying to explore subgraphs corresponding to functional regions in the genome (a bed file with ENCODE peaks, promoter regions etc.) 

So I think having a separate utility would be great. 

Something like:

vg subgraph -r chr1:12323-12323 
(r= region)

This will be really helpful to explore subgraphs in important regions of the genome.
