### ISSUE TITLE
vg mpmap very slow on short reads

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#2302]
@jeizenga @adamnovak 
Some of the reads when running 3 GB .fastq.gz chunks of reads from a whole genome HG002 readset are very slow on `vg mpmap` and can occupy a single thread for hours. Graph reference indexes where constructed using snp1kg phase 3 vcf and grch37d5.fa on vg container version `quay.io/vgteam/vg:v1.14.0-23-g2f02b148-t289-run`

The following is an example of one read pair chunk that was run in mpmap that took longer than 10 hours to process.

The command when running on VG container `quay.io/vgteam/vg:v1.15.0-208-gce79450f1-t311-run`:
```
vg mpmap \
    -S \
    -f fq_chunk_1.part.aa.fq.gz -f fq_chunk_2.part.aa.fq.gz \
    -x snp1kg_maf0.01_decoys_t289.xg \
    -g snp1kg_maf0.01_decoys_t289.gcsa \
    --gbwt-name snp1kg_maf0.01_decoys_t289.gbwt \
    -s snp1kg_maf0.01_decoys_t289.snarls
```

Input files:
- stderr log file indicating reads that were processing a long time and took up significant amounts of memory: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/stderr
- subsampled GAM for fragment-length distribution: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/subsample.gam
- GAM file created up to the 10 hour mark: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/HG003.aa.gam
- 1st read pair: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/fq_chunk_1.part.aa.fq.gz
- 2nd read pair: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/fq_chunk_2.part.aa.fq.gz
- XG index: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/snp1kg_maf0.01_decoys_t289.xg
- GCSA index: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/snp1kg_maf0.01_decoys_t289.gcsa
- GCSA LCP index: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/snp1kg_maf0.01_decoys_t289.gcsa.lcp
- GBWT index: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/snp1kg_maf0.01_decoys_t289.gbwt
- SNARLS index: https://storage.googleapis.com/cmarkell-vg-wdl-dev-test/problem_reads/snp1kg_maf0.01_decoys_t289.snarls

**Comment by cmarkello** [comment]
@jeizenga 
Sorry that command is incomplete.

Here's the full command:
```
vg mpmap \
    -S \
    -f fq_chunk_1.part.aa.fq.gz -f fq_chunk_2.part.aa.fq.gz \
    -x snp1kg_maf0.01_decoys_t289.xg \
    -g snp1kg_maf0.01_decoys_t289.gcsa \
    --gbwt-name snp1kg_maf0.01_decoys_t289.gbwt \
    -s snp1kg_maf0.01_decoys_t289.snarls \
    --read-group "ID:1 LB:lib1 SM:HG003 PL:illumina PU:unit1" \
    -t 32 \
    --recombination-penalty 5.0 \
    --sample "HG003" > HG003.aa.gam
```

**Comment by jeizenga** [comment]
This turned out to be a bad interaction between the haplotype-consistent tracebacks used for population MAPQs and complex multipath alignments produced in telomere regions. Following our discussion offline, the most immediate solution is not use the population MAPQs (i.e. remove the `--gbwt-name`, `--recombination-penalty`, and `-s` arguments), especially since we've become more doubtful about how useful the population MAPQs are anyway.

**Comment by cmarkello** [comment]
@jeizenga
I've now reproduced this problem persists on my parental graphs, though that's for a sample I can't release as it's real data. I've also noticed that there's a much more significant use of memory for some reason when using parental graph references instead of the snp1kg graph references.

However because that graph index is made of just the parents there should be at most 4 haplotypes present in the GBWT.
Should that still produce the same side-effect of slow mapping reads to the telomeric regions?
If this is a problem even for small-sample size graph references, what's the practical use-case for the GBWT and SNARL indicies?
Can my partially phased trio VCF be useful for parental graph construction or should I just abandon using phasing information?

I'm reopening this issue since I think this may be relevant to other issues.

**Comment by jeizenga** [comment]
I'm a bit surprised by that, but I can think of some left-field scenarios where this could happen. It's pretty hard for me to know exactly what's causing it to run slower without being able to see the data though. 

In theory you should get better results using a parental cohort (if it's well-phased) than a population cohort, but we've never systematically evaluated that to see exactly how much more helpful it is. Given the small effect size from the population, it still might be not be particularly worth it. Moreover, I expect that we'd need to change parameterization of the haplotype scoring, which we also haven't investigated. 

Given all the unknowns, I'd say that at least in the interim, leaving out the GBWT/snarl combo might be the best option.
