### ISSUE TITLE
Find back vg map result from vg mpmap

### ISSUE THREAD

**Issue by kevsilva** [vgteam/vg#2343]
Hello,

I am mapping a read ending by AAAAA on a graph, the interesting part of the graph I am dealing with is the following:

![subgraph_read72242](https://user-images.githubusercontent.com/48321731/61220245-3150aa80-a716-11e9-8151-d1b2dd8319f1.png)

I cannot use `vg map` here because I want all the possible paths my mapping can follow. Mainly the path composed of the nodes 167025, 167026 and the first 4 bases of the 395944, and the path composed of the nodes 167025 and the first 5 bases of the 395944.

If I use `vg map`, I get this output:
`{"sequence":"CGCTCCAGCTCTTCGCGCTGATGCTGGGCATTTTGAACTTCCTGCGACAGTGAGTTGTTTTTTTCTTTCAGCTCTTCGATTTCCATCTGCAACAGAGTGATGGTATCAATCGCCTGCTGTACTTTTGCTTCCAGTTTCTCAAACACTTCTAATGACATTGTCATACCTCTCCTGAATTGCAAGGCGTTGATGGATAAAAA","path":{"mapping":[{"position":{"node_id":"395937","offset":"18"},"edit":[{"from_length":12,"to_length":12}],"rank":"1"},{"position":{"node_id":"395938"},"edit":[{"from_length":30,"to_length":30}],"rank":"2"},{"position":{"node_id":"395939"},"edit":[{"from_length":30,"to_length":30}],"rank":"3"},{"position":{"node_id":"395940"},"edit":[{"from_length":30,"to_length":30}],"rank":"4"},{"position":{"node_id":"395941"},"edit":[{"from_length":30,"to_length":30}],"rank":"5"},{"position":{"node_id":"395942"},"edit":[{"from_length":30,"to_length":30}],"rank":"6"},{"position":{"node_id":"395943"},"edit":[{"from_length":30,"to_length":30}],"rank":"7"},{"position":{"node_id":"167025"},"edit":[{"from_length":3,"to_length":3}],"rank":"8"},{"position":{"node_id":"167026"},"edit":[{"from_length":1,"to_length":1}],"rank":"9"},{"position":{"node_id":"395944"},"edit":[{"from_length":4,"to_length":4}],"rank":"10"}]},"name":"read72242_contig0_position5031441_M0_I0_D0_NG0______er0__indel0__rgeom0_rev0","mapping_quality":60,"score":210,"identity":1,"refpos":[{"offset":"3195687","name":"gi|218698419|NC_011750.1|Escherichia_coli_IAI39_UTI "},{"offset":"5031441","name":"gi|407479587|NC_018658.1|Escherichia_coli_O104:H4_HUS "}],"time_used":1866}`
I only get the "167025+167026+first 4 bases of the 395944" path.

If I use `vg mpmap` I get this:
`{"sequence":"CGCTCCAGCTCTTCGCGCTGATGCTGGGCATTTTGAACTTCCTGCGACAGTGAGTTGTTTTTTTCTTTCAGCTCTTCGATTTCCATCTGCAACAGAGTGATGGTATCAATCGCCTGCTGTACTTTTGCTTCCAGTTTCTCAAACACTTCTAATGACATTGTCATACCTCTCCTGAATTGCAAGGCGTTGATGGATAAAAA","quality":"KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCg=","name":"read72242_contig0_position5031441_M0_I0_D0_NG0______er0__indel0__rgeom0_rev0","subpath":[{"path":{"mapping":[{"position":{"node_id":"395937","offset":"18"},"edit":[{"from_length":12,"to_length":12}],"rank":"1"},{"position":{"node_id":"395938"},"edit":[{"from_length":30,"to_length":30}],"rank":"1"},{"position":{"node_id":"395939"},"edit":[{"from_length":30,"to_length":30}],"rank":"1"},{"position":{"node_id":"395940"},"edit":[{"from_length":30,"to_length":30}],"rank":"1"},{"position":{"node_id":"395941"},"edit":[{"from_length":30,"to_length":30}],"rank":"1"},{"position":{"node_id":"395942"},"edit":[{"from_length":30,"to_length":30}],"rank":"1"},{"position":{"node_id":"395943"},"edit":[{"from_length":30,"to_length":30}],"rank":"1"},{"position":{"node_id":"167025"},"edit":[{"from_length":3,"to_length":3}],"rank":"1"}]},"next":[1,2],"score":200},{"path":{"mapping":[{"position":{"node_id":"167026"},"edit":[{"from_length":1}],"rank":"1"}]},"next":[2],"score":-6},{"path":{"mapping":[{"position":{"node_id":"395944"},"edit":[{"from_length":5,"to_length":5}],"rank":"1"}]},"score":10}],"mapping_quality":60,"start":[0],"annotation":{}}`
Two possible paths: 167025, 167026 with a deletion and the first 5 bases of 395944, or 167025 and the first 5 bases of 395944. The later being one of the two paths I am expecting but I do not get the other one found with `vg map`.

Hence my question, is there a way to find back the result of `vg map` using `vg mpmap`? Did I miss something in the parameters (everything is in default, I generated the snarls file for the multipath alignement)?

Thanks!

**Comment by jeizenga** [comment]
This is something that is certainly a challenge for mpmap. Since there's no clear "optimal" way to make a multipath alignment, it has to employ some heuristics when it's deciding how to structure them. This is case where the heuristics seem to be producing some unintended results.

There is a computational parameter that can help in cases like this, at the cost of slower mapping. I don't believe it's currently exposed at the command line, but if you're comfortable hacking the code it's right here: https://github.com/vgteam/vg/blob/master/src/subcommand/mpmap_main.cpp#L132. I think if you increased it to 5 it would have solved this case. I could also look into adding it as a command line option.

**Comment by kevsilva** [comment]
Thanks. Provided I did it correctly (edit mpmap_main.cpp and then use `make` again), I tried 5, 8 and even 12, and the outputs were exactly the same sadly.

**Comment by jeizenga** [comment]
Hmm, interesting. Is it possible to share the graph?

**Comment by kevsilva** [comment]
Here it is.
[seqwish_O104_IAI39_asm5.norm.zip](https://github.com/vgteam/vg/files/3405090/seqwish_O104_IAI39_asm5.norm.zip)

Thanks again!

**Comment by jeizenga** [comment]
Sorry for the slow response, just getting back to this. It seems I directed you to the wrong line last time! Sorry about that. The correct parameter is `max_branch_trim_length` on the following line.

**Comment by kevsilva** [comment]
Hi, thank you for getting back. But at the time of your suggestion the line was correct, `max_branch_trim_length` is the parameter I tested in my previous answer.

**Comment by jeizenga** [comment]
Oh, I see. Sorry! I'll take another look at this then.
