### ISSUE TITLE
start field in vg mpmap output

### ISSUE THREAD

**Issue by kevsilva** [vgteam/vg#2358]
Hello,

I am confused about the `start` field in the output of `vg mpmap`. I am not sure if it is a bug or an expected behavior or me misunderstanding this field. I have two examples.

The first one is the following:
```
{'sequence': 'GTATTCCTGTGTCTGGCGGCGCTGTACGAGAGCTGGTCGATTCCGTTCTCCGTTATGCTGGTCGTTCCGCTGGGGGTTATCGGTGCGTTGCTGGCTGCCACCTTCCGTGGCCTGACCAATGACGTTTACTTCCAGGTAGGCCTGCTCACAACCATTGGGTTGTCGGCGAAGAACGCGATACTTATCGTCGAATTCGCCAA',
 'quality': 'KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCg=',
 'name': 'read28226_contig0_position3934529_M0_I0_D0_NG0______er0__indel0__rgeom0_rev0',
 'subpath': [{'path': {'mapping': [{'position': {'node_id': '179167',
       'offset': '12'},
      'edit': [{'from_length': 2, 'to_length': 2},
       {'from_length': 1, 'to_length': 1, 'sequence': 'A'}]}]},
   'next': [2],
   'score': 3},
  {'path': {'mapping': [{'position': {'node_id': '131048', 'offset': '11'},
      'edit': [{'from_length': 3, 'to_length': 3}]}]},
   'next': [2],
   'score': 8},
  {'path': {'mapping': [{'position': {'node_id': '367164'},
      'edit': [{'from_length': 31, 'to_length': 31}],
      'rank': '1'},
     {'position': {'node_id': '367165'},
      'edit': [{'from_length': 31, 'to_length': 31}],
      'rank': '2'},
     {'position': {'node_id': '367166'},
      'edit': [{'from_length': 31, 'to_length': 31}],
      'rank': '3'},
     {'position': {'node_id': '367167'},
      'edit': [{'from_length': 31, 'to_length': 31}],
      'rank': '4'},
     {'position': {'node_id': '367168'},
      'edit': [{'from_length': 31, 'to_length': 31}],
      'rank': '5'},
     {'position': {'node_id': '367169'},
      'edit': [{'from_length': 31, 'to_length': 31}],
      'rank': '6'},
     {'position': {'node_id': '367170'},
      'edit': [{'from_length': 11, 'to_length': 11}],
      'rank': '7'}]},
   'score': 202}],
 'mapping_quality': 60,
 'start': [0, 2],
 'annotation': {}}
```
There are 3 subpaths. And while `start` indicates indexes 0 and 2, it is pretty clear that the potential roots of this alignment are subpath[0] and subpath[1], they have the `next` field set to [2].

An other example is with this read:
```
'AAACTGCGTTAATTACGCGTCTTAAATCACTGATTGCTGAGCAACAGGTAATTACGATTTTAGTTAAGGGTTCACGTAGTGCCGCCATGGAAGAGGTAGTACGCGCTTTACAGGAGAATGGGACATGTTAGTTTGGCTGGCCGAACATTTGGTCAAATATTATTCCGGCTTTAACGTCTTTTCCTATCTGACGTTTCGCG'
'start': [11, 22, 31, 0, 82, 91, 51, 73, 62, 40]
```
Not putting everything but this alignment has 91 subpaths. Index 91 in the `start` field is then out of range.

If you want to reproduce this, the graph I used is the same as here: https://github.com/vgteam/vg/issues/2343#issuecomment-512686337

Thank you!

**Comment by adamnovak** [comment]
The start field is supposed to point to the subpaths that begin with the first base in the read. It certainly does look to me like it ought to be `[0, 1]` in your example and not `[0, 2]`.

@jeizenga Can you reproduce this or shed light on how this is a plausible answer for mpmap to have?

**Comment by jeizenga** [comment]
Looks like a bug. How recent is your build? I fixed a bug that could have caused this problem about 2 weeks ago: https://github.com/vgteam/vg/pull/2333. If you haven't recompiled since then, that might fix it.

**Comment by kevsilva** [comment]
Indeed, with the most recent build, the output has changed (for my first example, there is now only one subpath). There is no index out of range and I could not find any other inconsistencies.

Thanks!
