### ISSUE TITLE
deconstruct shouldn't need to take a reference FASTA file

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#236]
It would be nice to do this:

```
➜  test git:(master) ✗ vg msga -f x.fa | vg deconstruct -p path - -o x.vcf
Error: A reference is needed for projection into vcf.
```

The reference path is embedded in the input, so maybe we could pull it directly out of the graph rather than use an external file? For instance, I may not have a FASTA file at all for any of the paths in my graph.

**Comment by edawson** [comment]
There are some other issues with deconstruct as well:
1. Streaming input is probably not implemented (at least in an obvious way).
2. It doesn't like reversals in the graph.
3. Its interface (especially the help message) is pretty broken.

I will put it on my todo list to patch these things up.

**Comment by ekg** [comment]
Streaming input is probably an easy fix, because we can load the whole graph using an idiom like:

```C++
VG* graph;
string file_name = argv[optind];
if (file_name == "-") {
    graph = new VG(std::cin);
} else {
    ifstream in;
    in.open(file_name.c_str());
    graph = new VG(in);
}
```

A streaming algorithm is another problem. Let's not focus on that; we should be able to fit the whole graph in memory, although at some point we'll need to rewire VG to use an alternative backend for high memory graphs, something like a dynamic version of XG.

**Comment by adamnovak** [comment]
The vg deconstruct help doesn't say it needs a reference FASTA (or how to give it one), so I will assume this is done.
