### ISSUE TITLE
vg mod no longer holds onto embedded paths.

### ISSUE THREAD

**Issue by Robin-Rounthwaite** [vgteam/vg#2364]
I used to generate subgraphs using vg mod to visualize embedded paths as a .svg file. Now when I run (what I believe to be) the same command, vg mod produces graphs without embedded paths, even when they used to have them.

example usage:
```
vg mod -g 23459 -x 20 test_mod.vg|\
vg view -dp - |\
dot -Tsvg -o test_mod.svg

chromium-browser test_mod.svg
```

**Comment by Robin-Rounthwaite** [comment]
Here's a better example, using the tiny graph in test.
```
TEST_DIR=test/tiny
FILE_NAME=tiny
FILE_NAME_OUT=tiny_out

echo "construct graph"
# make the graph with an embedded path
vg construct -r $TEST_DIR/$FILE_NAME.fa -v $TEST_DIR/multi.vcf.gz > $TEST_DIR/$FILE_NAME.vg

echo "view constructed graph"
# check to see that the path is there.
./bin/vg view -dpn $TEST_DIR/$FILE_NAME.vg| \
dot -Tsvg -o $TEST_DIR/$FILE_NAME.svg
chromium-browser $TEST_DIR/$FILE_NAME.svg

echo "modify graph"
# modify the graph
vg mod -g 12 -x 3 $TEST_DIR/$FILE_NAME.vg >$TEST_DIR/$FILE_NAME_OUT.vg #produces snarl from 1879:12785

echo "view modified graph"
# no embedded paths!
./bin/vg view -dpn $TEST_DIR/$FILE_NAME_OUT.vg| \
dot -Tsvg -o $TEST_DIR/$FILE_NAME_OUT.svg
chromium-browser $TEST_DIR/$FILE_NAME_OUT.svg
```

@jeizenga

**Comment by glennhickey** [comment]
Don't know why context expansion in *vg* is dropping paths, but FWIW you can use `vg find` on an *xg* as a workaround:
```
vg construct -r test/tiny/tiny.fa -v test/tiny/tiny.vcf.gz > tiny.vg
vg index tiny.vg -x tiny.xg
vg find -x tiny.xg -n 12 -c 3 > tiny_out.vg
vg paths -v tiny_out.vg -X | vg view -a -
```
gives
```
{"sequence":"GAAATTTTCTGGAGTTCTATTATATTCCAACTCTCTG","path":{"name":"x","mapping":[{"position":{"node_id":"8"},"edit":[{"from_length":1,"to_length":1}],"rank":"5"},{"position":{"node_id":"9"},"edit":[{"from_length":19,"to_length":19}],"rank":"6"},{"position":{"node_id":"11"},"edit":[{"from_length":1,"to_length":1}],"rank":"7"},{"position":{"node_id":"12"},"edit":[{"from_length":4,"to_length":4}],"rank":"8"},{"position":{"node_id":"14"},"edit":[{"from_length":1,"to_length":1}],"rank":"9"},{"position":{"node_id":"15"},"edit":[{"from_length":11,"to_length":11}],"rank":"10"}]},"name":"x"}
```

**Comment by Robin-Rounthwaite** [comment]
Good idea - I've been using that! Unfortunately it's only a partial solution. It works to preserve the paths inside the xg, but most paths aren't usually stored in the xg. On the thousand genomes chr10 graph I'm working with, for example, there's only the reference genome stored on the xg. The rest are in the vcf.

On Aug 9, 2019 1:58 PM, Glenn Hickey <notifications@github.com> wrote:

Don't know why context expansion in vg is dropping paths, but FWIW you can use vg find on an xg as a workaround:

vg construct -r test/tiny/tiny.fa -v test/tiny/tiny.vcf.gz > tiny.vg
vg index tiny.vg -x tiny.xg
vg find -x tiny.xg -n 12 -c 3 > tiny_out.vg
vg paths -v tiny_out.vg -X | vg view -a -


gives

{"sequence":"GAAATTTTCTGGAGTTCTATTATATTCCAACTCTCTG","path":{"name":"x","mapping":[{"position":{"node_id":"8"},"edit":[{"from_length":1,"to_length":1}],"rank":"5"},{"position":{"node_id":"9"},"edit":[{"from_length":19,"to_length":19}],"rank":"6"},{"position":{"node_id":"11"},"edit":[{"from_length":1,"to_length":1}],"rank":"7"},{"position":{"node_id":"12"},"edit":[{"from_length":4,"to_length":4}],"rank":"8"},{"position":{"node_id":"14"},"edit":[{"from_length":1,"to_length":1}],"rank":"9"},{"position":{"node_id":"15"},"edit":[{"from_length":11,"to_length":11}],"rank":"10"}]},"name":"x"}

**Comment by jeizenga** [comment]
Should be fixed now, but let me know if it isn't!

**Comment by ekg** [comment]
FWIW, the new xg index will allow us to store a much larger number of
paths. I haven't tested tens of millions yet but it may be possible.
