### ISSUE TITLE
vg augment - memory usage

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#2385]
Please describe:

1. What you were trying to do

I am trying to augment a graph with pileups from a gam (172Gb) file that contains the following:

```
Total alignments: 835716366
Total primary: 835716366
Total secondary: 0
Total aligned: 810190791
Total perfect: 284122869
Total gapless (softclips allowed): 728077335
Insertions: 116939388 bp in 49147528 read events
Deletions: 171668308 bp in 63548898 read events
Substitutions: 1886158080 bp in 1886158080 read events
Softclips: 2489282608 bp in 75396385 read events
```

The graph looks like this:

```
./vg stats -z -N -E -A test.vg
nodes   68499373
edges   68603230
acyclic
```

Loading the graph roughly consumes ~50Gb.

2. What you wanted to happen

I wanted to get a augmente graph.

3. What actually happened

`vg augment` consumed >768Gb of memory during `Computing pileups` and was killed.

4. What data and command line to use to make the problem recur, if applicable

`augment ref.vg test.gam -a pileup -P test.pileup -S test.support -Z test.trans > test.augmented.vg`

**Comment by ekg** [comment]
Is your graph based on chromosomes? If so, you should do the augmentation
in chunks. Even if it isn't based on chromosomes, it might be best to chunk
and recombine somehow. Glenn might have ideas.

**Comment by fbemm** [comment]
I thought of chunking. The graph itself is not chunked but I could do it. Although I would try to avoid mapping (takes 7-10days). There is no direct way to do that in augment correct?

**Comment by fbemm** [comment]
@ekg @glennhickey Can I use` vg mod -k <Chromosome-Path>` to subset the whole vg to chromosome ones?

**Comment by fbemm** [comment]
That worked:

```
vg mod -k 1 test.vg > test.1.vg
vg paths -L -v test.1.vg
1
```

**Comment by glennhickey** [comment]
`vg mod -k` is only going to keep your reference path, so you will lose variants that were in your graph.  

To keep all the variants, you can use `vg chunk -p 1` with a large context size, say `-c 9999999`.  You can do all your chromosomes in this way by specifying a list with -P.  Use `-g and -a` to chunk up the GAM into chromosomes as well.  

The pileup augmenter usually needs chunks even smaller than a chromosome, though.  If you're going to use it for `vg call`, I strongly recommend just going through toil-vg.

The pileup stuff will soon be deprecated, though.   To augment/call on chromosome sized graphs, you can try going through `vg pack` instead
```
vg augment chr1.vg chr1.gam -A chr1_aug.gam > chr1_aug.vg
vg index chr1_aug.vg -x chr1_aug.xg
vg pack -x chr1_aug.xg -g chr1_aug.gam -o chr1_aug.pack -Q 15
vg call chr1_aug.vg -x chr1_aug.xg -P chr1_aug.pack -r 1 -c 1
```
This will be streamlined and documented in the next release (or so).

**Comment by fbemm** [comment]
@glennhickey Splitting never finished. I constructed per chromosome graphs, merge the id space, and index everything together. Read mappings went fine. Augmenting, indexing of the augmented graph and packing went smoothly as well.

I am stuck at calling now. VG tells me that it is loading the graph and it takes very long (>24h). I assume it is somehow stuck. Is there anything I can do to see what is going on?

**Comment by fbemm** [comment]
Augmenting seems to have worked:

```
Total alignments: 36341324
Total primary: 36341324
Total secondary: 0
Total aligned: 36341324
Total perfect: 13276157
Total gapless (softclips allowed): 33697946
Insertions: 2575025 bp in 1488172 read events
Deletions: 3512036 bp in 1744524 read events
Substitutions: 55959018 bp in 55959018 read events
Softclips: 46317741 bp in 2456706 read events
```

To:

```
Total alignments: 36341324
Total primary: 36341324
Total secondary: 0
Total aligned: 36341324
Total perfect: 36341324
Total gapless (softclips allowed): 36341324
Insertions: 0 bp in 0 read events
Deletions: 0 bp in 0 read events
Substitutions: 0 bp in 0 read events
Softclips: 0 bp in 0 read events
```

**Comment by glennhickey** [comment]
Perhaps `vg call` has run out of memory?  

There also could be an issue computing snarls on the augmented graph.  To check this, you can try splitting it into two commands: `vg snarls chr1_aug.vg > chr1_aug.snarls` and then pass `-g chr1_aug.snarls` to `vg call`. 

Looking up thread, I forgot an important option for `augment`.  Should use `-C` to cut the soft clips.  This is important for computing snarls.  Sorry about that.  I'm working on documentation for this right now as part of #2148, which I hope to get into master today.  The new version should use quite a bit less memory as it doesn't need to load the .vg.  It should also work seamlessly on augmented or non-augmented graphs.

**Comment by fbemm** [comment]
Removing soft clips solved the problem. Thanks a lot @glennhickey.
