### ISSUE TITLE
vg map scoring: additional bonus with paired reads?

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#2407]
Hello,

I am aligning simulated sequencing reads to various graphs. The reads are all 100bp long and I'm using the default scoring for `vg map`:

```
-q, --match INT               use this match score [1]
-z, --mismatch INT            use this mismatch penalty [4]
--score-matrix FILE           read a 5x5 integer substitution scoring matrix from a file
-o, --gap-open INT            use this gap open penalty [6]
-y, --gap-extend INT          use this gap extension penalty [1]
-L, --full-l-bonus INT        the full-length alignment bonus [5]
```

A perfect alignment for a 100bp read should score 105 I would think, but I'm getting a lot of scores of 110. Is the bonus applied twice for aligning paired reads?

**Comment by jeizenga** [comment]
The bonus is applied to both _ends_ of each read in the pair if they don't soft-clip. Perhaps the name "full length bonus" is a little misleading.

**Comment by hgibling** [comment]
I see. Thanks for the clarification!
