### ISSUE TITLE
Can't load version 12 whole genome xg index

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#2455]
I'm trying to load the xg index at /public/home/anovak/build/vg/trash/whole_genome.xg (and s3://vg-k8s/profiling/graphs/whole_genome_graph/whole_genome.xg) which I pulled off of our profiling machine.

VG refuses to load it; it tries to upgrade it in place and throws a bad_alloc during load, and decides that the xg is malformed.

The 1.18.0 release loads this file just fine.

I suspect the new xg submodule.

@ekg Do you know what might be wrong?

**Comment by adamnovak** [comment]
I'm going to replace the S3 file with a new version xg.

**Comment by ekg** [comment]
I believe we made a completely breaking change with xg. I guess the update
path doesn't work correctly. Can you rebuild the index?

**Comment by adamnovak** [comment]
I can, but I don't think we should do a release (in the 1.x series)
that can't read xg indexes written by the last release. So we should
either fix this or rip it out and bump the major version, and provide
a dance to do with the old and new versions to go xg -> vg -> new xg.

**Comment by ekg** [comment]
This involves holding all of the previous xg index data structures in order
to do the upgrade. Maybe we can make a new tool that does this. It would be
easiest to write the xg index to GFA and re-index it.

 I don't think this is a good use of time, and would prefer the effort were
spent on improving documentation for end users. A warning message saying
that this is required should be enough here.

I'm really not sure that this would warrant a new major version. Wouldn't
vgpkg already have implied a need for a new major version?
