### ISSUE TITLE
automatically pruning / making kmer indexing less manual and confusing

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#2461]
New users of vg are often very confused about how and when to apply pruning.

We should try to automate it completely. Bonus points for doing better than we are now using simple kmer enumeration.

Related to this: if the graph has very high degree nodes, pruning itself can fail. This requires stripping the high-degree nodes from the graph. This should also be automated or, ideally, done in a way that preserves paths.

**Comment by jltsiren** [comment]
This is now superseded by #3144.
