### ISSUE TITLE
Illegal cast from istream to bool.

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/vg#247]
-lvcflib -lgssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2 -lgcsa2 -lxg -lsdsl -ldivsufsort -ldivsufsort64 -lrt -lvcfh
src/main.cpp: In function ‘int main_map(int, char**)’:
src/main.cpp:4161:31: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in assignment
                     more_data = std::getline(in,line);

**Comment by ekg** [comment]
Uh oh. That's weird. I guess it should change to something like:

```
std::getline(in, line);
more_data = in.is_good();
```

**Comment by JervenBolleman** [comment]
Its quite wierd, and might have been fixed, I somehow travelled into the git past. I am doing a clean rebuild now.

**Comment by JervenBolleman** [comment]
This is correct today it failed due to a trip into the past on my machine.
