### ISSUE TITLE
sequence length of nodes in vg file

### ISSUE THREAD

**Issue by yangxiaofeill** [vgteam/vg#2486]
Dear colleagues,
I constructed the graph by vg, and convert the vg file to gfa by `vg view` to check the sequence length of nodes in the vg file. I find most of the nodes (without variants) is 32bp length sequence, however a few of nodes with less than 32 bp length sequence. I checked that there are no variants of these nodes. Here are some examples:

```
S	196727	ATAATTAAGCAAAAGGTCTTGAGATGAGATCA	32
S	196728	CCCCGGATTCTCCAGGTGTGTCCTAAATCCTA	32
S	196729	TGACAAGTGTCCTTATAAGAGACAGAAGAGGA	32
S	196730	GAGACACACAGAGGAAGAGGCCTTGTGACCAC	32
S	196731	AGAGACAGACCAGAGTGACGCAGCCACAAGCC	32
S	196732	AAGAAACGTCAAGGAACAGCTGCTGCTCCCAG	32
S	196733	AAGCTGGAAGGGGCAGGGACGGATCCTCCCCT	32
S	196734	GACTTCAGAGGGACCTTGGCCCTGCTGA	28
S	196735	CGCCTTGATTTCAGAATTCTGGCCTCT	27
S	196736	AGAACTGGGGGCGAACAGATGTCTGTTGTTCT	32
S	196737	GAGCCCACCAGAAAGCAATGCCCATTCTCTAC	32
S	196738	AGTACAAAGCTCTGCCAGGCACCACGTGCAAC	32
S	196739	CCGAGGTGAGGTTTCTGTGCCTGCCAGTAGCT	32
S	196740	CCCTGGGCTCTTGACACCGACTGGGATAGTCC	32
``` 

```
S	131185	TAAATAAGACTTGCAATTTTTTTGCTGAAAGG	32
S	131186	CAGACATGATGTGCTGAAGAAAAGGCACTGAG	32
S	131187	CTAAGTGGGTTTTAGTGATGAGATGGTGAGGT	32
S	131188	CAGGGGAGGGGAAGGATTCTATAATCCTGTGA	32
S	131189	GCCAGTCTCAGCCTTTTGGTGGGCCTG	27
S	131190	TGACCCTGGGCTATGAACTTCATCAGT	27
S	131191	GCTTCTAATGGAGCATTTTATATAATATCATT	32
S	131192	CTTCCCTTAGGTGGAAGAGGATGGGGGGTGGG	32
S	131193	GTGGGGAGTACTGGAGTTGGGCATTTCCTTTT	32
S	131194	CCCCAGGCTGATTAGGTTTTGATGAAACCTAT	32
```

I would like to know the principle of setting the sequence length of each node. Could you help me to address this question?

Best
Xiaofei

**Comment by ekg** [comment]
This was determined to be helpful early in the development of vg. It helps for alignment and visualization. It is helpful for performance to not have to make subgraphs that have very large nodes mixed with very small ones. But it is not a requirement, and you can use most vg tools to work on graphs with long nodes. It's just that you won't be able to use the GCSA2 indexing to map against the graph of nodes longer than 1024 bp.

I think you would make such a graph with `vg construct -m 1000000000` or similar. There might be a nicer way to remove the automatic node length limit. 

I now think that we should reconsider this choice. However, we will have to change some aspects of the indexing and the read aligners to make them take substrings of very long nodes that will arise if we don't set a maximum node length.

@jltsiren I was thinking today that for usability and simplicity we should probably move to nodes of arbitrary length. This would probably mean changing the GCSA2 position type to be a 64 bit integer (with 1 bit for orientation) pointing into the concatenated node sequences. It might be a lot of work, but the fact that we chop node sequences up arbitrarily to make the graphs easier to process is a point of incompatibility with the rest of the GFA making world and a violation of user expectations.

**Comment by ekg** [comment]
You can also apply `vg mod -U` to simplify any graph so that unbranching chains of nodes become a single node.

**Comment by glennhickey** [comment]
+1 for longer nodes.  I think that'd speed up a lot of code.  Wonder if
giraffe has any node length expectations?

It is indeed pretty weird that, assuming no variation or path endpoints,
some nodes in the above example have 27bp while most others have 32.  I
think construct uses a windowing scheme to page through batches of sequence
-- perhaps this is an artifact of that?

**Comment by ekg** [comment]
Construct is just making sure that all nodes are <32bp. It's not ensuring
that they have an even length between variants. The algorithm that's used
leads to nodes with shorter lengths.

**Comment by jeizenga** [comment]
FWIW, longer nodes will probably slow down some of the subgraph extraction algorithms that are based on copying, since we'll have to copy the node strings. That said, we could pretty easily expand our collection of handle-based subgraph views to address this problem.

**Comment by jonassibbesen** [comment]
The RNA stuff would also benefit from longer nodes (the search through the haplotypes in the gbwt should be much faster).

**Comment by jltsiren** [comment]
GCSA2 and the minimizer index both use the same 64-bit encoding for positions: 53 bits for node id, 1 bit for orientation, and 10 bits for offset. We can't support arbitrary node lengths, but we could certainly increase the maximum node length to around 30 bits.

Using pointers to concatenated node sequences as positions feels like hack, because it assumes specific implementation choices in the underlying graph. It would also make decoding positions very slow. There would also be a conflict with the GCSA2 data model, which uses 1 bp nodes with integer ids, has no concept of node orientation, and assumes that successive nodes on unary paths have successive ids. We could not use the low-order bit for orientation, because it would violate the last point, and the high-order bit would probably cause issues due to excessively large node ids.

Another issue is `get_sequence()`. It would become a dangerous operation, as it's the easiest way to access the sequence, but it can require excessive amounts of time and memory with large nodes.

**Comment by jeizenga** [comment]
There's also `get_subsequence` and `get_base` as alternatives for long sequences.

**Comment by jltsiren** [comment]
GCSA2 and the minimizer index now support changing the maximum node length. Any change will break compatibility with existing indexes.

I think 2^31 bp is the maximum node length we can support with the current approach. A whole-genome TOPMed graph would have around 2^31 nodes, and unfolding the complex regions will create a fair number of duplicates, so we need at least 33 bits for node id and orientation.
