### ISSUE TITLE
Rename option in vg construct

### ISSUE THREAD

**Issue by RicciAle** [vgteam/vg#2493]
Hello! I do not understand how to properly use the option 
```
-v V=F
```
in the vg construct command. Can you please help me?
Thank you in advance!
Alessandro

**Comment by jltsiren** [comment]
VG construction uses the contig names found in the VCF file. If the contig names are different in the reference, they can be translated using the `-n` option. For example, if the VCF contig name is chr17 and the corresponding reference contig name is NC_000017.11, the construction command could be:

```
vg construct -r reference.fa -v chr17.vcf.gz -R chr17 -C -n chr17=NC_000017.11 > chr17.vg
```

**Comment by RicciAle** [comment]
Perfect!
I wanted to tell you that, if I execute the command
```
vg construct -p -C -R chr1 -r hg38.fa -v ALL.wgs.shapeit2_integrated_snvindels_v2a.GRCh38.27022019.sites.vcf.gz -n 1=chr1 > chr1.vg
```
on this fasta: ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
and on this vcf: wget http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/ALL.wgs.shapeit2_integrated_snvindels_v2a.GRCh38.27022019.sites.vcf.gz

the resulting vg occupies ~ 145 MB, whereas if I modify the vcf file (I know, it's a dangerous move to make for the fact that I modify fundamental information) and apply the command above without the option, the resulting vg occupies ~ 322 MB; thus, I'm afraid to lose some information about the contigs.

**Comment by jltsiren** [comment]
The key is the `-R` option. You should use the contig name from the VCF file, not from the reference.
