### ISSUE TITLE
Tool/API to efficiently estimate read depth

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2511]
I'd like to estimate the sequencing depth from a given GAM file.  A notion of the expected coverage is sorely lacking from `vg call`, and it will be important for `vg augment` soon too.  

Average coverage is easily obtained from BAMs, and can be broken down by contig (`samtools idxstats, depth etc`).   But on a graph, it's a harder problem.  In fact, I don't think we have any way to get contig depth right now, beyond chunking up the graph and gam by chromosome.  And even computing the depth then isn't so straightforward.  One way would be to sum up the base coverages from `pack -d`, then divide by the total length of reference paths as extracted from `paths -E`.

So I think we need something like `vg depth <pack file> <path names>` (or add to `stats`?) that uses context expansion to sample a few subgraphs from each path and compute depth across those (as described above).  It could also accept an indexed GAM as input.  Would be nice to run on non-indexed GAM but I'm not sure that's doable (maybe it just makes a pack on the fly in this case).

**Comment by ekg** [comment]
Let the vg monolith/ecosystem grow. This is a great idea!

Let's add `vg depth`, not add to stats.
