### ISSUE TITLE
Extracting haplotypes for simulation

### ISSUE THREAD

**Issue by cademirch** [vgteam/vg#2513]
I am trying to extract particular haplotypes from my gbwt index to simulate reads from. However I am confused by the process as well as the outputs from my testing. A reference and phased VCF was used for graph construction input. 

```
vg construct -r ref.fa -v phased.vars.vcf.gz -a -t 32 > sim_base.vg
vg index -x sim_base.xg -G sim_base.gbwt -v phased.vars.vcf sim_base.vg
```
Checking the threads in the gbwt outputs 14 threads, which I expect. 
```
vg paths -G sim_base.gbwt -L
_thread_ZI284_NC_004353.4_0_0
_thread_ZI284_NC_004353.4_1_0
_thread_ZI284_NC_004354.4_0_0
_thread_ZI284_NC_004354.4_1_0
_thread_ZI284_NC_024512.1_0_0
_thread_ZI284_NC_024512.1_1_0
_thread_ZI284_NT_033777.3_0_0
etc...
```
I tried this command (from #2427) to read the threads into a graph
`vg augment -B sim_base.vg  <(vg paths -x sim_base.xg -g sim_base.gbwt -X ) >sim.haps.vg
`
The resulting graph has the 14 as threads expected but many unexpected _alt paths ~2 million.
```
vg paths -v sim.haps.vg -L 
_thread_ZI284_NT_033777.3_1_0
_thread_ZI284_NT_033778.4_0_0
_thread_ZI284_NT_033778.4_1_0
_thread_ZI284_NT_033779.5_0_0
_thread_ZI284_NT_033779.5_1_0
_thread_ZI284_NT_037436.4_0_0
_thread_ZI284_NT_037436.4_1_0
_alt_fffff3756108af85d98d8a73881b628a05427fc9_0
_alt_fffff3756108af85d98d8a73881b628a05427fc9_1
_alt_fffff52b1962983f3f2e09c66645527c13f6430b_0
_alt_fffff52b1962983f3f2e09c66645527c13f6430b_1
_alt_fffff8679092e32b14416a8e625267ef599460c2_0
_alt_fffff8679092e32b14416a8e625267ef599460c2_1
etc...
```
What are these alt paths? And how can I get just the haplotypes from my sample so that I can simulate only from my sample?

 I am also a little confused on the difference between what a thread is and what a path is in the context of a variant graph, could someone clarify? Is a thread just a path that represents a haplotype? 

Thanks,
Cade

**Comment by jltsiren** [comment]
The alt paths were created by the `-a` option of `vg construct`. There is a path for each allele of each variant, and they are used for building the GBWT. Right now we don't have a direct way of removing the alt paths. You can do it by converting the XG index into a VG graph (`vg convert graph.xg > graph.vg`), and then you can use that graph in `vg augment`.

A path is defined both as a sequence of nodes and as a nucleotide sequence. It can start/end in the middle of a node, and we can use coordinates in either sequence meaningfully. Depending on the graph implementation, it may also be possible to jump directly into specific coordinates of a specific path.

In contrast, a thread is a lightweight path that is only defined as a sequence of nodes. We can store a huge number of threads space-efficiently, but they always consist of entire nodes and the coordinates are only defined in terms of nodes. Jumping into specific coordinates of a specific thread is not possible. We can only start from the beginning/end of a specific thread, or we can jump into a node and start traversing any threads visiting it without knowing the coordinates of the node in the threads.

**Comment by cademirch** [comment]
Thank you @jltsiren, this worked. Is there a way to extract only 1 out of my 14 haplotypes for simulation? I would like to simulate reads only from my haplotype threads, not the reference paths. 

Also, where does `vg sim` simulate from? Are reads simulated from randomly chosen paths in the graph? 

Thank you,
Cade

**Comment by jltsiren** [comment]
You can use option `-P` in `vg sim` to simulate reads from specific paths. Without it, the simulated reads can be from anywhere in the graph.

**Comment by ekg** [comment]
The problem is that we need to extract GBWT haplotypes as paths and put
them into another graph.

This used to be possible. How does it work now?

**Comment by jltsiren** [comment]
The best option seems to be extracting the paths as GAM and adding them with `vg augment -B`.
