### ISSUE TITLE
static build broken on Linux in current HEAD

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#252]
I guess there are incompatibilities with raptor's curl and the other curl. @JervenBolleman says he's got a patch coming.

```gcc
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libraptor2.a(raptor_www_curl.o):(.text+0x2be): more undefined references to `curl_easy_setopt' follow
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libraptor2.a(raptor_rss_common.o): In function `raptor_rss_field_conversion_date_uplift':
(.text+0x870): undefined reference to `curl_getdate'
```

**Comment by JervenBolleman** [comment]
no no, I am saying that I am putting apt get install raptor in the makefile getdeps target.

**Comment by JervenBolleman** [comment]
I suspect the solution is to make raptor/librdf a deps in the git submodule sense.
I can't do this on my work machine (autotoos to old...) but will try to do so on my mac.

**Comment by JervenBolleman** [comment]
I have made progress on this see [jervenbolleman/vg/raptor](https://github.com/JervenBolleman/vg/tree/raptor) but can't quite test it on my Cent-OS 7 box due to missing libbzp2 and libjansson static compiled libs in the default rpm repo.

**Comment by JervenBolleman** [comment]
Looks like raptor head has the same problem with the libcurl in ubuntu trusty. Meaning that adding raptor as a dependecy/submodule does not help.

**Comment by ekg** [comment]
I'm stuck now building on an older fedora system due to raptor. I'm not
sure what to do. It sounds like it'd be easiest to pull in your build
script. Then I can at least build the dynamic executable on the linux box.
Static binaries are a nice feature but building is an absolute essential.

**Comment by ekg** [comment]
I'm pulling in your changes here: #257

**Comment by ekg** [comment]
The raptor interface gets described by removing -lraptor2 from my libs and attempting to build static:

```
➜  vg git:(master) ✗ make static
g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -o bin/vg obj/main.o obj/gssw_aligner.o obj/vg.o cpp/vg.pb.o obj/index.o obj/mapper.o obj/region.o obj/progress_bar.o obj/vg_set.o obj/utility.o obj/path.o obj/alignment.o obj/edit.o obj/sha1.o obj/json2pb.o obj/entropy.o obj/pileup.o obj/caller.o obj/position.o obj/deconstructor.o -static -static-libstdc++ -static-libgcc -I/home/erik/vg/include -I. -I/home/erik/vg/src -I/home/erik/vg/cpp -I/home/erik/vg/include/dynamic -ggdb -L/home/erik/vg/lib -lvcflib -lgssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2 -lgcsa2 -lxg -lsdsl -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lrt
/home/erik/vg/lib/libhts.a(knetfile.o): In function `socket_connect':
/home/erik/vg/deps/htslib/knetfile.c:98: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
obj/vg.o: In function `vg::VG::from_turtle(std::string, std::string, bool)':
/home/erik/vg/src/vg.cpp:2617: undefined reference to `raptor_new_world_internal'
/home/erik/vg/src/vg.cpp:2623: undefined reference to `raptor_world_open'
/home/erik/vg/src/vg.cpp:2632: undefined reference to `raptor_new_parser'
/home/erik/vg/src/vg.cpp:2638: undefined reference to `raptor_parser_set_statement_handler'
/home/erik/vg/src/vg.cpp:2642: undefined reference to `raptor_uri_filename_to_uri_string'
/home/erik/vg/src/vg.cpp:2643: undefined reference to `raptor_new_uri'
/home/erik/vg/src/vg.cpp:2644: undefined reference to `raptor_new_uri'
/home/erik/vg/src/vg.cpp:2647: undefined reference to `raptor_parser_parse_file'
/home/erik/vg/src/vg.cpp:2649: undefined reference to `raptor_free_uri'
/home/erik/vg/src/vg.cpp:2650: undefined reference to `raptor_free_uri'
/home/erik/vg/src/vg.cpp:2651: undefined reference to `raptor_free_parser'
/home/erik/vg/src/vg.cpp:2652: undefined reference to `raptor_free_world'
obj/vg.o: In function `vg::triple_to_vg(void*, raptor_statement*)':
/home/erik/vg/src/vg.cpp:2569: undefined reference to `raptor_term_to_string'
/home/erik/vg/src/vg.cpp:2570: undefined reference to `raptor_term_to_string'
/home/erik/vg/src/vg.cpp:2571: undefined reference to `raptor_term_to_string'
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'static' failed
make: *** [static] Error 1
```

**Comment by ekg** [comment]
I think I've got this implemented at the current master HEAD. It's running through tests now.

**Comment by ekg** [comment]
I've failed. Looks like the linux build makes it further (bison gets installed, but isn't on brew apparently).

https://travis-ci.org/vgteam/vg/jobs/115990411#L4119-L4145

Basically, we get a really weird message like:

```
raptor_new_world() called via header from version 20013 but minimum supported version is 20016
```

Somehow we're not linking against libraptor2 right?

**Comment by adamnovak** [comment]
You forgot to copy the Raptor headers for the Raptor that VG builds, so the (too old) system Raptor headers are being used with the built Raptor library.

https://github.com/vgteam/vg/blob/master/Makefile#L135-L136

**Comment by ekg** [comment]
@adamnovak Just caught that and it's building now in #258
