### ISSUE TITLE
get_haplotypes_with_snarl() in phased_genome.cpp might have a bug

### ISSUE THREAD

**Issue by code-s-witch** [vgteam/vg#2529]
**1. What were you trying to do?**
```vector<int64_t> haplos_pass_snarl = genome.get_haplotypes_with_snarl(&snarl);```

**2. What did you want to happen?**
I expect to receive a vector<int> including haplotype ids that pass through snarl

**3. What actually happened?**
I got an empty vector 

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**
relevant files:
```vg/mcmc.sh```
```vg/subcommand/mcmc_main.cpp``` (calls mcmc_caller)
```mcmc_caller.cpp ```(line 130 calles get_haplotypes_with_snarl())
**6. What does running `vg version` say?**
There is no error message but I am expecting a non_empty vector 
I test the snarl and haplotypes using:

```
genome.print_phased_genome();
cerr << snarl.start() <<endl;
cerr << snarl.end() << endl;
```
OUTPUT:
```
Haplotype ID is: 1
node ID is 1
The sequence is: CAAATAAG
node ID is 3
The sequence is: G
node ID is 5
The sequence is: C
node ID is 6
The sequence is: TTG

(Similar ouput for haplo id 2)

1 fwd
6 fwd
```
This leads me to believe I should get a vector<int64_t> with ids:0,1
because both haplotypes pass through snarl starting in 1 and ending in 6

**Comment by code-s-witch** [comment]
Branch: https://github.com/code-s-witch/vg/tree/susanna 
Commit : 441e6d7276aa2da4a4730bbcab59226621f7dd0b

I also noticed that the mcmc.sh is not on the remote branch. I will copy/paste below:
``` 
set -ex

# Index a couple of nearly identical contigs
./bin/vg construct -m 1000 -a -r test/small/x.fa -v test/small/x.vcf.gz >x.vg
./bin/vg  index -x x.xg -g x.gcsa -v test/small/x.vcf.gz --gbwt-name x.gbwt -k 16 x.vg

# simulate reads
./bin/vg sim -l 100 -n 100 -e 0.1 -i 0.1 -a -x x.xg > reads.gam

# make the snarls file
./bin/vg snarls x.vg > sites.snarls

# This read is part ref and part alt which matches a haplotype on X, but is possible on Y as well.
./bin/vg mpmap -A -x x.xg -g x.gcsa -G reads.gam > reads.mgam

# call mcmc subcommand
./bin/vg mcmc reads.mgam x.vg sites.snarls > graph_with_paths.vg

```

**Comment by jeizenga** [comment]
Okay, I had a little time to look at this, and I've more or less diagnosed the problem. It occurs here: 
https://github.com/vgteam/vg/blob/master/src/mcmc_genotyper.cpp#L112
The issue is that the `PhasedGenome` does not seem to have a valid move operator--probably something to do with the custom linked lists in there. I don't know yet what's invalid about it, but I have to do some other stuff today. I'll eventually get around to looking at this, but I'll leave this here in case you want to try your hand at fixing it without me before then.

**Comment by code-s-witch** [comment]
Hi Jordan,

I'm dedicating all of today to vg. I'll look at the bug and try to fix it.

Best,
Susanna

**Comment by code-s-witch** [comment]
Not a bug.
