### ISSUE TITLE
Dockerfile build error: "sed: can't read deps/sdsl-lite/CMakeLists.txt: No such file or directory"

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#2545]
Hi there

Looks like I got an error trying to build the image directly from the Dockerfile in this repo. I'm simply running `$ docker build .` in a subdirecotry with the following Dockerfile: https://github.com/vgteam/vg/blob/master/Dockerfile

Here is the error:

```
Step 12/29 : RUN sed -i s/march=native/march=nehalem/ deps/sdsl-lite/CMakeLists.txt
 ---> Running in d255a700f65c
sed: can't read deps/sdsl-lite/CMakeLists.txt: No such file or directory
The command '/bin/sh -c sed -i s/march=native/march=nehalem/ deps/sdsl-lite/CMakeLists.txt' returned a non-zero code: 2
```

I'm attaching the full output I received running the command. 
[dockerfile_build_output24Nov2019.txt](https://github.com/vgteam/vg/files/3884250/dockerfile_build_output24Nov2019.txt)

Naturally, it's very possible I'm misunderstanding something---I'm not sure if this Dockerfile is "the correct" Dockerfile to use. I ran into other problems here: 
https://github.com/vgteam/vg_docker/issues/15

Thank you for the help, and thanks to the entire vg team!

Best, Evan

**Comment by adamnovak** [comment]
Did you do this from a fresh clone?

In that case, you need to either clone with `git clone --recursive`, or run `git submodule update --init --recursive` inside the repo after it is cloned. If you don't do that, the code for the vendored dependency submodules won't be on disk when the Dockerfile tries to copy it into the container, and so vg won't be able to build inside its container because it doesn't have its submodules.

**Comment by adamnovak** [comment]
The Dockerfile in this repo probably is the Right Dockerfile now; we're now using it for our release Dockers instead of vg_docker.

**Comment by evanbiederstedt** [comment]
Thanks for the help @adamnovak 

> The Dockerfile in this repo probably is the Right Dockerfile now; we're now using it for our release Dockers instead of vg_docker.

Excellent, this clarifies things for me. 

> Did you do this from a fresh clone?

Nope, that's my problem. :) Apologies for the run around. 

If you build the Dockerfile in the repo, it appears to work (though I haven't tried it from start to finish, as it does take a great deal of time). 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
For future reference (if only for myself):

My confusion here was that I was trying to use the Dockerfile to build an image of a specific vg release, e.g. https://github.com/vgteam/vg/tree/v1.20.0 via the tarball/zip. 

It's easier simply to clone the specific version with `--recursive` so that the necessary submodules exist

**Comment by adamnovak** [comment]
The tarball we manually make and upload with the release is *supposed*
to include all the submodules. The Github-made zip will not.

**Comment by evanbiederstedt** [comment]
> The Github-made zip will not.

Ah, that could have been my mistake then!

I appreciate the help @adamnovak
