### ISSUE TITLE
performance regression / infinite loop mapping unitigs in v1.4.0

### ISSUE THREAD

**Issue by mlin** [vgteam/vg#255]
Spent a little time today with v1.4.0 after a lengthy hiatus. My [automatic test workflow](https://github.com/dnanexus-rnd/dxvg/blob/master/run_tests.py#L53) builds a 1000G graph for chromosomes 21 and Y and then maps some unitigs to it (N50 around 800bp). The mapping used to run quickly (<1min), but it's now been spinning all its threads (8) for 36h...

Tarball of the graph and indices (658MiB): https://dl.dnanex.us/F/D/KjjK6fpFxPKyzZp4ybXQBK4V7q9VjvB4VP1GzGZ4/hs37d5.vg.index_l16e3l100k16F.tar
Unitigs (15MB): https://dl.dnanex.us/F/D/QY2xb6j2JP67QK20JPXBj82J8v62XP2KZzF1y0qQ/HS1011_unitigs_Y.fastq.gz

Mapping incantation:
```
vg map -f reads.fastq.gz -g vg/index.gcsa -x vg/index.xg -t 8 -k 27 -GFX 1.5 -T 50 -l 12 -S 5
```
I separately mapped some short reads to the same graph/index which seemed to go fine...

**Comment by ekg** [comment]
Uh oh. What about the current HEAD? The mapper is rebuilt around MEMs in
this version.

**Comment by mlin** [comment]
OK- tried but semi-blocked on #252, will give that a little time to bake

**Comment by ekg** [comment]
I'm seeing poor performance on my end too for long read mapping. I'm perplexed. It looks like very bad CPU utilization but also seems to have slowed down dramatically relative to the kmer mapper. Looks like we're almost done with the static build stuff blocking #252, so we can check soon if this is the same problem.

**Comment by mlin** [comment]
Update: I upgraded to 435c97c successfully. There is some improvement in that:

- with v1.4.0 the unitig mapping (only 15MB input) didn't complete in any reasonable amount of time -- I killed it after days
- with 435c97c it finished in roughly an hour
- but in prior versions where I'd developed this test it was <1min.
