### ISSUE TITLE
Return reference calls with `vg calls`

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#2551]
**1. What were you trying to do?**

I want to call (& genotype) with so that my final calls contain reference calls.

**2. What did you want to happen?**

The "hoped" that output VCF from either `vg call` or `vg genotype` contains 0/0 calls,

**3. What actually happened?**

With:

```
vg call -t $CPU $BSE/$BSE.aug.xg -k $BSE/$BSE.aug.pack -s $BSE > $BSE.vcf
```
0/0 genotypes are missing as expected. The option to add them was removed.

With:

```
./vg genotype -p -t $CPU -v -r $BSE.CTG1" -V $BSE.vcf -E -G $BSE.augmented.filtered.gam $BSE.augmented.vg > $BSE.recall.vcf
```

The input VCF to `vg genotype` is the output VCF from `vg call`. The graph was constructed with minigraph/seqwish.

I get 0/0 genotypes but the process takes up to 256Gb of memory for a single path on a rather small graph.

**6. What does running `vg version` say?**

```
vg: variation graph tool, version v1.20.0 "Ginestra"
```

**Comment by fbemm** [comment]
https://www.biostars.org/p/405182/#410024

**Comment by fbemm** [comment]
Would it be more memory efficient to built a reads.index?

**Comment by ekg** [comment]
It's not straightforward to do this on a graph.

**Comment by fbemm** [comment]
Ok. I thought that is done based on the GAM file.

**Comment by ekg** [comment]
Sorry, I'm not being clear. There is an indexing function but it depends on
the graph being mostly linear. This is usually the case even for whole
genome alignment graphs. However, the incompleteness of this and the cost
of extracting alignments from such a structure have motivated the
development of coverage based indexes (the pack format).

I'm off on a tangent :)

**Comment by fbemm** [comment]
So for now I provide the GAM and a path to not blow up genotype.

**Comment by glennhickey** [comment]
As you've seen, `vg genotype` scales very poorly with graph size.  This is due in large part to the limitations of GAM that Erik points out.  At this point `vg call` is several orders of magnitude more efficient.  I have a branch somewhere with the makings of a faster `genotype` in it.  I hope to one day incorporate some of these ideas into `call`, but I don't think it's feasible until we replace GAM as a format. 

Anyway, apart from GAM, one of the challenges in general of calling on the graph is that large sites can have millions of possible alleles.  So what does a 0/0 call look like in VCF here?  That's one of the reasons `vg call` only gives 0/0 when given a VCF input.

I will implement an option in `call` that will return the first `K` possible alleles or something, but it won't be exhaustive.  Similar functionality exists now in `vg decsontruct`.  You can use it get all the sites in your graph in VCF format.  But for complex sites, it works better with the `-e` option to only consider alleles that correspond to embedded paths in the graph.

**Comment by fbemm** [comment]
OK got it. Thanks for the explanation. So I guess constructing a graph from the vg-VCF again and call with that could give me what I want for now.

**Comment by fbemm** [comment]
@glennhickey, the `K` option never made it into vg correct?
