### ISSUE TITLE
mapping qualities

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#26]
We need mapping qualities. They can perhaps be estimated by looking at the size of the kmer space of the read vs. the kmer space of the entire index. A more nuanced approach is to build a ML model that calculates mapping accuracy given some parameters we can extract from the alignment (akin to Mosaik). But simple may be enough in this case.

**Comment by edawson** [comment]
*bump* Don't we have mapping qualities now?

**Comment by adamnovak** [comment]
We do indeed have mapping qualities now.
