### ISSUE TITLE
mpmap is seg faulting 

### ISSUE THREAD

**Issue by code-s-witch** [vgteam/vg#2604]
**1. What were you trying to do?**
```
./bin/vg mpmap -A -x x.xg -g x.gcsa -t 1 -G reads.gam > reads.mgam
```

**2. What did you want to happen?**
```
create reads.mgam file
```

**3. What actually happened?**
```
Segmentation Fault
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
[mpmap_bt.txt](https://github.com/vgteam/vg/files/4056480/mpmap_bt.txt)
```

**5. What data and command can the vg dev team use to make the problem happen?**
```
working directory in Courtyard: /public/home/sumorin/vg
Relevant files: 
/public/home/sumorin/vg/1kg_hg19-CHR21.vcf.gz
/public/home/sumorin/vg/1kg_hg19-CHR21.vcf.gz.tbi
/public/home/sumorin/vg/CHR21.fa
```
```
[script.txt](https://github.com/vgteam/vg/files/4056500/script.txt)
```
**6. What does running `vg version` say?**

```
vg version v1.17.0-1188-ga9f34a2c1 "Candida"
Compiled with g++ (GCC) 8.1.0 on Linux
Linked against libstd++ 20180502
Built by sumorin@courtyard
```

**Comment by jeizenga** [comment]
I think I've fixed this bug, but it also looks to me like you are using simulated reads from a different graph. That might cause you other issues as well.
