### ISSUE TITLE
Generate GCSA index for CACTUS whole genome alignments

### ISSUE THREAD

**Issue by RenzoTale88** [vgteam/vg#2612]
Hi again,
sorry to keep opening issues, I come across different problems in different works I'm running and It's just easier to keep trace by separating them in multiple issues.
I've generated whole genome alignments for two small assemblies (~250Mb each). I got the hal file of the whole genomes, including the small contigs, that I'd like to convert into a vg format for downstream analyses.
I proceeded analogously to the wiki:
```
vg mod -x 32 alignments.hal | vg ids -s - > alignments.vg
vg index -x alignments.vg > alignments.xg
vg ids -m mapping alignments.vg
vg prune -t 4 -u -a -m mapping alignments.vg> alignments.pruned.vg
vg index -p -Z 1536 -t 4 -g alignments.gcsa -f mapping alignments.pruned.vg
```

All the steps worked just fine, with the exception of the last, which returned the following error:
```
...
PathGraph::prune(): 703384902 -> 680206629 paths (609487611 ranges)
PathGraph::prune(): 578755193 unique, 0 redundant, 81621796 unsorted, 19829640 nondeterministic paths
PathGraph::prune(): 24.8592 GB in 1 file(s)
PathGraph::read(): File 0: Read 680206629 order-128 paths
PathGraph::extend(): File 0: Created 12129827405 order-256 paths
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_XT3U91/stacktrace.txt
Please include the stack trace file in your bug report!
```

Below attached the stacktrace. Thanks you in advance

Andrea

[stacktrace_17012020.txt](https://github.com/vgteam/vg/files/4077519/stacktrace_17012020.txt)

**Comment by jltsiren** [comment]
In the last extension step, GCSA construction created over 12 billion path objects. Loading them into memory would probably take at least 0.5 TB, which you didn't have, so the construction crashed.

You can probably index the graph by pruning it more aggressively. Either increase the kmer length in `vg prune` from the default 24 or reduce the edge max from 3.

**Comment by ekg** [comment]
You might also need to remove high degree nodes, if there are some. vg mod -D I think.

**Comment by jltsiren** [comment]
`vg prune` will also remove high-degree nodes with option `-M`. It's not on by default, because I'm not sure if if's a good idea or what the threshold should be.

**Comment by RenzoTale88** [comment]
Hi again, thank you for the suggestions! I've doubled the kmer size for the pruning (-k 48). Is it too much? Will this affect somehow all the downstream analyses?
Thank you again!

**Comment by jltsiren** [comment]
I've never tried that high values of k for pruning. If it works, it's probably fine, but I'm not sure if anyone has ever investigated the effects of pruning for downstream analyses. On the other hand, sometimes there are simply too many k bp paths for large values of k in the graph, and pruning may take a long time, because it has to enumerate the paths.
