### ISSUE TITLE
Include VCF allele information in constructed graphs

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#262]
This is basically what we wanted to do in #176. Now that we have code in that can include whole phase paths, it shouldn't be too hard to include per-allele path threads as well.

This combined with a prototype VCF-to-xg-thread importer could be a quicker way to get my gPBWT code to a testable state than taking on #261 right away.

**Comment by ekg** [comment]
What kind of a design were you considering for the importer? Would you run
through each haplotype stored in the VCF to do the import, using the stored
paths to concatenate up the thread, then pass that to gPBWT?

**Comment by adamnovak** [comment]
Yes, that's basically the idea. There needs to be some logic to emit
mappings to intervening reference sequence and to break the thread up at
contradictory or unphased variants, but I want to run through all the
haplotypes in the VCF while having access to the completed graph and the
variant embeddings, to make my life easier.
