### ISSUE TITLE
reading and writing the same RDF

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#264]
Is there any reason for vg to be able to read and write the same RDF format? We output turtle and read N-tuples.

@nerdstrike, @JervenBolleman, @ktym, I'm not sure if this matters for vg's usability. Is this worth fixing?

**Comment by JervenBolleman** [comment]
um, VG reads turtle. but that means automatically you read N-Triples as well. (Turtle being abbreviated N-Triples). As long as we use raptor you could read most RDF formats. Could be worth making that an option in the view code. For now we only write Turtle, but if we change that code to use Raptor too we could write the other formats as well.

**Comment by JervenBolleman** [comment]
Closed it because we do read the same RDF that VG writes.

**Comment by ekg** [comment]
OK! So the documentation confused me. Apologies and thanks :)
