### ISSUE TITLE
Feature request: vg deconstruct to output VCF with per-strain allele counts

### ISSUE THREAD

**Issue by nh13** [vgteam/vg#2724]
Related to: https://github.com/vgteam/vg/issues/2723

I am trying to create a VCF from an assembly graph using `vg deconstruct` for [COVID-19](https://workbench.lugli.arvadosapi.com/collections/lugli-4zz18-xdihpa8nzv906l8):

```
vg view -F SARS-CoV-2.genbank.20200329.complete.gfa --vg > SARS-CoV-2.genbank.20200329.complete.vg
vg deconstruct -p NC_045512 SARS-CoV-2.genbank.20200329.complete.vg > SARS-CoV-2.genbank.20200329.complete.vcf
```
The output VCF is a site-only VCF, with no samples.   

1. It would be nice to know in the INFO field, how many strains as input to the graph assembly have each allele (i.e. INFO.AD and INFO.DP fields).  
2. It would be nice to have a per-strain "SAMPLE" with the genotype at that site for the given strain.

Many folks are stuck in the VCF work (clinical space!), so this would be immensely helpful.  This came from a [discussion](https://twitter.com/erictdawson/status/1247935750546612226?s=20) with @ekg and @edawson elsewhere.

**Comment by nh13** [comment]
Could this be accomplished by?
1. align each strain to the graph: `vg map`
2. compute the "read support" (one read per strain) `vg pack...`
3. call a VCF from the support: `vg call...`

- [FASTA for all strains](https://workbench.lugli.arvadosapi.com/collections/lugli-4zz18-h5cm69e8xg0q54v)

**Comment by glennhickey** [comment]
If your samples are represented as paths in the GFA, then you should be
able to get them as samples in the VCF by using the -e option to vg
construct.  Otherwise, if you have reads for each sample, you can certainly
make a vcf with map/pack/call.

**Comment by nh13** [comment]
`vg deconstruct -e` solves this feature request.  Thank-you @glennhickey
