### ISSUE TITLE
Suspicious condition

### ISSUE THREAD

**Issue by maddin200** [vgteam/vg#2732]
/src/cluster.cpp line 3131
Code:
hit_node_2.mem->begin >= hit_node_1.mem->begin && hit_node_2.mem->begin < hit_node_1.mem->begin

Maybe  ->end the correct statement ?

**Comment by jeizenga** [comment]
Good catch, thanks! This is a bug that only affects speed, not accuracy, which is probably why it went unnoticed. I'll tag a fix onto my next PR.
