### ISSUE TITLE
Off-by-one error when annotating a graph / extracting annotated path

### ISSUE THREAD

**Issue by LilithElina** [vgteam/vg#2749]
**1. What were you trying to do?**
I have a genome graph based on five bacterial genomes and added the annotation for all five into the graph so I can extract single genes of interest.

**2. What did you want to happen?**
I wanted to extract fasta sequences of a certain gene.

**3. What actually happened?**
The fasta sequences are missing the first nucleotide if the gene of interest is located on the plus strand.

**5. What data and command can the vg dev team use to make the problem happen?**
I annotated the graph like this:

```
vg annotate -x graph.xg -f annotations/annotation.gff > annot_graph.gam
vg augment graph.vg -i annot_graph.gam > annot_graph.vg
vg index -x annot_graph.xg annot_graph.vg
```

Then I use `vg paths` to extract the sequences:

```
vg paths -x annot_graph.xg -F -Q "gene_name"
```

If you need to directly recreate these steps, the annotation and the graph can be found [here](https://drive.google.com/file/d/1_A2TIjhjJkRkU32w4494JtYHaJGFL1H_/view?usp=sharing) and [here](https://drive.google.com/open?id=15S15lNZEP10pEcbeF5_2TyOv-rmHF7D_), respectively.

The commands to use then are:

```
vg index -x FivePsae_new.xg FivePsae_new.vg
vg annotate -x FivePsae_new.xg -f PseudomonasAnnotationAll.gff > FivePsaeAnnotAll_new.gam
vg augment FivePsae_new.vg -i FivePsaeAnnotAll_new.gam > FivePsaeAnnotAll_new.vg
vg index -x FivePsaeAnnotAll_new.xg FivePsaeAnnotAll_new.vg
vg paths -x FivePsaeAnnotAll_new.xg -F -Q "dnaA"
```

And here is the link to an example sequence for comparison: [dnaA in PAO1](http://pseudomonas.com/feature/show/?id=134012&view=sequence)

**6. What does running `vg version` say?**

```
vg version v1.22.0 "Rotella"
Compiled with g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609 on Linux
Linked against libstd++ 20160609
Built by spo12@CPI-SL64001
```

**Comment by LilithElina** [comment]
Addition: if the gene is located on the minus strand, the last nucleotide is missing.

**Comment by jonassibbesen** [comment]
Hi, thanks for posting. I will look into this issue. As an alternative you can also try `vg rna` which can parse a gtf/gff file and add the annotation to a graph in a single step.

**Comment by LilithElina** [comment]
Cool, thanks!
