### ISSUE TITLE
VG will happily emit enormous chunks

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#278]
I tried to build a flat (i.e. no variation) vg graph for chimp.

```
wget http://hgdownload.cse.ucsc.edu/goldenPath/panTro4/bigZips/panTro4.fa.gz
gunzip panTro4.fa.gz
vg construct -r panTro4.fa -p > panTro4.vg
```

A vg graph comes out, but when I go to read it, vg complains.

```
vg stats -zNE panTro4.vg 
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:569] Reading dangerously large protocol message.  If the message turns out to be larger than 67108864 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 67108864
^C
```

VG shouldn't emit chunks that are too big to read back in.

**Comment by ekg** [comment]
We should set a maximum node size for all graphs that are constructed. 1024
is a nice size, and friendly with GCSA.

**Comment by adamnovak** [comment]
Yes, I think the problem is enormous nodes; I'm running again with -m 100
to see if that fixes it.

**Comment by adamnovak** [comment]
Trying -m 100 seems like a no-go. It sat overnight and is still 0% on "constructing graph", whereas without that it tool less than an hour to build.

It might be that nodes are being broken off inefficiently.

**Comment by ekg** [comment]
That's weird. Try -m 64 or -m 32.

**Comment by adamnovak** [comment]
It's because dice_nodes is O(n^2), since you break off the front of a node, then break off the front of the remainder, and so on, copying the remainder each time.

I'm switching over to an implementation that's O(n log n), based on breaking nodes in half when they are too long instead. I'll PR that in a bit; it seems to solve the problem.

**Comment by ekg** [comment]
Pleas do, makes sense to me.

**Comment by adamnovak** [comment]
I wrote a smarter chunker a while back; this should no longer happen.
