### ISSUE TITLE
Signal 11 error with vg deconstruct

### ISSUE THREAD

**Issue by drpatelh** [vgteam/vg#2790]
**1. What were you trying to do?**

Hi! I am persistently getting the error below for selected samples. We are using `vg` within the [nf-core/viralrecon](https://github.com/nf-core/viralrecon) pipeline in conjunction with `minimap2` and `seqwish` to call variants in de novo assemblies. The error is below:

```
ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_VLbZcK/stacktrace.txt
Please include the stack trace file in your bug report!
```

**2. What did you want to happen?**

See point 1

**3. What actually happened?**

It appears that the `vg deconstruct` command is failing because the output `vcf` file is empty i.e. `sample1.NC_045512.2.vcf.gz`

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

Sorry, that would have been created on one of the nodes on our cluster and I no longer have access to the file because it has most likely been deleted.

**5. What data and command can the vg dev team use to make the problem happen?**

All of the files required to reproduce the error are in the attached `tar` archive.

The commands used are in `command.sh` and the error trace is in `command.err`.

[VG_FAIL.tar.gz](https://github.com/vgteam/vg/files/4621796/VG_FAIL.tar.gz)

**6. What does running `vg version` say?**

```
vg version v1.23.0 "Lavello"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by anovak@octagon
```

The version of `vg` is `1.23.0` as installed via [Conda](https://github.com/nf-core/viralrecon/blob/11ba682ed6bca919e880c9982e731c047588fab2/environment.yml#L46). All of the software required to reproduce the error is installed in a Docker container that can be obtained from [here](https://hub.docker.com/repository/docker/nfcore/viralrecon/) (`dev` tag).

Thanks in advance!

**Comment by glennhickey** [comment]
I can reproduce this, and should be able to fix it soon.  In the meantime, here is a workaround that seems to work for me.  
Instead of running 
```
 vg deconstruct -p $chrom sample1.xg ...
```
Do
```
vg snarls sample1.xg > sample1.snarls
vg deconstruct -p $chrom sample.xg -r sample1.snarls
```

**Comment by drpatelh** [comment]
Really impressed with the response time @glennhickey ! 😎 Thank you very much. We will try and use the workaround you have suggested and get back to you if we have any more questions.
