### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by twesigomwedavid** [vgteam/vg#2802]
Hello,

It looks like some of the usage information given on the vg github no longer applies to the new versions. For example, the use of a `translation file` required for variant calling is not mentioned anywhere. I suggest an update to the USAGE part of the vg documentation? 

Thanks.

**Comment by glennhickey** [comment]
As far as I can tell, the variant calling documentation is up to date in both the [Readme](https://github.com/vgteam/vg/blob/master/README.md#variant-calling) and [Wiki](https://github.com/vgteam/vg/wiki/Whole-genome-calling-and-genoyping).

If you have a version of vg that doesn't seem consistent with this, please upgrade to the latest release.

**Comment by twesigomwedavid** [comment]
@glennhickey Thanks for the clarification.
