### ISSUE TITLE
VG version command

### ISSUE THREAD

**Issue by willgdjones** [vgteam/vg#283]
I think we should add a vg -v to return the version of VG that's being used!

**Comment by ekg** [comment]
Let's make it "vg version" or just appear when vg runs.

On build, use id=$(git log | head -1 | cut -f 2 -d\ | head -c 8) to get the
commit id. Stash this in a version.o file and link it in at build time.

As a fallback (and what I do), label the vg with the version you're using;
vg-$id.

**Comment by edawson** [comment]
We could put the commit hash at the top of vg_help's output?

**Comment by ekg** [comment]
Also a good idea!
