### ISSUE TITLE
Alignment tracebacks are sometimes wrong

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#285]
Taking "AAATTTTCTG" as a single-node reference, try aligning "AAAGGGTTTCTG" to it with vg map or vg align.

With the (current) default scoring parameters of match=2, mismatch=2, gap open=3, gap extend=1, you get this alignment:

```
{"sequence": "AAAGGGTTTCTG", "path": {"mapping": [{"position": {"node_id": 1}, "edit": [{"from_length": 3, "to_length": 3}, {"to_length": 3, "sequence": "GGG"}, {"from_length": 3, "to_length": 3}, {"from_length": 1}, {"from_length": 3, "to_length": 3}], "rank": 1}]}, "score": 12}
```

That looks like this:

```
AAAGGGTTT-CTG
AAA---TTTTCTG
```

But if you score it manually, you have 9 matches, 0 mismatches, 2 gap opens, and 2 gap extends, for a score of 9 * 2 - 0 * 2 - 2 * 3 - 2 * 1 = 10 points.

However, the mapper gives the score as 12 points. GSSW prints it as `12@0:1[3M3I3M1D3M]`

Here's the scoring matrix, if it's readable here:

```
	A		    A		    A		    T		    T		    T		    T		    C		    T           G		
A	(0, 0) 2	(1, 0) 2	(2, 0) 2	(3, 0) 0	(4, 0) 0	(5, 0) 0	(6, 0) 0	(7, 0) 0	(8, 0) 0	(9, 0) 0	
A	(0, 1) 2	(1, 1) 4	(2, 1) 4	(3, 1) 1	(4, 1) 0	(5, 1) 0	(6, 1) 0	(7, 1) 0	(8, 1) 0	(9, 1) 0	
A	(0, 2) 2	(1, 2) 4	(2, 2) 6	(3, 2) 3	(4, 2) 2	(5, 2) 1	(6, 2) 0	(7, 2) 0	(8, 2) 0	(9, 2) 0	
G	(0, 3) 0	(1, 3) 1	(2, 3) 3	(3, 3) 4	(4, 3) 1	(5, 3) 0	(6, 3) 0	(7, 3) 0	(8, 3) 0	(9, 3) 2	
G	(0, 4) 0	(1, 4) 0	(2, 4) 2	(3, 4) 1	(4, 4) 2	(5, 4) 0	(6, 4) 0	(7, 4) 0	(8, 4) 0	(9, 4) 2	
G	(0, 5) 0	(1, 5) 0	(2, 5) 1	(3, 5) 0	(4, 5) 0	(5, 5) 0	(6, 5) 0	(7, 5) 0	(8, 5) 0	(9, 5) 2	
T	(0, 6) 0	(1, 6) 0	(2, 6) 0	(3, 6) 3	(4, 6) 2	(5, 6) 2	(6, 6) 2	(7, 6) 0	(8, 6) 2	(9, 6) 0	
T	(0, 7) 0	(1, 7) 0	(2, 7) 0	(3, 7) 2	(4, 7) 5	(5, 7) 4	(6, 7) 4	(7, 7) 1	(8, 7) 2	(9, 7) 0	
T	(0, 8) 0	(1, 8) 0	(2, 8) 0	(3, 8) 2	(4, 8) 4	(5, 8) 7	(6, 8) 6	(7, 8) 3	(8, 8) 3	(9, 8) 1	
C	(0, 9) 0	(1, 9) 0	(2, 9) 0	(3, 9) 0	(4, 9) 1	(5, 9) 4	(6, 9) 5	(7, 9) 8	(8, 9) 5	(9, 9) 4	
T	(0, 10) 0	(1, 10) 0	(2, 10) 0	(3, 10) 2	(4, 10) 2	(5, 10) 3	(6, 10) 6	(7, 10) 5	(8, 10) 10	(9, 10) 7	
G	(0, 11) 0	(1, 11) 0	(2, 11) 0	(3, 11) 0	(4, 11) 0	(5, 11) 2	(6, 11) 3	(7, 11) 4	(8, 11) 7	(9, 11) 12
```

It looks like the aligner might really be finding this alignment:

```
AAAGGG-TTTCTG
AAA---TTTTCTG
```

I think it might be scoring the second gap as one gap extend rather than one gap open, and allowing a gap to "extend" from a gap in the other strand. See cell (4,6) where there's a 2, because the net score of everything to the left of that in this alignment is 0? But the traceback doesn't reflect that (or the equally good softclipped version where that part  left of the T,T match is just excluded from the alignment).

I haven't really tried to dig into the GSSW code, because it's all fancy SSE intrinsics, but I would appreciate it if someone who does know what's going on inside it can take a look at this. I ran into this trying to swap out the scoring parameters, and I don't want to try and merge in new scoring parameters or the UI I built to set them until I know they're actually being used properly.

@ekg, can you reproduce or diagnose this?

**Comment by ekg** [comment]
I'm on it. I'll check it out tomorrow.

Is it possible that the gap extend isn't recorded as a penalty. It is just
+1. That isn't what I expected it to do though.

I implemented this. I should know... Will IDG into it.

Thanks for taking on the local alignment. It needed a review and it seems
some revision.

**Comment by ekg** [comment]
Does IDG stand for I Do Good? Auto complete...

**Comment by adamnovak** [comment]
Have you found out why this is happening yet, @ekg?

I've done some investigating, and it seems like the original SSW handles my example problem reads just fine. I think the matrices are correct, and the traceback code is wrong, as it looks like the traceback is new code on top of SSW (and as SSW is giving the same scores but providing alignments that agree with them).

If you remember @AlexKuhnle's PR againsg GSSW, https://github.com/ekg/gssw/pull/1, it seems like he might have run into this issue as well.

I've normalized his changes for whitespace here, so we can actually see what they are: https://github.com/ekg/gssw/compare/master...adamnovak:alex-patch?expand=1

I'm going to see if making the required header changes to get his code to build solves the problem for my test reads. But he still says there are reads where the aligner falls down, even in his codebase, so I will have to see if I can come up with one.

Do you think it's worth adding unit tests to GSSW that compare it against a known good Smith-Waterman implementation? It would be nice to be able to pin down these bugs to particular functions.

**Comment by ekg** [comment]
It is absolutely worth doing. I will look at this today. I have been
working on the mapper and PhD requirements.

GSSW differs from the original SSW library in a few was that I should
clarify. SSW was designed for the problem of whole genome dynamic
programming alignment. It first scans using a memory less striped smith
waterman algorithm and records the best and second best hits using the
maximum of the scoring matrix. Then it goes back to the maximum scoring
location and runs a non-SIMD alignment algorithm that properly records the
direction of the traceback to derive the precise optimal alignment.

In GSSW I wanted to resolve the matrixes in one pass. So I keep the
matrixes, and the traceback I implemented walks over the retained matrix.
This will work provided the gap open and extension scores are not the same
as the match and mismatch scores. However it is not correct in the general
sense.

My suspicion is that the traceback is OK but the score calculation is not.
I will look at this today.

**Comment by adamnovak** [comment]
On your comment about the scores: which scores need to be distinct, exactly? Because the parameter set I am trying to use, from BWA-MEM, is match=1, mismatch=4, open=6, extend=1, and in that set the gap extend penalty equals the match bonus. Is that a problem?

**Comment by ekg** [comment]
I think it should be fine. But I feel like what you've shown indicates more
serious issues with the dynamic traceback approach.

**Comment by adamnovak** [comment]
OK I am digging into it, and I think it's possible to do correctly, but you need to consider two gap flags, and in cases where it's ambiguous which kind of gap to open (because they both have the same score) you need to check if a gap in the reference (which stays within the same DP matrix) can be traced all the way to an open, and if not go with a gap in the read.

I am attempting to code it up now, so it should work soon.

**Comment by adamnovak** [comment]
OK, I've now confused myself as to why we think it is even possible to extract the tracebacks from the main DP matrix alone, given that we're using affine gap scoring.

If you have a look at page 14 in this presentation, there's a pretty good example of why you can't do the affine gaps DP problem in a single matrix: https://www.cs.umd.edu/class/fall2010/cmsc423/lectures/Lec04-gaps.pdf

I've changed over to DNA here, but:

Best alignment of CAT and CAGT:

```
CAGT
CA-T
``

Best alignment of CAT and CAGTG:

```
CAGTG
CAT--
```
Presume that this is embedded in a longer alignment, to solve the potentially negatibe scores and the ending in what ought to be a free end gap.

If you try and do the traceback here, at some point you get to the bottom right cell for CAT and CAGTG, which says take a gap, which puts you in the cell holding the score for the best alignment between CAT and CAGT, which is going to tell the traceback to take a match, and which won't necessarily be consistent with a gap open or extend.

How does this work at all? Is there a trick I don't see?

**Comment by ekg** [comment]
I think some explanation is in order. GSSW is based on SSW, which is a nice implementation of Farrar's SIMD-based "Striped Smith Waterman" algorithm. That paper is ideal for getting a sense of how things are working. The generalization in GSSW is just to extend the Bellman equations (recurrence relation) across the edges of the graph, so we can start by focusing on this in terms of what happens in the SSW case. So, [Farrar's paper](http://bioinformatics.oxfordjournals.org/content/23/2/156.short) is a nice place to start.

There are 3 matrixes that we're using. Farrar calls them H, E, and F. The H matrix stores our final scores. E and F are the gap matrixes we need to handle affine gaps. In SSW we don't keep all three around. In fact, the SSW implementations just keep the maximum score (and maybe the second best), and a single column of each. If we think of the rows of the matrix being relative to the query and the columns relative to the reference, we are only looking at one column at a time.

To be totally clear, this is the relevant bit from Farrar's paper:

![image](https://cloud.githubusercontent.com/assets/145425/14347365/142904be-fcb7-11e5-9e26-80531bb16adc.png)

So the point I want to make is that the H matrix ends up taking values from the E and F matrixes when they are the max. My understanding is that we would only follow them if they are the max, so at the end, if we record the full H matrix we should have sufficient information to generate the traceback.

Now, it is highly possible that I misunderstand something, but this should clarify my thinking and also how this works at all.

We use the H, E, and F matrixes to derive the scores in the H matrix. Then, we trace back using the scores in the H matrix.

**Comment by ekg** [comment]
@adamnovak I've reproduced the alignment problem you've provided.

I'm adding the score matrix printing as an option to all the alignment functions, so it'll be easier to think about as we find other cases. Also, I'm exposing the various scoring parameters at least to `vg align`. I will also do this for `vg map`.

There seem to be two problems. The first is the scoring. I agree that it looks odd, and I'm confused exactly what's going on. At first glance, it looks like the gap open penalty for deletions is not being respected. But now I'm confused. I need to dig into the traceback code.

For what it's worth, the two alignments (the one GSSW gives vs the manual one) are equivalent; it's just the placement of the gap that is different. I believe this is because the traceback will induce right alignment of indels.

I guess you have other examples?

**Comment by ekg** [comment]
Another oddity, which maybe isn't important. Soft clips are not recorded in the score.

**Comment by adamnovak** [comment]
You're talking about reproducing this example, right?

```
AAAGGG-TTTCTG
AAA---TTTTCTG
```

I have code that fixes that right now, based on Alex's implementation. Basically the problem there is that the current mainline GSSW code doesn't force you to properly terminate your gap tracebacks by finding the gap open, meaning that if the scores of the other nearby cells happen to coincidentally be right, you can go from a gap to something else (either a match/mismatch or a gap in the other strand) and produce a traceback for an invalid alignment in which no gap open was charged on the gap.

Thanks for the explanation of the different matrices involved. However, I think the way they do H does indeed mean that the traceback algorithm structure we have, where you visit each cell along the path in H, can't always work. Basically, even though H isn't restricted to alignments ending in matches, and you pull from E and F when the best alignment at i,j ends in a gap extend, you're only pulling from E or F at that particular i,j position. At the position in H that the traceback says to go to (one left or one up, depending on the type of gap), the optimal alignment might not be the one that the alignment you are trying to trace back is actually based on, and the E or F value that you're expecting to see might not have been chosen.

I did work out a super complicated way to get the correct traceback from just the H matrix, but it involves scanning along and looking for the match/mismatch that preceded a gap, and might have to devolve into breadth-first search crossing node boundaries.

What I think I am going to do is to save E and F along with H, and to implement a normal affine gap traceback that can visit locations in the E and F matrices, flying over the corresponding locations in H. It might be slower, but it definitely should be correct.

**Comment by ekg** [comment]
> I have code that fixes that right now, based on Alex's implementation. Basically the problem there is that the current mainline GSSW code doesn't force you to properly terminate your gap tracebacks by finding the gap open, meaning that if the scores of the other nearby cells happen to coincidentally be right, you can go from a gap to something else (either a match/mismatch or a gap in the other strand) and produce a traceback for an invalid alignment in which no gap open was charged on the gap.

That makes sense and explains your example.

> I did work out a super complicated way to get the correct traceback from just the H matrix, but it involves scanning along and looking for the match/mismatch that preceded a gap, and might have to devolve into breadth-first search crossing node boundaries.

It definitely will end up in a DFS when we get to the node boundaries. Which is painful and probably not necessary if we eat the cost of holding the E and F matrices around.

> What I think I am going to do is to save E and F along with H, and to implement a normal affine gap traceback that can visit locations in the E and F matrices, flying over the corresponding locations in H. It might be slower, but it definitely should be correct.

This sounds plausible. I wonder if we could get away with only recording the gap open/close possibilities. This would triple the memory requirements for GSSW, which may hurt performance.

Saving the matrices may be somewhat complicated. See the section on the "lazy F loop" in the SSW paper.

I'm happier with slightly more memory-intensive, but correct and fast than low-memory, fast, and often slightly wrong. Let me know if I can help in any way beyond confirming that this is a problem.

**Comment by adamnovak** [comment]
I've implemented the matrix saving and am working on debugging the three-matrix traceback now.

**Comment by adamnovak** [comment]
OK, I am finally done! https://github.com/ekg/gssw/pull/6 should resolve this issue in GSSW, and I have some commits to pull that in that I am rebasing for vg.

Some small code changes are needed in VG, because that PR also includes the new CIGAR operations and print file parameters, but I will include those in my update PR.

**Comment by ekg** [comment]
I've pulled it in! Great!!!!!! I'm looking forward to having this land.

After it lands I'm going to add a few more tests to verify the method. One
that I think is important is ensuring that the generalization works
seamlessly across nodes. For instance, we should get exactly the same
alignment for one read against one node with a long sequence as for the
same but with the reference broken into many small nodes.
