### ISSUE TITLE
vg snarls doesn't traverse every ultrabubble

### ISSUE THREAD

**Issue by egoltsman** [vgteam/vg#2878]
Dear vg team,
I have been trying to get a better sense of the options available for de-novo variant calling on graphs built strictly from multiple alignments.   It appears that snarl detection and traversal are the two key steps here.  I have a toy graph example that contains a couple of pretty large indels - one of 60 kb and the other 110kb (the graph itself was built with minigraph, sample-paths were traced and added manually, then converted to vg format).   Each large indel contains a handful of smaller nested bubbles in it, and so I thought this would be a good test for the snarl finding algorithms.  Indeed, 'vg snarls' finds both of the outer bubbles as well as the inner ones (although I can't tell whether it actually classified them as 'ultrabubbles').   Below is a slice of the output for that region:  57-68 and 68-71 are the two large snarls.    All looks good so far.
```
{"directed_acyclic_net_graph": true, "end": {"node_id": "68"}, "start": {"node_id": "57"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "59"}, "parent": {"end": {"node_id": "68"}, "start": {"node_id": "57"}}, "start": {"node_id": "58"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "60"}, "parent": {"end": {"node_id": "68"}, "start": {"node_id": "57"}}, "start": {"node_id": "59"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "62"}, "parent": {"end": {"node_id": "68"}, "start": {"node_id": "57"}}, "start": {"node_id": "60"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "64"}, "parent": {"end": {"node_id": "68"}, "start": {"node_id": "57"}}, "start": {"node_id": "62"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "65"}, "parent": {"end": {"node_id": "68"}, "start": {"node_id": "57"}}, "start": {"node_id": "64"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "67"}, "parent": {"end": {"node_id": "68"}, "start": {"node_id": "57"}}, "start": {"node_id": "65"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "71"}, "start": {"node_id": "68"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "115"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "114"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "117"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "115"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "119"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "117"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "122"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "119"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "123"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "122"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "125"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "123"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "127"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "125"}, "start_end_reachable": true, "type": 1}
{"directed_acyclic_net_graph": true, "end": {"node_id": "128"}, "parent": {"end": {"node_id": "71"}, "start": {"node_id": "68"}}, "start": {"node_id": "127"}, "start_end_reachable": true, "type": 1}

```

Now,  as the snarls capture multiple nodes and possible paths, I wanted to try the Snarl Traversal feature and ran
vg snarls -a -r <traversals.out>  <my_graph.vg>
The traversals file contains what looks like one traversed path through the first snarl and nothing for the second snarl.   If the algorithm takes into account the reference paths present in the graph I would expect it to output two traversals for each snarl.  (See screenshot attached. Without the paths guiding the traversal there would be a combinatorial explosion of possible traversals through a large snarl, so I'm guessing the algorithm must be guided somehow)  Just looking at the graph topology, both bubbles seem like they would be fairly straightforward to traverse.  Is there a way to obtain additional information about why some traversals failed or got rejected?

Thank you!

![image](https://user-images.githubusercontent.com/3710754/86319595-b4019c80-bbe9-11ea-990e-a43b6f67a0ac.png)

**Comment by glennhickey** [comment]
You may be able to get more traversals using the `-m` option to increase the maximum snarl size to traverse.  

But in general, `snarls -r` isn't terribly practical. Current alternatives:
 
* `vg deconstruct -e`: If your graph has embedded paths (which it sounds like it does), this will output a traversal for each path such that spans the snarl in VCF format.
* `vg call -T`:  This depends on having some read mappings (converted from `gam` using `vg pack`), which it uses to greedily choose the best supported traversals.  It will output the traversals in GAF format.  It could also be limited to paths by using the GBWT interface (`-g`)

A lot of this logic could be wired in as options into `vg snarls`.  I'm working on this area now, in particular using GAF as an exchange format for traversals and genotypes, so hopefully we'll have a more general interface soon.

**Comment by egoltsman** [comment]
Hi Glenn,
I think we're getting close, but there are still occasional hickups with snarl-based decomposition.   I'm working with a simple graph of three "samples", which contains a nested variant.  The inner (smaller) indel was introduced in Sample2 and appears as a simple bubble on the graph, while Sample3 introduces an inversion of a larger region which includes the original indel  (green and red circles in the attached image).    This nested variant is correctly described in the snarls file,  as far as I can tell:
```
{"directed_acyclic_net_graph": true, "end": {"node_id": "69"}, "end_self_reachable": true, "start": {"node_id": "65"}, "start_end_reachable": true, "start_self_reachable": true}
{"directed_acyclic_net_graph": true, "end": {"node_id": "68"}, "parent": {"end": {"node_id": "69"}, "start": {"node_id": "65"}}, "start": {"node_id": "66"}, "start_end_reachable": true, "type": 1}
```
But when I deconstruct the graph using this snarl file I only get the *outer* bubble reported as a variant.   

vg deconstruct -r snarls.pb -e -p <path_name> -x <graph>

When Sample1 is passed in with -p  the resulting vcf contains one variant called in this region, but its positions correspond to the larger, outer bubble bound by nodes 65-69 and not the inner 66-68 one, when it should be the other way around.   It seems like the outter snarl takes precedence as it's considered the "parent".  Is this the intended behavior?     Again, the picture shows it better that I can explain it.

Thanks again!
![graph2](https://user-images.githubusercontent.com/3710754/95405115-c287e000-08cb-11eb-8150-d21417bef91f.png)
