### ISSUE TITLE
Killed, Mapping

### ISSUE THREAD

**Issue by a00101** [vgteam/vg#2889]
`vg map -x ref_pruned.xg -g ref_pruned.gcsa -f test1_1_val_1.fq.gz -f test1_2_val_2.fq.gz > test_map.gam
`
log file says below
`Killed`

Can you help me out?

**Comment by ekg** [comment]
How did you make your input graph?

In general, we prune the input to GCSA2 indexing, not the graph given as a
xg to map. This is because the indexing can have exponential costs in the
number of variants found within a k-mer. The alignment algorithm does not
suffer from these costs, so it can typically be run on the full graph.

The one exception are graphs with very high degree on their nodes. These do
cause problems for alignment.

**Comment by adamnovak** [comment]
`Killed` in the output means that some other process on your system stopped vg while it was trying to work. This is most often the "Out Of Memory Killer" (OOM Killer), which swoops in when you use up all your RAM and starts killing things.

How much memory do you have on your system? And how big are the files (.vg, .gcsa, .gcsa.lcp) that you are using?

You can usually solve this problem by using a computer with more RAM.

**Comment by a00101** [comment]
# construct
`vg construct -t 70 -p -r Homo_sapiens.GRCh38.dna.primary_assembly.fa -v 00-common_all.vcf.gz > 01.dbsnp_hg38.vg`

# pruning and indexing
`vg prune -p -t 80 -r 01.dbsnp_hg38.vg > 02.dbsnp_hg38_pruned.vg`

`vg index -b /data/prosium/ -t 75 -g 03.dbsnp_hg38.gcsa -x dbsnp_hg38.xg 02.dbsnp_hg38_pruned.vg
`
# mapping
`vg map -x 03.dbsnp_hg38.xg -g 03.dbsnp_hg38.gcsa -f test_1_val_1.fq.gz -f test_2_val_2.fq.gz -t 78 > test.gam`

`**Killed**`

My computer spec is, 80threads and 756GB RAM. not enough?

**Comment by a00101** [comment]
@ekg 
Let me get this straight.
You mean, have to use .gcsa only?

**Comment by ekg** [comment]
We use the full graph as input to mapping. The pruned graph is only useful as an input to the sequence indexing. This is what gives us seeds to map the reads against the full graph. The local alignment against the full graph does not suffer from combinatorial explosion in the way that the kmer enumeration does. (Partial order alignment has costs that scale with the length of the graph and the number of edges, but the kmer enumeration scales exponentially with the number of furcations in a given kmer length.)

So I would do this, following the guidelines on the wiki: https://github.com/vgteam/vg/wiki/Index-Construction#indexing-a-large-graph

```
vg construct -t 70 -p -r Homo_sapiens.GRCh38.dna.primary_assembly.fa -v 00-common_all.vcf.gz > 01.dbsnp_hg38.vg
vg convert -x 01.dbsnp_hg38.vg >01.dbsnp_hg38.xg
vg prune -p -t 80 -r 01.dbsnp_hg38.vg > 02.dbsnp_hg38_pruned.vg
vg index -b /data/prosium/ -t 75 -g 03.dbsnp_hg38.gcsa 02.dbsnp_hg38_pruned.vg
vg map -x 01.dbsnp_hg38.xg -g 03.dbsnp_hg38.gcsa -f test_1_val_1.fq.gz -f test_2_val_2.fq.gz -t 78 > test.gam
```

How does that go?

**Comment by a00101** [comment]
@ekg Thank you for your answer.

In the line of 'vg map', error occurred.

```
error:[Surjector] Failed to provide an graph to the Surjector
ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_EGk1Yg/stacktrace.txt
Please include the stack trace file in your bug report!

```

stacktrace.txt is below

```
Crash report for vg v1.25.0 "Apice"
Stack trace (most recent call last):
#4    Object "/root/anaconda3/bin/vg", at 0x4dfb19, in _start
#3    Object "/root/anaconda3/bin/vg", at 0x1c81848, in __libc_start_main
#2    Object "/root/anaconda3/bin/vg", at 0x40a137, in main
#1    Object "/root/anaconda3/bin/vg", at 0xa2a8f7, in vg::subcommand::Subcommand::operator()(int, char**) const
#0    Object "/root/anaconda3/bin/vg", at 0x9e5149, in main_map(int, char**)
```

**Comment by ekg** [comment]
That's a very surprising error to get here.  Which version are you using?

**Comment by glennhickey** [comment]
For some reason, `vg map` gives that `Error:[Surjector] Failed to provide an graph to the Surjector` message when the input graph doesn't exist.  So I'd definitely check to make sure `01.dbsnp_38.xg` is present in your path.  

Example
```
touch reads
vg map -x does-not-exist.xg -f reads
error:[Surjector] Failed to provide an graph to the Surjector
ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_0eoh8c/stacktrace.txt
Please include the stack trace file in your bug report!
```

**Comment by a00101** [comment]
@ekg 

vg --version
>vg v1.25.0 "Apice"

@glennhickey 

my cmd is below.
`vg map -x 01.dbsnp_38.xg -g 03.dbsnp_hg38.gcsa -f test_1_val_1.fq.gz -f test_2_val_2.fq.gz -t 78 > test.gam`

and my fileslist is below.
01.dbsnp_hg38.vg [2.8G]
01.dbsnp_hg38.xg [11G]
02.dbsnp_hg38_pruned.vg [3.6G]
03.dbsnp_hg38.gcsa [14G]
03.gbdnp_hg38.gcsa.lcp [8.5G]

Thank you. but Can i check something another?

**Comment by glennhickey** [comment]
The xg in your filelist doesn't match the one in your command.

**Comment by a00101** [comment]
@glennhickey 
Sorry I mistyped filename. gbdnp. actually file name is dbsnp.

filenames are below.
```
dbsnp_hg38.vg [2.8G]
dbsnp_hg38.xg [11G]
dbsnp_hg38_pruned.vg [3.6G]
dbsnp_hg38.gcsa [14G]
dbsnp_hg38.gcsa.lcp [8.5G]
```

And my cmd is 
`vg map -x dbsnp_38.xg -g dbsnp_hg38.gcsa -f test_1_val_1.fq.gz -f test_2_val_2.fq.gz -t 78 > test.gam`

Error still occurred
```
error:[Surjector] Failed to provide an graph to the Surjector
ERROR: Signal 11 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_mWzuJq/stacktrace.txt
Please include the stack trace file in your bug report!
```

What should i do? 
Thank you in advance.

**Comment by a00101** [comment]
Solved.

I renamed xg file from XXX.xg to XXX.vg.xg
It works well, but I don't know why.


Thank you for your consideration.

**Comment by ekg** [comment]
It does not make sense to me why this would resolve the issue. There is not
a requirement that the filename ends in .vg.xg.
