### ISSUE TITLE
Can not convert from GFA to VG

### ISSUE THREAD

**Issue by brettChapman** [vgteam/vg#2890]
Hi

I'm running vg view and I find it consumes a huge amount of memory which eventually kills the job.

I run with command:

vg view -Fv wildBarley_chr1.gfa > wildBarley_chr1.vg

My workflow starts from a cactus alignment, then hal file conversion, and running through seqwish. I've been following the steps from https://github.com/ComparativeGenomicsToolkit/hal to produce a GFA file, and then afterwards conversion to VG.

My GFA file is only 6.3GB in size.

I'm running on a Slurm managed cluster on a node with 16 cores and 64GB RAM. I don't have the option of upgrading my RAM. Is there a more memory efficient way of converting to a VG file?

I intend on later merging my VG files for each chromosome, doing some snp calls, dot plots, adding a gene annotation track and also viewing the alignments in sequenceTubeMap.

Thanks for your help.

**Comment by jeizenga** [comment]
Hi Brett,

The algorithm in `vg convert` will build the VG graph without loading the entire GFA file into memory. Instead, it uses multiple passes over the file. If you are still running into trouble with the memory limits, `vg convert` also allows you to specify the graph encoding. The PackedGraph format is the most memory-efficient option. Certain operations still require the old VG format, but at this point most of the code has transitioned to be agnostic about the graph encoding.

Hope that helps!
Jordan

**Comment by brettChapman** [comment]
Hi Jordan (@jeizenga)

Thanks. I tried vg convert and received the following error:

vg convert wildBarley_chr1.gfa -p > wildBarley_chr1.pg
error[load_proto_to_graph]: invalid Graph message

It gives me the same error message no matter what parameter I use. There is a reference in the https://github.com/ComparativeGenomicsToolkit/hal Readme which refers to a -g option for the GFA input graph, but that appears to no longer be an option. My GFA file was generated by seqwish.

I've also just tried Hal2VG https://github.com/ComparativeGenomicsToolkit/hal2vg using the suggested command in the Readme:

hal2vg wildBarley_chr1.hal --hdf5InMemory --chop 32 > wildBarley_chr1.pg

This method worked. I don't know if the output would be identical if I had used vg convert or not and I'm not sure if the --chop option will limit the information in my graph compared to using vg convert.

Thanks.

**Comment by jeizenga** [comment]
Ah, I should have mentioned that you need an extra argument `-g` to read GFA input in `vg convert`.

**Comment by brettChapman** [comment]
Hi Jordan (@jeizenga)

I tried that initially, but it appears to no longer be supported:

vg convert -g wildBarley_chr1.gfa -p > wildBarley_chr1.pg
vg: invalid option -- 'g'
usage: vg convert [options] <input-graph>
output options:
    -v, --vg-out           output in VG format [default]
    -a, --hash-out         output in HashGraph format
    -p, --packed-out       output in PackedGraph format
    -x, --xg-out           output in XG format
    -o, --odgi-out         output in ODGI format

**Comment by brettChapman** [comment]
I think I figured out what the issue is, I'm using an old version. I built it from the Dockerfile:

vg version
vg version v1.21.0-343-g4d48086a7 "Fanano"
Compiled with g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0 on Linux
Linked against libstd++ 20181206
Built by root@fb1b75f99a61

I'll try and update the Dockerfile, recompile and see if that fixes it.

**Comment by brettChapman** [comment]
Hi Jordan (@jeizenga)

I'm now using v1.25 and all works fine using vg contruct. Thanks.

Should all VG commands which take *.vg as input work just as well with *.pg? I intend to index and also prepare the *.pg files for viewing in sequenceTubeMap, however all examples from the sequenceTubeMap use *.vg files as input.

Thanks.

**Comment by jeizenga** [comment]
I believe at this point all of the main subcommands will work fine. We've been a bit slow to transition some of the relatively under-used subcommands, but if you encounter one that won't accept a PackedGraph let us know and we'll push it up to the top of our priorities.
