### ISSUE TITLE
vg mod -u doesn't unchop

### ISSUE THREAD

**Issue by maickrau** [vgteam/vg#2949]
**1. What were you trying to do?**

I have a graph with chopped nodes. I tried to use vg to unchop the nodes so that non-branching parts are collapsed into single nodes.

**2. What did you want to happen?**

The output graph has non-branching paths collapsed to single nodes

**3. What actually happened?**

The output graph is identical to the input graph and non-branching paths remain chopped

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

[graph.zip](https://github.com/vgteam/vg/files/5062778/graph.zip)

```
./vg view -Fv graph.gfa | ./vg mod -u - | ./vg view - > graph-unitig.gfa
```

**6. What does running `vg version` say?**

```
$ ./vg version
vg version v1.26.0 "Stornara"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by ubuntu@ip-172-31-9-245
```

**Comment by ekg** [comment]
It may be that there are paths that prevent the unchopping. You would remove these first to ensure that the unbranching components are turned into one node.

You might also consider testing the same algorithm in `odgi unchop`.

**Comment by maickrau** [comment]
You're right, there were paths remaining in the graph and that prevented unchopping. Running `grep -vP '^P' < graph.gfa | ./vg view -Fv - | ./vg mod -u - | ./vg view - > graph-unitig.gfa` gave the wanted results. Closing this
