### ISSUE TITLE
Convert BMP to GAM

### ISSUE THREAD

**Issue by persianpros** [vgteam/vg#2950]
Hello,

It's the first time I saw .gam format and it's for a bootlogo inside a mtd partition: https://github.com/OpenVisionE2/meta-sh4/blob/develop/recipes-bsp/cfe/forever-logo-cfe/bootloader.gz

I just want to ask if you know how can I convert a .bmp to a .gam file?

**Comment by jeizenga** [comment]
I think the .gam format you're describing must be different than the .gam format we use in VG. Our .gam format is used in computational genomics. It doesn't really have any direct relationship to graphics.
