### ISSUE TITLE
Gitlab CI no longer positing reports

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#2984]
This seems to have stopped happening in very early July.  On one hand, it's nice not to get all those emails, but on the other when trying to trace a recent running-time regression it was quite annoying.

**Comment by adamnovak** [comment]
Oh yeah, those are super not there.

Our problem is:

https://ucsc-ci.com/vgteam/vg/-/jobs/60506#L977

```
 Traceback (most recent call last):
  File "vgci/post-comment.py", line 12, in <module>
    import github
ModuleNotFoundError: No module named 'github'
```

We are installing `pygithub`, so either we're mixing up our pythons/virtualenvs or something about the module changed.
