### ISSUE TITLE
Behold! The un-index-able graph!

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#301]
Here is a graph (kmers.vg in the ZIP file) that can't be indexed with GCSA2. 
Note that this graph validates just fine.

```
$ vg index -g test.gcsa kmers.vg -k 16
vg: /cluster/home/anovak/build/vg/include/sdsl/int_vector.hpp:1436: sdsl::int_vector<<anonymous> >::const_reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) const [with unsigned char t_width = 1u; sdsl::int_vector<<anonymous> >::const_reference = const long unsigned int; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]: Assertion `idx < this->size()' failed.
Aborted (core dumped)
```

The file was generated like this:

```
sg2vg http://ga4gh-test1.cloudapp.net/debruijn-mhc-k63/v0.6.g -u | vg view -Jv - | vg mod -X100 - | vg ids -s - > debruijn-mhc-k63.vg
vg mod -p -l 16 -e 3 debruijn-mhc-k63.vg | vg mod -S -l 32 - > kmers.vg
```

It's part of my attempt to run the wiki pipeline on our De Bruijn k63 graph from the bake-off. When indexing the full graph with the De Bruijn .graph file from this graph, I get this same error, and I figured attempting to index the simplified graph was a good sanity check.

[unindexable.zip](https://github.com/vgteam/vg/files/214098/unindexable.zip)

**Comment by ekg** [comment]
@adamnovak I am not able to reproduce this.

I worked my way up to the order-128 GCSA, and every one has worked. I'm using a local build of vg that should be level with master except the addition of the sampler.

So this works fine:

```
vg index -k 16 -X 3 -p -g kmers.order128.gcsa kmers.vg
```

I can do a variety of sizes without problem:

```
-rw-rw-r-- 1 erik erik  21M Apr 13 10:45 kmers.order22.gcsa
-rw-rw-r-- 1 erik erik 6.4M Apr 13 10:45 kmers.order22.gcsa.lcp
-rw-rw-r-- 1 erik erik  18M Apr 13 10:49 kmers.order44.gcsa
-rw-rw-r-- 1 erik erik 9.2M Apr 13 10:49 kmers.order44.gcsa.lcp
-rw-rw-r-- 1 erik erik  19M Apr 13 10:54 kmers.order88.gcsa
-rw-rw-r-- 1 erik erik  12M Apr 13 10:54 kmers.order88.gcsa.lcp
-rw-rw-r-- 1 erik erik  20M Apr 13 11:04 kmers.order128.gcsa
-rw-rw-r-- 1 erik erik  12M Apr 13 11:04 kmers.order128.gcsa.lcp
```

**Comment by glennhickey** [comment]
I get the same error with my currentish local branch on two different
systems.

Just tried a fresh clone of ekg/master on my desktop and reproduced the
error as well...

**Comment by ekg** [comment]
Could this be an sdsl-lite compatibility problem on my or your end?

**Comment by glennhickey** [comment]
No idea, but I'd guess some kind of submodule shenanigans in your local
branch that somehow differ from master, given that we're reproducing on
multiple systems

**Comment by ekg** [comment]
I think we are going to need to bisect this somehow...

**Comment by ekg** [comment]
Here are my submodules:

```
➜  vg git:(master) ✗ git submodule status  
 2a82bbfda156ea38c1abc0078820277f492ef615 deps/DYNAMIC (2a82bbf)
 c38fbfa401600cc81ccda66bfc0da3ea56288d03 deps/bash-tap (1.0.2)
 c68cebb4f2e5d5d2b70cf08fbdf1944e9ab2c2dd deps/fastahack (c68cebb)
 b433cc28619bf4891869a671f2c0729bbd081b43 deps/gcsa2 (v0.6.1)
 781a216392a0ccf2ecac464ddba4c320da325d53 deps/gfakluge (heads/master)
 8476640f52d7dbff29e860991f44969e633a64bb deps/gssw (heads/master-2-g8476640)
 f83dfd233af3459e3b638fcb6379beb4c67b7c10 deps/htslib (1.2.1-29-gf83dfd2)
 7ee7a250ce009d29f20aca7a2e2ef24bb7825a0f deps/libVCFH (heads/master)
 e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc deps/lru_cache (e5fb7f3)
 f5cc1d1a10c6c05f172717ddac545e6a6606f7d2 deps/progress_bar (heads/master)
 dfae9e36c7c45b02f39463152c4f6560622d4a78 deps/protobuf (v3.0.0-alpha-4-152-gdfae9e3)
 2b56e14d04e511565febeea87754af7ca80e3829 deps/raptor (raptor2_2_0_15-105-g2b56e14)
 7246ad34d05dc4a29aadd80b378a607885c2edb2 deps/rocksdb (2.8.fb-2098-g7246ad3)
 df856d45be003522e0da813cfd454e6ed7dcd521 deps/sdsl-lite (v2.0.3-271-gdf856d4)
 6474be99be64bc9d930e9f30d89d71119f78f699 deps/sha1 (1.2)
 2b9152d9c5bed71dffb7f7f6c7a3ec48b058ff2d deps/snappy (1.1.3-8-g2b9152d)
 a61a6ba7adbc4e3a7545843a72c530bf35604dae deps/sparsehash (sparsehash-2.0.3-7-ga61a6ba)
 1c93badc74803cef0b3f6bf5c96e9c8e3f226fe8 deps/superbubbles (heads/master)
 0db2e8c82d8b38e560c2e373e34fbc802e8f35ab deps/vcflib (v1.0.0-rc0-12-g0db2e8c)
 13a45bdf36d7483be68cde7a107584d21e58ba1f deps/xg (v1.0.0-141-g13a45bd)
```

**Comment by adamnovak** [comment]
Alright, I've managed to reproduce both Erik's success and my and Glenn's
error with the same binary:

```
[anovak@kolossus broken-mhc]$ vg index -k 16 -X 3 -p -g kmers.order128.gcsa
kmers.vg
 loading graph                  [=======================]100.0%
 processing kmers of kmers.vg   [=======================]100.0%
[anovak@kolossus broken-mhc]$  vg index -g test.gcsa kmers.vg -k 16 -X 2 -p
 loading graph
[=================================================]100.0%
 processing kmers of kmers.vg
[=================================================]100.0%
vg: /cluster/home/anovak/build/vg/include/sdsl/int_vector.hpp:1436:
sdsl::int_vector<<anonymous> >::const_reference
sdsl::int_vector<<anonymous> >::operator[](const size_type&) const [with
unsigned char t_width = 1u; sdsl::int_vector<<anonymous> >::const_reference
= const long unsigned int; sdsl::int_vector<<anonymous> >::size_type = long
unsigned int]: Assertion `idx < this->size()' failed.
Aborted (core dumped)
```

It looks like the difference is the -X option for doubling steps. @ekg,
could you try -k 16 -X 2? That would come out to order 64, which it doesn't
look like you tried. Remember that we're indexing a k=63 De Bruijn graph to
start with? That might have something to do with it...

I'm using v1.4.0-426-g2d74e5f as reported by the newly added `vg version`,
and my submodules look like this:

```
[anovak@kolossus vg]$ git submodule status
 2a82bbfda156ea38c1abc0078820277f492ef615 deps/DYNAMIC
(heads/master-6-g2a82bbf)
 c38fbfa401600cc81ccda66bfc0da3ea56288d03 deps/bash-tap (1.0.2)
 c68cebb4f2e5d5d2b70cf08fbdf1944e9ab2c2dd deps/fastahack (c68cebb)
 b433cc28619bf4891869a671f2c0729bbd081b43 deps/gcsa2 (v0.6.1)
 781a216392a0ccf2ecac464ddba4c320da325d53 deps/gfakluge
(remotes/origin/HEAD)
 8476640f52d7dbff29e860991f44969e633a64bb deps/gssw
(heads/reworked-traceback)
 f83dfd233af3459e3b638fcb6379beb4c67b7c10 deps/htslib (1.2.1-29-gf83dfd2)
 7ee7a250ce009d29f20aca7a2e2ef24bb7825a0f deps/libVCFH (heads/master)
 e5fb7f3b15ec49edc3fc6293797b44cc7ce420cc deps/lru_cache (e5fb7f3)
 f5cc1d1a10c6c05f172717ddac545e6a6606f7d2 deps/progress_bar (heads/master)
 dfae9e36c7c45b02f39463152c4f6560622d4a78 deps/protobuf
(v3.0.0-alpha-4-152-gdfae9e3)
 2b56e14d04e511565febeea87754af7ca80e3829 deps/raptor
(raptor2_2_0_15-105-g2b56e14)
 7246ad34d05dc4a29aadd80b378a607885c2edb2 deps/rocksdb
(2.8.fb-2098-g7246ad3)
 df856d45be003522e0da813cfd454e6ed7dcd521 deps/sdsl-lite
(v2.0.3-271-gdf856d4)
 6474be99be64bc9d930e9f30d89d71119f78f699 deps/sha1 (1.2)
 2b9152d9c5bed71dffb7f7f6c7a3ec48b058ff2d deps/snappy (1.1.3-8-g2b9152d)
 a61a6ba7adbc4e3a7545843a72c530bf35604dae deps/sparsehash
(sparsehash-2.0.3-7-ga61a6ba)
 1c93badc74803cef0b3f6bf5c96e9c8e3f226fe8 deps/superbubbles (heads/master)
 0db2e8c82d8b38e560c2e373e34fbc802e8f35ab deps/vcflib
(v1.0.0-rc0-12-g0db2e8c)
 abd77efee740f42aeaed2d8ac055ab2886384720 deps/xg (v1.0.0-140-gabd77ef)
```

It looks like you have one extra commit to xg on top of what I have; I
don't think that would affect this particular operation.

**Comment by jltsiren** [comment]
I managed to reproduce the assertion failure by compiling sdsl-lite and gcsa2 without `-DNDEBUG`. If you compile them normally, there is no crash and the produced index works fine. I'm investigating the cause.

**Comment by jltsiren** [comment]
This looks like an SDSL issue. The assertion failure comes from the main constructor of `sdsl::wt_pc<sdsl::huff_shape>` called inside `gcsa::directConstruct()`.

**Comment by adamnovak** [comment]
@jltsiren Do you know what arguments we're calling into SDSL with to produce this error? That would help for reporting it upstream.

I'm concerned about adding `-DNDEBUG` to the VG build for GCSA2, because we want to know when we're doing something wrong.

**Comment by jltsiren** [comment]
The error happens at line `directConstruct(this->bwt, bwt_buffer);` in the GCSA constructor. You should be able to reproduce it easily:

1. Extract the kmers using `vg kmers`.
1. Add `sdsl::store_to_file(bwt_buffer, "foo.bwt");` to `gcsa.cpp` just before the line producing the error.
1. Try building the index with the modified GCSA2 using `build_gcsa -d 2` to generate `foo.bwt`.

The following should then reproduce the error:

```
sdsl::int_vector_buffer<8> buffer("foo.bwt");
sdsl::wt_huff<> wt(buffer, buffer.size());
```

I'm not sure what goes wrong. One guess is `sdsl::select_support_mcl<>::init_fast()` in [select_support_mcl.hpp](https://github.com/simongog/sdsl-lite/blob/master/include/sdsl/select_support_mcl.hpp). There is a line accessing a bitvector using `select_support_trait<t_b, t_pat_len>::found_arg(j, *v)` without explicitly checking that position `j` is within the bounds. I don't have the time to start digging any further until I have finished the GCSA2 paper.

**Comment by adamnovak** [comment]
Thanks! I'll give this a shot and complain to SDSL.

**Comment by adamnovak** [comment]
I still haven't complained to the SDSL people about this bug.

**Comment by adamnovak** [comment]
Looks like I waited long enough that this issue fixed itself. I can now index the un-index-able graph just fine.
