### ISSUE TITLE
By annotating, the edge is gone.

### ISSUE THREAD

**Issue by gf-ho** [vgteam/vg#3017]
When I tried as follows, the edge was gone.

```
$ vg view -Fv test.gfa > test.vg
$ vg index -x test.xg test.vg
$ vg annotate -b test.bed -x test.xg -p > output.gam
$ vg augment -i test.vg output.gam > merged.vg
$ vg view merged.vg 
graph path 'x' invalid: edge from 3 end to 3 end does not exist
[vg view] warning: graph is invalid!
H	VN:Z:1.0
S	1	AT
S	2	GA
S	3	A
P	x	1+,2+,3+,3-,2-,1-	2M,2M,1M,1M,2M,2M	
P	y	2+	2M	
L	1	+	2	+	0M
L	2	+	3	+	0M
```

Here are the contents of the files I used.

```
$ cat test.gfa
H	VN:Z:1.0
S	1	ATGAA
P	x	1+,1-	5M,5M	
L	1	+	1	-	0M

$ cat test.bed
x	2	4	y
```
The version used is v1.23.0

I'd like to annotate without cutting the edge.
Can you help me?

**Comment by glennhickey** [comment]
This seems to be a bug in various implementations of `divide_handle` that don't handle reversing-edges.  the `vg.cpp` implementation is the only one that gets it right:
```
#(hacking augment_main.cpp to load test.vg as a VG object)
vg augment -i test.vg output.gam | vg view -
H	VN:Z:1.0
S	5	A
S	4	GA
S	2	AT
P	x	2+,4+,5+,5-,4-,2-	2M,2M,1M,1M,2M,2M	
P	y	4+	2M	
L	5	+	5	-	0M
L	4	+	5	+	0M
L	2	+	4	+	0M
```

But all the other formats fail in their own special way.
hashgraph (default used in original issue)
```
vg convert test.vg -a | vg augment -i - output.gam | vg view -
H	VN:Z:1.0
S	1	AT
S	2	GA
S	3	A
P	x	1+,2+,3+,3-,2-,1-	2M,2M,1M,1M,2M,2M	
P	y	2+	2M	
L	1	+	2	+	0M
L	2	+	3	+	0M
graph path 'x' invalid: edge from 3 end to 3 end does not exist
[vg view] warning: graph is invalid!
```
packed graph gives the same erroneous output as above where the inverted edge is missing. 

odji is similar but adds a wrong inverting edge
```
vg convert test.vg -o | vg augment -i - output.gam | vg view -
H	VN:Z:1.0
S	1	GA
S	2	AT
S	4	A
P	x	2+,1+,4+,4-,1-,2-	2M,2M,1M,1M,2M,2M	
P	y	1+	2M	
L	1	+	4	-	0M
L	1	+	4	+	0M
L	2	+	1	+	0M
graph path 'x' invalid: edge from 4 end to 4 end does not exist
[vg view] warning: graph is invalid!
```
Could you please take a look at hashgraph/packedgraph @jeizenga and odgi @ekg ?

**Comment by jeizenga** [comment]
Yeah, that definitely looks wrong. I'll look into that today.

**Comment by jeizenga** [comment]
This should now work on the default setting that you were using @gf-ho . 
@glennhickey I'll make another issue for ODGI graphs.

**Comment by gf-ho** [comment]
Thanks.
