### ISSUE TITLE
Namespace collision in `vg filter`

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#302]
@glennhickey and I have both implemented some basic filtering for alignments, but we did so totally separately. They both do similar things.

I'd like to merge them into one command but want to standardize the flags so it's not a surprise to anyone. Here's Glenn's bit:
``usage: ./bin/vg filter [options] <graph.vg> <alignment.gam> > out.gam
Filter low-scoring alignments using different heuristics.

options:
    -s, --min-secondary N   minimum score to keep secondary alignment [default=0]
    -r, --min-primary N     minimum score to keep primary alignment [default=0]
    -d, --min-sec-delta N   mininum (primary - secondary) score delta to keep secondary alignment [default=0]
    -e, --min-pri-delta N   minimum (primary - secondary) score delta to keep primary alignment [default=0]
    -f, --frac-score        normalize score based on length
    -a, --frac-delta        use (secondary / primary) for delta comparisons
    -u, --substitutions     use substitution count instead of score
    -o, --max-overhang N    filter reads whose alignments begin or end with an insert > N [default=100]``

And here's the one I've got running, which I've temporarily moved to `scrub` on my branch:
``usage: ./bin/vg scrub [options] <alignments.gam> > filtered.gam
Filter alignments by various common metrics.

options: 
  -d --depth <DEPTH>    remove edits below DEPTH
  -q --qual <QUAL>      remove edits with a per-base quality below <QUAL>
  -p --percent-identity <PCTID> remove alignments that arbelow <PCTID>
  -r --remove-alignments if an alignment fails return an empty one
(default behavior: remove failing edits but return the alignment)``

I plan to add soft-clip/split-read handling here in a few days (much like the overhang flag in the current filter).

Any input is great; I'm having a tough time deciding if they should remain separate commands or be unified.

**Comment by ekg** [comment]
Can you use Glen's to do the filtering and leave the scrubbing and
alignment modifying ones in yours? That'd be a clean separation. If
anything is missing from filter then we can add it back in.

**Comment by glennhickey** [comment]
Some of the options in my filter were added while debugging things that
turned out not to be super related, and may not be too useful.  Not to
mention a bit cryptic.  Then there's the ident field being added to gam
that I heard about that should simplify things too.

That said, with all the deadlines coming up, I'd like to keep the current
filter (which is needed by vg call) intact for the next week or two if
possible.  After that, I'm happy to merge / change /replace as makes sense.

thanks!
-Glenn

**Comment by edawson** [comment]
I'm going to keep these separate for the moment in `scrub` and `filter`. I think it's actually fine to have them broken out this way.

Sorry for the open/reopen/open/close loop-de-loop: Waffle got a little excited.
