### ISSUE TITLE
Ploidy greater than 2 in vg call

### ISSUE THREAD

**Issue by cademirch** [vgteam/vg#3031]
Hi, I would like to use vg call on pooled sequencing data and call only variants supported by my graph. I am curious if there are any plans for vg map to support --ploidy greater than 2? 

Thank you,
Cade

**Comment by ekg** [comment]
Map supports any ploidy. But vg call doesn't do polyploid (yet?).
@glennhickey should be able to answer

**Comment by cademirch** [comment]
> Map supports any ploidy. But vg call doesn't do polyploid (yet?). @glennhickey should be able to answer
> […](#)

Ah I totally meant vg call... I’ll edit my post.

**Comment by glennhickey** [comment]
We will eventually have support for higher ploidies, but unfortunately I don't think that will happen too soon, as it will probably be part of a more fundamental change to the entire calling pipeline.
