### ISSUE TITLE
Help with vg contruct

### ISSUE THREAD

**Issue by RenzoTale88** [vgteam/vg#3037]
Hello,
I'm trying to contruct a vg graph using vg 1.27.0 and a vcf file file with variants. When i try to build with ```vg contruct``` I get the following error:
```
error:[vg::Constructor] non-ATGCN characters found in variant:
genome.25     3535    25:3535 G       *,A     0.0     .       AC=6,8;AN=20
```
Is there a way to fix the alleles so that the deletion will be recognised by vg? 

Thank you in advance
Andrea

**Comment by glennhickey** [comment]
vg doesn't yet support VCF 4.3.  There are a couple issues about this already #2928 #2644
You should be able to work around this by replacing the * with . (or deleting the * alleles entirely).  When you do this, the nested alleles should still appear as you expect in the graph.

**Comment by LuukHenk** [comment]
Hello,
What might be an option to replace the * with .?

Thanks in advance
Luuk
