### ISSUE TITLE
Surjection should be able to use a sequence dictionary for SAM/BAM/CRAM output

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#3043]
`vg surject` and other commands that write HTSLib formats should be able to take an order of contigs. This is usually specified as a "sequence dictionary" file that is basically a SAM header. If you don't use the same contig order when writing your BAM, downstream tools will get upset, and @cmarkello will have to spend 5 hours rewriting the whole BAM file to reference the contigs by different numbers.

We should be able to take a sequence dictionary file and follow that order of contigs.

**Comment by cmarkello** [comment]
It's not just me, it's anyone that wants to run GATK on these BAMs.

**Comment by cmarkello** [comment]
@adamnovak got the following error:
```
error:[vg mpmap] Graph does not have a path named @HD   VN:1.5, which was indicated in fasta.dict
```

It seems it's not ignoring the non `@SQ` lines in the `.dict` file.

**Comment by adamnovak** [comment]
Oops. I thought only sequence records meant *only* `@SQ` and no `@HD`. I can make it skip `@HD` lines. Are there any others?

**Comment by cmarkello** [comment]
Looking again at the raw `dict` file, I don't think so. I think it's just to log the sam format version. I tested it without the `@HD` line and it appears to work.
