### ISSUE TITLE
vg mod from gam file not working as described

### ISSUE THREAD

**Issue by egoltsman** [vgteam/vg#3051]
**1. What were you trying to do?**

Following steps to add gene annotations to the graph as described here:
https://github.com/vgteam/vg/wiki/VG-RDF,-the-Ensembl-bacteria-E.-coli-genome-hack-attack

**2. What did you want to happen?**
Ultimately, I'd like to try out the RDF functionality and make a few queries using the gene annotations as criteria

**3. What actually happened?**
Calling vg mod -i results in the "deprecated" error pointing the user to  vg augment,  but the latter bails out on the input:

```
$vg mod -i foo.gam foo.vg >bar.vg`
[vg mod] error: vg mod -i is deprecated.  please switch to vg augment

$vg augment foo.vg foo.gam > bar.vg
error[VPKG::load_one]: Correct input type not found while loading handlegraph::MutablePathMutableHandleGraph

```

Is this workflow still supported or is there an alternative way to do it?

I'm working with the latest release  - v.1.27.1

Thanks!

**Comment by glennhickey** [comment]
What do do `vg validate foo.vg` and  `vg stats -F foo.vg` print?

**Comment by ekg** [comment]
I suggest building the graph with pggb. https://github.com/pangenome/pggb

**Comment by egoltsman** [comment]
vg validate did expose the problem - thanks for the tip!   The paths in the vg graph were botched by my earlier attempt to merge adjacent paths into one, and I ended up with paths that don't have the edges to support it.  Once I fixed this everything worked.

Thanks!
