### ISSUE TITLE
Multiplicities don't do anything?

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#3059]
https://github.com/vgteam/vg/blob/8503aac4b09a718bf0be5ee61224758aff7816b1/src/aligner.hpp#L226-L230

@jeizenga Are multiplicities really unimplemented? Why are we passing them in paired-end Giraffe then?

**Comment by jeizenga** [comment]
Where are you getting the idea that they are unimplemented?

**Comment by adamnovak** [comment]
It says in the doc comment that `the mapping quality is always calculated as if it multiplicity is 1.`. That sounds unimplemented to me.

**Comment by jeizenga** [comment]
Oh, I see why that could be confusing. What it actually means is that if the primary alignment has multiplicity greater than 1, the mapping quality you get back is the value that only 1 of those copies would get, not the mapping quality they all would get collectively.
