### ISSUE TITLE
Giraffe/surjector can produce BAM with multiple insertions/deletions in a row

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#3080]
Andrew Carroll says that, when running GATK4.1.2.0 MarkDuplicates, he encountered a "No M or N operator between pair of D operators in CIGAR" error.

While in GAM we can need multiple deletions in a row on different nodes to delete all of them, in BAM they need to be merged.

We think we can still use these BAMs by telling the GATK validator to chill, but they shouldn't be like this.

**Comment by adamnovak** [comment]
This *shouldn't* happen. CIGAR generation for HTSAlignmentEmitter goes through `append_cigar_operation`, which coalesces adjacent operations of the same type:
https://github.com/vgteam/vg/blob/c4ad64e0a16d6095242545f9cafcc486f661350b/src/alignment.cpp#L818

I suppose we could actually be using the spliced alignment emitter somehow, which has its own non-coalescing append logic:
https://github.com/vgteam/vg/blob/c4ad64e0a16d6095242545f9cafcc486f661350b/src/hts_alignment_emitter.cpp#L732

I could add (time-taking) scans for adjacent identical operations when serializing, or code to fix them up, I suppose.

It would be nice if I could reproduce the problem.

**Comment by jeizenga** [comment]
The spliced version actually does coalesce as well:
https://github.com/vgteam/vg/blob/c4ad64e0a16d6095242545f9cafcc486f661350b/src/hts_alignment_emitter.cpp#L726-L733

**Comment by adamnovak** [comment]
OK, looking at Andrew's dump of offending reads, it seems that the problem isn't duplicate `D` operations, but runs of e.g. `7D8I7D`, where two `D` operations are separated by an `I` operation.

I think the right way to approach this might be to settle on a canonical order (e.g. `D` always comes before `I`), and to coalesce runs of D and I operations as a unit. So when we want to add e.g. `1D`, we look not only at the top operation to see if it is a `D`, but also see if it is an `I`, and if so either insert or add to a `D` one operation below it.

**Comment by jeizenga** [comment]
Sure, that sounds like a pretty easy post-processing step for the CIGAR code.

**Comment by adamnovak** [comment]
I already did #3080 in #3089 by changing the way we add in new CIGAR operations. Do we want that *and* a postprocessing step?
