### ISSUE TITLE
Add paired-end consistency enforcement

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#309]
Right now vg will take paired ends, and return primary alignments that are not consistent with each other.

What I think it should do is, when you give it paired ends, produce the pair of consistent alignments with highest total score as the primary alignments for the pair's reads, and the other alignments as secondaries.

I'm going to implement this using some simple consistency code that basically just walks the graph, and decides that alignments are consistent if they are sufficiently close in terms of number of edges traversed. Really what we want is some sort of heuristic-guided base-distance-and-orientation-aware path finding. However, looking at actual reads, empirically the problems we are seeing is the mapper having to choose between widely separated alignments for each read, and choosing a pair of very distantly separated alignments.

**Comment by ekg** [comment]
Could we implement this using positional information provided by a set of
positional paths?

**Comment by adamnovak** [comment]
We could do.

Right now I have a prototype that just uses the ID windowing, like the
rescue does, and I'm trying that on the bake-off regions. All I really need
is a yes/no in whether two alignments are consistent.

What we really should be doing, I think, to avoid having to check
consistency between all pairs of alignments for the read pair, is to find
pairs of consistent MEM seeds.

**Comment by ekg** [comment]
The distance oracle would be very helpful. I think using the paths would be
ideal. We could pre cache the path relative position of nodes not in a
particular path.

**Comment by adamnovak** [comment]
Caching or pre-computing path-relative positions was Charlie's idea here,
too, so that probably means it's a good one. It wouldn't take too many more
vectors in the xg index.

-Adam

**Comment by ekg** [comment]
I guess it would take two. One to store the distance, and the other to
store the positional path id that the distance refers to.

**Comment by adamnovak** [comment]
How about one vector per positional path, with entries for all the nodes
(and maybe an "N/A" value)? Then you could have as many paths as you want,
and declare things to be close together if they're close enough along any
path?

That only works if we're just pinning nodes to points on paths that don't
visit them, though. If we want distances *from* the path, it gets more
complex.

**Comment by ekg** [comment]
@adamnovak how are you tackling this?
