### ISSUE TITLE
using output from MUMmer to build and index genome graph

### ISSUE THREAD

**Issue by ac2278** [vgteam/vg#3114]
I've performed pairwise alignment of two genome assemblies using MUMmer. The output is a delta file. Could someone tell me what commands to run to import this file into vg for genome graph construction and indexing?.

**Comment by jeizenga** [comment]
I'm not specifically familiar with it, but I suspect the .delta file is specific to MUMmer. VG graph construction focuses on GFA files and VCF files. However, we have built auxiliary tools to import HAL files, which are the whole genome alignment output of the Cactus aligner (co-written by some of VG's developers):

https://github.com/ComparativeGenomicsToolkit/hal2vg

My bet is that your best chance of getting a .delta file into VG would be either by converting it to GFA, or converting it to HAL (possibly through a MAF intermediate?) and using hal2vg. However, I'm not particularly familiar with the ecosystem of tools supporting MUMmer. 

Perhaps @glennhickey knows more?

**Comment by glennhickey** [comment]
I think your best bet it to convert it to [PAF](https://lh3.github.io/minimap2/minimap2.html#10) with cigars, which is another pairwise alignment format.  From there you can convert it to GFA with [seqwish](https://github.com/ekg/seqwish), and GFA can then be converted into vg with `vg convert -g`

**Comment by ac2278** [comment]
Great, thanks for the suggestions.
