### ISSUE TITLE
vg giraffe falls back to single-end mapping

### ISSUE THREAD

**Issue by alxsimon** [vgteam/vg#3121]
I am very new to variation graph analysis and wanted to do some tests with my data, in the hope to call variants on the mitochondria in my model species.

I only have warnings but wanted to know if I could end up using the full power of my data, i.e. using paired-end information.

**1. What were you trying to do?**
Trying to map short paired-end reads to a graph built from mitochondrial genomes (built with pggb, pruned and indexed).

**2. What did you want to happen?**
vg giraffe maps considering paired-end reads.

**3. What actually happened?**
vg giraffe falls back to single-end mapping

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

**5. What data and command can the vg dev team use to make the problem happen?**

```
vg giraffe -t 30 -x mito_full.pruned.xg -H mito_full.pruned.gbwt -i -f GR10_interleaved.fastq.gz | vg filter -t 30 -q 5 - > GR10_giraffe.gam

warning[vg::giraffe]: Encountered 100000 ambiguously-paired reads before finding enough        
                      unambiguously-paired reads to learn fragment length distribution. Are you sure                                                                                          
                      your reads are paired and your graph is not a hairball?                  
warning[vg::giraffe]: Finalizing fragment length distribution before reaching maximum sample size                                                                                             
                      mapped 0 reads single ended with 100000 pairs of reads left unmapped     
                      mean: 0, stdev: 1                                                        
warning[vg::giraffe]: Cannot cluster reads with a fragment distance smaller than read distance 
                      Fragment length distribution: mean=0, stdev=1                            
                      Fragment distance limit: 2, read distance limit: 200                     
warning[vg::giraffe]: Falling back on single-end mapping
```

I am not sure how I am supposed to diagnose the "hairball" quality of my graph.
The graph does not seem that complex:
```
vg stats -z mito_full.pruned.vg
nodes   340
edges   371
```

**6. What does running `vg version` say?**

```
vg version v1.28.0 "Acquafredda"                               
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808                               
Built by erik@beyyo
```

Thanks for your help!

**Comment by adamnovak** [comment]
If you know the paired end distribution you are supposed to have, you can pass it in with `--fragment-mean` and `--fragment-stdev`.

You also might be interested in `--max-fragment-length`, which sets the upper limit on fragment length when estimating it. If everything seems to pair above that limit, that could explain your issue.

Are your read pairs in a random order? Sometimes when you pull them from a repository they'll come out unmappable-reads first.

Did pggb produce a single-copy genome? If your graph has 2 or more copies of everything, nothing will map unambiguously.

I'd look at the graph with Bandage to see what it looks like, and see if the single-ended mappings generally reach high mapping qualities. That would let you diagnose hairball-ness and single-copy-ness. 340 nodes also sounds quite small; you should check to make sure you actually have everything in there you expected.

**Comment by alxsimon** [comment]
@adamnovak thank you very much for pointing me to the right options. 
vg giraffe does not complain any more with fragment information. What I will do I think is get insert size stats of the different individuals I need to map to feed this to giraffe.


What could be going on in my case is that I map WGS samples on the mitochondria only (representing a small percentage of all reads), so giraffe sees a lot of reads it cannot map before reaching any mitochondrial one.

Read pairs were in a random order indeed, I tried both with raw reads and filtered ones with fastp.

Regarding my graph, I think the raw graph produced by pggb is fine. It is mostly linear, except at one end where it may be a bit hairbally (the attached picture is just a small part of the complete graph).

![Screenshot from 2020-12-17 15-51-25](https://user-images.githubusercontent.com/9567176/102598179-e95c6100-411b-11eb-8aa3-37eecb695058.png)

![end](https://user-images.githubusercontent.com/9567176/102598417-4821da80-411c-11eb-9593-e2780376b22e.png)

Thanks again for your feedback.
