### ISSUE TITLE
vg giraffe - use pre-computed snarls

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#3122]
Is there a way to pre-compute snarls using vg snarls and use it in vg giraffe? 
Repeating the snarl computing for every mapping is time and memory consuming and it would be nice to have a way to use pre-computed snarls and give it to vg giraffe as a option.

**Comment by adamnovak** [comment]
You can't feed in snarls, but Giraffe only makes the snarls to make the distance index, and you can feed in the distance index.

Giraffe can make the distance index file and then you can keep it around for the next run, or you can make it from the graph and snarls with `vg index -j graph.dist -s graph.snarls graph.xg` (or `.vg`). The snarls need to have come from a `vg snarls` run with `--include-trivial`.

**Comment by jeizenga** [comment]
It seems like this issue was resolved, so I'm going to close it. Please let us know if you still have questions.
