### ISSUE TITLE
vg view error

### ISSUE THREAD

**Issue by fantasticair** [vgteam/vg#3128]
Hello 
    I use the standard `GFA` format input the `vg view` to convert it, but get this error : 
```
error [vg convert]: Input GFA is not acceptable.
error:[gfa_to_handle_graph] Could not parse sequence ID 's1'. GFA sequence IDs must be integers >= 1.
```
 My `GFA` file content as follows:
```
S       s1      ATccatccccaaccccaatccctcatcccaatcccatcatcccatcaccccaatcccaccaccccaatcccaatcctcATCCCgtcatcccaatcccaatctCATcatcccatcaccccaatcccaatcctcaccccaatcccatcaccccaatcccaatcccatcatcccatcatcc
S       s2      GGGGTGTGAGCAgtgatggggttggggggtgatggggtggggatgtgtGGGGTGTGAGCAgtgatggggttggggggtgacGGGGTTGGGATGTGTGGGGTGTGAGCAGTGATGAGGttggggggtgatggggttggGATGTGT        LN:i:144        SN:Z:1  SO
L       s1      +       s2      +       0M      SR:i:0  L1:i:16663      L2:i:144
L       s1      +       s3      +       0M      SR:i:3  L1:i:16663      L2:i:1010
```

Finally, how to get the `vg`  format  from my file?

Best wishes!

**Comment by fantasticair** [comment]
The input file `GFA` is the result of the `minigraph`, whether have some ways to convert the format to `vg` ? Thank you!

**Comment by adamnovak** [comment]
As long as you don't have a node `s0`, you can just cut the `s` off all the node names in the GFA to produce a GFA that vg can read.

If there aren't any other lowercase `s` characters, you could try piping the GFA through `tr -d 's'`.

**Comment by adamnovak** [comment]
I think we might have some more recent logic that can do this for you. @jeizenga, do you remember?

**Comment by glennhickey** [comment]
vg can now import GFAs with non-numeric sequence ids (via #3160)
