### ISSUE TITLE
Duplicate alignment names with pair-ends reads!

### ISSUE THREAD

**Issue by sunnycqcn** [vgteam/vg#3139]
Hello developer,
I want to use vg to build a fungal pangenome graph. I have total of 148 isolate genome sequences.
The first I called the variants using GATK-pipeline.
Then I used these variants to run command:
`vg construct -r L022.fa -v fin.vcf.gz > graph.vg`
`vg index -x graph.xg  -k 11 graph.vg`
`vg index -x graph.xg -G graph.gbwt -v fin.vcf.gz graph.vg`
`vg prune -u -g graph.gbwt graph.vg > graph.pruned.vg`
`vg index -g graph.gcsa graph.pruned.vg`
`vg map -t 80 -x graph.xg -g graph.gcsa -f /isilon/saskatoon-rdc/users/fuf/BLgenome/DELLY/seq/L165_R1.fastq -f /isilon/saskatoon-rdc/users/fuf/BLgenome/DELLY/seq/L165_R2.fastq > L165.gam`
above commands can work well. I did not get any errors. But when I run this command
`vg index -d L165.gam.index -N L165.gam`
I got the errors as following:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  RocksDB operation failed: IO error: While fdatasync: L165.gam.index/000009.sst: Input/output error
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_KMtQ1H/stacktrace.txt
Please include the stack trace file in your bug report!`
Then I check the stacktrace.txt:
`Crash report for vg v1.29.0 "Sospiro"
Stack trace (most recent call last):
#15   Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x63c27d, in _start
#14   Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x1f4dd3f, in __libc_start_main
#13   Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x55db18, in main
#12   Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0xc0c5cb, in vg::subcommand::Subcommand::operator()(int, char**) const
#11   Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0xb7b3c1, in main_index(int, char**)
#10   Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0xdb4a10, in vg::get_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)>)
#9    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0xb7d311, in std::_Function_handler<void (std::istream&), main_index(int, char**)::{lambda(std::istream&)#7}>::_M_invoke(std::_Any_data const&, std::istream&)
#8    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0xb5e673, in void vg::io::for_each<vg::Alignment>(std::istream&, std::function<void (long, vg::Alignment&)> const&)
#7    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0xcc40e9, in vg::Index::cross_alignment(long, vg::Alignment const&)
#6    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x4d65b6, in vg::Index::put_traversal(long, vg::Mapping const&) [clone .cold]
#5    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x1e89b98, in __cxa_throw
#4    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x1e89a36, in std::terminate()
#3    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x1e899cb, in __cxxabiv1::__terminate(void (*)())
#2    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x55a5e2, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#1    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x55d073, in abort
#0    Object "/home/AAFC-AAC/fuf/miniconda3/envs/gatk/bin/vg", at 0x12e238b, in raise
`
I install VG by conada with version v1.29.0. By the way, did you finish the example as described in wiki (A-pangenomics-example-with-vg-(viruses))?
Thanks,
Fuyou

**Comment by glennhickey** [comment]
Please try to answer the questions in the [new issue template](https://github.com/vgteam/vg/issues/new?assignees=&labels=&template=report-a-bug.md&title=) so that we can better help you, Fuyou.

**Comment by sunnycqcn** [comment]
> Please try to answer the questions in the [new issue template](https://github.com/vgteam/vg/issues/new?assignees=&labels=&template=report-a-bug.md&title=) so that we can better help you, Fuyou.

Hello Glenn,
I have update my issue. Thanks for your suggestions.
Fuyou

**Comment by glennhickey** [comment]
`vg index -d` is deprecated and is in the process of being removed altogether (#3137).  Why are you running it?  If there's a wiki or other documentation suggesting it, we need to update it.

**Comment by sunnycqcn** [comment]
> `vg index -d` is deprecated and is in the process of being removed altogether (#3137). Why are you running it? If there's a wiki or other documentation suggesting it, we need to update it.

I think the wiki instruction is confused and should be updated.
It is working well now.
Thanks.
