### ISSUE TITLE
Create a planner with Recipes and Indexes to replace IndexManager

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#3144]
As part of #3126, we want to make `vg index` understand what indexes are needed for Giraffe and the other tools, and how to make them, and have it have a bit of smarts with regard to what indexes can be made and which jobs can be run in parallel. We also want to push down some of the things we learned about "good" pruning and path covering from toil-vg and/or our custom scripts into vg itself.

I made #3142 based on the existing IndexManager, but it turns out that Jordan has been working on a much cooler implementation that's more of a data-driven planner, which will be easier to extend with new rules and the ability to think about resource constraints.

This issue tracks implementing this new planner-based index management system, using it to replace IndexManager, and plugging it into at least some of `vg index`.

**Comment by adamnovak** [comment]
The planning logic @jeizenga has described to me so far reminds me very strongly of the backtracking used by [logic programming](https://en.wikipedia.org/wiki/Logic_programming) systems like [Prolog](https://www.cis.upenn.edu/~matuszek/Concise%20Guides/Concise%20Prolog.html), or the newer [Dialog](https://linusakesson.net/dialog/docs/choicepoints.html). Maybe some of the algorithms/principles used there will be helpful?

**Comment by jeizenga** [comment]
At this point this goal is reasonably complete, although there are still some developments I'd like to make.
