### ISSUE TITLE
Merge glenn2vcf and possibly vt into vg

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#315]
The current vcf calling pipeline relies on two external packages

https://github.com/adamnovak/glenn2vcf
http://genome.sph.umich.edu/wiki/Vt

It would be a nice simplification to just merge these into vg.  glenn2vcf, in particular, could probably stand to be more integrated into the caller.  Not a super high priority, but a reminder of something I'd like to do eventually....

**Comment by adamnovak** [comment]
We have had glenn2vcf integrated for a while now, and I think vt should probably not become part of vg. We could add more variant normalization stuff to our output, but that would be its own issue.

**Comment by ekg** [comment]
Yeah vt is a big bite. But it is smaller than other dependencies. The
problem is more that it may have a large dependency footprint.
