### ISSUE TITLE
Extract non-ref nodes

### ISSUE THREAD

**Issue by RenzoTale88** [vgteam/vg#3153]
Hello,
I have a question regarding handling the nodes inside a vg graph. I've generated a VG graph from a cactus multi-alignment of 5 genomes, converted through hal2vg to ```.pg``` format. I'd like to extract from this graph all nodes not in the reference path (genome1), and see from which of the  other paths they come from (e.g. node 137 is found in both genome 2 and 5, whereas node 138 is only in genome 3) with their position in the path as nucleotide range. Is any part of this doable?
Thank you in advance for your help
Andrea

**Comment by jeizenga** [comment]
I'm not aware of any functionality that does this directly, but you might `vg paths -A -v` useful. It will output some selection of paths as GAF alignments, which is a text-based format sort of similar to SAM. I don't know how efficient it will be, but it's at least amenable to some text-based scripting to do the analysis you're describing.

**Comment by adamnovak** [comment]
This might be easy enough to script with the `bdsg` Python module. You should be able to load the graph into a [`bdsg.bdsg.PackedGraph`](https://bdsg.readthedocs.io/en/master/rst/api.html#packedgraph) and then loop over all the nodes and find the ones that aren't on the path named "genome1".

Though now that I think of it, I'm not certain PackedGraph has efficient position lookup on a path. So you might be best off walking the other paths from start to end, keeping track of position, and printing the nodes that aren't also on the path for genome1.

**Comment by jeizenga** [comment]
That's a good idea. If you decide to go that route, it is also possible to add efficient lookup using the [`bdsg.bdsg.PositionOverlay`](https://bdsg.readthedocs.io/en/master/rst/api.html#bdsg.bdsg.PositionOverlay)

**Comment by RenzoTale88** [comment]
Sounds interesting. I've had a look at the python implementation and installed it through pip. Looking at the documentation, I am not sure on how to load a graph in memory before proceeding with the series of analyses. Would it be possible to have a few examples? Thank you again!

**Comment by jeizenga** [comment]
It seems like this issue may have been resolved. I'm going to close it, but let me know if you still have questions.
