### ISSUE TITLE
GFA P-lines from vg view don't conform to spec

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#3159]
@mlin noticed that:

1. the P-lines appear to have equal number of segments and overlaps (CIGARs), while [GFA1 spec](http://gfa-spec.github.io/GFA-spec/GFA1.html) says "If specified, the Overlaps field must have one fewer values than the number of segment names and orientations in the SegmentNames field."

1. P-lines also each appear to have a spurious trailing tab character

**Comment by ekg** [comment]
This is correct. The "cigars" should be replaced with * to conform with the
spec. It will also make the files much smaller.
