### ISSUE TITLE
1.30.0: compiltion error on Debian

### ISSUE THREAD

**Issue by mr-c** [vgteam/vg#3170]
**1. What were you trying to do?**

Build a Debian package for vg v1.30.0

**2. What did you want to happen?**

**3. What actually happened?**
```
. ./source_me.sh && g++ -I/usr/include/fastahack -I/usr/include/smithwaterman -I/usr/include/vcflib -I/usr/include/smithwaterman -I/usr/include/fastahack -I/build/vg-1.30.0+ds/include -isystem /build/vg-1.30.0+ds/include -I. -I/build/vg-1.30.0+ds/src -I/build/vg-1.30.0+ds/src/unittest -I/build/vg-1.30.0+ds/src/subcommand -I/build/vg-1.30.0+ds/include/dynamic -pthread -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -Wdate-time -D_FORTIFY_SOURCE=2 -O3 -Werror=return-type -std=c++14 -ggdb -g -g -O2 -ffile-prefix-map=/build/vg-1.30.0+ds=. -fstack-protector-strong -Wformat -Werror=format-security -DSIMDE_ENABLE_OPENMP -fopenmp-simd -O3 -mavx2 -fopenmp -MMD -MP -c -o obj/index_registry.o src/index_registry.cpp 
In file included from src/index_registry.cpp:3:
src/index_registry.hpp:207:57: error: expected class-name before ‘{’ token
  207 | class InsufficientInputException : public runtime_error {
      |                                                         ^
src/index_registry.cpp: In constructor ‘vg::InsufficientInputException::InsufficientInputException(const string&, const vg::IndexRegistry&)’:
src/index_registry.cpp:1235:5: error: type ‘std::runtime_error’ is not a direct base of ‘vg::InsufficientInputException’
 1235 |     runtime_error("Insufficient input to create " + target), target(target), inputs(registry.completed_indexes())
      |     ^~~~~~~~~~~~~

```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

I can make a Dockerfile that reproduces this (the Debian build process), if desired.

**6. What does running `vg version` say?**

```
Place vg version output here
```

**Comment by pgrosu** [comment]
@mr-c Assuming this is all building within Docker, if you run the following command, what does it report within Docker?

   `gcc --version`

**Comment by mr-c** [comment]
Hey @pgrosu !

It's Debian's default gcc version: 10.2.1-1 https://packages.debian.org/unstable/gcc

**Comment by mr-c** [comment]
```
# gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by pgrosu** [comment]
@mc-c Living on the edge :)  The goal is to try to have the following command retrieve only the stable versions:

```
sudo apt-get install build-essential git cmake pkg-config libncurses-dev libbz2-dev  \
                     protobuf-compiler libprotoc-dev libprotobuf-dev libjansson-dev \
                     automake libtool jq bc rs parallel npm curl unzip redland-utils \
                     librdf-dev bison flex gawk lzma-dev liblzma-dev liblz4-dev \
                     libffi-dev libcairo-dev libboost-all-dev
```

In order to do that, let me ask a few questions:

1) If you perform `cat /etc/apt/sources.list` what do you see?

2) What do the files under `/etc/apt/preferences.d/` contain as contents, and what are their file names?

3) If you do have a file called `/etc/apt/preferences` what are its contents?

Thanks,
~p

**Comment by mr-c** [comment]
@pgrosu This is a Debian package being built in a controlled clean environment, so all the package versions are what is in the `unstable`/`sid` repo. ([I'm the debian packager for vg](https://tracker.debian.org/pkg/vg)). So everything is without extra configuration.

If this is fixed quickly then vg 1.30.0 can be part of the next stable release of Debian; otherwise it will stay at 1.29.0

**Comment by adamnovak** [comment]
Looks like we're just missing an include that the STL used to drag along but now does not. I've opened a PR that adds what should be the missing include; does that fix it @mr-c?

**Comment by mr-c** [comment]
@adamnovak https://github.com/vgteam/vg/pull/3178 worked, thanks!
