### ISSUE TITLE
vg stats  to find coordinates of a node

### ISSUE THREAD

**Issue by egoltsman** [vgteam/vg#3175]
Hi, I'm looking for a way to tell the coordinates of a given node on the graph.   Ultimately, I'd like to know the coords/offsets on every path that contains this node.  For starters, it would be good to know just the offset relative to the "head" node

**1. What were you trying to do?**
vg stats -n 8280 -d -t   graph.xg

**2. What did you want to happen?**
Find out position of a node in the graph relative to the "head"

**3. What actually happened?**
got : 
8280 to head:   -1
8280 to tail:   -1

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
N/A
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**
```
vg version v1.29.0 "Sospiro"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808

```

Please advise, and thanks in advance.

**Comment by egoltsman** [comment]
p.s.
I was able to get the coordinate on a *specific* path using

vg find -x CHR1.w_AllPaths-n10_numeric_ids.chop-1024.xg -n 8280 -P pRef.2
8280    34336447

Is it at all possible to get the coordinates on ALL paths that contain the node?  In my case I don't what the all the paths are ahead of time.

**Comment by glennhickey** [comment]
Similar to #3153, there's not command to do this but you can get this information from the API, which can now be used in Python https://bdsg.readthedocs.io/en/master/rst/install.html#use-libbdsg-from-python

**Comment by egoltsman** [comment]
Thank you very much.  This is good to know.
