### ISSUE TITLE
how to parse gam files

### ISSUE THREAD

**Issue by ac2278** [vgteam/vg#3186]
Is there a tool that helps you parse/process gam files (i.e., the equivalent of samtools for gam files)? I'd like to get statistics on the number of reads for a sample that couldn't be mapped to the graph and also filter alignments based on MQ scores.

**Comment by jeizenga** [comment]
I think you'll find what you need in the `vg filter` subcommand, which can filter GAM alignments by various criteria. It can report counts too with the `-v` and `-V` options. If you want to see a human-readable version of the GAM, you can also use `vg view -aj` to get a JSON representation. However, the JSON format tends to be pretty computationally intensive to work with directly.

**Comment by glennhickey** [comment]
A couple other ideas:
* `vg stats -a`. 
*  convert to [GAF](https://github.com/lh3/gfatools/blob/master/doc/rGFA.md#the-graph-alignment-format-gaf) with `vg convert -G`.

**Comment by ac2278** [comment]
Thanks for the recommendations, @jeizenga and @glennhickey. Is there documentation on the vg filter and stats commands (other than the information returned when I type "vg filter" on the command line)? I can't seem to find documentation on the github wiki tab.

**Comment by jeizenga** [comment]
Unfortunately no, we haven't gotten around to making any more formal documentation. Do you have any specific questions about it? I can try to answer them here.

**Comment by ac2278** [comment]
Yes, @jeizenga! Thank you for your help.

Could you explain what each of the different fields from "vg stats -a" mean (see below for example output)? What's the difference between "Total alignments" and "Total aligned"? Is "Total Perfect" equivalent to Samtools's "properly paired" field (refer to second output)?

**vg stats -a output**
<img width="371" alt="Screen Shot 2021-02-11 at 6 45 03 PM" src="https://user-images.githubusercontent.com/6481584/107724673-43e7e880-6c99-11eb-8d7d-26824583a3a1.png">

**samtools flagstat output (alignment results for a different sample)**
<img width="449" alt="Screen Shot 2021-02-11 at 6 56 15 PM" src="https://user-images.githubusercontent.com/6481584/107725320-d341cb80-6c9a-11eb-93b3-6fb254b313a7.png">

**Comment by jeizenga** [comment]
Sure. "Total alignments" is the number of read mapping records, even if that record indicates that the read was unaligned. The "total aligned" are the alignments that are in fact aligned to the graph. "Total perfect" is the count of reads that are aligned with no mismatches, indels, or soft clips. "Total gapless" is a less stringent contingent that there are no indels. There's no direct equivalent to samtools' "properly paired" in the `vg stats` output.

**Comment by ac2278** [comment]
Thanks, @jeizenga. Is there a way to figure out which read pairs are "properly paired" using the json file? I assume there is. A "properly paired" read pair is a pair that aligns with the expected relative mate orientation and with the expected range of distances between mates. Could you tell me which fields in the json file to extract this information from (see below for example)?

![Screen Shot 2021-02-17 at 3 57 04 PM](https://user-images.githubusercontent.com/6481584/108284839-d88b9400-713a-11eb-8e95-a9387af9ab7b.png)

**Comment by jeizenga** [comment]
We haven't standardized an annotation for proper pairing, although we maybe should. We've also had recent questions about this output on https://github.com/vgteam/vg/issues/3190. This looks like the output of `vg map`, correct? If so, the `fragment` field might provide some info, but I don't know its semantics. @ekg, would these mappings still be considered properly paired with a negative `length`? Or does that indicate improper pairing?

**Comment by ac2278** [comment]
Thanks, @jeizenga. I'll take a look at that other ticket. Yes, this is the output of vg map.

**Comment by ac2278** [comment]
Hi @jeizenga, I took @glennhickey's recommendation of converting the gam file to a gaf file in hopes that it will give me information about which pair of reads are "properly map". Below are the entries for one pair of reads. I read about the GAF format [here](https://github.com/lh3/gfatools/blob/master/doc/rGFA.md#the-graph-alignment-format-gaf), but I'm still having a hard time understanding what each field is telling me. Genome graphs are completely new to me, so I'm sorry if these questions are basic. What exactly is the "path" that the entry descriptions are referring to? The path of nodes that the sequence aligns to along the graph? Do you think you could run through what the output is telling me about these two reads?

Col | Type | Description
-- | -- | --
1 | string | Query sequence name
2 | int | Query sequence length
3 | int | Query start (0-based; closed)
4 | int | Query end (0-based; open)
5 | char | Strand relative to the path: "+" or "-"
6 | string | Path matching /([><][^\s><]+(:\d+-\d+)?)+\|([^\s><]+)/
7 | int | Path length
8 | int | Start position on the path (0-based)
9 | int | End position on the path (0-based)
10 | int | Number of residue matches
11 | int | Alignment block length
12 | int | Mapping quality (0-255; 255 for missing)

`V1  "A00649:64:HLYN7DRXX:2:2142:7229:19774/1"                                                                                                                 
V2  "151"                                                                                                                                                         
V3  "0"                                                                                                                                                           
V4  "151"                                                                                                                                                         
V5  "+"                                                                                                                                                           
V6  "<43624457<43624456<43624455<43624454<43624453"                                                                                                               
V7  "160"                                                                                                                                                         
V8  "6"                                                                                                                                                           
V9  "20"                                                                                                                                                          
V10 "130"                                                                                                                                                         
V11 "151"                                                                                                                                                         
V12 "60"                                                                                                                                                          
V13 "AS:i:87"                                                                                                                                                     
V14 "bq:Z:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFF:FFFFFFFF"
V15 "cs:Z::4*AG:17*TC:13*CT:12*CG:11*TC*AG:12*GA:28*AG:5*CT:13*AG:1*TC:8*TC:6+AAGGAGCCG"                                                                          
V16 "dv:f:0.1391"                                                                                                                                                 
V17 "fn:Z:A00649:64:HLYN7DRXX:2:2142:7229:19774/2"`

`V1  "A00649:64:HLYN7DRXX:2:2142:7229:19774/2"                                                                                                                    
V2  "150"                                                                                                                                                        
V3  "0"                                                                                                                                                          
V4  "150"                                                                                                                                                        
V5  "+"                                                                                                                                                          
V6  ">43624446>43624447>43624448>43624449>43624450>43624451"                                                                                                     
V7  "192"                                                                                                                                                        
V8  "28"                                                                                                                                                         
V9  "16"                                                                                                                                                         
V10 "139"                                                                                                                                                        
V11 "150"                                                                                                                                                        
V12 "60"                                                                                                                                                         
V13 "AS:i:106"                                                                                                                                                   
V14 "bq:Z:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
V15 "cs:Z::26*AG:54+GC:3*CT:2*TC:2*CG:25*CT:2*CT:3*AG:2*CT:19*TC:1"                                                                                              
V16 "dv:f:0.0733"                                                                                                                                                
V17 "fp:Z:A00649:64:HLYN7DRXX:2:2142:7229:19774/1"`

**Comment by ac2278** [comment]
Also, does the vg team have any plans on hosting a mini course on vg implementation? I know there was a [course](https://gtpb.github.io/CPANG18/) offered a while ago.
