### ISSUE TITLE
Signal 11 crash when aligning to HPRC graph

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#3202]
**1. What were you trying to do?**
Align precision FDA reads to the human pan-genome reference graph using VG Giraffe.

**2. What did you want to happen?**
Get a BAM output from the alignment

**3. What actually happened?**
It crashed with a Signal 11 error.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.30.0-172-gb05d352c8 "Carentino"
Stack trace (most recent call last) in thread 9640:
#18   Object "", at 0xffffffffffffffff, in 
#17   Object "/vg/bin/vg", at 0x1bb9fde, in __clone
#16   Object "/vg/bin/vg", at 0x10aa18a, in start_thread
#15   Object "/vg/bin/vg", at 0x1b14f75, in gomp_thread_start
#14   Object "/vg/bin/vg", at 0xcea3d3, in unsigned long vg::io::paired_for_each_parallel_after_wait<vg::Alignment>(std::function<bool (vg::Alignment&, vg::Alignment&)>, std::function<void (vg::Alignment&, vg::Alignment&)>, std::function<bool ()>, unsigned long) [clone ._omp_fn.3]
#13   Object "/vg/bin/vg", at 0x1b173db, in gomp_team_barrier_wait_end
#12   Object "/vg/bin/vg", at 0x1b0e949, in gomp_barrier_handle_tasks
#11   Object "/vg/bin/vg", at 0xcea028, in unsigned long vg::io::paired_for_each_parallel_after_wait<vg::Alignment>(std::function<bool (vg::Alignment&, vg::Alignment&)>, std::function<void (vg::Alignment&, vg::Alignment&)>, std::function<bool ()>, unsigned long) [clone ._omp_fn.4]
#10   Object "/vg/bin/vg", at 0xa22fc1, in std::_Function_handler<void (vg::Alignment&, vg::Alignment&), main_giraffe(int, char**)::{lambda()#1}::operator()() const::{lambda(vg::Alignment&, vg::Alignment&)#3}>::_M_invoke(std::_Any_data const&, vg::Alignment&, vg::Alignment&)
#9    Object "/vg/bin/vg", at 0x1015064, in vg::io::AlignmentEmitter::emit_mapped_pair(std::vector<vg::Alignment, std::allocator<vg::Alignment> >&&, std::vector<vg::Alignment, std::allocator<vg::Alignment> >&&, long)
#8    Object "/vg/bin/vg", at 0xd10545, in vg::SurjectingAlignmentEmitter::emit_mapped_pairs(std::vector<std::vector<vg::Alignment, std::allocator<vg::Alignment> >, std::allocator<std::vector<vg::Alignment, std::allocator<vg::Alignment> > > >&&, std::vector<std::vector<vg::Alignment, std::allocator<vg::Alignment> >, std::allocator<std::vector<vg::Alignment, std::allocator<vg::Alignment> > > >&&, std::vector<long, std::allocator<long> >&&)
#7    Object "/vg/bin/vg", at 0xbb764f, in vg::Surjector::surject(vg::Alignment const&, std::unordered_set<handlegraph::path_handle_t, std::hash<handlegraph::path_handle_t>, std::equal_to<handlegraph::path_handle_t>, std::allocator<handlegraph::path_handle_t> > const&, bool, bool) const
#6    Object "/vg/bin/vg", at 0xbb6b41, in vg::Surjector::surject_internal(vg::Alignment const*, vg::multipath_alignment_t const*, vg::Alignment*, vg::multipath_alignment_t*, std::unordered_set<handlegraph::path_handle_t, std::hash<handlegraph::path_handle_t>, std::equal_to<handlegraph::path_handle_t>, std::allocator<handlegraph::path_handle_t> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, long&, bool&, bool, bool) const
#5    Object "/vg/bin/vg", at 0xbb5cc2, in vg::Surjector::realigning_surject(handlegraph::PathPositionHandleGraph const*, vg::Alignment const&, handlegraph::path_handle_t const&, std::vector<std::pair<std::pair<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, vg::Path>, std::allocator<std::pair<std::pair<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, vg::Path> > > const&, std::pair<handlegraph::step_handle_t, handlegraph::step_handle_t>&, bool, bool, bool) const [clone .constprop.1153]
#4    Object "/vg/bin/vg", at 0xc29c82, in vg::MultipathAlignmentGraph::align(vg::Alignment const&, handlegraph::HandleGraph const&, vg::GSSWAligner const*, bool, unsigned long, bool, unsigned long, double, unsigned long, vg::multipath_alignment_t&, bool)
#3    Object "/vg/bin/vg", at 0xc26b47, in vg::MultipathAlignmentGraph::align(vg::Alignment const&, handlegraph::HandleGraph const&, vg::GSSWAligner const*, bool, unsigned long, bool, unsigned long, double, std::function<unsigned long (vg::Alignment const&, handlegraph::HandleGraph const&)>, vg::multipath_alignment_t&, bool)
#2    Object "/vg/bin/vg", at 0xc36b8a, in vg::Aligner::align_global_banded_multi(vg::Alignment&, std::vector<vg::Alignment, std::allocator<vg::Alignment> >&, handlegraph::HandleGraph const&, int, int, bool) const
#1    Object "/vg/bin/vg", at 0xdf87e0, in vg::BandedGlobalAligner<int>::align(signed char*, signed char*, signed char, signed char)
#0    Object "/vg/bin/vg", at 0xddf7fc, in vg::BandedGlobalAligner<int>::BAMatrix::fill_matrix(handlegraph::HandleGraph const&, signed char*, signed char*, signed char, signed char, bool, int)
```

**5. What data and command can the vg dev team use to make the problem happen?**
Graph reference and indexes obtained from `s3://vg-k8s/vgamb/wg/cactus/GRCh38-freeze1/GRCh38-freeze1.cactus.feb10`
Reads from:
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/test_input_reads/HG003.novaseq.pcr-free.35x.R1.fastq.gz`
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/test_input_reads/HG003.novaseq.pcr-free.35x.R2.fastq.gz`

The command:
```
vg giraffe \
-x GRCh38-freeze1.cactus.feb10.xg \
-H GRCh38-freeze1.cactus.feb10.gbwt \
-m GRCh38-freeze1.cactus.feb10.min \
-g GRCh38-freeze1.cactus.feb10.gg \
-d GRCh38-freeze1.cactus.feb10.dist \
-f HG003.novaseq.pcr-free.35x.R1.fastq.gz \
-f HG003.novaseq.pcr-free.35x.R2.fastq.gz \
--output-format BAM \
-p \
-t 32 > giraffe_all_wgs.grch38_pgrc.HG003.bam
```

**6. What does running `vg version` say?**

```
vg version v1.30.0-172-gb05d352c8 "Carentino"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by root@1f854fe63676
```

**Comment by cmarkello** [comment]
Graph reference indexes more easily accessible from:
https://storage.googleapis.com/cmarkell-vg-wdl-dev/debug_pgrc_graph/GRCh38-freeze1.cactus.feb10.xg
https://storage.googleapis.com/cmarkell-vg-wdl-dev/debug_pgrc_graph/GRCh38-freeze1.cactus.feb10.gbwt
https://storage.googleapis.com/cmarkell-vg-wdl-dev/debug_pgrc_graph/GRCh38-freeze1.cactus.feb10.min
https://storage.googleapis.com/cmarkell-vg-wdl-dev/debug_pgrc_graph/GRCh38-freeze1.cactus.feb10.gg
https://storage.googleapis.com/cmarkell-vg-wdl-dev/debug_pgrc_graph/GRCh38-freeze1.cactus.feb10.dist

**Comment by adamnovak** [comment]
I will see if I can reproduce this, and maybe narrow it down to an offending read/pair.

**Comment by adamnovak** [comment]
OK, the problem is surjecting read `A00744:46:HV3C3DSXX:2:1124:18439:36652`, at its mapping that starts at node 95642170. The banded global aligner decides it needs a 3.6 megabase `band_height`, gets a null result from [this](https://github.com/vgteam/vg/blob/9476278df04c0147d5d3a2cc1b0d695b2bb51e0f/src/banded_global_aligner.cpp#L257) malloc (despite succeeding the equally-sized malloc right before it and only actually having 87.1g `res` memory, somehow), and segfaults [here](https://github.com/vgteam/vg/blob/9476278df04c0147d5d3a2cc1b0d695b2bb51e0f/src/banded_global_aligner.cpp#L300) trying to index into a null array.

So it's a segfault instead of a controlled abort because we don't check our malloc return values like we always should. And I think the malloc is returning null not because we have run out of memory, but because we have run out of virtual address space; `top` pegs our `virt` as `128.0t`, which happens to be [a Linux kernel limit](https://unix.stackexchange.com/q/61085) for a process's virtual memory size.

I'm not sure how to see why we've run out of virtual memory, but hopefully it has something to do with whatever is making the surjection try to use a 3 megabase band.

**Comment by adamnovak** [comment]
@jeizenga Any idea why it might want the bands that big? It looks like within about 20 nodes of 95642170, we manage to touch parts of chr9 that are over 20 megabases from each other. Is the surjector designed to be able to handle this?

**Comment by jeizenga** [comment]
My guess would be that there's a cycle that conflates two distal sequences on the same path, and this read aligns to unique sequence on either side of the cycle. Default `surject` treats the alignment with a lot of deference, so it will absolutely try to align 1bp of read sequence to 20Mbp of graph sequence to preserve the path-overlapping segments of the graph alignment.

**Comment by cmarkello** [comment]
@jeizenga, @jmonlong mentioned this might be related to https://github.com/vgteam/vg/issues/2812

**Comment by jeizenga** [comment]
Yeah, that's a similar problem, I suspect. I'm having trouble thinking of a general way to decide what to do in these scenarios.

**Comment by adamnovak** [comment]
OK, digging into the jemalloc statistics, our problem seems to be that many times more memory than we're currently using is ending up in jemalloc's "retained" state, where it isn't using physical memory but is also part of the virtual address space.

This is supposed to be controlled by their [`opt.retain`](http://jemalloc.net/jemalloc.3.html#opt.retain), which they default to off to prevent address space exhaustion (exactly what we're seeing). Except that on 64 bit Linux, they default it to on, to avoid "semi-permanent VM map holes". They don't seem to think it's feasible to exhaust the 64 bit address space, and it kind of isn't, but they don't seem to know about the lower kernel limit we're hitting.

I think we might try turning off `opt.retain` and taking our chances with the VM map holes, whatever those really are.

**Comment by glennhickey** [comment]
This graph has nodes chopped to 1024bp (as opposed to the usual 32).  I wonder if this (in addtion, of course, to the crazy SVs) is playing a part in these errors?

**Comment by jeizenga** [comment]
Yeah, I noticed a while ago that even though dozeu has a pretty sophisticated implementation for its internal stack, the safe methods for memory allocation are basically never used. Instead it just directly manipulates stack pointers without checking whether the memory is allocated. I think we've been saved by the fact that it also pre-allocates 4MB of memory, and the alignment problems we've been throwing at it all fit in that amount of memory.
