### ISSUE TITLE
minigraph gfa failing

### ISSUE THREAD

**Issue by cistarsa** [vgteam/vg#3203]
**1. What were you trying to do?**
Convert minigraph.gfa to vg using most recent docker build as:
```docker run --rm quay.io/vgteam/vg:latest vg convert -g CPB_Feb5.gfa```

**2. What did you want to happen?**
generate vg

**3. What actually happened?**
Signal 6.
```vg: /vg/include/gfakluge.hpp:569: size_t gfak::mmap_open(const string&, char*&, int&): Assertion `false' failed.```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
NA
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**

```
vg: variation graph tool, version v1.30.0 "Carentino"

```

**Comment by jeizenga** [comment]
It looks like that might be caused by the GFA filename being misspelled, or perhaps from not having read/write permissions for it. Could you check to make sure that neither of those is the cause?

**Comment by glennhickey** [comment]
Yeah, it's not finding the file.  With `docker run`, you need to use `-v` to mount the directory your input is in within the container: something like `docker run -v $(pwd):/data --rm quay.io/vgteam/vg:latest vg convert -g /data/CPB_Feb5.gfa`.  Usually much simpler to download and use the binary release. 

But... rGFA support is not yet in any release.  So neither the binary release nor the vg:latest container will work with your file (you would hopefully get an informative error message if you tried).  The only way around would be to build the master branch from source, or roll the dice on one of the newer images made by the CI: https://quay.io/repository/vgteam/vg?tab=tags

**Comment by cistarsa** [comment]
whoops. rookie docker mistake...yeah, I had gone the long route of running "pggb" iteratively to generate vg but the graph didn't have any snarls so trying the update you had mentioned from last month. 
Thanks for the CI suggestion, will this be rolled out with the new build in a couple weeks?

**Comment by cistarsa** [comment]
omg i think it worked :joy:  with 
```bash
$ docker run -v $(pwd):/data --rm quay.io/vgteam/vg:ci-2785-69b052f68df85d69f80f0ad52f685ef05ac3dc60 vg convert -g /data/CPB_Feb5.gf -v CPB_Feb5.vg
```

I'll close this for now but will (most likely) reach out again soon-thanks!
