### ISSUE TITLE
ERROR: Signal 11 occurred. VG has crashed.

### ISSUE THREAD

**Issue by minjinhan** [vgteam/vg#3209]
**1. What were you trying to do?**
   Call variations through mapping NGS data to constructed graph genome

**2. What did you want to happen?**
   We want to obtain VCF file containing variations

**3. What actually happened?**
    ERROR: Signal 11 occurred

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.30.0 "Carentino"
Stack trace (most recent call last) in thread 357824:
#8    Object "", at 0xffffffffffffffff, in 
#7    Object "/home/miniconda3/bin/vg", at 0x1d6e8c2, in __clone
#6    Object "/home/miniconda3/bin/vg", at 0x11f7288, in start_thread
#5    Object "/home/miniconda3/bin/vg", at 0x1cb73bd, in gomp_thread_start
#4    Object "/home/miniconda3/bin/vg", at 0xd82fb5, in vg::SnarlManager::for_each_top_level_snarl_parallel(std::function<void (vg::Snarl const*)> const&) const [clone ._omp_fn.0]
#3    Object "/home/miniconda3/bin/vg", at 0xdb71e8, in std::_Function_handler<void (vg::Snarl const*), vg::GraphCaller::call_top_level_snarls(handlegraph::HandleGraph const&, int, bool)::{lambda(vg::Snarl const*)#1}>::_M_invoke(std::_Any_data const&, vg::Snarl const*&&)
#2    Object "/home/miniconda3/bin/vg", at 0xdc5602, in vg::FlowCaller::call_snarl(vg::Snarl const&, int)
#1    Object "/home/miniconda3/bin/vg", at 0x1081b83, in vg::FlowTraversalFinder::find_weighted_traversals(vg::Snarl const&, bool)
#0    Object "/home/miniconda3/bin/vg", at 0x10d6497, in vg::algorithms::yens_k_widest_paths(handlegraph::HandleGraph const*, handlegraph::handle_t, handlegraph::handle_t, unsigned long, std::function<double (handlegraph::handle_t const&)>, std::function<double (std::pair<handlegraph::handle_t, handlegraph::handle_t> const&)>, bool)

```

**5. What data and command can the vg dev team use to make the problem happen?**
  
The processes of graph genome construction, mapping and call variation are as follows:

vg construct -r genome.fa -v All_samples_mergedSVs.vcf -t 55 -S -f >Samples_SVs.vg;
vg index -x Samples_SVs.xg -g Samples_SVs.gcsa -k 16 -b /home/data/SV/tmp/ -t 55 -p Samples_SVs.vg;
vg snarls Samples_SVs.xg -t 55 > Samples_SVs.snarls;
vg map -t 55 -d Samples_SVs -f Sample1_1.fq.gz -f Sample1_2.fq.gz > Sample1.gam;
vg augment -t 55 Samples_SVs.vg Sample1.gam -A aug_Sample1.gam >aug_Sample1.vg;
vg index aug_Sample1.vg -x aug_Sample1.xg -t 55";
vg pack -x aug_Sample1.xg -g aug_Sample1.gam -Q 5 -o aug_Sample1.pack -t 55";
vg snarls aug_Sample1.xg -t 55 >aug_Sample1.snarls";

**Above steps are smoothy. BUT the ERROR: Signal 11 occurred at the next step:**

vg call aug_Sample1.xg -k aug_Sample1.pack -r aug_Sample1.snarls -t 55 >Sample1.vcf

The size of aug_Sample1.xg file  is  11.65 GB.
The size of aug_Sample1.pack file is 1.53GB.
The All_samples_mergedSVs.vcf file contain non-redundant PAVs (insertions and deletions）from 600 samples.

Our server： 60 cores and 256GB RAM

**6. What does running `vg version` say?**

```
ERROR: Signal 11 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_MLEF14/stacktrace.txt
Please include the stack trace file in your bug report!
```

**Comment by minjinhan** [comment]
Hello guys, we would be very grateful for suggestions to fix this problem.

**Comment by jmonlong** [comment]
I'm getting the same issue when I'm trying to call variants in the cactus-HPRC pangenomes. 

@glennhickey if you want to reproduce I was running:

```
vg call -k GRCh38-freeze1.cactus.feb10.HG002.giraffe29k11wpaths.pack -t 8 -s HG002 --snarls GRCh38-freeze1.cactus.feb10.snarls GRCh38-freeze1.cactus.feb10.xg > out.vcf
```

and the data is in `s3://vg-k8s/vgamb/wg/cactus/`:
- `feb10/map/GRCh38-freeze1.cactus.feb10.HG002.giraffe29k11wpaths.pack`
- `feb10/map/GRCh38-freeze1.cactus.feb10.snarls`
- `GRCh38-freeze1/GRCh38-freeze1.cactus.feb10.xg`

I also got *Signal 11* error. The stack trace is sligthly different but it looks like the same issue:

```
Crash report for vg v1.30.0-172-gb05d352c8 "Carentino"
Stack trace (most recent call last):
#12   Object "/vg/bin/vg", at 0x431279, in _start
#11   Object "/vg/bin/vg", at 0x1b25ff8, in __libc_start_main
#10   Object "/vg/bin/vg", at 0x40b0eb, in main
#9    Object "/vg/bin/vg", at 0x9d44d7, in vg::subcommand::Subcommand::operator()(int, char**) const
#8    Object "/vg/bin/vg", at 0x97b973, in main_call(int, char**)
#7    Object "/vg/bin/vg", at 0xc88b16, in vg::GraphCaller::call_top_level_snarls(handlegraph::HandleGraph const&, int, bool)
#6    Object "/vg/bin/vg", at 0xc5c5d6, in vg::SnarlManager::for_each_top_level_snarl_parallel(std::function<void (vg::Snarl const*)> const&) const
#5    Object "/vg/bin/vg", at 0x1b0bf0e, in GOMP_parallel
#4    Object "/vg/bin/vg", at 0xc5af84, in vg::SnarlManager::for_each_top_level_snarl_parallel(std::function<void (vg::Snarl const*)> const&) const [clone ._omp_fn.0]
#3    Object "/vg/bin/vg", at 0xc8d211, in std::_Function_handler<void (vg::Snarl const*), vg::GraphCaller::call_top_level_snarls(handlegraph::HandleGraph const&, int, bool)::{lambda(vg::Snarl const*)#1}>::_M_invoke(std::_Any_data const&, vg::Snarl const*&&)
#2    Object "/vg/bin/vg", at 0xc97501, in vg::FlowCaller::call_snarl(vg::Snarl const&, int)
#1    Object "/vg/bin/vg", at 0xd8d14b, in vg::FlowTraversalFinder::find_weighted_traversals(vg::Snarl const&, bool)
#0    Object "/vg/bin/vg", at 0xf965e8, in vg::algorithms::yens_k_widest_paths(handlegraph::HandleGraph const*, handlegraph::handle_t, handlegraph::handle_t, unsigned long, std::function<double (handlegraph::handle_t const&)>, std::function<double (std::pair<handlegraph::handle_t, handlegraph::handle_t> const&)>, bool)
```

**Comment by glennhickey** [comment]
Ugh, this seems to be a multithreading issue, which is not at all what I expected.  I'm trying to figure it out, but if you want a slow work-around now, running with `-t 1` should fix it.
