### ISSUE TITLE
overlap graph import and support

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#321]
I'm going to extend vg to read overlap graphs. This would be easiest if we actually add support for manipulating them, such as via the protobuf schema. I don't think anything serious needs to change, just the addition of two fields on each edge that explain how far in each node these reach (if we want approximate overlaps, as is used in miniasm) or maybe just one number (if we want to support overlap graphs as in fermikit).

We can make vg validate complain if you give it one in this format, but at least it should be supported internally for certain operations.

**Comment by edawson** [comment]
Let me know if there's anything that needs to change in the GFA parser. It should just be a matter of adding a few calls to fill in the new schema bits.

**Comment by ekg** [comment]
Is the match field at the end of the link line (L) provided in the API in
gfakludge?

**Comment by edawson** [comment]
The match field? Is that the CIGAR for the overlap?
I parse all of the standard fields but no optional ones for link lines; that's an easy fix though.

**Comment by ekg** [comment]
Yep that's all!

**Comment by edawson** [comment]
As an update to this, I'm planning on extending the GFA parser to read/write DAS (the new name for GFA2). This should be in by late October as it's just a lot of copy pasta.

IIRC to fully implement overlap graphs we would need some wacky normalization or more permissiveness in our schema - is that the conclusion we've come to with this? What's your status on #190 , @ekg , and other necessary items / are we still planning on supporting overlaps?

**Comment by ekg** [comment]
@edawson I am not sure what we will need to do to support dasDAS graph format.

In vg we represent an assembly as a blunt ended graph. Sequences are described as walks though the graph (paths).

We have overlaps on edges to allow reading in overlap graphs. But these don't make sense from any algorithm in vg except the one that bluntifies the graph.

For dasDAS support things will get weird. A graph in that format is basically a collection of nodes, each representing a contig or input sequence. Between these sequences we have mappings from one subsequence to another subsequence (as E or M records... I can't remember where things have ended up). These records are equivalent to Translation objects in vg, where from and to are in the same graph, not at different stages in the history of a series of edits to a graph. We could introduce a new type but it would remain the same: a pair or paths describing the relationship between two parts of the graph.

It looks to me that there will need to be a reductive step to produce a blunt end string graph like we use in vg from an assembly encoded this way.

**Comment by edawson** [comment]
I was only planning to support a subset of dasDAS (enough to produce DAS from vg and read our own DAS back in). I will look more deeply into the matter but it was my understanding that GFA could be represented as a reduced set of DAS records.

**Comment by ekg** [comment]
A link is represented as a 0-length translation (mapping/E record...?)
between and end of one sequence and the end of another. But this is of
course just a special case among many things that this perspective allows
us to represent.

The problem is that this isn't a valid graph in vg. It's a high-level
description of the relationship between the components that went into the
assembly. We would represent the same data as a blunt-ended graph through
which the contigs/sequences are paths. If we want to work on that object we
need to project dasDAS into it, just as we do with overlap graphs from GFA.
It seems we can convert back and forth although it isn't clear if this
could be done efficiently.

I still need to get the conversion working right for overlap graphs.
Probably there is a way to project from dasDAS graphs into overlap graphs,
and then from those into blunt ended graphs with embedded paths.

**Comment by adamnovak** [comment]
We only have import support right now, but I'm going to close this anyway. If we embark on a project to bring overlap support to the entire vg codebase, we can make a bunch of new issues for that.
