### ISSUE TITLE
GCSA Indexing Silently failing?

### ISSUE THREAD

**Issue by cademirch** [vgteam/vg#3227]
**1. What were you trying to do?**
Create GCSA index for large graph with haplotypes (using pruned graphs) - following the Construction Examples on the wiki.

**2. What did you want to happen?**
Create a GCSA index.

**3. What actually happened?**
Indexing starts (tmp files being created), but stops at some point. No gcsa or gcsa lp files are created. No error or stack trace in the captured stderr.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
No strack trace, strangely.
```

**5. What data and command can the vg dev team use to make the problem happen?**
I can supply data if need be. The command used: `vg index -g all.gcsa -f node_mapping -p [unfolded chr graphs] 2> log`

**6. What does running `vg version` say?**

```
vg version v1.31.0 "Caffaraccia"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by ubuntu@ip-172-31-30-191
```

Thankful for any advice or suggestions to figure out the issue.

**Comment by jltsiren** [comment]
If your command was something like
```
vg index -g all.gcsa -f node_mapping -g chr1.unfolded.vg chr2.unfolded.vg chr3.unfolded.vg ...
```
the second `-g` overrode the first. The command probably built GCSA for chr2, chr3, and so on, and wrote the index to `chr1.unfolded.vg`and `chr1.unfolded.vg.lcp`. Because option `-p` was not used, nothing was written into the log file.

**Comment by cademirch** [comment]
> If your command was something like
> 
> ```
> vg index -g all.gcsa -f node_mapping -g chr1.unfolded.vg chr2.unfolded.vg chr3.unfolded.vg ...
> ```
> 
> the second `-g` overrode the first. The command probably built GCSA for chr2, chr3, and so on, and wrote the index to `chr1.unfolded.vg`and `chr1.unfolded.vg.lcp`. Because option `-p` was not used, nothing was written into the log file.

Ah sorry thats a typo in my post, I will fix that. The command I used was:
 `bin/vg_1.31 index -b tmp/ -g all.gcsa -f /node_mapping -p [graphs] 2> log`
And I did capture the progress, with the last ten lines reading:
```
GCSA::GCSA(): Step 4 (path length 128 -> 256)
PathGraph::prune(): 1486768075 -> 1396075784 paths (955690090 ranges)
PathGraph::prune(): 774173855 unique, 236 redundant, 290682830 unsorted, 331218863 nondeterministic paths
PathGraph::prune(): 60.2572 GB in 7 file(s)
PathGraph::read(): File 0: Read 7835026 order-128 paths
PathGraph::extend(): File 0: Created 37576991 order-256 paths
PathGraph::read(): File 0: Read 37576991 order-256 paths
PathGraphBuilder::sort(): File 0: Sorted 37576991 paths
PathGraph::read(): File 1: Read 286509100 order-128 paths
PathGraph::extend(): File 1: Created 2021807060 order-256 paths
```

**Comment by jltsiren** [comment]
How much memory did you have? In the fourth prefix-doubling step, the number of paths in the second graph file increases from ~286 million to over 2 billion. That's more than we usually see in the largest chromosomes of the 1000GP graph, and you will probably need well over 100 GB to work with that many paths.

If you did prune the graphs with `vg prune` before trying to index them, there are probably too many high-degree nodes in the graph. Such nodes are not pruned by default, but you can remove them by rerunning `vg prune` with option `-M 32`. That option removes all nodes with degree over 32.

**Comment by cademirch** [comment]
I see. Our machine has 128G of memory, I was thinking that the job probably got killed due to insufficient memory and thus the lack of errors. I will try rerunning prune with that setting. Thank you.

**Comment by jltsiren** [comment]
I don't think I've ever seen a situation like that before. What kind of data do you have, and how many haplotypes do you have in the GBWT? Can you share the files?

The fraction of nondeterministic paths seems very high. It could be possible that there are many complex regions with many distinct local haplotypes, creating a high degree of sequence duplication in the unfolded graph. Assuming that the second graph file is the worst, a 256 GB system should still be able to finish the construction.

**Comment by cademirch** [comment]
I'm working with drosophila variation data. A VCF with about 800 individuals and a linear reference was used as input for graph construction. `vg gbwt -H`reports 2140 haplotypes which sounds about right. I can make the files available, which would be the most helpful?

**Comment by jltsiren** [comment]
Please make all the files (reference, VCF, graph, GBWT) available. I may have to rebuild the GBWT to see what is going on.

**Comment by cademirch** [comment]
@jltsiren, sorry for the delay - I am now working on packaging up all the data and hosting it...  is it alright if I email you to give you the info to access the data?

**Comment by jltsiren** [comment]
@cademirch You can email the information to jltsiren@gmail.com.

**Comment by jltsiren** [comment]
I was able to build GCSA for the unfolded graph using 165 GB memory. The size of the final index is 7.5 GB. Both figures are too large for a graph of this size.

This seems to be a VCF normalization issue or a graph construction issue. Here is one example of a problematic region: [original.pdf](https://github.com/vgteam/vg/files/6322270/original.pdf).

Node 1000014 has multiple successors with sequence starting with C. The region encodes 0 to 6 copies of CA, but there are often many paths that encode the same sequence. GCSA does not like this kind of nondeterminism. The same structure (nodes ...15 to ...21) can be represented better as a chain of 6 nodes with label CA each, with edges to the next node in the chain and to node ...22.

**Comment by cademirch** [comment]
Interesting. Thank you for looking into this @jltsiren. Could you share the commands and options you used to construct the index?

**Comment by jltsiren** [comment]
I didn't record the exact commands, but it was just the normal pruning/unfolding with `vg prune -u` and GCSA construction with `vg index -g` using the node mapping from `vg prune`.
