### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#3242]
I attempted to build vg from a fresh clone, first using `make -j 8`, and then just `make`:

```
-> % make 
. ./source_me.sh && cd deps/fermi-lite && make  && cp *.h /home/erik/vg/include/ && cp libfml.a /home/erik/vg/lib/
make[1]: Entering directory '/home/erik/vg/deps/fermi-lite'
gcc -g -Wall -O2 -Wno-unused-function  libfml.a example.o -o fml-asm -L. -lfml -lm -lz -lpthread
/usr/bin/ld: ./libfml.a(rope.o):/home/erik/vg/deps/fermi-lite/rle.h:33: multiple definition of `rle_auxtab'; ./libfml.a(misc.o):/home/erik/vg/deps/fermi-lite/rle.h:33: first defined here
/usr/bin/ld: ./libfml.a(rle.o):/home/erik/vg/deps/fermi-lite/rle.h:33: multiple definition of `rle_auxtab'; ./libfml.a(misc.o):/home/erik/vg/deps/fermi-lite/rle.h:33: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:20: fml-asm] Error 1
make[1]: Leaving directory '/home/erik/vg/deps/fermi-lite'
make: *** [Makefile:666: lib/libfml.a] Error 2
```

What might be the problem?

**Comment by jltsiren** [comment]
This seems to be a fermi-lite issue.

`rle.h` declares `const uint8_t rle_auxtab[8]`, which is then defined in `rle.c`. If I compile fermi-lite with Apple clang 12.0.0 or GCC 9.3.0, it works fine. If I try GCC 10.2.0, I get a similar linker error. If I change the declaration to `extern const uint8_t rle_auxtab[8]`, GCC 10.2.0 is also able to compile it.

I'm not familiar enough with the C standard to tell which compiler is behaving correctly.

**Comment by jeizenga** [comment]
We're depending on our own fork though, so we could just fix it

**Comment by jltsiren** [comment]
Apparently vgteam/fermi-lite#2 already fixed that, but it's not in the vg master yet.
