### ISSUE TITLE
Try to construct vg from the clustal sequence alignment

### ISSUE THREAD

**Issue by minu7** [vgteam/vg#3253]
**1. What were you trying to do?**
Try to construct vg from the clustal sequence alignment

**2. What did you want to happen?**
I wanted to get the vg graph

**3. What actually happened?**
```
ERROR: Signal 11 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_1O0UKf/stacktrace.txt
Please include the stack trace file in your bug report!
```
**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg not-from-git
Stack trace (most recent call last):
#5    Object "/vg/bin/vg", at 0x591b8d, in _start
#4    Object "/vg/bin/vg", at 0x1d30dff, in __libc_start_main
#3    Object "/vg/bin/vg", at 0x56a0b4, in main
#2    Object "/vg/bin/vg", at 0xb7f03b, in vg::subcommand::Subcommand::operator()(int, char**) const
#1    Object "/vg/bin/vg", at 0xbca451, in main_construct(int, char**)
#0    Object "/vg/bin/vg", at 0xc38314, in vg::MSAConverter::load_alignments(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```

**5. What data and command can the vg dev team use to make the problem happen?**
command:
```
vg construct -M mult_seq_aln.clustal -F clustal -m 32 > msa.vg

```
Data: https://filebin.net/xxefd1q3fmus80f6/mult_seq_aln.clustal

**6. What does running `vg version` say?**

```
vg version not-from-git
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by root@150f26db8240
```

**Comment by minu7** [comment]
Thanks in advance for the help!

**Comment by jeizenga** [comment]
Are you positive this is the exact command and data you used? I tried to replicate the crash on both a macOS and CentOS machine, but couldn't replicate it on either.

**Comment by minu7** [comment]
I rebuilt the docker image and it works.
The vg version is the same.
Honestly, I don't know what changed.
Thank you for the help!
