### ISSUE TITLE
Question on GAF format

### ISSUE THREAD

**Issue by RenzoTale88** [vgteam/vg#3267]
Hello,
I got a simple question on the output gaf format.
I've seen the description (here)[]
Assuming a couple of reads as follow:
```
READ1   75      0       75      +       <1<2<3     93      6       19      74      75      60      AS:i:80 bq:Z:AAFAFJJJJJJJJJJJJJJJJJJJFJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJ        cs:Z::73*GC:1   dv:f:0.0133     fn:Z:READ1
READ1   75      0       75      +       >3>2>1     93      14      25      72      75      60      AS:i:77 bq:Z:#AAFFJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJFJJJJJJJJJJJJJJJJFJFJ        cs:Z:*AN:72+CT  dv:f:0.04       fp:Z:READ1
``` 
The read is 75nt long, and aligns on nodes 1-3. My doubt is: the alignment starts at base 6 of the path selected, and ends at base 19 of the same path, which indicates a total of 13 bases aligned. However, the CS field indicates 73 matches, 1 substitution and then another match, leaving me confused regarding the positioning of the end of the alignment. 
This possible make sense if the position is the base on the last node: the alignment starts at base 6 of node 1, and finishes at base 19 of node 3. Am I correct?
Thank you in advance
Andrea

**Comment by glennhickey** [comment]
Yeah, those offsets are node-relative.  But... reading [the spec](https://github.com/lh3/gfatools/blob/master/doc/rGFA.md#the-graph-alignment-format-gaf) again, it's listed as "End position on the path (0-based)" which I think is closer to your original interpretation.  So I will change it in vg.  Thanks!

(vg doesn't actually use that field since it can be inferred from the cigar, which is probably why it wasn't caught before)

**Comment by RenzoTale88** [comment]
@glennhickey thank you very much for clarifying this, just needed to confirm it. Yes, initially I was simply using the initial base and the cs field to define the end position, but I wanted to be sure to be matching the final position as "sanity check" for my code :)
One more question: do you mind clarifying the `fn`, `fp` and `dv` fields, since not "canonical"? 

I'm guessing `fp` stand for fragment positive, and `fn` for fragment negative, am I correct?
