### ISSUE TITLE
Lower case warning wrong in at least some cases

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#327]
I can't figure out the warning here

https://github.com/vgteam/vg/blob/master/src/vg.cpp#L3266-L3272

It seems to be checking if the fasta sequence *names* or (-R region) are upper case, rather than the DNA sequences themselves.  Am I missing something?

**Comment by ekg** [comment]
It does indeed give that impression.

**Comment by edawson** [comment]
Oops. That's definitely what's happening; my mistake.

Looks like we need call is_upper() on the bit fed to parse_region?

**Comment by ekg** [comment]
Isn't the problem with lower case DNA sequences?

**Comment by edawson** [comment]
Yes. I mistakenly thought that's what target was.
