### ISSUE TITLE
vg call: Why does the variant at position x now include information about the site (non variant) at position x-1?

### ISSUE THREAD

**Issue by ac2278** [vgteam/vg#3275]
I wanted to get a better sense of what variant calling looks like when using vg and ran through a small example. 

I constructed a graph using `vg construct -r example.fa -v example.vcf.gz -m 32 > example.vg`, 
stored the graph in the xg/gcsa index pair using `vg index -x example.xg -g example.gcsa -k 16 example.vg`, 
simulated 1 read (150 bp long) from the graph using `vg sim -n 1 -l 150 -x example.xg > example.sim.txt`, 
mapped the read against the graph to get a GAM using `vg map -T example.sim.txt -x example.xg -g example.gcsa > aln.gam`, 
computed the read support from the gam using `vg pack -x example.xg -g aln.gam -Q 5 -o aln.pack`, 
then generated a VCF from the support (calling every snarl using the same coordinates and including reference calls) using `vg call example.xg -k aln.pack -a > snarl_genotypes.vcf`.

These are the first 17 variants in `example.vcf.gz` (the VCF file used to construct the graph).
![toyset](https://user-images.githubusercontent.com/6481584/114591102-61f0ab80-9c3e-11eb-9314-4704a07a6363.png)
 
These are the first 17 variants in `snarl_genotypes.vcf` (output). 
![toyset_after](https://user-images.githubusercontent.com/6481584/114590961-38378480-9c3e-11eb-885c-aaec660b9592.png)

My question: Why are variants recoded in this way, i.e., the variant at position x now includes information about the site (non variant) at position x-1?

**Comment by glennhickey** [comment]
It looks like a bug in the `-a` option.  I'll take a look at fixing it, thanks.  In the meantime, you can correct it with `bcftools norm`

**Comment by ac2278** [comment]
Thanks, @glennhickey. I forgot to ask in my original post: Could you explain what the entries in the ID column represent?

**Comment by glennhickey** [comment]
The ID is the pair of nodes that define the "bubble" in the graph that corresponds to the site of variation.  For example in [this graph](https://raw.githubusercontent.com/vgteam/vg/master/doc/figures/smallgraph.png) the id `20030_30034` would correspond to the bubble with the snp and snp+insertion alleles.

**Comment by ac2278** [comment]
Ah, I see. Thanks, @glennhickey.

There's something I don't quite understand. In this example, I constructed a graph using 1 linear reference genome and a multi-sample VCF file. When I align reads and call variants, vg uses the reference genome's coordinate system. What happens when I align reads to and call variants from a graph that's constructed using a multiple-sequence alignment from Progressive Cactus? What coordinate system is used then?

**Comment by glennhickey** [comment]
It'll pick the alphabetically lowest path name that spans the site.  You can also use `-p` to force it to choose certain paths.

**Comment by ac2278** [comment]
Sorry, @glennhickey, I'm not following. Is there an illustration or example you could share? 

If I construct a graph using an MSA of reference genome A and reference genome B, align reads, then call variants, the coordinate system in the VCF file (i.e. how the physical position of variants are defined) will be based on some combination of reference A and B's coordinate system? When you say "You can also use -p to force it to choose certain paths.", are you saying that I could choose to use either A or B's coordinate system entirely?
