### ISSUE TITLE
construct

### ISSUE THREAD

**Issue by hongyu-zhang588** [vgteam/vg#3280]
vg: src/constructor.cpp:679: vg::ConstructedChunk vg::Constructor::construct_chunk(std::__cxx11::string, std::__cxx11::string, std::vector<vcflib::Variant>, size_t) const: Assertion `last_edit_end != -1' failed.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_7vXn8I/stacktrace.txt
Please include the stack trace file in your bug report!

**Comment by adamnovak** [comment]
Hello @hongyu-zhang588! Thanks for reporting this crash.

Unfortunately, without the input data to reproduce this bug, I don't think we can really fix it. If you can provide your input files and command line vg invocation, we can try and fix whatever is going wrong.
