### ISSUE TITLE
question about SV genotyping (1/2) in vcf

### ISSUE THREAD

**Issue by cistarsa** [vgteam/vg#3281]
hello again,

Should I assume the 1/2 genotypes at SV's (from vg call) refer to alternate paths (snarls) within the SV? 

thank you!

**Comment by ekg** [comment]
These would be over two alleles that aren't the specified reference path in
the VCF.

**Comment by cistarsa** [comment]
excellent, thank you. and just to clarify would novel alleles in the reads also be genotyped as alternates in this way?

**Comment by glennhickey** [comment]
`vg call` only genotypes variants in the graph. For small variants, you can first "agument" them in from the reads:  
https://github.com/vgteam/vg/wiki/Whole-genome-calling-and-genotyping
https://github.com/vgteam/vg#augmentation
https://github.com/vgteam/vg#variant-calling 
I'm not sure how well `vg augment` will work for SVs, though.

**Comment by cistarsa** [comment]
yes, thank you- super helpful. 

I've pulled SNP(V)s and am focusing on SV's now. Trying to appropriately get allele frequencies to compare (prob just gonna pool all alt alleles together...)

**fin**
