### ISSUE TITLE
Warning [vg call]: Unable, due to bug or corrupt graph, to search for any traversals through snarl

### ISSUE THREAD

**Issue by cademirch** [vgteam/vg#3286]
**1. What were you trying to do?**
Call variants from GAM using vg call. Followed [wiki instructions](https://github.com/vgteam/vg/wiki/Whole-genome-calling-and-genotyping). 

**2. What did you want to happen?**
Produce VCF without warnings?

**3. What actually happened?**
VCF produced, but many warnings: `Warning [vg call]: Unable, due to bug or corrupt graph, to search for any traversals through snarl {"directed_acyclic_net_graph": true, "end": {"node_id": "16149035"}, "start": {"node_id": "7677192"}, "start_end_reachable": true, "type": 1}`

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
No stacktrace.
```

**5. What data and command can the vg dev team use to make the problem happen?**
Can make data available. 

**6. What does running `vg version` say?**

```
vg version v1.31.0 "Caffaraccia"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by ubuntu@ip-172-31-30-191
```
Got many (gigabytes worth) of these snarl traversal warnings when calling variants.  Appreciate any thoughts/advice.

**Comment by adamnovak** [comment]
@glennhickey Is that part of the calling documentation still accurate?

@cademirch, what data inputs are you using to get this to happen? We're working on turning all of our wiki examples into tests, so we can't break them, but I'm not sure we actually have a particular set of files to use to run through the procedure on that page, so I suppose you have supplied your own data?

**Comment by cademirch** [comment]
@adamnovak Yup using my own data. Aligned whole genome D. melanogaster reads to my graph using `vg map`and used the resulting GAM in the calling process. I can make the data available if need be.

**Comment by adamnovak** [comment]
Could you share it? Then we might be able to reproduce the issue.

**Comment by cademirch** [comment]
@adamnovak I've put it all [here](https://storage.googleapis.com/vg_data/for_anovak.tar.gz). There are some snakefiles that I've also included that show how I generated the alignments as well as the various intermediates. Let me know if anything is unclear. Thank you for your help.

**Comment by glennhickey** [comment]
I've seen this before one time and couldn't figure it out.  If I remember, it was in a huge snarl that the traversal finder simply couldn't get through.  Even vg's implementation of Dijkstra (on which the traversal finder is based) wasn't able to.  But just scanning the reference path could get across. 

Using `-n` might fix this.  Even without, it will recurse on child snarls and give you variants nested within the site.

**Comment by cademirch** [comment]
Using `-n` resulted in a crash, unfortunately: 
```vg_1.31: src/graph_caller.cpp:1722: bool vg::NestedFlowCaller::call_snarl_recursive(const vg::Snarl&, int, const string&, std::pair<long unsigned int, long unsigned int>, vg::NestedFlowCaller::CallTable&): Assertion `false' failed.```

The stack trace:
```
Crash report for vg v1.31.0 "Caffaraccia"
Stack trace (most recent call last) in thread 48740:
#11   Object "", at 0xffffffffffffffff, in 
#10   Object "/scratch/cade/vg/bin/vg_1.31", at 0x1be58ce, in __clone
#9    Object "/scratch/cade/vg/bin/vg_1.31", at 0xc277f6, in vg::SnarlManager::for_each_top_level_snarl_parallel(std::function<void (vg::Snarl const*)> const&) const
#8    Object "/scratch/cade/vg/bin/vg_1.31", at 0x1b377fe, in GOMP_parallel
#7    Object "/scratch/cade/vg/bin/vg_1.31", at 0xc261a4, in vg::SnarlManager::for_each_top_level_snarl_parallel(std::function<void (vg::Snarl const*)> const&) const [clone ._omp_fn.0]
#6    Object "/scratch/cade/vg/bin/vg_1.31", at 0xc5331b, in std::_Function_handler<void (vg::Snarl const*), vg::GraphCaller::call_top_level_snarls(handlegraph::HandleGraph const&, bool)::{lambda(vg::Snarl const*)#1}>::_M_invoke(std::_Any_data const&, vg::Snarl const*&&)
#5    Object "/scratch/cade/vg/bin/vg_1.31", at 0xc6399f, in vg::NestedFlowCaller::call_snarl(vg::Snarl const&)
#4    Object "/scratch/cade/vg/bin/vg_1.31", at 0xc63784, in vg::NestedFlowCaller::call_snarl_recursive(vg::Snarl const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::pair<unsigned long, unsigned long>, std::map<vg::Snarl, vg::NestedFlowCaller::CallRecord, vg::NestedCachedPackedTraversalSupportFinder::snarl_less, std::allocator<std::pair<vg::Snarl const, vg::NestedFlowCaller::CallRecord> > >&)
#3    Object "/scratch/cade/vg/bin/vg_1.31", at 0x1b55821, in __assert_fail
#2    Object "/scratch/cade/vg/bin/vg_1.31", at 0x1b557ab, in __assert_fail_base
#1    Object "/scratch/cade/vg/bin/vg_1.31", at 0x1b621b0, in abort
#0    Object "/scratch/cade/vg/bin/vg_1.31", at 0x10d7867, in raise
```
