### ISSUE TITLE
Reproducible example of variant calling?

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#329]
Could I get a walkthrough for aligning reads to a graph and calling variants? I've tried with the `tiny` example:

```
vg construct -r tiny/tiny.fa -v tiny/tiny.vcf.gz > tiny.vg
vg index -x tiny.xg -g tiny.gcsa -k 11 tiny.vg
```

For an easy visual example, I'd like to simulate reads with a C -> A variant at position 22, so I saved the following as `tiny-var.reads` (where the variant is homozygous in the reads):
```
GCTTGGAAATTTTATGGAGT
AAGGCTTGGAAATTTTATGG
TGGAAATTTTATGGAGTTCT
ATTTTATGGAGTTCTATTAT
GGAGTTCTATTATATTCCAA
CTATTATATTCCAACTCTCT
TTTTATGGAGTTCTATTATA
GTTCTATTATATTCCAACTC
TTCTATTATATTCCAACTCT
GAAATTTTATGGAGTTCTAT
TGGAAATTTTATGGAGTTCT
TTTATGGAGTTCTATTATAT
AAGGCTTGGAAATTTTATGG
AAATAAGGCTTGGAAATTTT
AAATTTTATGGAGTTCTATT
AAATTTTATGGAGTTCTATT
AATTTTATGGAGTTCTATTA
CTTGGAAATTTTATGGAGTT
GGAGTTCTATTATATTCCAA
GAGTTCTATTATATTCCAAC
TGGAAATTTTATGGAGTTCT
AATTTTATGGAGTTCTATTA
AGGCTTGGAAATTTTATGGA
TGGAGTTCTATTATATTCCA
GAGTTCTATTATATTCCAAC
```

Then mapped those reads to the graph:
```
vg map -r tiny-var.reads -x tiny.xg -g tiny.gcsa -k 22 > tiny-var.gam
vg pileup tiny.vg tiny-var.gam > tiny-var.pileup
vg call -l -c tiny-var.tsv tiny.vg tiny-var.pileup > tiny-aug-var.vg
```

But this doesn't add three nodes and four edges to the graph like I'd expect with the addition of a SNP mid-node:
```
vg stats -lz tiny.vg

nodes   15
edges   20
length  55

vg stats -lz tiny-aug-var.vg

nodes   15
edges   20
length  55
```

Exporting a vcf doesn't produce anything expect headers, which seems odd--shouldn't the original variants be there?:
```
glenn2vcf tiny-aug-var.vg tiny-var.tsv

Graph has 1 paths to choose from.
Guessed reference path name of x
Traced 50 bp reference path x.
Reference sequence: CAAATAAGGCTTGGAAATTTTCTGGAGTTCTATTATATTCCAACTCTCTG
Loaded 35 lines from tiny-var.tsv
##fileformat=VCFv4.2
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele at this location">
##INFO=<ID=XREF,Number=0,Type=Flag,Description="Present in original graph">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
Had to drop 0 bp of unrepresentable variation.
```

Another attempt, with vg simulated reads:
```
vg sim -s 123 -l 20 -n 50 -e 0.07 tiny.vg > tiny-sim.reads
vg map -r tiny-sim.reads -x tiny.xg -g tiny.gcsa -k 22 > tiny-sim.gam
vg pileup tiny.vg tiny-sim.gam > tiny-sim.pileup
vg call -l -c tiny-sim.tsv tiny.vg tiny-sim.pileup > tiny-aug-sim.vg
glenn2vcf tiny-aug-sim.vg tiny-sim.tsv

Graph has 1 paths to choose from.
Guessed reference path name of x
Traced 50 bp reference path x.
Reference sequence: CAAATAAGGCTTGGAAATTTTCTGGAGTTCTATTATATTCCAACTCTCTG
Loaded 35 lines from tiny-sim.tsv
##fileformat=VCFv4.2
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele at this location">
##INFO=<ID=XREF,Number=0,Type=Flag,Description="Present in original graph">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
Warning: copy numbers don't add up consistently for 23; assuming het
.       14      23      G       A       0       .       XREF    GT      1/0
Had to drop 0 bp of unrepresentable variation.
```

This time I get the SNP at position 14, but not the others. I realize in this case there might not be enough reads for a given variant in the simulated reads to be called with the default parameters. I've tried with a bunch of different parameters, but I'm not sure if it's a matter of finding the right combination of parameters, or if the [process has changed](https://github.com/vgteam/vg/issues/305). A reproducible example would be helpful in figuring out how to call variants. Thanks!

**Comment by glennhickey** [comment]
Hi Heather,

Thanks for trying this out.

Your SNP isn't getting called because by default, there is a small strand
bias filter.  Since your reads all map on the forward strand, nothing gets
called.  You can get around this by adding -b 1 to vg call to disable to
filter completely.

The final VCF will only contain SNPs supported by your reads, of which
there is only one.  Since the other SNPs in tiny.vg have no read support,
your won't see them.

vg call -l -c tiny-var.tsv tiny.vg tiny-var.pileup -b 1 > tiny-aug-var.vg
glenn2vcf tiny-aug-var.vg tiny-var.tsv gives

#CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO    FORMAT
SAMPLE
.    22    23    C    A    0    .    XREF    GT    1/0

The genotype's wrong here because, as I've just noticed, the pr #322 that
fixes this never got merged.  Will look into now. .

-Glenn

**Comment by hgibling** [comment]
Thanks for the clarification, Glenn!

**Comment by glennhickey** [comment]
#322 is merged in now.  I disabled the strand bias filter by default while I was at it.  So your original commands should give the correct output now, provided you have the latest vg / glenn2vcf.
