### ISSUE TITLE
Autoindex fails to properly autogenerate the .fai of a .fa file.

### ISSUE THREAD

**Issue by Robin-Rounthwaite** [vgteam/vg#3291]
**1. What were you trying to do?**
Run autoindex on NYGC data, using a .fa for the reference. I hadn't included the .fai, so autoindex tried to autogenerate that for me. But it turned out to be malformed.

**2. What did you want to happen?**
I wanted to use the autogenerated .fa.fai file to autoindex my NYGC chr21 subgraph.

**3. What actually happened?**
It printed the following error:

```
rrounthw@courtyard:/public/groups/vg/rrounthw/nygc_normalize$ vg autoindex --provide VG:nygc_snp1kg_grch38.chr21.vg -p nygc_snp1kg_grch38.chr21 -w giraffe -r indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa -v CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz
[vg autoindex] Excecuting command: vg autoindex --provide VG:nygc_snp1kg_grch38.chr21.vg -p nygc_snp1kg_grch38.chr21 -w giraffe -r indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa -v CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz
[IndexRegistry]: Checking for phasing in VCF(s).
[IndexRegistry]: Chunking inputs for parallelism.
index file indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa.fai not found, generating...
[IndexRegistry]: Chunking FASTA(s).
Warning: malformed fasta index file indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa.faidoes not have enough fields @ line 2842
HLA-A*01:01:01:01	HLA00001	3503	3261539889	72	73
Warning: malformed fasta index file indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa.faidoes not have enough fields @ line 2842
HLA-A*01:01:01:01	HLA00001	3503	3261539889	72	73
Warning: malformed fasta index file indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa.faidoes not have enough fields @ line 2842
HLA-A*01:01:01:01	HLA00001	3503	3261539889	72	73
Warning: malformed fasta index file indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa.faidoes not have enough fields @ line 2842
HLA-A*01:01:01:01	HLA00001	3503	3261539889	72	73
Warning: malformed fasta index file indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa.faidoes not have enough fields @ line 2842
HLA-A*01:01:01:01	HLA00001	3503	3261539889	72	73
```

**5. What data and command can the vg dev team use to make the problem happen?**
I ran it on Courtyard.
Reference file:
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
Reference index (which I didn't use until I realized the autogenerated .fai was malformed):
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa.fai

VCF:
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/work[…]_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/work[…]0-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz.tbi

To make the chr21 graph I was using:
Get the full xg from:
https://storage.googleapis.com/cmarkell-vg-wdl-dev/nygc_snp1kg_grch38_ref/nygc_snp1kg_grch38.xg
Then make the subgraph with:
```
vg find -x nygc_snp1kg_grch38.xg -p chr21 >nygc_snp1kg_grch38.chr21.vg
```
Finally, here is the command I ran:
```
vg autoindex --provide VG:nygc_snp1kg_grch38.chr21.vg -p nygc_snp1kg_grch38.chr21 -w giraffe -r indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa -v CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz
```

I'm also dealing with a second bug when using the command with the proper .fai. I mentioned this to Jordan via Slack, and he showed me a workaround. Here is an  alternative command with the workaround, which I would expect to still create a problematic .fai:
```
vg autoindex --provide VG:nygc_snp1kg_grch38.chr21.vg -p nygc_snp1kg_grch38.chr21 -w giraffe -r indexing/GRCh38_full_analysis_set_plus_decoy_hla.fa -provide "Chunked VCF w/ Phasing":CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz
```

**6. What does running `vg version` say?**

```
vg version v1.13.0-5166-g8beeddbdd "Moschiano"
Compiled with g++ (GCC) 8.1.0 on Linux
Linked against libstd++ 20180502
Built by rrounthw@courtyard
```

**Comment by glennhickey** [comment]
You might want to try subsetting your vcf and fasta to chr21.
