### ISSUE TITLE
vg index error

### ISSUE THREAD

**Issue by Chipcui** [vgteam/vg#3313]
Hi,
When I use vg to index my vg file `vg index pangenome.v4.vg -x pangenome.v4.xg`, it occurs the following error:
```
sparsehash FATAL ERROR: failed to allocate 8 groups

```
And how to handle this error?

**Comment by jeizenga** [comment]
Could you add the commands you used to create `pangenome.v4.vg`?

**Comment by Chipcui** [comment]
@jeizenga 
I used the `vg construct -r pangenome.v4.fa -v filter_sort_SV.vcf.gz > pangenome.v4.vg` to create it.

**Comment by Chipcui** [comment]
And the files used to create the vg graph are here:
[pangenome.v4.fa.gz](https://1drv.ms/u/s!AuNwPjZED6DAi7dxv58TX5MtVBxxrA?e=XTRHCR) 
[filter_sort_SV.vcf.gz](https://1drv.ms/u/s!AuNwPjZED6DAi7du2cTK8ODjFanqqQ?e=VurjNw)
[filter_sort_SV.vcf.gz.tbi](https://1drv.ms/u/s!AuNwPjZED6DAi7dtvXPqp-NJUNQnMQ?e=OdT5T3)
[pangenome.v4.vg.gz](https://1drv.ms/u/s!AuNwPjZED6DAi7dvBCJ5aHlJPc3gyw?e=WA8ZAe)

**Comment by Chipcui** [comment]
I think the error maybe related to my server's system (CentOS 7), which is not the Ubuntu. After I moved to my computer (windows subsystem linux Ubuntu), the xg index file constructed successfully without any error. 
I think the vg tools need to rebuild from source code in my server.

**Comment by jeizenga** [comment]
That's interesting. The static binaries we distribute as releases are compiled on an Ubuntu machine, so there may be some system dependency in there somehow, although it's not obvious to me how that would happen. Internally, the VG team does a lot of its development on a CentOS 7 server, so VG is definitely compatible with that environment. However, we would typically be building from source code on that server. It sounds like that's your plan now, but let us know if you continue to see problems.
