### ISSUE TITLE
Port Install on Mac OSX

### ISSUE THREAD

**Issue by jjfarrell** [vgteam/vg#332]
I am trying to install vg on a Mac with  El Capitan OS X.

The first issue is the port install of the redland-utils which the README indicates should be:
`sudo port install  redland-utils`
but this generates:
Error: Port redland-utils not found

However, 
`sudo port install redland `
does install. So it looks like the vg README needs to be updated.

The other issue is related to bison. The port install places the most up to date version of bison in /opt/local/bin. This directory is ahead of /usr/bin in the PATH where the old 2.3 bison is installed. However, this error is generated when compiling.  To get around this, I could update or replace the old bison in /usr/bin but was wondering if there was a cleaner way to achieve this in the source_me.sh  or make scripts.

`. ./source_me.sh && make`
cd deps/raptor/build && cmake .. && /Applications/Xcode.app/Contents/Developer/usr/bin/make && cp src/libraptor2.a /Users/farrell/github/vg/lib && mkdir -p /Users/farrell/github/vg/include/raptor2 && cp src/*.h /Users/farrell/github/vg/include/raptor2
CMake Error at /opt/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find BISON: Found unsuitable version "2.3", but required is at
  least "3" (found /usr/bin/bison)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.5/Modules/FindBISON.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:33 (FIND_PACKAGE)

**Comment by adamnovak** [comment]
For the bison thing, have you tried clearing out the cmake cache and/or deleting the `deps/raptor` submodule and restoring it with `git submodule update --init --recursive`? I also had this problem with Bison, and I also have an old `/usr/bin/bison` and a new `/opt/local/bin/bison`, and from a clean checkout of the submodule, cmake is finding the right one.

**Comment by jjfarrell** [comment]
Thanks!  The restore of deps/raptor submodule worked.

John

On Wed, May 11, 2016 at 4:03 PM, adamnovak <notifications@github.com> wrote:

> For the bison thing, have you tried clearing out the cmake cache and/or
> deleting the deps/raptor submodule and restoring it with git submodule
> update --init --recursive? I also had this problem with Bison, and I also
> have an old /usr/bin/bison and a new /opt/local/bin/bison, and from a
> clean checkout of the submodule, cmake is finding the right one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vgteam/vg/issues/332#issuecomment-218573224>
>



-- 
John Farrell, Ph.D.
IT Manager
Biomedical Genetics-Evans 218
Boston University Medical School
72 East Concord Street
Boston, MA

ph: 617-638-5491
