### ISSUE TITLE
extracting a region from graph for all genomes

### ISSUE THREAD

**Issue by userzxyz** [vgteam/vg#3331]
Hello,

I have made a chromosome wise graph genome for 10 genomes using pggb. For chromosome 1, there is an insertion for one of the genomes (`Line4`) used to make graph genome. To validate this insertion in the graph genome, I used:
```
vg view -F -v seqwish.gfa > seqwish.vg
vg index -x seqwish.xg seqwish.vg
vg find -x seqwish.xg -p Line4ch01:50553-78776 -c 2 > out.vg
```

I was looking to extract this region for all the genomes not only just Line4. So that I can compare if the insertion is present in this sample or not. Is there a way to extract this region for all the genomes used? Thank you!

**Comment by jeizenga** [comment]
You might be able to get what you want using `-c` or `-c`+`-L` in the `vg find` call. It can be a bit fiddly to figure out how much extra context you need to extract to get the whole region of the graph you want, but it can be done.

**Comment by userzxyz** [comment]
Thank you @jeizenga! I tried it with `-c` and got the output. I tried to open the `out.vg` file using 
`vg view out.vg`. I am trying to understand this output. I pasted a few random lines from the output to give an idea how it looks. There is one line that starts with` H`, followed by lines starting with `S`. Then there are lines starting with `P` for each of the input samples used (shown for `Line1` here) followed by lines starting with `L`:
```
H	VN:Z:1.0
S	275893	ACTCAAGCTTTGT
S	220	AATTGTACCTTTAAGT
S	308	TGCTTTTAATATCTT
S	334881	ATCAGTTCATGAGCA
S	319134	TTAACTAAATATATAGT
S	215	GGAATGGTAAGG
S	400136	CTTTCAAAATGGGTCGGA
S	319	TTTTACTTTCTTGTTTCTC
S	365562	TTTTGTTAGGAAATTTCAAAACGAT
P	Line01ch01 198+,202+,203+,204+,205+,206+,207+,208+,209+,210+,211+,212+,213+,214+,215+,216+,217+,218+,219+,220+,221+,222+,223+,224+,225+,226+,227+,228+,229+,230+,231+,232+,233+,234+,235+,236+,237+,238+,239+,240+,241+,242+,243+,244+,245+,246+,247+,248+,249+,250+,251+,252+,253+,254+,255+,256+,257+,258+,259+,260+,261+,262+,263+,264+,265+,266+,267+,268+,269+,270+,271+,272+,273+,274+,275+,276+,277+,278+,279+,280+,282+,284+,285+,286+,287+,288+,289+,290+,291+,292+,293+,294+,295+,296+,297+,298+,299+,300+,301+,302+,303+,304+,305+,306+,307+,308+,309+,310+,311+,312+,313+,314+,315+,316+,317+,318+,319+,320+,321+,322+,323+,324+,325+,326+,327+,328+,329+,330+,331+,332+,333+,334+,335+,336+,337+,338+,339+,340+,341+,342+,343+,344+,345+,346+,348+,349+,350+,351+,352+,353+,354+,355+,356+,357+,358+,359+,360+,361+,362+,363+,364+,365+,366+,367+,368+,369+,370+,379+,380+,381+,382+,383+,384+,385+,386+,387+,388+,389+,390+,391+,392+,393+	*
L	275893	+	365544	+	*
L	275893	+	275894	+	*
L	365543	+	275893	+	*
L	378098	+	378099	+	*
L	378098	+	400122	+	*
L	220	+	221	+	*
L	365539	+	220	+	*
L	308	+	309	+	*
```
I could not find any documentation to understand this format. Ideally, I would like to see an insertion in the sample at the location and no insertion for other samples. Can you please share any suggestions to achieve it? Thank you!

**Comment by glennhickey** [comment]
That's [gfa](http://gfa-spec.github.io/GFA-spec/GFA1.html) which you can visualize with bandage or odgi.  There's also [graphviz](https://github.com/vgteam/vg#viewing-conversion).

**Comment by userzxyz** [comment]
Is it possible to use` vg` find with a `vcf `file as input?

**Comment by ekg** [comment]
You'll need to use vg construct to build a graph from the VCF and FASTA.
Then you can extract the desired region. Alternatively, you can give a
reference range to vg construct.

**Comment by userzxyz** [comment]
Thanks @ekg! I have made a vcf file from graph genome. How can I extract the region from this vcf file?

**Comment by ekg** [comment]
When you do VG construct you specify -R (I think) and give a samtools style
region string like chr8:3920-4959

**Comment by userzxyz** [comment]
Thanks ! I used bcftools and it seems to work. I got a vcf and first few lines look like:


```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Line1ch01	Line2ch01	Line3ch01	Line4ch01	Line5ch01	Line6ch01	Line7ch01	Line8ch01	Line9ch01	Line10ch01			
Line1ch01	914	>155>157	ATCATCACAATCATTAGAGTTTTCATCATCACTATCATTAGTAGTCTCATTCTCTTCAATTAGAAAAAGAAGTTGGCATTCA	ATCATCACTATCATTAGAGTTTTCATCATCACTATCATTAGTAGTCTCATTCTCTTCAATTAGAAAAAGAAGTTGGCATTCT,ATCATCACTATCATTAGAGTTTTCATCATCACTATCATTAGTAGTCTCATTCTCTTCAATTAGAAAAAGAAGTTGGCATTCA	60	.	AC=1,12;AF=0.0714286,0.857143;AN=14;NS=14	GT	0	1	2	2	2	2	2	2	2	2			
```

In a multisample vcf, sample columns usually have calls like `0/0`, `0/1`, `1/1`. Can you help me understand what does `0`, `1`, `2` mean in this file for the sample? Thank  you!
