### ISSUE TITLE
Impact of K-mer size during pruning

### ISSUE THREAD

**Issue by RenzoTale88** [vgteam/vg#3343]
Hi,
I got a question concerning the pruning stage. As outline in a previous issue (#2612) I've generate a graph genome using a insect assemblies of small size (250Mb). I've used the cactus pangenome workflow to generate a whole-genome vg graph, that I then indexed using VG 1.33.0.
I encountered issues during the generation of the GCSA2 index, since even with a genome this small the indexing stage would generate over 8Tb of temporary files. To overcome the issue, I've increased the K-mer size to 28 and 32, and seen that the storage burden massively reduced (~600Gb for -k 28).
My question is: is it possible to estimate the impact that the increase in K-mer size will have on the alignment/calling step? Will it negatively impact the result? If so, is there a limit of K-mer threshold it is recommended to not go over?
Thank you in advance,
Andrea

**Comment by RenzoTale88** [comment]
@ekg thanks, yes sorry I explained myself poorly. I tried to prune the graph using the default k-mer size, but that would lead to huge temporary files, making it impossible to generate the index due to lack of space (>8Tb for a 250Mb genome).
Then I've tried to increase the K-mer size during the pruning stage (K-28, K=32, K=48). This made the generation of the index feasible. However, I'm unsure how it would impact the downstream analyses. So I was wondering if there is a limit that you would discourage to use when pruning?

**Comment by jltsiren** [comment]
I don't think anyone knows how kmer length in pruning affects downstream accuracy. My best guess is that if you use option `-u` and have the original sequences as paths in the graph or the GBWT index, kmer length will only affect the resource requirements of pruning and index construction. With longer kmers, you prune unobserved recombinations from complex regions more aggressively, but option `-u` ensures that the index will contain the observed haplotypes.

**Comment by RenzoTale88** [comment]
@jltsiren thank you for the explanation. Indeed, I prune using the `-u` flag since I'm using a cactus-derived graph. 
I'll try to use the minimum K-value for the pruning stage just in case (I've managed to go down to k=26) and hope for the best!
Thank you very much again for the help!

Andrea
