### ISSUE TITLE
vg rna error

### ISSUE THREAD

**Issue by userzxyz** [vgteam/vg#3351]
Hello,

I made chromosome wise graph genomes. I then combined seqwish graph files to make a combined graph genome using `vg combine`. 

```
vg mod -X 1000 combined.gfa > combined_fixed.gfa
vg gbwt -G combined_fixed.gfa -p -o combined.gbwt
vg convert -x -g combined_fixed.gfa > combined.xg
vg convert -x combined.xg -p > combined.pg

```
Then I combined the gff files for all the input samples used for graph genome. Now I am trying to make a spliced graph genome using `vg rna`.
vg rna -p -t -16 -n merged.gff -l combined.pg combined_fixed.gfa > combined.pg

```
But it is giving error:
[vg rna] Parsing graph file ...
[vg rna] Parsing haplotype GBWT index file ...
GBWT::load(): Invalid header: GBWT v268435456: 3259984688 sequences of total length 6658561, alphabet size 182 with offset 8526021
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_63zOD5/stacktrace.txt
Please include the stack trace file in your bug report!
```

Thank you!

**Comment by jltsiren** [comment]
Your `vg rna` command should use option `-l combined.gbwt`. At the moment you are trying to load the GBWT from the empty output file `combined.pg`.

**Comment by userzxyz** [comment]
Thank you @jltsiren!  I could not find another way to produce combined.pg from the files that I have. Could you please help me if you are aware of a command for it?
