### ISSUE TITLE
IntegratedSnarlFinder's traverse_decomposition crashes

### ISSUE THREAD

**Issue by xchang1** [vgteam/vg#3355]
I was trying to use `IntegratedSnarlFinder::traverse_decomposition` on the hgsvc graph (s3://vg-k8s/profiling/graphs/v2/for-NA19240/hgsvc/hs38d1/HGSVC_hs38d1.xg) for distance index construction but it failed with the error
```
src/integrated_snarl_finder.cpp:1507: void vg::IntegratedSnarlFinder::traverse_computed_decomposition(vg::IntegratedSnarlFinder::MergedAdjacencyGraph&, const vg::IntegratedSnarlFinder::MergedAdjacencyGraph&, std::vector<std::pair<long unsigned int, std::vector<handlegraph::handle_t> > >&, std::unordered_map<handlegraph::handle_t, handlegraph::handle_t>&, std::vector<std::pair<long unsigned int, handlegraph::handle_t> >&, std::unordered_map<handlegraph::handle_t, handlegraph::handle_t>&, const std::function<void(handlegraph::handle_t)>&, const std::function<void(handlegraph::handle_t)>&, const std::function<void(handlegraph::handle_t)>&, const std::function<void(handlegraph::handle_t)>&) const: Assertion `!seen.count(here)' failed.
```
When I was making the distance index, it was trying to make a chain starting at node 19542917 rev twice. 

I made a branch (https://github.com/xchang1/vg/tree/snarl-traversal-bug) that will call `traverse_decomposition` in `vg stats` and it fails with the same error, although this time it fails trying to visit a chain starting at 79661163 fd twice. I ran my modified vg stats:
```
vg stats -R HGSVC_hs38d1.xg 2> snarls
```
It prints out the start and end nodes of each snarl/chain as it sees them, and writes it to stderr.  When I `grep`-ed the node that was causing problems, this was the result
```
end snarl 79658794 0->79661163 0
start snarl 79661163 0
end snarl 79661163 0->79661164 0
start chain 79661163 0
start snarl 79661163 0
end snarl 79661163 0->79661164 0
end chain 79661163 0->81087388 0
start chain 79661163 0
```
So it looks to me like the node 63 is the boundary node of two consecutive snarls (94-63 and 63-64) in a chain, which are found properly. But then it's starting a chain at 63, then finds snarl 63-64 a second time, ends the chain at node 88, then tries to start the same chain again.
I also `grep`-ed for node 88 and there are multiple chains ending at that node
```
end snarl 81087387 0->81087388 0
end chain 78452241 0->81087388 0
end snarl 81087387 0->81087388 0
end chain 79661163 0->81087388 0
```
@adamnovak can you help me out with this one please? I'm stuck

**Comment by xchang1** [comment]
I also ran `vg snarls -T HGSVC_hs38d1.xg -t 12 > /dev/null` on the same graph and it finished without crashing

**Comment by adamnovak** [comment]
How long is vg stats supposed to take here?

**Comment by xchang1** [comment]
If you're printing out the snarls it takes about an hour and a half. If you send cerr to /dev/null it takes half an hour

**Comment by adamnovak** [comment]
OK, I have something that should fix this here: https://github.com/adamnovak/vg/commits/f09523415

It looks like I wasn't properly ignoring orientation when checking if a node had been visited, and this graph has a particularly long child chain that gets visited the first time in reverse. At some point that chain becomes the longest cycle left in the graph, and we were forgetting we had visited it and trying to use it to root a new decomposition.

I think that combined with some of the cycle surgery we do was hitting the `seen` assert?

I'm still testing this; hopefully it works all the way through.
