### ISSUE TITLE
alignment of reads by giraffe that match multiple positions equivalently

### ISSUE THREAD

**Issue by jnvaughn** [vgteam/vg#3363]
In contrast with most single-reference short-read aligners, Giraffe does not appear to randomly chose an alignment position for reads that align equivalently at multiple positions.  Instead, one of the many repetitive sites absorbs all reads and leaves the remaining sites uncovered.  I am basing this observation on surjection of simulated reads to their source genome in the graph, so I can directly compare source origin with aligned locus.  

Giraffe does give such reads a poor MQ score (0) as expected, so they can be filtered, but, for biological interpretation, random placement would be preferred (assuming MQ is still called 0).  One solution is to use -M flag with large INT and randomly sample reads in resultant GAF with multiple entries.  Is there a better way to get random placement of equivalent alignments directly from giraffe?

Thanks very much.

**Comment by briannadon** [comment]
I can add some information here with a handy example. I've run an alignment of simulated reads from a bacterial genome against a graph containing that genome as a path, then surjected against that path to ensure we're properly reconstituting haplotypes.

You can see below in the surjected BAM output, there is a locus with clear 2x coverage of the rest of the genome on the left, followed by an identical (confirmed w alignment) region on the right with 0x coverage. What's happening is all reads that *should* align to either of the 2 loci are instead *always* aligning to the first, despite the two being 100% identical in sequence.  Writing a custom post-script to randomly reassign these read helped slightly, at the cost of losing paired-read information. This is why it'd be better to have this handled during alignment, as other aligners do.
![image](https://user-images.githubusercontent.com/19713362/128380376-c996356d-dd87-4bd7-bb04-a80650892bf8.png)

**Comment by jnvaughn** [comment]
To further illustrate, I've written a simply redistribution script  and have shown results of simulated reads surjected back to source path: 
[redistribution.pdf](https://github.com/vgteam/vg/files/6946297/redistribution.pdf)

**Comment by jnvaughn** [comment]
Redistribution script:

**Comment by jltsiren** [comment]
I believe this was resolved in #3387.
