### ISSUE TITLE
vg crashes at SV genotyping step - Error [Packer]: unable to read pack file

### ISSUE THREAD

**Issue by rbr7** [vgteam/vg#3366]
**1. What were you trying to do?**

1. Take the output products from vg toolkit giraffe paper for HGSVC graph as here (http://cgl.gi.ucsc.edu/data/giraffe/calling/hgsvc/) and map reads to HGSVC graph using giraffe mapper, using  "vg giraffe"
2. Generated the .pack file for computing packed coverage from aligned reads, using "vg pack"
3. Call variants from the packed read coverage, using "vg call"
4. Genotype variants from the packed read coverage, using "vg call -v HGSVC.haps.vcf.gz"

**2. What did you want to happen?**
Step 4 to complete successfully and genotype variants. 

**3. What actually happened?**
Here is the list of commands i actually ran,

1)   vg giraffe -p -t 64 -m hg38-hgsvc.k29.w11.N32.min -d hg38-hgsvc.dist -g hg38-hgsvc.N32.gg --gbwt-name hg38-hgsvc.N32.gbwt -x hg38-hgsvc.xg -N sid17 -f 17_R1.fastq.gz -f 17_R2.fastq.gz > GRCh38-HGSVC-sid17_v14.gaffek29w11N32.gam

2)  vg pack -x hg38-hgsvc.xg -Q 5 -g GRCh38-HGSVC-sid17_v14.gaffek29w11N32.gam -t 24 -o GRCh38-HGSVC-sid17_v14.minq.pack

3)  vg call -k GRCh38-HGSVC-sid17_v14.minq.pack -s sid17 --snarls hg38-hgsvc.snarls hg38-hgsvc.xg -t 32 > GRCh38-HGSVC-sid17-minq_calltemp_raw_v14.vcf

4)  vg call -k GRCh38-HGSVC-sid17_v14.minq.pack -s sid17 --snarls hg38-hgsvc.snarls -v HGSVC.haps.vcf.gz -x hg38-hgsvc.xg -t 64 > GRCh38-HGSVC-sid17-minq_genotemp_raw_v14.vcf

Upon running the Step 4, the stderr showed :-

"stderr": "warning:[XG] Loading an out-of-date XG format. For better performance over repeated loads, consider recreating this XG index.\nterminate called after throwing an instance of 'std::runtime_error'\n  what():  Error [Packer]: unable to read pack file: \"GRCh38-HGSVC-sid17_v14.minq.pack\"\n\nERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.\nStack trace path: /tmp/vg_crash_alkpXD/stacktrace.txt\nPlease include the stack trace file in your bug report!\n",                             "exitCode": 134

NOTE : every time i take a new sample and map it via giraffe, then compute packed coverage and finally try to genotype variants, it crashes with the same error saying  " unable to read .pack file". I tried multiple times with >10 samples and multiple retries.

What concerns me is that -> If the "vg call" can read the pack file when doing the variant calling step, then why not read the .pack file at variant genotyping step with "vg call -v HGSVC.haps.vcf.gz" file ?

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

Here it is,

```
cat /tmp/vg_crash_0zxxoR/stacktrace.txt
 
Crash report for vg not-from-git
Stack trace (most recent call last):
#11   Object "/vg/bin/vg", at 0x5a7a2d, in _start
#10   Object "/vg/bin/vg", at 0x1b9a1af, in __libc_start_main
#9    Object "/vg/bin/vg", at 0x57d364, in main
#8    Object "/vg/bin/vg", at 0xbb85cb, in vg::subcommand::Subcommand::operator()(int, char**) const
#7    Object "/vg/bin/vg", at 0xb82047, in main_call(int, char**)
#6    Object "/vg/bin/vg", at 0x50375f, in vg::Packer::load_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold]
#5    Object "/vg/bin/vg", at 0x1ad5f78, in __cxa_throw
#4    Object "/vg/bin/vg", at 0x1ad5e16, in std::terminate()
#3    Object "/vg/bin/vg", at 0x1ad5dab, in __cxxabiv1::__terminate(void (*)())
#2    Object "/vg/bin/vg", at 0x579e02, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#1    Object "/vg/bin/vg", at 0x57c893, in abort
#0    Object "/vg/bin/vg", at 0x12a4eab, in raise
```

**5. What data and command can the vg dev team use to make the problem happen?**

Commands are submitted as above. Restrictions to share proprietary data.

**6. What does running `vg version` say?**

Latest docker image for vg
```
vg version v1.33.0 "Moscona"
```

**Comment by rbr7** [comment]
I agree that vg call has no -x flag and that previous line for variant genotyping i copied from some mistaken file, but here are the actual screenshots of what I ran with the stacktrace being displayed as well. The .pack file is there on disk as well. attached are images where the commands were run on AWS and the same on local machine.

![Screenshot (229)](https://user-images.githubusercontent.com/52232895/128784318-ddb8f6c8-f60c-4ec8-b535-3dfe65df5343.png)
![Screenshot (206)](https://user-images.githubusercontent.com/52232895/128784333-91ea69ec-9ebe-4377-9550-dc2e452dba63.png)

**Comment by glennhickey** [comment]
> The .pack file is there on disk as well

no, it isn't.  that's why you get the error.

**Comment by jeizenga** [comment]
It looks like there's an underscore missing in your filepath.
