### ISSUE TITLE
GCSA constructor failed 

### ISSUE THREAD

**Issue by lucky-syn** [vgteam/vg#3400]
**1. What were you trying to do?**
      build an pan genome.

**2. What did you want to happen?**

       Get gcsa index  file 
**3. What actually happened?**
        Got a stacktrace

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Generating kmer files...
Building the GCSA2 index...
InputGraph::InputGraph(): 2614062776 kmers in 1 file(s)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
ERROR: Signal 6 occurred. VG has crashed.
```

**5. What data and command can the vg dev team use to make the problem happen?**

vg index -p -b ./temp/  -t 64 -g Chr1.gcsa Chr1.pruned.vg
**6. What does running `vg version` say?**
    v1.30.0
```
Place vg version output here
```

**Comment by jltsiren** [comment]
How much memory do you have available? VG generated ~2.6 billion 16-mers for the graph, and reading them into memory will take ~64 GB in addition to the in-memory structures the construction uses.
