### ISSUE TITLE
vg map crash

### ISSUE THREAD

**Issue by lt11** [vgteam/vg#3414]
**1. What were you trying to do?**
Mapping short-reads against a vg graph. The graph was built using pggb. Then it was converted to vg format, chopped, pruned, and indexed.

**2. What did you want to happen?**
Obtain a gam file.

**3. What actually happened?**
Something bad:
```
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
terminate called recursively
  what():  Attempted to get handle for node 1777689 not present in graphterminate called recursively

ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.34.0 "Arguello"
Stack trace (most recent call last) in thread 15544:
#17   Object "", at 0xffffffffffffffff, in 
#16   Object "", at 0x1c8f4e2, in 
#15   Object "", at 0x12d30e8, in 
#14   Object "", at 0x1bc889d, in 
#13   Object "", at 0xe9119f, in 
#12   Object "", at 0x1bcb177, in 
#11   Object "", at 0x1bc283b, in 
#10   Object "", at 0xe9134a, in 
#9    Object "", at 0xb8436a, in 
#8    Object "", at 0x50f3aa, in 
#7    Object "", at 0x1bd8f99, in 
#6    Object "", at 0x1bd85aa, in 
#5    Object "", at 0x1b171d3, in 
#4    Object "", at 0x1bb65c8, in 
#3    Object "", at 0x1b1781b, in 
#2    Object "", at 0x578f7a, in 
#1    Object "", at 0x57b913, in 
#0    Object "", at 0x12d64cb, in 
```

**5. What data and command can the vg dev team use to make the problem happen?**
I can provide the graph and the short-reads if needed.

**6. What does running `vg version` say?**

```
vg version v1.34.0 "Arguello"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by anovak@octagon
```

**Comment by jltsiren** [comment]
What were the exact vg commands you used for converting the graph, chopping it, pruning it, indexing it, and mapping the reads?

It looks like the graph and the GCSA index you provide to `vg map` do not match, and the mapper gets seeds from the index that do not exist in the graph. There are several reasons why this could happen, depending on the exact commands.

**Comment by lt11** [comment]
I was running these commands:
### graph conversion
vg view --threads "${n_threads}" --gfa-in "${gfa_graph}" --vg > "${vg_graph}"
### chopping
vg mod -X 256 "${vg_graph}" > "${vg_chp}"
### indexing
vg index --temp-dir "${TMP}" --threads "${n_threads}" \
-x "${x_idx}" -k 16 "${vg_chp}"
vg ids "${vg_chp}" -m node-map.vg
vg prune -t "${n_threads}" -u --mapping node-map.vg -k 24 -e 3 -s 33 -M 32 \
"${vg_chp}" > "${vg_prn}"
vg index --temp-dir "${TMP}" --threads "${n_threads}" \
-g "${g_idx}" -Z 20480 -k 16 "${vg_prn}"
### mapping
vg map -d "${vg_base}" \
-f "${fq_1}" -f "${fq_2}" > out.gam

I'm currently re-running everything in batch mode to make sure I did not mess up using the interactive shell.

**Comment by lt11** [comment]
Yep, same problem in batch mode. I'll try autoindex. Thanks for feedbacks!

**Comment by lt11** [comment]
Everything ok with autoindex. Thanks for your help!

**Comment by ekg** [comment]
Hooray for autoindex 👏

**Comment by jltsiren** [comment]
In case someone is interested: the issue was not passing the node mapping from `vg prune` to `vg index`. But autoindex is usually the right solution in the scenarios it supports.
