### ISSUE TITLE
Sim/Mapping example correction

### ISSUE THREAD

**Issue by jjfarrell** [vgteam/vg#343]
In the README.md, the example for simulating and mapping reads shows:

` vg map -r <(vg sim -n 1000 -l 150 x.xg ) -x x.xg -g x.gcsa -k 22 >aln.gam`

However, it generates the following error for the vg sim command line:
[vg sim] error: we need an xg index to sample reads from

It looks like the -x parameter is missing from the vg sim command line ....

`vg map -r <(vg sim -n 1000 -l 150 -x x.xg ) -x x.xg -g x.gcsa -k 22 >aln.gam`

This runs fine.

A similar update for the documentation is needed for the surject  example with the addition of the -d parameter to point to the rocksdb-backed index:

`vg surject -p x -b aln.gam >aln.bam`

Should be:

vg surject  -d x -b aln.gam >aln.bam

**Comment by adamnovak** [comment]
I'm not sure about the second change (where's the path for the RocksDB index?) but you're right that these are out of date.
