### ISSUE TITLE
vg convert creates different graphs depending on output format

### ISSUE THREAD

**Issue by MBMumphrey** [vgteam/vg#3435]
**1. What were you trying to do?**
I have a graph in GBZ format that I converted to XG format for analysis. I also wanted to convert the same graph to GFA for visualization with Bandage. Both conversions were using `vg convert`.

**2. What did you want to happen?**
I wanted to have an XG and GFA representation of the same graph.

**3. What actually happened?**
The XG and GFA graphs were different.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
There was no stack trace.
```

**5. What data and command can the vg dev team use to make the problem happen?**

```
$ vg convert -Z graph.gbz -f > graph.gfa
$ vg stats -z graph.gfa 
nodes   391264
edges   598661
$ vg convert -Z graph.gbz -x > graph.xg
$ vg stats -z graph.xg 
nodes   655561
edges   862958
```

**6. What does running `vg version` say?**

```
vg version v1.34.0 "Arguello"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by anovak@octagon
```

**Comment by jltsiren** [comment]
All three formats have different semantics, and conversions between them are sometimes lossy. Here, GFA has segments that have string names and can be arbitrarily long. All graphs in the VG ecosystem have nodes with integer identifiers, and the length of a node is often restricted to 1024 bp or less for various reasons.

When you convert GFA to GBZ, the default conversion chops the segments into 1024 bp nodes and stores a node-to-segment translation that can be used to restore the original segments. If you convert the GBZ back to GFA, you get the same segments.

There is no similar translation in the XG format, so the XG graph only has the chopped nodes. If you want a GFA graph with segments matching XG nodes, you have to base the conversion on the XG graph.

**Comment by MBMumphrey** [comment]
I see. I went back and chopped my original graph down to smaller node sizes, and now the conversion from GBZ to GFA and XA are the same. Thank you!
