### ISSUE TITLE
Tests have undocumented dependencies on Mac OS X

### ISSUE THREAD

**Issue by jeizenga** [vgteam/vg#347]
The tests require GNU coreutils, which is not pre-installed on Macs. There's a test in tests/t/20_vgtordf.t that uses a command `roqet` that I also don't have. I'm running El Capitan 10.11.4.

**Comment by jjfarrell** [comment]
The Mac OS X documentation presently includes coreutils as one of the required packages to install with home brew or port install.

**Comment by jeizenga** [comment]
So it does! Oops. I think what actually happened is that the Homebrew install prepends 'g' to all the commands by default (e.g. gsort), so the commands in the test come up as missing. I had to manually add /usr/local/opt/coreutils/libexec/gnubin to my path to get around it.
