### ISSUE TITLE
how to construct a graph of two genomes  from two  species

### ISSUE THREAD

**Issue by Aannaw** [vgteam/vg#3508]
Hello,Professor
I have two genomes from two species. My end goal is to construct  a graph of the two genomes from two species and then map 
tens of illumina short reads to the graph. But I am not sure how to construct the graph taking a VCF file and the reference sequence by "vg construct". Should I combine  the two genomes from two species into a input fasta by "cat" ? Also,  how do I generate the prior vcf  needed by "vg construct"?
I would appreciate it if you could give me any suggestions. 
Best wishes !

**Comment by jltsiren** [comment]
You should take a look at the [PGGB pipeline](https://github.com/pangenome/pggb), which builds a graph by aligning the input sequences. `vg construct` is primarily intended for building a graph from a reference sequence and a set of variants in a VCF file.

**Comment by Aannaw** [comment]
Hello,Professor

I have read the PGGB pipline you recommended. I still have some confusion with vg. The reference sequence is a genome assembly? In vg pipeline, How should I generate the vcf file of a set of variants. Maybe it is called through illumina reads of some samples of different species basing on the reference sequnece? 

Looking forward with your reply!

Best wishes!

**Comment by jltsiren** [comment]
If you have an assembled reference sequence and a VCF file describing variation relative to the reference sequence, you use `vg construct` for building the graph. If you don't have a VCF file, you don't need it. If you have multiple assembled genomes, you should use other tools such as PGGB for building the graph.

**Comment by diriano** [comment]
Dear @jltsiren , after building the graph with PGGB with multiple genome can I use VG to call variants?

**Comment by ekg** [comment]
Yes. And there is even a command line option in pggb to run the variant
deconstruction with VG.
