### ISSUE TITLE
Got an error called: Signal 6 occurred. VG has crashed.

### ISSUE THREAD

**Issue by ZoeYang2020** [vgteam/vg#3516]
**1. What were you trying to do?**
I was trying to use vg surject to convert gam into bam 
./vg surject -x nm_3ST_100k_sorted_graph.xg -p NC_017518 -l -i NMI97348_mapped.gam -b > NMI97348_mapped.bam

**2. What did you want to happen?**
I want to get the bam file output for following variant calling

**3. What actually happened?**
when I run the command,

I got the errors as following 

terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_FUK95n/stacktrace.txtterminate called recursively
  what():  Attempted to get handle for node 24554 not present in graph
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_NB5TTq/stacktrace.txt
Please include the stack trace file in your bug report!
terminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_Bcqxepterminate called recursively
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_vEMkZn/stacktrace.txt
Please include the stack trace file in your bug report!

Please include the stack trace file in your bug report!
ERROR: Signal 6ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

Crash report for vg v1.34.0 "Arguello"
Stack trace (most recent call last) in thread 66456:
#17   Object "", at 0xffffffffffffffff, in
#16   Object "", at 0x1c8f4e2, in
#15   Object "", at 0x12d30e8, in
#14   Object "", at 0x1bc889d, in
#13   Object "", at 0xb4ae03, in
#12   Object "", at 0x1bcb177, in
#11   Object "", at 0x1bc283b, in
#10   Object "", at 0xb4a781, in
#9    Object "", at 0xb4a2f2, in
#8    Object "", at 0x4f8bd9, in
#7    Object "", at 0x1bd8f99, in
#6    Object "", at 0x1bd85aa, in
#5    Object "", at 0x1b171d3, in
#4    Object "", at 0x1bb65c8, in
#3    Object "", at 0x1b1781b, in
#2    Object "", at 0x1b18dd9, in
#1    Object "", at 0x57b913, in
#0    Object "", at 0x12d64cb, in

Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**
 I also tried vg pack, vf call, got very similar error too

**6. What does running `vg version` say?**

```
Place vg version output here
vg version v1.34.0 "Arguello"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by anovak@octagon

**Comment by jeizenga** [comment]
Is it possible to share the data that produced the error?

**Comment by ZoeYang2020** [comment]
Would love to share the data. it seems i can't directly upload the file here, the format is not recognized.  how can I upload the data into the channel. 
Can I have you email please, I can send it to you through email

**Comment by jeizenga** [comment]
You can send it to joeizeng@gmail.com

**Comment by ZoeYang2020** [comment]
I have sent you the data:) Thanks

**Comment by ZoeYang2020** [comment]
What I have done
 1)is using 3 genomes to build the graph using pggb

 2) using odgi to sort the graph
odgi sort -i $input_gfa -o - -p Ygs -P | odgi view -i - -g > nm_3ST_100k_sorted_graph.gfa

3)using vg autoindex to index the gfa flie
$vg autoindex --workflow giraffe -t 16  --prefix 3ST_100K -g $input_gfa

4)using the giraffe to map the paired short reads, and get a gam file 
$vg giraffe -Z $idx -m $mini_idx -d $dist -f $data_fa/NMI97348_R1_P.fastq -f $data_fa/NMI97348_R2_P.fastq -N NMI97348 > NMI97348_mapped.gam

The error that I posted here is the fifth step which I want to try convert the gam file into bam, then call variant. 

Thank you very much

**Comment by ZoeYang2020** [comment]
As my data is not very big, I tried vg map to map the paired reads to the graph
Then I try the ./vg surject to convert gam into bam, got a warning saying 
[vg::Surjector]: **Refusing to perform very large alignment against 508178 bp strand split subgraph for read K00198:344:HWVK7BBXX:5:1103:16244:4659**2; suppressing further warnings.

**Comment by JD12138** [comment]
I got the same error message as you.Could you please tell me why?

**Comment by jeizenga** [comment]
This message is a warning, not an error. We currently don't have the capacity built into `vg surject` to do split alignments, so it needs to re-align over large structural variants in order to produce a BAM. With large enough variants, this is too computationally costly, so we decline to produce a mapping for those regions instead. That's what this warning indicates. If you had a crash, it is most likely for some other reason.
