### ISSUE TITLE
Is vg compatible with minigraph now?

### ISSUE THREAD

**Issue by biozzq** [vgteam/vg#3520]
Dear all,

Can I use minigraph+Giraffe to achieve genotyping of structural variants in the framework of the graph genome? Thank you in advance.

Sincerely,
Zheng zhuqing

**Comment by jltsiren** [comment]
The situation has not changed. Minigraph does not store enough information in the GFA to determine which paths in the graph correspond to the original assemblies. You have to align the sequences back to the graph and add the paths as P-lines or W-lines to the GFA file. Here is a [description of a Cactus pipeline](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md) we use for making (human) graphs built by minigraph useful for Giraffe.

**Comment by glennhickey** [comment]
@jltsiren Are "path cover" gbwt's still an option?  If so, it'd be possible in theory to index a mingraph for giraffe, then make a vcf with vg call.

**Comment by jltsiren** [comment]
@glennhickey The path cover option exists, but it's not that suitable for real use. We got better results with 3 real samples in the HGSVC graph (which should be similar to minigraph graphs) than with path cover.

**Comment by glennhickey** [comment]
Makes sense.  Best to use `vg map` instead on minigraph graphs then
