### ISSUE TITLE
vg index command was killed

### ISSUE THREAD

**Issue by wzhang42** [vgteam/vg#3547]
Hi, Sir, 
I download the graph file **1000GPlons_hs38d1.vg** from https://cgl.gi.ucsc.edu/data/giraffe/mapping/graphs/for-NA19239/1000gplons/hs38d1/.   Then, I use "vg index -x 1000GPlons_hs38d1.xg -g 1000GPlons_hs38d1.gcsa -k 16 1000GPlons_hs38d1.vg", then it was killed without any message. But I use the small test dataset , "vg index -x x.xg -g x.gcsa -k 16 x.vg" , it's ok.  What I should do.?   Thank you in advance.

**Comment by jltsiren** [comment]
You need a GCSA index only for the old `vg map` aligner, which is slower than `vg giraffe`. You can find prebuilt graphs and indexes named `1000GPlons_hs38d1_filter.*` and `1000GPlons_hs38d1_filter_forvgmap.*`. They are almost the same as `1000GPlons_hs38d1.*`, except that variants in long segmental duplications have been filtered out, as we found that it improves genotyping accuracy.

**Comment by wzhang42** [comment]
Hi, jltsiren, Many thanks for your reply.
