### ISSUE TITLE
VG crash : reads mapping visualisation with vg view  

### ISSUE THREAD

**Issue by Chaima-Bouchenak** [vgteam/vg#3558]
**1. What were you trying to do?**
Create a pdf file 
```
vg view -d ref.vg -A mappedL1.gam mappedL2.gam mappedL3.gam mappedL4.gam mappedL5.gam | dot -Tpdf -o aln.pdf
```

**2. What did you want to happen?**
to visualize the results of mapped reads (.gam) on my ref graph (.vg)

**3. What actually happened?**
VG crash
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [io::ProtobufIterator] could not parse message
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_EDFr2V/stacktrace.txt
```
**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
No
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**

```
vg version v1.38.0 "Canossa"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by anovak@octagon
```

**Comment by glennhickey** [comment]
`-A` can only take one argument so view multiple gams like this you'd need to combine them. Ex:
```
cat  mappedL1.gam mappedL2.gam mappedL3.gam mappedL4.gam mappedL5.gam > mappedL1-5.gam
vg view -d ref.vg -A mappedL1-5.gam | dot -Tpdf -o aln.pdf
```

**Comment by Chaima-Bouchenak** [comment]
> ```
> vg view -d ref.vg -A mappedL1-5.gam | dot -Tpdf -o aln.pdf
> ```

Thanks for the quick reply , i actually tried that but i still get the same error and VG crash 
PS : i m working with test data so i dont think it's a data problem , my graph has 29 nodes, 50 bp in each one

**Comment by glennhickey** [comment]
Either your graph or gam is invalid.  probably easiest to determine which by trying to view them separately
```
vg view ref.vg
vg view -a mappedL1-5.gam
```

**Comment by Chaima-Bouchenak** [comment]
i did , both commands worked 

also when i run the below one, it works fine. I think the problem comes from my attamption to convert it to PDF  file.
would you recommend adding any parameters or visualizing read alignment on ref. in another file format?

To explain what i want to do:
1 -

**Comment by glennhickey** [comment]
So you run 
```
vg view -d ref.vg -A L1.gam
``` 
and it works, but then you run 
```
vg view -d ref.vg -A L1.gam | dot -Tpdf -o aln.pdf
``` 
and it aborts with `what():  [io::ProtobufIterator] could not parse message`?

That sounds like an issue with your shell not recognizing the `|` character (?!?!) rather than vg.  To get around using the pipe, you can try
```
vg view -d ref.vg -A L1.gam > aln.dot
dot -Tpdf aln.dot -o aln.pdf
```
