### ISSUE TITLE
Widget: Map over indexed GAM and associated graph

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#356]
Given an indexed GAM and the graph to which it is aligned, we should be able to map over it (in parallel) in (possibly overlapping) chunks.

Each chunk should consist of a VG graph and an index of the alignments, which can be efficiently queried to get the alignments visiting a node. This indexing structure is probably where most of the work will go.

**Comment by adamnovak** [comment]
Erik wants to implement the GAM index the hard way.

**Comment by glennhickey** [comment]
Maybe an XG-style index can help here?

Use Rocksdb to map each GAM alignment to a unique ID.

Then throw the alignment IDs into an integer vector, and use a bit vector
to look up nodes in the usual way.

Ex:  if Node 1 is contained in Alignments 5 and 6, and Node 2 is contained
in Alignments 5, 6, 7:

Integer Vector:  5, 6, 5, 6, 7
Bit Vector:         1, 0, 1, 0, 0

Could be quicker than an all-Rocksdb approach, at least for an exhaustive
mapping that doesn't rely on id assumptions..

**Comment by ekg** [comment]
I implemented the GAM index the hard way.
