### ISSUE TITLE
ERROR: Signal 6 occurred. VG has crashed

### ISSUE THREAD

**Issue by Wenfei-Xian** [vgteam/vg#3560]
**1. What were you trying to do?**
Mapping short reads to reference and genotyping SV

**2. What did you want to happen?**
ERROR: Signal 6 occurred. VG has crashed

**3. What actually happened?**
vg: src/packer.cpp:883: size_t vg::Packer::average_node_quality(size_t) const: Assertion `total_node_quality(i) == 0' failed.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.38.0
Stack trace (most recent call last) in thread 2095:
#8    Object "", at 0xffffffffffffffff, in 
#7    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x1d6bb52, in __clone
#6    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x1367de8, in start_thread
#5    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x1ca03fd, in gomp_thread_start
#4    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0xdacd21, in vg::Packer::make_compact() [clone ._omp_fn.6]
#3    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x1cc3855, in __assert_fail
#2    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x589a23, in __assert_fail_base.cold
#1    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x589b53, in abort
#0    Object "/tmp/global2/wxian/software/anaconda3/envs/vg/bin/vg", at 0x136b1cb, in raise

```

**5. What data and command can the vg dev team use to make the problem happen?**
vg pack -x Chr1.vg -g Chr1.gam -o Chr1.pack -Q 5 -s 5

**6. What does running `vg version` say?**

```
vg: variation graph tool, version v1.38.0 "Canossa"
```

**Comment by Wenfei-Xian** [comment]
Many thanks for your quickly reply!
When I try "vg validate Chr1.vg -a Chr1.gam"
It printed a lot on scream:  

`Invalid Alignment:
{"annotation": {"fragment_length": 357, "fragment_length_distribution": "-I 356.094737 -D 62.373611", "mapq_applied_cap": 88.01590482857543, "mapq_explored_cap": 0, "mapq_score_group": 2147483647, "mapq_uncapped": 2147483647, "proper_pair": true, "rescued": true, "secondary_scores": [159.99992386337604]}, "fragment_prev": {"name": "110820010345904111/1"}, "identity": 0.93069306930693074, "mapping_quality": 44, "name": "110820010345904111/2", "path": {"mapping": [{"edit": [{"from_length": 21, "to_length": 21}, {"from_length": 1}], "position": {"is_reverse": true, "node_id": "38428676", "offset": "10"}, "rank": "1"}, {"edit": [{"from_length": 1, "to_length": 1}], "position": {"is_reverse": true, "node_id": "38428312"}, "rank": "2"}, {"edit": [{"from_length": 2, "to_length": 2}, {"from_length": 1, "sequence": "C", "to_length": 1}, {"from_length": 15, "to_length": 15}, {"from_length": 1, "sequence": "A", "to_length": 1}], "position": {"is_reverse": true, "node_id": "38428311"}, "rank": "3"}, {"edit": [{"from_length": 5, "to_length": 5}, {"from_length": 1, "sequence": "A", "to_length": 1}, {"from_length": 26, "to_length": 26}], "position": {"is_reverse": true, "node_id": "38428310"}, "rank": "4"}, {"edit": [{"from_length": 1, "sequence": "T", "to_length": 1}, {"from_length": 6, "to_length": 6}, {"sequence": "TTA", "to_length": 3}, {"from_length": 18, "to_length": 18}], "position": {"is_reverse": true, "node_id": "38428309"}, "rank": "5"}]}, "quality": "KCgnKCgoKCgoKCgoKCgoJygoKCcoJygoKCgoKCcmKCgoKCgmKCgoKCYmKCgnKCgoKCgoJigoKCcoKCglKCgoKCUnKCcnKCgkJScoJycoJygkJyghKCEoIiQhIyEkJCMlJyUnJSg=", "score": 74, "sequence": "GTAATGAATAATAATATATATATTCGTTTTAAATATTATTAGTTTGATAGGTATTGATAAGAAAAAAATATTATAATATCTTATCAGTTAATTTATTTTTA", "time_used": 0.00027235999999999997}
Length of node 38428676 (14) exceeded by Mapping with offset 10 and from-length 22:
{"edit": [{"from_length": 21, "to_length": 21}, {"from_length": 1}], "position": {"is_reverse": true, "node_id": "38428676", "offset": "10"}, "rank": "1"}


Invalid Alignment:
{"annotation": {"fragment_length": 358, "fragment_length_distribution": "-I 356.094737 -D 62.373611", "mapq_applied_cap": 3.0102999566398121, "mapq_explored_cap": 23.263015907219099, "mapq_score_group": 2147483647, "mapq_uncapped": 15, "proper_pair": true, "rescuer": true, "secondary_scores": [165.99966274852113, 162.99959233552656, 162.99959233552656, 90]}, "fragment_prev": {"name": "110820010345916787/1"}, "identity": 0.96039603960396036, "mapping_quality": 1, "name": "110820010345916787/2", "path": {"mapping": [{"edit": [{"from_length": 3, "to_length": 3}], "position": {"is_reverse": true, "node_id": "33748728", "offset": "29"}, "rank": "1"}, {"edit": [{"from_length": 32, "to_length": 32}], "position": {"is_reverse": true, "node_id": "33748727"}, "rank": "2"}, {"edit": [{"from_length": 1, "to_length": 1}, {"from_length": 1, "sequence": "A", "to_length": 1}, {"from_length": 4, "to_length": 4}, {"from_length": 1, "sequence": "A", "to_length": 1}, {"from_length": 5, "to_length": 5}, {"from_length": 1, "sequence": "A", "to_length": 1}, {"from_length": 19, "to_length": 19}], "position": {"is_reverse": true, "node_id": "33748726"}, "rank": "3"}, {"edit": [{"from_length": 24, "to_length": 24}, {"from_length": 1, "sequence": "A", "to_length": 1}, {"from_length": 7, "to_length": 7}], "position": {"is_reverse": true, "node_id": "33748725"}, "rank": "4"}, {"edit": [{"from_length": 2, "to_length": 2}], "position": {"is_reverse": true, "node_id": "33748724"}, "rank": "5"}]}, "quality": "KCgoKCcoKCgoKCgoKCgoKCgoJygoKCcnKCgnKCgoKCQoKCgoKCgoKCgoKCQoKCgoKCgoKCcoKCcnJygoKCgnJSgnJycnIyMnKCcnIycnHyclJSInIyclIyQlISEhIR0aHyMeHxg=", "score": 91, "sequence": "AGGATACAATTCTTACGCCTTTAAGATCCGGTTGCGATTTAAGTTCTAATACTCAATCATACACATGACATCAAGTCATATTTGACTCCAAAACACTAACC", "time_used": 0.00028951999999999998}
Length of node 33748728 (17) exceeded by Mapping with offset 29 and from-length 3:
{"edit": [{"from_length": 3, "to_length": 3}], "position": {"is_reverse": true, "node_id": "33748728", "offset": "29"}, "rank": "1"}`

**Comment by Wenfei-Xian** [comment]
There are commands what I used:

vg construct -f  -S  -a -r Chr1.fa -v Chr1.vcf.gz > Chr1.vg
vg autoindex --workflow giraffe -r Chr1.fa -v Chr1.vcf.gz -p Chr1
vg giraffe -Z Chr1.giraffe.gbz  -m Chr1.min -d Chr1.dist -f ../1741.1001G.PE.1.fastq.gz -f ../1741.1001G.PE.2.fastq.gz  > Chr1.gam
**vg pack -x Chr1.vg -g Chr1.gam -o Chr1.pack -Q 5 -s 5 ( Error happened )**

vg snarls Chr1.vg > Chr1.snarls
vg call Chr1.vg -k Chr1.pack -r Chr1.snarls -v Chr1.vcf.gz -s Chr1 -d 2 > Chr1.genotypes.vcf

**Comment by glennhickey** [comment]
`autoindex` must have changed (chopped?) the nodes in your graph.  To fix this, you'd need to use `Chr1.giraffe.gbz` instead of `Chr1.vg` as input to every command after `vg giraffe`.  

Did you get the commands you're using from one of our tutorials?  If so please let me know which, so I can update it.

**Comment by Wenfei-Xian** [comment]
Thanks, as recommonded  by our lab members, when I remove the -f  (don't chop up alternate alleles from input VCF): vg construct -S -a -r Chr1.fa -v Chr1.vcf.gz > Chr1.vg. it work on vg pack. 

I will try `Chr1.giraffe.gbz` instead of `Chr1.vg`. 

The commands from https://github.com/vgteam/vg/wiki/SV-genotyping-with-vg (May be you can update this page to adapt to the giraffe algorithm)
https://github.com/vgteam/vg/wiki/Mapping-short-reads-with-Giraffe

**Comment by glennhickey** [comment]
No, you don't want to use `vg augment` when genotyping SVs with short reads.  While you'd think that augment would help resolve exact breakpoints, in practice the added graph complexity hurts accuracy (at least in my testing).
