### ISSUE TITLE
Contigs in VCF must be in ASCII-lexicographic order. Encountered contig 'chr10' after contig 'chr9' in VCF file

### ISSUE THREAD

**Issue by JD12138** [vgteam/vg#3563]
hello,
    I use vg autoindex to construct a vg index.But it reported an error "**Contigs in VCF must be in ASCII-lexicographic order. Encountered contig 'chr10' after contig 'chr9' in VCF file**".This is an indel VCF.
    I don't know the reason.I used another  snp VCF file to construct an index and succeeded.And that VCF file is sorted in chromosomal order.
    The following are my codes:
     **vg autoindex --workflow giraffe -r $reference -v $vcf_snp -v $vcf_indel -p pan_index -t 20** 

Thank you very much!

**Comment by jeizenga** [comment]
VG expects the chromosomes to be sorted into lexicographic order rather than numerical order (in fact, this is what most genomics tools expect). In lexicographic order, the numbers are treated as strings, so 10 through 19 come before 2, like this:
```
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
2
20
21
22
3
4
5
6
7
8
9
```

**Comment by JD12138** [comment]
Thank you very much! 
But I used a snp vcf file which was in numeric order to construct an index and succeeded. I don't know why I added another indel vcf file then failed. Is there any difference between snp and indel files?

Another question. If I use a sample to construct a graph and then I map the sample to that graph and call variants.Then are the variants all included in the graph? I mean ,will there be novel variants which not in the graph?

**Comment by jeizenga** [comment]
So you're using two VCFs per chromosome? If so, that could be the issue. Try merging each chromsome's VCF first.

You can call additional variants that are not included in the graph construction by using the `vg augment` subcommand to add variant candidates from the reads into the graph after mapping. The process is described here:
https://github.com/vgteam/vg/wiki/Whole-genome-calling-and-genotyping#whole-genome-calling
