### ISSUE TITLE
Missing new line/truncated quality string when output a SAM file

### ISSUE THREAD

**Issue by maxrossi91** [vgteam/vg#3570]
**1. What were you trying to do?**
Align reads to the reference with a parallel execution and out a SAM file

**2. What did you want to happen?**
get a SAM file

**3. What actually happened?**
the sam file have two lines that are joined together e.g.
```
simulated.34557 163     21      29209457        60      100M    =       29209681        324     TGAAACTGCACTCCAGCCTGGGCAACAGAGTGAGACTCTGTCTCTAAAAAAAAAAAAAAAAAAACTTTCTATAATGATAAACATTTTCTGTGTATATGCTHHHHIHHIHHHGHIIGIIIHGIIIHHIDHFDGGGIIHCDEG@II;IIEDIIIIFHIEEGIIIIGGDGFIFAI9simulated.34558        99      21      27095727        60      100M    =       27095990        363     CTATTATCCCTTAATTGGGGATTGACAGTGTCTGTAATTACAGTTAGGATTATATTATTTTAAATGTATTCTTTGGACCGTCTTATCTTTCAGAATTTCA        HHHIIHIIHGIGIHHHHIIGIGIGIFFIDHHHIIGIIHIIIHCICA@EDIHIFIIIIBIIGIIHIIIDAIIGHI?IIIIII?I;IIFIGEIHC8DB@II<
```

the original read is 

```
@simulated.34557/2
TGAAACTGCACTCCAGCCTGGGCAACAGAGTGAGACTCTGTCTCTAAAAAAAAAAAAAAAAAAACTTTCTATAATGATAAACATTTTCTGTGTATATGCT
+
HHHHIHHIHHHGHIIGIIIHGIIIHHIDHFDGGGIIHCDEG@II;IIEDIIIIFHIEEGIIIIGGDGFIFAI9=<=F<IIFIII:D;IFII<IEBIGIE8
```

It seems the quality string has been truncated. However, it occurs at line 2663 of the SAM file for unpaired reads (two separate runs of the same set of reads with different references. The read that got stuck was different in both cases) but this might be just a coincidence.

This happened in more than one case, with bot `vg map` and vg giraffe` and paired and unpaired reads.

**5. What data and command can the vg dev team use to make the problem happen?**
Some examples:
```
vg map -t 1 -d Chr21.10 -f Chr21.1M.HG002.R1.fastq -f Chr21.1M.HG002.R2.fastq  --surject-to sam > Chr21.10.HG002.mate.sam
```
```
vg giraffe -t 1 -d Chr21.10.dist -Z Chr21.10.giraffe.gbz -m Chr21.10.min -f Chr21.1M.HG002.fastq -o SAM > Chr21.10.HG002.sam
```

**6. What does running `vg version` say?**

```
vg version v1.38.0 "Canossa"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by anovak@octagon
```

**Comment by jeizenga** [comment]
The fact that it happened with both `vg map` and `vg giraffe` makes me think it's probably happening in the function that locally realigns to the reference to make a BAM file. Is it possible to share the graph that you encountered this on?

**Comment by maxrossi91** [comment]
This should do the job

```
wget ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz
wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz

bcftools query -l ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz | grep "HG00111" -v | head -n 5 > sample_list.txt

bcftools view -v snps,indels -m2 -M2 --min-ac 1 -S sample_list.txt -Oz -o chr21_10.vcf.gz ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz;

vg autoindex --workflow giraffe --prefix Chr21.10 --ref-fasta Homo_sapiens.GRCh38.dna.chromosome.21.fa --vcf chr21_10.vcf.gz -t 32

vg giraffe -t 1 -d Chr21.10.dist -Z Chr21.10.giraffe.gbz -m Chr21.250.min -f <fastq reads> -o SAM > out.sam
```

let me know if you need the graph that I have stored.

**Comment by jeizenga** [comment]
Okay, I've replicated this locally, and it seems to even have the bug at a deterministic set of reads. It shouldn't be too hard to fix. In the meantime, it seems that outputting to BAM and then piping through `samtools view -h` doesn't result in the same issue.

**Comment by maxrossi91** [comment]
Ok thanks, I will go with this workaround.

**Comment by jeizenga** [comment]
@Chaima-Bouchenak, are you sure that the `vg giraffe` command completed? I've seen this error after a mapping step crashed or exited. Another case I've seen is when a download was interrupted.

**Comment by Chaima-Bouchenak** [comment]
@jeizenga I'm assuming it ran all well as it was done through a bash script and I had no error message with ```vg giraffe```, but the next command ```samtools sort``` threw one

**Comment by adamnovak** [comment]
@Chaima-Bouchenak This should be a new issue; the problem here only affected the text SAM files as far as I can tell. I've opened #3677 for you.
