### ISSUE TITLE
Widget: Superbubble and Alignments to Haplotypes

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#359]
Given a superbubble and some perfect match alignments clipped so that they don't extend beyond the superbubble, generate a collection of candidate haplotypes supported by at least 1 alignment, as paths running through the superbubble.

This is only going to work on superbubbles that are fully bridged by at least one alignment.

**Comment by ekg** [comment]
The extension comes up with possible haplotypes consistent with the
alignments but not limited to paths they literally represent.

**Comment by adamnovak** [comment]
OK this should be mostly done. Just need to wire it up.
