### ISSUE TITLE
Installation bug on Mac

### ISSUE THREAD

**Issue by WenyuLiang** [vgteam/vg#3602]
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/y8/2rld2mxd44n4t1d3jy14kxy00000gn/T/aligner-f345c6.cpp
clang: note: diagnostic msg: /var/folders/y8/2rld2mxd44n4t1d3jy14kxy00000gn/T/aligner-f345c6.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/wenyu/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make: *** [obj/aligner.o] Error 254

**Comment by jltsiren** [comment]
This is a known compiler bug. Apple Clang 13 crashes when compiling some vg sources on an M1 Mac running macOS Monterey. You may try reporting the issue to Apple, and they may eventually fix it. Until then, the only known solution is using another computer. Downgrading to macOS Big Sur may also help if your computer supports it.

**Comment by WenyuLiang** [comment]
Ok, thank you!

**Comment by adamnovak** [comment]
Do we need to do something to work around this bug, such as developing Mac build instructions that give a procedure for installing and building with a fixed compiler?

**Comment by jltsiren** [comment]
I'm not sure there is a fixed compiler.

I get similar crashes when compiling GBWTGraph tests on my M1 laptop, so the crash is probably caused by libhandlegraph code.

**Comment by jltsiren** [comment]
After updating to macOS 12.3 and command line tools 13.3, everything seems to be working again.
