### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by WenyuLiang** [vgteam/vg#3604]
I install vg via docker but I met a problem as follows: (on Mac)

root@dd3a5e401c40:/vg/lwy/test# vg construct -r small/x.fa -v small/x.vcf.gz >x.vg
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)

**Comment by adamnovak** [comment]
I'm going to close this issue; I think that that message is supposed to happen in your environment.
