### ISSUE TITLE
Extract haplotype sequences from gbwt

### ISSUE THREAD

**Issue by NedaTavakoli** [vgteam/vg#3605]
I used `vg gbwt` to build gbwt indexes for each chromosome of the 1000 Genomes Project (1000 GP). Next, using the indexes I unfolded vg graphs (per chromosome) such that they only contain haplotypes. The obtained vg files are converted to GFA then FASTA format ( containing only haplotype paths). Now, how can I extract haplotype sequences from GFA/or FASTA format 

For example for the chromosome 1, the gbwt file has:

`1840731 paths with names, 2504 samples with names, 5008 haplotypes, 1 contigs with names`

These are some output results for chromosome 1:

```
cat chr1_pruned.gfa | head -10
H	VN:Z:1.0
S	4760953	AGATTTTTAAAAAACAGTTTCTAAGGAAGGGC
S	6586721	AAGATAAAATATTTACAGTATTGTAAAGTATT
S	13173442	CATTTCCATCAGGCTTTGATCTTTGAAATGTC
S	18507388	T
S	23208738	C
S	5284586	AGGTTGCAGTGAGCCAAGATCGTGCCATTGCA
S	19495969	G
S	13515975	TGCTCTTCCGCCCCACCCTCCGCCGACTCAGC
S	22345553	CGCCACCA
```

```
cat chr1_pruned.gfa | grep L| head -10
L	4760953	+	4760954	+	0M
L	6586721	+	6586722	+	0M
L	13173442	+	13173443	+	0M
L	18507388	+	18507389	+	0M
L	23208738	+	23208740	+	0M
L	5284586	+	5284587	+	0M
L	19495969	+	19495971	+	0M
L	13515975	+	13515976	+	0M
L	22345553	+	22345555	+	0M
L	22345553	+	22345554	+	0M
```

```
cat chr1_pruned.fa | head -10
>4760953
AGATTTTTAAAAAACAGTTTCTAAGGAAGGGC
>6586721
AAGATAAAATATTTACAGTATTGTAAAGTATT
>13173442
CATTTCCATCAGGCTTTGATCTTTGAAATGTC
>18507388
T
>23208738
C
```
```
cat chr1_pruned.fa |wc -l
51683102
```
Since `chr1_pruned.fa` has 51683102 lines, and the total number of haplotypes is 5008, how can I extract sequences for 5008 haplotypes?

**Comment by Chaima-Bouchenak** [comment]
Hello,

Did you tried the command ``vg paths`` with the argument `` -F, --extract-fasta`` it print thes paths in FASTA format. When selectiong the GBWT as input, it will generate the fasta sequence for each haplotype.
``
