### ISSUE TITLE
Covert vg graph to edge-labeled 

### ISSUE THREAD

**Issue by NedaTavakoli** [vgteam/vg#3608]
Is there any way to convert a vg graph to an edge-labeled vg graph? 

Thanks

**Comment by jeizenga** [comment]
All of the VG tools are based on a node-labeled implementation. At this point, we have a large amount of code investment in this implementation, so I doubt it will ever change, sorry. If you need an edge-labeled graph for a downstream analysis, I'd recommend using GFA as an interchange format and then converting the GFA into its edge-labeled representation.
