### ISSUE TITLE
vg giraffe

### ISSUE THREAD

**Issue by hgz2021** [vgteam/vg#3631]
Hello, vg team, I have a problem. When I used giraffe pipeline to call VCF, I found that when I input the data of single chromosome in VCF file, I would get VCF of 1 to 2G size. I am studying grapes, which has 19 chromosomes. So my final VCF file was 20GB to 40GB of data size, but when my input file turned into variation information for the entire genome (19 chromosomes), I got 1.4GB of VCF file. Which result should I believe?
 In this  is the process I ran.

vg=1.38.0
vg autoindex --workflow giraffe -r $ref.fasta -v $varients.vcf.gz -R XG  -p all_cute_

vg convert $name.xg -p > $name.pg

vg giraffe -x $name.xg -m $name.min -d $name.dist -Z $name.gbz  -f $f1 -f $f2 -t $thread > $sample_name.gam

vg augment $name.pg $sample_name.gam -m 2 -q 3 -Q 3 -t $thread -A $sample_name.aug.gam > $sample_name.aug.pg

vg snarls $sample_name.aug.pg > $sample_name.aug.snarls

vg pack -x $sample_name.aug.pg -g $sample_name.aug.gam -o $sample_name.aug.pack

vg call $sample_name.aug.pg -r $sample_name.aug.snarls -k $sample_name.aug.pack -s $sample_name > $sample_name.callsvcf

**Comment by adamnovak** [comment]
So if you build the graph with a VCF that only covers one chromosome, your final whole-genome called VCF is 20-40 GB, but when you use a larger VCF with variation from all the chromosomes to build the graph, your final VCF is only 1.4 GB?

Though you say you get the 20-40 GB files by combining 1-2 GB files for each chromosome. Are you running the whole construction, mapping and calling pipeline for each chromosome independently? What are you doing to identify and remove the reads that don't actually belong on the chromosome you are running, to keep them from mapping to weird places on the chromosome you are running and producing false variants?

My guess is that the smaller call set is likely to be better; 20-40 GB of variation sounds like a lot for one individual. But I'm not actually sure I understand the differences between the pipelines you are using to produce your two call sets; you only provided commands for one pipeline.

**Comment by hgz2021** [comment]
> 因此，如果您使用仅覆盖一条染色体的 VCF 构建图，则称为 VCF 的最终全基因组为 20-40 GB，但是当您使用具有所有染色体变异的更大 VCF 来构建图时，您的最终 VCF 是只有 1.4 GB？
> 
> 尽管您说通过为每个染色体组合 1-2 GB 文件来获得 20-40 GB 文件。您是否独立运行每个染色体的整个构建、映射和调用管道？您正在做什么来识别和删除实际上不属于您正在运行的染色体上的读数，以防止它们映射到您正在运行的染色体上的奇怪位置并产生错误的变异？
> 
> 我的猜测是较小的调用集可能会更好。对于一个人来说，20-40 GB 的变化听起来很多。但我实际上并不确定我是否理解您用来生成两个调用集的管道之间的区别；您只为一个管道提供了命令。

**Comment by hgz2021** [comment]
> So if you build the graph with a VCF that only covers one chromosome, your final whole-genome called VCF is 20-40 GB, but when you use a larger VCF with variation from all the chromosomes to build the graph, your final VCF is only 1.4 GB?
> 
> Though you say you get the 20-40 GB files by combining 1-2 GB files for each chromosome. Are you running the whole construction, mapping and calling pipeline for each chromosome independently? What are you doing to identify and remove the reads that don't actually belong on the chromosome you are running, to keep them from mapping to weird places on the chromosome you are running and producing false variants?
> 
> My guess is that the smaller call set is likely to be better; 20-40 GB of variation sounds like a lot for one individual. But I'm not actually sure I understand the differences between the pipelines you are using to produce your two call sets; you only provided commands for one pipeline.

Thank you for your reply. The pipeline I used has always been the pipeline mentioned above. I just changed the input file (VCF file at chromosome level or VCF file at genome level), and the corresponding index was generated according to the corresponding file, without index mismatch or parameter change. I saw your reply to others in question #3303. Can I assume that the input file of giraffe pipeline can only be genome level?

**Comment by adamnovak** [comment]
It is indeed only meant to work with a graph that covers the whole region being sequenced (usually the whole genome). Giraffe doesn't try to identify whether or not reads actually come from anywhere in the graph; it just places reads at the best place it can find for them. If you have a lot of reads from places not included in your graph, they will mismap to places that actually are in your graph, possibly with high mapping quality, and cause variant calling mistakes.

**Comment by hgz2021** [comment]
> It is indeed only meant to work with a graph that covers the whole region being sequenced (usually the whole genome). Giraffe doesn't try to identify whether or not reads actually come from anywhere in the graph; it just places reads at the best place it can find for them. If you have a lot of reads from places not included in your graph, they will mismap to places that actually are in your graph, possibly with high mapping quality, and cause variant calling mistakes.

Thanks for your help, I will close this comment
