### ISSUE TITLE
Only half of SVs in graph can be called by  `vg call`

### ISSUE THREAD

**Issue by BRLIA** [vgteam/vg#3636]
**1. What were you trying to do?**
I was trying to call VCFs from graph constructed by `minigraph` and `vg`. 
```
###vg call
##generate vcf file from graph genome
##min-length INT，only call variants > INT

#-a & > 50bp
vg call -t 30 $prefix.xg \
-k ${prefix}_${suffix}.pack \
--min-length 50 \
-a > ${prefix}_${suffix}_a.vcf

#> 50bp
vg call -t 30 $prefix.xg \
-k ${prefix}_${suffix}.pack \
--min-length 50 > ${prefix}_${suffix}.vcf
```

**2. What did you want to happen?**
I thought I would get most of SVs in the graph.

**3. What actually happened?**
Actually, I only call 146700+ SVs from graph, even I used `vg call -a`. If the graph constructed by 9 genome has too many complex nests, which lead to only 60% SVs that can be identified by 2rd reads.
![graph](https://github.com/BRLIA/markdown/blob/main/picture2.png?raw=true)

`vg version: 1.39`

**Comment by glennhickey** [comment]
You can count the number of top-level bubbles in your graph with 
```
vg stats $prefix.xg -R | awk '$13 == 0' | wc -l
```
`vg call -a` should print out (approximately) this many sites in your VCF.

If you want to print out all sites, including nested sites, then you can use `vg call -a -A`, which should give you something closer to the total number of bubbles
```
vg stats $prefix.xg -R | wc -l
```
`vg call`'s accuracy may be questionable on giant complex nested sites.

**Comment by BRLIA** [comment]
Thanks for your help. I will close the comment
