### ISSUE TITLE
vg index error

### ISSUE THREAD

**Issue by jinshangkun** [vgteam/vg#3638]
**1. What were you trying to do?**
I want to use 'vg giraffe' pipeline to genotype SV

**2. What did you want to happen?**

**3. What actually happened?**
I got an error when using 'vg autoindex' for whole genome, but running successfully for each singal chromosome.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**
No
```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**
.vg autoindex --workflow giraffe --prefix $prefix -R XG --ref-fasta $ref --vcf $vcf -t 1 -T ./

**6. What does running `vg version` say?**
[IndexRegistry]: Checking for phasing in VCF(s).
[W::vcf_parse] INFO 'SUPP' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SUPP_VEC' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SVMETHOD' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CHR2' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CIPOS' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CIEND' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'STRANDS' is not defined in the header, assuming Type=String
[IndexRegistry]: Chunking inputs for parallelism.
[IndexRegistry]: Chunking FASTA(s).
[IndexRegistry]: Chunking VCF(s).
[W::vcf_parse] INFO 'SUPP' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SUPP_VEC' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SVMETHOD' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CHR2' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CIPOS' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'CIEND' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'STRANDS' is not defined in the header, assuming Type=String
[E::bcf_translate] Unchecked error (2), exiting

```
version v1.32.0 "Sedlo"
```
Thanks for any solutions!

**Comment by jeizenga** [comment]
It's hard to say without seeing the files, but my guess is that this is due to malformed VCFs. The `bcf_translate` function is used to translate tags from one VCF file to another, so it's possible that missing tags are causing both the parse warning and the translate error.

**Comment by jinshangkun** [comment]
@jeizenga YES! Your guess is right. Thanks so much!
