### ISSUE TITLE
Clarification request: unmapped reads in VG (giraffe) ?

### ISSUE THREAD

**Issue by Chaima-Bouchenak** [vgteam/vg#3645]
Hello, 
Sorry to make support requests here, but the biostars link doesn't work.

I tried to look for the answer in your recent articles but it does not seem to be mentioned (maybe I missed it ?!).

Questions :
1- How does VG deal with unmapped reads? 
2 - In which file are they stored? (in order to parse it and retrieve them)
3 - with unphased VCF, would it be ''correct'' to use the argument ```--force  phasing``` to build a phased GBWT index (needed for the mapping step) as fellow : 
```
vg gbwt -x graph.vg -v var.vcf.gz --discard-overlaps --force-phasing --buffer-size 2000 -o graph.gbwt 
```

Best,
Chaima

**Comment by jltsiren** [comment]
If the aligner can't find an acceptable mapping for a read, it will output an `Alignment` object with an empty path into the same GAM file. That should translate into the appropriate representations of unmapped reads in other output formats.

`--force-phasing` should only be used when the VCF file is mostly phased. If it's completely unphased, the haplotype paths in the GBWT will probably be misleading and alignment accuracy may be worse than with just the reference.

**Comment by Chaima-Bouchenak** [comment]
@jltsiren Thank you , i've checked the other output formats and i should be able to work with that.

The second part is a bit confusing,
In [thise](https://github.com/vgteam/vg/wiki/VG-GBWT-Subcommand#vcf-parsing-options) Index construction tutorial , this was mentionned :
```
-force-phasing: Randomly phase unphased genotypes.
```
I understand that it's not necessary to use this arg when the input VCF is phased (as the genotypes are already phased) ?

**Comment by jltsiren** [comment]
If the haplotypes are not true haplotypes, they can easily be worse alignment targets than the reference sequence. If there are only a few unphased locations, random phasing will probably not cause too much troble, but it can make things computationally more efficient. If every genotype is unphased, the false haplotypes created by `--force-phasing` will mislead Giraffe into believing that variants always occur in combinations that are not seen in real data.
