### ISSUE TITLE
Missing emojis with vg view

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#365]
Some path names don't seem to produce emojis, such as B and E as seen here:
![test](https://cloud.githubusercontent.com/assets/7570351/15655848/eed560f4-266e-11e6-80ec-390538c9bf9e.png)

I don't think it's a graphviz issue, as empty boxes are produced with `vg find -n 1 -x graph.xg | vg view -dp -` 
```
digraph graphname {
    node [shape=plaintext];
    rankdir=LR;
    1 [label="1:TGTGGACAAGGTTTCAGTGTTA",shape=box,penwidth=2,pos="-100, -10"];
    2 [label="🍰 A  1 ",fontcolor="/dark28/7"];
    2 -> 1 [dir=none,color="/dark28/7", style=invis];
    { rank = same; 2; 1; };
    3 [label="🖗 B  1 ",fontcolor="/dark28/5"];   
    3 -> 1 [dir=none,color="/dark28/5", style=invis];
    { rank = same; 3; 1; };
    4 [label="🏖 C  1 ",fontcolor="/dark28/3"];
    4 -> 1 [dir=none,color="/dark28/3", style=invis];
    { rank = same; 4; 1; };
    5 [label="👸 D  1 ",fontcolor="/dark28/3"];
    5 -> 1 [dir=none,color="/dark28/3", style=invis];
    { rank = same; 5; 1; };
    6 [label="🗈 E  1 ",fontcolor="/dark28/1"];
    6 -> 1 [dir=none,color="/dark28/1", style=invis];
    { rank = same; 6; 1; };
}
```

Is there a way to either select which emojis represent the paths, or change the name of the paths without having to modify the fasta sequences and rebuild the graph?

**Comment by ekg** [comment]
You can modify pictogram.cpp to do this. It would be a good idea to make it
configurable. This all works on my Ubuntu setup but seems to cause problems
for OSX.

**Comment by hgibling** [comment]
Ok, I'll modify when I next update. Thanks.

**Comment by adamnovak** [comment]
I think I'm going to close this; "add configurable emoji" can be a separate issue.
