### ISSUE TITLE
rGFA graph construction with vg

### ISSUE THREAD

**Issue by gsc74** [vgteam/vg#3652]
Hi, with `vg construct` we can build directed acyclic `GFA` graphs, but can we also build `rGFA` graphs?

**Comment by glennhickey** [comment]
No, `vg` only supports writing a (rank-0) reference path as rGFA (`vg convert -P`), but there is currently no functionality for filling in the rank>0 insertion bubble tags.  Adding full rGFA export support is something I'm very interested in personally, but simply haven't had the time pursue.

**Comment by gsc74** [comment]
Thanks, So provided `.vg` graph and linear reference(`.fasta`) for `chr1` , how can i convert `vg` to `rGFA`. \
tried `vg convert chr1.vg -f -P chr1.fa > chr1.gfa` but got error; `error [vg convert]: specified path,  not found in graphchr1.fa` .
Is there something wrong in commands that i've used?

**Comment by glennhickey** [comment]
```
#path "x" from the input is written as a P-line by default:
vg construct -r test/tiny/tiny.fa -v test/tiny/tiny.vcf.gz | vg convert - -f

#use convert -P to transform it into rGFA tags
vg construct -r test/tiny/tiny.fa -v test/tiny/tiny.vcf.gz | vg convert - -fP x
```

**Comment by gsc74** [comment]
Thanks!

**Comment by gsc74** [comment]
> #path "x" from the input is written as a P-line by default:
> vg construct -r test/tiny/tiny.fa -v test/tiny/tiny.vcf.gz | vg convert - -f
> 
> #use convert -P to transform it into rGFA tags
> vg construct -r test/tiny/tiny.fa -v test/tiny/tiny.vcf.gz | vg convert - -fP x

Hi, I'm able to construct `rGFA` for `chr1` (`rank 0`) , however the `rGFA` constructed contains few segment lines (`S`) as same as `GFA`, for example;
```
S	297267	A	SN:Z:chr1	SO:i:241993276	SR:i:0
S	191878	T
```
Here segement line with vertex id: `297267` contains information as of `rGFA` but for vertex id: `191878` there is no such information, is it a bug?

**Comment by glennhickey** [comment]
You can indeed conclude that.  See also [this comment](https://github.com/vgteam/vg/issues/3652#issuecomment-1110954721).

**Comment by gsc74** [comment]
> You can indeed conclude that. See also [this comment](https://github.com/vgteam/vg/issues/3652#issuecomment-1110954721).

Thanks!
