### ISSUE TITLE
Question : graph annotation

### ISSUE THREAD

**Issue by alinehugo** [vgteam/vg#3667]
Good Morning , 

i want to know what's the best way to annotate pangenome graphs ?
as i've read in litterature, there is no proper way and we're only able to annotate a part of the graph in a traditionnel way (extract linaire sequence).

Do you have any recommendations please?
We have 2 graphs, one based on a reference genome fasta and we have its GFF file and the other based on non-model organisms alignement.
i want for exemple the know who much genes are in core/dispensible areas and such as pangenomic related questions

Best,
Aline

**Comment by jeizenga** [comment]
I think you are correct that the current state-of-the-art is to annotate the genomes individually. There are prototype annotation systems implemented in `vg annotate`, but they are far from mature.

There are tools that will help you lift annotations over from one genome to the others (Comparative Annotation Toolkit, liftOff), but they may not be very helpful if you are expecting significantly different gene contents between the genomes.
