### ISSUE TITLE
gam format

### ISSUE THREAD

**Issue by 8banzhuan** [vgteam/vg#3671]
Hi there, I'm looking for a complete description of the gam file format and of all the possible elements it can include, but I'm not finding nothing exhaustive. Does anyone know where can I find it?

**Comment by glennhickey** [comment]
the GAM format is specified [here](https://github.com/vgteam/libvgio/blob/master/deps/vg.proto#L111-L151)

**Comment by 8banzhuan** [comment]
Thank you！
