### ISSUE TITLE
Assessing mapping quality

### ISSUE THREAD

**Issue by lsoldini** [vgteam/vg#3672]
**1. What were you trying to do?**

Compare number of reads mapped from `vg mpmap` with number of reads mapped with `kallisto`.

**2. What did you want to happen?**

Know what is the number of "correctly" aligned and properly paired reads from my _.gamp_ files.

From the wiki, I thought that _.gamp_ to _.gam_ conversion would only retain the best alignment when a multipath alignement is provided :
"A GAMP can be converted to a GAM using vg view. Since a GAM can only align to a single path, the path through the multipath alignment graph that has the highest score is used (ties broken arbitrarily)". 

Then I thought of using `vg stats` on that _.gam_ file (as done #3614, but that was on `vg giraffe` output, so maybe I was wrong in wanting to do this that way).

**3. What actually happened?**

The number of aligned reads from `vg stats` is higher than the actual number of reads in the _.fastq_ file.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

No stacktrace, but the interpretation of the output is misleading (for me at least).

**5. What data and command can the vg dev team use to make the problem happen?**

I can share data by email or something else, but here are the command used for one of the 'problematic' sample:

```
vg view -K -G BrPP1_L3.gamp > BrPP1_L3.gam
vg stats -a BrPP1_L3.gam > BrPP1_L3.stats
```
The _BrPP1_L3.stats_ looks like this:
```
Total alignments: 25567874
Total primary: 25567874
Total secondary: 0
Total aligned: 25567872
Total perfect: 15963186
Total gapless (softclips allowed): 22353253
Total paired: 25565874
Total properly paired: 25120388
Insertions: 13636299 bp in 10328660 read events
Deletions: 16899751 bp in 11415102 read events
Substitutions: 40644313 bp in 40107401 read events
Softclips: 17282209 bp in 754298 read events
```
The total number of reads in that sample is 13'288'329, which is lower than the above values.

**6. What does running `vg version` say?**

```
vg version v1.39.0 "Runzi"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0 on Linux
```

**Comment by jeizenga** [comment]
That's off by a factor ~2. Maybe it's a reads vs. fragments issue? `vg stats` will count each read in a pair as a separate alignment.

**Comment by lsoldini** [comment]
Thanks for the reply :)

That would be great!  I think I will try mapping only with the first read of the pair and see if I get the expected number with `vg stats`. And maybe repeat the previous procedure over samples and verify it is never more than twice the number of reads. 

Also, I extracted paths (`vg paths -L -g` from the _.gbwt_ file) and then `vg surject` them to convert _.gamp_ to _.bam_. But then using `samtools flagstat` is not working. It should be possible to use classical samtools on the produced _.bam_ file or am I missing something?

**Comment by jeizenga** [comment]
The output of `vg surject` should be well-formed BAM. Was `samtools flagstat` crashing or just not giving you the output you expect?

**Comment by lsoldini** [comment]
Not crashing but giving this as output:
```
samtools flagstat test.bam
25567874 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (0.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by lsoldini** [comment]
Well, I am not sure what I am doing wrong with `vg surject`, but I'll close this since the `vg view is working`. (but if anyone see what is wrong I would be glad!)

**Comment by jeizenga** [comment]
That crash in `vg surject` looks like a bug to me. Is it possible to share the data so I can reproduce it? I would also expect that the "proper pair" and "mapped" fields would be filled out correctly, but I can look into that on your data.

**Comment by lsoldini** [comment]
Yes sure, I can send you one of the _.gamp_ file, with both the _.gbwt_ and _.xg_ of the spliced pangenome graph. Or would you want to start from the `vg mpmap` step ? Also, it is fine for me to share the data, but I'd rather do it by email.

**Comment by jeizenga** [comment]
The `vg mpmap` inputs are most important, but I might be able to do some troubleshooting with the .gamp file as well. You can email them to me at joeizeng@gmail.com.

**Comment by lsoldini** [comment]
I'll send you the `vg mpmap` input then, with one pair of _.fastq_.

**Comment by jeizenga** [comment]
This ended up taking quite a bit more coding than I expected, so I apologize for the delay. I believe I have something working now with this PR: https://github.com/vgteam/vg/pull/3706

I have successfully run `vg surject` on alignments of your reads to your graph. I do have a couple of suggestions though:
- It is not necessary to convert to GAM before running `vg surject`. GAMP input can be used with the `-m` flag (in fact, this usually has better performance).
- If you have used spliced alignment (`vg mpmap`'s default behavior) or are aligning to a spliced pangenome, you should also give the `-S` flag to `vg surject`, or else it will try to re-align to all of the introns, which can be very slow.

I hope that wraps up your issues, but let me know if I missed anything.

**Comment by lsoldini** [comment]
No problem for the delay, and thank you for working on this!

I'll then give it a try with the `-m` and `-s` flags and let you know if anything goes wrong.

**Comment by lsoldini** [comment]
Maybe it's best I write here actually (#3821). I was waiting on some fix related to `vg rna`, and then worked on other things, but I am still working with the same data described in this post. 

My questions are twofold:
1) I sent you the files because `vg surject` is asking for (seemingly) excessive amount of memory and run time. 
2) I used `vg view`, but I am not sure on how to interpret the output - example:
```
vg mpmap -x splicepangenome.xg -g splicepangenome.gcsa -d splicepangenome_50000.dist -n rna -l short -e low -f sample_R1.fastq.gz -f sampe_R2.fastq.gz > sample.gamp

Total alignments: 4492940
Total primary: 4492940
Total secondary: 0
Total aligned: 4455092
Total perfect: 2931963
Total gapless (softclips allowed): 4337905
Total paired: 4490940
Total properly paired: 4421976
Insertions: 195524 bp in 64101 read events
Deletions: 368071 bp in 70373 read events
Substitutions: 3835797 bp in 3706326 read events
Softclips: 6429065 bp in 231133 read events
```
I used `vg mpmap -x splicepangenome.xg -g splicepangenome.gcsa -d splicepangenome_50000.dist -n rna -l short -e low
-f sample_R1.fastq.gz -f sample_R2.fastq.gz > sample.gamp`.

In the above example, each input file (two per sample, R1 and R2) contained 2'049'278 reads. I am not sure on how to interprete it. Again, it's off by a factor ~2. I would understand a factor of two because this would count for fragments rather than reads, but here it is 2.192... and then I do not understand where those read can come from.

**Comment by jeizenga** [comment]
I'd assume that's due to secondary alignments. Since maybe ~6 months ago, `vg mpmap` produces up to 10 alignments by default, which can be controlled with the `-M` parameter. This seems to be the expected behavior for an RNA-seq mapper among geneticists who do RNA-seq analysis.

**Comment by jeizenga** [comment]
Okay, I think that it is in fact secondaries. I'm pretty the issue is that the conversion from GAMP -> GAM (probably using `vg view`?) annotates the secondary-ness of the mappings a little bit differently than `vg stats` expects it to be. I'll make a quick PR about this.

**Comment by lsoldini** [comment]
Thanks for such rapid answer! Looking forward to it. 
I am still wondering (but maybe this will be fixed by the PR you're thinking about), if there isn't something else going on, because the number of "Total perfect" mapping is higher than the total number of reads; wouldn't we expect that secondaries mapping cannot be perfect ? (I mean, if there are similar genes, I could see it that some share identical regions, but then the amount here (882'685) is around 50% of all reads, which seems quite excessive for such rather particular case).

**Comment by jeizenga** [comment]
The 2,931,963 perfect alignments are taken out of the 4,492,940 total alignments, which should include 4,098,556 primary alignments and 394,384 secondary alignments. I think you're interpreting the number of perfect alignments relative to the number of fragments instead of the number of reads. At most ~72% of primaries have a perfect mapping, let alone secondaries. However, it's perfectly possible to have both a read's primary and secondary alignments be perfect if the pangenome contains >1 sequence with perfect identity to the read.

**Comment by lsoldini** [comment]
Thanks for the PR. It's perfect, I do get the same results as you for secondary alignments, and the number of primary is exactly the double of the number of reads. This solves the `vg view` part. 

On the other hand, I was wondering about `vg surject`. I tried to give it as much memory as possible, but there is no way for me to make it run (consistently oom killed). Do you think it is due to the `pggb` origin of my _.gfa_ ? Is there anyway (other than changing graph software) to circumvent this ?

**Comment by jeizenga** [comment]
Sorry, I haven't gotten around to looking into it yet. I'll try to do it in the next couple of days. I think the`pggb`-based graph is a pretty likely culprit just on the grounds that we haven't seen this behavior in pangenomes generated by other graph-building pipelines. However, I'd ideally like to be able to support `pggb` graphs in `vg surject`, so my preferred solution is to modify `vg surject` rather than having you start over without `pggb`. It's hard for me to say how plausible that is without having looked into what's going wrong though.

**Comment by lsoldini** [comment]
Works fine for me, and I'd rather also not start over without `pggb`. No worries for the delay, I am working on other aspects in the meantime.

**Comment by lsoldini** [comment]
Hi Jordan, did you have the chance to go any further into this ?
I am also having problems when mapping reads with exceedingly long running times, which I was thinking may be related ? (more than 70-hours with 20 threads for 20 million reads).

**Comment by jeizenga** [comment]
Sorry, I have not yet. That definitely seems like too long. On a simple graph, you could probably do `surject` in a couple hours. Are you able to share the graph and alignments?

**Comment by jeizenga** [comment]
Hey, just wanted to bump this again to see if you can share the data that you ran into the problem on.

**Comment by lsoldini** [comment]
Sorry did not had time to come back to this. I'll send you by email the files required for vg surject and vg maman by the end of the week.

**Comment by lsoldini** [comment]
I just sent you an email with the _.gfa_ and _.xg_ graphs, the indexes (_.gcsa_, _.gsca.lp_, _.dist_), the two _.gff_, and one pair of _.fastq_ files (those that took too long with `vg mpmap`).

**Comment by lsoldini** [comment]
Hey, just wanted to know whether you had any time to look at this ?

**Comment by jeizenga** [comment]
I've started to, but I expect it's not going to be a quick fix. In my hands, the resource utilization of `vg mpmap` alone is prohibitive on this graph, which is not a particularly large graph. I think some of the more fundamental aspects of `vg mpmap` and `vg surject` might have to be rethought to be practically efficient on the more complicated graphs produced by PGGB, which makes this less of a bug fix and more of a research project.

**Comment by lsoldini** [comment]
Thanks for the quick reply and explanation. I understand the issue, and I am thus wondering about the timeline - are we speaking about few months, a year, more ? Although I would still be interested in using `pggb` with `vg`, I may have to consider switching to other graph pipeline in order to advance on this current project. Especially because I have two samples that I simply cannot run because of required resources.

**Comment by jeizenga** [comment]
I think months at least, but it's hard to say for sure. I have to balance my time with some other projects as well.

**Comment by lsoldini** [comment]
Would you suggest not using `vg rna` on `pggb` graph in the meantime? In other words, if I manage to get `vg mpmap` to finish by splitting the _.fastq_ files, would you trust the output ? Do you think the excessive running time is only about optimization or some other stuff may be going on ?

**Comment by jeizenga** [comment]
As far as I know, the alignments would be technically valid even on complicated graphs. It's just a matter of practical computation costs. If you have paired-end reads, then splitting the FASTQ can create subtle batch effects across the chunks due to slightly different estimates for the fragment length distribution. However, I would expect the differences to be minimal.

**Comment by lsoldini** [comment]
Ok, I'll will then go with that. Fortunately it is only two lanes of one replicate at out of hundreds that do not work. Thanks!
