### ISSUE TITLE
GAM format

### ISSUE THREAD

**Issue by 8banzhuan** [vgteam/vg#3674]
Hello, I want to find some examples about the gam file format, because I can't open the gam file, and there are garbled characters when I force it to open. Can you give an example to see what the content of the gam file is? I can also convert it into json format to view , but I still seem to know what the original format is like, thank you。
I'm a beginner and I don't know much about many places, thanks for your help

**Comment by jeizenga** [comment]
The GAM format is based on serialized Protobuf messages, which are non-human-readable binary files. If you want to manually inspect their contents, `vg view -aj` is probably the easiest way to do it (which I think you saw in https://github.com/vgteam/vg/issues/3675). The schema for the Protobuf objects is available here: 
https://github.com/vgteam/libvgio/blob/master/deps/vg.proto#L109-L151

**Comment by adamnovak** [comment]
Here's a description I wrote up of how the Protobuf-serialized `Alignment` objects are stored in the GAM file: https://github.com/vgteam/vg/wiki/File-Formats#vgs-protobuf-framing-format

**Comment by adamnovak** [comment]
And the documentation for how Protobuf serializes each `Alignment` object (or any object) to the byte strings we store in the GAM file is at https://developers.google.com/protocol-buffers/docs/encoding
