### ISSUE TITLE
vg surject loses pairing information

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#369]
Would be super handy to preserve this (and our eventual mapping qualities), to be able to see how other callers perform on vg alignments.

**Comment by ekg** [comment]
It is essential.

We are missing one thing and a decision about another thing.

We need a piece of code that provides the path relative alignment of any
other path in the graph. f(Path', Path'') --> Path. Right now we are
realigning the reads against the reference path, which is expensive.

Then we need to design a strategy for how to represent the parts of
alignments that leave the reference path. Should we describe the entire
allele or just a part of it? It may be important for the caller to see the
entire allele.

**Comment by ekg** [comment]
With the new translation interface it should be straightforward to do this.

**Comment by adamnovak** [comment]
We do actually bring through the paired end information now.

**Comment by adamnovak** [comment]
Actually, it looks like we don't bring this through. The mate fields of SAM are being filled, but reads are being recorded as their own mates. Maybe that's what the spec says to do for unpaired reads, but it's very wrong for paired reads.

**Comment by wheaton5** [comment]
So before I was getting all mapped reads to be flagged as proper pairs. Now none of them are being flagged as proper pairs.
