### ISSUE TITLE
giraffe with -o bam is slow

### ISSUE THREAD

**Issue by zhoudreames** [vgteam/vg#3694]
**1. What were you trying to do?**

we mapped the sort-reads(30Gb,10X) to graph pan-genome(2.7Gb) using giraffe with -o bam, it cost almost 16h. 
However, It only cost 1h when I mapped them with -o gam. Is there any faster way to get BAM? thanks~

```
vg giraffe -p -t $nproc --sample $ID -m $ref.min -d $ref.dist -Z $ref.giraffe.gbz  \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam
```

Place vg version output here
version v1.41.0 "Salmour"

**Comment by jltsiren** [comment]
Without knowing further details, I can imagine three possible explanations:

1. Projecting the alignments to a linear reference is slow with (this particular?) GBZ graph. You can try converting the graph to XG format with `vg convert -x graph.gbz > graph.xg` and passing the XG graph to Giraffe with option `-x graph.xg`. Giraffe will then use the GBZ graph for alignment and the XG graph for projecting the alignments to the reference.
2. You have too many generic / reference paths in the GBZ graph. Once you have converted the graph to XG format, you can list the paths with `vg paths -L -x graph.xg`. There should be one path for each chromosome / major contig in the reference. If there are substantially more paths, and especially if they look like they overlap in the graph, this is probably the reason. The solution then depends on how those paths got into the graph in the first place.
3. The graph itself is problematic in some way. This would require further investigation, and the eventual solution would probably be building an easier graph without the problematic features.

**Comment by zhoudreames** [comment]
> 

thank you for your reply, I follow your recommendations step by step. First, I want to try the first method, can I use blow code to run giraffe after I convert the graph.gbz to the graph.xg ?
```
vg giraffe -p -t $nproc --sample $ID -m $ref.min -d $ref.dist -x $ref.xg \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam
```

**Comment by jltsiren** [comment]
You must also include `-Z $ref.giraffe.gbz`, as the haplotype paths Giraffe aligns to are in the GBZ graph.

**Comment by zhoudreames** [comment]
> You must also include `-Z $ref.giraffe.gbz`, as the haplotype paths Giraffe aligns to are in the GBZ graph.

thanks for your help,  I try it right now

**Comment by zhoudreames** [comment]
I know it, thanks~

**Comment by zhoudreames** [comment]
> 

Hi, I used your first method to resolve this problem, the runtime is faster, but the output bam files are strange.
```
#without -x $ref.xg
vg giraffe -p -t $nproc --sample $ID -m $ref.min -d $ref.dist -Z $ref.giraffe.gbz  \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam

the bam files are only including reference sequence:
![image](https://user-images.githubusercontent.com/54714639/176809866-8b8e59d9-b364-44c2-a746-cc4644f36304.png)

#with  -x $ref.xg
vg giraffe -p -t $nproc --sample $ID -m $ref.min -d $ref.dist -x $ref.xg \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam

the bam files added many path_cover sequence
![image](https://user-images.githubusercontent.com/54714639/176810740-085a575b-3991-4e22-a2f6-14f2615f98bc.png)

the $ref.xg path:
chr1
chr13
chr6
chr14
chr15
chr2
chr3
chr9
chr8
chr4
chr7
chrX
chr5
chr10
chr16
chr17
chr11
chr12
chr18
chrY
chrMT
path_cover_0#0#chr1#0
path_cover_1#0#chr1#0
path_cover_2#0#chr1#0
path_cover_3#0#chr1#0
path_cover_4#0#chr1#0
path_cover_5#0#chr1#0
path_cover_6#0#chr1#0
path_cover_7#0#chr1#0
path_cover_8#0#chr1#0
path_cover_9#0#chr1#0
path_cover_10#0#chr1#0
path_cover_11#0#chr1#0
path_cover_12#0#chr1#0
path_cover_13#0#chr1#0
path_cover_14#0#chr1#0
path_cover_15#0#chr1#0
path_cover_0#0#chr13#0
path_cover_1#0#chr13#0
path_cover_2#0#chr13#0
path_cover_3#0#chr13#0
path_cover_4#0#chr13#0
path_cover_5#0#chr13#0
path_cover_6#0#chr13#0
path_cover_7#0#chr13#0
path_cover_8#0#chr13#0
path_cover_9#0#chr13#0
path_cover_10#0#chr13#0
path_cover_11#0#chr13#0
path_cover_12#0#chr13#0
path_cover_13#0#chr13#0
path_cover_14#0#chr13#0
path_cover_15#0#chr13#0
path_cover_0#0#chr6#0
path_cover_1#0#chr6#0
path_cover_2#0#chr6#0
path_cover_3#0#chr6#0
path_cover_4#0#chr6#0
path_cover_5#0#chr6#0
path_cover_6#0#chr6#0
path_cover_7#0#chr6#0
path_cover_8#0#chr6#0
path_cover_9#0#chr6#0
path_cover_10#0#chr6#0
path_cover_11#0#chr6#0
path_cover_12#0#chr6#0
path_cover_13#0#chr6#0
path_cover_14#0#chr6#0
path_cover_15#0#chr6#0
path_cover_0#0#chr14#0
path_cover_1#0#chr14#0
path_cover_2#0#chr14#0
path_cover_3#0#chr14#0
path_cover_4#0#chr14#0
path_cover_5#0#chr14#0
path_cover_6#0#chr14#0
path_cover_7#0#chr14#0
path_cover_8#0#chr14#0
path_cover_9#0#chr14#0
path_cover_10#0#chr14#0
path_cover_11#0#chr14#0
path_cover_12#0#chr14#0
path_cover_13#0#chr14#0
path_cover_14#0#chr14#0
path_cover_15#0#chr14#0
path_cover_0#0#chr15#0
path_cover_1#0#chr15#0
path_cover_2#0#chr15#0
path_cover_3#0#chr15#0
path_cover_4#0#chr15#0
path_cover_5#0#chr15#0
path_cover_6#0#chr15#0
path_cover_7#0#chr15#0
path_cover_8#0#chr15#0
path_cover_9#0#chr15#0
path_cover_10#0#chr15#0
path_cover_11#0#chr15#0
path_cover_12#0#chr15#0
path_cover_13#0#chr15#0
path_cover_14#0#chr15#0
path_cover_15#0#chr15#0
path_cover_0#0#chr2#0
path_cover_1#0#chr2#0
path_cover_2#0#chr2#0
path_cover_3#0#chr2#0
path_cover_4#0#chr2#0
path_cover_5#0#chr2#0
path_cover_6#0#chr2#0
path_cover_7#0#chr2#0
path_cover_8#0#chr2#0
path_cover_9#0#chr2#0
path_cover_10#0#chr2#0
path_cover_11#0#chr2#0
path_cover_12#0#chr2#0
path_cover_13#0#chr2#0
path_cover_14#0#chr2#0
path_cover_15#0#chr2#0
path_cover_0#0#chr3#0
path_cover_1#0#chr3#0
path_cover_2#0#chr3#0
path_cover_3#0#chr3#0
path_cover_4#0#chr3#0
path_cover_5#0#chr3#0
path_cover_6#0#chr3#0
path_cover_7#0#chr3#0
path_cover_8#0#chr3#0
path_cover_9#0#chr3#0
path_cover_10#0#chr3#0
path_cover_11#0#chr3#0
path_cover_12#0#chr3#0
path_cover_13#0#chr3#0
path_cover_14#0#chr3#0
path_cover_15#0#chr3#0
path_cover_0#0#chr9#0
path_cover_1#0#chr9#0
path_cover_2#0#chr9#0
path_cover_3#0#chr9#0
path_cover_4#0#chr9#0
path_cover_5#0#chr9#0
path_cover_6#0#chr9#0
path_cover_7#0#chr9#0
path_cover_8#0#chr9#0
path_cover_9#0#chr9#0
path_cover_10#0#chr9#0
path_cover_11#0#chr9#0
path_cover_12#0#chr9#0
path_cover_13#0#chr9#0
path_cover_14#0#chr9#0
path_cover_15#0#chr9#0
path_cover_0#0#chr8#0
path_cover_1#0#chr8#0
path_cover_2#0#chr8#0
path_cover_3#0#chr8#0
path_cover_4#0#chr8#0
path_cover_5#0#chr8#0
path_cover_6#0#chr8#0
path_cover_7#0#chr8#0
path_cover_8#0#chr8#0
path_cover_9#0#chr8#0
path_cover_10#0#chr8#0
path_cover_11#0#chr8#0
path_cover_12#0#chr8#0
path_cover_13#0#chr8#0
path_cover_14#0#chr8#0
path_cover_15#0#chr8#0
path_cover_0#0#chr4#0
path_cover_1#0#chr4#0
path_cover_2#0#chr4#0
path_cover_3#0#chr4#0
path_cover_4#0#chr4#0
path_cover_5#0#chr4#0
path_cover_6#0#chr4#0
path_cover_7#0#chr4#0
path_cover_8#0#chr4#0
path_cover_9#0#chr4#0
path_cover_10#0#chr4#0
path_cover_11#0#chr4#0
path_cover_12#0#chr4#0
path_cover_13#0#chr4#0
path_cover_14#0#chr4#0
path_cover_15#0#chr4#0
path_cover_0#0#chr7#0
path_cover_1#0#chr7#0
path_cover_2#0#chr7#0
path_cover_3#0#chr7#0
path_cover_4#0#chr7#0
path_cover_5#0#chr7#0
path_cover_6#0#chr7#0
path_cover_7#0#chr7#0
path_cover_8#0#chr7#0
path_cover_9#0#chr7#0
path_cover_10#0#chr7#0
path_cover_11#0#chr7#0
path_cover_12#0#chr7#0
path_cover_13#0#chr7#0
path_cover_14#0#chr7#0
path_cover_15#0#chr7#0
path_cover_0#0#chrX#0
path_cover_1#0#chrX#0
path_cover_2#0#chrX#0
path_cover_3#0#chrX#0
path_cover_4#0#chrX#0
path_cover_5#0#chrX#0
path_cover_6#0#chrX#0
path_cover_7#0#chrX#0
path_cover_8#0#chrX#0
path_cover_9#0#chrX#0
path_cover_10#0#chrX#0
path_cover_11#0#chrX#0
path_cover_12#0#chrX#0
path_cover_13#0#chrX#0
path_cover_14#0#chrX#0
path_cover_15#0#chrX#0
path_cover_0#0#chr5#0
path_cover_1#0#chr5#0
path_cover_2#0#chr5#0
path_cover_3#0#chr5#0
path_cover_4#0#chr5#0
path_cover_5#0#chr5#0
path_cover_6#0#chr5#0
path_cover_7#0#chr5#0
path_cover_8#0#chr5#0
path_cover_9#0#chr5#0
path_cover_10#0#chr5#0
path_cover_11#0#chr5#0
path_cover_12#0#chr5#0
path_cover_13#0#chr5#0
path_cover_14#0#chr5#0
path_cover_15#0#chr5#0
path_cover_0#0#chr10#0
path_cover_1#0#chr10#0
path_cover_2#0#chr10#0
path_cover_3#0#chr10#0
path_cover_4#0#chr10#0
path_cover_5#0#chr10#0
path_cover_6#0#chr10#0
path_cover_7#0#chr10#0
path_cover_8#0#chr10#0
path_cover_9#0#chr10#0
path_cover_10#0#chr10#0
path_cover_11#0#chr10#0
path_cover_12#0#chr10#0
path_cover_13#0#chr10#0
path_cover_14#0#chr10#0
path_cover_15#0#chr10#0
path_cover_0#0#chr16#0
path_cover_1#0#chr16#0
path_cover_2#0#chr16#0
path_cover_3#0#chr16#0
path_cover_4#0#chr16#0
path_cover_5#0#chr16#0
path_cover_6#0#chr16#0
path_cover_7#0#chr16#0
path_cover_8#0#chr16#0
path_cover_9#0#chr16#0
path_cover_10#0#chr16#0
path_cover_11#0#chr16#0
path_cover_12#0#chr16#0
path_cover_13#0#chr16#0
path_cover_14#0#chr16#0
path_cover_15#0#chr16#0
path_cover_0#0#chr17#0
path_cover_1#0#chr17#0
path_cover_2#0#chr17#0
path_cover_3#0#chr17#0
path_cover_4#0#chr17#0
path_cover_5#0#chr17#0
path_cover_6#0#chr17#0
path_cover_7#0#chr17#0
path_cover_8#0#chr17#0
path_cover_9#0#chr17#0
path_cover_10#0#chr17#0
path_cover_11#0#chr17#0
path_cover_12#0#chr17#0
path_cover_13#0#chr17#0
path_cover_14#0#chr17#0
path_cover_15#0#chr17#0
path_cover_0#0#chr11#0
path_cover_1#0#chr11#0
path_cover_2#0#chr11#0
path_cover_3#0#chr11#0
path_cover_4#0#chr11#0
path_cover_5#0#chr11#0
path_cover_6#0#chr11#0
path_cover_7#0#chr11#0
path_cover_8#0#chr11#0
path_cover_9#0#chr11#0
path_cover_10#0#chr11#0
path_cover_11#0#chr11#0
path_cover_12#0#chr11#0
path_cover_13#0#chr11#0
path_cover_14#0#chr11#0
path_cover_15#0#chr11#0
path_cover_0#0#chr12#0
path_cover_1#0#chr12#0
path_cover_2#0#chr12#0
path_cover_3#0#chr12#0
path_cover_4#0#chr12#0
path_cover_5#0#chr12#0
path_cover_6#0#chr12#0
path_cover_7#0#chr12#0
path_cover_8#0#chr12#0
path_cover_9#0#chr12#0
path_cover_10#0#chr12#0
path_cover_11#0#chr12#0
path_cover_12#0#chr12#0
path_cover_13#0#chr12#0
path_cover_14#0#chr12#0
path_cover_15#0#chr12#0
path_cover_0#0#chr18#0
path_cover_1#0#chr18#0
path_cover_2#0#chr18#0
path_cover_3#0#chr18#0
path_cover_4#0#chr18#0
path_cover_5#0#chr18#0
path_cover_6#0#chr18#0
path_cover_7#0#chr18#0
path_cover_8#0#chr18#0
path_cover_9#0#chr18#0
path_cover_10#0#chr18#0
path_cover_11#0#chr18#0
path_cover_12#0#chr18#0
path_cover_13#0#chr18#0
path_cover_14#0#chr18#0
path_cover_15#0#chr18#0
path_cover_0#0#chrY#0
path_cover_1#0#chrY#0
path_cover_2#0#chrY#0
path_cover_3#0#chrY#0
path_cover_4#0#chrY#0
path_cover_5#0#chrY#0
path_cover_6#0#chrY#0
path_cover_7#0#chrY#0
path_cover_8#0#chrY#0
path_cover_9#0#chrY#0
path_cover_10#0#chrY#0
path_cover_11#0#chrY#0
path_cover_12#0#chrY#0
path_cover_13#0#chrY#0
path_cover_14#0#chrY#0
path_cover_15#0#chrY#0
path_cover_0#0#chrMT#0
path_cover_1#0#chrMT#0
path_cover_2#0#chrMT#0
path_cover_3#0#chrMT#0
path_cover_4#0#chrMT#0
path_cover_5#0#chrMT#0
path_cover_6#0#chrMT#0
path_cover_7#0#chrMT#0
path_cover_8#0#chrMT#0
path_cover_9#0#chrMT#0
path_cover_10#0#chrMT#0
path_cover_11#0#chrMT#0
path_cover_12#0#chrMT#0
path_cover_13#0#chrMT#0
path_cover_14#0#chrMT#0
path_cover_15#0#chrMT#0


```

**Comment by zhoudreames** [comment]
@jltsiren I am so sorry to disturb you, can you help me? thanks~

**Comment by jltsiren** [comment]
@adamnovak Here is an unfortunate side effect of path senses. If you convert GBZ to XG, haplotype paths wil also be included in the XG graph. Surjecting with the XG seems to be much faster than with the GBZ, but vg seems to be surjecting the alignments to both the reference and the haplotypes.

@zhoudreames Are you sure this command line is correct:
```
#with  -x $ref.xg(cost 2h)
vg giraffe -p -t $nproc --sample $ID -m $ref.min -d $ref.dist -x $ref.xg \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam
```
I'm surprised that didn't crash, because you didn't use the GBZ graph with `-Z $ref.giraffe.gbz`. You must use the XG in addition to the GBZ, because otherwise Giraffe will create another GBZ graph from the XG, and that could be different from the one used for building the minimizer index.

**Comment by zhoudreames** [comment]
> 

I am so sorry, this code is an error, I corrected it:
```
#with  -x $ref.xg(cost 2h)
vg giraffe -p -t $nproc --sample $ID -Z $ref.giraffe.gbz -m $ref.min -d $ref.dist -x $ref.xg \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam
```

**Comment by zhoudreames** [comment]
In order to make it convenient for you to find errors, I showed my whole process：
```
# construct  and index
vcf=graph.vcf.gz
ref=genome.fa
for i in {1..18} X Y
do
	{
	 bcftools view $vcf chr$i -Oz >chr${i}.vcf.gz
	 tabix -f  chr${i}.vcf.gz
	}&
done
VCF_ARGS=()
for CHROM in {1..18} X Y ; do
    VCF_ARGS+=(-v chr${CHROM}.vcf.gz)
done
vg autoindex --workflow giraffe -r $ref "${VCF_ARGS[@]}" -p ${ref%%.fa}


# covert gbz to xg
vg convert -x graph.gbz > graph.xg


#align pair-end reads to graph with giraffe
vg giraffe -p -t $nproc --sample $ID -Z $ref.giraffe.gbz -m $ref.min -d $ref.dist -x $ref.xg \
-f $fq1 -f $fq2 -o bam > $ID.raw.bam

**Comment by adamnovak** [comment]
It looks like the reason we end up surjecting onto haplotypes when they are in the XG is that [`get_sequence_dictionary()`](https://github.com/vgteam/vg/blob/e35370d5732b25340ea3f35e3b87143f6b4f2c82/src/hts_alignment_emitter.cpp#L119) doesn't yet know about path metadata, and just gives you a default dictionary of every path it can find. Since the XG just stores all paths the same and doesn't elide haplotypes from `for_each_path_handle()`, and since `get_sequence_dictionary()` isn't filtering, we end up surjecting into the haplotype paths as well.

The workaround is to use your own sequence dictionary: grab all the `@SQ` lines for the paths you actually want, or even just their names, put them in a file, and pass that to `vg giraffe` with the `--ref-paths` option. Then it will only surject into those paths.

Another workaround is to not use `vg convert` to convert the GBZ and all its haplotype paths to an XG, but to get a graph that is just the GBZ and the reference paths, and then make that an XG. We don't quite have a way to select haplotype paths as such yet, but these al start with `path_cover_`, so you could drop them by prefix: 

```
vg paths -x graph.gbz --drop-paths --paths-by "path_cover_" > graph.nohaps.vg
vg convert -x graph.nohaps.vg > graph.nohaps.xg
```

The other question is why surjeting from the XG is ten times faster than doing it form GBZ. I'm not sure why that would be; we might have to do some profiling to find out.

**Comment by zhoudreames** [comment]
> It looks like the reason we end up surjecting onto haplotypes when they are in the XG is that [`get_sequence_dictionary()`](https://github.com/vgteam/vg/blob/e35370d5732b25340ea3f35e3b87143f6b4f2c82/src/hts_alignment_emitter.cpp#L119) doesn't yet know about path metadata, and just gives you a default dictionary of every path it can find. Since the XG just stores all paths the same and doesn't elide haplotypes from `for_each_path_handle()`, and since `get_sequence_dictionary()` isn't filtering, we end up surjecting into the haplotype paths as well.
> 
> The workaround is to use your own sequence dictionary: grab all the `@SQ` lines for the paths you actually want, or even just their names, put them in a file, and pass that to `vg giraffe` with the `--ref-paths` option. Then it will only surject into those paths.
> 
> Another workaround is to not use `vg convert` to convert the GBZ and all its haplotype paths to an XG, but to get a graph that is just the GBZ and the reference paths, and then make that an XG. We don't quite have a way to select haplotype paths as such yet, but these al start with `path_cover_`, so you could drop them by prefix:
> 
> ```
> vg paths -x graph.gbz --drop-paths --paths-by "path_cover_" > graph.nohaps.vg
> vg convert -x graph.nohaps.vg > graph.nohaps.xg
> ```
> 
> The other question is why surjeting from the XG is ten times faster than doing it form GBZ. I'm not sure why that would be; we might have to do some profiling to find out.

thanks, following your method, I resolved it with the --ref-paths option.  In addition,  I have a problem:
Is there any difference between the BAM files obtained by linear genome + BWA mapper and graph pan-genome + giraffe mapper? I see that the results of these two BAM files use linear genome as a reference or header. Will the BAM files obtained by graph pan-genome+ giraffe mapper be helpful for later call SV ？

**Comment by netwon123** [comment]
> > It looks like the reason we end up surjecting onto haplotypes when they are in the XG is that [`get_sequence_dictionary()`](https://github.com/vgteam/vg/blob/e35370d5732b25340ea3f35e3b87143f6b4f2c82/src/hts_alignment_emitter.cpp#L119) doesn't yet know about path metadata, and just gives you a default dictionary of every path it can find. Since the XG just stores all paths the same and doesn't elide haplotypes from `for_each_path_handle()`, and since `get_sequence_dictionary()` isn't filtering, we end up surjecting into the haplotype paths as well.
> > The workaround is to use your own sequence dictionary: grab all the `@SQ` lines for the paths you actually want, or even just their names, put them in a file, and pass that to `vg giraffe` with the `--ref-paths` option. Then it will only surject into those paths.
> > Another workaround is to not use `vg convert` to convert the GBZ and all its haplotype paths to an XG, but to get a graph that is just the GBZ and the reference paths, and then make that an XG. We don't quite have a way to select haplotype paths as such yet, but these al start with `path_cover_`, so you could drop them by prefix:
> > ```
> > vg paths -x graph.gbz --drop-paths --paths-by "path_cover_" > graph.nohaps.vg
> > vg convert -x graph.nohaps.vg > graph.nohaps.xg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The other question is why surjeting from the XG is ten times faster than doing it form GBZ. I'm not sure why that would be; we might have to do some profiling to find out.
> 
> thanks, following your method, I resolved it with the --ref-paths option. In addition, I have a problem: Is there any difference between the BAM files obtained by linear genome + BWA mapper and graph pan-genome + giraffe mapper? I see that the results of these two BAM files use linear genome as a reference or header. Will the BAM files obtained by graph pan-genome+ giraffe mapper be helpful for later call SV ？

Should i use 'vg convert -H' ?

**Comment by adamnovak** [comment]
> Is there any difference between the BAM files obtained by linear genome + BWA mapper and graph pan-genome + giraffe mapper?

They are essentially interchangeable, but we have published results showing that the Giraffe BAM can get better variant calls, since the pangenome information was used to inform the read mapping process.

> Should i use 'vg convert -H' ?

You probably can use that to do both those commands in one step. I forgot that that was available.
