### ISSUE TITLE
how to updata graph genome with graph's vcf files

### ISSUE THREAD

**Issue by zhoudreames** [vgteam/vg#3695]
**1. What were you trying to do?**
we first used 8 haplotypes assemblies to construct the original graph genome, then I want to add more variants from additional 500 Illumina short-reads samples to the original graph genome. the calling process for 500 samples is shown in below
```
# Align with giraffe
vg giraffe -p -t $nproc --sample $ID -m $ref.min -d $ref.dist -Z $ref.giraffe.gbz  \
-f $fq1 -f $fq2  > $ID.raw.gam

# Chunk the graph
$> vg chunk -M -x $ref.giraffe.gbz  -O pg

# Get the snarls
$> vg snarls chunk_1_aug.pg > chunk_1_aug.snarls

# Augment
$> vg augment $ID.raw.gam -s -m 2 -q 5 -Q 5 -A chunk_1_aug.gam > chunk_1_aug.pg

# Pack
$> vg pack -x chunk_1_aug.pg -g chunk_1_aug.gam -o chunk_1_aug.pack

# Call
$> vg call chunk_1_aug.pg -r chunk_1_aug.snarls -k chunk_1_aug.pack -s $ID >$ID.1.vcf
```
How to integrate these more VCF files into the original graph genome ？the vg construct is only for input FASTA reference,can i add the variant with graph genome?

Place vg version output here
version v1.41.0 "Salmour"

**Comment by caixu0518** [comment]
Hi, can you tell me how to construct the original graph genome from your eigth assemblies. I have 20 assemblies, but i dont know how to generate a non-redundant vcf file.

**Comment by ekg** [comment]
If you have assemblies you can use the pggb or minigraph-cactus processes.

If not, you'll want to use vg add to put alleles into the existing graph.
