### ISSUE TITLE
vg mpmap parameter for strand specifity

### ISSUE THREAD

**Issue by lsoldini** [vgteam/vg#3698]
While `rpvg` takes a parameter for strand-specificity of RNA-seq reads, there is no such parameter for `vg mpmap`. Hence, I was wondering whether `vg mpmap` has anyway of considering strand-specificity ? (I have stranded RNA-seq reads (R1 = reverse, R2 = forward), and I would like to use that information)

**Comment by jeizenga** [comment]
Currently, no, there is not. I think this feature would actually be pretty difficult to implement. Right now, `vg mpmap` makes minimal use of transcript annotations, so the infrastructure isn't implemented to propagate information about the transcripts' strands. One exception might be spliced alignment (over unannotated splice junctions), where I could pretty easily enforce that the splice motifs be in a particular orientation. 

That said, I think this would probably make a difference in a small fraction of the reads. My intuition is that it should be very, very unlikely that a read maps to the forward strand of one transcript and the reverse strand of another, which is the only situation I can think of where strandedness would resolve mapping ambiguity. One exception might be if the transcript is the result of evolutionary processes started from the antisense strand of another transcript. I know of one such case in mouse, but I don't think it's a widespread evolutionary phenomenon.

**Comment by lsoldini** [comment]
Oh okay, I see. Maybe I am confusing things, but from my understanding, having the information on strand-specificity is quite important to properly assign reads when you have two genes that are overlapping but on different strands - e.g., [this](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-1876-7). I am not sure this is quite rare, e.g. [this](https://www.nature.com/articles/s41576-021-00417-w) (although, this one is quite recent). 

Also, in the first place, I was wondering why `rpvg` was considering strand-specificity although the software producing its input does not - i.e., does ´rpvg´ retrieve such information from the _.gamp_ files ? 

In particular, if I started wondering about this it's because I have much different results when defining the `-e` parameter in `rpvg` - e.g., with `unstranded`, I have the highest sum of counts, but with one of the two strand specificity, I almost getting nothing (surprisingly, the sum of total read counts obtained with `-e rf` summed to the one obtained with `-e fr` is equal to the sum obtained with `-e unstranded`, which seems odd). 

My apologies for insisting, I am just trying to figure out how to make the best use of both my data and the great ´vg | rpvg´ pipeline :)

**Comment by jeizenga** [comment]
Ah, I see what you're getting at. In those cases, the strand is important, but not at the mapping step. The process of assigning aligned reads to particular transcripts happens in the downstream inference (such as `rpvg`). For mapping, we can be agnostic about which of the two we are aligning to, because they would result in the same alignment.

**Comment by lsoldini** [comment]
Yes, now that I read it that way, it makes complete sense! Thanks :)
