### ISSUE TITLE
How to generate a nonreduant vcf file from multiple assemblies?

### ISSUE THREAD

**Issue by caixu0518** [vgteam/vg#3707]
Hello vg team,

I have 20 assemblies and a population-scale resequencing data. I want to follow your wonderfull vg Giraffe pipeline to genotype all candidate SVs （INS， DEL， INV）in my large resequencing population. 

However, it make me confuse how to get a nonreduant vcf file (including INS， DEL， INV) from aligments of multiple assemblies. I have tried SyRI pipeline, but the final VCF is not accepted by the vg  Giraffe pipeline. Is there any pipelines to generate the nonreduant vcf ?

I will appreciate any comments on this issue.

Best,
Xu

**Comment by glennhickey** [comment]
Your best bet is to make a graph directly from assemblies.  You could try https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md, following the HPRC instructions.  The results work well with Giraffe and Pangenie: https://www.biorxiv.org/content/10.1101/2022.07.09.499321v1
