### ISSUE TITLE
vg can't surject pair of unmapped GAF reads

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#3711]
An unmapped read pair
`cat up.gaf`:
```
SRR835033.100738	95	*	*	*	*	*	*	*	*	*	0
SRR835033.100738	95	*	*	*	*	*	*	*	*	*	0
```

Surjects fine unless I use `-i`
```
vg construct -r tiny/tiny.fa > tiny.vg
#works
vg surject -x tiny.vg up.gaf -G -s > tiny.up.sam
#doesn't work
vg surject -x tiny.vg up.gaf -G -s -i > tiny.up.sam
```
```
[vg surject] error: alignments SRR835033.100738 and SRR835033.100738 are adjacent but not paired
```
If both of the reads are mapped, then it works fine with `-i` (if just one mapped, then the same error happens)

**Comment by jeizenga** [comment]
I imagine this is probably actually a bug in libvgio:

https://github.com/vgteam/libvgio/blob/6a8b7fa6f8f848c587536cd6e501eb7bc81b2c1d/include/vg/io/alignment_io.hpp#L60-L73

**Comment by glennhickey** [comment]
Huh, I thought this sounded familiar.  Thanks for fixing, @jmonlong, I now remember how annoying this issue was.
