### ISSUE TITLE
superbubble detection failure near doubly-reversing edges

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#377]
In this graph there appear to be several superbubbles that are not detected by our superbubble detection method:

![image](https://cloud.githubusercontent.com/assets/145425/16035455/27b6f6d2-3252-11e6-8082-407553c24d53.png)

```text
H       VN:Z:1.0
S       78      TGA
L       78      +       79      +       0M
S       79      T
L       79      +       80      +       0M
L       79      +       81      +       0M
S       80      A
L       80      +       299     +       0M
S       81      G
L       81      +       299     +       0M
S       83      C
L       83      +       301     +       0M
S       84      G
L       84      +       301     +       0M
S       297     AT
L       297     +       298     +       0M
S       298     GCTTG
L       298     +       78      +       0M
S       299     A
S       300     AGCT
L       300     -       513     -       0M
L       300     +       83      +       0M
L       300     +       84      +       0M
S       301     AGGG
L       301     +       303     +       0M
S       303     AA
S       513     TGA
L       513     -       299     -       0M
```

To reproduce:

```
-> % cat missed_bubble.gfa | vg view -Fv - | vg stats -b - 
78      79      78,79,
297     298     297,298,
298     78      298,78,
300     301     300,83,84,301,
301     303     301,303,
```

We expect to see a record like:

```
79     299     79,80,81,299,
```

Closer inspection showed that the undetected bubble was near a pair of doubly-reversed edges.

I added an option to `vg mod` that let's us apply `flip_doubly_reversed_edges` to the graph, and this demonstrates that this was the problem.

```
-> % cat missed_bubble.gfa | vg view -Fv - | vg mod -E - | vg stats -b -
78      79      78,79,
79      299     79,80,81,299,
297     298     297,298,
298     78      298,78,
299     513     299,513,
300     301     300,83,84,301,
301     303     301,303,
513     300     513,300,
```

This is getting pushed onto the "genotypes" branch where we are all hacking away.

I'll update the superbubble detection stuff to first flip doubly reversing edges and then dagify/sort or whatnot.

**Comment by ekg** [comment]
Presumably there is a problem in `VG::sort` when handling the doubly reversed edges.

**Comment by ekg** [comment]
This failure occurs because the superbubble interface interprets the doubly reversed edges like this:

![image](https://cloud.githubusercontent.com/assets/145425/16036479/273ebe10-3257-11e6-8ab1-25747ce60020.png)

**Comment by edawson** [comment]
Ah, I'm pretty sure the doubly-reversed edges would violate the entrance/exit conditions of super bubbles. Flipping them should remedy it.

**Comment by ekg** [comment]
It's pushed onto the genotype branch.

**Comment by ekg** [comment]
We can now visualize very complex alignment graphs without the graphviz artifacts that we had before:

![image](https://cloud.githubusercontent.com/assets/145425/16036912/01b7aab0-3259-11e6-8156-e2c3f3e2c202.png)

Nodes would be pulled around.

This is thanks to linear time superbubble detection!

**Comment by ekg** [comment]
I'm doing this with `vg view -dBp`. The `-B` says to give graphviz hints using the superbubbles. Cool stuff!

We are also using the superbubbles in a genotyper in the genotype branch. @adamnovak has it making "VCF" now.

**Comment by ekg** [comment]
This is how the rendering looked before:

![image](https://cloud.githubusercontent.com/assets/145425/16037091/e6904afc-3259-11e6-9d9d-17bdde754766.png)

What a mess.
