### ISSUE TITLE
Wrong Chromosome ID in the BAM file converted from GAM file by surject

### ISSUE THREAD

**Issue by Sunhh** [vgteam/vg#3777]
**1. What were you trying to do?**
I want to call SNPs using GATK based on graph-based pangenome alignments.

**2. What did you want to happen?**
After constructing the graph, I aligned the reads and converted the GAM file into BAM file for GATK. I expect the GATK can call SNPs more accurately than using BWA alignments.

**3. What actually happened?**
I did both graph-based alignments and BWA alignments, and found that there were nearly no SNPs called in CannZSG_Chr02, and the ~ 623 k SNPs called from BWA alignments were genotyped as missing ("./.") by graph-based alignments. After checking the BAM file converted by "vg surject", I found that the reads aligned to CannZSG_Chr02 should be assigned to ZSG_Chr03 with exactly the same position, which was also true for CannZSG_Chr03, while reads in CannZSG_Chr01 were good.

**5. What data and command can the vg dev team use to make the problem happen?**

My commands to get the GAM file and BAM file are as the following:

```
vg autoindex -T temp/ --workflow giraffe --prefix pg_vg/m6a --ref-fasta ZSG.chr.fa --vcf m6a.4gir.vcf.gz
vg giraffe -t 50 -Z pg_vg/m6a.giraffe.gbz -m pg_vg/m6a.min -d pg_vg/m6a.dist -f s1.R1P.fq -f s1.R2P.fq > s1.gam
vg surject  -N s1 -R s1 -t 100 -x pg_vg/m6a.giraffe.gbz -b -i s1.gam > s1.gam.bam
samtools  sort -@ 20 -o s1.gam_srt.bam s1.gam.bam
samtools index s1.gam_srt.bam
```

And the chromosomes are like the following:

```
##contig=<ID=CannZSG_Chr01,length=332615375>
##contig=<ID=CannZSG_Chr02,length=177319215>
##contig=<ID=CannZSG_Chr03,length=289790774>
##contig=<ID=CannZSG_Chr04,length=248932513>
##contig=<ID=CannZSG_Chr05,length=254874144>
##contig=<ID=CannZSG_Chr06,length=253233553>
##contig=<ID=CannZSG_Chr07,length=266382521>
##contig=<ID=CannZSG_Chr08,length=174326481>
##contig=<ID=CannZSG_Chr09,length=278410012>
##contig=<ID=CannZSG_Contig01,length=17280>
##contig=<ID=CannZSG_Contig02,length=14241>
```

**6. What does running `vg version` say?**

```
vg version v1.40.0-88-g04775076b "Suardi"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by Sunhh@swift
```

**Comment by Sunhh** [comment]
Sorry, I found it was not caused by vg surject. I'll close this.

**Comment by netwon123** [comment]
Sorry sir~ I also meet this problem. I found the performance of vg surject+gatk was not better than bwa+gatk. Could you solve this problem?
