### ISSUE TITLE
vg index memory

### ISSUE THREAD

**Issue by wjq1981** [vgteam/vg#3779]
hi, when I use 'vg index -t 32 -p -x vsyl.genome.xg -g vsyl.genome.gcsa -k 16 vsyl.genome.vg' it needs at least 500Mb of memory, is there a way to reduce this?

**Comment by jeizenga** [comment]
Did you prune the graph first with `vg prune`? That's recommended on graphs that have dense variation, even if there are only small regions of density. Alternatively, you could use `vg autoindex -w map`, which essentially does our entire best-practices indexing pipeline for you automatically.
