### ISSUE TITLE
Assertion `hasNodeId(node_id)' failed

### ISSUE THREAD

**Issue by Kongqq5** [vgteam/vg#3783]
Hello,
I want to analyze the haploid-specific  transcriptome expression of a diploid plant, and I have assembled two haplotypes and obtained the corresponding annotation files.
What I have done
```
# Construct variation graph
wfmash -t 72 -p 90 -s 100000 ./BM#1#$CHR.fa.gz ./BM#2#$CHR.fa.gz  > ./$CHR.aln.paf
seqwish -t 72 -s $CHR.pggb.input.fa.gz -p $CHR.aln.paf -g $CHR.aln.gfa
smoothxg -t 72 -g $CHR.aln.gfa -V -o $CHR.smoothxg.aln.gfa
# Convert variation graph to PackedGraph format
vg convert -g $CHR.smoothxg.aln.gfa > $CHR.pg
# Find Chromosome transcripts
grep -P '$CHR' hap1.final_annotation1.gff > $CHR.hap1.gff
grep -P '$CHR' hap2.final_annotation1.gff > $CHR.hap2.gff
# Construct spliced variation graph
vg rna -k 256 -y CDS -s Parent -p -t 72 -n $CHR.hap1.gff -n $CHR.hap2.gff -r -u -b new.$CHR.pantranscriptome.gbwt -i new.$CHR.pantranscriptome.txt $CHR.pg > new.split.$CHR.pg
#Prune graph
vg prune -t 72  new.split.$CHR.pg > new.split.$CHR.pruned.pg
#gcsa index
vg index -Z 102400 -b split.chr.tmp -t 72 -p -g new.split.$CHR.pruned.pg.gcsa new.split.$CHR.pruned.pg
#Get distance and .xg 
vg index -b hap1 -t 72 -x new.split.$CHR.pruned.pg.xg new.split.$CHR.pruned.pg 
vg snarls -t 96 -T new.split.$CHR.pruned.pg.xg > new.split.$CHR.pruned.pg.snarls 
vg index -b hap1 -t 72 -x new.split.$CHR.pruned.pg.xg -s new.split.$CHR.pruned.pg.snarls -j new.split.$CHR.pruned.pg.dist
vg mpmap -t 72 -n rna -x new.split.$CHR.pruned.pg.xg -g new.split.$CHR.pruned.pg.gcsa -d new.split.$CHR.pruned.pg.dist -f SRR397771.1.clean.gz -f SRR397771.2.clean.gz > ./new.$CHR.seed.7771.gamp
vg gbwt --num-threads 72 -r new.$CHR.pantranscriptome.gbwt.ri new.$CHR.pantranscriptome.gbwt
```
**1. What were you trying to do?**
```
rpvg -t 60 -g new.split.$CHR.pruned.pg.xg -p new.$CHR.pantranscriptome.gbwt -a new.$CHR.seed.7771.gamp -f new.$CHR.pantranscriptome.txt.gz -o 771rpvg_results -i transcripts
```

**3. What actually happened?**
```
Running rpvg (commit: 1282449273f3f39e75542cc751dd5f2630050a25)
Random number generator seed: 1668482436
Fragment length distribution parameters found in alignment (mean: 205.934, standard deviation: 13.1126)
Loaded graph, GBWT and r-index (0.706422 seconds, 0.25808 GB)
rpvg: /public1/home/sc80041/software/new/rpvg/rpvg/src/paths_index.cpp:73: uint32_t PathsIndex::nodeLength(uint32_t) const: Assertion `hasNodeId(node_id)' failed.
```

**6. What does running `vg version` say?**

```
vg version v1.42.0 "Obolo"
Compiled with g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0 on Linux
Linked against libstd++ 20220324
Built by ubuntu@ip-172-31-12-246
```

**Comment by jonassibbesen** [comment]
hi, I think the issue is that you are using the pruned graph for mapping and expression inference. The pruned graph (*new.split.$CHR.pruned.pg*) should only be used for GCSA indexing. For generating the xg and distance indexes you should instead use the *new.split.$CHR.pg* graph. The same graph should also be used for mpmap and rpvg.

**Comment by Kongqq5** [comment]
Thank you for your prompt reply, i will give it a try.




孔倩倩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vgteam/vg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vgteam/vg] Assertion `hasNodeId(node_id)' failed (Issue #3783)





 
hi, I think the issue is that you are using the pruned graph for mapping and expression inference. The pruned graph (new.split.$CHR.pruned.pg) should only be used for GCSA indexing. For generating the xg and distance indexes you should instead use the new.split.$CHR.pg graph. The same graph should also be used for mpmap and rpvg.

**Comment by Kongqq5** [comment]
Hello, following your suggestion, I did solve the above problem, however, there is another small question, if I want to use the whole genome for mpmap, is there any way to merge the GCSA files of ten chromosomes together? Or does it have to be done?
···
vg index -Z 104800 -b tmp -p -t 72 -g split.gcsa $(for i in $(seq 1 10); do echo split.chr${i}_RagTag_pruned.vg; done)
···
 I've tried this way, but it runs slowly and there is no result file output. Do you have any suggestions?

**Comment by jonassibbesen** [comment]
Yes, you need to index all the chromosomes together. For how long has it run? GCSA indexing can take a while.

**Comment by Kongqq5** [comment]
Sorry to reply to you so late, I have already got the GCSA file as you suggested. Thank you so much!
