### ISSUE TITLE
vg mpmap aligns with softclips and not to intron

### ISSUE THREAD

**Issue by ldenti** [vgteam/vg#3802]
**1. What were you trying to do?**
Aligning RNA-Seq to a splicing graph with `vg mpmap`.

**2. What did you want to happen?**
Spliced reads should align to correct intron. 

**3. What actually happened?**
Reads are mapped with soft clippings (`S`) instead of introns (`N`). ![Screenshot_20221128_194323](https://user-images.githubusercontent.com/22707509/204356165-d7d7474e-bde9-46fe-96ed-8b81e56aa104.png)

Note that I should have an exon skipping in the alignments (between exon 1 and 2): ![Screenshot_20221128_194843](https://user-images.githubusercontent.com/22707509/204357258-38c34208-cb3a-4497-a54a-a79b3ed52064.png)

I noticed that regions around the splice sites are quite similar:
```
Correct:         CTGCTGTTGATTTTTTGCATAGTTAT                                  CTGTGA...       > 26M1549N75M
Reference:   TCTTCTGCTGTTGATTTTTTGCATAGTTAT | CTGTAAGAAAA ... ATATAAAGTTAC | CTGTGATTGTAT
VG mpmap:                                                           AGTTAT   CTGTGA...       > 20S81M
             --------- exon --------------> | <-------- intron ----------> | <-- exon ---
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

**5. What data and command can the vg dev team use to make the problem happen?**
I isolated this read on the gene: [PIGP.tar.gz](https://github.com/vgteam/vg/files/10106623/PIGP.tar.gz)

Commands I used:
```
# cannot autoindex since I don't have a VCF (is this correct?) 
vg construct -r PIGP.fa > PIGP.vg
vg convert -p PIGP.vg > PIGP.pg
vg rna -p -n PIGP.gtf  PIGP.pg  > PIGP.spliced.pg
vg index -p -x PIGP.spliced.xg -g PIGP.spliced.gcsa PIGP.spliced.pg
vg snarls -T PIGP.spliced.xg  > PIGP.spliced.trivial.snarls
vg mpmap -x PIGP.spliced.xg  -g PIGP.spliced.gcsa  -s PIGP.spliced.trivial.snarls   -f PIGP-read.fa  -F BAM > PIGP-read.bam
```

**6. What does running `vg version` say?**

```
vg version v1.44.0 "Solara"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```

**Comment by jeizenga** [comment]
Hi, sorry for the slow response. I've been on strike with my union for most of the last month. I just merged a PR that behaves more sensibly on cases like this where there is moderate micro-homology between the exon and the intron. I also thought the no-VCF spliced graph is a reasonable pipeline that `vg autoindex` should rightly handle, so I added the capacity for that workflow in the same PR. Let me know if you have any more issues :)
