### ISSUE TITLE
vg rna index

### ISSUE THREAD

**Issue by sdws1983** [vgteam/vg#3815]
Hi!
    I'm using `vg rna` for transcriptomic analyses following the [wiki](https://github.com/vgteam/vg/wiki/Transcriptomic-analyses). I will list each of my steps and confusion below：

1. First, I started with the final pangenome graph **.gfa** file obtained by the [cactus-minigraph pipeline](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md), which is in GFA 1.1 format. I converted it into GFA 1.0 format using [gfa-wp](https://github.com/pangenome/gfa-wp): `gfa-wp joint-full.gfa > joint-full.cov.gfa`

The first two columns of the P line in `joint-full.cov.gfa` looks like:
```
P       COR_A#0#Chr10:0-69032057
P       COR_B#0#Chr10:107698-185749
P       COR_B#0#Chr10:198532-281912
P       COR_B#0#Chr10:291916-528385
P       COR_B#0#Chr10:759772-790564
```
2. Then I used `joint-full.cov.gfa` for the GBWT construction:

```
vg convert -p -t 40 joint-full.cov.gfa > joint-full.cov.pg
vg gbwt -p -d ./ -o joint-full.cov.gbwt \
    --path-regex "(.*)#(.*)#(.*):(.*)" --path-fields _SHCF \
    -G joint-full.cov.gfa
```

3. Finally, I used `vg rna` for Pantranscriptomes Construction:
```
vg rna -p -t 40 -s ID -j -k 32 -u \
    -n gff/COR_A.gff -n gff/COR_B.gff \
    -n gff/COR_C.gff -n gff/COR_D.gff \
    -l joint-full.gbwt -b joint-full.rna.gbwt -f joint-full.rna.fa \
    -i joint-full.rna.txt joint-full.pg > joint-full.rna.pg
```
The following error occurred:
```
[vg rna] Parsing graph file ...
[vg rna] Parsing haplotype GBWT index file ...
[vg rna] Graph and GBWT index parsed in 25.7318 seconds, 18.4524 GB
[vg rna] Adding transcript splice-junctions and exon boundaries to graph ...
[transcriptome] ERROR: Chromomsome path "COR_A#0#Chr10" not found in graph or haplotypes index (line 1).
```

So, my question is: 

 - How do my steps need to be improved to successfully build a pan-transcriptome index using `vg rna` based on the `cactus-minigraph` gfa file.
 - How to solve the chromosome path mismatch in the error message, how do I know what the chromosome path in the gbwt index looks like?

**Comment by lsoldini** [comment]
I had similar error using pggb, and the solution was to use vg toolkit v.1.40.0 or below because .gfa from pggb were not supported by above verions

**Comment by sdws1983** [comment]
> I had similar error using graph _.gfa_ from `pggb`, and the solution was to use `vg toolkit` version 1.40.0 (or below) because _.gfa_ from `pggb` are not supported by vg > 1.40.0.

**Comment by sdws1983** [comment]
> I had similar error using graph _.gfa_ from `pggb`, and the solution was to use `vg toolkit` version 1.40.0 (or below) because _.gfa_ from `pggb` are not supported by vg > 1.40.0.

Thank you for sharing your experience, I have tried vg1.40, but I still get an error.

I think it is maybe the cause of the chromosome path mismatch. I use `vg gbwt -M -C -H -S -L -T joint-full.cov.gbwt` to view the information in the gbwt index, which is as follows:

```
29379 paths with names, 12 samples with names, 12 haplotypes, 10 contigs with names
Chr1
Chr3
Chr2
Chr10
Chr7
Chr9
Chr6
Chr8
Chr4
Chr5
12
COR_A
COR_B
COR_C
COR_D
COR_E
COR_F
COR_G
COR_H
COR_I
COR_J
COR_K
COR_L
_thread_COR_A_Chr10_0_0
_thread_COR_B_Chr10_0_107698
_thread_COR_B_Chr10_0_198532
_thread_COR_B_Chr10_0_291916
_thread_COR_B_Chr10_0_759772
_thread_COR_B_Chr10_0_943427
_thread_COR_B_Chr10_0_1088850
_thread_COR_B_Chr10_0_1166426
_thread_COR_B_Chr10_0_1229383
_thread_COR_B_Chr10_0_1992992
_thread_COR_B_Chr10_0_2266779
_thread_COR_B_Chr10_0_2317201
_thread_COR_B_Chr10_0_2361082
_thread_COR_B_Chr10_0_2377269
_thread_COR_B_Chr10_0_2521740
_thread_COR_B_Chr10_0_2552854
...
```

The names of `thread` shown here are completely different from those in the `gfa` P line path, which confuses me as to how to make the chromosome paths match. Even if I modify the chromosome name of the `gff` file according to the above `thread` name, it still doesn't work.

**Comment by lsoldini** [comment]
Sorry this is beyond what I know of `vg toolkit`, good luck!

**Comment by jonassibbesen** [comment]
Hi,
I am not sure why this is happening. Would it be possible for you to share the data? You can share it using: jonas.sibbesen@sund.ku.dk

**Comment by sdws1983** [comment]
> Hi, I am not sure why this is happening. Would it be possible for you to share the data? You can share it using: [jonas.sibbesen@sund.ku.dk](mailto:jonas.sibbesen@sund.ku.dk)

I have sent the email, you can check it now. Many thanks!
