### ISSUE TITLE
vg simplify on pggb graph bug

### ISSUE THREAD

**Issue by colindaven** [vgteam/vg#3817]
This bug was initially reported here with a valuable response from Glenn Hickey: 
https://github.com/pangenome/pggb/issues/270

**1. What were you trying to do?**

My goal is to simplify the graph prior to alignment to increase mapping speed and decrease downstream problems with SNP calling and SV genotyping.

I've generated quite a few graphs in PGGB and am trying to work with them in vg and with graphaligner. In general, I can map short and long reads and sometimes call SNPs, yet problems do occur.

I have read multiple issues from the vg team saying they test on minigraph-cactus graphs rather than PGGB graphs. Do you see any reason why the following error might occur, and how I might solve it ? Could vg simplify be too old, or the two ecosystems actually be somewhat incompatible ?

Workflow
`PGGB -> GFA per chromosome -> ODGI squeeze ->  OG to GFA -> vg convert GFA to VG -> vg simplify (fails) -> vg to GFA `

**2. What did you want to happen?**

**3. What actually happened?**

An error

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```

/1ac5a95697e10f859b0b469c956f01$ cat .command.err

graph path 'AT_Col-0_hq-v1.1.chr4' invalid: edge from 2932976 end to 2934155 end does not exist
graph path 'AT_Col-0_hq-v1.1.chr4' invalid: edge from 2934276 start to 3646278 start does not exist
error:[vg::SmallSnarlSimplifier] Invalid graph on iteration 0
```

**5. What data and command can the vg dev team use to make the problem happen?**

This is public data so fine to share, but likely not neccessary.

**6. What does running `vg version` say?**

```
vg version v1.44.0 "Solara"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon

```

**Comment by jeizenga** [comment]
VG generally assumes that paths (usually reference sequences) can only follow edges that actually exist in the graph (i.e. they are included in the GFA as L lines). It seems that your GFA contains a path that contains two non-adjacent nodes. Based on your description of the pipeline, my bet would be that this bug occurs earlier in the pipeline during the PGGB steps. The `vg convert` step is a very simple-minded conversion that doesn't check validity, so the input is probably already invalid in the GFA but only caught in `vg simplify`. Can you check the GFA to see if it is in fact missing that edge, and that the edge is taken by that path?

**Comment by colindaven** [comment]
Thanks for the response. Indeed, running `odgi validate` on all my test pangenomes does show problems have arisen during construction for most. The more complex the pangenome, the more problems arise 

- eg Arabidopsis chr1 only - no issues
- Arabidopsis all chr - 2 issues

I'll try to prune and simplify the pangenomes to avoid errors and test their paths are valid again using `odgi validate` before converting to GFA and moving to the vg toolset.
