### ISSUE TITLE
vg rna crash

### ISSUE THREAD

**Issue by lsoldini** [vgteam/vg#3818]
**1. What were you trying to do?**

I build a graph with `pggb` (two assemblies of the same species but different haplotypes), then converted it to _.pg_ with `vg convert` (v.1.40) then chopped nodes with `vg mod` (v.1.44, used for all further steps). 

Then, I wanted to build a spliced graph by adding the two _.gff_ files (one for each assembly).

```
vg rna -p -n annotationA.gff -n AnnotationB.gff -s Parent -c all -r -b pantranscriptome.gbwt -i pantranscriptome.txt genome_mod.pg > splicepangenome.pg
```

**2. What did you want to happen?**

Build a spliced graph (and pantranscriptome files) from _.gfa_ and _.gff_, using `vg rna`.

**3. What actually happened?**

```
[vg rna] Parsing graph file ...
[vg rna] Graph parsed in 0.219125 seconds, 0.254841 GB
[vg rna] Adding transcript splice-junctions and exon boundaries to graph ...
vg: src/transcriptome.cpp:622: int32_t vg::Transcriptome::parse_transcripts(std::vector<vg::Transcript>*, std::istream*, const bdsg::PositionOverlay&, const gbwt::GBWT&, bool) const: Assertion `strand == "+" || strand == "-"' failed.
ERROR: Signal 6 occurred. VG has crashed. 
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.44.0-199-g8570100f0 "Solara"
Stack trace (most recent call last):
#10   Object "", at 0xffffffffffffffff, in
#9    Object "PATH/bin/vg", at 0x564b9b400db9, in _start
#8    Object "/lib/x86_64-linux-gnu/libc-2.31.so", at 0x7f5718caed09, in __libc_start_main
#7    Object "PATH/bin/vg", at 0x564b9bb387f7, in vg::subcommand::Subcomm
and::operator()(int, char**) const
    | Source "src/subcommand/subcommand.cpp", line 75, in operator()
      Source "/usr/include/c++/10/bits/std_function.h", line 622, in operator() [0x564b9bb387f7]
        619:     {
        620:       if (_M_empty())
        621:    __throw_bad_function_call();
      > 622:       return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
        623:     }
        624:
        625: #if __cpp_rtti
#6    Object "PATH/bin/vg", at 0x564b9bb09bba, in main_rna(int, char**)
      Source "src/subcommand/rna_main.cpp", line 331, in main_rna [0x564b9bb09bba]
#5    Object "PATH/bin/vg", at 0x564b9c0a0b9f, in vg::Transcriptome::add_
reference_transcripts(std::vector<std::istream*, std::allocator<std::istream*> >, std::unique_ptr<gbwt::GBWT, std::default_delete<gbwt:
:GBWT> >&, bool, bool)
      Source "src/transcriptome.cpp", line 325, in add_reference_transcripts [0x564b9c0a0b9f]
#4    Object "PATH/bin/vg", at 0x564b9c086b03, in vg::Transcriptome::pars
e_transcripts(std::vector<vg::Transcript, std::allocator<vg::Transcript> >*, std::istream*, bdsg::PositionOverlay const&, gbwt::GBWT co
nst&, bool) const [clone .constprop.0]
      Source "src/transcriptome.cpp", line 622, in parse_transcripts [0x564b9c086b03]
#3    Object "/lib/x86_64-linux-gnu/libc-2.31.so", at 0x7f5718cbc661, in __assert_fail
#2    Object "/lib/x86_64-linux-gnu/libc-2.31.so", at 0x7f5718cad40e, in
#1    Object "/lib/x86_64-linux-gnu/libc-2.31.so", at 0x7f5718cad536, in abort
#0    Object "/lib/x86_64-linux-gnu/libc-2.31.so", at 0x7f5718cc3ce1, in raise
```

**5. What data and command can the vg dev team use to make the problem happen?**

Data are unpublished by I can share by email. I can add that both _.gff_ look as following:
```
##gff-version 3
Species1#1#chr1    Geneious        exon    21718402        21719026        .       -       .       Parent=Species.tr05232
Species1#1#chr1    Geneious        exon    21713828        21714078        .       -       .       Parent=Species.tr05232
Species1#1#chr1    Geneious        exon    21714243        21714467        .       -       .       Parent=Species.tr05232
```
For the other _.gff_, the locations are given as "Species2#1#chr" etc., such that the _.gff_ should be compatible with `pggb` paths (i.e., based on PanSpec). 

**6. What does running `vg version` say?**

Using vg 1.44.0 (Solara), cloned the 20.12.2022 (I am using Singularity, except for the `vg convert` step, for which I used conda v.1.40).  

For the singularity v.1.44 :
```
vg version v1.44.0-199-g8570100f0 "Solara"
Compiled with g++ (Debian 10.2.1-6) 10.2.1 20210110 on Linux
Linked against libstd++ 20210110
```
For the conda 1.40:
```
vg version v1.40.0 "Suardi"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
```

**Comment by lsoldini** [comment]
What surprises me the most is that I have two separate projects, each with two assemblies and associated RNA-seq data. I used the same pipeline for both (_.gfa_ to `rpvg`) and used similar formatting. However, for one of the two projects, I do not manage to get `vg rna` working. I tried with `vg 1.45.` but I still got the same error line:
```
vg: src/transcriptome.cpp:622: int32_t vg::Transcriptome::parse_transcripts(std::vector<vg::Transcript>*, std::istream*, const bdsg::Po
sitionOverlay&, const gbwt::GBWT&, bool) const: Assertion `strand == "+" || strand == "-"' failed.
```

**Comment by jeizenga** [comment]
Just a thought, could it be that one is space-delimited and the other tab-delimited? Or maybe the # in the contig name is being interpreted as a comment?

**Comment by lsoldini** [comment]
Thanks for the suggestion. Unfortunately, both are tab-delimited (just manually checked). Further, I don't think it can be the # in the contig name, because for my other project I used the same notation and it worked.

**Comment by lsoldini** [comment]
It is only one of the two _.gff_ causing this behaviour (i.e., I tried with both _.gff_ on its own). 

To see what differs between the two files, I searched for all unique entries (separately in each file):

- Seqname: all identical (except for one character: `Species1#1#chr1` vs `Species2#1#chr1`)
- Source: all annotation pipeline are shared between the two _.gff_
- Feature: all `exon` 
- Start: all numerical
- End: all numerical
- Score: all .
- Strand: + or - (1)
- Frame: all .
- Attribute: lots of differences, but I found no special character (, . - ; : #) that was unique to one of the two ...

(1) Actually there was a unique occurence of a "." in the non-working _.gff_, but after changing it to a "+" (as all other exon of that gene), it did not change the behaviour.

**Comment by jonassibbesen** [comment]
Hi, 
The first error you encountered was indeed due to the "." in the _Strand_ column. _Strand_ can only be either "+" or "-". The new error is because you have a transcript that spans more than one chromosome. This is not supported by `vg rna`. I should probably add some more informative error messages.

**Comment by lsoldini** [comment]
Hi Jonas, 
Great, thank you! Indeed, I had 4 genes that were on two chromosomes (i.e., the same name was used for different genes by the annotation pipeline twice). `vg rna` now worked smoothly and the `-c all` behaved as expected!

**Comment by lsoldini** [comment]
While `vg rna` worked smoothly, I noticed that 6 genes were lost in the process (i.e., they are in my _.gff_ but not in the `pantranscriptome.txt`). 

5 of these 6 genes are overlapping with each other (2 overlap on one chromosome, and 3 overlap in another chromosome). The 6-th gene may overlap with some other gene that was not lost in the process.

Anyway, this looks a lot like a previous issue I had (@jonassibbesen). If you'd agree, I could send you the data (or to someone else), to have a look.

**Comment by jonassibbesen** [comment]
Yes, it does sound like the previous issue. I would be happy to take a look. You can use the same email to send the data as last time.

**Comment by lsoldini** [comment]
Perfect, thanks! I just sent you an email with the files.

**Comment by xuxingyubio** [comment]
I'm very sorry to bother you.
I also encountered a similar problem: 

vg: src/transcriptome.cpp:718: int32_t vg::Transcriptome::parse_transcripts(std::vector<vg::Transcript>*, uint32_t*, std::istream*, const bdsg::PositionOverlay&, const gbwt::GBWT&, bool) const: Assertion `transcript->chrom == chrom' failed.

How can I screen and process transcripts that span multiple chromosomes?
