### ISSUE TITLE
vg mpmap returns GB of "oversized snarls without a graph" warnings

### ISSUE THREAD

**Issue by lsoldini** [vgteam/vg#3820]
**1. What were you trying to do?**

Map paired-end RNA-seq reads to spliced graph, with :
```
vg mpmap \
-x /PATH/splicepangenome.xg \
-g /PATH/splicepangenome.gcsa \
-d /PATH/splicepangenome.dist \
-n rna \
-l short \
-e low \
-f PATH/Sample1_R1.fastq.gz \
-f PATH/Sample1_R2.fastq.gz > PATH/Sample1.gamp
```

No errors or warning were given by any of the prior step (e.g., `vg index` or `vg rna`). 

**2. What actually happened?**

```
[vg mpmap] elapsed time 0 s: Loading graph from /users/lsoldini/workmc/MK_project/splice/splicepangenome.xg
[vg mpmap] elapsed time 3 s: Completed loading graph
[vg mpmap] elapsed time 3 s: Graph is in XG format. XG is a good graph format for most mapping use cases. PackedGraph may be selected i
f memory usage is too high. See `vg convert` if you want to change graph formats.
[vg mpmap] elapsed time 3 s: Identifying reference paths
[vg mpmap] elapsed time 3 s: Loading GCSA2 from /users/lsoldini/workmc/MK_project/splice/splicepangenome.gcsa
[vg mpmap] elapsed time 3 s: Loading distance index from /users/lsoldini/workmc/MK_project/splice/splicepangenome.dist (in background)
[vg mpmap] elapsed time 14 s: Completed loading GCSA2
[vg mpmap] elapsed time 14 s: Loading LCP from /users/lsoldini/workmc/MK_project/splice/splicepangenome.gcsa.lcp
[vg mpmap] elapsed time 14 s: Memoizing GCSA2 queries (in background)
[vg mpmap] elapsed time 16 s: Completed loading distance index
[vg mpmap] elapsed time 16 s: Completed loading LCP
[vg mpmap] elapsed time 18 s: Completed memoizing GCSA2 queries
[vg mpmap] elapsed time 18 s: Building null model to calibrate mismapping detection
warning: trying to find the distance in an oversized snarl without a graph. Returning inf
```
Then the last warining line is repeated forever (at least until I stopped it, after +5 GB of .out file).

**5. What data and command can the vg dev team use to make the problem happen?**

Unpublished data which I can send by email if required.

**6. What does running `vg version` say?**

```
vg version v1.44.0-199-g8570100f0 "Solara"
Compiled with g++ (Debian 10.2.1-6) 10.2.1 20210110 on Linux
Linked against libstd++ 20210110
```

**Comment by lsoldini** [comment]
Since I am using both `vg 1.40` (_.gfa_ -> _.pg_) and `vg 1.44` (all the rest) in the whole process, I wondered whether this could have an impact ? 

I also tried to re-run all indexes (.dist, .gcsa) and others preliminary files, but I still have the same warning.

**Comment by jeizenga** [comment]
This does seem to be a bug that resulted from our switch to a new back-end distance index encoding. My understanding is that @xchang1 is working on it, and it should be resolved soon.

**Comment by xchang1** [comment]
I just made a pr that should fix this. The warning is caused by snarls that are too big to be indexed. When the snarls don't get indexed, the algorithm will use a slower method for finding distances, which might makes mapping too slow. You can build the distance index with `vg index` and increase the `--snarl-limit` value to build the index for larger snarls. This will be a tradeoff between the size and build time for the index, and the runtime of the mapping algorithm.

**Comment by lsoldini** [comment]
Thanks for the pr and the reply. I'll try to increase the `--snarl-limit` in the meantime, although I am not sure about which value would be suited (i.e., I'll try around the default).

**Comment by lsoldini** [comment]
Thanks for the PR. As a side note, when running with `--snarl-limit` too small (e.g., 5000 or even 10000 in my case), it still gives GB of "oversized snarl" warnings when running `vg mpmap`.

**Comment by xchang1** [comment]
If you want to know how big the snarls are, you can use `vg stats -b` with the distance index. The snarl_size column is how many nodes are in a given snarl. Probably there are just a couple outliers that are very big and you can set the limit to exclude those.

**Comment by lsoldini** [comment]
Thanks for the feedback and the `vg stats -b` way to work around this. Anyway, I am working with a rather small genome, so increasing the `--snarls-limit` was not a problem with respect to memory use or running time. 
Since there seems to be some problems with graphs from `pggb` and `vg convert` from >v.1.40 fails to convert _.gfa_ to _.pg_, would you rather suggest using cactus ? Is it planned that, on the long term, `vg` will only work with that ?

**Comment by jeizenga** [comment]
The Minigraph-Cactus pipeline does produce graphs with simpler topologies, and we've been able to produce reasonable distance indexes for them in the past. Ideally, I think we'd like to be able to support graphs constructed with PGGB as well, but we haven't found a way to do so with the existing algorithmic technology in the best-practices pipelines for `vg mpmap` and `vg giraffe` yet. 

That said, there actually is a mapping mode in `vg mpmap` that doesn't use a distance index (although you would then want to supply the snarls with `-s`), but I haven't focused on maintaining or optimizing it. I suspect that the accuracy will be noticeably worse.

**Comment by lsoldini** [comment]
I see, thank you for the explanation. I am considering switching method for the graph-construction step. 

Do you think that too complex graph topologies could also explain an excessively high memory consumption of _.gamp_ to _bam_ conversion ? (using `vg surject -S -A -b -m -i`, I am having out of memory errors for one single file while providing +64Gb RAM ... I could also make another issue if required).

**Comment by jeizenga** [comment]
Possibly. Most likely I'd have to take a look at the data you're using to be sure.

**Comment by lsoldini** [comment]
I've sent you the `.xg`, `ref_paths.txt`, one `.gamp`, and the initial files (`.gfa` and `.gff`) by email. If you have some time to look at it, it would be great. If it's not related to complex graph topologies, I'll make a new issue.
