### ISSUE TITLE
editing introduces duplicates

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#383]
It looks like there are a number of problems with `VG::edit`.

I'm exploring the new `vg genotype` command by making trivial changes to a linear graph, simulating reads from the changed graph, and mapping them back. Then I try to do calling. This didn't work for both of the SNPs so I examined the editing results produced by `vg mod -i`. They look a bit funny.

Here's a screenshot to explain several of the problems:

![screenshot from 2016-06-17 15-47-15](https://cloud.githubusercontent.com/assets/145425/16143054/4189bf9a-34a5-11e6-80cd-b897193fb254.png)

Zooming in on one of the bubbles:

![image](https://cloud.githubusercontent.com/assets/145425/16143088/77af12a0-34a5-11e6-9d10-521f83db6a15.png)

The same node is added many times by edit. Woah! I didn't expect that.

~~Worse, there are some edits which seem to be coming in reversed, but aren't reverse complemented when projected into the graph.~~ This is the reference base, so not a problem.

Normalization is a nice idea, but doesn't yet produce graph translations. It also doesn't work on this graph! I'm not sure why.

So there are a heap of problems here...

**Comment by adamnovak** [comment]
Is this the underlying cause of #389 maybe?

Also, isn't this fixed now?

**Comment by ekg** [comment]
This is fixed now.
