### ISSUE TITLE
Results of Normalize Snarls Indicates Problematic Alignment with Giraffe

### ISSUE THREAD

**Issue by Robin-Rounthwaite** [vgteam/vg#3859]
**1. What were you trying to do?**
Normalize Snarls is built to take each snarl, extract their haplotypes, and realign them using sPOA to generate a new and hopefully improved representation of variation.

Running this process has indicated one or multiple bugs with Giraffe. I'll use the mapping of seed_12345_fragment_100483 as an example mapping.

**2. What did you want to happen?**
Get reads which map consistently to both the unnormalized and normalized graphs, at least for the type so changes in this example.

**3. What actually happened?**
First, the unnormalized graph has multiple secondary overlapping mappings, and these mappings overlap. Is that supposed to be possible?

Second, it seems unlikely that giraffe should be this confused about the mapping locations of these reads. Note that, when the normalized graph rearranges the variation slightly, the secondary mappings are collapsed into a single mapping. 

Here are screenshots of the most relevant snarl in the mapping. I’ll also include where you can find the .svg visualizations, as well as the 3 single-line gams needed to debug the read mapping (truth set, unnormalized mapping gam, and normalized mapping gam). 

**5. What data and command can the vg dev team use to make the problem happen?**
Unnormalized snarl screenshot
![unnormalized-100483](https://user-images.githubusercontent.com/35412828/219212761-10a42192-1629-4d3b-ad58-978bde7fe252.png)

normalized snarl screenshot
![normalized-100483](https://user-images.githubusercontent.com/35412828/219212625-0a8710e4-05de-4b35-8717-1f7c2ab1dfbd.png)

Unnormalized mapping output (gam of a single read):
s3://vg-k8s/users/rrounthw/normalize_snarls/report-giraffe-bug/seed_12345_fragment_100483.unnormalized.gam

Normalized mapping output (gam of a single read):
s3://vg-k8s/users/rrounthw/normalize_snarls/report-giraffe-bug/seed_12345_fragment_100483.normalized.gam

truth-set gam (gam of a single read):
s3://vg-k8s/users/rrounthw/normalize_snarls/report-giraffe-bug/seed_12345_fragment_100483.true-pos.gam

unnormalized graph:
s3://vg-k8s/users/rrounthw/normalize_snarls/report-giraffe-bug/graph.vg

normalized graph:
s3://vg-k8s/users/rrounthw/normalize_snarls/report-giraffe-bug/graph.spoa.normalized.vg

You can find the svgs here:
s3://vg-k8s/users/rrounthw/normalize_snarls/report-giraffe-bug/seed_12345_fragment_100483-svgs/

Example commands to run mapping (where BASE is the name of the files without the extension):
```
vg convert -x ${BASE}.vg > ${BASE}.xg

# #get gbwt, gg, min, dist:

vg index -j ${BASE}.dist ${BASE}.xg

vg gbwt -g ${BASE}.sampled.gbwt.gg -x ${BASE}.xg ${BASE}.sampled.gbwt

vg minimizer -g ${BASE}.sampled.gbwt -d ${BASE}.dist -o ${BASE}.min ${BASE}.sampled.gbwt.gg 

vg giraffe -M 10 -x ${BASE}.xg -H ${BASE}.sampled.gbwt -g ${BASE}.sampled.gbwt.gg -m ${BASE}.min -d ${BASE}.dist -G ${SIM_READS} -b default -i -t 22 > ${OUTPUT_DIR}/${METADATA}.${BASE}.mapped.gam

```

**6. What does running `vg version` say?**

```
vg version v1.44.0-208-g319d08485 "Solara"
Compiled with g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 on Linux
Linked against libstd++ 20220421
Built by robin@robin-Zephyrus
```

**Comment by jltsiren** [comment]
I think this is the issue: https://github.com/vgteam/vg/blob/6259717c20a434018dd2829ef8ed3a49b53ad62d/src/gbwt_extender.hpp#L179-L185

According to the specification we ended up with, `GaplessExtender::extend()` should ideally return the maximal set of non-overlapping full-length extensions that start from different seeds in the cluster and remain within the mismatch bound. Two extensions are "non-overlapping" if the fraction of identical base mappings is at most `overlap_threshold` (default 0.8). In an extreme case, if you have a long sequence of GTGTGTGTGTGT..., extensions that start from i, i+2, i+4, ... are non-overlapping by this definition.

**Comment by benedictpaten** [comment]
I see, so non-overlapping is based upon the fraction matching pairs? This is reasonable in some respects. @jeizenga what do you think?

**Comment by jeizenga** [comment]
If I'm understanding things correctly, I think it's a tricky problem, which pretty much boils down to figuring out when two distinct graph locations are "the same". Node IDs work most of the time, but there are obviously limitations. It looks to me like this is a case where the normalization has improved the situation by making the alleles have a single canonical representation, right?
