### ISSUE TITLE
MinHash is useful for pre-clustering/pre-classification of reads, but isn't native in vg yet.

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#387]
I've run into a few useful cases for MinHash so far. I'm working on a small library to bring it into the vg code, as it is very useful in pre-clustering genomes (e.g. before running MSGA) and may also be useful in resolving reads with large soft clips (i.e. determining the degree of similarity between their soft clipped regions, for instance).

I'll bring in another submodule with my code in the time I have available this week or next.

**Comment by adamnovak** [comment]
@edawson Is this still something you want to do?

**Comment by edawson** [comment]
I think @ekg got around it by just improving MSGA. The use case I wanted to use this for has been shifted to another project.
