### ISSUE TITLE
vg align does 1 alignment when given many reads

### ISSUE THREAD

**Issue by abanerjee10** [vgteam/vg#3870]
**1. What were you trying to do?**
I was trying to optimally align a fastq file of 10k reads to a genome graph.

**2. What did you want to happen?**
I wanted vg align to output an optimal alignment for each of the reads in my fastq file.

**3. What actually happened?**
vg align performed a single alignment.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Total alignments: 1
Total primary: 1
Total secondary: 0
Total aligned: 1
Total perfect: 0
Total gapless (softclips allowed): 1
Total paired: 0
Total properly paired: 0
Insertions: 0 bp in 0 read events
Deletions: 0 bp in 0 read events
Substitutions: 41 bp in 41 read events
Softclips: 0 bp in 0 read events
```

**5. What data and command can the vg dev team use to make the problem happen?**
Data:
[brca1.zip](https://github.com/vgteam/vg/files/10864765/brca1.zip)
Commands:
```
vg align -s brca1.fastq brca1.vg > brca1.gam
vg stats brca1.gam
```

**6. What does running `vg version` say?**

```
vg version v1.43.0 "Barisano"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```

**Comment by jeizenga** [comment]
This behavior is expected.`vg align` is essentially a debugging and unit testing tool. If you want to map sequencing reads to the graph, you should use one of our read mapping tools: `vg map`, `vg mpmap`, or `vg giraffe`.

**Comment by abanerjee10** [comment]
I see, could you share how to do optimal instead of heuristic read mapping? I thought that vg align was the solution for doing so.

**Comment by abanerjee10** [comment]
I wanted to know vg's support for this, so scripting with vg align is good to know. Thanks for your help!
