### ISSUE TITLE
vg filter followed by vg surject with -i results in truncated bam

### ISSUE THREAD

**Issue by peterdfields** [vgteam/vg#3872]
**1. What were you trying to do?**

I'm trying to output a bam file from a gam file which was generated using `vg map` and `vg filter`

**2. What did you want to happen?**

I wanted the output bam file to maintain pairing information

**3. What actually happened?**

When I use the `vg surject` on the filtered bam file with the `-i` flag I receive the following error:

```
[vg surject] error: alignments A00739:714:H53H5DSX5:3:1101:14009:19899 and A00739:714:H53H5DSX5:3:1101:14281:19899 are adjacent but not paired
```
The resulting bam file is substantially truncated. If I do not include the `-i` flag the command runs successfully and the bam file is fine. If I run `vg surject` with the `-i` flag on the unfiltered bam file the process also completes successfully.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

`vg surject -x grcm39_cast.xg -b -i B6xB6-Day0-2.filtered.gam > B6xB6-Day0-2.bam`

**6. What does running `vg version` say?**

Initially I tried the following version

```
vg version v1.45.0 "Alpicella"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```

When I found issue #3711, I went ahead and tried the more recent version

```
vg version v1.46.0 "Altamura"
Compiled with g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0 on Linux
Linked against libstd++ 20210408
Built by xian@octo
```

The error persists across both versions.

**Comment by jeizenga** [comment]
How were the reads mapped?

**Comment by peterdfields** [comment]
@jeizenga the reads were mapped with `vg map`, with left and right reads provided with two `-f` flags.

**Comment by jeizenga** [comment]
Could you provide the exact command?

**Comment by peterdfields** [comment]
@jeizenga sure:

```
vg map -f ../reads_trim/B6xB6-Day0-2_R1_paired_trimmed.fq.gz \
-f ../reads_trim/B6xB6-Day0-2_R2_paired_trimmed.fq.gz \
-x grcm39_cast.xg -g grcm39_cast.gcsa -t 56 \
> B6xB6-Day0-2.gam
```

**Comment by jeizenga** [comment]
Hmm, nothing immediately jumps out at me from the command line calls. Do you have a sense of how quickly `vg surject` runs into this crash? Also, is it possible to share the data?

**Comment by peterdfields** [comment]
@jeizenga The error happens very quickly when running `vg surject`, probably in less than a minute. The output partial bam file is very small. I don't think it would be so easy to share the data as a whole. Is it useful to somehow subset the gam to the first part in someway and that might be sharable?

**Comment by jeizenga** [comment]
Oh, actually I just noticed that you said you also used `vg filter` in the issue title. Sorry I missed that. Did you use either `-i` or `-I` in `vg filter`?

**Comment by peterdfields** [comment]
@jeizenga I did not use the `-i` or `-I` in the `vg filter` step. I can repeat the filtering step with this flag included and see if the error persists?

**Comment by jeizenga** [comment]
That's almost certainly the issue then. Either option will make sure that pairs are filtered as full pairs. Without one of the flags, it's possible to remove only one end of the pair, which is why `vg surject` is getting confused about the missing paired read.
