### ISSUE TITLE
What's the dominance of variation graph if I surject the alignment to linear reference

### ISSUE THREAD

**Issue by dudududu12138** [vgteam/vg#3885]
Hello,
    I tried to surject my alignment result(.gam) to GRCh38. And I successfully got the bam file. But I can only surject the mapping result to chromosomes in GRCh38. And I know the reads that mapped to non-reference paths will be remapped to the reference. But in this way, the non-reference sequences are lost. So after surject, is the advantage of the graph genome over the linear genome thrown away?

**Comment by netwon123** [comment]
> You are correct that a read mapping that is completely off of a reference sequence will be lost. However, most of the time read mappings partially overlap the reference, so their rough mapping location will be preserved. Thus, the benefit in reduced mapping bias is preserved. The conversion to BAM also preserves the base-level alignment against the graph, which lets it produce alignments that would normally be disfavored by linear reference mappers (such as an alignment that spans a large deletion).

Sorry, i think it would loss some true variant in non-reference paths.  Could it  be solved in vg pipeline?
