### ISSUE TITLE
Unexpected delimiter/Signal 6 when running vg giraffe

### ISSUE THREAD

**Issue by WackerO** [vgteam/vg#3897]
Hey there, I am trying to generate a test GAM file for the module test in https://github.com/nf-core/modules/pull/3202 and giraffe is throwing an unexpected delimiter error (possibly related to #3512).

**1. What were you trying to do?**
I tried to run
```
vg giraffe -Z giraffe/test.giraffe.gbz -m giraffe/test.min -d giraffe/test.dist -f data/genome.fasta > test_mapped.gam
```

**2. What did you want to happen?**
I wanted to produce a GAM file

**3. What actually happened?**
This error showed:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found unexpected delimiter N in fastq/fasta inputERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_gy2iqv/stacktrace.txt
Please include the stack trace file in your bug report!
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.46.0 "Altamura"
Stack trace (most recent call last) in thread 1909516:
#13   Object "", at 0xffffffffffffffff, in 
#12   Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x20c4632, in __clone
#11   Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x15b0f68, in start_thread
#10   Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x1ff2e5d, in gomp_thread_start
#9    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x10d948f, in unsigned long vg::io::unpaired_for_each_parallel<vg::Alignment>(std::function<bool (vg::Alignment&)>, std::function<void (vg::Alignment&)>, unsigned long) [clone ._omp_fn.0]
#8    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x552e47, in vg::get_next_alignment_from_fastq(gzFile_s*, char*, unsigned long, vg::Alignment&) [clone .cold]
#7    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x2009159, in _Unwind_Resume
#6    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x200862d, in _Unwind_RaiseException_Phase2
#5    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x1f47320, in __gxx_personality_v0
#4    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x1fe1128, in __cxa_call_terminate
#3    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x1f4798b, in __cxxabiv1::__terminate(void (*)())
#2    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x5e1d06, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#1    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x5e455f, in abort
#0    Object "/home/iivow01/tools/miniconda3/bin/vg", at 0x15b47eb, in raise
```

**5. What data and command can the vg dev team use to make the problem happen?**

Use the following files as input for `vg autoindex --workflow giraffe`

 https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/gatk/haplotypecaller_calls/test2_haplotc.ann.vcf.gz

https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/chr21/sequence/genome.fasta

https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/chr21/sequence/genome.fasta.fai

Then run `vg giraffe` with the results.

**6. What does running `vg version` say?**

```
vg version v1.46.0 "Altamura"
Compiled with g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0 on Linux
Linked against libstd++ 20210408
Built by xian@octo
```
(Tried 1.45.0 before, same issue)

**Comment by WackerO** [comment]
Hm no, I'm using a short sub-fasta which has one name >chr21. The sequence itself starts with a lot of N before the actual base sequence starts

**Comment by jeizenga** [comment]
It looks like our FASTA parsing function assumes that each sequence is on a single line. This isn't great behavior, since the multi-line FASTA sequence is a common idiom. However, if you need a hot-fix, you could edit your FASTA so that the entire sequence is on one line. That said, the current iteration of `vg giraffe` is really designed for short read sequencing data. We are working on developing methods to map high-accuracy long read data, but we have not invested time in mapping entire chromosome sequences. I personally doubt that you will get particularly good performance.
