### ISSUE TITLE
Determining path of aligned reads

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#390]
Hello,

If I've aligned reads to a graph, what's the best way to find out the path that those reads take through the graph? I have a graph of different alleles for a specific region, and I would like to be able to determine the allele that best matches the aligned reads. Is there a way to print out the sequence information of the aligned nodes from the pileup output?

**Comment by ekg** [comment]
> If I've aligned reads to a graph, what's the best way to find out the path that those reads take through the graph?

You can walk Mappings in the Path object embedded in the Alignment. Each mapping has a position, and each position has `node_id`, `offset`, and `is_reverse` variables that define a starting position on the bidirectional digraph.

Maybe the easiest way to do this would be by parsing the line-delimited JSON output by `vg view -a` on the GAM stream emitted by the aligner. You can quickly make a table using jq.

You can run this example in the test directory:

```
vg construct -v tiny/tiny.vcf.gz -r tiny/tiny.fa > tiny.vg
vg index -x tiny.vg.xg tiny.vg
vg sim -s 420 -n 5 -e 0.1 -i 0.2 -x tiny.vg.xg -l 30 -a | vg view -a - | sort | vg view -JGa - > tiny.sim
vg map -G tiny.sim -k 8 -V tiny.vg -t 1 > tiny.gam
```

Using jq we can get vectors describing the nodes that each path maps across:

```
-> % vg view -a tiny.gam | jq -c '[ .path.mapping[] | .position.node_id ]'
[9,10,12]
[1,2,4,6,8,9]
[9,7,6,4]
[6,5,3,1]
```

However, keep in mind that these may run in either forward or reverse direction, and they may not start at the beginning of the node, so we might want to look at the whole position object:

```
-> % vg view -a tiny.gam | jq -c '[ .path.mapping[] | .position ]'        
[{"node_id":9,"offset":12},{"node_id":10},{"node_id":12}]
[{"node_id":1,"offset":5},{"node_id":2},{"node_id":4},{"node_id":6},{"node_id":8},{"node_id":9}]
[{"is_reverse":true,"node_id":9,"offset":13},{"is_reverse":true,"node_id":7},{"is_reverse":true,"node_id":6},{"is_reverse":true,"node_id":4}]
[{"is_reverse":true,"node_id":6,"offset":2},{"is_reverse":true,"node_id":5},{"is_reverse":true,"node_id":3},{"is_reverse":true,"node_id":1}]
```

Hopefully it's easy to get an interface that you can work with downstream.

> I have a graph of different alleles for a specific region, and I would like to be able to determine the allele that best matches the aligned reads.

Are you thinking of developing a genotyping algorithm? Or is this just exploratory?

**Comment by hgibling** [comment]
Thanks, I should be able to figure out a script for parsing the mappings and comparing it to `vg paths -x`.

This is exploratory for now, but hoping to turn it into a genotyping script.
