### ISSUE TITLE
vg pack error

### ISSUE THREAD

**Issue by ETC100** [vgteam/vg#3915]
**1. What were you trying to do?**
Hello, I got an error when using vg pack. I run vg pack after the giraffe mapping was completed. The fastq.gz file using for giraffe mapping are two-paired end 150bp short reads.

**2. What did you want to happen?**
I have got the gam file by giraffe and I further want to get pack file to call variants.

**3. What actually happened?**
VG crashed and I failed to run vg pack.
The error information is as followed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [vg::io::MessageIterator::operator++] (group 0) message of 1714655862 bytes is too long
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_gNqLS8/stacktrace.txt

**4. The content of stacktrace.txt

```
Crash report for vg v1.46.0-40-gc2078c664 "Altamura"
Stack trace (most recent call last):
#18   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x612bf4, in _start
#17   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x20450e6, in __libc_start_main
#16   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x2043889, in __libc_start_call_main
#15   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0xdd04db, in vg::subcommand::Subcommand::operator()(int, char**) const
#14   Object "cactus-bin-v2.4.3/bin/vg", at 0xd90985, in main_pack(int, char**)
#13   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x13df407, in vg::get_input_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)>)
#12   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0xd8ec2d, in std::_Function_handler<void (std::istream&), main_pack(int, char**)::{lambda(std::istream&)#2}>::_M_invoke(std::_Any_data const&, std::istream&)
#11   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x2021145, in GOMP_parallel
#10   Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0xd914fb, in void vg::io::for_each_parallel_impl<vg::Alignment>(std::istream&, std::function<void (vg::Alignment&, vg::Alignment&)> const&, std::function<void (vg::Alignment&)> const&, std::function<bool ()> const&, unsigned long) [clone ._omp_fn.0]
#9    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x5d12e1, in vg::io::MessageIterator::take[abi:cxx11]() [clone .cold]
#8    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x2040f8d, in _Unwind_Resume
#7    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x204040b, in _Unwind_RaiseException_Phase2
#6    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x1f7cab9, in __gxx_personality_v0
#5    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x20171d8, in __cxa_call_terminate
#4    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x1f7d36b, in __cxxabiv1::__terminate(void (*)())
#3    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x5df48d, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#2    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x5e1bd5, in abort
#1    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x205c2c5, in raise
#0    Object "biosoft/cactus-bin-v2.4.3/bin/vg", at 0x2088ccc, in __pthread_kill
```

**5. What data and command can the vg dev team use to make the problem happen?**
vg giraffe -Z graph.gbz -m graph.min -d graph.dist -x graph.xg -f 1.fastq.gz -f 2.fastq.gz -t 20 > species.gam
vg pack -t 15 -x graph.xg -g species.gam -Q 5 -s 5 -o species.pack

**6. The vg version
```
vg: variation graph tool, version v1.46.0-40-gc2078c664 "Altamura"
```

**Comment by jltsiren** [comment]
This looks similar to #3914. If you look inside the GAM file, does it start with something resembling status messages or warnings? If so, it could be that your environment redirects stderr to stdout and all the messages printed by Giraffe end up in the GAM file. Then you should be able to fix the problem by finding a way to keep the two streams separate.

**Comment by Dkyuan** [comment]
Hello, is it solved? I met the similar issue.

**Comment by ETC100** [comment]
> Hello, is it solved? I met the similar issue.

Yes, this problem have been solved. You can directly run vg without "nohup" or use "nohup yourcommand 2>&1 &" to redirect the output of information to a log file, not in gam file.
