### ISSUE TITLE
The .gaf output doesn't follow the standard 

### ISSUE THREAD

**Issue by Mirkocoggi** [vgteam/vg#3930]
I'm using " vg map [options] --gaf  > aln.gaf " and when I open the aln.gaf file the values are correct but the read name is missing and between each line, there is a line of ' * ', which make it really hard to be parsed by a GAF parser. Finally, the CIGAR of each read alignment is missing too.

**Comment by glennhickey** [comment]
Please share your full command line, and example of an input read and what it looks like in your GAF.

**Comment by Mirkocoggi** [comment]
[Files.zip](https://github.com/vgteam/vg/files/11292959/Files.zip)
command: vg map -T input_data/t1.fa -x input_data/graph.xg -g input_data/graph.gcsa --gaf > output/out_vg.gaf
In the .ZIP folder you will find the t1.fa read file, the graph.gfa graph file (which has been passed through the view command to be converted in .vg, then in the mod command for reducing the number of characters in the nodes, and then in the index command to create the .xg and .gcsa) and the out_vg.gaf results file.

**Comment by glennhickey** [comment]
Try using `-F` to pass in FASTA format reads.
```
input:
    -s, --sequence STR            align a string to the graph in graph.vg using partial order alignment
    -V, --seq-name STR            name the sequence using this value (for graph modification with new named paths)
    -T, --reads FILE              take reads (one per line) from FILE, write alignments to stdout
    -b, --hts-input FILE          align reads from htslib-compatible FILE (BAM/CRAM/SAM) stdin (-), alignments to stdout
    -G, --gam-input FILE          realign GAM input
    -f, --fastq FILE              input fastq or (2-line format) fasta, possibly compressed, two are allowed, one for each mate
    -F, --fasta FILE              align the sequences in a FASTA file that may have multiple lines per reference sequence
    -i, --interleaved             fastq or GAM is interleaved paired-ended
    -N, --sample NAME             for --reads input, add this sample
    -R, --read-group NAME         for --reads input, add this read group

```

**Comment by Mirkocoggi** [comment]
Now the output is correct, but I think there is a problem with the CIGAR string:

VG output
r1	51	0	51	+	>101	256	0	50	51	51	60	AS:i:61	cs:Z::51	dv:f:0
r2	45	0	45	+	>103	256	0	44	44	45	60	AS:i:50	cs:Z::4*TG:40	dv:f:0.0222
r3	42	0	42	+	>103	256	0	42	42	42	60	AS:i:46	cs:Z::4-T:38	dv:f:0

GraphAligner output
r1	51	0	51	+	>101	3023	0	51	51	51	60	NM:i:0	AS:f:51	dv:f:0	id:f:1	cg:Z:51=
r2	45	0	45	+	>103	1345	0	45	44	45	60	NM:i:1	AS:f:42.06	dv:f:0.0222222	id:f:0.977778	cg:Z:4=1X40=
r3	42	0	42	+	>103	1345	0	43	42	43	60	NM:i:1	AS:f:39.06	dv:f:0.0232558	id:f:0.976744	cg:Z:5=1D37=

In particular it use the ' : ' instead of ' = ', and the subst and deletion are proposed in a different format.

**Comment by glennhickey** [comment]
vg outputs `cs` cigar strings, which are more verbose than the `cg` cigar strings from graph aligner (ie they contain non-reference bases).  You can see the exact specifications [here](https://lh3.github.io/minimap2/minimap2.html)

**Comment by Mirkocoggi** [comment]
Ok thank you! Do you know if there is a tool for converting a `cs` CIGAR to a `cg` CIGAR?

**Comment by glennhickey** [comment]
We're using the `cs` fields because they most closely resemble GAM which most of `vg` still uses internally.  I also like that `cs` gives you everything you need for variant calling without needing to look up the read's sequence. 

I'm not aware of any conversion tools, personally, but I guess if enough people need `cg` cigars we can look at adding one to `vg` (which already supports (lossy) conversion from `cg` to `cs`).
