### ISSUE TITLE
Extracting GFA with alternate paths from vg autoindex

### ISSUE THREAD

**Issue by venkatk89** [vgteam/vg#3949]
**1. What were you trying to do?**

I am creating a human whole genome graph and indexing it with the *vg autoindex* command within the Giraffe workflow. I want to extract the GFA files (with the alternate paths) of the the created genome graph. 

**2. What did you want to happen?**

**2A.** Used the autoindex command, with the *--keep-intermediate* parameter to retain the .vg files. Then used *vg view* to extract the GFA out.

**2B.** Created the indices required for the Giraffe mapper manually by retracing the computational pipeline followed by the [vg-snakemake](https://github.com/vgteam/vg_snakemake/blob/master/Snakefile#L495) repository in Github. This method enabled us to convert the .vg files to GFA format.

**2C.** Created the VG files manually and converted them to GFA files. Each chromosome in the human genome corresond to one GFA file. Using the *vg ids* command, the node IDs are coordinated between all the files to be continuous.
Then created the indices by passing the GFA files as a list (as VCF files are passed in the [documentation](https://github.com/vgteam/vg/wiki/Mapping-short-reads-with-Giraffe)) to the *vg autoindex* command with the *--gfa parameter*.

**3. What actually happened?**

**3A.** Files did not have any alternate allele paths. The following warning was observed;
```
[IndexRegistry]: Stripping allele paths from VG. 
```
Also retained some files named *.varpaths.vg* but these files also do not contain the alternate path and are exact copies of the .vg files.

**3B.** The final indices created, when used for mapping, are extremely slow compared to the autoindex created files.
  
**3C.** Created the genome graph only for the first chromosome in the list.
  
**5. What data and command can the vg dev team use to make the problem happen?**
The VCF files from the [1000 genomes project](http://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/) and GRCH38 reference genome with the commands from the [documentation](https://github.com/vgteam/vg/wiki/Mapping-short-reads-with-Giraffe#indexing-with-vg-autoindex) can be used to recreate this issue. 

**6. What does running `vg version` say?**

```
vg version v1.42.0 "Obolo"
Compiled with g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0 on Linux
Linked against libstd++ 20220324
Built by ubuntu@ip-172-31-12-246
```

One alternate way we are working on is to concatenate all the ID coordinated chromosome-wise GFA files into a single whole genome GFA file and pass it to the *vg autoindex* command.

Is this a practicable solution? Or are there better ways to accomplish this task? 
Please let us know what your thoughts are.
Thanks a lot in advance for taking the time to help me out.

Warmly,
Venkatesh K

**Comment by jeizenga** [comment]
It would be easier for me to diagnose what's happening here if you included the actual commands, but it seems like you're using `vg autoindex` for a purpose that it's not really designed for. I highly recommend not trying to reach into the inside of on of `vg autoindes`'s indexing workflows. The individual steps can be unintuitive, and we don't try to maintain any consistent interface or guarantees for the intermediate stages. The `--keep-intermediate` option is only intended as a debugging tool.

I think what might be happening here is that `vg autoindex` does not accept repeated `--gfa` arguments. It's probably only retaining the last GFA, in which case you would expect mapping to be very slow since most reads will not have a good mapping target.

**Comment by venkatk89** [comment]
Thank you for your quick response.

I was wondering if there is a way to manually create the indices required for the Giraffe mapper from scratch. By collating the different indexing commands present in the wiki, I could come with the following pipeline for creating the 1000 genomes project graph:

**1.Create VG files with alt paths**
```
(seq 1 22; echo X; echo Y) | \
parallel -j 24 \
vg construct --alt-paths \
--region-is-chrom --region chr{} \
--reference $hg38_reference_genome \
--vcf 1KGP_chr{}.vcf.gz \
--threads 1 --flat-alts --handle-sv > 1KGP_graph_chr{}.vg 
```

**2. Coordinate Node IDs**
```
vg ids -j -m mapping $(for i in $(seq 1 22; echo X; echo Y); do echo 1KGP_graph_chr$i.vg; done)
```

**3. Create GFAs**
```
seq 1 22; echo X; echo Y) | \
parallel -j 24 \
"time \
vg view -v 1KGP_graph_chr{}.vg \
-g > 1KGP_graph_chr{}.gfa
```

**4. Get XG index with Alt paths**
```
vg index -L -x 1KGP_graph.xg \
$(for i in $(seq 22; echo X; echo Y); do echo 1KGP_graph_chr$i.vg; done)
```

**5. GBWT with greedy path cover**
```
vg gbwt -n 16 -g 1KGP_graph.gg -o 1KGP_graph.gbwt -x 1KGP_graph.xg -P 
```

**6. Build Minimizer Index**
```
vg minimizer -o 1KGP_graph.min -g 1KGP_graph.gbwt 1KGP_graph.xg
```

**7. Get Distance Index**
```
vg snarls --include-trivial 1KGP_graph.xg > 1KGP_graph.trivial.snarls

vg index -j 1KGP_graph.dist -x 1KGP_graph.xg -s 1KGP_graph.trivial.snarls
```


When I run *vg giraffe* using the .gbwt, .dist and .min files created above, a .gbz file is created for the first time. Later on, the .gbz file is auto-recognized  by giraffe. 

But the issue is, when using these indices, the runtime of the giraffe mapper is extremely high. Is the pipeline missing something?

**Comment by jeizenga** [comment]
Nothing jumps out immediately to me, but maybe @xchang1 could comment.
