### ISSUE TITLE
When I try to convert the format of "new.vg>new.gfa", I always get the same error.

### ISSUE THREAD

**Issue by SUGARlx** [vgteam/vg#3952]
Hello,

When I try to convert the format of "new.vg>new.gfa", I always get the same error.

This is my script:
vg view -g BPS1149.vg > BPS1149.gfa

This is my error report:
[E::bgzf_read_block] Failed to read BGZF block data at offset 1465845050 expected 14182 bytes; hread returned 11975
terminate called after throwing an instance of 'std::runtime_error'
what():  [vg::io::MessageIterator] obsolete, invalid, or corrupt input at message 96059333933943 group 96059333933939
ERROR: Signal 6 occurred. VG has crashed. Visit  https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_RhuEV5/stacktrace.txt
Please include the stack trace file in your bug report!

I would like to ask what caused this? How should I solve this error?  

Thank you!

**Comment by jeizenga** [comment]
There's something wrong with `BPS1149.vg`, but it's hard to say what without knowing how you made it. It would be more useful to see the earlier steps in your script than this one.

**Comment by SUGARlx** [comment]
Thank you very much for your reply！

I use Sniffles2 to call SV. However, the sniffles result shows that the insertion site of INS is 'N’, which I mentioned in the question "error: [VG:: constructor] variant/reference sequence mismatch: n vs POS: 34014: t; do your VCF and FASTA coordinates match? It is also mentioned in #3744 ". In order to solve this error, I extracted all the INS positions in the sniffles results and changed their corresponding reference genome positions to ’N’ , so I was able to successfully construct' BPS1149.vg'.  

Maybe that's the reason?

**Comment by SUGARlx** [comment]
Hello, it seems that it is still the format problem of Sniffles2? 

I tried to recreate ‘BPS1149.vg’ again, but' warning' kept appearing.

This is my script:
vg construct -v BPS1149.vcf -r BPS1149_ref.fa > BPS1149.vg

This is my warning report:
warning:[vg::Constructor] Unsupported variant allele "<DEL>"; Skipping variant(s) A01	5554	Sniffles2.DEL.2391S0	N	<DEL>	59	PASS	AF=1.000;COVERAGE=24,23,23,21,21;END=5610;STDEV_LEN=0.289;STDEV_POS=0.389;STRAND=+-;SUPPORT=22;SVLEN=-56;SVTYPE=DEL;PRECISE !
warning:[vg::Constructor] Unsupported variant allele "<INV>"; Skipping variant(s) A01	972313	Sniffles2.INV.5404S0	N	<INV>	59	PASS	AF=0.972;COVERAGE=16,0,22,0,20;END=1051116;STDEV_LEN=2.587;STDEV_POS=4.159;STRAND=+-;SUPPORT=35;SVLEN=78803;SVTYPE=INV;PRECISE !
warning:[vg::Constructor] Unsupported variant allele "<INS>"; Skipping variant(s) A01	4901674	Sniffles2.INS.1C5S0	N	<INS>	60	GT	AF=0.194;COVERAGE=35,32,31,31,32;END=4901674;STDEV_LEN=14.213;STDEV_POS=3.742;STRAND=+-;SUPPORT=6;SUPPORT_LONG=0;SVLEN=445;SVTYPE=INS;PRECISE !
warning:[vg::Constructor] Unsupported variant allele "<DUP>"; Skipping variant(s) A01	28985108	Sniffles2.DUP.53CCS0	N	<DUP>	52	PASS	AF=1.000;COVERAGE=4,4,24,0,0;END=29035126;STDEV_LEN=6.833;STDEV_POS=0.886;STRAND=+-;SUPPORT=14;SVLEN=50018;SVTYPE=DUP;PRECISE !

**Comment by jeizenga** [comment]
Can you share the input FASTA and VCF?

**Comment by SUGARlx** [comment]
Thank you very much for your reply !


I extracted the first 10000 lines of vcf file and the whole  fasta file, and uploaded them to the attachment of this email. 🔗







| |
刘璇 202122582017793
|
|
***@***.***
|


---- Replied Message ----
| From | Jordan ***@***.***> |
| Date | 05/12/2023 00:37 |
| To | ***@***.***> |
| Cc | Xuan ***@***.***> ,
***@***.***> |
| Subject | Re: [vgteam/vg] When I try to convert the format of "new.vg>new.gfa", I always get the same error. (Issue #3952) |

Can you share the input FASTA and VCF?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| cotton_gen_Gossypium_hirsutum_AD1_TM-1_UTX_v2.1_Ghirsutum_527.fa |
| |
| (2.17GB,2023年5月28日 13:4 到期) |
| |
| 下载 |
| |
| |
|
| |
| |
|
| |
| BPS1149_try.vcf |
| |
| (11.4MB,2023年5月28日 12:38 到期) |
| |
| 下载 |
| |
| |

**Comment by jeizenga** [comment]
Sorry for the lack of response. I did not get the attachments. I don't think the GitHub email interface supports attachments. You can email them directly to me at joeizeng@gmail.com though.

**Comment by SUGARlx** [comment]
Hello, I re-sent it to your personal email, please check it, thank you very much.😄😄😄

**Comment by SUGARlx** [comment]
Hello, have you received the vcf and fasta files successfully?😄😄😄

**Comment by jeizenga** [comment]
Yes, I did receive them. I believe the reason is that your `.vg` file is either truncated or completely empty (you could check its file size with `ls -l` to confirm). The `vg construct` command errors out because Sniffles2 has produced non-conformant VCF files where the reference allele doesn't match the reference sequence. 

In fact, this problem was previously reported here: https://github.com/vgteam/vg/issues/3744. The conversation on that issue indicates that we have reported the problem to the Sniffles2 developers.

I'm going to close this issue on account of the fact that it's actually an upstream problem. Hopefully it gets fixed soon though!
