### ISSUE TITLE
vg giraffe alignment target end is beyond node length

### ISSUE THREAD

**Issue by ASLeonard** [vgteam/vg#3996]
**1. What were you trying to do?**
Hi,
This is all being run with `v1.48.0 "Gallipoli"`.

I'm aligning short reads with `vg giraffe` to a `pggb` gfa (passing the index components as well as `--named-coordinates --interleaved -o gaf`). The command ends without an error, and many alignment records look reasonable, but some appear to have incorrect target start/end coordinates. I believe I saw a similar error reported here before but can't find it now.

Here is an example, where the node "1346224" is indeed 1183 bp. The alignment for the second read states the target start is 646 and target end is 1482, but does not appear to traverse another node, and so the target end is *beyond* the end of the only node. This seems to mess up downstream tools like [gafpack](https://github.com/ekg/gafpack) since the "coverage" being attributed to this read is much larger than possible with a 101bp read that theoretically aligns perfectly.

```
HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/1    101     0       101     +       <1346224        1183    244     663     101     419     60      AS:i:111        bq:Z:<==><==>=<<<=>;<??;<???=<>=>?==>>:>=<<=<:<>;><=><=>=<>>><;<?=>??<=<>==<>==>><>=>==<>=<>=>?==<>>><<=::      cs:Z::101       dv:f:0  fn:Z:HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/2       pd:b:1
HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/2    101     0       101     +       >1346224        1183    646     1482    101     836     60      AS:i:111        bq:Z:;;;;;:>=<:>==<<=<<=====<>>>:;<<========<<==>=>>==>>?<==<<><=<<;>==<==<<><>==<=>====>>;=<<<;;;=;;:=;;3      cs:Z::101       dv:f:0  fp:Z:HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/1       pd:b:1
```

This happens on other nodes as well
```
HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/1     101     0       101     +       <1348296        2109    810     1803    101     993     60      AS:i:111        bq:Z:<;<:;;<;<<=<<<>=>>>>>=<<=>==<<=<>==<=<<><=<>>=<<>==<<>=<>>>==>=>;>>=<<<<=<<==?=><=>;>><;<=<>=<<>=<<<;      cs:Z::101       dv:f:0  fn:Z:HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/2        pd:b:1
HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/2     101     0       101     +       >1348296        2109    1055    2307    101     1252    60      AS:i:111        bq:Z:;;;3<<=<;<===>:<<<==<<>==<><><=<>=<<====<<<=>===>====>=<===>;>====<><=><=><<<<===>:==;>=<<;>=<<<<;;9<      cs:Z::101       dv:f:0  fp:Z:HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/1        pd:b:1
```

Is this expected behaviour where exact start/end is approxiamte or should that be accurate?

The reads are public, but the graph is not yet public but I can share it if helpful.

Best,
Alex

**Comment by glennhickey** [comment]
This does seem broken .  Can you please share the GAM output of one of these read pairs (either attach the gam or paste the output of `vg view -a` on it? That should be enough to at least start trying to debug this.

**Comment by ASLeonard** [comment]
here is the `vg view -a` output for both pairs of reads.

```
{"annotation": {"last_placed_stage": "none", "last_placed_stage_0bp": "none", "mapq_explored_cap": 115.9433658243543, "mapq_uncapped": 2147483647, "proper_pair": true, "secondary_scores": [111]}, "fragment_next": {"name": "HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/2"}, "identity": 1.0, "mapping_quality": 60, "name": "HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/1", "path": {"mapping": [{"edit": [{"from_length": 101, "to_length": 101}], "position": {"is_reverse": true, "name": "1346224", "offset": "244"}, "rank": "1"}]}, "quality": "GxwcHRscHB0cGxsbHB0aGx4eGhseHh4cGx0cHR4cHB0dGR0cGxscGxkbHRodGxwdGxwdHBsdHR0bGhseHB0eHhscGx0cHBsdHBwdHRsdHB0cHBsdHBsdHB0eHBwbHR0dGxscGRk=", "score": 111, "sequence": "AAGATTCTCCCAGACAAACAAAAGCTGAAGGAACTCATCACAACTAGATCTGCTTTACAAGAAATGCTGTAAGGAATTCTTCAAGCTGAAGTAAAAGGACA", "time_used": 2.4122999999999999e-5}
{"annotation": {"last_placed_stage": "none", "last_placed_stage_0bp": "none", "mapq_explored_cap": 84.86945831242906, "mapq_uncapped": 2147483647, "proper_pair": true, "secondary_scores": [111, 51]}, "fragment_prev": {"name": "HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/1"}, "identity": 1.0, "mapping_quality": 60, "name": "HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/2", "path": {"mapping": [{"edit": [{"from_length": 101, "to_length": 101}], "position": {"name": "1346224", "offset": "646"}, "rank": "1"}]}, "quality": "GhoaGhoZHRwbGR0cHBsbHBsbHBwcHBwbHR0dGRobGxwcHBwcHBwcGxscHB0cHR0cHB0dHhscHBsbHRscGxsaHRwcGxwcGxsdGx0cHBscHRwcHBwdHRocGxsbGhoaHBoaGRwaGhI=", "score": 111, "sequence": "ATATACTTACTTCCAGCAGTGTGTTTTACATTTTTGTGTATGGAGAAGGAAATGGCAATCCACTCCAGTATTCTGGCCTGGAGAATTCCATGGATAGAGGA", "time_used": 4.9747999999999999e-5}
{"annotation": {"last_placed_stage": "none", "last_placed_stage_0bp": "none", "mapq_explored_cap": 132.58618252056158, "mapq_uncapped": 2147483647, "proper_pair": true, "secondary_scores": [111]}, "fragment_next": {"name": "HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/2"}, "identity": 1.0, "mapping_quality": 60, "name": "HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/1", "path": {"mapping": [{"edit": [{"from_length": 101, "to_length": 101}], "position": {"is_reverse": true, "name": "1348296", "offset": "810"}, "rank": "1"}]}, "quality": "GxobGRoaGxobGxwbGxsdHB0dHR0dHBsbHB0cHBsbHBsdHBwbHBsbHRscGx0dHBsbHRwcGxsdHBsdHR0cHB0cHRodHRwbGxsbHBsbHBweHB0bHB0aHR0bGhscGx0cGxsdHBsbGxo=", "score": 111, "sequence": "ATACACACATGTATTCTTTTTCATCTCCATCCTTTAGCAATGCTTCCCTGTATTGCTTTCCTGACTTCATATGCAGCTCTAGACTTACAGCTCATTGCAGA", "time_used": 2.7061999999999999e-5}
{"annotation": {"last_placed_stage": "none", "last_placed_stage_0bp": "none", "mapq_explored_cap": 103.95806648149519, "mapq_uncapped": 2147483647, "proper_pair": true, "secondary_scores": [111]}, "fragment_prev": {"name": "HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/1"}, "identity": 1.0, "mapping_quality": 60, "name": "HWI-ST1194:48:D0YKDACXX:5:1113:3125:28661/2", "path": {"mapping": [{"edit": [{"from_length": 101, "to_length": 101}], "position": {"name": "1348296", "offset": "1055"}, "rank": "1"}]}, "quality": "GhoaEhsbHBsaGxwcHB0ZGxsbHBwbGx0cHBsdGx0bHBsdHBsbHBwcHBsbGxwdHBwcHRwcHBwdHBscHBwdGh0cHBwcGx0bHB0bHB0bGxsbHBwcHRkcHBodHBsbGh0cGxsbGxoaGBs=", "score": 111, "sequence": "GCCGGGGCATGTGACCCAGGCCTGGCTGATCCTTATGTTCCATCTGTCTGGTTTCAGTGACTGGTTCTAGATGAGCATGTGACTTAAGCCAAGTCAGCACT", "time_used": 2.1648e-5}
```

**Comment by glennhickey** [comment]
Thanks.  I didn't pick up on this before, but this must be directly related to `--named-coordinates`.  Looking at the code, it seems that there should be support (in theory) for `--named-coordinates` with GAF output, but something is obviously going wrong.  @adamnovak I think you did the GAF translation -- is this something you can check?

**Comment by ASLeonard** [comment]
I was looking into the details a bit more, using `--show-work`,

```
T0:     Extensions:
T0:             Read 0-101 with 0 mismatches:
T0:     gapless extension group 0 is good enough (score=111)
T0:     Produced alignment directly from full length gapless extension 0
T0:     Produced alignment from gapless extension group 0 with score 111: 
...
```
And reformatted the path information a bit. The alignment does span 101 bp (correct length of this read), and does seem contiguous on the graph path `<39438<39437<39436<39435`, so I guess the issue is somehow in translating the starting offset of 21 from node 39438 and ending only 26 bases into node 39435, and how that relates to the GFA-named coordinate.

```
path:
  mapping:
    - edit:
        - from_length: 11
          to_length: 11
      position:
        is_reverse: true
        node_id: '39438'
        offset: '21'
      rank: '1'
    - edit:
        - from_length: 32
          to_length: 32
      position:
        is_reverse: true
        node_id: '39437'
      rank: '2'
    - edit:
        - from_length: 32
          to_length: 32
      position:
        is_reverse: true
        node_id: '39436'
      rank: '3'
    - edit:
        - from_length: 26
          to_length: 26
      position:
        is_reverse: true
        node_id: '39435'
      rank: '4'
```

**Comment by adamnovak** [comment]
OK, so in GAF, read `HWI-ST1194:48:D0YKDACXX:5:2203:10041:97792/2` claims to run 646-1482 on GFA node `"1346224"`. But this is impossible because the node is not that long.

In GAM, we have the read as a 101bp perfect match starting at 646 on GFA node `"1346224"`, which makes sense.

So it seems something might be going wrong with the GAF conversion? I'm not sure if I wrote it but I can see if I can work out what it is.

**Comment by adamnovak** [comment]
Unfortunately I can't exercise the gam-to-gaf conversion without the graph here. Is there a way I can get a copy of the graph @ASLeonard?

**Comment by adamnovak** [comment]
OK it looks like we have one test for the very fiddly GAF-conversion-and-node-to-named-segment-translation logic, and it tests just one little forward-strand example. So my logic for the conversion is probably just wrong; I bet adding more comprehensive tests will turn up the problem.

**Comment by adamnovak** [comment]
OK in https://github.com/vgteam/vg/commit/02fddf12bf7c32305890dc6b38d76a220ae90107 I think I have a test that triggers this, so I should be able to fix it without any more data files.

**Comment by ASLeonard** [comment]
I just checked with `v1.49.0` and got the same results, but here is a pretty minimal subgraph with 1 pair of reads that causes the same issue.
[reprex.tar.gz](https://github.com/vgteam/vg/files/11830748/reprex.tar.gz)

**Comment by ASLeonard** [comment]
You probably have more robust tests, but I tested #4004 with some other samples on the same GFA and they all have <=101 bp aligned for 101 bp reads, so this appears resolved.

Thanks for the quick fix!
