### ISSUE TITLE
Trying to make a spliced pangenome for RNAseq alignment

### ISSUE THREAD

**Issue by oakeley** [vgteam/vg#3999]
**1. What were you trying to do?**
I made a pangenome using cactus pangenome like this:
---
rm -rf js; source /da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/cactus_env/bin/activate; cactus-pangeno
me ./js cyno.txt --outDir /da/cbt/GX/oakeled1/genomes/cyno/S-210316-00677/pangenome --outName cyno-pg --reference Maca
ca_fascicularis_6.0.109 --vcf --giraffe --gfa --gbz
---
This works fine as a reference for aligning Illumina reads to. But I would like to align RNAseq reads so I tried to make a spliced reference using either the GTF or GFF3 file and either the "cyno-pg.gbz" or "cyno-pg.d2.gbz" generated by cactus-pangenome.
I also tried with and without the --use-hap-ref flag. The most recent command I tried was (but all failed the same way):

---
source /da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/cactus_env/bin/activate; vg rna -p -t 8 --transcripts /da/cbt/GX/oakeled1/genomes/cyno/S-210316-00677/GFF3/Macaca_fascicularis.Macaca_fascicularis_6.0.109.gff3 --gbz-format cyno-pg.gbz > cyno-spliced.pg
---

**2. What did you want to happen?**
I wanted a spliced pangenome graph to be made using the GFF3 or GTF annotations.

**3. What actually happened?**
"vg rna" failed

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```
Crash report for vg v1.48.0 "Gallipoli"
Stack trace (most recent call last):
#12   Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x5f0e3d, in _start
#11   Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x1ed71af, in __libc_start_main
#10   Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x5c0ade, in main
#9    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0xd3143b, in vg::subcommand::Su
bcommand::operator()(int, char**) const
#8    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0xc2cecc, in main_rna(int, char
**)
#7    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0xc2bf73, in std::__cxx11::basi
c_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)
[clone .isra.0]
#6    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x5bf3e0, in std::__throw_logic
_error(char const*)
#5    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x1e13228, in __cxa_throw
#4    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x1e130c6, in std::terminate()
#3    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x1e1305b, in __cxxabiv1::__ter
minate(void (*)())
#2    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x5bd66a, in __gnu_cxx::__verbo
se_terminate_handler() [clone .cold]
#1    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x5c0007, in abort
#0    Object "/da/cbt/GX/oakeled1/genomes/cyno/pangenome/cactus-bin-v2.6.0/bin/vg", at 0x149611b, in raise
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Please include this entire error log in your bug report!
```

**5. What data and command can the vg dev team use to make the problem happen?**
---
vg rna -p -t 8 --transcripts /da/cbt/GX/oakeled1/genomes/cyno/S-210316-00677/GFF3/Macaca_fascicularis.Macaca_fascicularis_6.0.109.gff3 --gbz-format cyno-pg.gbz > cyno-spliced.pg
---

**6. What does running `vg version` say?**

```
vg v1.48.0 "Gallipoli"
```

**Comment by jeizenga** [comment]
Are you able to share the data that led to this crash?

**Comment by brettChapman** [comment]
I'm getting the exact same crash

**Comment by jonassibbesen** [comment]
Hi, thanks for writing. I think I just found the issue. Please see my response to the same issue here: #3997
