### ISSUE TITLE
Defining personal genomes on a variation graph

### ISSUE THREAD

**Issue by inti** [vgteam/vg#40]
Hi, 
For some analyses, like Allelic Specific Expression, one wants to have a personal version of the reference. That is the reference modified to represent the known sequence of a individual. It seems this would be *trivial* with variation graphs if one has a set of variants for which a individual is hom/het. Question: is it possible to align the reads against a subset of the paths of the graph? like define a subset of the graph removing paths for alleles not present on a personal genome (it is hom at the site) and keeping only paths for het sites?
Thanks in advance

**Comment by ekg** [comment]
@inti I think this should be possible by annotating paths in the graph. These paths can be used to project alignments (`vg surject`) against the graph against a particular path. This subgraph could be a personal genome. Does this make sense?

**Comment by inti** [comment]
Yes, it does make sense. I just have not got chance to try it. I will have a chance soonish. Cheers, Inti

**Comment by adamnovak** [comment]
I'm going to close this because, while it's a cool project, it's not really a vg bug.

**Comment by edawson** [comment]
Hey @inti , if you've tried it out let us know - we'd like to hear a success story if you have one, and you can catch us [on gitter](https://gitter.im/vgteam/vg) if for some reason things didn't work!

**Comment by inti** [comment]
Thanks. I will try to get around to test it and I will let you know. Cheers, Inti
