### ISSUE TITLE
Retrieving alignment scores for multiple alignments with vg surject

### ISSUE THREAD

**Issue by gamerino** [vgteam/vg#4005]
Hello!

I'm trying to get multiple alignments with their corresponding **alignment scores** for paired-end reads against a pangenome using `vg giraffe`, and then `vg surject` to convert `gam` to `bam`. 

As a result, the generated `bam` file contains multiple alignments for paired-end reads but alignment scores **AS:XX** are not reported. 

Could you please provide an option for including them in the alignment section of `sam/bam` files?

For generating pangenome alignments I'm using the following command line:

```
vg giraffe -M 10 -x ${panIdxPath}/${panPre}.xg -g ${panIdxPath}/${panPre}.gg -H ${panIdxPath}/${panPre}.gbwt \
-L 2000 -m ${panIdxPath}/${panPre}.min -d ${panIdxPath}/${panPre}.dist -p -f ${fastq1} -f ${fastq2} -t 30 \
1> ${outPre}.gam --report-name ${log} 2> ${log}_run.log
```

For converting the `gam` file to `bam` file, I'm running:

```
vg surject -b -M -i -t 30 -x ${panIdxPath}/${panPre}.xg ${prefix}.gam 1> ${prefix}.bam
```

Thanks!

**Comment by jeizenga** [comment]
Hi @gamerino, I added alignment scores to `vg surject`'s output. You can access the new behavior by recompiling on the current master branch or else by waiting until our next release.

**Comment by gamerino** [comment]
Hi @jeizenga!

Thank you so much for this! 

I'll follow your suggestions and try again with the new output of `vg surject`.
