### ISSUE TITLE
Construct a pantranscriptome reference with two haplotypes from a single sample.

### ISSUE THREAD

**Issue by Juhyun-Kim-0203** [vgteam/vg#4009]
Hello,

I am trying to construct a graph reference for rpvg using two haplotypes from a single sample.

I created a GFA file from two haplotype from single sample with pggb. Then, I generated VCF file and graph.pg from the gfa file using vg deconstruct command line. I attempted to run vg rna or vg autoindex -w mpmap with this vcf and graph.pg, but I encountered the following error.
```

[IndexRegistry]: Checking for phasing in VCF(s).
error:[vg autoindex] Input is not sufficient to create indexes
Inputs
    GTF/GFF
    Reference FASTA
    VCF
are insufficient to create target index Haplotype-Transcript GBWT
```

I believe the error may be caused by the absence of heterogenous variants in the VCF file, making it impossible to phase the VCF file.
![image](https://github.com/vgteam/vg/assets/131193680/15fcd291-0507-484f-a75c-6f4708c5380f)

In this situation, is there any way to construct rna pantranscriptome reference using only two haplotype? or with only GFA file

Thank you

**Comment by jeizenga** [comment]
I believe we also interacted on [this Biostars question](https://www.biostars.org/p/9567968/#9568041), but I'm going to close this bug report as  This specific bug was fixed a while back in https://github.com/vgteam/vg/pull/3889. Users who encounter this issue should be able to resolve it by updating the VG version.
