### ISSUE TITLE
haplotype assgining

### ISSUE THREAD

**Issue by sdws1983** [vgteam/vg#4014]
Hi,

I am assigning node haplotypes according to the method mentioned in this issue #3668, but I found that nearly half of the nodes were not assigned to the corresponding haplotypes in the GBWT. What is the reason? 

My commands:
```
vg construct -f -S -a -C -R Chr10 -v Chr10.top-level.vcf.gz -r A.fasta -t 2 > chr10.vg
vg view -Vg chr10.vg > chr10.gfa

vg gbwt -x chr10.vg -v LAp.Chr10.top-level.vcf.gz -o x.gbwt
vg gbwt -x chr10.vg -E -o x.paths.gbwt
vg gbwt -m x.gbwt x.paths.gbwt -o x.combined.gbwt
vg gbwt -x chr10.vg x.combined.gbwt --gbz-format -g x.gbz
vg convert -Z -f x.gbz > chr10.hap.gfa
```

```
$ grep "^S" chr10.gfa |wc -l
13727994
$ grep "^S" chr10.hap.gfa |wc -l
5972365
```

Thanks!

Yumin

**Comment by jltsiren** [comment]
Is the VCF file phased, and how many haplotypes does it contain?

What do you get if you run the following commands with each GBWT:
```
vg gbwt -M graph.gbwt
hexdump -s 24 -n 16 graph.gbwt
```

A GBWT-based graph only contains the nodes used on at least one path. If you get much fewer nodes in the GBZ graph than in the original, it means that the remaining nodes are not used by any haplotype or the reference.

**Comment by sdws1983** [comment]
> Is the VCF file phased, and how many haplotypes does it contain?
> 
> What do you get if you run the following commands with each GBWT:
> 
> ```
> vg gbwt -M graph.gbwt
> hexdump -s 24 -n 16 graph.gbwt
> ```
> 

My vcf:
![image](https://github.com/vgteam/vg/assets/18738943/6ccf9d36-d668-453f-a1fa-f950308effef)


My outputs:
```
$ vg gbwt -M x.combined.gbwt 
8 paths with names, 8 samples with names, 8 haplotypes, 1 contigs with names
$ hexdump -s 24 -n 16 x.combined.gbwt 
0000018 0001 0000 0000 0000 f1f6 01a2 0000 0000
0000028
```

> A GBWT-based graph only contains the nodes used on at least one path. If you get much fewer nodes in the GBZ graph than in the original, it means that the remaining nodes are not used by any haplotype or the reference.

I checked some unassigned nodes and found that they were assigned to alt paths in the original vg

**Comment by jltsiren** [comment]
The alt paths you see are vg's internal representation of alternate alleles.

Your VCF fragment makes heavy use of `.` in the genotype fields. When GBWT construction encounters one, it falls back to the reference allele. My best guess at this point is that there are many variants where each haplotype has the reference allele, either explicitly (`0`) or implicitly (`.`). Because the alternate alleles exist in the VCF, the graph built with `vg construct` contains the corresponding nodes.  But because no haplotype uses them, the nodes are not included in the GBWT-based graph.

**Comment by sdws1983** [comment]
> The alt paths you see are vg's internal representation of alternate alleles.
> 
> Your VCF fragment makes heavy use of `.` in the genotype fields. When GBWT construction encounters one, it falls back to the reference allele. My best guess at this point is that there are many variants where each haplotype has the reference allele, either explicitly (`0`) or implicitly (`.`). Because the alternate alleles exist in the VCF, the graph built with `vg construct` contains the corresponding nodes. But because no haplotype uses them, the nodes are not included in the GBWT-based graph.

Thank you for your valuable suggestions. I tried to delete the above sites without alt alleles, and the result was much better. 

But I still found that a small number of nodes failed to be assigned to haplotypes, such as the following:

<img width="1038" alt="image" src="https://github.com/vgteam/vg/assets/18738943/57f7cf7f-577a-4af0-b812-39ee6a1c81d2">

**Comment by jltsiren** [comment]
A small number of nodes with no haplotypes is normal, at least in regions with overlapping variants. Graph construction with `vg construct` and GBWT construction with `vg gbwt` interpret the VCF in slightly different ways in such regions, and nobody has bothered to deal with the situation.
