### ISSUE TITLE
How to merge  GBZ indexes

### ISSUE THREAD

**Issue by gaochenx** [vgteam/vg#4029]
I built the pan-genome using minigraph and got the GFA file for each chromosome.
Then I used vg GWBT to convert the gfa file to gbz format file.
 But I don't know how to combine all the gbz indexes.
Or other ways to combine the gfa chromosomes
 Can you help me

**Comment by glennhickey** [comment]
You can combine gfas with `vg combine`:

```
vg combine chr1.gfa chr2.gfa chr3.gfa > genome.gfa
```

**Comment by gaochenx** [comment]
Thank you! It is resolved now.
