### ISSUE TITLE
Does “vg mod” change the graph

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4033]
**PLEASE DO NOT MAKE SUPPORT REQUESTS HERE**

Please the Biostars forum instead:

https://www.biostars.org/p/new/post/?tag_val=vg

Now I have a graph named "chr21.vg", then I use "vg mod -X 32 chr21.vg > chr21.mod32.vg" and "vg index -g chr21.mod32.gcsa chr21.mod32.vg" to create the gcsa index for it. 

My problem is that if I want to map reads to the graph, which graph should I map to, "chr21.vg" or "chr21.mod32.vg", considering I'll use the "vg pack" information later.

**Comment by glennhickey** [comment]
`vg mod` does indeed change the graph (mod here is short for modify). In this case you would have to map to the `chr21.mod32.vg` if you are using `chr21.mod32.gcsa`.
