### ISSUE TITLE
vg 1.50 -  Reference path must have a sample name

### ISSUE THREAD

**Issue by colindaven** [vgteam/vg#4043]
**1. What were you trying to do?**

Run  an internal nextflow pipeline which creates vg indices from a  odgi->GFA and maps to them with giraffe.
Odgi files were created in a previous pipeline with minigraph-cactus.

**2. What did you want to happen?**

Successful conversion and mapping, as previously with vg1.48 I believe

**3. What actually happened?**
`
    what():  Reference path must have a sample name`

Presumably the vg mod or more likely vg convert failed. I probably need to add sample path information, but how - by which vg command, and where ?

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```

Error executing process > 'make_indices (AT_Col0.gfa)'

Caused by:
  Process `make_indices (AT_Col0.gfa)` terminated with an error exit status (134)

Command executed:

  vg mod -t 8 -X 1000 AT_Col0.gfa > AT_Col0.gfa.fixed.gfa
  vg convert -t 8 -x -g AT_Col0.gfa.fixed.gfa > AT_Col0.gfa.xg

  vg gbwt --num-threads 8 --gbz-format -G AT_Col0.gfa.fixed.gfa -g AT_Col0.gfa.gbz
  vg gbwt --num-threads 8 -g AT_Col0.gfa.gg  -G AT_Col0.gfa.fixed.gfa -o AT_Col0.gfa.gbwt   

  vg snarls -t 8 -T AT_Col0.gfa.xg > AT_Col0.gfa.snarls
  vg index -t 8 -j AT_Col0.gfa.dist AT_Col0.gfa.gbz
  vg minimizer -t 8 -d AT_Col0.gfa.dist AT_Col0.gfa.gbz -o AT_Col0.gfa.min

Command exit status:
  134

Command output:
  (empty)

Command error:
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Reference path must have a sample name
  ━━━━━━━━━━━━━━━━━━━━
  Crash report for vg v1.50.0 "Monopoli"

```

**5. What data and command can the vg dev team use to make the problem happen?**

As above.

**6. What does running `vg version` say?**

```
vg version v1.50.0 "Monopoli"
Compiled with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 on Linux
Linked against libstd++ 20230528
Built by hickey@boreale

```

**Comment by adamnovak** [comment]
I think this is a bug. A path `ref#contig` has a sample name `ref` and a contig name `contig`. I bet when I touched the name regex in https://github.com/vgteam/libhandlegraph/pull/91 to fix attempts to parse non-numerical haplotypes, I broke this, maybe for cases where the contig is numerical.

**Comment by glennhickey** [comment]
OK, thanks for looking.  My reading was that the sky was falling down because the reference path didn't have a HAPLOTYPE, which SENSE_REFERENCE is required to have. 

>  SENSE_REFERENCE: a part of a reference assembly. Has a "sample" name, a
>    "locus" name, and a haplotype number.
 
 https://github.com/vgteam/libhandlegraph/blob/master/src/include/handlegraph/path_metadata.hpp

and that `ref#contig`, despite working fine all this time, wasn't valid.  

In any case, this issue seems to apply to any (not just numeric) contig name.

**Comment by adamnovak** [comment]
OK, I was right, I broke this in that libhandlegraph PR.

This should be fixed and under test in https://github.com/vgteam/vg/pull/4045. We might want to do a patch release?

**Comment by glennhickey** [comment]
Yeah, I think the patch release may be a good idea simply because the problems with the v1.1 HPRC graphs it can cause...

**Comment by colindaven** [comment]
Thanks, the same datasets are now not causing this problem with vg1.50.1. 
Indexing ran successfully.

```

[0e/431611] Submitted process > make_indices (AT_Col0.gfa)
[80/7ec4db] Submitted process > giraffe_bam (SRR2183387_Arabidopsis_1-8_R1.fastq)
[6d/89d098] Submitted process > giraffe (SRR2183387_Arabidopsis_1-8_R1.fastq)

```
