### ISSUE TITLE
Alignment mapping qualities not robust

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#405]
No alignments are found when aligning the NA12878 reads to this NA12878 BRCA2 graph. See the GAM and indexes in the attached file.

[snp1kg-issue.tar.gz](https://github.com/vgteam/vg/files/330676/snp1kg-issue.tar.gz)

Some of these reads ought to be consistent and survive the -a filter.

`vg map -f NA12878.bam.fq -i -x graph.vg.xg -g graph.vg.gcsa -J | less` produces mapped alignments.

`vg map -f NA12878.bam.fq -i -a -x graph.vg.xg -g graph.vg.gcsa -J | less` produces only unmapped alignments.

**Comment by adamnovak** [comment]
It seems to work if I pass a `-W 300` along with `-a`. @jeizenga what is the behavior supposed to be when the fragment size is unspecified?

**Comment by ekg** [comment]
My objective was to always require the specification of fragment size when
mapping paired ends. To improve this we should estimate based on a sampling
of mappings. If we don't have an estimated fragment size we might as well
map single end.

**Comment by jeizenga** [comment]
@ekg Yeah, I think this is something that happened when we were both working on paired end mapping at the same time. I guess I didn't catch it before my last PR. The PR above fixes it though.

**Comment by glennhickey** [comment]
Something's still up.  While the alignments seem good now, only a handful
have mapping qualities (or at least non-zero mapping qualities).

**Comment by jeizenga** [comment]
Hmm. I don't see that on my local build. Is the data set you're using small enough to post / email me?

**Comment by adamnovak** [comment]
OK, it looks like the problem now is the -U option for always rescuing, which is resulting in mapped reads coming out with no map qualities.

**Comment by adamnovak** [comment]
OK I have code to fix this. I am running it now, replacing the old alignments.
