### ISSUE TITLE
GCSA index building always fails. Is there any other way to support long reads mapping

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4054]
When I use `vg map` to map `long reads` to graph, there are major problems with `gcsa index` construction: `PathGraphBuilder::write(): Size limit exceeded, construction aborted`. It seems to be running out of storage space, but I only use the chr21 graph（900MB） and give it a few terabytes of space to construct gcsa index.
So is there any other way to support long reads mapping without too many resources?

**Comment by jeizenga** [comment]
Did you use `vg prune` to reduce the complexity of the graph? In practice, this is almost always necessary. There are details on how to do it manually [here](https://github.com/vgteam/vg/wiki/Index-Construction#complex-graph), but most users will use `vg autoindex --workflow map` instead. The `autoindex` subcommand takes care of details like pruning on its own, so all you have to do is provide common input formats like VCF, FASTA, and GFA. 

That said, `vg map` is not a great mapping algorithm for long reads. Currently, the most capable long read graph mapping tool is GraphAligner. `vg giraffe` has some experimental features for mapping accurate long reads (PacBio HiFi, ONT, R10 duplex), but they are still under development.
