### ISSUE TITLE
gaf file converted to gam file, and all sequence fields are all "NNNN"

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4057]
![image](https://github.com/vgteam/vg/assets/74750242/9df64753-ffa4-4063-baa7-2e92c6bc8905)
I use GraphAligner to align some reads to a chr21 graph and get the `GAF` file. Then I use `vg convert -F gaf_file graph_file > aln.gam` to convert the `gaf` format to the `gam` format. But why all the `"sequence"` fields that represent variation are all `"N"` ?

**Comment by glennhickey** [comment]
If your GAF file doesn't contain the read's sequence, then there is not enough information for vg to fill in this information and it just puts N as a placeholder.

Here I'm guessing GraphAligner is outputting `cg` cigar strings which just contain `M`, `D`, `I` characters and their respective sizes, without specifying the bases invovled in each operation.
