### ISSUE TITLE
vcf call result

### ISSUE THREAD

**Issue by gaochenx** [vgteam/vg#4064]
**1. What were you trying to do?**
I want to compare VCFs for multiple samples,  so  I use -z -a when using vg call

**2. What did you want to happen?**

**3. What actually happened?**

I found that the number of rows of VCF for each sample is not the same， And in some rows, alt has only one genotype in some samples and is multi allele in others

A01        312481  >18733>18738    TT      T,TTT   10.0905 lowdepth

A01        312482  >18733>18738    T       TT      159.905 PASS

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**

vg version v1.47.0 "Ostuni"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon

**Comment by gaochenx** [comment]
D13        723660  >120807185>120807188    A       AAA     120.028 PASS
.D13        723660  >120807185>120807188    A       AAA,AA  10.7915 lowdepth

**Comment by glennhickey** [comment]
To fix the number of rows, add -A.  For the different alleles, the problem
is that for big sites there can be too many alleles to count, so it only
outputs alleles that are at all supported by reads.
