### ISSUE TITLE
Transcriptome::project_transcript_gbwt error during vg rna

### ISSUE THREAD

**Issue by jjuhyunkim** [vgteam/vg#4066]
**1. What were you trying to do?**
construct pantranscriptome graph reference with the gbz files from minigraph-cactus

**2. What did you want to happen?**
make the graph reference for transcriptome analysis.

**3. What actually happened?**
I encountered an error saying `vg: src/transcriptome.cpp:1670: std::__cxx11::list<vg::EditedTranscriptPath> vg::Transcriptome::project_transcript_gbwt(const vg::Transcript&, const gbwt::GBWT&, float) const: Assertion `haplotype_id_index_it->second.second < exon_idx' failed.`

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
[vg rna] Parsing graph file ...
[vg rna] Parsing haplotype GBWT index file ...
[vg rna] Graph and GBWT index parsed in 1.71296 seconds, 2.09251 GB
[vg rna] Adding transcript splice-junctions and exon boundaries to graph ...
        Parsed 320068 transcripts
        Constructed 320068 reference transcript paths
        Updated graph with reference transcript paths
[vg rna] Transcripts parsed and graph updated in 478.66 seconds, 36.4734 GB
[vg rna] Projecting transcripts to haplotypes ...
        Parsed 320068 transcripts
vg: src/transcriptome.cpp:1670: std::__cxx11::list<vg::EditedTranscriptPath> vg::Transcriptome::project_transcript_gbwt(const vg::Transcript&, const gbwt::GBWT&, float) const: Assertion `haplotype_id_index_it->second.second < exon_idx' failed.
━━━━━━━━━━━━━━━━━━━━
Crash report for vg v1.50.1 "Monopoli"
Stack trace (most recent call last) in thread 2962066:
#11   Object "", at 0xffffffffffffffff, in 
#10   Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x21472f3, in __clone
#9    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x20a09ba, in start_thread
#8    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x2018943, in execute_native_thread_routine
#7    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x13d78a7, in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (vg::Transcriptome::*)(std::__cxx11::list<vg::CompletedTranscriptPath, std::allocator<vg::CompletedTranscriptPath> >*, spp::sparse_hash_map<handlegraph::handle_t, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> >, spp::spp_hash<handlegraph::handle_t>, std::equal_to<handlegraph::handle_t>, spp::libc_allocator<std::pair<handlegraph::handle_t const, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> > > > >*, std::mutex*, int, std::vector<vg::Transcript, std::allocator<vg::Transcript> > const&, gbwt::GBWT const&, bdsg::PositionOverlay const&, bool, float), vg::Transcriptome*, std::__cxx11::list<vg::CompletedTranscriptPath, std::allocator<vg::CompletedTranscriptPath> >*, spp::sparse_hash_map<handlegraph::handle_t, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> >, spp::spp_hash<handlegraph::handle_t>, std::equal_to<handlegraph::handle_t>, spp::libc_allocator<std::pair<handlegraph::handle_t const, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> > > > >*, std::mutex*, unsigned long, std::reference_wrapper<std::vector<vg::Transcript, std::allocator<vg::Transcript> > const>, std::reference_wrapper<gbwt::GBWT const>, std::reference_wrapper<bdsg::PositionOverlay const>, bool, float> > >::_M_run()
#6    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x13ceb29, in vg::Transcriptome::project_haplotype_transcripts_callback(std::__cxx11::list<vg::CompletedTranscriptPath, std::allocator<vg::CompletedTranscriptPath> >*, spp::sparse_hash_map<handlegraph::handle_t, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> >, spp::spp_hash<handlegraph::handle_t>, std::equal_to<handlegraph::handle_t>, spp::libc_allocator<std::pair<handlegraph::handle_t const, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> > > > >*, std::mutex*, int, std::vector<vg::Transcript, std::allocator<vg::Transcript> > const&, gbwt::GBWT const&, bdsg::PositionOverlay const&, bool, float)
#5    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x13cb9d1, in vg::Transcriptome::project_transcript_gbwt[abi:cxx11](vg::Transcript const&, gbwt::GBWT const&, float) const
#4    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x206f1c5, in __assert_fail
#3    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x5e5053, in __assert_fail_base.cold
#2    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x5e512b, in abort
#1    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x20757d5, in raise
#0    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x20a21dc, in __pthread_kill
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Please include this entire error log in your bug report!

```

**5. What data and command can the vg dev team use to make the problem happen?**
vg rna -p -o -n ${GTF} -l ./haplotype.gbwt  -r -e -d -b pantranscriptome.gbwt -f pantranscriptome.fa -i pantranscriptome.txt graph.pg > pantranscript.pg

**6. What does running `vg version` say?**

```
Crash report for vg v1.50.1 "Monopoli"
```

**Comment by Juhyun-Kim-0203** [comment]
> **1. What were you trying to do?** construct pantranscriptome graph reference with the gbz files from minigraph-cactus
> 
> **2. What did you want to happen?** make the graph reference for transcriptome analysis.
> 
> **3. What actually happened?** I encountered an error saying `vg: src/transcriptome.cpp:1670: std::__cxx11::list<vg::EditedTranscriptPath> vg::Transcriptome::project_transcript_gbwt(const vg::Transcript&, const gbwt::GBWT&, float) const: Assertion `haplotype_id_index_it->second.second < exon_idx' failed.`
> 
> **4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**
> 
> ```
> [vg rna] Parsing graph file ...
> [vg rna] Parsing haplotype GBWT index file ...
> [vg rna] Graph and GBWT index parsed in 1.71296 seconds, 2.09251 GB
> [vg rna] Adding transcript splice-junctions and exon boundaries to graph ...
>         Parsed 320068 transcripts
>         Constructed 320068 reference transcript paths
>         Updated graph with reference transcript paths
> [vg rna] Transcripts parsed and graph updated in 478.66 seconds, 36.4734 GB
> [vg rna] Projecting transcripts to haplotypes ...
>         Parsed 320068 transcripts
> vg: src/transcriptome.cpp:1670: std::__cxx11::list<vg::EditedTranscriptPath> vg::Transcriptome::project_transcript_gbwt(const vg::Transcript&, const gbwt::GBWT&, float) const: Assertion `haplotype_id_index_it->second.second < exon_idx' failed.
> ━━━━━━━━━━━━━━━━━━━━
> Crash report for vg v1.50.1 "Monopoli"
> Stack trace (most recent call last) in thread 2962066:
> #11   Object "", at 0xffffffffffffffff, in 
> #10   Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x21472f3, in __clone
> #9    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x20a09ba, in start_thread
> #8    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x2018943, in execute_native_thread_routine
> #7    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x13d78a7, in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (vg::Transcriptome::*)(std::__cxx11::list<vg::CompletedTranscriptPath, std::allocator<vg::CompletedTranscriptPath> >*, spp::sparse_hash_map<handlegraph::handle_t, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> >, spp::spp_hash<handlegraph::handle_t>, std::equal_to<handlegraph::handle_t>, spp::libc_allocator<std::pair<handlegraph::handle_t const, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> > > > >*, std::mutex*, int, std::vector<vg::Transcript, std::allocator<vg::Transcript> > const&, gbwt::GBWT const&, bdsg::PositionOverlay const&, bool, float), vg::Transcriptome*, std::__cxx11::list<vg::CompletedTranscriptPath, std::allocator<vg::CompletedTranscriptPath> >*, spp::sparse_hash_map<handlegraph::handle_t, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> >, spp::spp_hash<handlegraph::handle_t>, std::equal_to<handlegraph::handle_t>, spp::libc_allocator<std::pair<handlegraph::handle_t const, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> > > > >*, std::mutex*, unsigned long, std::reference_wrapper<std::vector<vg::Transcript, std::allocator<vg::Transcript> > const>, std::reference_wrapper<gbwt::GBWT const>, std::reference_wrapper<bdsg::PositionOverlay const>, bool, float> > >::_M_run()
> #6    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x13ceb29, in vg::Transcriptome::project_haplotype_transcripts_callback(std::__cxx11::list<vg::CompletedTranscriptPath, std::allocator<vg::CompletedTranscriptPath> >*, spp::sparse_hash_map<handlegraph::handle_t, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> >, spp::spp_hash<handlegraph::handle_t>, std::equal_to<handlegraph::handle_t>, spp::libc_allocator<std::pair<handlegraph::handle_t const, std::vector<vg::CompletedTranscriptPath*, std::allocator<vg::CompletedTranscriptPath*> > > > >*, std::mutex*, int, std::vector<vg::Transcript, std::allocator<vg::Transcript> > const&, gbwt::GBWT const&, bdsg::PositionOverlay const&, bool, float)
> #5    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x13cb9d1, in vg::Transcriptome::project_transcript_gbwt[abi:cxx11](vg::Transcript const&, gbwt::GBWT const&, float) const
> #4    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x206f1c5, in __assert_fail
> #3    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x5e5053, in __assert_fail_base.cold
> #2    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x5e512b, in abort
> #1    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x20757d5, in raise
> #0    Object "/gpfs/gsfs11/users/kimj75/anaconda3/envs/pacbioDNA/bin/vg", at 0x20a21dc, in __pthread_kill
> ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
> Please include this entire error log in your bug report!
> ```
> 
> **5. What data and command can the vg dev team use to make the problem happen?** vg rna -p -o -n ${GTF} -l ./haplotype.gbwt -r -e -d -b pantranscriptome.gbwt -f pantranscriptome.fa -i pantranscriptome.txt graph.pg > pantranscript.pg
> 
> **6. What does running `vg version` say?**
> 
> ```
> Crash report for vg v1.50.1 "Monopoli"
> ```

**Comment by Juhyun-Kim-0203** [comment]
I encountered the same error when I use gbz file directly

`vg rna -p -o -n ${GTF} -r -e -d -b pantranscriptome.gbwt -f pantranscriptome.fa -i pantranscriptome.txt -z graph.gbz > splicing.pg
`

**Comment by jeizenga** [comment]
Are you able to share the inputs that you encountered the error on? It would also be helpful to see the full sequence of commands that led to the crash.

**Comment by jjuhyunkim** [comment]
Yes sure! I will email you

**Comment by jeizenga** [comment]
I believe this specific issue has been resolved based on email correspondence. Feel free to re-open if I've misinterpreted.

**Comment by jjuhyunkim** [comment]
Interestingly, I was able to project the transcript annotation onto a graph, except for only one region : the short arms of chr14. I believe this issue is caused by repeats and the tangles generated as a result of those repeats. Consequently, I was able to construct my transcriptome graph by removing several genes within the large tangles from GTF file, using the coordinates of the start and end sites. 
<img width="720" alt="image" src="https://github.com/vgteam/vg/assets/131193680/1e500a15-f075-440c-b566-9544f7fca64e">

I suspected that this problem arose because I used minigraph-cactus with the T2T chm13 reference and other long sequences. However, I believe it could be beneficial for developers to be aware of such issues. Additionally, it would be greatly appreciated if you could offer advice or share your thoughts on this matter. 

This is the code I used
```
vg rna -p --threads $SLURM_CPUS_PER_TASK \
        -q \
        --transcripts ${wd}/03.pantranscriptome/${chr}.gtf --gbz-format \
        --write-gbwt ${wd}/03.pantranscriptome/${chr}.pantranscriptome.gbwt \
        --write-info ${wd}/03.pantranscriptome/${chr}.pantranscriptome.txt \
        -f ${wd}/03.pantranscriptome/${chr}.pantranscriptome.fa \
        ${wd}/02.minigraph-cactus/chm13.hg002.all.${chr}.gbz \
        > ${wd}/03.pantranscriptome/${chr}.spliced_graph.pg 
```

**Comment by jjuhyunkim** [comment]
There are many regions with small loops containing several genes, but these regions didn't cause any errors during the construction of the graph with 'vg rna.' However, in the 'isoform-information' text file, there are several isoforms with more than one specific haplotype in 4th column, as shown below. 
<img width="726" alt="Screenshot 2023-11-06 at 4 21 52 PM" src="https://github.com/vgteam/vg/assets/131193680/203ffae8-6a5e-4718-b25e-3977dcae8e46">

This is not a problem until 'mpmap,' but it causes an error when I run 'rpvg.'

```spp::sparse_hash_map<std::__cxx11::basic_string<char>, PathInfo> parseHaplotypeTranscriptInfo(const string&, bool, bool): Assertion `haplotype_transcript_info_it.first->second.source_ids.emplace(haplotype_id_index_it.first->second).second' failed.```

Therefore, I am going to try to remove duplicated haplotypes in column 4 of each row in the 'isoform-haplotype information' text file.

It would be very helpful if you could provide any advice on this as well.

Thank you.
