### ISSUE TITLE
vg autoindex for multi-threaded

### ISSUE THREAD

**Issue by dongdongdong0203** [vgteam/vg#4076]
Hi, developer.
I ran vg autoindex on real data with the command :
`vg autoindex 
--threads 32  
--workflow mpmap  
--workflow rpvg 
--prefix chr1 
--ref-fasta 1.chr1.dna.toplevel.fa 
--vcf  chr1_qc.generegion.phased.vcf.gz 
--tx-gff chr1.gtf`
But I found that even though I set up 32 threads, the task is still running single threaded. Currently, it takes me longer to test just one chromosome. If the whole genome is analyzed it can take even longer, and I can't figure out why the threading option is provided, but it still runs single threaded. Can you please give me some suggestions to improve the efficiency of the operation?

Thanks

**Comment by jeizenga** [comment]
There are certain sub-tasks that cannot be multithreaded, so this is expected behavior. The biggest one is parsing the VCF file, which can take quite a bit of time if there are many samples.
