### ISSUE TITLE
How to evaluate the vg genotyping result

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4082]
![image](https://github.com/vgteam/vg/assets/74750242/a9376313-7747-4be2-997a-6f70c557f3de)

The `toil-vg sveval` can evaluate the SV calls relative to a truth set. Is there a corresponding commands in VG?

**Comment by glennhickey** [comment]
To evaluate sv calls you can use [truvari](https://github.com/ACEnglish/truvari) or [sveval](https://github.com/jmonlong/sveval).  Toil-vg uses sveval too, but it hasn't been maintained for a while.  

Evaluating variant calls against a truthset is outside the scope of vg so you will need to use other tools.
