### ISSUE TITLE
vg surject error

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4101]
I want to get the **bam file** from **gam file** using command:`vg surject -b -t 20 -p GRCh38#0#chr21 -x ../chr21.gfa graphaligner_aln_new.gam > aln.bam`,but there is a stack smashing detected error.
Do you have any solutions？

This is the crash report.
[crash_report.txt](https://github.com/vgteam/vg/files/12727195/crash_report.txt)

**Comment by jeizenga** [comment]
Are you able to share the inputs that led to this crash?

**Comment by tanger-code** [comment]
The vg file is from [https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.chroms/chr21.vg](url).
The GFA file is converted from the vg file.
The gam file is too big(2GB) that I can't upload it. I use graphaligner to align HG002-chr21 long reads to the gfa file and get the gam file.

**Comment by tanger-code** [comment]
[https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/](url)
I use these reads to align to GRCh38 and get the bam file. Then find the chr21 reads and align them using command: 
```
samtools view -b aln.sorted.bam chr21 > chr21.bam, 
samtools bam2fq chr21.bam > chr21.fq
GraphAligner -g chr21.gfa -f chr21.fq -a graphaligner_aln_new.gam -x vg
```

**Comment by adamnovak** [comment]
This looks like the Dozeu stack bug for long reads that #4130 fixed. I'm going to close this; the fix is merged and should come out in the next vg release.
