### ISSUE TITLE
errors when read `.vg` in python

### ISSUE THREAD

**Issue by yihangs** [vgteam/vg#4108]
**1. What were you trying to do?**

I use the way shown in `https://github.com/cartoonist/pystream-protobuf/blob/master/Makefile` to generate the file `vg_pb2.py` from `vg.proto` in `https://github.com/vgteam/libvgio/blob/master/deps/vg.proto`, and I use `vg_pb2.py` for reading `.vg` in python via the following code structure:
```
with stream.open(fname, "rb") as istream:
   for data in istream:
      vg = vg_pb2.Graph()
      vg.ParseFromString(data)
```

**2. What did you want to happen and what actually happened?**

It works well when I read `.vg` generated from `vg construct`, however, for `.vg` files generated from, e.g. `vg mod` or `vg find -p chr1`, it does not work, with error: `OSError: Not a gzipped file (b'\xe9\x07')`, which comes from the code line `for data in istream`. I don't know how to solve this problem. I used `vg stats -F` to check the graph format, they are all `VG-Protobuf`. 

**6. What does running `vg version` say?**

```
vg version v1.49.0-9-ge61a8a475 "Peschici"
Compiled with g++-9 (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0 on Linux
Linked against libstd++ 20210601

```

Thanks!

**Comment by glennhickey** [comment]
Use `vg convert -v` to convert any graph into protobuf format. 

Use [libbdsg](https://github.com/vgteam/libbdsg) to access the other graph formats in Python.

**Comment by blinard-BIOINFO** [comment]
@yihangs I get this error unless I use `stream.open(fname, "rb", gzip=False) `.
