### ISSUE TITLE
extract aligned reads within a specific chromosome from `.gam`

### ISSUE THREAD

**Issue by yihangs** [vgteam/vg#4112]
Hi, 

Is there an efficient way to extract aligned reads within a specific chromosome (e.g. chromosome 1) from `.gam`? I tried `vg view -a file.gam -p chr1` but not work. 

Thanks!

**Comment by jeizenga** [comment]
I believe the functionality you're asking for is available with `vg chunk -a file.gam -C -p chr1`.

**Comment by yihangs** [comment]
Thank you for your response! However, I tried the command `vg chunk -x graph.xg -a file.gam -C -p chr1 > file_chr1.gam` but find that it returns nothing, the file `file_chr1.gam` is an empty file. Do you know why is that? 

Thanks!

**Comment by jeizenga** [comment]
Were there any files created in the local directory? The output might not be through stdout.

**Comment by yihangs** [comment]
Ah yes, a file called `chunk_chr1.gam` was generated, I didn't notice before. Thank you so much!
