### ISSUE TITLE
vg pack error

### ISSUE THREAD

**Issue by Drbiology** [vgteam/vg#4114]
Hi !
I used [PGGB](https://github.com/pangenome/pggb) software to get a graph of one chromosome of 10 genomes, and then wanted to align the WGS data to the graph and perform SV calling.

Command:
`vg autoindex --workflow giraffe -t 60 -g combined.paf.417fcdf.42e55e5.smooth.final.gfa  -p pangenome_chr14`

`vg giraffe -t 60 -Z pangenome_chr14.giraffe.gbz -m pangenome_chr14.min -d pangenome_chr14.dist -f T2-1_good_1.fastp.fq.gz -f T2-1_good_2.fastp.fq.gz > pangenome_chr14.gam`

`vg pack -x pangenome_chr14.giraffe.gbz -a pangenome_chr14.gam -o pangenome_chr14.pack -Q 5` ,

But the following error occurred in "vg pack",

_[E::hts_hopen] Failed to open file pangenome_chr14.gam
[E::hts_open_format] Failed to open file "pangenome_chr14.gam" : Exec format error
[vg::alignment.cpp] couldn't open pangenome_chr14.gam_

I checked the path and size of the gam file and there is no problem.  What could be the cause of this problem?  Is it because the chromosome is too large (~713 Mb) or  WGS data cannot be used to align a single chromosomes in vg?

Thanks for your help!

**Comment by glennhickey** [comment]
Use `vg pack -g`
```
    -g, --gam FILE         read alignments from this GAM file (could be '-' for stdin)
    -a, --gaf FILE         read alignments from this GAF file (could be '-' for stdin)
```

**Comment by Drbiology** [comment]
Thank you very much!
I referred to the code of this web page.  It seems that it needs to be updated.
https://github.com/vgteam/vg/wiki/SV-Genotyping-and-variant-calling

This c
