### ISSUE TITLE
vg surject  short paired-end reads' gam file to bam file, but the insert fragment length is very big.

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4119]
This is the reads `.fq` file that contains paired end reads in it.
![image](https://github.com/vgteam/vg/assets/74750242/b128c274-33ed-48f9-aa60-98b9162020ec)
Then I map them to the graph using comman:
`vg giraffe -Z HPRC_chr21.giraffe.gbz -f $reads -i -t 38 > mapped.gam`
And then I want to surject them to the linear reference and use command:
`vg surject -b -t 20 -p GRCh38#0#chr21 -x $gfa_file mapped.gam -i > mapped_linear.bam`
But in the result bam file，the **insert fragment length** between paired end reads is very big：
![image](https://github.com/vgteam/vg/assets/74750242/67e1dfa9-31cf-48cb-ab83-c669ad0ae865)

Is this normal? Or is there something wrong with the command I used?
（And are the two `-i` arguments in the command correct?）

**Comment by jeizenga** [comment]
With the `-i` argument, you need every pair of adjacent reads in the FASTQ to be part of the same read pair. It looks to me like your input FASTQ is not sorted in this order, which would cause `vg giraffe` to interpret reads that aren't actually paired together as if they were part of the same pair. Maybe you extracted this FASTQ from a BAM that was sorted by reference position? If so, you can regenerate a sorted FASTQ with `samtools collate`.

**Comment by tanger-code** [comment]
Okay, I got it. Thank you！
