### ISSUE TITLE
< vg call --vcf > command produce empty VCF file

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4120]
The graph I used is the hprc-v1.1-mc-grch38.chr21.vg from [hprc-v1.1-mc-grch38.chroms/chr21.vg](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.chroms/chr21.vg)
Then I convert it to GFA graph file, and use graphAligner to map long reads of HG002 to the chr21.gfa graph.
Then I get the pack file using `vg pack -x chr21.gfa -g aln.gam -t 20 -o aln.pack`.
And last I genotyping it using `vg call -t 30 chr21.gfa -k aln.pack -S GRCh38 -v $vcf_file > vg_genotype_wiht_vcf.vcf`.
The VCF file used is also from HPRC: [hprc-v1.0-mc.grch38.vcfbub.a100k.wave.vcf.gz](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.0-mc.grch38.vcfbub.a100k.wave.vcf.gz)
But the result VCF file only contains header, and it seems like all records are skipped(No alt path found in graph for variant.  It will be ignored):
![image](https://github.com/vgteam/vg/assets/74750242/f51de655-bf71-4438-aa9f-f493d0b49f31)

This issue [3950](https://github.com/vgteam/vg/issues/3950) mentions using xg files. I tried it but the result is the same.
Is this because there is no alt-path in the HPRC graph？If so, how can I add alt-pth to it? Is there some relate command?

**Comment by netwon123** [comment]
Don't you need to provide a reference sequence?

**Comment by tanger-code** [comment]
> #3950 maybe help for u

I've looked at it. And I use `.vg` and `.gfa` and `.xg` file to call variants separately. But the results are the same.
I wonder if there is no alt-path stored in the HPRC graph. 
If so, is there a way to add it to the graph after constructing graph?

**Comment by glennhickey** [comment]
You cannot use `-v` with `vg call` unless the graph was constructed with `vg construct -a`.

**Comment by tanger-code** [comment]
> You cannot use `-v` with `vg call` unless the graph was constructed with `vg construct -a`.

The graph I used is HPRC graph. It's constructed using `cactus-pangenome`. So it not support for calling with VCF, right? And is there a way to add `alt-path` info to the graph after constructing graph like HPRC?

**Comment by netwon123** [comment]
How I combine the giraffe and Vg call?
---- Replied Message ----
| From | Glenn ***@***.***> |
| Date | 10/17/2023 20:04 |
| To | vgteam/vg ***@***.***> |
| Cc | Qi ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [vgteam/vg] < vg call --vcf > command produce empty VCF file (Issue #4120) |

You cannot use -v with vg call unless the graph was constructed with vg construct -a.
