### ISSUE TITLE
Obtain poor genotype performance by vg call

### ISSUE THREAD

**Issue by netwon123** [vgteam/vg#4127]
I am using vg 1.51.0 to try and call snp and indel (vg call -a)  from simulated short-read  data mapped to a pangenome using giraffe.  The true set is obtained by downsampling from the variation set of the build graph. In my experience, the genotype of variants is based on the variants already in the graph. Even if it is self-verified, the performance of SNP and indel obtained is low. (F1 =~0.6). 

The relevant information is shown below:
The simulated reads is 5x, 10x, 15x.
vg paths -M 
![image](https://github.com/vgteam/vg/assets/108071362/f666d13a-5e68-48c6-9075-17d909332642)
vg depth -k x.pack -b 100000
![image](https://github.com/vgteam/vg/assets/108071362/39952a5f-d4d9-48c5-bcb8-8f9c2f9d8b7f)

The command used in my test is :
vg giraffe -t 36 -Z PGG_all.giraffe.gbz -m PGG_all.min -d PGG_all.dist  -f 10x_R1.fastq.gz -f 10x_R2.fastq.gz  > 10x_vg-pan.gam
 vg pack -t 36 -x PGG_all.giraffe.gbz -g 10x_vg-pan.gam -o 10x_vg-pan.pack
 vg call -t 36 -r PGG_all.snarls -z PGG_all.giraffe.gbz -a -k 10x_vg-pan.pack -s 10x > 10x-vg-pan.vcf

 I don't understand how to improve the performance of genotype, if someone can explain it and a potential solution that would be great!

**Comment by glennhickey** [comment]
How do you simulate the reads?
