### ISSUE TITLE
vg autoindex crashes when pangenome is missing contigs.

### ISSUE THREAD

**Issue by MarionPerrier** [vgteam/vg#4136]
**1. What were you trying to do?**
I am trying to autoindex a pangenome of 7 _S. cerevisiae_ isolates built using `cactus-pangenome`. 
The following steps were to run `vg mpmap` followed by `rpvg` on RNAseq data.

I have 6 samples with a chromosomal resolution, and if I only run these 6 in cactus-pangenome, `vg autoindex` runs without troubles. However, the 7th is very fragmented (around ~300 contigs), and  `cactus-pangenome` removes some of these contigs entirely, even by running loose parameters. 
It lead `vg autoindex` to crash since some of these contigs has annotations linked to them in the GFF3 file of this sample.

**2. What did you want to happen?**
An indexing of my pangenome so I could align RNAseq data on it.

**3. What actually happened?**
This crash: 

```
(base) marion@marion-PC:~/Documents/pangenome_assembly/test_yeast/vg_annot2$ singularity run docker://quay.io/vgteam/vg:v1.52.0 vg autoindex -w mpmap -w rpvg --prefix yeast_annot2 --gfa yeastPg2.gfa -H ../annotation/prefix/BY4741_prefix.gff3 -H ../annotation/prefix/DBVPG6044_prefix.gff3 -H ../annotation/prefix/SK1_prefix.gff3 -H ../annotation/prefix/UWOPS034614_prefix.gff3 -H ../annotation/prefix/Y12_prefix.gff3 -H ../annotation/prefix/YPS128_prefix.gff3 -x ../annotation/prefix/S288C_prefix.gff3 --gff-tx-tag Parent -t 8
INFO:    Using cached SIF image
[vg autoindex] Executing command: /vg/bin/vg autoindex -w mpmap -w rpvg --prefix yeast_annot2 --gfa yeastPg2.gfa -H ../annotation/prefix/BY4741_prefix.gff3 -H ../annotation/prefix/DBVPG6044_prefix.gff3 -H ../annotation/prefix/SK1_prefix.gff3 -H ../annotation/prefix/UWOPS034614_prefix.gff3 -H ../annotation/prefix/Y12_prefix.gff3 -H ../annotation/prefix/YPS128_prefix.gff3 -x ../annotation/prefix/S288C_prefix.gff3 --gff-tx-tag Parent -t 8
[IndexRegistry]: Checking for haplotype lines in GFA.
[IndexRegistry]: Constructing a GBZ from GFA input.
[IndexRegistry]: Constructing haplotype-transcript GBWT and spliced graph from GBZ-format graph.
	ERROR: Chromosome path "BY4741#0#scaffold_151" not found in graph or haplotypes index (line 22194).
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**
NA

**5. What data and command can the vg dev team use to make the problem happen?**
Here is the construction of the pangenome:  

```
singularity run --cleanenv docker://quay.io/comparative-genomics-toolkit/cactus:v2.6.9 cactus-pangenome ./js input.txt --outDir yeastPg2 --outName yeastPg2 --reference S288C --vcf --giraffe full --gfa --gbz --odgi --draw --viz --permissiveContigFilter
```

The vg autoindex command leading to the crash:

```
singularity run docker://quay.io/vgteam/vg:v1.52.0 vg autoindex -w mpmap -w rpvg --prefix yeast_annot2 --gfa yeastPg2.gfa -H ../annotation/prefix/BY4741_prefix.gff3 -H ../annotation/prefix/DBVPG6044_prefix.gff3 -H ../annotation/prefix/SK1_prefix.gff3 -H ../annotation/prefix/UWOPS034614_prefix.gff3 -H ../annotation/prefix/Y12_prefix.gff3 -H ../annotation/prefix/YPS128_prefix.gff3 -x ../annotation/prefix/S288C_prefix.gff3 --gff-tx-tag Parent -t 8
```
I can send you by mail the assemblies and annotation if you need them.

**6. What does running `vg version` say?**

```
INFO:    Using cached SIF image
vg version v1.52.0 "Bozen"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by root@buildkitsandbox
```

**Comment by adamnovak** [comment]
A fix would be a way to skip items in the GFF3 that are on paths that aren't in the pangenome, right?

A workaround would be to subset the GFF3 file to the paths actually in the pangenome GFA. But I thing `vg paths --list -x yeastPg2.gfa` might describe paths like `BY4741#0#scaffold_151[12000]` if the paths got broken up into multiple pieces by Cactus, so there might need to be some `sed` surgery involved in getting a clean list of all the paths to keep. And once you have that, I can't name a tool that knows how to take a list of contigs and subset a GFF3 file to it.

**Comment by MarionPerrier** [comment]
Thank you for your reply, indeed this solves the issue and after filtering the gff3, `vg autoindex` can complete without error. 
This also solve [this cross-post](https://www.biostars.org/p/9577434/) on Biostars. 

In case someone comes here with the same issue: I also opened a [ticket on cactus' github](https://github.com/ComparativeGenomicsToolkit/cactus/issues/1212) to know if there is a better practice for building a pangenome with fragmented assemblies, and limit the number of lost contigs.

I wish you a good day,
Marion
