### ISSUE TITLE
Problem about graph path

### ISSUE THREAD

**Issue by Drbiology** [vgteam/vg#4142]
Hi,
I used the [PGGB](https://github.com/pangenome/pggb) program to construct the graph of ten species. And I got the VCF file with variant and the graph path of each variant. But when I finished the vg calling, I found the graph paths of the variant in vg calling output were not same as the PGGB. Is this correct? Does vg calling re-arrange the graph path?

VCF from PGGB
![image](https://github.com/vgteam/vg/assets/42206757/89b2fb8b-d0fc-4b8c-af7a-20e16f3fd4cc)

VCF from vg calling
![image](https://github.com/vgteam/vg/assets/42206757/35dc6ef5-e75c-470b-ba45-3da4d2906912)

Looking forward to your response. Thanks!

**Comment by glennhickey** [comment]
`vg call` doesn't touch your node IDs. There must have been a change between the graph the PGGB VCF was made from and the graph used for calling.  Converting to GBZ can change the IDs.  If it was GBZ conversion, you can tell `vg call` to use the original IDs with its `-O` option.
