### ISSUE TITLE
What's the maximum sample size in the vcf files to construct a graph with vg autoindex?

### ISSUE THREAD

**Issue by dudududu12138** [vgteam/vg#4144]
Hi,
I constructed an index of the graph genome using vcf files containing different numbers of samples.
For example, this is a vcf file with 5 samples:
![1698997541829](https://github.com/vgteam/vg/assets/125525648/9d9ede0c-e58d-4fc7-a675-8a7291e93aae)
And I construct the giraffe index with the codes below:
```
vg autoindex --workflow giraffe -r ../x.fa -v x.vcf.gz -t 5 -p x_index
vg convert -x x_index.giraffe.gbz -t 5 >x_index.xg
vg paths -L -x x_index.xg
```
I repeated the above using vcf files with different numbers of samples. And the upper limit of the sample size appears to be 95.
When I use sample number less than 95, the path names are like this:
![1698997781842](https://github.com/vgteam/vg/assets/125525648/e5bc660b-4d3a-497f-b495-c7730d688f21)
But when I use sample number more than 95,for example 100,the path names are like this:
![1698997893146](https://github.com/vgteam/vg/assets/125525648/01717641-f7c2-43e0-8db4-f7c2c1c3add8)
The graph constructed using 100 samples did not have 100 pairs of haplotypes.
Do you know the reason? And I didn't find a parameter to adjust the max number of samples. The version of vg that I use is `v1.43.0 "Barisano"`
Thank you very much!

**Comment by jltsiren** [comment]
Giraffe does not like having too many haplotypes in the graph. Rare variants can act as decoys, making mapping slower and less accurate. Once the number of haplotypes reaches 192, `vg autoindex` downsamples them to 64 synthetic haplotypes.

If you want a graph with more samples, you must build and index it manually. The exact commands depend on what you have as an input and what you want to do with the graph. There are many cases, but you can find some documentation [in the wiki](https://github.com/vgteam/vg/wiki/Index-Construction).

Also, vg 1.43.0 is quite old, and newer versions have many improvements and bug fixes. Unless you have a reason for using a specific version, you should update at least once every few months.

**Comment by dudududu12138** [comment]
> Giraffe does not like having too many haplotypes in the graph. Rare variants can act as decoys, making mapping slower and less accurate. Once the number of haplotypes reaches 192, `vg autoindex` downsamples them to 64 synthetic haplotypes.
> 
> If you want a graph with more samples, you must build and index it manually. The exact commands depend on what you have as an input and what you want to do with the graph. There are many cases, but you can find some documentation [in the wiki](https://github.com/vgteam/vg/wiki/Index-Construction).
> 
> Also, vg 1.43.0 is quite old, and newer versions have many improvements and bug fixes. Unless you have a reason for using a specific version, you should update at least once every few months.

Thank you for your response! 
By the way, what's the

**Comment by jltsiren** [comment]
We use a greedy algorithm for generating the synthetic haplotypes. In the proportional sampling mode, we consider the frequency of each 4-node subpath in the true haplotypes and in the haplotypes we have generated so far, and choose the next node to minimize the deviation from the true distribution. If there are no true haplotypes (for example because the VCF was not phased), we try to sample all 4-node subpaths evenly and generate 16 instead of 64 haplotypes.

**Comment by dudududu12138** [comment]
> We use a greedy algorithm for generating the synthetic haplotypes. In the proportional sampling mode, we consider the frequency of each 4-node subpath in the true haplotypes and in the haplotypes we have generated so far, and choose the next node to minimize the deviation from the true distribution. If there are no true haplotypes (for example because the VCF was not phased), we try to sample all 4-node subpaths evenly and generate 16 instead of 64 haplotypes.

Thank you so much!
