### ISSUE TITLE
The result of 'vg view -dpn' has too many paths. Is there a way to extract only the paths I'm interested in？

### ISSUE THREAD

**Issue by tanger-code** [vgteam/vg#4154]
Hi.
I'm working with the whole-genome and I'm visualizing the parts I'm interested in. I use command `vg find -x chr21.xg -r 44549648:44549651 | vg view -dpn - | dot -Tjpg -o 44549648_44549651.jpg` to visualize the subgraph, but there are many paths in the result which makes my analysis inconvenient:
![image](https://github.com/vgteam/vg/assets/74750242/4c199adb-c8da-4cff-957d-d01c9c93bb33)

Is there a way to extract only the paths I'm interested in？

**Comment by jeizenga** [comment]
It's a bit inelegant, but you could convert it into and out of GFA format. GFA is a simple line-based format, so you could filter the paths using `grep`. It would look something like this:

```
vg find -x chr21.xg -r 44549648:44549651 | vg convert -f - | grep -v REGEXHERE | vg convert -g - | vg view -dpn - | dot -Tjpg -o 44549648_44549651.jpg
```

**Comment by glennhickey** [comment]
You can also pipe through `vg paths -x -` with one of
```
    -d, --drop-paths         output a graph with the selected paths removed
    -r, --retain-paths       output a graph with only the selected paths retained
```
and one of
```
    -p, --paths-file FILE    select the paths named in a file (one per line)
    -Q, --paths-by STR       select the paths with the given name prefix
```
