### ISSUE TITLE
How to construct a graph without any variants?

### ISSUE THREAD

**Issue by dudududu12138** [vgteam/vg#4160]
Hello,
I want to make a giraffe index with only reference genome and without variants. I do this with codes below:
```
vg autoindex --workflow giraffe -r $ref -t $t -p ./index/index
```
And I got an error report like this:
```
error:[vg autoindex] Input is not sufficient to create indexes
Inputs
        Reference FASTA
are insufficient to create target index Giraffe Distance Index
```
So how can I get a reference graph and the giraffe index without variants vcf file?
Thanks!

**Comment by jltsiren** [comment]
`vg autoindex` does not support that use case at the moment. If you want a graph with just the reference, you have to build the graph and index it manually:

```
# Build a graph with 32 bp nodes. Use -m to change node length.
vg construct -r reference.fa > graph.vg

# Convert the graph to GBZ format.
vg gbwt -p -E -x graph.vg --gbz-format -g graph.gbz

# Build the distance index.
vg index -j graph.dist graph.gbz

# Build the minimizer index.
vg minimizer -p -d graph.dist -o graph.min graph.gbz
```

The above commands should use a reasonable number of threads by default. If you want to adjust that, you can use option `--num-jobs` in `vg gbwt` and option `-t` in `vg minimizer`.

**Comment by Ahahaha3** [comment]
> `vg autoindex` does not support that use case at the moment. If you want a graph with just the reference, you have to build the graph and index it manually:
> 
> ```
> # Build a graph with 32 bp nodes. Use -m to change node length.
> vg construct -r reference.fa > graph.vg
> 
> # Convert the graph to GBZ format.
> vg gbwt -p -E -x graph.vg --gbz-format -g graph.gbz
> 
> # Build the distance index.
> vg index -j graph.dist graph.gbz
> 
> # Build the minimizer index.
> vg minimizer -p -d graph.dist -o graph.min graph.gbz
> ```
> 
> The above commands should use a reasonable number of threads by default. If you want to adjust that, you can use option `--num-jobs` in `vg gbwt` and option `-t` in `vg minimizer`.

hello,
i run the pipeline followed you and get graph.gbz,  graph.dist,and graph.min, then i run (1) vg giraffe -Z ../graph.gbz -m ../graph.min -d ../graph.dist -f sample_R1.fq.gz -f sample_R2.fq.gz -t 40 > sample.gam. (2) vg pack -x ../graph.gbz -g sample.gam -o sample.pack -Q 5 -t 40. (3) vg call ../graph.gbz -k sample.pack -t 40 -r ../Graph.snarls 2> vcf.log > sample.vcf. But i get an empty   vcf file.

**Comment by jltsiren** [comment]
The `vg call` command you are using is for genotyping the variants that are present in the graph. But because you built the graph from the reference only, there are no variants to be genotyped.

If you want to use `vg call` for de novo variant calling, see section "Whole genome calling" [in the wiki](https://github.com/vgteam/vg/wiki/SV-Genotyping-and-variant-calling).
