### ISSUE TITLE
indels aren't left-shifted

### ISSUE THREAD

**Issue by alshai** [vgteam/vg#4163]
**1. What were you trying to do?**

How does VG handle placement of indels when there are multiple equal-scoring possibilities? I am seeing a lot of cases where the indels are either right-aligned or split up. This is causing problems in our internal tools because it introduces some inconsistency in the representation of variation across the reads.
Indel-realignment helps, but I'd rather avoid it especially as our datasets can get very large.

**2. What did you want to happen?**
Ideally, as per general convention, the indels in the alignment CIGAR strings would be left-shifted,

**3. What actually happened?**

We often see examples of right-shifted indels, as in the example below. Top panel is Giraffe-HPRC alignments, middle panel is BWA, and bottom panel is Giraffe-HPRC left-shifted with freebayes `bamleftalign`. See screenshot below

![Screenshot 2023-11-15 at 3 18 57 PM](https://github.com/vgteam/vg/assets/3864800/35c2be2f-dc27-494e-8550-3371ecd0f0ea)

**5. What data and command can the vg dev team use to make the problem happen?**

can email data on request.

**6. What does running `vg version` say?**

```
v1.50.1 "Monopoli"
```

**Comment by jltsiren** [comment]
Giraffe maps the reads to a graph, where the direction relative to the reference ("left" or "right") is not always well-defined. The same alignment can be left-shifted relative to one set of paths and right-shifted relative to another.

The actual behavior is usually pushing the indels away from the selected seed. Giraffe first tries finding an alignment without gaps. If it cannot find a full-length alignment, it trims the partial alignment to maximize the alignment score and then considers indels when aligning the tails.

If you want mappings against a linear reference, the alignments must be projected to some paths in the graph. I'm not fully sure about the current algorithm, but there should be several cases:
1. The read is aligned to another path that can be understood as containing indels relative to the selected reference. In that case, the indels can be left-shifted or right-shifted relative to the reference, depending on the choices made when building the graph.
2. The read is aligned to a reference path, but there are indels in the alignment. Then the projected alignment should reflect the internal priorities of Giraffe, pushing indels away from the seed.
3. Some parts of the alignment are relative to a path that diverges from the reference. That part of the read will be realigned and may contain indels.

And if you choose another set of paths as the reference, a projected alignment that used to be left-shifted can become right-shifted, and the other way around.
