### ISSUE TITLE
vg haplotypes can't generate sample gbz for large chromsomes because of small buffer size

### ISSUE THREAD

**Issue by hahahafeifeifei** [vgteam/vg#4167]
Hi,

I used the `vg haplotypes` to generate the sample graph and I got the message:
```
Estimating kmer coverage
Estimated kmer coverage in 3.90783 seconds
Building GBWT
Running 14 GBWT construction jobs in parallel
GBWTBuilder::insert(): Sequence is too long for the buffer, skipping
GBWTBuilder::insert(): Sequence is too long for the buffer, skipping
GBWTBuilder::insert(): Sequence is too long for the buffer, skipping
GBWTBuilder::insert(): Sequence is too long for the buffer, skipping
GBWTBuilder::insert(): Sequence is too long for the buffer, skipping
```
The sample gbz file can be generated but only contains the chromosome paths with node count of less than 50M. It seems related to buffer size issue mentioned in https://github.com/vgteam/vg/issues/3303. Could the --buffer-size parameter be added to vg haplotypes?

**Comment by jltsiren** [comment]
In the latest master, GBWT construction (in `vg haplotypes` and elsewhere) will automatically resize the buffer if the paths are too long. The fix will be included in the next release, which is due in a couple of weeks.
