### ISSUE TITLE
Should alignment.quality be phred or phred+33?

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#419]
On input we convert FASTQ qualities (phred+33) into raw phred scores (including low values below 32) and stick those in the "quality" field on Alignment objects. Internal math that uses qualities on an Alignment assumes this semantics for the field, from what I can tell. But when Alignments are output in GAM format, the "quality" field holds phred+33 again; we seem to up-convert somewhere. This means that when we read in Alignments from GAM, we need to convert their qualities from phred+33 to phred again, which is easy to forget to do (as I have in the genotyper, it seems).

Is there a reason we don't just use raw phred in the quality field in alignments in GAM files, for a unified representation?

**Comment by ekg** [comment]
Well this sounds like a bug because I meant to implement regular phred in
the quality byte array, and only convert for SAM.

**Comment by adamnovak** [comment]
@glennhickey has given me reason to believe that `vg view -JGa` is what's tacking +33 onto the quality scores in GAM format.
