### ISSUE TITLE
error [vg call]: No reference paths found

### ISSUE THREAD

**Issue by YibinQiu** [vgteam/vg#4194]
**1. What were you trying to do?**
I wish to manually construct and index the graph using vg construct -a and perform SV genotyping of an individual with second-generation sequencing data using vg call -v. I followed the commands as per the official vg documentation (https://github.com/vgteam/vg/wiki/SV-Genotyping-and-variant-calling):
```
#vg construct -a 
vg construct -f -a -S -r $ref -v convert_merge.vcf.gz -p > out.vg
vg index -t 64 out.vg -L -x out.xg -p --temp-dir ${LARGE_DISK_TMP}
vg index -t 64 out.vg -v convert_merge.vcf.gz -G out.gbwt -p --temp-dir ${LARGE_DISK_TMP}
vg gbwt -x out.xg out.gbwt -g out.gbz --gbz-format -p --temp-dir ${LARGE_DISK_TMP}
vg index -t 64 out.gbz -j out.dist -p --temp-dir ${LARGE_DISK_TMP}
vg minimizer -t 16 out.gbz -d out.dist -o out.min -p
vg snarls -t 64 out.xg >out.snarls

#vg giraffe pack and call -v
cp out.gbz ${sample}_out.gbz
cp out.dist ${sample}_out.dist
cp out.min ${sample}_out.min
cp out.gbwt ${sample}_out.gbwt
cp out.xg ${sample}_out.xg
cp out.snarls ${sample}_out.snarls
cp out.vg ${sample}_out.vg
vg giraffe -p -t 24 -Z ${sample}_out.gbz -d ${sample}_out.dist -m ${sample}_out.min -f ${sample}_1.fq.gz -f ${sample}_2.fq.gz > ${sample}.gam
vg pack -t 24 -x ${sample}_out.gbz -g ${sample}.gam -o ${sample}.pack -Q 5
vg call -t 24 ${sample}_out.gbz -r ${sample}_out.snarls -k ${sample}.pack -s ${sample} -v convert_merge.vcf.gz -f $ref > ${sample}.vcf
```
**2. What did you want to happen?**
The SV information contained in the VCF file generated by the vg call step corresponds to the VCF input 

**3. What actually happened?**
When running vg call out.gbz, the following error is reported:
```error [vg call]: No reference paths found```

When I replaced ${sample}_out.gbz with ${sample}_out.xg, vg call was able to run normally, but it displayed: 
```
[VCFTraversalFinder] Warning: Site {'directed_acyclic_net_graph': true, 'end': {'node_id': '8705753'}, 'end_self_reachable': true, 'start': {'node_id': '8645904'}, 'start_end_reachable': true, 'start': {'node_id': '8645904'}, 'start_end_reachable': true, 'start_self_reachable': true} with 304 variants contains too many traversals (>50000) to enumerate so it will be skipped.
```
Following the suggestion #3950 , I also used : 
```
vg call -t 24 ${sample}_out.gbz -r ${sample}_out.snarls -k ${sample}.pack -s ${sample} -a -z > ${sample}.vcf
```
but the result was the same, showing:
```error [vg call]: No reference paths found.```
So, I'm not sure which step I did wrong?

Additionally, I previously tried using vg autoindex to construct the graph, and performing vg call on out.gbz with 15X second-generation sequencing data only took about half an hour. Now, using vg construct -a and vg call out.xg, I find that the runtime of vg call is too long (~5 hours).

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**
```
vg call -t 24 out.gbz -r out.snarls -k ${sample}.pack -s ${sample} -v convert_merge.vcf.gz -f $ref > ${sample}.vcf
```
**6. What does running `vg version` say?**

```
vg version v1.53.0 "Valmontone"
Compiled with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 on Linux
Linked against libstd++ 20230528
Built by anovak@courtyard.gi.ucsc.edu

```

**Comment by glennhickey** [comment]
Can you please provide the output of `vg paths -Mx out.gbz`? It looks like your graph has now reference paths, which is strange since it comes from `vg construct`

**Comment by YiBenqiu** [comment]
> paths -Mx out.gbz

@glennhickey  the output looks like this (I also uploaded the file):
<img width="713" alt="image" src="https://github.com/vgteam/vg/assets/57091259/aa34b273-5c5b-4d2f-b72c-f21230620886">
[test.txt](https://github.com/vgteam/vg/files/13690354/test.txt)

**Comment by YibinQiu** [comment]
> Can you please provide the output of `vg paths -Mx out.gbz`? It looks like your graph has now reference paths, which is strange since it comes from `vg construct`
@glennhickey the output looks like this (I also uploaded the file):
<img width="608" alt="image" src="https://github.com/vgteam/vg/assets/152879713/e776cd36-0b95-457b-89f4-191db1539967">
[test.txt](https://github.com/vgteam/vg/files/13690445/test.txt)

**Comment by YibinQiu** [comment]
I  follow the steps to build gbz( https://github.com/vgteam/vg/wiki/VG-GBWT-Subcommand)：
```
vg construct -f -a -S -r $ref -v convert_merge.vcf.gz -p > out.vg
vg gbwt -x out.vg -v convert_merge.vcf.gz -o out.gbwt -p --temp-dir ${LARGE_DISK_TMP}vg gbwt -x out.vg -E -o out.paths.gbwt -p --temp-dir ${LARGE_DISK_TMP}
vg gbwt -m out.gbwt out.paths.gbwt -o out.combined.gbwt -p --temp-dir ${LARGE_DISK_TMP}
vg gbwt -x out.vg out.combined.gbwt --gbz-format -g out.gbz -p --temp-dir ${LARGE_DISK_TMP}
```

and then try `vg paths -Mx out.gbz` again, the head of output looks like:
![image](https://github.com/vgteam/vg/assets/152879713/594f7149-1b6c-4a2e-aea0-940e1b65b046)

but when I grep 'GENERIC', the output seems has reference paths?:
![image](https://github.com/vgteam/vg/assets/152879713/96ef5378-896d-4b95-a2da-252ba367e542)

**Comment by glennhickey** [comment]
A few things.  If you want to use `-v` with `vg call`, you need to follow the instructions [here](https://github.com/vgteam/vg/wiki/SV-Genotyping-and-variant-calling#genotyping-a-vcf-using-the-graph).  

It looks like you are doing this for the index, but this part here is important

>You can now use test.gbz, test.dist and test.min as input for vg giraffe and test.xg as input for vg call.

Ie, you need to run `vg call` on the `xg` and `vcf` in order for it to work (even though you `ran` `vg giraffe` on the `gbz`). 

If you do not want to pass in your `vcf` with `-v` then you can don't need to bother with this, and can just run `call` on the .gbz you used for `giraffe` (that you made [here](https://github.com/vgteam/vg/issues/4194#issuecomment-1858855581)).  To speed that up you can try `vg call -z`

**Comment by YibinQiu** [comment]
Thank you for the help with this

**Comment by hyBio** [comment]
I encountered the following error when using vg call. I don't know how to set the -p parameter. Can anyone help me? I'd appreciate it.`(pggb) /02.vcf_files/
$ vg paths -Mx ../00.vg_files/${myprefix}_${i}.gbz
#NAME	SENSE	SAMPLE	HAPLOTYPE	LOCUS	PHASE_BLOCK	SUBRANGE
a_2#1#>CM024215.1#0	HAPLOTYPE	a_2	1	>chr1	0	NO_SUBRANGE
a_1#1#>NC_051039.1#0	HAPLOTYPE	a_1	1	>chr1	0	NO_SUBRANGE
a_3#1#>CM034631.1#0	HAPLOTYPE	a_3	1	>chr1	0	NO_SUBRANGE
b_1#1#>CM085472.1#0	HAPLOTYPE	fAcaSch_1	1	>chr1	0	NO_SUBRANGE
(pggb) /02.vcf_files/
$ vg call -t 16 -z ../00.vg_files/${myprefix}_${i}.gbz -a -k ./${samples}_${i}.pack -s ${samples} -r ../00.vg_files/${myprefix}_${i}.snarls -p a_1 > ./${samples}_${i}_variants.vcf &
[9] 73026
(pggb) /02.vcf_files/
$ error [vg call]: Reference path "a_1" not found in graph
[9]   退出 1                vg call -t 16 -z ../00.vg_files/${myprefix}_${i}.gbz -a -k ./${samples}_${i}.pack -s ${samples} -r ../00.vg_files/${myprefix}_${i}.snarls -p a_1 > ./${samples}_${i}_variants.vcf`

**Comment by hyBio** [comment]
I encountered the following error when using vg call. I don't know how to set the -p parameter. Can anyone help me? I'd appreciate it.
```shell
(pggb) /02.vcf_files/ $$$

vg paths -Mx ../00.vg_files/${myprefix}_${i}.gbz 
#NAME	SENSE	SAMPLE	HAPLOTYPE	LOCUS	PHASE_BLOCK	SUBRANGE 
a_2#1#>chr1#0	HAPLOTYPE	a_2	1	>chr1	0	NO_SUBRANGE 
a_1#1#>chr1#0	HAPLOTYPE	a_1	1	>chr1	0	NO_SUBRANGE 
a_3#1#>chr1#0	HAPLOTYPE	a_3	1	>chr1	0	NO_SUBRANGE 
b_1#1#>chr1#0	HAPLOTYPE	b_1	1	>chr1	0	NO_SUBRANGE

(pggb) /02.vcf_files/ $$$

vg call -t 16 -z ../00.vg_files/${myprefix}_${i}.gbz -a \
-k ./${samples}_${i}.pack -s ${samples} \
-r ../00.vg_files/${myprefix}_${i}.snarls -p a_1 > ./${samples}_${i}_variants.vcf & 

[9] 73026 

(pggb) /02.vcf_files/ $$$

error [vg call]: Reference path "a_1" not found in graph 
[9]   exit 1                vg call -t 16 -z ../00.vg_files/${myprefix}_${i}.gbz -a \
-k ./${samples}_${i}.pack -s ${samples} -\
r ../00.vg_files/${myprefix}_${i}.snarls -p a_1 > ./${samples}_${i}_variants.vcf

```
