### ISSUE TITLE
error [vg call]: No paths with selected reference sample

### ISSUE THREAD

**Issue by zhixue** [vgteam/vg#4198]
**1. What were you trying to do?**
After building a plant graph pan-genome of with Minigraph-cactus, I used vg to map short reads to graph and genotype. 
Details are as following link (Part 4: Genotyping and Variant Calling, SV Genotyping with vg):
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/sa_refgraph_hackathon_2023.md

**2. What did you want to happen?**
Got xx.vcf.gz at the step of "vg call”. 

**3. What actually happened?**
An error happened "error [vg call]: No paths with selected reference sample "NDH108" found. Try using vg paths -M to see which samples are in your graph"

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Nothing.
```

**5. What data and command can the vg dev team use to make the problem happen?**

```
# Index (It works)
vg autoindex -t $th --workflow giraffe --prefix P8_MC --gfa P8_MC.gfa
vg convert -t $th P8_MC.giraffe.gbz -x > P8_MC.xg
vg snarls -t $th P8_MC.xg > P8_MC.snarls

# Map with giraffe (It works)
vg giraffe -t $th -Z P8_MC.giraffe.gbz -d P8_MC.dist -m P8_MC.min -f $fq1 -f $fq2 -o gaf | bgzip > ${sample}.P8_MC.gaf.gz 

# Pack (it works)
#vg pack -x P8_MC.giraffe.gbz -Q5 -a ${sample}.P8_MC.gaf.gz -o ${sample}.P8_MC.pack 

# Call (Error)
vg call P8_MC.giraffe.gbz -r P8_MC.snarls -k ${sample}.P8_MC.pack -s ${sample} -S NDH108 -az | bgzip > ${sample}.P8_MC.call.vcf.g
#### error [vg call]: No paths with selected reference sample "NDH108" found. Try using vg paths -M to see which samples are in your graph

# Check the path
vg paths -M -x P8_MC.xg | grep 'NDH108'
NDH108#0#A01#0  HAPLOTYPE       NDH108  0       A01     0       NO_SUBRANGE
NDH108#0#A02#0  HAPLOTYPE       NDH108  0       A02     0       NO_SUBRANGE
NDH108#0#A03#0  HAPLOTYPE       NDH108  0       A03     0       NO_SUBRANGE
NDH108#0#A04#0  HAPLOTYPE       NDH108  0       A04     0       NO_SUBRANGE
NDH108#0#A05#0  HAPLOTYPE       NDH108  0       A05     0       NO_SUBRANGE
NDH108#0#A06#0  HAPLOTYPE       NDH108  0       A06     0       NO_SUBRANGE
NDH108#0#A07#0  HAPLOTYPE       NDH108  0       A07     0       NO_SUBRANGE
NDH108#0#A08#0  HAPLOTYPE       NDH108  0       A08     0       NO_SUBRANGE
NDH108#0#A09#0  HAPLOTYPE       NDH108  0       A09     0       NO_SUBRANGE
NDH108#0#A10#0  HAPLOTYPE       NDH108  0       A10     0       NO_SUBRANGE
NDH108#0#B01#0  HAPLOTYPE       NDH108  0       B01     0       NO_SUBRANGE
NDH108#0#B02#0  HAPLOTYPE       NDH108  0       B02     0       NO_SUBRANGE
NDH108#0#B03#0  HAPLOTYPE       NDH108  0       B03     0       NO_SUBRANGE
NDH108#0#B04#0  HAPLOTYPE       NDH108  0       B04     0       NO_SUBRANGE
NDH108#0#B05#0  HAPLOTYPE       NDH108  0       B05     0       NO_SUBRANGE
NDH108#0#B06#0  HAPLOTYPE       NDH108  0       B06     0       NO_SUBRANGE
NDH108#0#B07#0  HAPLOTYPE       NDH108  0       B07     0       NO_SUBRANGE
NDH108#0#B08#0  HAPLOTYPE       NDH108  0       B08     0       NO_SUBRANGE
NDH108#0#B09#0  HAPLOTYPE       NDH108  0       B09     0       NO_SUBRANGE
NDH108#0#B10#0  HAPLOTYPE       NDH108  0       B10     0       NO_SUBRANGE
```

**6. What does running `vg version` say?**

```
vg: variation graph tool, version v1.53.0 "Valmontone"
```

**Comment by glennhickey** [comment]
You can only run `vg call` on paths that turn up as `REFERENCE` (ie not `HAPLOTYPE`) in the graph.   

In `minigraph-cactus`, you use the `--reference` option to select which paths are reference.  

There is some information [here in the wiki](https://github.com/vgteam/vg/wiki/Changing-References) about changing the reference in your graph.

**Comment by zhixue** [comment]
Thank you very much!!!

I used `--reference` in MC, while the step from GFA to gbz (vg autoindex --workflow giraffe --gfa) can not recognize the reference path.

Your reply about how to change reference in a graph is very helpful, I have solved this problem.
