### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [vgteam/vg#42]
I find that include guards like "[`INDEX_H`](https://github.com/ekg/vg/blob/4bbbd251aae0e753e6e326d14ea6c8b11be9de7f/index.hpp#L1)" and "[`PATH_H`](https://github.com/ekg/vg/blob/0f4e94613213e983ef3e030321efd20f5036b3e1/path.hpp#L1)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by ekg** [comment]
Would you please propose a patch? I support changing this.

**Comment by ekg** [comment]
Things should move to `VG_INDEX_H` and so on. No?

**Comment by elfring** [comment]
How do you think about to make [include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by ekg** [comment]
I think that'd be fine, but if I implement the patch I'll do the simplest
thing and prefix VG on everything.
