### ISSUE TITLE
Multithreading (option "-t 20" ) does not work in vg giraffe.

### ISSUE THREAD

**Issue by Aasesss** [vgteam/vg#4201]
**1. What were you trying to do?**
I try to mapping my simmulated reads set to graph pangenome using vg giraffe.

**2. What did you want to happen?**
I want to use 20 threads.

**3. What actually happened?**
I set the option "-t 20", but that doesn't work.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

There is no error infomation.

**5. What data and command can the vg dev team use to make the problem happen?**
```
vg giraffe -p -t 20 -Z ${graph_gbz} -d ${graph_dist} -m ${graph_min} -f ${fq_prefix}.1.fq.gz -f ${fq_prefix}.2.fq.gz > ${prefix}.gam
```

**6. What does running `vg version` say?**

```
vg version v1.53.0 "Valmontone"
Compiled with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 on Linux
Linked against libstd++ 20230528
Built by anovak@courtyard.gi.ucsc.edu
```

**The following content is from my logfile:**

```
Guessing that /public/home/mjchen/object/pangenome/data/refpang/Brassica_napus15-pg.d2.gbwt is Giraffe GBWT
Guessing that /public/home/mjchen/object/pangenome/data/refpang/Brassica_napus15-pg.d2.xg is XG
Preparing Indexes
Loading Minimizer Index
Loading GBZ
Loading Distance Index v2
Paging in Distance Index v2
Initializing MinimizerMapper
Loading and initialization: 37.7295 seconds
Of which Distance Index v2 paging: 5.11609 seconds
Mapping reads to "-" (GAM)
--watchdog-timeout 10
--match 1
--mismatch 4
--gap-open 6
--gap-extend 1
--full-l-bonus 5
--max-multimaps 1
--hit-cap 10
--hard-hit-cap 500
--score-fraction 0.9
--max-min 500
--num-bp-per-min 1000
--distance-limit 200
--max-extensions 800
--max-alignments 8
--cluster-score 50
--pad-cluster-score 20
--cluster-coverage 0.3
--extension-score 1
--extension-set 20
--rescue-attempts 15
--max-fragment-length 2000
--paired-distance-limit 2
--rescue-subgraph-size 4
--rescue-seed-limit 100
--chaining-cluster-distance 100
--precluster-connection-coverage-threshold 0.3
--min-precluster-connections 10
--max-precluster-connections 50
--max-lookback-bases 100
--min-lookback-items 1
--lookback-item-hard-cap 15
--chain-score-threshold 100
--min-chains 1
--chain-min-score 100
--max-chain-connection 100
--max-tail-length 100
--max-dp-cells 16777216
--rescue-algorithm dozeu
warning[vg::Watchdog]: Thread 0 has been checked in for 10 seconds processing: 1-2783708/1, 1-2783708/2
warning[vg::Watchdog]: Thread 0 finally checked out after 21 seconds and 0 kb memory growth processing: 1-2783708/1, 1-2783708/2
warning[vg::Watchdog]: Thread 0 has been checked in for 10 seconds processing: 1-2783704/1, 1-2783704/2
warning[vg::Watchdog]: Thread 0 finally checked out after 28 seconds and 0 kb memory growth processing: 1-2783704/1, 1-2783704/2
warning[vg::Watchdog]: Thread 0 has been checked in for 10 seconds processing: 1-2783700/1, 1-2783700/2
warning[vg::Watchdog]: Thread 0 finally checked out after 16 seconds and 0 kb memory growth processing: 1-2783700/1, 1-2783700/2
```

**Comment by jltsiren** [comment]
Giraffe uses the specified number of mapping threads and one additional output thread. When you run it in paired-end mode, Giraffe starts by mapping some reads using a single thread in order to determine fragment length distribution. This normally takes around one second.

It looks like your run is stuck in that process, with many reads taking a long time to map. That often means one or both of the following:

* The structure of your graph is not what Giraffe expects, and mapping will be very slow.
* Your reads are sorted, with unmapped reads placed in front. Fragment length estimation may be slow, and it will eventually fail.

There is a little more information [in the wiki](https://github.com/vgteam/vg/wiki/Giraffe-best-practices).

**Comment by Aasesss** [comment]
> Giraffe uses the specified number of mapping threads and one additional output thread. When you run it in paired-end mode, Giraffe starts by mapping some reads using a single thread in order to determine fragment length distribution. This normally takes around one second.
> 
> It looks like your run is stuck in that process, with many reads taking a long time to map. That often means one or both of the following:
> 
> * The structure of your graph is not what Giraffe expects, and mapping will be very slow.
> * Your reads are sorted, with unmapped reads placed in front. Fragment length estimation may be slow, and it will eventually fail.
> 
> There is a little more information [in the wiki](https://github.com/vgteam/vg/wiki/Giraffe-best-practices).


Thank you very much for your detailed reply! 

Acturally, I think this problem may not caused by graph or reads data. 

I need to map multiple samples. It works fine when I run sample after sample, but when doing multiple mapping processes at once, only the first process can successfully Implement multithreading. However, these processes all take up the same amount of memory (about 17GB). I'm not sure why this happened.

**Comment by jltsiren** [comment]
The distance index could be the reason for that. It is a memory-mapped file, and some systems may have performance issues when multiple jobs memory-map the same file. Especially if it's on a network drive.

These are some solutions that could work:
1. Make the distance index (`.dist`) file read-only.
2. Create a private copy of the distance index file for each process.
3. Create private copies of all index files for each process.
