### ISSUE TITLE
Deletions at start of CIGAR sequences

### ISSUE THREAD

**Issue by huzuner** [vgteam/vg#4204]
Hello,

Thank you for your contribution to the field with your tool.

I have been using `vg giraffe` and I came across some aligned reads with CIGAR strings that start with deletions, leading a downstream process crash. So I was wondering if this behavior has an intended purpose and how it should be perceived in terms of using soft/hard clips?

**Comment by jeizenga** [comment]
I think that's unexpected behavior. Could you be more specific about the commands and data that you used?

**Comment by huzuner** [comment]
Any other information that is required on this issue?

**Comment by jeizenga** [comment]
Are you able to share the reads that you used as well? If you know which read had the issue from error logging output, that would also be helpful to know.

**Comment by huzuner** [comment]
Sorry for the delay in my replay, I was on vacation.

Here is the corresponding read alignment together with the pair:

```
SRR233141.2837738       83      GRCh38.chr14    69324672        48      25D76M  =       69324551        -222    CATCTGTGCCCTCCCCCGCGGACCTGCCAGCCCCCAGCGTCATCATCCCCTTCCACAATGAGGCCCGTTCCACCCT    ###############################A*EEDBE?DE>B@@:@3BC<EFEBEEEEEBFFFEFDCCBD<CBBB        AS:i:26
SRR233141.2837738       163     GRCh38.chr14    69324551        48      76M     =       69324672        222     GCGGGGCCTCTGGCCTGGCTGTTGGTGTGCCTTCTCTGCCTGGCAGAAGTATTCTCAGGCACAAGACTGGACAAAG    EGDEHG=GGGFG=DEGGDFGC@CBB@C3B@@CC<BE?DEE:BE>D<4><4DCDCD;4?C@FFBFE>9@D@@=CBC=        AS:i:86
```

Please let me know if you require more information.

**Comment by jeizenga** [comment]
If you rebuild off the master branch, this problem should now be resolved. Thanks for bringing it to our attention!

**Comment by huzuner** [comment]
Happy to help, thanks for taking care of the issue!
Are you thinking of doing a new release soon? So that the tool is updated in Bioconda.

**Comment by jeizenga** [comment]
We make releases on a regular schedule. The next one is scheduled for Feb. 26.
