### ISSUE TITLE
`vg giraffe` for long reads

### ISSUE THREAD

**Issue by Wenhai-Zhang** [vgteam/vg#4217]
Hi,

I found that `vg giraffe` can do long read alignments in some issues, but no manual explaining how to use it. 
Does it work like short reads alignments, or does it need specific parameters to be specified？If I have a GFA file, how should I design parameters for index construction and `vg giraffe` long reads alignment？

Thank you in advance.

**Comment by jeizenga** [comment]
The long-read features are under active development and are still largely experimental. We aren't trying to provide a stable interface or consistent performance yet. You are welcome to try the new features out, but there won't be anything like a "best practice" pipeline in the near future.
