### ISSUE TITLE
vg giraffe mapping HiFi

### ISSUE THREAD

**Issue by brettChapman** [vgteam/vg#4227]
Hi

I have some HiFi sequences, and was wondering if it's possible to align long reads to a genome graph, such as those produced from minigraph-cactus, or is it only designed for short read sequences? If not, are there plans to accommodate long reads?

Thanks.

**Comment by jeizenga** [comment]
The current default `vg giraffe` is really tailored specifically to short reads. It will run on long reads, but it will not be efficient. We are actively working on new algorithms for accurate long reads like HiFi, but the new features are still experimental. We aren't yet maintaining a consistent interface, and the performance may fluctuate unpredictably as we continue development.
