### ISSUE TITLE
Make superbubbles bigger when there's low entropy/evidence

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#423]
If your site is low-entropy (i.e. all repeats), or if your reads don't give you any traction towards one allele or the other, you ought to expand your site (by collecting sibling superbubbles) until you have something big enough to really genotype.

You know your site is big enough when you have enough entropy/uniqueness at the ends, or when it's clear that reads really do argue in favor of one allele or the other, even when aligning in the context of the surrounding graph.

@ekg could you elaborate on how the entropy measurement stuff in Freebayes works?

**Comment by ekg** [comment]
It's pretty simplistic. When we see repeated sequence, we progressively extend the window right (keeping the same start position) until we find a window with entropy greater than some fixed number of shannons per base.

**Comment by adamnovak** [comment]
I think this is outdated now, since call and genotype have been reworked a few times over and superbubbles are gone.
