### ISSUE TITLE
I have a question about gam file.

### ISSUE THREAD

**Issue by pioneer-pi** [vgteam/vg#4233]
The length of sequence and the length of quality is different. The following is a read mapping result. The length of sequence is 100, but the length of quality is 136.  Theoretically, shouldn't these two values be equal?

```
{"identity": 1.0, 
"mapping_quality": 60, 
"name": "simulated.1", 
"path": 
	{"mapping": .......................
	"name": "simulated.1"}, 
"quality": "JycnJygoJyYnKCYoKCgoKCcmJygkKCglJSgnKCgoKCQhKCgoKCglJxwoKCIoIiMeKCgcKCgoJyckJSUiKCgkIiUoJiEaJiUoJyggKCgoKCMeKCcoJygoJCQkKCAoJyYbIRwoKA==", 
"refpos": [{"name": "x", "offset": "403"}], 
"score": 110, 
"sequence": "GTTATTTACTATGAATCCTCACCTTCCTTGACTTCTTGAAACATTTGGCTATTGACCTCTTTCCTCCTTGAGGCTCTTCTGGCTTTTCATTGTCAACACA", 
"time_used": 888.0}
```

**Comment by glennhickey** [comment]
The quality string is a [base64](https://docs.python.org/3/library/base64.html) encoding of the quality values. Its length will only be the same after decoding  
```
import base64
len(base64.b64decode('JycnJygoJyYnKCYoKCgoKCcmJygkKCglJSgnKCgoKCQhKCgoKCglJxwoKCIoIiMeKCgcKCgoJyckJSUiKCgkIiUoJiEaJiUoJyggKCgoKCMeKCcoJygoJCQkKCAoJyYbIRwoKA=='))
100
```

**Comment by pioneer-pi** [comment]
> The quality string is a [base64](https://docs.python.org/3/library/base64.html) encoding of the quality values. Its length will only be the same after decoding
> 
> ```
> import base64
> len(base64.b64decode('JycnJygoJyYnKCYoKCgoKCcmJygkKCglJSgnKCgoKCQhKCgoKCglJxwoKCIoIiMeKCgcKCgoJyckJSUiKCgkIiUoJiEaJiUoJyggKCgoKCMeKCcoJygoJCQkKCAoJyYbIRwoKA=='))
> 100
> ```
