### ISSUE TITLE
ERROR: Signal 6 occurred. VG has crashed.  Terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by RohitKapila** [vgteam/vg#4244]
**1. What were you trying to do?**
Trying to call Structural variants. Have Illumina reads and SVs called from Manta.

**2. What did you want to happen?**
the vcf it is generating is empty. It is working well until it generates .gam file (around 8gb in size) but it fails at last step of generating vcf. I am expecting a vcf with structural variant information.

**3. What actually happened?**
the vcf it is generating is empty. It is working well until it generates .gam file (around 8gb in size) but it fails at last step of generating vcf. I am expecting a vcf with structural variant information.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Stack trace path: /tmp/vg_crash_xIZ3xM/stacktrace.txt
```

**5. What data and command can the vg dev team use to make the problem happen?**
ile.modules
module load vg-1.44.0 
vg construct -r N2_refrence.fna -v N2_1Formal_Manta.vcf > N2_1Formal_graph.vg
vg index -x N2_1Formal_graph.xg -g N2_1Formal_graph.gcsa -k 16 N2_1Formal_graph.vg
vg map -x N2_1Formal_graph.xg -g N2_1Formal_graph.gcsa -f N2_1Formal_Combined.fq > N2_1Formal_aln.gam
vg call N2_1Formal_graph.vg -k N2_1Formal_aln.gam > N2_1Formal_calls.vcf

N2_1Formal_calls.vcf file is empty. 

**6. What does running `vg version` say?**

```
vg version v1.44.0 "Solara"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```

**Comment by glennhickey** [comment]
There's some examples and documentation about using `vg call` [here](https://github.com/vgteam/vg/wiki/SV-Genotyping-and-variant-calling) and [here](https://github.com/vgteam/vg?tab=readme-ov-file#variant-calling), take note that it does not take a GAM file as input....
