### ISSUE TITLE
How to align both long and paired end short reads using vg

### ISSUE THREAD

**Issue by nathanLauHKGI** [vgteam/vg#4282]
Hi there

This is another clarification question:

Is there a recommended way align both long and paired end short reads using vg?

**Comment by jeizenga** [comment]
Paired-end short reads are fully supported. To access the paired-end features, you can use two `-f` arguments to provide the R1 and R2 reads. We are currently developing long-read alignment support, but these features are still experimental. You shouldn't yet expect a consistent interface or consistent performance for `giraffe`'s long-read mapping.
