### ISSUE TITLE
VG Construct will load the first variant when it shouldn't/not load subsequent variants when it should

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#431]
I fed `vg construct` a VCF where all the variants were on contig `.`. `vg construct` added the first variant to my graph, but ignored all the others.

Changing the contig to `ref`, which was the name of my FASTA sequence, puts all the variants into the graph.

When the contig and sequence names don't match, I think that the first variant shouldn't be added to the graph at all.

**Comment by ekg** [comment]
That makes sense to me. Quirky bug.

**Comment by adamnovak** [comment]
Since this is a terrible issue (no reproduction) and since I basically redid the construction algorithm, I'm going to close this issue.
