### ISSUE TITLE
About vg call -a -A

### ISSUE THREAD

**Issue by JiadongZHONG** [vgteam/vg#4317]
Hi,

I have some confusion about the results of "vg call".

**1. Can novel variants be discovered using only "_vg call - a - A_" (without using the "_vg augment_" mode)?**
Because of your description: 
"_Warning Using vg augment for variant calling remains very experimental. It is not at all recommended for structural variant calling, and even for small variants, you will often get much more accurate results (at least on human) by projecting your alignment to BAM and running a linear variant caller such as DeepVariant._", 
But if not using "_vg augment_," I can only genotype the known variants in the graph?

**2. If "_vg call - a - A_" is only for genotyping known variants, what is the difference between it and PanGenie?**

**3. Can the result of "_vg call - a - A_" be treated as a file similar to "_.gvcf_" and then used for joint-calling? Or is it that it only needs to be simply merged (SNPs, not SVs), and then can perform QC, beagle imputation, and so on?**”

Thanks！

**Comment by glennhickey** [comment]
`vg call` (without `augment`) and `PanGenie` both only call variants that are represented in the graph.  They use quite different approaches and inputs: the graph and read coverage for call, the vcf and kmer coverage for pangenie.  

The idea behind `vg call -a` in indeed to be able to merge together multisample VCFs.  `-A` is for nested VCFs, and may make the output difficult to use.
