### ISSUE TITLE
Can GAF format reports the segment sequence and the query sequence?

### ISSUE THREAD

**Issue by Hendricks27** [vgteam/vg#4327]
To whom it may concern,

Thank you for making VG available and keeping it up to date. 
Personally, I use the gaf alignment format extensively, and I am hoping the gaf file can embed the query sequence (read sequence) and the segment sequence in gaf file probably using additional tags.
Btw, I use the --named-coordinate option most of the time. 
Thanks!

**Comment by adamnovak** [comment]
It looks like there's a "long form" of the `cs` tag we already use that can encode the query string, and also the string it was aligned to. See https://lh3.github.io/minimap2/minimap2.html

Would an option to output long-form `cs` tags work, or would you not want to need to decode those to get the sequences?

**Comment by Hendricks27** [comment]
Hi Adam,

Thank you so much for your timely reply! I forgot to mention I use VG Giraffe mostly. 
Is "cs:Z::58+GCGACCGCCCCCCCCCC" this the long format? 
I am using your CS tag already. However, it doesn't tell the sequence of the read. For instance, how could I reconstruct the read sequence regarding the matched region (:58 section)?
