### ISSUE TITLE
GAF file empty with vg giraffe

### ISSUE THREAD

**Issue by m-bogaerts** [vgteam/vg#4331]
Hello @jltsiren ,

I am trying to use vg giraffe while using a pangenome made with Minigraph Cactus. The main idea is that I have 5 different genomes from the same species (Harmonia axyridis - ladybird) and I would like to have the information about the reads that are mapping each genome. However, once I run vg giraffe, the resulting GAF file only gives * and no info in all lines:  

```
D00562:114:C94WFANXX:7:1111:16937:20541 125     *       *       *       *       *       *       *       *       *       0       fn:Z:D00562:114:C94WFANXX:7:1111:16937:20541
```

The command lines I have used are (in a SLURM cluster):

```
 cactus-pangenome ./js seq_file.txt --outDir hax-pg --outName hax-pg --reference haxRed --vcf --giraffe clip --gfa --gbz

vg giraffe -p -t 32 -Z hax-pg/hax-pg.gbz -d hax-pg/hax-pg.dist -m hax-pg/hax-pg.min \
    -f HOMO-N4.fq_1.gz -f HOMO-N4.fq_2.gz --output-format gaf > hax-homo-N4.gaf
```
I already checked that the fastq files I am using are not ordered in any specific way (they are the raw fastq files).

Do you have any idea about what could be happening?

Thank you very much in advance.

```
vg version 1.48.0
```

**Comment by xchang1** [comment]
@jltsiren I think this is a problem with the minimizers. There were a bunch of errors like this
`MinimizerIndex::find_offset(): Cannot find the offset for key 66075703255364729`

**Comment by jltsiren** [comment]
It sounds like the minimizer index is corrupted. You could try rebuilding it with:
```
vg minimizer -p -d graph.dist -o graph.min graph.gbz
```

Also, are what does the `vg giraffe` command output during initialization? Are there any errors/warnings?

**Comment by m-bogaerts** [comment]
Hello again,

It worked perfectly after rebuilding the minimizer index! Now I am getting this GAF output:
```
D00562:114:C94WFANXX:7:1111:1229:2161	125	0	125	+	<48413770<48413771<48413772<48413773<48413775<48413776<48413778<48413779<48413780<48413781<48413782	173	7	131	124	125	60	AS:i:130	bq:Z:CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGDFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG	cs:Z::76*AG:48	dv:f:0.008	fn:Z:D00562:114:C94WFANXX:7:1111:1229:2161	pd:b:1
```

I used to get these outputs while running vg giraffe (which I haven't got right now):
```
MinimizerIndex::find_offset(): Cannot find the offset for key 237432784254556
MinimizerIndex::find_offset(): Cannot find the offset for key 3709887253977
MinimizerIndex::find_offset(): Cannot find the offset for key 229929871826950668
MinimizerIndex::find_offset(): Cannot find the offset for key 68746704681186812
T19:    All minimizers:
T19:    00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000001111111111111111111111111
T19:    00000000001111111111222222222233333333334444444444555555555566666666667777777777
888888888899999999990000000000111111111122222
T19:    01234567890123456789012345678901234567890123456789012345678901234567890123456789
012345678901234567890123456789012345678901234
T19:    CGATTCGATGGGGTTTGAAAGACATCACTTCACTGCTACCTGTTTTTAACCNTGATGACCAACTTATAGGCGAGATTATT
CCGTAAAGGATTTTTTTTCATTATAATTGAATATTTAGCTGCAAT
T19:    -------ATGGGGTTTGAAAGACATCACTTCACTGC---------- (#0, 0 hits)
T19:            --------AAACAGGTAGCAGTGAAGTGATGTCTTTC---------- (#2, 0 hits)
T19:                     ---TTAAAAACAGGTAGCAGTGAAGTGATGTC---------- (#3, 0 hits)
```

Thank you very much!!
