### ISSUE TITLE
when i do the code :vg stats -a var1.gam > var1.stats ,show me a bug 

### ISSUE THREAD

**Issue by peanut-nu** [vgteam/vg#4346]
**1. What were you trying to do?**

**2. What did you want to happen?**

**3. What actually happened?**

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**

```
Place vg version output here
```

**Comment by jeizenga** [comment]
We'll need more information than this to effectively troubleshoot this problem. Can you fill out the template we issue report we provided?

**Comment by peanut-nu** [comment]
> We'll need more information than this to effectively troubleshoot this problem. Can you fill out the template we issue report we provided?

I'm so sorry. I was in such a hurry. I thought I'd uploaded it.
`terminate called after throwing an instance of 'std::runtime_error'
  what():  [vg::io::MessageIterator::operator++] (group 0) message of 2332715937 bytes is too long
━━━━━━━━━━━━━━━━━━━━
Crash report for vg v1.50.1 "Monopoli"
Stack trace (most recent call last) in thread 2608880:
#14   Object "", at 0xffffffffffffffff, in
#13   Object "/share/work/biosoft/tools/vg50.1", at 0x21472f3, in __clone
#12   Object "/share/work/biosoft/tools/vg50.1", at 0x20a09ba, in start_thread
#11   Object "/share/work/biosoft/tools/vg50.1", at 0x204329d, in gomp_thread_start
#10   Object "/share/work/biosoft/tools/vg50.1", at 0xded18b, in void vg::io::for_each_parallel_impl<vg::Alignment>(std::istream&, std::function<void (vg::Alignment&, vg::Alignment&)> const&, std::function<void (vg::Alignment&)> const&, std::function<bool ()> const&, unsigned long) [clone ._omp_fn.0]
#9    Object "/share/work/biosoft/tools/vg50.1", at 0x5d47ef, in vg::io::MessageIterator::take[abi:cxx11]() [clone .cold]
#8    Object "/share/work/biosoft/tools/vg50.1", at 0x205a49d, in _Unwind_Resume
#7    Object "/share/work/biosoft/tools/vg50.1", at 0x205991b, in _Unwind_RaiseException_Phase2
#6    Object "/share/work/biosoft/tools/vg50.1", at 0x1f960d9, in __gxx_personality_v0
#5    Object "/share/work/biosoft/tools/vg50.1", at 0x20305e8, in __cxa_call_terminate
#4    Object "/share/work/biosoft/tools/vg50.1", at 0x1f9698b, in __cxxabiv1::__terminate(void (*)())
#3    Object "/share/work/biosoft/tools/vg50.1", at 0x5e29e3, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#2    Object "/share/work/biosoft/tools/vg50.1", at 0x5e512b, in abort
#1    Object "/share/work/biosoft/tools/vg50.1", at 0x20757d5, in raise
#0    Object "/share/work/biosoft/tools/vg50.1", at 0x20a21dc, in __pthread_kill
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Please include this entire error log in your bug report!`
