### ISSUE TITLE
vg view simple-dot error

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#436]
Simplified dot output doesn't seem to work when piped into dot:
```
vg view -dS tiny.vg | dot -Tsvg -o tiny.vg

Error: <stdin>: syntax error in line 4 near '"'
```

(vg version v1.4.0-1017-g0042f59 -- this worked with a mid-April compilation of vg)

**Comment by ekg** [comment]
As a baseline, can you do regular dot rendering? The support for this
improved and it may not be necessary to use simple mode on some graphs.

**Comment by hgibling** [comment]
Yes, regular dot is fine.

**Comment by ekg** [comment]
One of the reasons for the simple dot was to get around dot bugs with the
edge ports I was specifying.

But it does look like you've run into a bug with the simple mode. I'll try
to track it down.

**Comment by hgibling** [comment]
I noticed the `libpath/shortest.c:324: triangulation failed` messages were gone :)

**Comment by adamnovak** [comment]
I noticed something similar a while ago; I think @buske broke simple rendering when he added all that HTML stuff to fix the port triangulation. HTML is being dumped into the simple-mode DOT and nothing is getting escaped and it's making graphviz very sad,

The solution is probably to not dump all that HTML or try to use ports in in simple mode---it is, after all, supposed to be simple.

**Comment by buske** [comment]
Ack, sorry! Yeah, the explicit HTML ports seem like overkill for simple mode and should probably be turned off.
