### ISSUE TITLE
vg call error

### ISSUE THREAD

**Issue by aaaniich** [vgteam/vg#4360]
Good afternoon!
I created a pangenome based on two references: grch38, chm13. However, when collating variants using vg call, I get this error
If I try to pass through flags -p grch38 -p chm13, it also shows that it doesn't see the paths 

**error [vg call]: Multiple reference samples detected: [chm13, grch38]. Please use -S to specify a single reference sample or use -p to specify reference paths**

**Comment by glennhickey** [comment]
Try `-S chm13` OR `-S grch38`

**Comment by aaaniich** [comment]
Thanks!!

> Try `-S chm13` OR `-S grch38`
