### ISSUE TITLE
Error when trying to map reads to a spliced-pangenome

### ISSUE THREAD

**Issue by CarlosAmadeo7** [vgteam/vg#4390]
Hello vg team 
I am trying to run a haplotype-expression analysis using rpvg. 
I am using a spliced-pangenome and a pantranscriptome that have already been created. The respective pangenomes and files associated to run rpvg can be found in this location : https://cgl.gi.ucsc.edu/data/vgrna/hprc_analyses/graphs/minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32/
 
While I am trying to map paired-end reads to the spliced pangenome I am using this command :
vg mpmap -t 4 -x spliced_pangenome.xg -g spliced_pangenome.gcsa -d spliced_pangenome.dist -f rna_1.fq -f rna_2.fq > mpmap.gamp 

However, I am receiving the following error:
![error](https://github.com/user-attachments/assets/16c0228a-9637-4ab0-88f5-5dfeec40331e)

I would appreciate your comments and guidance to help me fixing this error so I can continue with the analysis.
I hope for your prompt response.
Best

**Comment by jltsiren** [comment]
The distance index you have seems to be an old version no longer supported by recent versions of vg. You need to rebuild it with:

```
vg index -j graph.dist graph.xg
```

**Comment by CarlosAmadeo7** [comment]
I see, thank you for the information. 

I am trying to get some results from the paper: Haplotype-aware pantranscriptome analyses using spliced pangenome graphs.
I am using some files that they have used,  such as : 
  minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.dist | 2022-07-04 03:54 |
  | minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.gbwt | 2022-10-24 04:07 |  
  | minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.gbwt.ri | 2022-10-24 04:07 |  
  | minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.gcsa | 2022-07-04 03:55 |  
  | minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.gcsa.lcp | 2022-07-04 03:55 |  
  | minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.txt.gz | 2022-10-24 04:07 | 
  | minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.xg

If the distance index seems to be not updated, could it also mean that all these files are not updated too?
Best

**Comment by jeizenga** [comment]
I don't think we've updated any of the other file formats.

**Comment by CarlosAmadeo7** [comment]
So what would be your recommendation, please?

**Comment by jeizenga** [comment]
Update the distance index with the command above from @jltsiren and then use the result in place of `minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.dist`.

**Comment by CarlosAmadeo7** [comment]
Thank you for the clarification. Just one more question: In the command above **vg index -j graph.dist graph.xg**;  is the graph.xg the original human pangenome-graph or is it the spliced pangenome graph which is the minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32.xg
I appreciate your patient

**Comment by jeizenga** [comment]
You would want to use the spliced pangenome graph.

**Comment by CarlosAmadeo7** [comment]
Thank you so much, it worked perfectly
