### ISSUE TITLE
Issue Converting PGGB GFA Files for Panacus

### ISSUE THREAD

**Issue by OZTaekOppa** [vgteam/vg#4392]
**1. What were you trying to do?**
Dear VG team,
After generating GFA files for each chromosome using PGGB, I need to merge them for Panacus. However, the Panacus team confirmed that a simple cat command to merge PGGB GFA files won't work. 

**2. What did you want to happen?**
I was advised to convert the PGGB GFA files into VG-compatible GFA format.

**3. What actually happened?**
Here’s what I tried in Step 2 (Convert PGGB GFA to VG-compatible GFA):
vg convert -fW -t ${PBS_NCPUS} -g ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.vg1.gfa
vg convert -f -t ${PBS_NCPUS} -g ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.vg2.gfa

Both commands produced only a single line: H VN:Z:1.1, without any error messages or meaningful output.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

The following steps would be:
Step 3: Merge VG GFA files using vg combine
vg combine $(find -L ${PGGB_GFA} -type f -name "*.vg.gfa") > ${OUTPUT_DIR}/chrAll_merged_pggb.smooth.final.vg.gfa

Step 4: Convert merged VG to GFA
vg view --threads ${PBS_NCPUS} -F -v ${OUTPUT_DIR}/chrAll_merged_pggb.smooth.final.vg.gfa > ${OUTPUT_DIR}/chrAll_merged_pggb_convert.smooth.final.vg.gfa

Step 5: Validate final GFA file
vg validate ${OUTPUT_DIR}/chrAll_merged_pggb_convert.smooth.final.vg.gfa
 
Unfortunately, Step 2 did not produce any usable output for proceeding with the next steps.

Do you have any suggestions on how to resolve this issue?

Regards,

Taek

**6. What does running `vg version` say?**

No error messages or meaningful output.

```
I used vg version 1.56.0 from bioconda.
```

**Comment by AndreaGuarracino** [comment]
Have you already tried to merge the GFAs with odgi squeeze?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Taek Wizard ***@***.***>
Sent: Monday, September 9, 2024 8:36:00 PM
To: vgteam/vg ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vgteam/vg] Issue Converting PGGB GFA Files for Panacus (Issue #4392)


1. What were you trying to do?
Dear VG team,
After generating GFA files for each chromosome using PGGB, I need to merge them for Panacus. However, the Panacus team confirmed that a simple cat command to merge PGGB GFA files won't work.

2. What did you want to happen?
I was advised to convert the PGGB GFA files into VG-compatible GFA format.

3. What actually happened?
Here’s what I tried in Step 2 (Convert PGGB GFA to VG-compatible GFA):
vg convert -fW -t ${PBS_NCPUS} -g ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.vg1.gfa
vg convert -f -t ${PBS_NCPUS} -g ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.vg2.gfa

Both commands produced only a single line: H VN:Z:1.1, without any error messages or meaningful output.

4. If you got a line like Stack trace path: /somewhere/on/your/computer/stacktrace.txt, please copy-paste the contents of that file here:

Place stacktrace here.


5. What data and command can the vg dev team use to make the problem happen?

The following steps would be:
Step 3: Merge VG GFA files using vg combine
vg combine $(find -L ${PGGB_GFA} -type f -name "*.vg.gfa") > ${OUTPUT_DIR}/chrAll_merged_pggb.smooth.final.vg.gfa

Step 4: Convert merged VG to GFA
vg view --threads ${PBS_NCPUS} -F -v ${OUTPUT_DIR}/chrAll_merged_pggb.smooth.final.vg.gfa > ${OUTPUT_DIR}/chrAll_merged_pggb_convert.smooth.final.vg.gfa

Step 5: Validate final GFA file
vg validate ${OUTPUT_DIR}/chrAll_merged_pggb_convert.smooth.final.vg.gfa

Unfortunately, Step 2 did not produce any usable output for proceeding with the next steps.

Do you have any suggestions on how to resolve this issue?

Regards,

Taek

6. What does running vg version say?

No error messages or meaningful output.

I used vg version 1.56.0 from bioconda.

**Comment by jeizenga** [comment]
If you want to do this in the `vg` universe, I think the strategy would be to convert into VG formats with `vg convert -g graphX.gfa > graphX.vg, then combine them with `vg combine graphX.vg graphY.vg > graphXY.vg`, and then convert to GFA with `vg convert -f graphXY.vg > graphXY.gfa`.

**Comment by OZTaekOppa** [comment]
Thank you @AndreaGuarracino and @jeizenga!
I will get back to you after testing your suggestions.
Cheers,
Taek

**Comment by OZTaekOppa** [comment]
FYI, odgi squeeze worked well for the Panacus. 
Thanks!
