### ISSUE TITLE
Hello, I have a question about vg map.

### ISSUE THREAD

**Issue by pioneer-pi** [vgteam/vg#4398]
I check out the result(GAM file) of vg map. I found that there are some question in base repeat region. If there is a few bp deletion/insertion, the mapping information may represent this mismatch in the middle of this region rather than the begin of this region. Can this question be soloved?

For example:
Ref:    TATATATA
Read: TATATA
Then the mapping result may be  4M2D(four base match, then 2 base deletion), rather than(2D4M). I would like to the latter result.

**Comment by jeizenga** [comment]
Unfortunately, `vg map` doesn't have an easy way to consistently left- or right-align indels. If you're projecting to BAM with `vg surject` or `vg map --surject-to bam`, then you can use a tool like `freebayes bamleftalign`, but I don't know of anything like that for GAM or GAF files.
