### ISSUE TITLE
vg build fails on Apple M1 pro running Sequoia 15.0.1

### ISSUE THREAD

**Issue by dmgood11** [vgteam/vg#4414]
M1 Pro Mac running Sequoia 15.0.1
using a clean Homebrew install and a clean Xcode install.

```
$ clang --version
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ brew --version
Homebrew 4.4.0

$ echo $OpenMP_ROOT 
/opt/homebrew/opt/libomp

$ ls $OpenMP_ROOT 
INSTALL_RECEIPT.json	
include
lib
sbom.spdx.json
```

**1. What were you trying to do?**
build vg from source on an M1 Pro (Apple Silicon) running Sequoia 15.0.1

**2. What did you want to happen?**
successful build of the vg executable

**3. What actually happened?**

build ultimately fails with what seems like a problem linking in libomp while building gbwt:

```
$tail build.log 
      gbwt::MergeBuffers::write(gbwt::GapArray<gbwt::BlockArray>&) in libgbwt.a[3](bwtmerge.o)
      gbwt::DynamicGBWT::remove(std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long>> const&, unsigned long long) (.omp_outlined) in libgbwt.a[5](dynamic_gbwt.o)
      gbwt::buildRA(gbwt::DynamicGBWT const&, gbwt::DynamicGBWT const&, gbwt::MergeBuffers&) (.omp_outlined) in libgbwt.a[5](dynamic_gbwt.o)
  "_omp_get_wtime", referenced from:
      gbwt::readTimer() in libgbwt.a[13](utils.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/build_gbwt] Error 1
rm obj/build_gbwt.o
make: *** [lib/libgbwt.a] Error 2
``
**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

I've attached the build log.

**5. What data and command can the vg dev team use to make the problem happen?**
Follow the Mac OS build instructions on an M1 mac running sequoia, having satisfied dependencies via Homebrew or MacPorts.

**6. What does running `vg version` say?**
vg does not build so no running vg to check.  vg source acquire via
```
$git clone --recursive https://github.com/vgteam/vg.git
```
[build.log](https://github.com/user-attachments/files/17267334/build.log)

**Comment by jltsiren** [comment]
This seems to be the issue:

```
ld: warning: ignoring file '/usr/local/Cellar/libomp/10.0.1/lib/libomp.dylib': found architecture 'x86_64', required architecture 'arm64'
```

You have an old x86 version of libomp installed under `/opt/homebrew`, while the right version is a keg-only install under `/opt/homebrew/opt/libomp`. Some parts of the vg build system have been updated to use the keg-only install (which has been the default for a while), while other parts still expect that libomp has been linked into `/opt/homebrew`.

If Apple Clang is the only C/C++ compiler you use, you should be able to fix this particular issue with:

```
brew unlink libomp && brew link --force libomp
```

But if you are using other compilers, this may break OpenMP for them.

**Comment by dmgood11** [comment]
Thank you for the suggestion.

After 
```
$make clean
$brew unlink libomp && brew link --force libomp
$ . ./source_me.sh && make > build.log 2>&1
```
I'm still getting the same error:

```
$ ls -l build.log 
-rw-r--r--  1 DMGoodstein-M65  staff  137708 Oct  5 22:15 build.log
$ tail build.log 
      gbwt::MergeBuffers::write(gbwt::GapArray<gbwt::BlockArray>&) in libgbwt.a[3](bwtmerge.o)
      gbwt::DynamicGBWT::remove(std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long>> const&, unsigned long long) (.omp_outlined) in libgbwt.a[5](dynamic_gbwt.o)
      gbwt::buildRA(gbwt::DynamicGBWT const&, gbwt::DynamicGBWT const&, gbwt::MergeBuffers&) (.omp_outlined) in libgbwt.a[5](dynamic_gbwt.o)
  "_omp_get_wtime", referenced from:
      gbwt::readTimer() in libgbwt.a[13](utils.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/build_gbwt] Error 1
rm obj/build_gbwt.o
make: *** [lib/libgbwt.a] Error 2
```

build log attached again.

**Comment by jltsiren** [comment]
I don't see the attached log. Did you remove the link to it?

**Comment by dmgood11** [comment]
Apologies
[build.log](https://github.com/user-attachments/files/17268360/build.log)

**Comment by jltsiren** [comment]
According to the log, you still have libomp 10.0.1 for x86 installed. The latest version on Homebrew is 19.1.0.

What does `brew info libomp` say?

Is the Homebrew you are using the ARM version, or the x86 version running in Rosetta 2?

If you migrated the home directory from an Intel Mac to an ARM Mac, did you uninstall Homebrew and everything you installed with it before installing the ARM version?

**Comment by dmgood11** [comment]
```
(VG) MacBook-Pro-3:vg DMGoodstein-M65$ brew info libomp
==> libomp: stable 19.1.0 (bottled) [keg-only]
LLVM's OpenMP runtime library
https://openmp.llvm.org/
Installed
/opt/homebrew/Cellar/libomp/19.1.0 (9 files, 1.7MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-05 at 22:08:45
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libomp.rb
License: MIT
==> Dependencies
Build: cmake ✔, lit ✘
==> Caveats
libomp is keg-only, which means it was not symlinked into /opt/homebrew,
because it can override GCC headers and result in broken builds.

For compilers to find libomp you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
==> Analytics
install: 49,049 (30 days), 117,036 (90 days), 557,315 (365 days)
install-on-request: 9,718 (30 days), 22,470 (90 days), 110,858 (365 days)
build-error: 7 (30 days)
```
I'm definitely using the ARM version:
```
(VG) MacBook-Pro-3:vg DMGoodstein-M65$ brew config
HOMEBREW_VERSION: 4.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84c31175f11860129a9aaed40a13c549625e2db1
Last commit: 6 days ago
Core tap JSON: 06 Oct 05:08 UTC
Core cask tap JSON: 06 Oct 05:08 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```

**Comment by dmgood11** [comment]
after manually removing:
```
$rm -fr usr/local/Cellar/libomp/
$rm -fr /usr/local/var/homebrew/linked/libomp 
$rm -fr /usr/local/opt/libomp

the build got further along, but failed again on an architecture issue, this time for protobuf:
```
Undefined symbols for architecture arm64:
  "google::protobuf::Arena::AllocateForArray(unsigned long)", referenced from:
      std::__1::pair<google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, google::protobuf::Value>::iterator, bool> google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, google::protobuf::Value>::TryEmplaceInternal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) in annotation.o
```
I should also report that another team member, who has a "greenfield" Apple Silicon mac (meaning not cloned from a previous X86 laptop, so no chance of vestigial X86 libraries), has encountered the same issues.  

[build.log](https://github.com/user-attachments/files/17287030/build.log)

**Comment by jltsiren** [comment]
Unfortunately I can't help you further. (Maybe @adamnovak can.) Protobuf issues are common, but I've never been able to fix them on my own.

**Comment by dmgood11** [comment]
Thanks anyway Jouni.  I did wrangle up an older x86 iMac so I can do some local development on that.  If you do hear of anyone who has gotten vg build from source on Apple Silicon I’d like to ping them.


Best,
-David

**Comment by jltsiren** [comment]
Apple Silicon is not the issue. The troubles come from being the first person to upgrade to the latest major version of macOS. I usually wait until February or March, because the upgrade usually breaks something.

**Comment by dmgood11** [comment]
Removing /opt/local/lib/libprotobuf* (leaving just my Homebrew installed protobuf libraries, which are the right architecture) did the trick.  I (finally) have a working vg build.

Best,
-David
