### ISSUE TITLE
A question about vg filter.

### ISSUE THREAD

**Issue by pioneer-pi** [vgteam/vg#4424]
I want to extract reads which mapping to chr1 from gam file, how could I do this through vg filter or other vg's command?

Thank you

**Comment by glennhickey** [comment]
`vg chunk -x <graph> -a <gam> -C -p <path name, ex chr1>`  then look for the result in `chunk_chr1.gam`

**Comment by pioneer-pi** [comment]
Thank you, I get it!

**Comment by pioneer-pi** [comment]
Hello, I use vg giraffe to map reads to `pangenome.giraffe.gbz` and get `map.gam`. I check map.gam and find it's different with the result of gam file which map use `vg map`. Some tags are different. And I have two questions:
1. If I want to  extract reads which mapping to chr1 from map.gam file. There is no xg file.How should I do?
2. If I want to use the map.gam file to augment the org vg graph.(Like `vg augment -x *.xg -A *.gam *.gam > *_aug.vg`). Can I use this function with `vg giraffe`
