### ISSUE TITLE
Add read de-fraying to `vg filter`

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#443]
There should be a feature in `vg filter` where it can look at reads and find ambiguous alignments at their ends (for example, cases where a read reads into but does not span a variable-length homopolymer, and has arbitrarily been aligned to one of two equivalent paths), and then trim back the read to the point of ambiguous divergence.

We anticipate that this will reduce the number of false positives called from the `vg call` pipeline.

The easiest way to do this is probably some kind of string-matching search, but it would be nice if we could re-use searches and not re-do all the work for all the reads overlapping a potentially ambiguous branch point.

**Comment by glennhickey** [comment]
If you want, you can just replace the 5-minute repeat filter I did
yesterday afternoon:

https://github.com/vgteam/vg/blob/master/src/main.cpp#L442-L461

and re-use the option (only catch is that you'll have to change it to
modify and not throw out the read but that shoudn't be too hard).  vg
filter is needlessly complicated by always comparing primary secondary
pairs before doing anything -- functionality that's all but been forgotton
now i hitnk

**Comment by adamnovak** [comment]
That looks like the chunking code and not the depth filter. But I will see if I can replace it or mimic it.

I'm hesitant to really replace it because I'm simultaneously trying to run the assembly remapping evaluation with your new parameter set that uses it...

**Comment by glennhickey** [comment]
Oops  https://github.com/vgteam/vg/blob/master/src/main.cpp#L527-L548
