### ISSUE TITLE
"vg giraffe" crash

### ISSUE THREAD

**Issue by pliang64** [vgteam/vg#4458]
**1. What were you trying to do?**
``` vg giraffe -t 30 -Z HPRC/hprc-v1.1-mc-chm13.gbz -f hprc.sim1000-150.gam -o BAM -p > test.mapped.bam```

**2. What did you want to happen?**
generation of the alignment file in bam format

**3. What actually happened?**
Loading Distance Index v2
Paging in Distance Index v2
Initializing MinimizerMapper
Loading and initialization: 7551.15 seconds
Of which Distance Index v2 paging: 9.12964 seconds
Mapping reads to "-" (BAM)
--watchdog-timeout 10
--match 1
--mismatch 4
--gap-open 6
--gap-extend 1
--full-l-bonus 5
--max-multimaps 1
--hit-cap 10
--hard-hit-cap 500
--score-fraction 0.9
--max-min 500
--num-bp-per-min 1000
--distance-limit 200
--max-extensions 800
--max-alignments 8
--cluster-score 50
--pad-cluster-score 20
--cluster-coverage 0.3
--extension-score 1
--extension-set 20
--rescue-attempts 15
--max-fragment-length 2000
--paired-distance-limit 2
--rescue-subgraph-size 4
--rescue-seed-limit 100
--chaining-cluster-distance 100
--precluster-connection-coverage-threshold 0.3
--min-precluster-connections 10
--max-precluster-connections 50
--max-lookback-bases 100
--min-lookback-items 1
--lookback-item-hard-cap 15
--chain-score-threshold 100
--min-chains 1
--chain-min-score 100
--max-chain-connection 100
--max-tail-length 100
--max-dp-cells 16777216
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found unexpected delimiter ? in fastq/fasta input
━━━━━━━━━━━━━━━━━━━━
Crash report for vg v1.60.0 "Annicco"
Stack trace (most recent call last):
#19   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x623574, in _start
#18   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20e2396, in __libc_start_main
#17   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20e0af9, in __libc_start_call_main
#16   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0xe16d0b, in vg::subcommand::Subcommand::operator()(int, char**) const
#15   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0xd3a33a, in main_giraffe(int, char**)
#14   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0xdd1caf, in std::_Function_handler<void (std::function<void ()> const&), vg::subcommand::TickChainLink::get_iterator()::{lambda(std::function<void ()> const&)#1}>::_M_invoke(std::_Any_data const&, std::function<void ()> const&)
#13   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0xd354a5, in main_giraffe(int, char**)::{lambda()#1}::operator()() const
#12   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0xec9c2c, in vg::fastq_unpaired_for_each_parallel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (vg::Alignment&)>, unsigned long)
#11   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20be2b5, in GOMP_parallel
#10   Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0xed3ebd, in unsigned long vg::io::unpaired_for_each_parallel<vg::Alignment>(std::function<bool (vg::Alignment&)>, std::function<void (vg::Alignment&)>, unsigned long) [clone ._omp_fn.0]
#9    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x53952c, in vg::get_next_alignment_from_fastq(gzFile_s*, char*, unsigned long, vg::Alignment&) [clone .cold]
#8    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20de1fd, in _Unwind_Resume
#7    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20dd67b, in _Unwind_RaiseException_Phase2
#6    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x2019e99, in __gxx_personality_v0
#5    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20b4348, in __cxa_call_terminate
#4    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x201a74b, in __cxxabiv1::__terminate(void (*)())
#3    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x5ef9ab, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#2    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x5f20f3, in abort
#1    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x20f9575, in raise
#0    Object "/project/6006653/lianglab-def/bin/cactus-bin-v2.9.2/bin/vg", at 0x21260cc, in __pthread_kill
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Please include this entire error log in your bug report!
━━━━━━━━━━━━━━━━━━━━

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

**6. What does running `vg version` say?**

```
vg version v1.60.0 "Annicco"
Compiled with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 on Linux
Linked against libstd++ 20230528
```

**Comment by jltsiren** [comment]
With GAM input, you should use option `-G` / `--gam-in`. Option `-f` / `--fastq-in` expects FASTQ, though it apparently also works with FASTA.

**Comment by pliang64** [comment]
Thank you very Jouni. It fixed the issue.
