### ISSUE TITLE
Something weird about vg giraffe

### ISSUE THREAD

**Issue by dudududu12138** [vgteam/vg#4468]
Hi, I use vg's pipeline to get an .xg graph and align reads to the whole graph. My vg version is v1.61.0 "Plodio". And I use the MinigraphCactus graph ([gbz](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.d9.gbz), [dist](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.d9.dist), [min](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.d9.min)). While there are some questions during use. And I listed below.

### Question 1 
Because HPRC didn't give a `.XG` file of their graph, so I use `vg convert` to get the `.xg` file. And there is no `gbwt` file so I use [.gbz](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.d9.gbz) to get the `.xg`. I don't know whether it is reasonable. Below is my code:

```
vg convert -t 80 -x hprc-v1.1-mc-grch38.d9.gbz >hprc-v1.1-mc-grch38.d9.xg
```

### Questsion 2
I use `vg giraffe` to align short reads to the graph listed above. Below is my code:

```
vg giraffe -t $cpu \
        -Z $refroot/hprc-v1.1-mc-grch38.d9.gbz \
        -d $refroot/hprc-v1.1-mc-grch38.d9.dist \
        -m $refroot/hprc-v1.1-mc-grch38.d9.min \
        -f $fastq1 -f $fastq2   -N $sample -R $sample  >$outdir/$sample.gam
```
While there are 2 problems:
(1) vg giraffe just running without results. That is , it doesn't report error but the result `.gam` file is always null for several hours(more than 10 hours). And while I cancel the job and resubmit it, the alignment results started to produce normally and finished in less than 30min.
(2) I tested the difference between putting the `xg` file in the same folder as the other index files(.gbz,.dist,.min) and in a different folder. While they are in different folders, the log file is biref, just like this: 
```
warning[vg::giraffe]: Refusing to perform too-large tail alignment of 90 bp against 18284 bp tree which would use more than 1572864 cells and might exhaust Dozeu's allocator; suppressing further warnings.
warning[vg::giraffe]: Refusing to perform too-large rescue alignment of 150 bp against 11478 bp ordered subgraph for read A00217:15:H23TKDSXX:1:1101:20491:14810 which would use more than 1572864 cells and might exhaust Dozeu's allocator; suppressing further warnings.
```
But while they are in the same folder with the same code, the log file is long and the problem in (1) also appears. So will vg giraffe use the `.xg` file automatically even I don't listed it in my code? Blow is a cut of the long log file:
```
Guessing that hprc-v1.1-mc-grch38.d9.xg is XG
warning[vg::Watchdog]: Thread 6 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:19569:3975, A00217:15:H23TKDSXX:2:1101:19569:3975
warning[vg::Watchdog]: Thread 18 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:26458:5102, A00217:15:H23TKDSXX:2:1101:26458:5102
warning[vg::Watchdog]: Thread 21 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:30843:2863, A00217:15:H23TKDSXX:2:1101:30843:2863
warning[vg::Watchdog]: Thread 24 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:17897:4617, A00217:15:H23TKDSXX:2:1101:17897:4617
warning[vg::Watchdog]: Thread 36 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:22996:3333, A00217:15:H23TKDSXX:2:1101:22996:3333
warning[vg::Watchdog]: Thread 36 finally checked out after 10 seconds and 0 kb memory growth processing: A00217:15:H23TKDSXX:2:1101:22996:3333, A00217:15:H23TKDSXX:2:1101:22996:3333
warning[vg::Watchdog]: Thread 4 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:5963:6684, A00217:15:H23TKDSXX:2:1101:5963:6684
warning[vg::Watchdog]: Thread 31 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:9127:7498, A00217:15:H23TKDSXX:2:1101:9127:7498
warning[vg::Watchdog]: Thread 32 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:10294:6198, A00217:15:H23TKDSXX:2:1101:10294:6198
warning[vg::Watchdog]: Thread 38 has been checked in for 10 seconds processing: A00217:15:H23TKDSXX:2:1101:20112:1783, A00217:15:H23TKDSXX:2:1101:20112:1783
```
Thank you very much! Looking forward to your reply.

**Comment by dudududu12138** [comment]
Hi, I checked again and I got some new information.It seems that `vg giraffe` can only run one task at a time. That is, if I submit 2 alignment jobs to my server, `vg giraffe` will run in turn rather than simultaneously. So the `.gam` file will generate normally while the previous job finished. It is so weired.

**Comment by jltsiren** [comment]
There is documentation on some common Giraffe issues / pitfalls in the [vg wiki](https://github.com/vgteam/vg/wiki/Giraffe-best-practices).

In particular:
* Because the distance index is a memory-mapped file, there could be issues when multiple systems try to access it simultaneously. In such cases, it is usually enough to make the file read-only.
* An XG graph can sometimes make SAM/BAM/CRAM output faster. It is not used with GAM/GAF output. If you want to convert GBZ to XG, you probably want to use option `--drop-haplotypes` in the `vg convert` command. Otherwise the haplotype paths can make the XG file massive.

**Comment by dudududu12138** [comment]
> There is documentation on some common Giraffe issues / pitfalls in the [vg wiki](https://github.com/vgteam/vg/wiki/Giraffe-best-practices).
> 
> In particular:
> 
> * Because the distance index is a memory-mapped file, there could be issues when multiple systems try to access it simultaneously. In such cases, it is usually enough to make the file read-only.
> * An XG graph can sometimes make SAM/BAM/CRAM output faster. It is not used with GAM/GAF output. If you want to convert GBZ to XG, you probably want to use option `--drop-haplotypes` in the `vg convert` command. Otherwise the haplotype paths can make the XG file massive.

Thank you so much! So If there is only `.gbz`,`.min`,`.dist`,`.snarl` for a graph and I want to get the `.xg` file, the correct way is to use `.gbz` file and attach the `--drop-haplotypes`  parameter?

**Comment by jltsiren** [comment]
In most cases, you should use `--drop-haplotypes` whenever you convert a GBZ graph to another format. No other graph type can store a large number of haplotypes efficiently. The main exception is when you know that you are going to need the haplotype paths.

Commands like `vg pack` that do not change the graph itself work with any graph type, including GBZ. The name of the option used for graph input may mention XG for historical reasons. In some cases, another graph type can be more efficient than GBZ, but it's no longer as common as it used to be. `vg pack` loads a `HandleGraph`, which means that the presence of paths (haplotype, reference, or generic) has no effect on the outcome.

**Comment by glennhickey** [comment]
From `vg pack -h`:

```
usage: vg pack [options]
options:
    -x, --xg FILE          use this basis graph (any format accepted, does not have to be xg)
```

**Comment by dudududu12138** [comment]
> In most cases, you should use `--drop-haplotypes` whenever you convert a GBZ graph to another format. No other graph type can store a large number of haplotypes efficiently. The main exception is when you know that you are going to need the haplotype paths.
> 
> Commands like `vg pack` that do not change the graph itself work with any graph type, including GBZ. The name of the option used for graph input may mention XG for historical reasons. In some cases, another graph type can be more efficient than GBZ, but it's no longer as common as it used to be. `vg pack` loads a `HandleGraph`, which means that the presence of paths (haplotype, reference, or generic) has no effect on the outcome.


> From `vg pack -h`:
> 
> ```
> usage: vg pack [options]
> options:
>     -x, --xg FILE          use this basis graph (any format accepted, does not have to be xg)
> ```

Thanks！I know `vg pack` can now all be run on directly on any graph format. But will running vg pack using different formats of the same graph give the same results? Will there be differences?

**Comment by jltsiren** [comment]
There should be no differences from using different graph formats in `vg pack`.
