### ISSUE TITLE
How to rename the paths in the surject result(.bam)

### ISSUE THREAD

**Issue by dudududu12138** [vgteam/vg#4470]
Hi, I used the Minigraph Cactus graph as a reference for analysis. And I ran `vg surject` to convert my `.gam` result to `.bam`. But the path name in Minigraph Cactus is like `GRCh38#0#chr1`, so the contig names in the surject result bam file are also like this. Is there any parameter to change the contig name? Just leave “chr1” and delete “GRCh38#0#”? Or is it only possible to change it myself with a shell script?

**Comment by jltsiren** [comment]
The current convention is specifying the reference sample explicitly, because graphs often have multiple reference samples (such as GRCh38 and CHM13). `chr1` would not tell unambiguously which sequence the reads are aligned to. The names can be changed easily enough with other tools.
