### ISSUE TITLE
FastG output

### ISSUE THREAD

**Issue by alexjironkin** [vgteam/vg#45]
Hi,

Would you be interested in outputting into fastg format to then view it in @rrwick Bandage tool?

**Comment by ekg** [comment]
Yes. If this is your itch, please scratch it. You can follow the functions
in `vg::VG::to_gfa(...)` to see how to do so.

What I'm really interested in is a visualization of the alignments.

**Comment by alexjironkin** [comment]
Intersting. Well in this visualiser you can colour nodes with different colours along the length. Could you not use that to reflect the mapping quality on the graph?

**Comment by ekg** [comment]
That would work, but I can already do that with dot output. I'm interested
in seeing the alignments (and paths, generally) in some way.

**Comment by ekg** [comment]
I've worked a bit on multi-path visualization:

![screenshot from 2015-10-07 17 33 15](https://cloud.githubusercontent.com/assets/145425/10342742/d3b12e42-6d1a-11e5-90e0-c47f60527ff7.png)

I know this isn't FASTG. However, if you can convert GFA to FASTG then I think we're good. Do you know if this is possible?

**Comment by rrwick** [comment]
Converting GFA to FASTG shouldn't be necessary, as I've added GFA support to Bandage.  That being said, it hasn't gotten a lot of testing, so I'd be interested in getting my hands on a vg-produced GFA file to make sure that everything works as it should.

If you could email one to me (rrwick@gmail.com), I'd appreciate it and will let you know how it goes!

**Comment by edawson** [comment]
We've updated the GFA parser/producer in VG and I've tested it with Bandage - they great together from what I've seen. I've attached a trivial example made with `vg construct -r x.fa | vg view -g - > x.gfa.txt`

[x.gfa.txt](https://github.com/vgteam/vg/files/483658/x.gfa.txt)

**Comment by adamnovak** [comment]
Since we now have a GFA bridge to Bandage, I don't think we need FastG.
