### ISSUE TITLE
overview of components of vg

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#480]
@vnsk asks:

> Is there any presentation or tutorial kind of thing on how the modules
work in vg?

@edawson has hugely cleaned up the wiki: https://github.com/vgteam/vg/wiki

Have you looked through that recently?

**Comment by edawson** [comment]
Here: https://github.com/vgteam/vg/wiki/File-Formats
 and here : https://github.com/vgteam/vg/wiki/Basic-Operations

are especially helpful sections. I'm still working on improving the Quickstart to include more functionality and haven't begun to explain the data model in wiki format, but those two improvements will come in time.

@vnsk if you have any requests please post them and I will do my best to address them specifically!

**Comment by vnsk** [comment]
Thanks !..will go through them.
