### ISSUE TITLE
vg index: Node::encode(): Offset xxxx too large

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#523]
I'm having problems running `vg index` on a graph.

`vg index -x Pt_2ins.xg -g Pt_2ins.gcsa -k 11 Pt_2ins.vg`

It quickly starts throwing error messages like:
`Node::encode(): Offset 1065 too large` and quits with:
 `PathGraphBuilder::write(): Size limit exceeded, construction aborted`
The `.xg` index is created, but the `.gcsa` file is not. If tried to run `vg index` with`--edge-max 3`, but it does not make a difference.

The graph was converted from an progressiveCactus alignment using [hal2vg](https://github.com/glennhickey/hal2vg) but `vg validate` does not return an error and I have indexed much bigger graphs before.

The graph is fairly simple (7 nodes, 11 edges) and covers a sequence of ~6kb.

![pt_2ins](https://cloud.githubusercontent.com/assets/20687698/19800222/1716efd0-9cfb-11e6-97ce-ba7e7d9dcc4e.png)

I have appended the vg file and the error log as a zip archive.
[Pt_2ins.zip](https://github.com/vgteam/vg/files/558121/Pt_2ins.zip)

**Comment by ekg** [comment]
@ChriKub the problem is that GCSA2 only supports nodes up to 1024 bases long.

Also, shorter nodes help a number of operations in vg. However, very short nodes (1bp) tend to increase memory usage. In practice, we are usually making graphs with maximum node sizes between 32 and 64 bp.

There is a quick fix. Use `vg mod -X 32 Pt_2ins.vg >Pt_2ins.32bp.vg` to chop the nodes of your graph to be less than 32bp. Then proceed as before with indexing of `Pt_2ins.32bp.vg`.

**Comment by ChriKub** [comment]
Thanks! That fixed it. 
Is it planed, for the future, to allow larger nodes?

**Comment by glennhickey** [comment]
For what it's worth, hal2vg has a chop option (set to 1000 by default) as
of very recently.   Still working on streaming the output, which will be
necessary to scale up to bigger graphs.

**Comment by ekg** [comment]
That would depend on changes in GCSA2. @jltsiren may have some thougths.

I'm fine with the limit, but we need to put warnings in the kmer generation and indexing steps. Keeping this open until we get the warnings in.

**Comment by jltsiren** [comment]
GCSA2 needs a mapping from positions (node, orientation, offset) in the variation graph to 64-bit integers. In the future, the position will sometimes include a haplotype identifier as well. Currently the mapping is just 53 bits for the node (or node + haplotype), 1 bit for the orientation, and 10 bits for the offset. This causes the 1024-base limit for node labels.

The mapping is used for performance and debugging:

* The nodes of the (pruned) de Bruijn graph contain pointers to positions in the variation graph. Most of the time, these pointers can be derived from the predecessor nodes, so we only need to store the pointers at branching nodes. Finding the nearest stored pointers can be expensive on long unary paths, so we also store the pointers with offset 0. This can be replaced by storing pointers divisible by e.g. 64.
* Index construction supports a text input format for debugging purposes. GCSA2 needs to parse the positions and map them to integers.
* Index verification must be able to map the integers back to positions when printing error messages.

We can change the mapping if necessary.

**Comment by adamnovak** [comment]
I'm tired of people coming here with this error message. We need our own error detection code in vg that refuses to pass too-long nodes into GCSA2 and instead recommends to the user that a `vg mod -x 1000` be applied to the graph.

**Comment by ekg** [comment]
Agreed.
