### ISSUE TITLE
performance problem with stream::for_each_parallel<Alignment>

### ISSUE THREAD

**Issue by mlin** [vgteam/vg#530]
@adamnovak @glennhickey @ekg 
As discussed on the call earlier today; I've seen some drastic performance problems using `stream::for_each_parallel` on GAM alignments. I've hit this while fiddling with RocksDB, and it also seems to manifest using Glenn's new parallel version of vg filter (which ran much slower than the old serial version!)

I've pushed a branch [mlin-stream-for-each-parallel-perf-repro](https://github.com/vgteam/vg/tree/mlin-stream-for-each-parallel-perf-repro) to isolate the problem using a trivial subcommand `vg count` that counts the alignments. `vg count -t 0` uses `stream::for_each`, while `-t N` for N>0 uses `stream::for_each_parallel` with that number of threads.

Here's a small GAM (155MB) I'm using with it: [TSNano_1lane_L008_13801_NA12878_R1_001.18.gam](https://dl.dnanex.us/F/D/YBvZXJ5k2B6jJZzb31y2KyggK440Qb3zY3Gg4Zk3/TSNano_1lane_L008_13801_NA12878_R1_001.18.gam)

On a 4-core desktop I get:

```
$ time vg count -t 0 TSNano_1lane_L008_13801_NA12878_R1_001.18.gam
945336

real	0m4.600s
user	0m4.524s
sys	0m0.068s
$ time vg count -t 1 TSNano_1lane_L008_13801_NA12878_R1_001.18.gam
945336

real	0m10.414s
user	0m10.356s
sys	0m0.052s
$ time vg count -t 2 TSNano_1lane_L008_13801_NA12878_R1_001.18.gam
945336

real	0m11.625s
user	0m21.948s
sys	0m1.092s
$ time vg count -t 4 TSNano_1lane_L008_13801_NA12878_R1_001.18.gam
945336

real	0m14.399s
user	0m48.956s
sys	0m1.048s
$ time vg count -t 8 TSNano_1lane_L008_13801_NA12878_R1_001.18.gam
945336

real	0m58.169s
user	2m37.132s
sys	0m5.712s
$ time vg count -t 16 TSNano_1lane_L008_13801_NA12878_R1_001.18.gam
945336

real	3m53.226s
user	11m15.684s
sys	0m9.280s
```

Given this trivial counting function, I wouldn't necessarily expect a wall speedup from parallelization; but, this goes the other way rather dramatically!

**Comment by ekg** [comment]
That's.... Crazy!

With the mapper I am sometimes hitting limits but they appear to be coming
when I use a thread count higher than the number of actual cores on the
system. (After this point things go slower.) But always slowing down is
another thing entirely that escaped my attention!

I'll check out this juicy test today.

**Comment by mlin** [comment]
FWIW I checked in a script for one-line repro. I'm poking at it too.

```
$ git checkout mlin-stream-for-each-parallel-perf-repro
Switched to branch 'mlin-stream-for-each-parallel-perf-repro'
$ ./issue530.sh
t = 0: 945336
4.52user 0.05system 0:04.60elapsed 99%CPU (0avgtext+0avgdata 10884maxresident)k
317992inputs+0outputs (0major+543minor)pagefaults 0swaps
t = 1: 945336
10.48user 0.17system 0:10.67elapsed 99%CPU (0avgtext+0avgdata 25716maxresident)k
0inputs+0outputs (0major+4310minor)pagefaults 0swaps
t = 2: 945336
22.11user 1.03system 0:12.10elapsed 191%CPU (0avgtext+0avgdata 14572maxresident)k
0inputs+0outputs (0major+6653minor)pagefaults 0swaps
t = 4: 945336
59.99user 1.25system 0:19.89elapsed 307%CPU (0avgtext+0avgdata 12428maxresident)k
0inputs+0outputs (0major+2157minor)pagefaults 0swaps
t = 8: 945336
161.26user 6.81system 0:57.23elapsed 293%CPU (0avgtext+0avgdata 16508maxresident)k
0inputs+0outputs (0major+54997minor)pagefaults 0swaps
t = 16: 945336
710.33user 11.68system 3:51.80elapsed 311%CPU (0avgtext+0avgdata 15352maxresident)k
0inputs+0outputs (0major+129372minor)pagefaults 0swaps
$
```

**Comment by mlin** [comment]
Here's a perf flamegraph from running that script (click through and download the svg).
Looks like excessive mutex contention
[![https://dx.doi.org/10.6084/m9.figshare.4204962.v1](https://s3-eu-west-1.amazonaws.com/pfigshare-u-previews/6862173/preview.jpg)](https://dx.doi.org/10.6084/m9.figshare.4204962.v1)

**Comment by mlin** [comment]
So `for_each_parallel` in [stream.hpp](https://github.com/vgteam/vg/blob/master/src/stream.hpp) acquires the mutex once per object, which is murdering us when the lambda doesn't take long to run. We probably need to pass the objects between the threads in batches instead of one-at-a-time, to amortize the locking cost.

**Comment by mlin** [comment]
Worse- the worker threads spin-wait for their next object (locking continuously)

**Comment by mlin** [comment]
Ok, simply doing this makes `-t 16` run in roughly the same cpu+wall time as `-t 1` (though still twice `-t 0`)

```
         if (has_object) {
             lambda(object);
+        } else {
+            usleep(10000);
         }
```

(not that this is a good solution)

**Comment by mlin** [comment]
I'm not experienced with OpenMP, but perhaps the [Tasking](https://docs.oracle.com/cd/E19205-01/820-7883/6nj43o69j/index.html) feature would facilitate a more straightforward implementation of `for_each_parallel`
