### ISSUE TITLE
vg mod -u doesn't unchop across from_start, to_end edges

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#542]
Here's a 20-base, 5-node linear graph that `vg mod -u` refuses to combine down to a single node.

Looking at the JSON, I suspect it's because all the edges have both `from_start` and `to_end` set to `true`.

```
{
  "node": [
    {
      "sequence": "AGCCTC",
      "id": 4674
    },
    {
      "sequence": "T",
      "id": 4673
    },
    {
      "sequence": "C",
      "id": 4676
    },
    {
      "sequence": "CAAGTAGC",
      "id": 7198
    },
    {
      "sequence": "GCCT",
      "id": 4671
    }
  ],
  "edge": [
    {
      "to_end": true,
      "from_start": true,
      "from": 4676,
      "to": 4674
    },
    {
      "to_end": true,
      "from_start": true,
      "from": 4674,
      "to": 4673
    },
    {
      "to_end": true,
      "from_start": true,
      "from": 7198,
      "to": 4676
    },
    {
      "to_end": true,
      "from_start": true,
      "from": 4673,
      "to": 4671
    }
  ]
}
```

Instead of leaving the graph unchanged, `vg mod -u` ought to combine these nodes into one node.

[unchop.vg.zip](https://github.com/vgteam/vg/files/584203/unchop.vg.zip)

**Comment by ekg** [comment]
Can it be fixed by first flipping the doubly reversed edges?

**Comment by adamnovak** [comment]
I would assume so. But we might be able to avoid the preprocessing and just
make vg unchop handle it natively. I'll have to go in and check.
