### ISSUE TITLE
vg deconstruct returns empty file

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#550]
vg deconstruct doesn't work for me. I allways get a empty vcf, I believe the option to set a reference is missing.
`vg deconstruct -x Pt_2ins.xg -r Pt Pt_2ins.vg`

Output:
`##fileformat=VCF4.2
##fileDate=20161115
##source=VG
##reference=
##contig=
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO`

**Comment by edawson** [comment]
Hi @ChriKub ,

    You're correct that there's no option to set a reference - `deconstruct` should output the help and about when passed the `-r` flag. What's your output if you don't pass the `-r Pt`?

   Are you trying to pass a `-r` because you have multiple references in your graph?

    Deconstruct hasn't been updated in a while, but your graph will need to have bubbles in it to output a VCF. Some variants aren't incorporated during construct because of the way the construct algo works. What variants are you trying to extract / what does your graph look like?

**Comment by ChriKub** [comment]
Without the -r option the output is the as before:
I tried to set a reference as by default the reference field in the vcf output is empty.

_##fileformat=VCF4.2
##fileDate=20161115
##source=VG
##reference=
##contig=
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO_
