### ISSUE TITLE
Better variant IDs for alt paths for gPBWT

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#560]
Right now when we construct a graph, we embed "alt paths" in it that describe each alt of each variant in the VCF used to build the graph. Right now these are named based on hashes of the VCF records, and so the name depends on contig name and position.

This isn't necessarily robust to manually chunked parallel graph construction, where one might rewrite a VCF for a chunk and then weld the chunks together later. You wouldn't be able to find the paths from the rewritten variants when you go to build the gPBWT.

Is that a use case we want to support? Do we want to add a VCF offset option to `vg construct` to support it without making people do VCF rewriting? Or do we want to somehow make variant IDs without using offset?

**Comment by edawson** [comment]
I'm confused as to what you mean by "rewrite a VCF for a chunk." Do you mean fudging the contig names so that the same contig is broken into smaller, uniquely named contigs?

**Comment by adamnovak** [comment]
Basically the use case is wrapper scripts around vg construct. Say I split
chromosome 1 and give the P arm to one `vg construct` call, and the Q arm
to another, cutting the FASTA and adjusting all the VCF coordinates on the
second arm to be relative to the start of the cut FASTA.

**Comment by adamnovak** [comment]
I don't think we actually want to support this use case. If we decide to, we can add an offset parameter into vg construct so that variant IDs are calculated by hashing with the specified offset to the position.
