### ISSUE TITLE
Master branch has `-ltcmalloc_minimal` in the Makefile but we don't ship tcmalloc as a dependency

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#569]
I just pulled down master, and it's not building for me, because my system doesn't have tcmalloc. I don't see it (or the Google perf tools thing) anywhere in deps.

@ekg I have you in my Git Blame for the Makefile line in question. Did you add this dependency? Where is it supposed to come from?

**Comment by ekg** [comment]
Yes, I added it. I thought it was included in the deps too? How is this building on travis?

We can build it very quickly from https://github.com/gperftools/gperftools. It might be easiest to do this as it's not always available on systems (e.g. Sanger).

**Comment by adamnovak** [comment]
I don't see gperftools in our deps folder. Maybe Travis happens to have it
in the base image? Perhaps some Travis thing pulls the library in as a
dependency. Or perhaps one of our *other* deps pulls it in as a transitive
dependency somehow, and that's not building on my system.

**Comment by ekg** [comment]
It needs to be added. I'll do that.

**Comment by adamnovak** [comment]
We now do ship tcmalloc.
