### ISSUE TITLE
vg find -A

### ISSUE THREAD

**Issue by shilpagarg** [vgteam/vg#589]
Hi, vg find -A does do the right thing, it still keeps the false connections generated by pacbio alignments that are not in the subgraph. Is it possible to fix it?

To test: data is at erik/chr1:
extract alignments: test.gam, subgraph: primary-graph.simplify.all_subgraphs.vg, input pacbio alignments: aln.SK1+Y12.chr1.pacbio.db

**Comment by adamnovak** [comment]
`vg find -A` is supposed to output alignments, right? Is it outputting more alignments or fewer alignments than you expect?

What false connections are you referring to?
