### ISSUE TITLE
Improve "cannot setRegion" error message / failure mode

### ISSUE THREAD

**Issue by ryan-williams** [vgteam/vg#6]
I am running `vg` and getting this error:

```
$ ./vg construct -r hg19.fasta -v NA12878.vcf
cannot setRegion on a non-tabix indexed file
```
1. help debugging would be appreciated
2. a more descriptive error message would be helpful here.

I see that it [comes from vcflib](https://github.com/ekg/vcflib/blob/b1dfd7a73140f9b12cb8fd2a554d70188ff05cca/src/Variant.cpp#L1313) but that's all I've got.

**Comment by ekg** [comment]
tabix is in [htslib](http://github.com/samtools/htslib). You use it to
index "block gzipped" (bgzipped) files.

You use bgzip and tabix like this:

    bgzip NA12878.vcf
    tabix -p vcf NA12878.vcf.gz

Now you can use the VCF file for construction:

    ./vg construct -r hg19.fasta -v NA12878.vcf.gz

Probably the error message (and you're right that it's in vcflib) just
needs to indicate this process.

**Comment by ekg** [comment]
Sorry if this is pedantic, but in case someone else gets caught by it
before the fix propagates to various repos that depend on vcflib.

**Comment by ryan-williams** [comment]
no that is perfect, thanks
