### ISSUE TITLE
Path simplify doesn't look at position is_reverse when combining Mappings

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#605]
`simplify()` on paths can combine adjacent Mappings to the same node, if they abut. But it doesn't look at orientation when making this abutment calculation, so it could combine Mappings it shouldn't.

**Comment by ekg** [comment]
I'm wondering if this is causing an msga failure I ran into recently. How'd
you catch this?

**Comment by adamnovak** [comment]
I was digging after my msga failure. I'm pretty sure it wasn't this, but I figured I should file an issue since I noticed it.
