### ISSUE TITLE
Bams not mapping

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#607]
Hello,

When I try to map a `bam` file to a graph:
```
vg map -b file.bam -x graph.xg -g graph.gcsa -t 8 graph.vg > file.gam
```
the resulting `gam` is blank.

If I convert the `bam` to a `fastq` with `bamtools` and then map:
```
vg map -f file.fastq -x graph.xg -g graph.gcsa -t 8 graph.vg > file.gam
```
I get a proper `gam` with alignments.

Am I missing a parameter when mapping the `bam`?
Thanks

(using vg 1.4.0-1414)

**Comment by hgibling** [comment]
Actually if I filter the `bams` to specific regions it maps fine... I'm guessing there's a size limit on `bams`?

**Comment by ekg** [comment]
There is not a size limit. This feels like a bug. Any chance you could
share the bam?

**Comment by hgibling** [comment]
Unfortunately not. I've since been able to map different bams entirely without any issues... I'll close and reopen if I can replicate the issue.
