### ISSUE TITLE
Temp files in current directory

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#609]
I am having `.gcsa-` hidden temp files dumped in the current directory. All the temp files ought to be in `TMPDIR`. because the current directory might not have space for them.

**Comment by ekg** [comment]
It's possible to set the working directory for GCSA2, so we could expose
that on the command line.

These files remain when the indexing process doesn't finish, so another
thing would be to consider a way to clean them up automatically on a crash.

**Comment by adamnovak** [comment]
We can expose it on the command line, but it should default to the `$TMPDIR` environment variable, and `/tmp` if that's not set.

We could also try adding some signal handler hooks to try and clean things up on a ctrl+c or a normal kill. Probably best not to try to delete things in the event of a segfault.

**Comment by jltsiren** [comment]
You can change the directory for temp files with `gcsa::TempFile::setDirectory()`. The it defaults to `.`, because `$TMPDIR` is not always a reasonable place for storing hundreds of gigabytes.

**Comment by ekg** [comment]
I think it's risky to set it to $TMPDIR. On the HPC systems I've used it's
not clear that's the right choice. The current working directory seems like
a safe choice for hundreds of gigs.

It's also risky that users don't see the files, but I think the biggest
problem is not realizing you should clean up after a failed run.

**Comment by adamnovak** [comment]
I think TMPDIR is going to be a smarter directory for hundreds of gigs than
whatever the working directory is. Running out of temporary file space in
/tmp isn't that surprising, because if you have a small /tmp and
hundred-gig temp files you might expect that to happen. Running out of
space in your home directory because it's being used for temporary files
without your knowledge is very surprising.

The alternative I think would be to default to dropping the temp files next
to wherever the output files are going; you might be sitting in one
directory but be reading and writing to completely different mount points,
and it's pretty surprising to have files dumped wherever you happen to be
standing. A common use case might be to `cd my_binaries` and run `./vg
index -g /other/mount/thing.idx /other/mount/thing.vg`, and we don't want
to drop huge temp files in a binaries directory.

**Comment by jltsiren** [comment]
I changed the naming scheme from `.gcsa_host_process_counter` to `gcsa_host_process_counter`.
