### ISSUE TITLE
RocksDB conditional dependency on lz4 shared library

### ISSUE THREAD

**Issue by mlin** [vgteam/vg#62]
Documenting a minor build annoyance:

The revision of RocksDB used as of this writing has a [slighty too-clever configure script](https://github.com/facebook/rocksdb/pull/74/files) that enables LZ4 compression if liblz4 is present on the build system. The vg Makefile does not include `-llz4` in the final link step. Consequently:

* If liblz4 isn't installed, everything is fine.
* If liblz4 is installed, then librocksdb.a depends on it, and the final link step of vg fails.

It looks like the RocksDB configuration has been [simplified recently](https://github.com/facebook/rocksdb/commits/master/thirdparty.inc) so the solution may be as simple as upgrading to a recent revision.

**Comment by ekg** [comment]
Great, so hopefully I can upgrade past this. Soon we will only need rocksdb
for sorting reads, but this is still worth sorting out.

**Comment by adamnovak** [comment]
It looks like this isn't building on Travis where liblz4 isn't installed. It fails because the linker can't find `-llz4`.
