### ISSUE TITLE
Construct clobbers its own ID space

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#620]
It looks like construct clobbers graph ID spaces when multiple contigs are present in the fasta/VCF pair. I get a bunch of `warning: [node/edge ID N] appears multiple times. Skipping.` when trying to view the resulting graphs and some node IDs appear on multiple reference paths in the GFA. Building the graphs individually and then combining them after a `vg ids -j` yields a perfectly fine graph, so the chunking logic looks to be fine.

I think it's as simple as tracking the maximum id of the individual contig graphs in the callback function that serializes the graphs to disk and incrementing the next graph's ID's as needed (similar to what is done for chunks right now). Does this sound reasonable as a fix, @adamnovak ?

**Comment by adamnovak** [comment]
Oops.

That sounds like it ought to fix it; all the construction is done in
serial, so it should all get serialized once in order.
