### ISSUE TITLE
Refactor SV normalization code

### ISSUE THREAD

**Issue by edawson** [vgteam/vg#630]
As @adamnovak mentioned on the call yesterday, it would be useful to have the SV normalization code currently in constructor.cpp accessible from elsewhere in vg.

I'm going to move it to utility.hpp for the moment, but I'd like to push it into vcflib at some point. As long as a reference and a FASTA with insertion sequences are provided all of the functionality already exists there.

**Comment by adamnovak** [comment]
I also want to add support for some more complex mobile element insertion variants. Here's some information I was sent by 1KG about how to interpret MEINFO tags:

> In accordance with VCF format for MEIs, the REF column is the last
> reference base prior to the MEI (i.e. the last base of the reference
> duplication). You are correct about the AluYa5 being the consensus sequence at
> that locus. So in the record listed, the sequence for the filled allele would
> be: <REF:G><AluYa5><PolA><TSD:AAAAAGGTGAGGG> The REF is the base from the REF
> column, followed by the AluYa5 consensus sequence, a Pol (A) tail of
> indeterminate length (see Sudmant et al for an explanation on this), followed
> by the target site duplication (which is NOT included in SVLEN). You are
> correct that '+' means that the Alu sequence should be inserted in the ‘+’
> orientation, however the TSD information is ALWAYS given on the ‘+’ strand, so
> do not perform reverse complement of it when including in the sequence
> assembly. Alu consensus sequences for separate subfamilies are provided as part
> of the Stewart et. al. paper supplement (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3158055/).
> Please be aware, however, that the subfamily listed in MEINFO was provided by
> an early assembly algorithm included in MELTv1.0. A more accurate
> representation is included in the latest version of MELT (v2.0.2), along with
> full assemblies for the majority of Alu elements, in a forthcoming paper
> currently under review.

**Comment by edawson** [comment]
I've gone ahead and [refactored the code into vcflib](https://github.com/vcflib/vcflib/pull/172). Everything behaves as before; the representative alleles are replaced by ones inferred from the info fields and the fasta files. If the variant is able to be canonicalized it returns true; if it fails it spits back false.

We just need @ekg to approve the PR, which seems to fix another issue where the ssw.c/h files had been swizzled around between vg's vcflib commit and vcflib's master tip.

**Comment by edawson** [comment]
Code now resides in vcflib and the submodules have been updated to include it.
