### ISSUE TITLE
vg mod -B fails with an unsupported '=' CIGAR operation

### ISSUE THREAD

**Issue by shilpagarg** [vgteam/vg#642]
I am trying vg mod -B <vg graph>
error [GSSWAligner::gssw_mapping_to_alignment] unsupported cigar op type =

**Comment by adamnovak** [comment]
GSSW isn't supposed to generate '=' as a GIGAR operation. But it appears to be doing so somehow.

Do you have an example file?

**Comment by shilpagarg** [comment]
Its it big huge, how can I share with you? Thanks.

**Comment by adamnovak** [comment]
If you can't attach it on Github and you haven't got a ~/public_html folder
somewhere to drop it in, you could try something like [transfer.sh](
https://transfer.sh/).

**Comment by shilpagarg** [comment]
https://transfer.sh/2Fj2J/prefix.int.vg

**Comment by adamnovak** [comment]
Sorry, I know I said I would look at this, but do you feel comfortable trying to track it down yourself a little bit? You'd probably start by adding a loop to dump all of the "elements" in the alignment that GSSW returns.

The GSSW struct definitions are here: https://github.com/ekg/gssw/blob/master/src/gssw.h#L120-L130

And the loop probably ought to dump this: https://github.com/vgteam/vg/blob/master/src/gssw_aligner.cpp#L349

It might also help to dump the actual string being aligned (to_seq), in case there's something weird about it.

**Comment by shilpagarg** [comment]
is it possible for you to handle this bug for now? Probably I will know the vg code more in few days and then can investigate more in detail.

**Comment by ekg** [comment]
The best way to learn the code is by trying to get it to do what we need it
to do! Try what Adam suggested and share what you find.

**Comment by shilpagarg** [comment]
Sure, Next, I was trying vg mod -f 10000000000 on the same graph and I get segmentation fault.

vg mod -f 10000000000 prefix.int.vg

**Comment by shilpagarg** [comment]
For vg mod -B part, I just un-commented line 350 at  https://github.com/vgteam/vg/blob/master/src/gssw_aligner.cpp#L349

Still I get error [GSSWAligner::gssw_mapping_to_alignment] unsupported cigar op type =

Is it something else I should be doing? Could you tell me more precisely? Thanks.

**Comment by adamnovak** [comment]
You don't want to just dump gm->position; you also want to print out all
the items in the gc->elements array. Something like:

for (size_t i = 0; i < gc->length; i++) {
    // Loop over the graph cigar and get each node cigar
    gssw_node_cigar* item = gc->elements[i];
    // Then you need to loop over the item->cigar->elements array, which
has length item->cigar->length
    // So add another loop over that here
    // For each resulting gssw_cigar_element you want to cerr <<
element->type << " " << element->length
    // Then you will be able to see the actual alignment that is causing
trouble, output to the console.
}

**Comment by adamnovak** [comment]
This should be fixed by #658.
