### ISSUE TITLE
Bluntification duplicates overlapping sequences over reversing edges

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#656]
Try bluntifying this GFA with `vg mod -B`:

```
S	2	ACA
S	1	TC
L	1	-	2	+	1M
```

It produces this:

![image](https://cloud.githubusercontent.com/assets/5062495/22806144/80097004-eed5-11e6-8d2a-b563313a3aae.png)

It seems to have duplicated the overlapping sequence and included it in both orientations, when really it should just include it in one orientation.

**Comment by adamnovak** [comment]
The problem with this is it creates a fake bubble, which throws off @shilpagarg's bubble-based analysis.

**Comment by adamnovak** [comment]
Also, we're getting an extra A on the full traversal through. In the original it's `GACA`, and bluntified it's `GAACA`.

**Comment by shilpagarg** [comment]
Here is one more example where bluntification fails, it is in GFA format.
[bluntify_fail_test1.txt](https://github.com/vgteam/vg/files/765347/bluntify_fail_test1.txt)

**Comment by adamnovak** [comment]
I've sketched out an implementation of this that uses the pinch graph library. Now I just need to test it to make sure I have all the orientation flags correct.

**Comment by shilpagarg** [comment]
Thats great! Thanks. I can provide u the test cases tomorrow.

**Comment by adamnovak** [comment]
This has been fixed.
