### ISSUE TITLE
vg map produces invalid GAM

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#666]
(indexes are the latest whole genome indexes @mlin sent out.  Here for ucsc folks /hive/users/hickey/toil_vg/genome/vg)

vg map -x vg/index.xg -g vg/index.gcsa -s TGCACCACTGCACTCTAGCCGCAGCAACAGGGCAAGACCTTGTCAAAAAAAAAAAAAAAAAGAAGAAAGGAAGGAAGAATGAAAGAAGAAAAGGAGAGACA

produces an alignment containing this mapping

{"position": {"node_id": 290483617}, "edit": [{"from_length": 31, "to_length": 31}, {"sequence": "G", "from_length": 1, "to_length": 1}, {"from_length": 1, "to_length": 1}], "rank": 5}

The from_length totals 33.  But the node in question has length 32

{"node": [{"id": 290483617, "sequence": "GGCAAGACCTTGTCAAAAAAAAAAAAAAAAAA"}], "path": [{"mapping": [{"position": {"node_id": 290483617}, "rank": 3079143}], "name": "22"}]}

When trying to extract the subgraph, re-index, and reproduce, I get a valid alignment, where the "G" is an insert (from_length = 0), which makes debugging hard.  

But even if the fault lies entirely within the index, vg map needs to throw an error before writing invalid output.

**Comment by ekg** [comment]
Is this an index version mismatch? Where should we be detecting the problem?

**Comment by glennhickey** [comment]
Hoping it's just an index version.  I'm trying to regenerate a new one.

As for detection, if it is an index version issue, this should be detected
when the gcsa is loaded by vg map (which I thought was what happened).

My other point was that vg map should can and should detect invalid edits
before they are written.  At least for this case where from_length >
node_length.

**Comment by ekg** [comment]
The node length check seems reasonable and very cheap to implement. I
haven't been able to work on this yet, but I will also explore this when I
do. Should be early next week.

**Comment by glennhickey** [comment]
Closed by #689 which fixed the faulty gam error (at least in the bakeoff data, will assume in the larger case too), and #682 which added some more checking.
