### ISSUE TITLE
MEM threader produces alignments that run off the ends of nodes

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#683]
I have a chr22 index and an example sequence here: http://hgwdev.soe.ucsc.edu/~anovak/halIssues/node_escape.tar.gz

When you map the sequence to the index with the MEM threader, with the command in the included README.txt, you get an alignment that purports to be a perfect match, but runs off the end of a node by one base (and has an incorrect score for a full length perfect match). When you turn off the MEM threader with -a, or when you use `vg align` on the local region, you get a different alignment (with an indel) that stays inside the bounds of the nodes.

This running-off-the-end problem was causing crashes in vg call because of pileups that ran off the ends of their nodes, resulting from alignments that run off the ends of nodes.

Turning on mapper debugging appears to let it catch the error:

```
alignment does not match graph 
{"path": {"mapping": [{"position": {"offset": 88, "node_id": 786749}, "edit": [{"to_length": 32, "from_length": 32}], "rank": 1}, {"position": {"node_id": 786753}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 2}, {"position": {"node_id": 786754}, "edit": [{"to_length": 63, "from_length": 63}], "rank": 3}, {"position": {"node_id": 786756}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}, {"position": {"node_id": 786759}, "edit": [{"to_length": 28, "from_length": 28}], "rank": 5}]}, "sequence": "CCACTGTGACCGGCCATTCATTTATTCTTAGGTTTTTTTTTCTATTAATGCCTACTGTGTGTCAGGACCTACGGATGCAGATTATAGAAGATATATGTACACTGGTGAAGGTGATAGGAGAAATA", "score": 118, "identity": 1.0}
expect:	CCACTGTGACCGGCCATTCATTTATTCTTAGGTTTTTTTTTCTATTAATGCCTACTGTGTGTCAGGACCTACGGATGCAGATTATAGAAGATATATGTACACTGGTGAAGGTGATAGGAGAAATA
got:	CCACTGTGACCGGCCATTCATTTATTCTTAGTTTTTTTTTCTATTAATGCCTACTGTGTGTCAGGACCTACGGATGCAGATTATAGAAGATATATGTACACTGGTGAAGGTGATAGGAGAAATA
alignment failure {"path": {"mapping": [{"position": {"offset": 88, "node_id": 786749}, "edit": [{"to_length": 32, "from_length": 32}], "rank": 1}, {"position": {"node_id": 786753}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 2}, {"position": {"node_id": 786754}, "edit": [{"to_length": 63, "from_length": 63}], "rank": 3}, {"position": {"node_id": 786756}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}, {"position": {"node_id": 786759}, "edit": [{"to_length": 28, "from_length": 28}], "rank": 5}]}, "sequence": "CCACTGTGACCGGCCATTCATTTATTCTTAGGTTTTTTTTTCTATTAATGCCTACTGTGTGTCAGGACCTACGGATGCAGATTATAGAAGATATATGTACACTGGTGAAGGTGATAGGAGAAATA", "score": 118, "identity": 1.0}
```

@ekg Can you fix this? And why doesn't it always do these alignment-matching-graph checks?

I have a PR in #682 that among other things adds some asserts to catch this behavior, but that doesn't actually fix the underlying issue.

**Comment by ekg** [comment]
> @ekg Can you fix this? And why doesn't it always do these alignment-matching-graph checks

Yes, and it wasn't set to do them because of computational costs of the way that I'd previously implemented the check. Path dependence and rushed coding.

**Comment by ekg** [comment]
I have a fix in that uses full GSSW alignment on windows (as before with the old version) but does so using clusters established with the "MEM threading" model.

It looks to me that the performance is identical (ROC, QQ, etc.) and I will push this into a PR today. It may actually run slightly faster as well.
