### ISSUE TITLE
vg simplify: Segmentation faults

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#719]
I'm trying to simplify a graph constructed by vg msga. When simplifing it I get various error messages, depending on the modification steps I performed before.

**Without modification:**
`vg simplify -p sibelia_TAIR10_masked_9.vg > sibelia_TAIR10_masked_9_simplified.vg`
` loading graph                  [=============================================================================================================================]100.0%
Iteration 0: Scanning 23615 nodes and 28058 edges for sites...
Found 28 leaves
Segmentation faults             [                                                                                                                             ]  0.0%`

**After unchopping:**
`vg mod -u sibelia_TAIR10_masked_9.vg > sibelia_TAIR10_masked_9_unchopped.vg
vg simplify -p sibelia_TAIR10_masked_9_unchopped.vg > sibelia_TAIR10_masked_9_unchopped_simplified.vg`
` loading graph                  [=============================================================================================================================]100.0%
Iteration 0: Scanning 12160 nodes and 16603 edges for sites...
Segmentation fault
`

**After unchopping and sorting**
`vg mod -u -z sibelia_TAIR10_masked_9.vg > sibelia_TAIR10_masked_9_unchopped.vg
vg simplify -p sibelia_TAIR10_masked_9_unchopped.vg > sibelia_TAIR10_masked_9_unchopped_simplified.vg`
` loading graph                  [=============================================================================================================================]100.0%
Iteration 0: Scanning 12160 nodes and 16603 edges for sites...
Found 28 leaves
 saving graph                   [=============================================================================================================================]100.0%
terminate called after throwing an instance of 'std::runtime_error'
  what():  No node 0 in graph
Aborted
`

Is there any way to get the vg simplify to work on a graph? It would be especially useful for visualisations of the graph.

**Comment by adamnovak** [comment]
Simplify can probably be made to work with the graph. It was a bit of a rush job for a particular application in our lab, and clearly it has some bugs.

Unfortunately I have no real clue what those bugs are. Can you post your graph? Or, failing that, a backtrace from GDB showing where it's segfaulting?

Can you also make sure that your graph passes `vg validate`?

**Comment by ChriKub** [comment]
All versions of the graph pass vg validate.

GDB backtrace for unmodified graph:
[gdb-vg_simplify.txt](https://github.com/vgteam/vg/files/841273/gdb-vg_simplify.txt)

GDB backtrace of unchopped graph:
[gdb-vg_simplify_unchopped.txt](https://github.com/vgteam/vg/files/841287/gdb-vg_simplify_unchopped.txt)

**Comment by adamnovak** [comment]
Hm. The first one doesn't make sense to me (we're getting a segfault trying to grab the default Visit instance when grabbing the start of a snarl to see if the snarl is a leaf), and the second one makes even less sense (because the bubble contents finding code seems to be going for nodes that don't exist).

I'll have to see if I'm maybe removing nodes from the graph and not re-finding bubbles or re-initializing the SnarlManager like maybe I need to. But the first one seems like maybe @jeizenga should look at it.
