### ISSUE TITLE
Maintain dockerfile standard

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#738]
@glennhickey @adamnovak The dockerfile should at least contain a `/data` directory in order to maintain docker container standards as specified by @hannes-ucsc @jvivian @cket in the old cgl-docker-lib repo (https://github.com/BD2KGenomics/cgl-docker-lib#basic-philosophy).

An example of how I setup the dockerfiles in that repo can be found here (https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/vg/runtime/Dockerfile).

**Comment by adamnovak** [comment]
I think @cmarkello has overall better Dockerfiles for vg, and the current Dockerfile in this repo has outstanding bugs #503 #515 that I haven't gotten around to fixing.

@cmarkello, do you want to put together a PR that replaces the Dockerfile here with your two-Docker CGL-style setup?

**Comment by glennhickey** [comment]
@adamnovak @cmarkello

The vg docker file has moved here:

https://github.com/vgteam/vg_docker

courtesy of @mlin.  It works and gets updated automatically on quay when
pushing to this repo.  The one in vg should be removed, and we should move
docker issues and PRs to vg_docker...

**Comment by mlin** [comment]
Yes there was a lot of inspiration from @cmarkello's dockerfiles linked above in preparing the vg_docker glue. Let's evolve it further there
