### ISSUE TITLE
 Compile [obj/main.o] Error 1 - commit ee1ef2f207ddd143228435b7cf68433fcea391fd

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#751]
Compiling the latest commit to test GFA changes gives me:
```
vg/include/lru_cache.h:74:37: error: no type named ‘iterator’ in ‘using map_type = class std::unordered_map<long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*, std::hash<long int>, std::equal_to<long int>, std::allocator<std::pair<const long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*> > > {aka class std::unordered_map<long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*, std::hash<long int>, std::equal_to<long int>, std::allocator<std::pair<const long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*> > >}’
make: *** [obj/main.o] Error 1
```

**Comment by edawson** [comment]
That's odd, as I haven't touched that part of the code. @ekg @adamnovak any ideas where this came from?

The latest GFA changes aren't in fully in yet but I've add a spec converter for (V0.1 <-> V1.0) to [gfakluge](https://github.com/edawson/gfakluge). Starting tonight vg will take either and produce V1.0. If you want to stick to a frozen commit of vg you can use the spec converter to go 1.0 -> 0.1.

**Comment by adamnovak** [comment]
That commit really shouldn't have done anything.

Does d95c37cb5989d3310386a025daeadbc751bfbaa0 work?

**Comment by fbemm** [comment]
Same as before:

`vg/include/lru_cache.h:74:37: error: no type named ‘iterator’ in ‘using map_type = class std::unordered_map<long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*, std::hash<long int>, std::equal_to<long int>, std::allocator<std::pair<const long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*> > > {aka class std::unordered_map<long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*, std::hash<long int>, std::equal_to<long int>, std::allocator<std::pair<const long int, LRUCache<long int, std::vector<vg::Edge> >::Impl::Node*> > >}’
make: *** [obj/main.o] Error 1
`

**Comment by ekg** [comment]
What gcc version are you using?

**Comment by fbemm** [comment]
Dammit, env source did not work and I used the wrong compiler. Works now! Sorry! F
