### ISSUE TITLE
Installation fails due to no rocksdb installation?

### ISSUE THREAD

**Issue by russianconcussion** [vgteam/vg#765]
Hi, just tried to install vg from github on 4.9.6-200.fc25.x86_64 and it failed.  Something about rocksdb not being installed, maybe?

The stdout and stderr from make:
[stdout.txt](https://github.com/vgteam/vg/files/907817/stdout.txt)
[stderr.txt](https://github.com/vgteam/vg/files/907818/stderr.txt)

**Comment by edawson** [comment]
This looks a bit odd, but here are two things that might help:  
1. `source ./source_me.sh` in the main vg directory.
2. Did you use the `--recursive ` flag when cloning? If not, run a `git submodule update --init --recursive`.

It looks like it just didn't find the rocks library, maybe?

**Comment by edawson** [comment]
I'm going to assume this helped? Shall I close this?

**Comment by russianconcussion** [comment]
Hi Eric, yes, I ended up using the `--recursive` flag and that solved my problem! Thanks.
