### ISSUE TITLE
mapper non-determinism due to fragment length estimation

### ISSUE THREAD

**Issue by mlin** [vgteam/vg#802]
The mapper makes running estimates of the fragment length distribution as it processes paired-end reads. These estimates can affect where a read pair maps, or whether it maps at all. As a result, the mapping generated for a given read pair in general depends on the preceding reads in the FASTQs. With multithreading, even a given pair of FASTQs can show some variability over repeated mapper invocations. In practice only a tiny fraction of reads are affected but still this Feels Bad, Man.

The variability can be somewhat reduced by initializing the fragment length model on the command line e.g. "-I 2000:450:150:0:1". But this only sets an initial condition currently, and so does not make a multithreaded run deterministic.

Ideas:

1. Fix the parameters provided on the command line, if any, instead of updating them dynamically.
2. Do a first pass over the data (perhaps the first 10k pairs) to estimate the parameters, then map from the beginning.

**Comment by ekg** [comment]
I implemented both of your ideas in #803. They got merged in with long read alignment work, but they'll be in master shortly provided there are no more surprises in the tests.

Here's how to use the new functionality.

First, we can run a subset of the alignments in "print model mode" and we'll get only the model specification as output:

```
vg map -iG <(vg view -a yeast.100k/sim.gam | head -1000 | vg view -JaG - ) -d SGRP2/SGRP2-cerevisiae -t 4 --compare -p 
10000:402.162:50.2105:0:1
```

Now, we can take this as input to a new mapping run, using `-U` to disable the updates to the model. This produces deterministic mapping results for the pairs.

```
erik@tappy [06:41:07 PM] [~/vg-paper] 
-> % vg map -iG <(vg view -a yeast.100k/sim.gam | head -1000 | vg view -JaG - ) -d SGRP2/SGRP2-cerevisiae -t 4 --compare -U -I 10000:402.162:50.2105:0:1 | sort | md5sum
f73fdc75f032b40af4b994acd377472b  -
erik@tappy [06:42:01 PM] [~/vg-paper] 
-> % vg map -iG <(vg view -a yeast.100k/sim.gam | head -1000 | vg view -JaG - ) -d SGRP2/SGRP2-cerevisiae -t 4 --compare -U -I 10000:402.162:50.2105:0:1 | sort | md5sum 
f73fdc75f032b40af4b994acd377472b  -
erik@tappy [06:42:03 PM] [~/vg-paper] 
-> % vg map -iG <(vg view -a yeast.100k/sim.gam | head -1000 | vg view -JaG - ) -d SGRP2/SGRP2-cerevisiae -t 4 --compare -U -I 10000:402.162:50.2105:0:1 | sort | md5sum 
f73fdc75f032b40af4b994acd377472b  -
erik@tappy [06:42:05 PM] [~/vg-paper] 
-> % vg map -iG <(vg view -a yeast.100k/sim.gam | head -1000 | vg view -JaG - ) -d SGRP2/SGRP2-cerevisiae -t 4 --compare | sort | md5sum  
4d9c99d77f9de24d1389114610d1b990  -
```

Please let me know if you find any issues with this.
