### ISSUE TITLE
vg msga segfault

### ISSUE THREAD

**Issue by simonrharris** [vgteam/vg#806]
Hi. I've been trying to create a graph from a set of 129 sequences in a multifasta file using msga but it segfaults early on in the process. I've tried with various parameters but always get the same thing. The file is 19 sequences of around 8050-900bp each. Debugging output is below.

H 5
loading folP.mfa
preparing initial graph
building xg index
building GCSA2 index
InputGraph::InputGraph(): 1728 kmers in 1 file(s)
InputGraph::read(): Read 1728 11-mers from .vg-kmers-tmp-XXZZhi7y
InputGraph::readKeys(): 1724 unique keys
InputGraph::read(): Read 1728 11-mers from .vg-kmers-tmp-XXZZhi7y
InputGraph::readFrom(): 1716 unique from nodes
InputGraph::read(): Read 1728 11-mers from .vg-kmers-tmp-XXZZhi7y
PathGraph::PathGraph(): 1728 paths with 3456 ranks
PathGraph::PathGraph(): 5.14984e-05 GB in 1 file(s)
GCSA::GCSA(): Preprocessing: 0.103303 seconds, 0.0145874 GB
GCSA::GCSA(): Prefix-doubling from path length 11
GCSA::GCSA(): Step 1 (path length 11 -> 22)
PathGraph::prune(): 1728 -> 1726 paths (1724 ranges)
PathGraph::prune(): 1722 unique, 0 redundant, 4 unsorted, 0 nondeterministic paths
PathGraph::prune(): 5.14388e-05 GB in 1 file(s)
PathGraph::read(): File 0: Read 1726 order-11 paths
PathGraph::extend(): File 0: Created 1726 order-22 paths
PathGraph::read(): File 0: Read 1726 order-22 paths
PathGraphBuilder::sort(): File 0: Sorted 1726 paths
PathGraph::extend(): 1726 -> 1726 paths (3456 ranks)
PathGraph::extend(): 5.14537e-05 GB in 1 file(s)
GCSA::GCSA(): Step 2 (path length 22 -> 44)
PathGraph::prune(): 1726 -> 1726 paths (1726 ranges)
PathGraph::prune(): 1726 unique, 0 redundant, 0 unsorted, 0 nondeterministic paths
PathGraph::prune(): 5.14537e-05 GB in 1 file(s)
PathGraph::read(): File 0: Read 1726 order-22 paths
PathGraph::extend(): File 0: Created 1726 order-44 paths
PathGraph::read(): File 0: Read 1726 order-44 paths
PathGraphBuilder::sort(): File 0: Sorted 1726 paths
PathGraph::extend(): 1726 -> 1726 paths (3456 ranks)
PathGraph::extend(): 5.14537e-05 GB in 1 file(s)
GCSA::GCSA(): Step 3 (path length 44 -> 88)
PathGraph::prune(): 1726 -> 1726 paths (1726 ranges)
PathGraph::prune(): 1726 unique, 0 redundant, 0 unsorted, 0 nondeterministic paths
PathGraph::prune(): 5.14537e-05 GB in 1 file(s)
PathGraph::read(): File 0: Read 1726 order-44 paths
PathGraph::extend(): File 0: Created 1726 order-88 paths
PathGraph::read(): File 0: Read 1726 order-88 paths
PathGraphBuilder::sort(): File 0: Sorted 1726 paths
PathGraph::extend(): 1726 -> 1726 paths (3456 ranks)
PathGraph::extend(): 5.14537e-05 GB in 1 file(s)
GCSA::GCSA(): Prefix-doubling: 0.237203 seconds, 0.0145874 GB
GCSA::GCSA(): Merging the paths
MergedGraph::MergedGraph(): 1726 paths with 3456 ranks and 0 additional from nodes
MergedGraph::MergedGraph(): 5.30612e-05 GB
GCSA::GCSA(): Merging: 0.00333703 seconds, 0.0145874 GB
GCSA::GCSA(): Building the index
GCSA::GCSA(): Construction: 0.00792665 seconds, 0.0145874 GB
GCSA::GCSA(): 1726 paths, 1727 edges
GCSA::GCSA(): 1726 pointers (10 redundant)
GCSA::GCSA(): 80 samples at 80 positions
LCPArray::LCPArray(): Construction: 0.0154371 seconds, 0.0145874 GB
LCPArray::LCPArray(): 1754 values at 3 levels (branching factor 64)
folP.Neisseria_meningitidis_MC58_v2_01707: adding to graph1
folP.Neisseria_meningitidis_MC58_v2_01707: aligning sequence of 858bp against 39 nodes
folP.Neisseria_meningitidis_MC58_v2_01707: editing graph
folP.Neisseria_meningitidis_MC58_v2_01707: sorting and compacting ids
building xg index
building GCSA2 index
InputGraph::InputGraph(): 3982 kmers in 1 file(s)
InputGraph::read(): Read 3982 11-mers from .vg-kmers-tmp-XXCWpnNJ
InputGraph::readKeys(): 3686 unique keys
InputGraph::read(): Read 3982 11-mers from .vg-kmers-tmp-XXCWpnNJ
InputGraph::readFrom(): 2062 unique from nodes
InputGraph::read(): Read 3982 11-mers from .vg-kmers-tmp-XXCWpnNJ
PathGraph::PathGraph(): 3982 paths with 7964 ranks
PathGraph::PathGraph(): 0.000118673 GB in 1 file(s)
GCSA::GCSA(): Preprocessing: 0.177697 seconds, 0.0193481 GB
GCSA::GCSA(): Prefix-doubling from path length 11
GCSA::GCSA(): Step 1 (path length 11 -> 22)
PathGraph::prune(): 3982 -> 2963 paths (2928 ranges)
PathGraph::prune(): 2901 unique, 0 redundant, 54 unsorted, 8 nondeterministic paths
PathGraph::prune(): 8.83043e-05 GB in 1 file(s)
PathGraph::read(): File 0: Read 2963 order-11 paths
PathGraph::extend(): File 0: Created 2983 order-22 paths
PathGraph::read(): File 0: Read 2983 order-22 paths
PathGraphBuilder::sort(): File 0: Sorted 2983 paths
PathGraph::extend(): 2963 -> 2983 paths (6040 ranks)
PathGraph::extend(): 8.9176e-05 GB in 1 file(s)
GCSA::GCSA(): Step 2 (path length 22 -> 44)
PathGraph::prune(): 2983 -> 2979 paths (2954 ranges)
PathGraph::prune(): 2929 unique, 0 redundant, 0 unsorted, 50 nondeterministic paths
PathGraph::prune(): 8.90419e-05 GB in 1 file(s)
PathGraph::read(): File 0: Read 2979 order-22 paths
PathGraph::extend(): File 0: Created 2979 order-44 paths
PathGraph::read(): File 0: Read 2979 order-44 paths
PathGraphBuilder::sort(): File 0: Sorted 2979 paths
PathGraph::extend(): 2979 -> 2979 paths (6028 ranks)
PathGraph::extend(): 8.90419e-05 GB in 1 file(s)
GCSA::GCSA(): Step 3 (path length 44 -> 88)
PathGraph::prune(): 2979 -> 2979 paths (2954 ranges)
PathGraph::prune(): 2929 unique, 0 redundant, 0 unsorted, 50 nondeterministic paths
PathGraph::prune(): 8.90419e-05 GB in 1 file(s)
PathGraph::read(): File 0: Read 2979 order-44 paths
PathGraph::extend(): File 0: Created 2979 order-88 paths
PathGraph::read(): File 0: Read 2979 order-88 paths
PathGraphBuilder::sort(): File 0: Sorted 2979 paths
PathGraph::extend(): 2979 -> 2979 paths (6028 ranks)
PathGraph::extend(): 8.90419e-05 GB in 1 file(s)
GCSA::GCSA(): Prefix-doubling: 0.390511 seconds, 0.0193481 GB
GCSA::GCSA(): Merging the paths
MergedGraph::MergedGraph(): 2939 paths with 5908 ranks and 10 additional from nodes
MergedGraph::MergedGraph(): 9.0587e-05 GB
GCSA::GCSA(): Merging: 0.00497865 seconds, 0.0193481 GB
GCSA::GCSA(): Building the index
GCSA::GCSA(): Construction: 0.0116253 seconds, 0.0193481 GB
GCSA::GCSA(): 2939 paths, 3118 edges
GCSA::GCSA(): 2949 pointers (887 redundant)
GCSA::GCSA(): 609 samples at 606 positions
LCPArray::LCPArray(): Construction: 0.0143038 seconds, 0.0193481 GB
LCPArray::LCPArray(): 2986 values at 3 levels (branching factor 64)
folP.Neisseria_meningitidis_H44_76_v1_00541: adding to graph1
folP.Neisseria_meningitidis_H44_76_v1_00541: aligning sequence of 858bp against 207 nodes
Segmentation fault
Thanks,
Simon

**Comment by ekg** [comment]
This is with the current HEAD of master? If so could you please attach a
zip or email me one to reproduce the problem?

**Comment by adamnovak** [comment]
Without data to reproduce this, I'm goign to have to close the issue. Sorry, @simonrharris !

If you can post the data or otherwise get it to us, please feel free to re-open.
