### ISSUE TITLE
Rocksdb alignment from node lookup returns random stuff

### ISSUE THREAD

**Issue by glennhickey** [vgteam/vg#818]
I noticed this while extracting a gam from chr21 from @mlin's latest vg alignment against the linear reference:
`vg chunk -x index.xg -a HG002-NA24385-30x-ref.gam.index -p 21:282160186-286392791 -t 1 -b rechunk -i -c 0`
This command just calls Index::for_alignment_to_nodes() on each id in the range and dumps the results.. https://github.com/vgteam/vg/blob/master/src/chunker.cpp#L137-L149
But the output contains Alignments such as below, whose ids are all well outside the range (over in chromosome 10).

I haven't found a case where an alignment that should be returned isn't yet. 

Is this by design where we expect a certain number of hash collisions, or is there something wrong? 

{"fragment": [{"name": "10", "length": -421}], "path": {"mapping": [{"position": {"offset": 18, "node_id": 183832189}, "rank": 1, "edit": [{"from_length": 9, "to_length": 9}]}, {"position": {"node_id": 183832191}, "rank": 2, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 183832192}, "rank": 3, "edit": [{"from_length": 32, "to_length": 32}]}, {"position": {"node_id": 183832193}, "rank": 4, "edit": [{"from_length": 2, "to_length": 2}]}, {"position": {"node_id": 183832195}, "rank": 5, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 183832196}, "rank": 6, "edit": [{"from_length": 16, "to_length": 16}]}, {"position": {"node_id": 183832198}, "rank": 7, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 183832199}, "rank": 8, "edit": [{"from_length": 26, "to_length": 26}]}, {"position": {"node_id": 183832201}, "rank": 9, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 183832202}, "rank": 10, "edit": [{"from_length": 32, "to_length": 32}]}, {"position": {"node_id": 183832203}, "rank": 11, "edit": [{"from_length": 8, "to_length": 8}]}, {"position": {"node_id": 183832205}, "rank": 12, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 183832206}, "rank": 13, "edit": [{"from_length": 18, "to_length": 18}]}]}, "sequence": "ATTCTATACGATAGCTATAGTTTTCTTTTTTTCATTCTTTTTTTTATTATTATTGGAGATGGTGTCTTGCTGTATGGCCCAGGCTGGTCTTGAACACCTAGGCTTAGGCAGTCCTTCTACCTCAGCTTCCCAAATTGTTGGGATTACA", "name": "HISEQ1:22:H9UJNADXX:2:2112:9195:58956 2:N:0:CGATGT", "quality": "Hh8fIyEjIRogGQobIx8bISUgJSQdIyAnGCUlJyElJSUkJiIlJR0eJSUmIxofFR8cJBofICMdHB4SFh8WFhYNFhwgIiIgGiAfHyAjEgsHGRseGBcLGwcUChMdIB0SHyAZHh8hEh0gHiAeHxIdGRMXEhgHEwcTHyEdHSAZGR4gIR8gHx4ZEhEZHQcZHxAbFBcfIRkfCg==", "score": 148, "mapping_quality": 60, "fragment_prev": {"name": "HISEQ1:22:H9UJNADXX:2:2112:9195:58956 1:N:0:CGATGT"}, "identity": 1.0}

**Comment by glennhickey** [comment]
Just noticed that vg index -N wants an "ideally, sorted" gam.  Sorting seems to fix this problem on a small test case.  @ekg, is this the most efficient way to do this?

vg index -a x.gam -d x.gam.index
vg index -A -d x.gam.index | vg index -N - -d x_sort.gam.index

**Comment by glennhickey** [comment]
On a related note, @edawsonk is vg gamsort something I should be using instead?  I can't get it to output anything.

**Comment by ekg** [comment]
Sorting solved it? Yes that is the best way we have for approximate node
based sorting.

**Comment by glennhickey** [comment]
Yeah thanks, sorting does seem to have worked.  Big time and space overhead though, I'm actually wondering if it's not better just to filter the spurious results and work on the unsorted gam.
