### ISSUE TITLE
Compile error with commit 47ec88ee87df9559abde6f22ae03efff041ad1f0

### ISSUE THREAD

**Issue by fbemm** [vgteam/vg#835]
I am getting a compile error since a couple of days. We switched to Ubuntu 16.04 lately and I guess it's GCC 5.4.0 related.

g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -g -c -o obj/unittest/srpe_filter.o src/unittest/srpe_filter.cpp -I/ebio/abt6_projects9/abt6_software/bin/vg/include -I. -I/ebio/abt6_projects9/abt6_software/bin/vg/src -I/ebio/abt6_projects9/abt6_software/bin/vg/src/unit
test -I/ebio/abt6_projects9/abt6_software/bin/vg/src/subcommand -I/ebio/abt6_projects9/abt6_software/bin/vg/cpp -I/ebio/abt6_projects9/abt6_software/bin/vg/include/dynamic -I/ebio/abt6_projects9/abt6_software/bin/vg/include/sonLib -I/ebio/abt6_projects9/abt6_softw
are/bin/vg/include/gcsa -ggdb -L/ebio/abt6_projects9/abt6_software/bin/vg/lib -lvcflib -lgssw -lssw -lprotobuf -lhts -lpthread-ljansson -lncurses -lgcsa2 -lxg -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lraptor2 -lsupbub -lsdsl -lpinchesandcacti -l3edgeconnecte
d -lsonlib -lfml -Wl,-rpath,/ebio/abt6_projects9/abt6_software/bin/vg/lib -lrocksdb
In file included from /ebio/abt6_projects9/abt6_software/bin/vg/src/position.hpp:7:0,
                 from /ebio/abt6_projects9/abt6_software/bin/vg/src/path.hpp:16,
                 from /ebio/abt6_projects9/abt6_software/bin/vg/src/gssw_aligner.hpp:14,
                 from /ebio/abt6_projects9/abt6_software/bin/vg/src/vg.hpp:20,
                 from /ebio/abt6_projects9/abt6_software/bin/vg/src/filter.hpp:11,
                 from src/unittest/srpe_filter.cpp:6:
/ebio/abt6_projects9/abt6_software/bin/vg/include/lru_cache.h:52:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<Impl> impl_;
          ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/c++/5/iomanip:43,
                 from src/unittest/catch.hpp:1458,
                 from src/unittest/srpe_filter.cpp:5:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
. ./source_me.sh && g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -g -c -o obj/unittest/phase_duplicator.o src/unittest/phase_duplicator.cpp -I/ebio/abt6_projects9/abt6_software/bin/vg/include -I. -I/ebio/abt6_projects9/abt6_software/bin/vg/src -I/ebio/abt6_projects9
/abt6_software/bin/vg/src/unittest -I/ebio/abt6_projects9/abt6_software/bin/vg/src/subcommand -I/ebio/abt6_projects9/abt6_software/bin/vg/cpp -I/ebio/abt6_projects9/abt6_software/bin/vg/include/dynamic -I/ebio/abt6_projects9/abt6_software/bin/vg/include/sonLib -I/
ebio/abt6_projects9/abt6_software/bin/vg/include/gcsa -ggdb -L/ebio/abt6_projects9/abt6_software/bin/vg/lib -lvcflib -lgssw -lssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lgcsa2 -lxg -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lraptor2 -lsupbub -lsdsl -l
pinchesandcacti -l3edgeconnected -lsonlib -lfml -Wl,-rpath,/ebio/abt6_projects9/abt6_software/bin/vg/lib -lrocksdb  -lpthread -lrt -lsnappy -lz -lbz2
src/unittest/phase_duplicator.cpp: In function ‘void vg::unittest::____C_A_T_C_H____T_E_S_T____0()’:
src/unittest/phase_duplicator.cpp:74:46: error: no matching function for call to ‘xg::XG::insert_threads_into_dag(std::vector<std::vector<xg::XG::ThreadMapping> >&, <brace-enclosed initializer list>)’
     index.insert_threads_into_dag(threads, {});
                                              ^
In file included from src/unittest/../phase_duplicator.hpp:13:0,
                 from src/unittest/phase_duplicator.cpp:8:
/ebio/abt6_projects9/abt6_software/bin/vg/include/xg.hpp:252:10: note: candidate: void xg::XG::insert_threads_into_dag(const std::vector<std::vector<xg::XG::ThreadMapping> >&)
     void insert_threads_into_dag(const vector<thread_t>& t);
          ^
/ebio/abt6_projects9/abt6_software/bin/vg/include/xg.hpp:252:10: note:   candidate expects 1 argument, 2 provided
src/unittest/phase_duplicator.cpp: In function ‘void vg::unittest::____C_A_T_C_H____T_E_S_T____9()’:
src/unittest/phase_duplicator.cpp:197:46: error: no matching function for call to ‘xg::XG::insert_threads_into_dag(std::vector<std::vector<xg::XG::ThreadMapping> >&, <brace-enclosed initializer list>)’
     index.insert_threads_into_dag(threads, {});
                                              ^
In file included from src/unittest/../phase_duplicator.hpp:13:0,
                 from src/unittest/phase_duplicator.cpp:8:
/ebio/abt6_projects9/abt6_software/bin/vg/include/xg.hpp:252:10: note: candidate: void xg::XG::insert_threads_into_dag(const std::vector<std::vector<xg::XG::ThreadMapping> >&)
     void insert_threads_into_dag(const vector<thread_t>& t);
          ^
/ebio/abt6_projects9/abt6_software/bin/vg/include/xg.hpp:252:10: note:   candidate expects 1 argument, 2 provided
src/unittest/phase_duplicator.cpp: In function ‘void vg::unittest::____C_A_T_C_H____T_E_S_T____14()’:
src/unittest/phase_duplicator.cpp:271:46: error: no matching function for call to ‘xg::XG::insert_threads_into_dag(std::vector<std::vector<xg::XG::ThreadMapping> >&, <brace-enclosed initializer list>)’
     index.insert_threads_into_dag(threads, {});
                                              ^
In file included from src/unittest/../phase_duplicator.hpp:13:0,
                 from src/unittest/phase_duplicator.cpp:8:
/ebio/abt6_projects9/abt6_software/bin/vg/include/xg.hpp:252:10: note: candidate: void xg::XG::insert_threads_into_dag(const std::vector<std::vector<xg::XG::ThreadMapping> >&)
     void insert_threads_into_dag(const vector<thread_t>& t);
          ^
/ebio/abt6_projects9/abt6_software/bin/vg/include/xg.hpp:252:10: note:   candidate expects 1 argument, 2 provided
Makefile:596: recipe for target 'obj/unittest/phase_duplicator.o' failed
make: *** [obj/unittest/phase_duplicator.o] Error 1

Any ideas?
F

**Comment by ekg** [comment]
This is a fresh build, correct?

**Comment by ChriKub** [comment]
Yes.

**Comment by adamnovak** [comment]
@fbemm What was the resolution?
