### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [vgteam/vg#854]
I would like to point out that identifiers like “[`VG__BIN2ASCII_H__`](https://github.com/vgteam/vg/blob/b3c680233a7d851c9dce4ab76881c8994e9da873/src/bin2ascii.h#L8 "Update candidate")” and “[`VG__JSON2PB_H__`](https://github.com/vgteam/vg/blob/b3c680233a7d851c9dce4ab76881c8994e9da873/src/json2pb.h#L8 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by adamnovak** [comment]
Those IDs were `__BIN2ASCII_H__` and `__JSON2PB_H__` in the library we pulled in. In addition to prefixing them with VG, we probably ought to make them standards-compliant by dropping the double underscores, which are supposed to be reserved for the compiler's use.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/vgteam/vg/commit/c5154eb20756dad1ab9930345c5f93c6396dd7a0 "Remove double underscores which are reserved for the compiler").
