### ISSUE TITLE
Map and align disagree on how to use the full length bonus

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#863]
Here's a graph where map and align give different scores with the default full length bonus of 5, but the same score when it's set to 0. I think the problem is that map is not applying the bonus at each end (requiring both ends to be full length to get any bonus), while align is applying it per-end.

```
[anovak@kolossus bonus-problem]$ vg index -x primary-part.xg -g primary-part.gcsa primary-part.vg -k 16
[anovak@kolossus bonus-problem]$ vg map -s $(cat read.txt) -x primary-part.xg -g primary-part.gcsa -j | jq '.score'
89
[anovak@kolossus bonus-problem]$ vg align -s $(cat read.txt) primary-part.vg -j | jq '.score'
94
[anovak@kolossus bonus-problem]$ vg map -s $(cat read.txt) -x primary-part.xg -g primary-part.gcsa -j --full-l-bonus 0 | jq '.score'
89
[anovak@kolossus bonus-problem]$ vg align -s $(cat read.txt) primary-part.vg -j --full-l-bonus 0 | jq '.score'
89
[anovak@kolossus bonus-problem]$ 
```

[bonus-problem.tar.gz](https://github.com/vgteam/vg/files/1149830/bonus-problem.tar.gz)

**Comment by jeizenga** [comment]
In my refactor, I made some changes to the full length bonus. This was probably caused by something I did.

Now, instead of having the full length bonus as an argument to alignment methods, I made it a member variable given to the constructor. Aligners should automatically apply the full length bonus whenever it's meaningful (both ends on GSSW alignment, one end on pinned alignment, neither for global alignment).

Just an intuition, it might be that the defaults on the arguments are interacting poorly. The constructor has default arguments for score parameters, and the align methods have a default argument for printing matrices. I've seen it get confused by this previously and just case arguments intended for one parameter into the other.

**Comment by adamnovak** [comment]
It looks like this difference is a deliberate choice by @ekg not to use the full length bonus in the scores output by the mapper (even though it's included by the aligner).

See the commits around https://github.com/vgteam/vg/commits/master?before=258cfdf74c2830c75c1af2a80e91a165bba5bd50+35 and in particular https://github.com/vgteam/vg/commit/7344458b2269a1277ce6b7639cde620c28369750

I definitely liked it with the score bonuses in the score; maybe we need two scores reported (actual alignment DP score and score that describes how good the alignment is), so we can tell that the aligner is making the correct decisions? We could also just tack the end bonuses back on in the test code when appropriate, but that seems like pretty strong coupling.

**Comment by glennhickey** [comment]
If the bonus is always added, couldn't we then end up with scores higher
than bwa for the same alignment?  Say a 100bp perfectly matched read
getting 105 in vg vs 100 in bwa.

**Comment by adamnovak** [comment]
Yep. We would actually get 110 for 100 perfect matches, because it applies
on both ends.

It looks like BWA actually structures it as a "softclip penalty", at least
in the help for the bwa mem I have.

Maybe we should make it work like that too.

**Comment by glennhickey** [comment]
We're going to go nuts comparing against bwa with different score
functions, so it'd be great to somehow get this into a penalty in vg too (I
say this with blissful ignorance of how hard that would be to implement).

I also think the penalty makes more intuitive sense, where we only award
matches and everything else is a subtraction.

**Comment by ekg** [comment]
I didn't think that bwa mem is including the penalty in the score. But I
could be mistaken.

**Comment by glennhickey** [comment]
I think you're right.  So Adam's strip-bonus option should give the same
score as bwa.

I'm still pretty sure I had a bunch of cases where the bonus seemed to be
applied differently between bwa and vg (vg aligning a mismatch at the end
of the read but bwa leaving the gap).  I will retest on the latest mapper
and make a specific issue if this is the still the case.

**Comment by adamnovak** [comment]
OK, so here's what BWA MEM does with a full matching read, a read with one terminal mismatch, a read with a terminal mismatch on each side, a read with a central mismatch and a softclipping read.

```
read	0	ref	67	60	66M	*	0	0	ATACACAATTTACCGCATCTAGACTTAACTGAGATATTACCATAGATGACTAGCCATTCCTCTAGT	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:0	MD:Z:66	AS:i:66	XS:i:0
single	0	ref	67	60	66M	*	0	0	ATACACAATTTACCGCATCTAGACTTAACTGAGATATTACCATAGATGACTAGCCATTCCTCTAGG	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:1	MD:Z:65T0	AS:i:65	XS:i:0
both	0	ref	67	60	66M	*	0	0	CTACACAATTTACCGCATCTAGACTTAACTGAGATATTACCATAGATGACTAGCCATTCCTCTAGG	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:2	MD:Z:0A64T0	AS:i:64	XS:i:0
central	0	ref	67	60	66M	*	0	0	ATACACAATTTACCGCATCTAGACTGAACTGAGATATTACCATAGATGACTAGCCATTCCTCTAGT	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:1	MD:Z:25T40	AS:i:61	XS:i:0
dangle	0	ref	67	60	48M18S	*	0	0	ATACACAATTTACCGCATCTAGACTTAACTGAGATATTACCATAGATGGAAGAGTATCCTCCACAA	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:0	MD:Z:48	AS:i:48	XS:i:0
```
66 perfect matches gets you a score of 66 = 66 * 1 point per match.

65 matches and 1 mismatch comes out as 65 points (= 65 * 1 point per match) if the mismatch is on the end of the read, and 61 points (= 65 * 1 point per match - 1 * 4 points per mismatch) if it's in the middle.

I've played around with the softclip penalties a bit, and it looks like BWA MEM is *scoring* the softclipping alignment, with no bonus or penalty, no matter what actual alignment it reports. If the softclip penalty is high enough, you can get a quite different optimal alignment from the softclip-using alignment (I got a `48M14I4M` for the dangling-end read), but it still somehow finds and reports the score of the optimal softclipping alignment.

I'm not quite sure how we would go about replicating that behavior. We might want to do all our alignments without the softclip penalty/full length bonus first to get the scores, and then if they softclip realign with the bonus and use the new alignment with the old score.

**Comment by glennhickey** [comment]
Regardless of the scoring, it's doing something to not align that mismatch
at the end of the read, despite the mismatch penalty being lower than the
softclip penalty.

**Comment by adamnovak** [comment]
No, BWA *is* aligning the mismatch at the end of the read. The CIGAR is `66M` for everything except the last read with 18 random bases at the end.

If I up the mismatch cost to be as much as or more than the softclip penalty, I can force the reads with mismatches at the end to report softclips, but only the read with the mismatch in the middle has its score go down.

**Comment by adamnovak** [comment]
I think our disagreement with BWA is maybe a separate issue or something to discuss on the Tuesday call.

Now we have a better grasp of why `vg map` and `vg align` report different scores; the mapper doesn't want to include the bonus in the score, while the aligner works at a lower level and does include the bonus.

Do we still want to unify their behavior? That might take the form of moving the rescoring function (and the bonus stripping) over into the aligner, so that `vg align` can also do it.

**Comment by jeizenga** [comment]
May or may not make the Tuesday meeting on account of the conference, but imo that behavior is weird and bad. The idea of reporting one alignment and then scoring a completely different alignment is very strange to me. If that's what BWA is doing, I don't think we should try to match BWA.
