### ISSUE TITLE
Alignment scores get worse when turning on full length bonus

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#865]
This is probably related to #863.

When you turn on `--full-l-bonus 5` for this read, the score from `vg map` actually drops, because it's unwilling to use a softclip.

I think the full length bonus is not being added to the score, but is being accounted for in the dynamic programming.

```
[anovak@kolossus got-worse]$ vg map -s $(cat read.txt) -x snp1kg-part.xg -g snp1kg-part.gcsa -j --full-l-bonus 0 | jq .score
89
[anovak@kolossus got-worse]$ vg map -s $(cat read.txt) -x snp1kg-part.xg -g snp1kg-part.gcsa -j --full-l-bonus 5 | jq .score
86
```

[got-worse.tar.gz](https://github.com/vgteam/vg/files/1149866/got-worse.tar.gz)

This came up in my quest to enforce that reads aligned against larger graphs have their scores go up, because this read was showing as getting a worse score in snp1kg (where it won't take the softclip) than in primary (where it does take the softclip).

@ekg did you do something with end bonuses when changing the aligner around?

**Comment by jeizenga** [comment]
I know in the past there were steps that rescored alignments without taking into account the full length bonus.

FWIW, this is why I've slowly been moving everything that has to do with scores into the Aligner classes. If there's a rescoring function, it should be in the same aligner that scored the alignments in the first place so that the scoring is consistent.

**Comment by ekg** [comment]
Agreed.

In any case it seems to me that the score should affect the DP but not the
final score. This is a reflection of testing and some discussion with
@richarddurbin.

**Comment by adamnovak** [comment]
@ekg Can you elaborate on why you would not want the full length bonus to affect the actual alignment score?

If we don't account for it, we will have cases where the aligner prefers an alignment with a worse reported score over an available alignment with a better reported score. That's very bad for testability; it could result in things like a secondary alignment having a better score than a primary alignment, and makes my attempt to ensure that scores go up when we move from the primary graph to a superset graph fundamentally misguided, because some reads would be expected to find better alignments with lower scores.

**Comment by jeizenga** [comment]
My intuition is also that we should keep the bonus in the score. It makes statistical sense as a prior odds that the alignment is full length, and I can think of some slightly nasty things that could happen if we try to use the reduced score as a log likelihood.
