### ISSUE TITLE
Refactor Jenkins input to HTTPS

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#868]
We shouldn't need to connect to S3 with credentials to pull down the public test input data.

It might also be nice if it didn't try to upload the baseline unless we were actually on Jenkins.

**Comment by glennhickey** [comment]
Good idea. Toil uses BUILD_NUMBER to check this FWIW
https://github.com/BD2KGenomics/toil/blob/master/Makefile#L237-L240
