### ISSUE TITLE
Implement restricted alternate traceback logic in gssw and BandedGlobalAligner

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#869]
Via @jeizenga:

When my current code looks for sub-optimal tracebacks, it finds any and all of them. I want to be able to restrict the sub-optimal tracebacks to only tracebacks that follow different node paths in graph (rather than just having different edits to a node). Basically, this just means adding extra conditions to if statements, but there are a lot of them. Might be helpful to discuss this one in person with someone.

**Comment by adamnovak** [comment]
@jeizenga Is this something you have done? Or something you still intend to do?

**Comment by jeizenga** [comment]
I did it in GSSW, I think. In the process I realized some problems with this approach, so the code path is currently deactivated. I don't think I'm going to go back to this anytime soon, if ever.
