### ISSUE TITLE
Coordinate log miner design

### ISSUE THREAD

**Issue by adamnovak** [vgteam/vg#886]

**Comment by ekg** [comment]
What is the log miner?

**Comment by adamnovak** [comment]
Benedict wants a bot that will look at the statistics coming out of the
Jenkins tests and make nice plots and summary reports, so we don't have to
go digging through the Jenkins web UI to see how a PR will affect read
mapping performance and so on. That's the project Glenn and I are going to
work on this week.

It's going to accomplish this by looking through the test output, hence the
name log miner.
