### ISSUE TITLE
VG map performance very slow on wgs reads

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#999]
@ekg 
I've been using a docker version of vg running version `v1.5.0-824-gcc531354-t73-run` as of 8/4/2017 from `quay.io/vgteam/vg:v1.5.0-824-gcc531354-t73-run` on a whole genome set of reads and the mapping is taking forever. Almost an order of magnitude longer.

The first mapping that was done using vg version `v1.5.0-511-g6aebc5d4-t65-run` as of 7/14/2017 on a paired-end set of reads of size 35GB and 40GB in size which took about 36 hours (1.5 days). 

Running vg version `v1.5.0-824-gcc531354-t73-run` as of 8/4/2017 on the same sample on the same pair of reads has so far taken about 136 hours (5.6 days) to process HALF of the total amount of reads. That's an estimate of about 272 hours (11.3 days!) to do all of the mapping.

**Comment by ekg** [comment]
We've improved runtime by a factor of 4.
